# -*- coding: utf-8 -*-
# Nieuwe Antwerpse wijken (kind "wijk", meestal binnen 20 tot 30 minuten), nieuwe Vlaamse steden
# (kind "stad", meestal binnen 45 tot 75 minuten) en de regio-hub "provincie-antwerpen".

AREAS = [
    # ------------------------------------------------------------------ wijken
    {
        "slug": "linkeroever",
        "name": "Linkeroever",
        "kind": "wijk",
        "title": "Lachgas Linkeroever | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen op Linkeroever? Tanks en patronen bezorgd aan de overkant van de Schelde, van Sint-Anna tot Regatta, meestal binnen 20 tot 30 minuten.",
        "h1": "Lachgas Linkeroever",
        "lead": "Aan de overkant van de Schelde, tussen het Sint-Annabos en het Galgenweel: lachgas aan huis, geregeld met één WhatsApp-bericht en betaald bij levering.",
        "intro": [
            "Linkeroever is het deel van het district Antwerpen aan de westelijke oever van de Schelde, recht tegenover de kaaien van het centrum. De wijk bestaat grotendeels uit de hoogbouw langs de Blancefloerlaan, de Halewijnlaan en de Charles De Costerlaan, aangevuld met de nieuwere woonbuurt Regatta aan het Galgenweel en de groene rand van het Sint-Annabos en het Sint-Annastrand. Woont u in een appartement op de twaalfde verdieping of in een rijhuis bij het Frederik van Eedenplein, dan komen wij tot aan uw deur. U stuurt ons een WhatsApp-bericht met uw bestelling en adres, wij bevestigen en laten weten wanneer de bezorger de tunnel inrijdt.",
            "Voor onze bezorgers is de rivier geen obstakel: vanuit het centrum nemen zij de Waaslandtunnel of, komend van de Ring, de Kennedytunnel richting Zwijndrecht en de afrit Linkeroever. Buiten de spitsuren is dat een kwestie van minuten, maar bij files aan de tunnelmonden of werken aan de Oosterweelverbinding kan het langer duren, en daarom rekenen wij op meestal 20 tot 30 minuten. De trams 3, 5, 9 en 15 rijden via de premetrotunnel onder de Schelde naar de haltes op Linkeroever en de P+R aan de Blancefloerlaan; fietsers en voetgangers gebruiken de Sint-Annatunnel. U hoeft echter nergens heen, want wij komen naar u.",
            "Een avond met vrienden in een flat aan de Halewijnlaan, een housewarming in Regatta of een gezellig samenzijn na een zomerdag aan het Sint-Annastrand: kies het formaat dat bij uw gezelschap past. Het compacte 2KG-formaat past in elke keuken, voor meer mensen zijn er de 4KG en 10KG. Alle tanks, crackers en slagroompatronen vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen alleen aan meerderjarigen en vragen bij twijfel naar uw identiteitskaart. Afrekenen doet u aan de deur, cash of via Payconiq. Neem vooraf ook even onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a> door.",
        ],
        "wijken": "Blancefloerlaan, Halewijnlaan, Charles De Costerlaan, Frederik van Eedenplein, Regatta, Galgenweel, Sint-Annabos, Sint-Annastrand, Europark, Middenvijver",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Kost het extra tijd dat jullie door de tunnel moeten?", "Normaal niet: de Waaslandtunnel brengt onze bezorger in enkele minuten van de Tunnelplaats naar de Blancefloerlaan. Alleen bij zware files aan de Kennedytunnel of bij afgesloten tunnelbuizen kan het naar het einde van de indicatie van 20 tot 30 minuten lopen, en dan verwittigen wij u via WhatsApp."],
            ["Leveren jullie ook in de torens aan de Blancefloerlaan en Europark?", "Ja, ook in de hoogbouw. Onze bezorger belt aan bij de inkomhal, u laat hem binnen en hij brengt de bestelling tot aan uw appartementsdeur, hoe hoog u ook woont. Zet in uw bericht het nummer van het appartement of de verdieping erbij."],
            ["Komen jullie tot aan het Sint-Annastrand of het Sint-Annabos?", "Wij leveren aan woonadressen op Linkeroever, niet op het strand, in het bos of op een parking. Woont u in de straten vlak bij het Sint-Annabos of in Regatta aan het Galgenweel, dan komen wij gewoon tot aan uw voordeur."],
        ],
        "nearby": ["antwerpen-centrum", "zwijndrecht", "kruibeke"],
        "lat": 51.2185, "lon": 4.3730,
    },
    {
        "slug": "antwerpen-zuid",
        "name": "Antwerpen-Zuid",
        "kind": "wijk",
        "title": "Lachgas Antwerpen-Zuid | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen op het Zuid? Tanks en patronen bezorgd rond de Zuiderdokken, het KMSKA en Nieuw Zuid, meestal binnen 20 tot 30 minuten. Enkel 18+.",
        "h1": "Lachgas Antwerpen-Zuid",
        "lead": "Van de Waalsekaai tot Nieuw Zuid: lachgas discreet aan huis geleverd op het Zuid, besteld via WhatsApp en afgerekend bij levering.",
        "intro": [
            "Het Zuid ligt pal ten zuiden van de historische binnenstad, ingesloten tussen de Scheldekaaien, de Amerikalei als deel van de Leien en de Bolivarplaats met het justitiepaleis. Het is de buurt van het KMSKA aan de Leopold de Waelplaats, van de cafés en restaurants rond de Marnixplaats en de Gedempte Zuiderdokken, van de lofts in de Vlaamsekaai en de Waalsekaai en van de nieuwe appartementen in Nieuw Zuid richting Konijnenwei. Overal in deze buurt komen wij aan huis. Stuur ons via WhatsApp welke tank of welke producten u wenst en op welk adres, dan bevestigen wij en spreken wij een moment af.",
            "Onze bezorgers bereiken het Zuid vanuit het centrum via de Amerikalei of de kaaien, en vanaf de Ring via de afrit Antwerpen-Zuid aan de Bolivarplaats. De afstanden zijn klein, maar het parkeren in de smalle straten rond de Zuiderdokken vraagt soms wat tijd, zeker op vrijdag- en zaterdagavond wanneer de horeca vol zit. Daarom houden wij het op meestal 20 tot 30 minuten. De trams 1, 4, 12 en 24 stoppen op de Bolivarplaats en in de Nationalestraat, en het Centraal Station ligt op een kwartier met de tram. Voor u maakt het geen verschil: wij brengen uw bestelling tot aan de deur.",
            "Een etentje in een herenhuis in de Verschansingsstraat, een afterwork met collega's in een loft aan de Vlaamsekaai of een gezellige avond in een nieuw appartement in Nieuw Zuid: het formaat van de tank hangt af van het aantal gasten. De 2KG volstaat voor een kleine groep, de 4KG en 10KG zijn er voor wie meer mensen verwacht. Bekijk alle formaten en ook crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar of ouder en controleren dat waar nodig. U betaalt bij levering, cash of met Payconiq. Op <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u hoe u verantwoord met lachgas omgaat.",
        ],
        "wijken": "Gedempte Zuiderdokken, Marnixplaats, Leopold de Waelplaats, Vlaamsekaai, Waalsekaai, Bolivarplaats, Nieuw Zuid, Verschansingsstraat, Brederodewijk, Scheldekaaien",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Kunnen jullie wel parkeren in de straten rond de Zuiderdokken?", "Onze bezorger kent de buurt en stopt kort voor uw deur om de bestelling af te geven; hij hoeft geen plaats te zoeken voor langere tijd. Op drukke avonden kan het zoeken naar een plek de levering iets vertragen, wat binnen onze indicatie van meestal 20 tot 30 minuten valt."],
            ["Bezorgen jullie ook in Nieuw Zuid en aan de Brederodewijk?", "Ja, Nieuw Zuid tussen de Ledeganckkaai en de Konijnenwei hoort er volledig bij, net als de Brederodewijk aan de andere kant van de Amerikalei. Woont u in een van de nieuwe woontorens, geef dan het appartementsnummer mee in uw WhatsApp-bericht."],
            ["Leveren jullie aan een café of restaurant op het Zuid?", "Wij bezorgen aan particuliere adressen en, na afspraak, aan horecazaken die slagroompatronen of een tank voor culinair gebruik nodig hebben. Voor die laatste vragen neemt u best vooraf contact op via WhatsApp, dan bekijken wij wat mogelijk is."],
        ],
        "nearby": ["antwerpen-centrum", "kiel", "hoboken"],
        "lat": 51.2070, "lon": 4.3940,
    },
    {
        "slug": "eilandje",
        "name": "Het Eilandje",
        "kind": "wijk",
        "title": "Lachgas Het Eilandje | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen op het Eilandje? Tanks en patronen aan huis rond het MAS, de Cadixwijk en het Kattendijkdok, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Het Eilandje",
        "lead": "Van de Hanzestedenplaats tot de Cadixwijk: lachgas geleverd aan uw deur in de oude havenbuurt, besteld via WhatsApp en betaald bij levering.",
        "intro": [
            "Het Eilandje is de voormalige havenwijk ten noorden van de binnenstad, tussen de Schelde, de Italiëlei en Park Spoor Noord. Rond het Bonapartedok en het Willemdok met de jachthaven staan het MAS en de omgebouwde pakhuizen van de Montevideowijk, met het Red Star Line Museum aan de Rijnkaai. Verder naar het Kattendijkdok ligt de Cadixwijk, waar de laatste jaren veel nieuwe appartementen zijn gebouwd. In al die buurten bezorgen wij aan huis. U stuurt een WhatsApp-bericht met uw bestelling en adres, wij bevestigen de prijs vooraf en laten weten wanneer onze bezorger vertrekt.",
            "Vanuit het stadscentrum rijden onze bezorgers over de Italiëlei en de Londenstraat of langs de kaaien naar het Eilandje; komen zij van de Ring, dan via de afrit Antwerpen-Noord en de Noorderlaan. Het zijn korte ritten, maar de bruggen over de dokken en het drukke verkeer aan de Londen-Amsterdamstraat vragen soms wat geduld, waardoor wij op meestal 20 tot 30 minuten rekenen. De trams 7 en 24 rijden door de wijk tot aan het MAS en het Havenhuis, en het Centraal Station ligt op wandelafstand van de Cadixwijk. Dat is handig voor uw gasten; voor uw bestelling hoeft u zelf de deur niet uit.",
            "Een appartement met zicht op het Willemdok, een loft in een oud pakhuis in de Montevideowijk of een nieuwbouwflat in de Cadixwijk: kies een tankformaat op maat van uw gezelschap. Voor een rustige avond met enkele vrienden is de 2KG het meest praktische formaat, voor grotere groepen zijn er de 4KG en de 10KG. U vindt ze samen met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Bestellen kan uitsluitend als u 18 jaar of ouder bent; wij vragen zo nodig uw identiteitskaart. Betalen gebeurt bij levering, cash of via Payconiq. Lees vooraf zeker ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a>.",
        ],
        "wijken": "Hanzestedenplaats, Bonapartedok, Willemdok, Montevideowijk, Cadixwijk, Kattendijkdok, Londenstraat, Rijnkaai, Droogdokkeneiland, Park Spoor Noord",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de nieuwe gebouwen van de Cadixwijk?", "Ja, de hele Cadixwijk tussen het Kattendijkdok en de Kempenstraat hoort bij ons bezorggebied. Veel gebouwen daar hebben een gemeenschappelijke inkomhal; vermeld daarom het appartementsnummer in uw bericht, zodat onze bezorger meteen juist aanbelt."],
            ["Kunnen jullie leveren aan een boot in de jachthaven van het Willemdok?", "Wij bezorgen aan woonadressen met een gewone voordeur, niet op een steiger of aan boord. Woont u aan het Willemdok of het Bonapartedok, dan komen wij tot aan de deur van uw gebouw."],
            ["Is het Eilandje ook ’s nachts bereikbaar voor jullie?", "Ja, ook laat op de avond en ’s nachts rijden wij naar het Eilandje; er zijn dan zelfs minder files aan de Londenstraat. Hoe nachtlevering werkt en wat u mag verwachten, leest u op onze pagina over <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["antwerpen-centrum", "luchtbal", "merksem"],
        "lat": 51.2310, "lon": 4.4070,
    },
    {
        "slug": "luchtbal",
        "name": "Luchtbal",
        "kind": "wijk",
        "title": "Lachgas Luchtbal | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Luchtbal? Tanks en patronen aan huis tussen de Noorderlaan en de spoorlijn naar Essen, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Luchtbal",
        "lead": "Lachgas aan huis in Luchtbal, van de Canadablokken tot de Havanastraat: één WhatsApp-bericht volstaat en u betaalt pas bij levering.",
        "intro": [
            "Luchtbal is een woonwijk in het noorden van het district Antwerpen, ingeklemd tussen de Noorderlaan en het havengebied aan de westkant, de spoorlijn naar Essen aan de oostkant en de Groenendaallaan richting Merksem in het zuiden. De wijk is bekend om haar sociale woningbouw uit de vorige eeuw, zoals de Canadablokken en de flats langs de Columbiastraat en de Manchesterlaan, met het cultuurcentrum als ontmoetingsplek. Overal in deze straten komen wij tot aan uw deur. Bestellen gaat via WhatsApp: u stuurt wat u nodig heeft en uw adres, wij bevestigen en geven aan wanneer wij onderweg zijn.",
            "Vanuit het centrum bereiken onze bezorgers Luchtbal via de Noorderlaan of de Groenendaallaan, en vanaf de Ring via de A12 en de afrit Luchtbal of Ekeren. Het is een vlotte route, al kan het havenverkeer op de Noorderlaan in de ochtend- en avondspits voor oponthoud zorgen; daarom spreken wij van meestal 20 tot 30 minuten. Het station Antwerpen-Luchtbal ligt op de lijn naar Essen en Roosendaal, en tram 6 heeft zijn eindhalte aan de P+R bij de Havanastraat. Dat openbaar vervoer is er voor u; onze bezorger komt met de wagen tot voor uw voordeur.",
            "Een verjaardag in een flat aan de Columbiastraat, een avond met de buren in een woning bij het Lambrechtshoekenpark of een rustig samenzijn in een appartement langs de Manchesterlaan: voor elke groepsgrootte is er een passend formaat. De 2KG is compact en volstaat voor een klein gezelschap, voor meer gasten kiest u de 4KG of de 10KG. Alle tanks en toebehoren vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen enkel aan 18-plussers en controleren de leeftijd wanneer dat nodig is. Afrekenen gebeurt aan de deur, cash of via Payconiq. Op <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u hoe u verstandig met een tank omgaat.",
        ],
        "wijken": "Canadablokken, Columbiastraat, Manchesterlaan, Havanastraat, Santiagostraat, Groenendaallaan, Noorderlaan, Lambrechtshoeken, Station Luchtbal",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Leveren jullie in alle blokken van Luchtbal, ook in de hoge flats?", "Ja, in de Canadablokken en in de hogere torens langs de Columbiastraat en de Manchesterlaan bezorgen wij aan de appartementsdeur. Vermeld het nummer van uw appartement en de verdieping in uw WhatsApp-bericht, dan belt onze bezorger meteen bij de juiste bel aan."],
            ["Komen jullie ook aan de kant van Rozemaai en de Ekerse grens?", "De noordelijke rand van Luchtbal richting Rozemaai en de Ekersesteenweg hoort gewoon bij ons bezorggebied, net als het aangrenzende <a href=\"/bezorggebied/ekeren/\">Ekeren</a>. Onze bezorger kiest de kortste weg, zodat de levertijd ook daar meestal binnen 20 tot 30 minuten blijft."],
            ["Hoe weet ik wanneer de bezorger aan de Havanastraat aankomt?", "Na uw bestelling krijgt u via WhatsApp een bevestiging met een geschatte levertijd, en een nieuw bericht zodra onze bezorger vertrekt. Vlak voor hij in Luchtbal aankomt, stuurt hij nog een kort bericht, zodat u klaarstaat aan de deur."],
        ],
        "nearby": ["merksem", "ekeren", "eilandje"],
        "lat": 51.2515, "lon": 4.4290,
    },
    {
        "slug": "kiel",
        "name": "Kiel",
        "kind": "wijk",
        "title": "Lachgas Kiel | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen op het Kiel? Tanks en patronen aan huis rond de Abdijstraat en het Olympisch Stadion, meestal binnen 20 tot 30 minuten. Enkel 18+.",
        "h1": "Lachgas Kiel",
        "lead": "Van de Abdijstraat tot de Tentoonstellingswijk: lachgas aan huis op het Kiel, besteld via WhatsApp en betaald wanneer wij aanbellen.",
        "intro": [
            "Het Kiel is de zuidelijke wijk van het district Antwerpen, tussen de Scheldekaaien en de oude Petroleum Zuid-site in het westen, de Boomsesteenweg en de Jan De Voslei in het oosten, en de grens met Hoboken en Wilrijk in het zuiden. De winkelstraat Abdijstraat, het Olympisch Stadion van Beerschot, het Kielpark en de ruimere lanen van de Tentoonstellingswijk rond Antwerp Expo geven de buurt haar gezicht. In al die straten bezorgen wij aan huis. Een WhatsApp-bericht met uw bestelling en adres is genoeg: wij bevestigen en geven door wanneer onze bezorger bij u is.",
            "Onze bezorgers rijden vanuit het centrum over de Amerikalei en de Jan De Voslei naar het Kiel, of nemen vanaf de Ring de afrit Antwerpen-Zuid of de Boomsesteenweg. Het gaat vlot, maar rond de Abdijstraat en op wedstrijddagen aan het Kielstadion is het soms druk, en op die momenten ligt de levertijd eerder aan het einde van onze indicatie van meestal 20 tot 30 minuten. De trams 2 en 4 rijden door de wijk richting Hoboken en tram 6 heeft zijn eindhalte aan de Olympiade; wie van het Centraal Station komt, is in een kwartier ter plaatse. Voor uw bestelling hoeft u niets te doen behalve de deur openen.",
            "Een feestje in een appartement aan de Emiel Vloorsstraat, een avond met vrienden in een rijhuis in de De Bosschaertstraat of een samenzijn in een ruime woning van de Tentoonstellingswijk: het aantal gasten bepaalt welk formaat u best neemt. Voor een klein gezelschap is de 2KG het handigst, voor grotere groepen zijn er de 4KG en 10KG. Ontdek alle formaten, crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan meerderjarigen en vragen bij twijfel een identiteitskaart. Betalen kan cash of via Payconiq op het moment van levering. Bekijk vooraf ook onze tips over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Abdijstraat, Olympisch Stadion, Kielpark, Tentoonstellingswijk, Emiel Vloorsstraat, De Bosschaertstraat, Jan De Voslei, Sint-Bernardsesteenweg, Olympiade, Blue Gate",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Leveren jullie ook op een wedstrijddag van Beerschot?", "Ja, maar rond het Olympisch Stadion zijn er dan verkeersmaatregelen en afgesloten straten, waardoor onze bezorger soms moet omrijden. Wij melden het vooraf wanneer dat de levertijd beïnvloedt; meestal blijft het binnen 20 tot 30 minuten."],
            ["Hoort de Tentoonstellingswijk bij het Kiel of bij Wilrijk voor jullie?", "Voor ons maakt die grens niets uit: de Tentoonstellingswijk rond de Jan Van Rijswijcklaan en Antwerp Expo bezorgen wij aan dezelfde indicatie als de rest van het Kiel. Ook de straten die net over de grens in <a href=\"/bezorggebied/wilrijk/\">Wilrijk</a> liggen, komen wij zonder probleem bedienen."],
            ["Kan ik na mijn bestelling nog het adres op het Kiel wijzigen?", "Zolang onze bezorger niet vertrokken is, past u via WhatsApp eenvoudig het adres aan, bijvoorbeeld van de Abdijstraat naar een vriend in de Emiel Vloorsstraat. Is hij al onderweg, dan bekijken wij samen of een kleine omweg binnen het Kiel nog haalbaar is."],
        ],
        "nearby": ["hoboken", "antwerpen-zuid", "wilrijk"],
        "lat": 51.1905, "lon": 4.3860,
    },
    {
        "slug": "zurenborg",
        "name": "Zurenborg",
        "kind": "wijk",
        "title": "Lachgas Zurenborg | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Zurenborg? Tanks en patronen aan huis rond de Dageraadplaats en de Cogels-Osylei, meestal binnen 20 tot 30 minuten. Enkel 18+.",
        "h1": "Lachgas Zurenborg",
        "lead": "Tussen de Dageraadplaats en het station Antwerpen-Berchem: lachgas discreet aan huis in Zurenborg, via WhatsApp besteld en bij levering betaald.",
        "intro": [
            "Zurenborg ligt op de grens van het district Antwerpen en Berchem, ten oosten van de Leien en net binnen de Singel en de Ring, met het station Antwerpen-Berchem als zuidelijke buur. De wijk staat bekend om de art-nouveauhuizen van de Cogels-Osylei, de Transvaalstraat en de Waterloostraat, en om de gezellige Dageraadplaats met haar terrassen. Rond de Draakplaats en het Tramplein wonen veel jonge gezinnen en studenten. In al die straten bezorgen wij tot aan uw deur. Stuur ons via WhatsApp uw bestelling en adres; wij bevestigen meteen en melden wanneer onze bezorger vertrekt.",
            "Vanuit het centrum rijden onze bezorgers over de Plantin en Moretuslei of de Mechelsesteenweg naar Zurenborg, en komend van de Ring nemen zij de afrit Berchem of Borgerhout. De ritten zijn kort, maar de wijk heeft veel eenrichtingsstraten en weinig parkeerplaatsen, zodat wij op meestal 20 tot 30 minuten rekenen. Tram 11 rijdt door de wijk langs de Draakplaats, de trams 9 en 15 volgen de Plantin en Moretuslei, en de treinen in het station Antwerpen-Berchem brengen u in enkele minuten naar het Centraal Station. Wij komen evenwel met de wagen en bellen bij u aan.",
            "Een etentje in een herenhuis aan de Cogels-Osylei, een verjaardag in een appartement bij de Dageraadplaats of een avond met medestudenten in een kot aan de Draakplaats: kies een tank die bij het aantal gasten past. De 2KG is het meest compacte formaat, de 4KG en 10KG zijn er voor grotere groepen. Alle formaten, crackers en slagroompatronen vindt u terug in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen enkel aan personen vanaf 18 jaar en vragen zo nodig een identiteitsbewijs. U rekent af bij levering, cash of met Payconiq. Lees ook even onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a>.",
        ],
        "wijken": "Dageraadplaats, Cogels-Osylei, Transvaalstraat, Waterloostraat, Draakplaats, Tramplein, Generaal Van Merlenstraat, Pretoriastraat, Krugerplein, Station Antwerpen-Berchem",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ligt mijn adres in Zurenborg bij Antwerpen of bij Berchem voor jullie?", "Dat maakt voor de bezorging niets uit. Of uw straat nu bij het district Antwerpen of bij <a href=\"/bezorggebied/berchem/\">Berchem</a> hoort, de levertijd blijft meestal 20 tot 30 minuten en onze bezorger komt in beide gevallen gewoon tot aan uw voordeur."],
            ["Komen jullie ook tijdens evenementen op de Dageraadplaats?", "Ja, maar als het plein afgesloten is voor een buurtfeest of markt, parkeert onze bezorger in een zijstraat en wandelt hij het laatste stuk naar uw deur. Het kan dan enkele minuten langer duren; wij laten dat vooraf weten via WhatsApp."],
            ["Kan ik lachgas laten bezorgen in een studentenkot in Zurenborg?", "Ja, zolang u zelf 18 jaar of ouder bent en de bestelling aan de deur in ontvangst neemt met uw identiteitskaart bij de hand. Houd rekening met de huisregels van uw kotbaas; meer leest u op onze pagina voor <a href=\"/lachgas-studenten-antwerpen/\">studenten in Antwerpen</a>."],
        ],
        "nearby": ["berchem", "borgerhout", "antwerpen-centrum"],
        "lat": 51.2060, "lon": 4.4300,
    },
    # ------------------------------------------------------------------ steden
    {
        "slug": "mechelen",
        "name": "Mechelen",
        "kind": "stad",
        "title": "Lachgas Mechelen | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Mechelen? Tanks en patronen vanuit Antwerpen aan huis, van de Grote Markt tot Nekkerspoel, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Mechelen",
        "lead": "Halfweg tussen Antwerpen en Brussel: lachgas aan huis in Mechelen en de deelgemeenten, besteld via WhatsApp en betaald bij levering.",
        "intro": [
            "Mechelen ligt aan de Dijle, halfweg tussen Antwerpen en Brussel langs de E19. De stad draait rond de Grote Markt met de Sint-Romboutskathedraal, de IJzerenleen en de Vismarkt, met daarrond woonwijken zoals Nekkerspoel, de Battelse wijken en de buurten binnen de Vesten. Ook de deelgemeenten Hombeek, Leest, Heffen, Walem en Muizen horen bij ons bezorggebied. Wij rijden vanuit Antwerpen naar al die adressen. Bestellen doet u door ons een WhatsApp-bericht te sturen met de gewenste tank of producten en uw adres; wij bevestigen de prijs vooraf en melden wanneer de bezorger de E19 oprijdt.",
            "De rit van Antwerpen naar Mechelen loopt over de E19 tot de afritten Mechelen-Noord of Mechelen-Zuid, of via de N1 door Kontich en Rumst wanneer de autosnelweg vastzit. Dat is een afstand van ruim twintig kilometer, en in de avondspits rond het knooppunt Antwerpen-Zuid kan het traag gaan; daarom rekenen wij voor Mechelen op meestal 45 tot 75 minuten. Het station Mechelen is een van de drukste van het land en Mechelen-Nekkerspoel ligt aan de oostkant van het centrum, maar u hoeft nergens naartoe: onze bezorger komt tot aan uw voordeur.",
            "Een feestje in een studentenflat aan de Vesten, een verjaardag in een gezinswoning in Hombeek of een avond met vrienden in een appartement aan de Dijle: kies het formaat op maat van uw groep. Voor een handvol mensen is de 2KG ruim voldoende, wie meer gasten verwacht neemt de 4KG of de 10KG. Alle tanks, crackers en slagroompatronen staan in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen enkel aan meerderjarigen en vragen indien nodig uw identiteitskaart. Betalen gebeurt bij levering, cash of via Payconiq. Lees vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>, zeker als u voor het eerst bestelt.",
        ],
        "wijken": "Grote Markt, IJzerenleen, Vismarkt, Nekkerspoel, Battel, Hombeek, Leest, Heffen, Walem, Muizen",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Waarom duurt bezorgen in Mechelen langer dan in Antwerpen?", "Omdat elke rit vanuit Antwerpen vertrekt en Mechelen ruim twintig kilometer verder langs de E19 ligt. Met het laden, de snelweg en het parkeren in het centrum komen wij meestal uit op 45 tot 75 minuten; bij uw bestelling krijgt u een actuele inschatting."],
            ["Bezorgen jullie ook in Muizen, Hombeek en de andere deelgemeenten?", "Ja, alle deelgemeenten van Mechelen horen bij ons bezorggebied, van Walem in het noorden tot Muizen en Hofstade richting Zemst. De levertijd blijft overal meestal 45 tot 75 minuten, afhankelijk van het verkeer op de E19 en de R6."],
            ["Komen jullie ook ’s nachts naar Mechelen?", "Dat hangt af van onze planning die nacht; vaak wel, omdat de E19 dan rustig is. Stuur uw adres via WhatsApp en u hoort meteen of het lukt. Hoe nachtlevering werkt, leest u op <a href=\"/lachgas-nachtbezorging/\">lachgas nachtbezorging</a>."],
        ],
        "nearby": ["duffel", "lier", "willebroek"],
        "lat": 51.0259, "lon": 4.4776,
    },
    {
        "slug": "lier",
        "name": "Lier",
        "kind": "stad",
        "title": "Lachgas Lier | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Lier? Tanks en patronen vanuit Antwerpen aan huis, van de Zimmertoren tot Koningshooikt, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Lier",
        "lead": "Lachgas aan huis in de Netestad en Koningshooikt: bestellen via WhatsApp, prijs vooraf bevestigd en betalen bij levering.",
        "intro": [
            "Lier ligt ten zuidoosten van Antwerpen, waar de Grote en de Kleine Nete samenvloeien. Binnen de ring R16 vindt u het historische centrum met de Grote Markt, de Zimmertoren, de Sint-Gummaruskerk en het begijnhof, met daarrond woonwijken zoals Lisp, de Mechelpoort en de nieuwe buurt op de oude Dungelhoeffkazerne. De deelgemeente Koningshooikt, een stuk zuidelijker richting Putte, bedienen wij ook. Vanuit Antwerpen komen wij in al die straten aan huis. Stuur ons een WhatsApp-bericht met uw bestelling en adres, dan bevestigen wij meteen en geven wij aan wanneer de bezorger onderweg is.",
            "Onze bezorgers rijden naar Lier over de N10 door Mortsel en Boechout, of nemen de E313 tot Ranst en vervolgens de N14 wanneer de Liersesteenweg vastzit. Een afstand van zo’n twintig kilometer, grotendeels over gewone wegen met veel lichten en dorpskernen; daarom hanteren wij voor Lier een indicatie van meestal 45 tot 75 minuten. Het station Lier ligt op de lijnen naar Antwerpen, Mechelen en Herentals en de bussen van De Lijn stoppen aan de Grote Markt, maar u hoeft daar geen rekening mee te houden: wij brengen de bestelling tot aan uw deur.",
            "Een avond met vrienden in een herenhuis aan de Werf, een verjaardag in een rijhuis in Lisp of een barbecue in een tuin in Koningshooikt: het formaat van de tank kiest u naargelang het aantal gasten. De compacte 2KG past bij een klein gezelschap, de 4KG en 10KG bij grotere groepen. Bekijk alle formaten met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar en ouder en controleren dat met uw identiteitskaart. Afrekenen gebeurt cash of via Payconiq bij levering. Neem vooraf ook onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a> door.",
        ],
        "wijken": "Grote Markt, Zimmertoren, Begijnhof, Lisp, Mechelpoort, Dungelhoeff, Werf, Koningshooikt, Netekanaal, Pallieterland",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Hoe komen jullie vanuit Antwerpen in Lier en hoe lang duurt dat?", "Meestal via de N10 door Mortsel en Boechout, bij files via de E313 en de N14. Omdat die route grotendeels over gewone wegen loopt, rekenen wij op meestal 45 tot 75 minuten; de concrete inschatting krijgt u bij de bevestiging van uw bestelling via WhatsApp."],
            ["Leveren jullie ook in Koningshooikt?", "Ja, Koningshooikt hoort bij Lier en dus bij ons bezorggebied, ook de straten richting Putte en Berlaar. Omdat het nog een stuk voorbij het centrum ligt, kan de levertijd daar eerder aan het einde van de indicatie van 45 tot 75 minuten uitkomen."],
            ["Mag ik mijn bestelling laten leveren tijdens een feest in het centrum van Lier?", "Wij bezorgen aan uw woonadres, niet op straat of op een evenement. Is het centrum afgesloten voor een markt of festiviteit, dan parkeert onze bezorger buiten de afsluiting en wandelt hij naar uw deur. Wat de wet in België over lachgas zegt, leest u op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
        ],
        "nearby": ["lint", "duffel", "boechout"],
        "lat": 51.1310, "lon": 4.5700,
    },
    {
        "slug": "sint-niklaas",
        "name": "Sint-Niklaas",
        "kind": "stad",
        "title": "Lachgas Sint-Niklaas | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Sint-Niklaas? Tanks en patronen vanuit Antwerpen aan huis in heel het Waasland, meestal binnen 45 tot 75 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Sint-Niklaas",
        "lead": "Van de Grote Markt tot Belsele en Nieuwkerken: lachgas aan huis in Sint-Niklaas, via WhatsApp besteld en bij levering betaald.",
        "intro": [
            "Sint-Niklaas is de hoofdstad van het Waasland en ligt langs de E17 tussen Antwerpen en Gent. De Grote Markt, met het stadhuis en de Sint-Nicolaaskerk, is de grootste van België; daarrond liggen de Stationsstraat, de Parklaan en woonbuurten zoals Tereken, Puyenbeke en de Clementwijk, met het Waasland Shopping Center aan de rand. De deelgemeenten Belsele, Nieuwkerken-Waas en Sinaai horen eveneens bij ons bezorggebied. Vanuit Antwerpen komen wij in al die straten aan huis. U stuurt een WhatsApp-bericht met uw bestelling en adres, wij bevestigen en laten weten wanneer de bezorger de Kennedytunnel in rijdt.",
            "De route vanuit Antwerpen loopt door de Kennedytunnel en over de E17 tot de afrit Sint-Niklaas, zo’n vijfentwintig kilometer. Als de tunnel vastzit, kiezen onze bezorgers de Liefkenshoektunnel en de N70 via Beveren. De E17 is in de avondspits en op zaterdag bij het shoppingcenter vaak druk, en daarom rekenen wij voor Sint-Niklaas op meestal 45 tot 75 minuten. Het station Sint-Niklaas ligt aan de lijn Antwerpen–Gent en de bussen van De Lijn vertrekken aan het Stationsplein; voor uw bestelling hoeft u echter niets anders te doen dan thuis te zijn.",
            "Een verjaardag in een appartement aan de Parklaan, een tuinfeest in Belsele of een avond met vrienden in een woning in de Clementwijk: kies een tankformaat dat bij uw gezelschap past. De 2KG is er voor een kleine groep, de 4KG en 10KG voor wie meer mensen uitnodigt. Al onze tanks, crackers en slagroompatronen vindt u in het <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen uitsluitend aan 18-plussers en vragen zo nodig een identiteitskaart aan de deur. Betalen kan cash of via Payconiq bij levering. Lees voor uw eerste bestelling zeker ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Grote Markt, Stationsstraat, Parklaan, Tereken, Puyenbeke, Clementwijk, Waasland Shopping Center, Belsele, Nieuwkerken-Waas, Sinaai",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Komen jullie ook in Belsele, Nieuwkerken-Waas en Sinaai?", "Ja, de drie deelgemeenten van Sint-Niklaas horen volledig bij ons bezorggebied. Sinaai ligt het verst van de E17, waardoor de levertijd daar eerder richting 75 minuten kan gaan; wij geven u bij de bestelling een realistische inschatting."],
            ["Wat als de Kennedytunnel vastzit wanneer ik bestel?", "Dan rijdt onze bezorger via de Liefkenshoektunnel en de N70 of de E34 naar Sint-Niklaas. Dat kost soms iets meer tijd, maar meestal blijven wij binnen de indicatie van 45 tot 75 minuten; wij houden u via WhatsApp op de hoogte als het langer dreigt te duren."],
            ["Kan ik in Sint-Niklaas ook alleen slagroompatronen bestellen?", "Ja, slagroompatronen en crackers leveren wij ook los, zonder tank. Omdat het een langere rit vanuit Antwerpen is, bekijken wij bij kleine bestellingen wel of de levering die avond past in onze route; u krijgt daar meteen antwoord op via WhatsApp."],
        ],
        "nearby": ["temse", "beveren", "lokeren"],
        "lat": 51.1650, "lon": 4.1430,
    },
    {
        "slug": "turnhout",
        "name": "Turnhout",
        "kind": "stad",
        "title": "Lachgas Turnhout | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Turnhout? Tanks en patronen vanuit Antwerpen aan huis in de hoofdstad van de Kempen, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Turnhout",
        "lead": "Lachgas aan huis in Turnhout, van de Grote Markt tot Zevendonk: één WhatsApp-bericht, prijs vooraf bevestigd, betalen bij levering.",
        "intro": [
            "Turnhout is de hoofdstad van de Kempen en ligt in het noordoosten van de provincie Antwerpen, dicht bij de Nederlandse grens. Rond de Grote Markt met de Sint-Pieterskerk en het Kasteel van de Hertogen van Brabant liggen het begijnhof, het nieuwe stadsdeel Turnova en de winkelstraten Gasthuisstraat en Leopoldstraat. Daaromheen vindt u woonwijken als Schorvoort, de Parkwijk en Zevendonk, en aan de noordkant het kanaal Dessel-Schoten. Vanuit Antwerpen bedienen wij al die adressen. Bestellen gaat via WhatsApp: stuur ons uw bestelling en adres, wij bevestigen en melden wanneer de bezorger vertrekt.",
            "De rit naar Turnhout verloopt over de E34 richting Eindhoven, een afstand van ongeveer vijfenveertig kilometer vanaf de Ring van Antwerpen. Buiten de spits is dat een vlotte snelweg, maar rond het knooppunt Antwerpen-Oost en op vrijdagavond richting de Kempen staat er geregeld file, en daarom rekenen wij voor Turnhout op meestal 45 tot 75 minuten. Het station Turnhout heeft treinen richting Herentals en Lier, en de stadsring R13 maakt elke wijk vlot bereikbaar. Voor u verandert dat niets: onze bezorger komt met de wagen tot aan uw voordeur.",
            "Een feestje in een studio bij de Turnova-site, een familiefeest in een gezinswoning in Schorvoort of een avond met vrienden in Zevendonk: het aantal gasten bepaalt welk formaat u best kiest. De 2KG is compact en volstaat voor een klein groepje, de 4KG en 10KG zijn geschikt voor grotere gezelschappen. Alle formaten plus crackers en slagroompatronen vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan meerderjarigen en controleren de leeftijd wanneer nodig. U betaalt pas bij levering, cash of via Payconiq. Lees vooraf ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Grote Markt, Begijnhof, Turnova, Gasthuisstraat, Leopoldstraat, Schorvoort, Parkwijk, Zevendonk, Stadspark, Kanaal Dessel-Schoten",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Is Turnhout niet te ver voor bezorging vanuit Antwerpen?", "Nee, Turnhout hoort bij onze buitenste zone. De rit over de E34 duurt doorgaans drie kwartier, en met laden en het laatste stuk door de stad komen wij meestal uit op 45 tot 75 minuten. Bij uw bestelling krijgt u een inschatting die rekening houdt met het verkeer op dat moment."],
            ["Bezorgen jullie ook in Oud-Turnhout of Vosselaar?", "Die buurgemeenten staan niet apart op onze site, maar liggen zo dicht bij Turnhout dat wij er doorgaans ook komen. Stuur uw adres via WhatsApp, dan laten wij meteen weten of het die avond past en hoe lang het ongeveer duurt."],
            ["Kan ik in Turnhout ’s nachts bestellen?", "Dat bekijken wij per nacht, afhankelijk van onze route; op rustige nachten is de E34 vlot en lukt het meestal. Vraag het gewoon via WhatsApp. Meer over onze werkwijze bij late bestellingen vindt u op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["geel", "herentals", "malle"],
        "lat": 51.3225, "lon": 4.9450,
    },
    {
        "slug": "hasselt",
        "name": "Hasselt",
        "kind": "stad",
        "title": "Lachgas Hasselt | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Hasselt? Tanks en patronen vanuit Antwerpen aan huis in de Limburgse hoofdstad, meestal binnen 45 tot 75 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Hasselt",
        "lead": "Lachgas aan huis in Hasselt, binnen de Groene Boulevard en in Kiewit, Runkst of Kuringen: via WhatsApp besteld en betaald bij levering.",
        "intro": [
            "Hasselt is de hoofdstad van Limburg en de meest oostelijke stad in ons bezorggebied. Het compacte centrum binnen de Groene Boulevard draait rond de Grote Markt, de Sint-Quintinuskathedraal en de winkelstraten Demerstraat en Koning Albertstraat, met het Jenevermuseum en de Japanse Tuin als bekende plekken. Daarrond liggen wijken en deelgemeenten als Runkst, Kiewit, Kuringen, Godsheide en Sint-Lambrechts-Herk, en aan de rand van de stad het Albertkanaal. Vanuit Antwerpen komen wij in al die buurten aan huis. Stuur ons een WhatsApp-bericht met uw bestelling en adres; wij bevestigen en geven aan wanneer de bezorger vertrekt.",
            "De rit van Antwerpen naar Hasselt gaat over de E313, ongeveer tachtig kilometer via Ranst, Herentals en Geel tot de afritten bij Hasselt. Buiten de spits is het een vlotte autosnelweg, maar in de ochtend- en avondspits staat er geregeld file tussen Antwerpen en Ranst; daarom rekenen wij voor Hasselt op meestal 45 tot 75 minuten en soms, bij zware files, iets meer. Het station Hasselt en de busterminal van De Lijn liggen aan de zuidrand van het centrum, en de Groene Boulevard maakt elke wijk vlot bereikbaar. Onze bezorger komt met de wagen tot aan uw deur.",
            "Een studentenfeest in Runkst dicht bij de universiteitscampus, een verjaardag in een gezinswoning in Kuringen of een avond met vrienden in een appartement aan de Groene Boulevard: kies een tank op maat van uw gezelschap. De 2KG is er voor kleine groepen, de 4KG en 10KG voor wie meer gasten verwacht. Alle tanks met crackers en slagroompatronen staan in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen uitsluitend aan personen van 18 jaar en ouder en vragen zo nodig een identiteitskaart. Betalen doet u bij levering, cash of met Payconiq. Op <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> staat hoe u verantwoord met lachgas omgaat.",
        ],
        "wijken": "Grote Markt, Demerstraat, Koning Albertstraat, Groene Boulevard, Runkst, Kiewit, Kuringen, Godsheide, Sint-Lambrechts-Herk, Quartier Bleu",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Hasselt ligt tachtig kilometer van Antwerpen; halen jullie 45 tot 75 minuten?", "Buiten de spits wel: de E313 is dan een vlotte snelweg en wij staan vaak binnen het uur aan uw deur. Bij files rond Antwerpen of werken op de E313 kan het langer duren, en dan zeggen wij dat eerlijk bij de bevestiging via WhatsApp."],
            ["Bezorgen jullie ook in Kiewit, Kuringen en Sint-Lambrechts-Herk?", "Ja, alle deelgemeenten van Hasselt horen bij ons bezorggebied, net als Godsheide en Stokrooie langs het Albertkanaal. De indicatie blijft overal meestal 45 tot 75 minuten; het verkeer op de E313 weegt zwaarder door dan de laatste kilometers binnen Hasselt."],
            ["Gelden in Hasselt andere regels voor lachgas dan in Antwerpen?", "Het federale kader is overal in België hetzelfde; daarnaast kan elke stad eigen politieregels hebben over overlast en afval op straat. Wij leveren aan uw woonadres en verwachten dat u lachgas verantwoord en binnen de wet gebruikt; lees meer op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
        ],
        "nearby": ["geel", "herentals", "leuven"],
        "lat": 50.9307, "lon": 5.3378,
    },
    {
        "slug": "aalst",
        "name": "Aalst",
        "kind": "stad",
        "title": "Lachgas Aalst | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Aalst? Tanks en patronen vanuit Antwerpen aan huis in de Denderstad en haar deelgemeenten, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Aalst",
        "lead": "Lachgas aan huis in Aalst, van de Grote Markt tot Erembodegem en Hofstade: besteld via WhatsApp, prijs vooraf bevestigd en betaald bij levering.",
        "intro": [
            "Aalst ligt aan de Dender in Oost-Vlaanderen, tussen Gent en Brussel langs de E40. De stad is bekend om haar carnaval en om de Grote Markt met het belfort en het oude schepenhuis, met daarrond de Hopmarkt, het Stationsplein en de nieuwe woonbuurt op de rechteroever van de Dender. De deelgemeenten Erembodegem, Hofstade, Moorsel, Gijzegem, Herdersem, Baardegem, Meldert en Nieuwerkerken horen allemaal bij ons bezorggebied. Vanuit Antwerpen rijden wij naar al die adressen. Bestellen doet u via WhatsApp: stuur ons de gewenste producten en uw adres, wij bevestigen en melden wanneer onze bezorger vertrekt.",
            "Vanuit Antwerpen rijden onze bezorgers over de E17 tot Sint-Niklaas en verder via de N41 door Hamme en Dendermonde naar Aalst, of via de E19 en de Brusselse ring naar de E40 wanneer dat sneller gaat. Beide routes zijn ruim vijftig kilometer en lopen deels over gewone wegen, zodat wij voor Aalst rekenen op meestal 45 tot 75 minuten. Het station Aalst ligt aan de lijn Gent–Brussel en de bussen van De Lijn vertrekken aan het Stationsplein, maar u hoeft daar geen gebruik van te maken: wij komen tot aan uw voordeur.",
            "Een verjaardag in een appartement aan de Dender, een tuinfeest in Hofstade of een avond met vrienden in een rijhuis in Mijlbeek: kies het formaat dat past bij het aantal gasten. Voor een klein gezelschap is de 2KG ideaal, voor grotere groepen kiest u de 4KG of de 10KG. Bekijk alle tanks, crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren enkel aan 18-plussers en vragen bij twijfel uw identiteitskaart. Afrekenen doet u bij levering, cash of via Payconiq. Neem vooraf ook onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door.",
        ],
        "wijken": "Grote Markt, Hopmarkt, Stationsplein, Rechteroever, Mijlbeek, Erembodegem, Hofstade, Moorsel, Gijzegem, Nieuwerkerken",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Hoe rijden jullie vanuit Antwerpen naar Aalst?", "Meestal via de E17 tot Sint-Niklaas en dan over de N41 langs Hamme en Dendermonde; bij druk verkeer kiezen wij soms de E19 en de E40. Reken op meestal 45 tot 75 minuten; de concrete inschatting krijgt u bij de bevestiging van uw bestelling."],
            ["Leveren jullie ook tijdens Aalst Carnaval?", "Ja, maar het centrum is dan grotendeels afgesloten en de levertijd kan oplopen. Onze bezorger parkeert buiten de afgesloten zone en wandelt naar uw woonadres; op straat of op het feest zelf bezorgen wij niet. Overleg vooraf via WhatsApp wat die dag haalbaar is."],
            ["Bezorgen jullie in alle deelgemeenten van Aalst?", "Ja, van Gijzegem en Herdersem in het noorden tot Erembodegem en Meldert in het zuiden. Voor de deelgemeenten die het verst van de N41 of de E40 liggen, kan de levertijd eerder aan het einde van de indicatie van 45 tot 75 minuten uitkomen."],
        ],
        "nearby": ["brussel", "gent", "lokeren"],
        "lat": 50.9378, "lon": 4.0402,
    },
    {
        "slug": "herentals",
        "name": "Herentals",
        "kind": "stad",
        "title": "Lachgas Herentals | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Herentals? Tanks en patronen vanuit Antwerpen aan huis, ook in Noorderwijk en Morkhoven, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Herentals",
        "lead": "Lachgas aan huis in Herentals, Noorderwijk en Morkhoven: één WhatsApp-bericht, prijs vooraf bevestigd, betalen cash of via Payconiq bij levering.",
        "intro": [
            "Herentals ligt in het hart van de Kempen, aan de Kleine Nete en het Albertkanaal, langs de E313 tussen Antwerpen en Hasselt. Het historische centrum rond de Grote Markt met de Lakenhal en de Sint-Waldetrudiskerk wordt omringd door het begijnhof, de Bovenrij en de Zandstraat, met daarbuiten rustige woonwijken en de Kempense Heuvelrug als groene rand. De deelgemeenten Noorderwijk en Morkhoven, ten zuiden van het kanaal, horen eveneens bij ons bezorggebied. Vanuit Antwerpen leveren wij op al die adressen. Stuur ons via WhatsApp uw bestelling en adres, dan bevestigen wij en zeggen wij wanneer onze bezorger vertrekt.",
            "De rit vanuit Antwerpen loopt over de E313 tot de afritten Herentals-West of Herentals-Oost, ongeveer vijfendertig kilometer vanaf de Ring. Het grootste deel is autosnelweg, maar het stuk tussen het knooppunt Antwerpen-Oost en Ranst zit in de spits vaak vol, en daarom hanteren wij voor Herentals een indicatie van meestal 45 tot 75 minuten. Het station Herentals is een knooppunt met treinen naar Antwerpen, Turnhout, Mol en Lier, en de bussen van De Lijn stoppen aan de Grote Markt. Voor uw bestelling hoeft u echter de deur niet uit.",
            "Een verjaardag in een gezinswoning in Noorderwijk, een avond met vrienden in een appartement aan de Bovenrij of een barbecue in een tuin aan de rand van de Kempense Heuvelrug: kies de tank die bij uw gezelschap past. De 2KG volstaat voor een kleine groep, de 4KG en 10KG zijn er voor grotere gezelschappen. Alle tanks staan samen met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen alleen aan meerderjarigen en controleren de leeftijd waar nodig. Betalen gebeurt aan de deur, cash of met Payconiq. Op <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u hoe u verstandig met lachgas omgaat.",
        ],
        "wijken": "Grote Markt, Lakenhal, Begijnhof, Bovenrij, Zandstraat, Kempense Heuvelrug, Netepark, Albertkanaal, Noorderwijk, Morkhoven",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Hoe lang rijden jullie vanuit Antwerpen naar Herentals?", "Over de E313 is het ongeveer vijfendertig kilometer, buiten de spits een halfuur rijden. Met het laden en het laatste stuk door de stad komen wij meestal uit op 45 tot 75 minuten; staat er file aan Ranst, dan melden wij dat bij uw bestelling."],
            ["Komen jullie ook in Noorderwijk en Morkhoven?", "Ja, beide deelgemeenten ten zuiden van het Albertkanaal horen bij ons bezorggebied. Onze bezorger neemt dan de afrit Herentals-Oost of rijdt via Olen; de levertijd blijft meestal binnen 45 tot 75 minuten."],
            ["Kan ik lachgas bestellen voor een feest in een huurzaal in Herentals?", "Wij leveren aan particuliere woonadressen en in overleg aan een privéfeest op een vast adres waar de bestelling door een meerderjarige wordt ontvangen. Beschrijf de situatie vooraf via WhatsApp, dan bekijken wij of het past; op <a href=\"/lachgas-feest-evenement/\">lachgas voor feesten</a> leest u onze voorwaarden."],
        ],
        "nearby": ["geel", "lier", "turnhout"],
        "lat": 51.1767, "lon": 4.8350,
    },
    {
        "slug": "geel",
        "name": "Geel",
        "kind": "stad",
        "title": "Lachgas Geel | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Geel? Tanks en patronen vanuit Antwerpen aan huis in het centrum en de gehuchten, meestal binnen 45 tot 75 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Geel",
        "lead": "Lachgas aan huis in Geel en de gehuchten rond de stad: bestellen via WhatsApp, prijs vooraf bevestigd, betalen bij levering.",
        "intro": [
            "Geel ligt in de Antwerpse Kempen, langs de E313 tussen Herentals en de Limburgse grens, met het Albertkanaal aan de noordkant. Het centrum rond de Markt, de Sint-Amandskerk en de Nieuwstraat is compact; daaromheen liggen de hogeschoolcampus van Thomas More, het cultuurcentrum de Werft en woonwijken als Elsum, Holven en Punt. Verder van de kern liggen gehuchten zoals Ten Aard, Larum, Bel, Winkelomheide, Zammel en Oosterlo, allemaal binnen ons bezorggebied. Vanuit Antwerpen komen wij in al die straten aan huis. U stuurt een WhatsApp-bericht met uw bestelling en adres; wij bevestigen en melden wanneer de bezorger vertrekt.",
            "Onze bezorgers rijden vanuit Antwerpen over de E313 tot de afritten Geel-West of Geel-Oost, een afstand van ongeveer vijftig kilometer. In de daluren is dat een vlotte rit, maar de spitsfiles tussen de Ring en Ranst en de werken die geregeld op de E313 plaatsvinden maken dat wij voor Geel rekenen op meestal 45 tot 75 minuten. Het station Geel ligt aan de lijn Antwerpen–Mol en de bussen van De Lijn stoppen aan de Markt en de campus. Dat is handig voor uw gasten; onze bezorger komt zelf met de wagen tot aan uw voordeur.",
            "Een studentenfeest bij de campus van Thomas More, een familiefeest in een vrijstaande woning in Ten Aard of een avond met vrienden in een appartement aan de Nieuwstraat: het tankformaat kiest u op basis van het aantal gasten. De 2KG past bij een klein gezelschap, de 4KG en 10KG bij grotere groepen. Elk formaat staat met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen zo nodig uw identiteitskaart. Afrekenen doet u aan de deur, cash of via Payconiq. Lees vooraf ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a>.",
        ],
        "wijken": "Markt, Nieuwstraat, Sint-Amandskerk, Thomas More campus, Elsum, Holven, Punt, Ten Aard, Larum, Zammel",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Bezorgen jullie ook in de gehuchten buiten het centrum van Geel?", "Ja, Ten Aard, Larum, Bel, Winkelomheide, Zammel, Oosterlo en Stelen horen allemaal bij Geel en bij ons bezorggebied. Omdat sommige gehuchten een stuk van de E313 liggen, kan de levertijd daar eerder aan het einde van de indicatie van 45 tot 75 minuten uitkomen."],
            ["Kan ik als student in Geel lachgas laten bezorgen op mijn kot?", "Ja, als u 18 jaar of ouder bent en zelf aan de deur opent met uw identiteitskaart. Respecteer de regels van uw kotbaas of residentie; wij bezorgen niet in gemeenschappelijke ruimtes van een studentenhuis. Meer leest u op <a href=\"/lachgas-studenten-antwerpen/\">lachgas en studenten</a>."],
            ["Waar laat ik een lege tank in Geel?", "Een lege lachgastank hoort nooit bij het restafval of in een glascontainer; brengt u ze naar het recyclagepark van uw gemeente of geef ze terug aan onze bezorger bij een volgende levering. Hoe u een lege fles inlevert, leest u op <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">lege lachgasfles inleveren</a>."],
        ],
        "nearby": ["herentals", "turnhout", "hasselt"],
        "lat": 51.1620, "lon": 4.9900,
    },
    {
        "slug": "lokeren",
        "name": "Lokeren",
        "kind": "stad",
        "title": "Lachgas Lokeren | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Lokeren? Tanks en patronen vanuit Antwerpen aan huis, van de Markt tot Eksaarde en Daknam, meestal binnen 45 tot 75 minuten. 18+.",
        "h1": "Lachgas bezorgen in Lokeren",
        "lead": "Lachgas aan huis in Lokeren, Eksaarde en Daknam: via WhatsApp besteld, prijs vooraf bevestigd en betaald wanneer wij aanbellen.",
        "intro": [
            "Lokeren ligt aan de Durme in het Waasland, langs de E17 tussen Sint-Niklaas en Gent. Het centrum rond de Markt met de Sint-Laurentiuskerk en de Grote Kaai aan de rivier wordt omringd door woonwijken zoals Bergendries, Heiende, Oudenbos en Hillare, en verder buiten de stad liggen de deelgemeenten Eksaarde, Daknam en Doorslaar. Al die adressen bedienen wij vanuit Antwerpen. Bestellen is eenvoudig: u stuurt ons via WhatsApp door welke tank of producten u wenst en op welk adres, wij bevestigen de prijs en laten weten wanneer onze bezorger de E17 oprijdt.",
            "De route naar Lokeren loopt door de Kennedytunnel en over de E17 voorbij Sint-Niklaas tot de afrit Lokeren, zo’n veertig kilometer vanaf het centrum van Antwerpen. Die snelweg is in de avondspits richting Gent vaak druk, en bij een afgesloten Kennedytunnel wijken onze bezorgers uit via de Liefkenshoektunnel; daarom rekenen wij voor Lokeren op meestal 45 tot 75 minuten. Het station Lokeren ligt aan de lijn Antwerpen–Gent en de bussen van De Lijn stoppen aan de Markt, maar daar hoeft u geen rekening mee te houden: wij brengen uw bestelling tot aan de deur.",
            "Een verjaardag in een appartement aan de Grote Kaai, een tuinfeest in Eksaarde of een avond met vrienden in een rijhuis in Bergendries: kies de tank die bij het aantal gasten past. Voor een klein gezelschap volstaat de 2KG, voor grotere groepen zijn er de 4KG en de 10KG. Alle formaten met crackers en slagroompatronen vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen alleen aan 18-plussers en vragen zo nodig een identiteitskaart aan de deur. Betalen kan cash of via Payconiq bij levering. Neem vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Markt, Grote Kaai, Sint-Laurentiuskerk, Bergendries, Heiende, Oudenbos, Hillare, Eksaarde, Daknam, Doorslaar",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Leveren jullie ook tijdens de Lokerse Feesten?", "Ja, maar begin augustus is het centrum rond de Grote Kaai dan afgesloten en is het verkeer rond Lokeren druk. Onze bezorger parkeert buiten de afgesloten zone en komt te voet naar uw woonadres; op het festivalterrein zelf leveren wij niet. Reken die dagen op het einde van de indicatie van 45 tot 75 minuten."],
            ["Komen jullie ook in Eksaarde, Daknam en Doorslaar?", "Ja, de deelgemeenten ten noorden van het centrum horen gewoon bij ons bezorggebied. Eksaarde ligt het verst van de E17, waardoor de levertijd daar eerder richting 75 minuten kan gaan; bij uw bestelling krijgt u een realistische inschatting."],
            ["Kan ik vanuit Lokeren ook een grotere tank voor een privéfeest bestellen?", "Ja, de 10KG leveren wij ook in Lokeren, zolang de bestelling door een meerderjarige op een woonadres wordt ontvangen. Welk formaat voor uw gezelschap het meest geschikt is, leest u op <a href=\"/lachgas-informatie/welke-lachgastank-heb-ik-nodig/\">welke lachgastank heb ik nodig</a>."],
        ],
        "nearby": ["sint-niklaas", "gent", "aalst"],
        "lat": 51.1040, "lon": 3.9930,
    },
]

HUBS = [
    {
        "slug": "provincie-antwerpen",
        "name": "Provincie Antwerpen en Vlaanderen",
        "title": "Lachgas bezorgen in provincie Antwerpen en Vlaanderen",
        "description": "Ons bezorggebied per zone: stad Antwerpen en districten, Noord- en Zuidrand, Waasland, Kempen en Vlaamse steden, met de levertijd per regio. 18+.",
        "h1": "Lachgas bezorgen in de provincie Antwerpen en Vlaanderen",
        "lead": "Vanuit Antwerpen bezorgen wij lachgastanks in de hele provincie en tot in Gent, Leuven, Brussel, Brugge en Hasselt. De levertijd groeit mee met de afstand tot de stad.",
        "intro": [
            "Ons bezorggebied begint in de stad Antwerpen. Alle districten en wijken binnen en rond de Ring horen erbij: het centrum binnen de Leien, het Zuid, het Eilandje, het Kiel, Zurenborg en Luchtbal, de districten Berchem, Borgerhout, Deurne, Merksem, Hoboken, Wilrijk en Ekeren, en aan de overkant van de Schelde Linkeroever. Omdat onze bezorgers hier dagelijks rijden en elke buurt via de Ring, de Leien of de Singel snel bereikbaar is, staan wij in de stad meestal binnen 20 tot 30 minuten aan de deur. Voor elke wijk en elk district is er een eigen pagina met buurten, route en lokale vragen.",
            "Rond de stad liggen de randgemeenten: de Noordrand van Brasschaat en Schoten tot Kapellen, Kalmthout en Essen, de Voorkempen met Schilde, Zoersel, Malle en Brecht, de Zuidrand van Mortsel en Edegem tot Kontich en Aartselaar, de Rupelstreek met Boom, Niel en Rumst, en over de Schelde het Waasland en Klein-Brabant. Hier is de rit langer en loopt hij vaker over steenwegen en door dorpskernen, zodat wij rekenen op meestal 25 tot 40 minuten. De Vlaamse steden verder weg, van Mechelen en Lier tot Gent, Leuven, Brussel, Brugge en Hasselt, bedienen wij via de E17, E19, E313, E34 en E40 met een indicatie van meestal 45 tot 75 minuten.",
            "Bestellen werkt overal hetzelfde: u stuurt ons een WhatsApp-bericht met de gewenste tank of producten en uw adres, wij bevestigen de prijs en de verwachte levertijd en melden wanneer de bezorger vertrekt. De stappen staan uitgelegd op onze pagina <a href=\"/werkwijze/\">werkwijze</a>, en alle formaten van 2KG tot 10KG, crackers en slagroompatronen vindt u in het <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar en ouder, aan een woonadres en niet op straat of in een park, en u betaalt pas bij levering, cash of via Payconiq. Hieronder vindt u ons bezorggebied per deelregio.",
        ],
        "groups": [
            {
                "h2": "Stad Antwerpen en districten",
                "text": "Het centrum, de wijken binnen en rond de Ring en alle districten van de stad Antwerpen, inclusief Linkeroever: meestal binnen 20 tot 30 minuten.",
                "slugs": ["antwerpen-centrum", "antwerpen-zuid", "eilandje", "kiel", "zurenborg", "linkeroever", "luchtbal", "berchem", "borgerhout", "deurne", "merksem", "hoboken", "wilrijk", "ekeren"],
            },
            {
                "h2": "Noordrand",
                "text": "De gemeenten ten noorden en oosten van de stad, van Brasschaat en Schoten tot Essen en de Voorkempen rond Schilde, Zoersel en Malle: meestal binnen 25 tot 40 minuten.",
                "slugs": ["brasschaat", "schoten", "kapellen", "stabroek", "kalmthout", "essen", "brecht", "schilde", "zoersel", "malle", "wijnegem", "wommelgem", "ranst"],
            },
            {
                "h2": "Zuidrand en Rupelstreek",
                "text": "Mortsel, Edegem, Kontich en de gemeenten langs de A12, de N1 en de Rupel meestal binnen 25 tot 40 minuten; Lier, iets verder langs de Nete, meestal binnen 45 tot 75 minuten.",
                "slugs": ["mortsel", "edegem", "kontich", "hove", "boechout", "lint", "aartselaar", "hemiksem", "niel", "boom", "rumst", "duffel", "lier"],
            },
            {
                "h2": "Waasland en Klein-Brabant",
                "text": "Over de Schelde: Zwijndrecht, Kruibeke, Beveren en Temse en de gemeenten van Klein-Brabant meestal binnen 25 tot 40 minuten; Sint-Niklaas en Lokeren verder langs de E17 meestal binnen 45 tot 75 minuten.",
                "slugs": ["zwijndrecht", "kruibeke", "beveren", "temse", "bornem", "puurs", "willebroek", "sint-niklaas", "lokeren"],
            },
            {
                "h2": "Kempen",
                "text": "Herentals, Geel en Turnhout, bereikbaar via de E313 en de E34: een langere rit, meestal binnen 45 tot 75 minuten.",
                "slugs": ["herentals", "geel", "turnhout"],
            },
            {
                "h2": "Vlaamse steden",
                "text": "Mechelen, Brussel, Leuven, Gent, Aalst, Brugge en Hasselt, de buitenste zone van ons bezorggebied: meestal binnen 45 tot 75 minuten.",
                "slugs": ["mechelen", "brussel", "leuven", "gent", "aalst", "brugge", "hasselt"],
            },
        ],
        "faq": [
            ["Hoe weet ik in welke zone mijn gemeente valt?", "Zoek uw gemeente hierboven op bij de deelregio waar ze bij hoort; de indicatie die wij voor die zone hanteren staat erbij. Op <a href=\"/bezorgtijden-antwerpen/\">bezorgtijden Antwerpen</a> staan de zones nog eens op een rij, en bij uw bestelling krijgt u altijd de actuele verwachting."],
            ["Mijn gemeente staat niet in de lijst. Komen jullie dan toch?", "Ligt uw gemeente tussen of vlak bij de genoemde plaatsen in de provincie Antwerpen of het Waasland, dan meestal wel. Stuur uw adres via WhatsApp en u hoort meteen of wij kunnen komen en hoe lang het ongeveer duurt."],
            ["Betaal ik extra voor bezorging buiten de stad Antwerpen?", "Voor de verder gelegen steden kunnen wij een bijdrage in de verplaatsing vragen; dat hangt af van de afstand en van wat u bestelt. U hoort het vooraf in de WhatsApp-bevestiging, zodat er aan de deur geen verrassingen zijn. Betalen gebeurt altijd pas bij levering, cash of via Payconiq."],
            ["Is lachgas overal in Vlaanderen op dezelfde manier geregeld?", "Het federale kader geldt in heel België: het Koninklijk Besluit van 11 maart 2024 beperkt verkoop, vervoer en bezit van lachgas tot medische, technische en culinaire doeleinden, en verkoop aan minderjarigen is al sinds 2021 verboden. Gemeenten kunnen daarbovenop eigen regels hebben; lees meer op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
            ["Bezorgen jullie ’s nachts ook buiten Antwerpen?", "In de randgemeenten vaak wel; voor Mechelen, Gent, Hasselt en de andere steden hangt het af van onze planning die nacht. Vraag het gewoon via WhatsApp, dan hoort u meteen of het lukt. Wat u van een late levering mag verwachten, staat op <a href=\"/lachgas-nachtbezorging/\">lachgas nachtbezorging</a>."],
        ],
    },
]
