# -*- coding: utf-8 -*-
# Randgemeenten rond Antwerpen (deel A): zuidrand, Rupelstreek, oostrand en Noordrand.
# Levertijd overal "meestal binnen 25 tot 40 minuten".

AREAS = [
    {
        "slug": "aartselaar",
        "name": "Aartselaar",
        "kind": "gemeente",
        "title": "Lachgas Aartselaar | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Aartselaar? Wij leveren lachgastanks en patronen aan huis langs de A12, meestal binnen 25 tot 40 minuten. Uitsluitend 18+.",
        "h1": "Lachgas bezorgen in Aartselaar",
        "lead": "Van het centrum tot Buerstede en Lindenbos: lachgas aan huis geleverd, besteld via WhatsApp en betaald bij levering.",
        "intro": [
            "Aartselaar ligt pal ten zuiden van Wilrijk, aan weerszijden van de A12 die als Boomsesteenweg door de gemeente loopt. De winkels en horeca concentreren zich rond de Baron van Ertbornstraat en de Kapellestraat, terwijl wijken als Buerstede, Lindenbos en Koekoek vooral uit rustige woonstraten bestaan. Al die adressen bedienen wij vanuit Antwerpen. Bestellen doet u door ons een WhatsApp-bericht te sturen met wat u nodig heeft en het adres waar wij mogen aanbellen; wij bevestigen uw bestelling en de prijs op voorhand en verwittigen u wanneer onze bezorger vertrekt.",
            "Onze bezorgers rijden vanuit het centrum van Antwerpen over de Boomsesteenweg of via de Ring en de afrit Wilrijk, en staan doorgaans binnen het halfuur in Aartselaar. Omdat de A12 in de avondspits en op zaterdagnamiddag rond de winkelzone langs de steenweg druk kan zijn, houden wij een marge aan: reken op een levertijd van meestal 25 tot 40 minuten. Aartselaar heeft geen eigen treinstation; het openbaar vervoer verloopt via de bussen van De Lijn langs de Boomsesteenweg en de Kapellestraat. Voor u maakt dat niets uit, want wij komen gewoon tot aan uw voordeur.",
            "Een verjaardag in een gezinswoning in Lindenbos, een tuinfeest in Buerstede of een rustige avond met vrienden in een appartement langs de Kapellestraat: voor een klein gezelschap is de 2KG-tank meestal voldoende, voor grotere groepen kiest u de 4KG of 10KG. U vindt alle formaten, crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen zo nodig een identiteitsbewijs. Betalen doet u bij levering, cash of via Payconiq. Lees vooraf zeker onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a>.",
        ],
        "wijken": "Aartselaar-Centrum, Baron van Ertbornstraat, Kapellestraat, Buerstede, Lindenbos, Koekoek, Solhof, Cleydael, Boomsesteenweg",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe snel bent u in Aartselaar na mijn bestelling?", "Vanuit Antwerpen rijden wij via de A12 of de afrit Wilrijk en zijn wij meestal binnen 25 tot 40 minuten bij u. Zodra uw bestelling bevestigd is, krijgt u via WhatsApp een concrete indicatie en een bericht wanneer wij vertrekken."],
            ["Leveren jullie ook in de buurt van Cleydael en het Solhof?", "Ja, heel het grondgebied van Aartselaar hoort bij ons bezorggebied, ook de randen richting Hemiksem en Schelle. Wij bezorgen aan de deur van uw woonadres, niet op een parking of in het park."],
            ["Bezorgen jullie aan beide kanten van de A12?", "Ja, zowel in het centrum als in de wijken aan de andere kant van de Boomsesteenweg. Onze bezorger kiest de juiste afrit of oversteek, zodat u er geen rekening mee hoeft te houden. Levering gebeurt altijd aan de deur van uw woonadres."],
        ],
        "nearby": ["wilrijk", "hemiksem", "kontich"],
        "lat": 51.134, "lon": 4.386,
    },
    {
        "slug": "hemiksem",
        "name": "Hemiksem",
        "kind": "gemeente",
        "title": "Lachgas Hemiksem | Snel aan huis via WhatsApp",
        "description": "Lachgas bestellen in Hemiksem? Lachgastanks en patronen bezorgd tot aan uw deur aan de Scheldeboorden, meestal binnen 25 tot 40 minuten. Alleen 18+.",
        "h1": "Lachgas bezorgen in Hemiksem",
        "lead": "Van de Sint-Bernardusabdij tot Callebeek: discreet geleverd aan huis in Hemiksem, geregeld via één WhatsApp-bericht.",
        "intro": [
            "Hemiksem is de eerste gemeente voorbij Hoboken langs de Schelde, met de Sint-Bernardusabdij als blikvanger en Callebeek, waar het veer naar Bazel vertrekt, als groene uitloper aan de rivier. Tussen de Heuvelstraat, de Gemeenteplaats en de nieuwere woonbuurten zoals Varenvelden en Scheldeboord wonen mensen die ons vooral op vrijdag- en zaterdagavond contacteren. Een bestelling plaatsen gaat simpel: stuur ons via WhatsApp door welke tank of welke producten u wenst en op welk adres, dan bevestigen wij meteen en spreken wij een tijdstip af.",
            "Vanuit Antwerpen volgen onze bezorgers de Sint-Bernardsesteenweg door Hoboken, de oude verbinding langs de Schelde die rechtstreeks het centrum van Hemiksem binnenloopt; is het daar druk, dan nemen zij de A12 tot Aartselaar en de Kleidaallaan. Die route is kort, maar de steenweg heeft veel lichten en zebrapaden, waardoor wij meestal 25 tot 40 minuten rekenen. Het station Hemiksem ligt op lijn 52 tussen Antwerpen en Puurs, en ook de bussen van De Lijn stoppen in het centrum; wij komen echter steeds tot aan uw voordeur, dus u hoeft nergens naartoe.",
            "Of u nu een appartement aan de Scheldeboord bewoont, een rijhuis in de Heuvelstraat of een woning in Varenvelden: kies de tank die bij de grootte van uw gezelschap past. De 2KG is compact en volstaat voor een avond met enkele vrienden, de 4KG en 10KG zijn er voor grotere groepen. Alle formaten plus crackers en slagroompatronen staan in ons <a href=\"/assortiment/\">assortiment</a>. Wij controleren de leeftijd: enkel 18-plussers kunnen bij ons bestellen. Betalen gebeurt pas bij levering, cash of met Payconiq, en wij raden u aan vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> te lezen.",
        ],
        "wijken": "Hemiksem-Centrum, Gemeenteplaats, Heuvelstraat, Sint-Bernardusabdij, Callebeek, Scheldeboord, Varenvelden, Station Hemiksem",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook aan Callebeek, bij het veer naar Bazel?", "Zeker, Callebeek ligt gewoon in Hemiksem en dus in ons bezorggebied. Wij leveren aan de deur van uw adres; aan de veersteiger of op de dijk zelf bezorgen wij niet. Aan de overkant van de Schelde bezorgen wij ook, maar onze bezorger rijdt dan via Antwerpen om."],
            ["Welke weg nemen jullie bij file op de Sint-Bernardsesteenweg?", "Dan rijden wij via de A12 tot de afrit Aartselaar en komen wij langs de Kleidaallaan Hemiksem binnen. U merkt daar weinig van: wij melden via WhatsApp wanneer wij vertrekken en of de indicatie van 25 tot 40 minuten verandert."],
            ["Kan ik laat op de avond nog bestellen in Hemiksem?", "Ja, u kunt ons elke dag ook ’s avonds en ’s nachts via WhatsApp bereiken. Houd er rekening mee dat de levertijd op drukke weekendavonden tegen de bovengrens van onze indicatie kan aanleunen. Meer over onze <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a> leest u op de servicepagina."],
        ],
        "nearby": ["hoboken", "aartselaar", "niel"],
        "lat": 51.145, "lon": 4.340,
    },
    {
        "slug": "niel",
        "name": "Niel",
        "kind": "gemeente",
        "title": "Lachgas Niel | Thuisbezorgd in de Rupelstreek",
        "description": "Lachgas bestellen in Niel? Wij bezorgen lachgastanks en patronen in heel Niel, van het centrum tot Hellegat, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Niel",
        "lead": "Lachgas aan huis in Niel en Hellegat, besteld via WhatsApp en afgerekend bij levering, cash of met Payconiq.",
        "intro": [
            "Niel is een echte Rupelgemeente: ingeklemd tussen Schelle, Boom en de Rupel, met een verleden van steenbakkerijen dat u nog ziet aan de oude kleiputten van Walenhoek en het gehucht Hellegat aan het water. Het dorpsleven speelt zich af rond de Dorpsstraat en de Antwerpsestraat, met daaromheen woonwijken die tot aan de Rupeldijk reiken. Woont u ergens in Niel en wilt u lachgas laten leveren? Stuur ons dan een WhatsApp-bericht met uw bestelling en adres; wij antwoorden snel, bevestigen de prijs en laten weten wanneer onze bezorger vertrekt.",
            "De rit vanuit Antwerpen loopt meestal over de A12 richting Boom en van daar via de N148 het dorp binnen; een alternatief is de Sint-Bernardsesteenweg door Hoboken, Hemiksem en Schelle. Niel ligt wat verder dan de eerste zuidrand, en op zaterdagavond kan de A12 vertragen, dus geven wij een indicatie van meestal 25 tot 40 minuten. Wie het openbaar vervoer kent, weet dat het station Niel op lijn 52 richting Puurs ligt en dat De Lijn via de Antwerpsestraat rijdt. Onze bezorgers rijden simpelweg tot uw voordeur, wat voor u het gemakkelijkst is.",
            "Een familiefeest in een huis aan de Rupeldijk, een avond met vrienden in een appartement in het centrum of een feestje bij iemand in Hellegat: u kiest het formaat dat past. Voor enkele personen is de 2KG-tank handig en compact, voor een grotere groep is de 4KG of de 10KG de logische keuze. Ook crackers en slagroompatronen kunt u in hetzelfde bericht meebestellen (zie ons <a href=\"/assortiment/\">assortiment</a>). Bestellen kan uitsluitend wanneer u 18 jaar of ouder bent; onze bezorger mag naar uw identiteitskaart vragen. U betaalt bij levering, cash of via Payconiq. Neem vooraf onze tips over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door.",
        ],
        "wijken": "Niel-Centrum, Dorpsstraat, Antwerpsestraat, Hellegat, Walenhoek, Rupeldijk, Station Niel",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Is Hellegat even snel bereikbaar als het centrum van Niel?", "Hellegat ligt aan de Rupel, iets buiten het centrum, en vraagt een paar minuten extra rijden. In de praktijk valt dat binnen onze indicatie van 25 tot 40 minuten; bij vertrek krijgt u via WhatsApp een preciezer tijdstip."],
            ["Kunnen jullie ook naar Schelle of Boom leveren vanuit Niel?", "Ja, de hele Rupelstreek hoort bij ons werkgebied. Boom heeft een eigen pagina met uitleg over routes en levertijden; bekijk daarvoor <a href=\"/bezorggebied/boom/\">lachgas bezorgen in Boom</a>."],
            ["Kan ik slagroompatronen apart bestellen in Niel?", "Ja, slagroompatronen en crackers kunt u los of samen met een tank bestellen; vermeld het gewoon in uw WhatsApp-bericht. De bezorger brengt alles in één rit mee. Bekijk de details op de pagina over <a href=\"/product/slagroompatronen/\">slagroompatronen</a>."],
        ],
        "nearby": ["boom", "hemiksem", "aartselaar"],
        "lat": 51.111, "lon": 4.333,
    },
    {
        "slug": "boechout",
        "name": "Boechout",
        "kind": "gemeente",
        "title": "Lachgas Boechout | Vlot bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Boechout? Wij bezorgen lachgastanks en patronen in Boechout en Vremde, meestal binnen 25 tot 40 minuten.",
        "h1": "Lachgas bezorgen in Boechout",
        "lead": "Lachgas thuisgeleverd in Boechout en Vremde: één WhatsApp-bericht volstaat, u betaalt pas aan de deur.",
        "intro": [
            "Boechout ligt net voorbij Mortsel langs de Provinciesteenweg richting Lier en bestaat uit twee kernen: Boechout zelf, met de Heuvelstraat als winkelas en de Sint-Bavokerk als herkenningspunt, en het landelijke Vremde aan de oostkant. Daartussen en errond liggen woonstraten, hoeves en natuurgebied zoals de Boshoek. Wilt u lachgas laten bezorgen op een adres in Boechout of Vremde? Stuur ons via WhatsApp uw bestelling en het adres, en wij bevestigen snel met een prijs en een verwachte aankomsttijd.",
            "Vanuit Antwerpen nemen onze bezorgers de Krijgsbaan (R11) of de Liersesteenweg door Mortsel, die in Boechout Provinciesteenweg heet; voor Vremde kan de route ook via Borsbeek lopen. Het zijn drukke steenwegen met heel wat verkeerslichten, zeker in de avondspits, en daarom rekenen wij een levertijd van meestal 25 tot 40 minuten. Het station Boechout ligt op lijn 15 tussen Antwerpen en Lier, en De Lijn bedient zowel het centrum als Vremde; voor onze dienst speelt dat geen rol, want wij komen aan uw voordeur en niet aan een halte.",
            "Boechout heeft een actief verenigingsleven en is bekend van het Sfinks-festival, maar de meeste bestellingen komen gewoon van gezinnen en vriendengroepen die thuis iets vieren. Voor een klein gezelschap past de 2KG-tank; wordt het groter, dan is de 4KG of de 10KG geschikter. Bekijk de formaten, crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan 18-plussers en vragen bij twijfel uw identiteitskaart. Afrekenen doet u bij levering, cash of via Payconiq. Lees voor uw bestelling onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig omgaan met lachgas</a>.",
        ],
        "wijken": "Boechout-Centrum, Heuvelstraat, Sint-Bavokerk, Provinciesteenweg, Station Boechout, Vremde, Boshoek",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Vremde?", "Ja, Vremde is een deelgemeente van Boechout en zit volledig in ons bezorggebied. Omdat het iets verder van Antwerpen ligt, komt de levertijd daar vaker in de buurt van 40 minuten dan van 25."],
            ["Ik woon vlak bij het station van Boechout. Kunnen jullie daar afleveren?", "Wij bezorgen aan de deur van uw woning of verblijfsadres, ook in de straten rond het station. Op het perron, aan de fietsenstalling of op de parking leveren wij niet; dat is voor u en voor ons discreter."],
            ["Hoe betaal ik in Boechout?", "Bij levering, cash of via Payconiq op uw GSM. De prijs wordt vooraf via WhatsApp bevestigd, zodat u exact weet wat u aan de deur betaalt. Meer hierover leest u op de pagina <a href=\"/betalen-bij-levering/\">betalen bij levering</a>."],
        ],
        "nearby": ["mortsel", "hove", "lint"],
        "lat": 51.159, "lon": 4.493,
    },
    {
        "slug": "hove",
        "name": "Hove",
        "kind": "gemeente",
        "title": "Lachgas Hove | Discreet bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Hove? Lachgastanks en patronen discreet aan huis geleverd in heel Hove, meestal binnen 25 tot 40 minuten. Enkel voor 18+.",
        "h1": "Lachgas bezorgen in Hove",
        "lead": "Lachgas discreet thuisgeleverd in Hove, van de Kapelstraat tot Weyninckhoven, geregeld via WhatsApp.",
        "intro": [
            "Hove is een kleine, groene woongemeente tussen Mortsel, Edegem, Kontich, Lint en Boechout. Het dorpscentrum rond de Kapelstraat en de Sint-Laurentiuskerk is compact, met daarrond villawijken, de buurt Weyninckhoven en het domein Frijthout. Wie hier woont, bestelt graag zonder gedoe en zonder dat de buren meekijken; precies daarom werkt onze dienst via WhatsApp. U stuurt een bericht met uw bestelling en adres, wij bevestigen de prijs en de verwachte levertijd, en onze bezorger komt onopvallend tot aan uw deur.",
            "Vanuit Antwerpen bereiken wij Hove via Berchem en Mortsel, over de Mortselsesteenweg, of via de Krijgsbaan en de Boechoutsesteenweg; vanuit het zuiden kan het ook langs Edegem en Kontich. De afstand is beperkt, maar het traject loopt door woonzones met zone 30 en verkeerslichten, waardoor wij een indicatie van meestal 25 tot 40 minuten hanteren. Het station Hove op lijn 15 en de bussen van De Lijn via de Mortselsesteenweg verbinden de gemeente met de stad, maar u hoeft daar niet op te wachten: wij brengen uw bestelling aan huis.",
            "Een verjaardagsfeest in een villa aan de Lintsesteenweg, een etentje met vrienden in Weyninckhoven of een rustige avond in een appartement in het centrum: u kiest de tank op maat van uw groep. De 2KG is compact voor een handvol mensen, de 4KG en 10KG zijn er voor meer gasten. Alle formaten, crackers en slagroompatronen vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Bestellen kan enkel vanaf 18 jaar; onze bezorger kan uw identiteitskaart vragen. Betalen doet u bij levering, cash of via Payconiq, en wij vragen u vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door te nemen.",
        ],
        "wijken": "Hove-Centrum, Kapelstraat, Station Hove, Mortselsesteenweg, Boechoutsesteenweg, Lintsesteenweg, Weyninckhoven, Frijthout",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe discreet verloopt een levering in Hove?", "Onze bezorger komt met een onopvallende wagen, belt aan op het afgesproken adres en overhandigt de verzegelde tank aan de deur. Er staat niets op de verpakking of het voertuig dat de buren iets vertelt, en wij bezorgen niet op straat."],
            ["Ligt Hove niet te dicht bij Mortsel voor een aparte levertijd?", "Hove grenst inderdaad aan Mortsel, maar ligt net buiten de Antwerpse districten en wordt via smallere woonstraten bereikt. Daarom geven wij meestal 25 tot 40 minuten op; in rustige periodes zijn wij er vaak sneller, maar dat beloven wij niet vooraf."],
            ["Mogen jullie aan mijn kind van 17 leveren als ik erbij ben?", "Nee. De verkoop van lachgas aan minderjarigen is in België sinds 2021 verboden, en wij leveren uitsluitend aan personen van 18 jaar en ouder die zich kunnen identificeren. Lees meer op onze pagina over <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole</a>."],
        ],
        "nearby": ["mortsel", "edegem", "boechout"],
        "lat": 51.153, "lon": 4.470,
    },
    {
        "slug": "lint",
        "name": "Lint",
        "kind": "gemeente",
        "title": "Lachgas Lint | Snel aan huis via WhatsApp",
        "description": "Lachgas bestellen in Lint? Wij leveren lachgastanks en patronen aan huis in Lint, meestal binnen 25 tot 40 minuten. Alleen voor 18+.",
        "h1": "Lachgas bezorgen in Lint",
        "lead": "Lachgas aan huis in Lint, van de Koning Albertstraat tot Lachenen, besteld via WhatsApp en betaald bij levering.",
        "intro": [
            "Lint is een kleine, rustige gemeente tussen Kontich, Hove, Boechout, Lier en Duffel. Het leven concentreert zich rond de Koning Albertstraat en de Liersesteenweg, met woonwijken tot aan de spoorlijn en het groene Lachenen aan de zuidkant. Ook hier bezorgen wij aan huis, net zoals in de grotere buurgemeenten. Een bestelling plaatsen doet u via WhatsApp: u stuurt het gewenste formaat of product door samen met uw adres, wij bevestigen de prijs en het tijdstip, en u hoeft verder niets te regelen.",
            "Onze bezorgers rijden vanuit Antwerpen via de E19 tot de afrit Kontich en vervolgens langs Kontich-Kazerne naar Lint, of over de Mechelsesteenweg wanneer de autosnelweg vastzit. De omweg door de zuidrand verklaart waarom wij voor Lint meestal 25 tot 40 minuten aangeven, iets ruimer dan voor Mortsel of Wilrijk. Met de trein komt u aan in het station Kontich-Lint, dat vlak over de gemeentegrens op het grondgebied van Kontich ligt; De Lijn rijdt door de Koning Albertstraat. Voor onze levering telt alleen uw voordeur.",
            "Of het nu gaat om een tuinfeest in Lachenen, een verjaardag in een rijhuis aan de Liersesteenweg of een avond met vrienden in het centrum: u bepaalt zelf het formaat. De 2KG-tank is handig voor een klein gezelschap, de 4KG of de 10KG wanneer u meer gasten verwacht. Ons volledige <a href=\"/assortiment/\">assortiment</a> bevat ook crackers en slagroompatronen. Bestellen is voorbehouden aan 18-plussers en onze bezorger controleert dat zo nodig met uw identiteitskaart. U betaalt pas bij levering, cash of via Payconiq. Lees ook even onze uitleg over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Lint-Centrum, Koning Albertstraat, Liersesteenweg, Duffelsesteenweg, Lachenen, buurt rond het station Kontich-Lint",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Waarom duurt een levering in Lint iets langer dan in Mortsel?", "Lint ligt achter Kontich en Hove, zonder eigen afrit van de autosnelweg, zodat onze bezorger altijd een stukje door de buurgemeenten rijdt. Daarom spreken wij van meestal 25 tot 40 minuten; via WhatsApp krijgt u telkens een actuele inschatting."],
            ["Kunnen jullie ook aan het station Kontich-Lint afleveren?", "Nee, wij bezorgen enkel aan een woon- of verblijfsadres, niet op straat, aan een station of op een parking. Woont u in de straten rond het station, dan komen wij natuurlijk gewoon aan uw deur."],
            ["Bezorgen jullie in Lint ook in het weekend?", "Ja, ook op vrijdag, zaterdag en zondag en tijdens de avonduren. Op drukke weekendavonden kan de levertijd richting de bovengrens van onze indicatie gaan. Meer informatie vindt u op onze pagina over <a href=\"/lachgas-weekendbezorging/\">weekendbezorging</a>."],
        ],
        "nearby": ["kontich", "hove", "boechout"],
        "lat": 51.128, "lon": 4.491,
    },
    {
        "slug": "ranst",
        "name": "Ranst",
        "kind": "gemeente",
        "title": "Lachgas Ranst | Snel bezorgd langs de E313",
        "description": "Lachgas bestellen in Ranst? Lachgastanks en patronen aan huis geleverd in Ranst, Broechem, Emblem en Oelegem, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Ranst",
        "lead": "Lachgas aan huis in Ranst, Broechem, Emblem en Oelegem: bestellen via WhatsApp, betalen bij levering.",
        "intro": [
            "Ranst is een uitgestrekte plattelandsgemeente ten oosten van Antwerpen met vier kernen: Ranst zelf, Broechem, Emblem en Oelegem aan het Albertkanaal. Het is een gemeente van bossen en kasteeldomeinen, met het Vrieselhof en het Zevenbergenbos als bekendste groene plekken en het Fort van Oelegem als stille getuige van de fortengordel. Wij bezorgen in alle vier de deelgemeenten. Bestellen gaat via WhatsApp: u stuurt uw keuze en adres door, wij bevestigen de prijs en melden wanneer onze bezorger onderweg is.",
            "De snelste weg vanuit Antwerpen is de E313 richting Hasselt tot de afrit Ranst, van waar Ranst-centrum, Broechem en Emblem snel bereikbaar zijn; voor Oelegem rijden wij vaak via Wijnegem langs het Albertkanaal. Omdat de E313 aan het knooppunt Antwerpen-Oost geregeld dichtslibt, rekenen wij meestal 25 tot 40 minuten, met Oelegem en Emblem eerder aan de bovengrens. Het openbaar vervoer in Ranst bestaat uit buslijnen van De Lijn richting Antwerpen en Lier; een treinstation is er niet. Wij leveren rechtstreeks aan uw voordeur, waar u ook woont.",
            "Een feest op een hoeve in Broechem, een verjaardag in een nieuwbouwwijk in Ranst-centrum of een avond met vrienden in Emblem: het formaat kiest u op basis van uw gezelschap. Kleine groepen zijn gebaat met de 2KG-tank, grotere met de 4KG of de 10KG. Daarnaast leveren wij crackers en slagroompatronen (zie ons <a href=\"/assortiment/\">assortiment</a>). Wij verkopen uitsluitend aan personen van 18 jaar of ouder en vragen zo nodig een identiteitsbewijs. Betalen doet u bij levering, cash of via Payconiq. Lees vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a>.",
        ],
        "wijken": "Ranst-Centrum, Broechem, Emblem, Oelegem, Vrieselhof, Zevenbergenbos, Fort van Oelegem, Albertkanaal",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie in alle deelgemeenten van Ranst?", "Ja: Ranst, Broechem, Emblem en Oelegem horen alle vier bij ons bezorggebied. Voor Oelegem en Emblem, die het verst van de afrit liggen, rekent u best op het hogere deel van onze indicatie van 25 tot 40 minuten."],
            ["Wat als er file staat op de E313?", "Dan wijken wij uit via Wommelgem en de Herentalsebaan of via Boechout en Vremde, afhankelijk van uw deelgemeente. U krijgt via WhatsApp een bericht als de verwachte aankomsttijd daardoor verschuift."],
            ["Kan ik voor een feest op een hoeve in Broechem verschillende formaten combineren?", "Ja, u kunt formaten combineren of crackers en slagroompatronen toevoegen; vermeld alles in uw bericht, dan bevestigen wij het geheel vooraf, inclusief de prijs. Hulp bij het kiezen vindt u in onze gids <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">2KG, 4KG of 10KG</a>."],
        ],
        "nearby": ["wommelgem", "wijnegem", "boechout"],
        "lat": 51.190, "lon": 4.565,
    },
    {
        "slug": "wommelgem",
        "name": "Wommelgem",
        "kind": "gemeente",
        "title": "Lachgas Wommelgem | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Wommelgem? Wij bezorgen lachgastanks en patronen aan huis, van de Kerkplaats tot Kandonklaar, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Wommelgem",
        "lead": "Lachgas thuisgeleverd in Wommelgem, net buiten Deurne: besteld via WhatsApp, discreet aan de deur, betalen bij levering.",
        "intro": [
            "Wommelgem sluit naadloos aan op Deurne en Borsbeek, maar is wel een zelfstandige gemeente met een eigen karakter: een dorpskern rond de Kerkplaats, de drukke Herentalsebaan die er dwars doorheen loopt, de woonwijk Kandonklaar en het Fort 2 uit de Brialmontgordel dat nu een groene long is. Langs de Uilenbaan en de Dasstraat liggen bedrijven en winkels. Bestellen bij ons doet u met één WhatsApp-bericht: vermeld het gewenste product en uw adres, dan krijgt u van ons een bevestiging met prijs en verwachte aankomsttijd.",
            "Vanuit Antwerpen is Wommelgem via de E313 en de E34 bereikbaar, met een eigen afrit Wommelgem, maar onze bezorgers kiezen vaak voor de Herentalsebaan door Deurne, die rechtstreeks naar het centrum leidt. Rond het knooppunt Antwerpen-Oost en aan de verkeerslichten op de Herentalsebaan verliest u in de spits makkelijk tijd, en daarom geven wij meestal 25 tot 40 minuten op. De Lijn verbindt Wommelgem met Deurne en de stad over diezelfde Herentalsebaan. Wij komen tot aan uw deur, dus van het openbaar vervoer hoeft u niets te weten.",
            "Een barbecue in een tuin in Kandonklaar, een verjaardag in een appartement aan de Herentalsebaan of een avond met vrienden rond de Kerkplaats: kies het formaat dat bij uw gezelschap past. De 2KG volstaat voor een kleine groep, de 4KG en 10KG zijn bedoeld voor meer mensen. In ons <a href=\"/assortiment/\">assortiment</a> vindt u ook crackers en slagroompatronen. Wij leveren uitsluitend aan 18-plussers en controleren bij twijfel de identiteitskaart. Betalen kan bij levering, cash of met Payconiq. Neem vooraf zeker onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Wommelgem-Centrum, Kerkplaats, Herentalsebaan, Fort 2, Kandonklaar, Autolei, Uilenbaan, Dasstraat",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Wommelgem grenst aan Deurne; waarom is de levertijd dan langer?", "Deurne is een Antwerps district dat wij vanuit de stad heel direct bereiken, terwijl Wommelgem achter de Ring en de E313 ligt. Dat scheelt een paar kilometer en vaak een file, vandaar meestal 25 tot 40 minuten in plaats van 20 tot 30."],
            ["Leveren jullie ook in de bedrijvenzone aan de Uilenbaan?", "Wij bezorgen aan de deur van een woon- of verblijfsadres; op parkings of op straat leveren wij niet. Heeft u een andere situatie, bespreek die dan vooraf via WhatsApp, zodat wij samen bekijken wat mogelijk is."],
            ["Hoe snel reageren jullie op een WhatsApp-bericht uit Wommelgem?", "Doorgaans binnen enkele minuten, ook ’s avonds en in het weekend. U krijgt een bevestiging van uw bestelling en de prijs, en zodra onze bezorger vertrekt een tweede bericht met de verwachte aankomst. Hoe dat precies werkt, leest u op onze pagina <a href=\"/werkwijze/\">werkwijze</a>."],
        ],
        "nearby": ["deurne", "wijnegem", "ranst"],
        "lat": 51.203, "lon": 4.520,
    },
    {
        "slug": "wijnegem",
        "name": "Wijnegem",
        "kind": "gemeente",
        "title": "Lachgas Wijnegem | Thuisbezorgd via WhatsApp",
        "description": "Lachgas bestellen in Wijnegem? Lachgastanks en patronen aan huis bezorgd in Wijnegem, meestal binnen 25 tot 40 minuten. Alleen 18+, betalen bij levering.",
        "h1": "Lachgas bezorgen in Wijnegem",
        "lead": "Lachgas aan huis in Wijnegem, langs de Turnhoutsebaan en het Albertkanaal, snel geregeld via WhatsApp.",
        "intro": [
            "Wijnegem is bij veel Antwerpenaren vooral bekend van het grote shoppingcenter aan de Turnhoutsebaan, maar het is ook een woongemeente met een eigen dorpskern rond het Marktplein, het cultuurcentrum ’t Gasthuis en het kasteeldomein Pulhof. Aan de noordkant stroomt het Albertkanaal, richting Deurne ligt het groene domein Ertbrugge. Wie in Wijnegem woont en lachgas wil laten leveren, stuurt ons via WhatsApp een bericht met het gewenste product en het adres; wij bevestigen de prijs en zeggen erbij wanneer u ons mag verwachten.",
            "Onze bezorgers rijden vanuit de stad via de Bisschoppenhoflaan en de Turnhoutsebaan door Deurne rechtstreeks naar Wijnegem, of via de E34 en de afrit Wommelgem wanneer de Turnhoutsebaan stilstaat. Rond het shoppingcenter is het op zaterdag en tijdens de solden erg druk, en ook de Houtlaan rond het centrum kent in de spits oponthoud; vandaar onze indicatie van meestal 25 tot 40 minuten. Tram 10 van De Lijn heeft zijn eindhalte in Wijnegem en bussen rijden via de Turnhoutsebaan, maar u hoeft nergens heen: wij komen tot aan uw deur.",
            "Een feestje in een appartement aan het Marktplein, een verjaardag in een woonwijk langs de Houtlaan of een avond met vrienden in een huis bij Ertbrugge: het formaat van de tank hangt af van hoeveel mensen u verwacht. Voor een klein groepje is de 2KG geschikt, voor meer volk de 4KG of de 10KG. Ons <a href=\"/assortiment/\">assortiment</a> bevat daarnaast crackers en slagroompatronen. Bestellen kan uitsluitend als u 18 jaar of ouder bent; onze bezorger mag uw identiteitskaart vragen. U betaalt bij levering, cash of via Payconiq. Lees voor uw bestelling onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Wijnegem-Centrum, Marktplein, Turnhoutsebaan, Houtlaan, Wijnegem Shopping Center, ’t Gasthuis, Kasteel Pulhof, Ertbrugge, Albertkanaal",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Kunnen jullie leveren aan het shoppingcenter van Wijnegem?", "Nee, wij bezorgen enkel aan een woon- of verblijfsadres, niet op de parking van het shoppingcenter of aan een tramhalte. Woont u in de buurt ervan, dan komen wij gewoon tot aan uw voordeur."],
            ["Hoe lang duurt een levering in Wijnegem op zaterdag?", "Op zaterdag is de Turnhoutsebaan rond het shoppingcenter druk, waardoor wij vaker aan de bovenkant van onze indicatie van 25 tot 40 minuten zitten. Wij kiezen dan dikwijls voor de E34 en melden u via WhatsApp het verwachte tijdstip."],
            ["Ik moet de tank nog een dag bewaren voor het feest. Mag dat?", "Ja. Bewaar de tank rechtop, koel, droog en buiten het bereik van kinderen, en laat ze nooit in de zon of in een warme auto staan. Meer tips staan in ons artikel over <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">een lachgastank bewaren en vervoeren</a>."],
        ],
        "nearby": ["deurne", "schoten", "wommelgem"],
        "lat": 51.228, "lon": 4.520,
    },
    {
        "slug": "kapellen",
        "name": "Kapellen",
        "kind": "gemeente",
        "title": "Lachgas Kapellen | Snel bezorgd in de Noordrand",
        "description": "Lachgas bestellen in Kapellen? Wij leveren lachgastanks en patronen aan huis in Kapellen, Hoogboom en Putte, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Kapellen",
        "lead": "Lachgas aan huis in Kapellen, Hoogboom en Putte-Kapellen: via WhatsApp besteld, discreet aan de deur geleverd.",
        "intro": [
            "Kapellen ligt in de groene Noordrand, boven Ekeren en Brasschaat, en loopt met Putte-Kapellen tot aan de Nederlandse grens. De gemeente is ruim opgezet: een centrum rond het station en de Antwerpsesteenweg, de kern Hoogboom aan de kant van Brasschaat, villawijken als Zilverenhoek en Kapellenbos en uitgestrekte bossen zoals het Mastenbos. Wij bezorgen in heel Kapellen. U bestelt door ons via WhatsApp te laten weten welk product u wenst en op welk adres; wij bevestigen prijs en tijdstip en komen aan uw deur.",
            "Vanuit Antwerpen rijden onze bezorgers over de A12 richting Bergen op Zoom of via Ekeren over de Kapelsesteenweg, die in Kapellen overgaat in de Antwerpsesteenweg. De afstand is groter dan naar Brasschaat of Ekeren, en de steenweg loopt door woonkernen met lichten en zone 30, zodat wij voor Kapellen meestal 25 tot 40 minuten aangeven; voor Putte eerder het bovenste deel daarvan. Het station Kapellen ligt op lijn 12 tussen Antwerpen en Essen en De Lijn rijdt over de steenweg, maar u blijft gewoon thuis: wij bezorgen tot aan de voordeur.",
            "Een tuinfeest in Kapellenbos, een verjaardag in een appartement bij het station of een avond met vrienden in Hoogboom: kies de tank die bij uw gezelschap past. De 2KG is bedoeld voor een kleine groep, de 4KG en 10KG voor meer gasten. Wie crackers of slagroompatronen zoekt, geeft dat gewoon aan in de bestelling (zie ons <a href=\"/assortiment/\">assortiment</a>). Wij leveren uitsluitend aan personen vanaf 18 jaar en vragen zo nodig uw identiteitskaart. Betalen doet u bij levering, cash of via Payconiq. Lees vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> en kom met vragen gerust bij ons terecht via WhatsApp.",
        ],
        "wijken": "Kapellen-Centrum, Station Kapellen, Antwerpsesteenweg, Hoogboom, Putte-Kapellen, Zilverenhoek, Kapellenbos, Mastenbos",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Putte, vlak bij de grens?", "Ja, het Belgische deel van Putte dat bij Kapellen hoort, bedienen wij gewoon. Over de grens, in Nederland, leveren wij niet. Omdat Putte het verste punt van ons traject is, rekent u er best op 40 minuten in plaats van 25."],
            ["Hoe komen jullie vanuit Antwerpen naar Kapellen?", "Meestal via de A12 richting Bergen op Zoom, of door Ekeren en Brasschaat over de Kapelsesteenweg wanneer de A12 vaststaat. Onze bezorger kiest ter plaatse de vlotste weg en houdt u via WhatsApp op de hoogte."],
            ["Gelden er in Kapellen andere regels dan in Antwerpen?", "De basis is overal in België dezelfde: het Koninklijk Besluit van 11 maart 2024 beperkt verkoop, vervoer en bezit van lachgas tot medische, technische en culinaire doeleinden, en verkoop aan minderjarigen is sinds 2021 verboden. Gemeenten kunnen daarbovenop eigen politiereglementen hebben; raadpleeg bij twijfel <a href=\"https://www.belgium.be\">belgium.be</a> of uw gemeente."],
        ],
        "nearby": ["ekeren", "brasschaat", "stabroek"],
        "lat": 51.313, "lon": 4.433,
    },
    {
        "slug": "stabroek",
        "name": "Stabroek",
        "kind": "gemeente",
        "title": "Lachgas Stabroek | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Stabroek? Lachgastanks en patronen aan huis geleverd in Stabroek, Hoevenen en Putte, meestal binnen 25 tot 40 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Stabroek",
        "lead": "Lachgas aan huis in Stabroek, Hoevenen en Putte-Stabroek: één WhatsApp-bericht, betalen bij levering.",
        "intro": [
            "Stabroek is een poldergemeente ten noorden van Ekeren, tussen de A12 en de bossen van Kapellen, met de deelgemeente Hoevenen in het zuiden en Putte-Stabroek tegen de Nederlandse grens. De Dorpsstraat vormt het hart van Stabroek zelf, het domein Ravenhof bij Putte is het bekendste stukje groen, en de open polders grenzen aan het havengebied. Wij bezorgen in alle drie de kernen. Een bestelling plaatst u via WhatsApp met het gewenste product en uw adres; wij bevestigen en geven de verwachte aankomsttijd door, zodat u weet wanneer u ons kunt verwachten.",
            "Onze bezorgers nemen vanuit Antwerpen de A12 richting Bergen op Zoom tot de afrit Stabroek, een vlotte rit zolang het havenverkeer meezit; bij problemen rijden zij via Ekeren en Hoevenen over de gewone wegen. Door de afstand en het vrachtverkeer op de A12 houden wij een indicatie van meestal 25 tot 40 minuten aan, met Putte als verste punt. Stabroek heeft geen treinstation; het openbaar vervoer verloopt via de bussen van De Lijn naar Ekeren en Antwerpen. Voor onze levering is dat niet relevant, want wij komen tot aan uw deur.",
            "Een barbecue in Hoevenen, een verjaardagsfeest in een nieuwbouw in Stabroek-centrum of een gezellige avond in een hoeve aan de rand van de polder: u kiest het formaat op basis van uw gezelschap. De 2KG-tank past bij een kleine groep, de 4KG en 10KG bij grotere feesten. Crackers en slagroompatronen vindt u eveneens in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan 18-plussers en vragen bij twijfel een identiteitsbewijs. U betaalt pas bij levering, cash of via Payconiq. Lees voor u bestelt onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig omgaan met lachgas</a>.",
        ],
        "wijken": "Stabroek-Centrum, Dorpsstraat, Hoevenen, Putte-Stabroek, Ravenhof, Hoogeind, Laageind, Stabroekse polders",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Hoevenen?", "Ja, Hoevenen is een deelgemeente van Stabroek en ligt zelfs iets dichter bij Antwerpen dan het centrum, dus daar zijn wij vaak aan de onderkant van onze indicatie van 25 tot 40 minuten."],
            ["Kunnen jullie na een avondshift in de haven nog leveren?", "Wij zijn elke dag ook ’s avonds en ’s nachts via WhatsApp bereikbaar en bezorgen aan uw woonadres in Stabroek, Hoevenen of Putte. Leveren in het havengebied zelf of aan een bedrijfspoort doen wij niet. Zie ook onze pagina over <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
            ["Moet ik thuis zijn op het afgesproken moment?", "Ja, de bestelling wordt persoonlijk overhandigd aan iemand van 18 jaar of ouder die zich kan identificeren. Wij laten geen tank achter aan de deur of bij de buren. Loopt u vertraging op, laat het dan even weten via WhatsApp, dan passen wij het tijdstip aan."],
        ],
        "nearby": ["ekeren", "kapellen", "brasschaat"],
        "lat": 51.331, "lon": 4.372,
    },
    {
        "slug": "kalmthout",
        "name": "Kalmthout",
        "kind": "gemeente",
        "title": "Lachgas Kalmthout | Snel aan huis via WhatsApp",
        "description": "Lachgas bestellen in Kalmthout? Wij bezorgen lachgastanks en patronen aan huis in Kalmthout, Heide, Achterbroek en Nieuwmoer.",
        "h1": "Lachgas bezorgen in Kalmthout",
        "lead": "Lachgas aan huis in Kalmthout, Heide, Achterbroek en Nieuwmoer, geregeld via WhatsApp en betaald bij levering.",
        "intro": [
            "Kalmthout is de gemeente van de Kalmthoutse Heide en het Arboretum, een ruim grondgebied aan de Noordrand met verspreide kernen: Kalmthout-centrum rond het station en de Kapellensteenweg, de kern Heide met een eigen station, het landelijke Achterbroek en Nieuwmoer tegen de grens, plus de buurt Kijkuit. Tussen de kernen liggen bossen, heide en weilanden. Wij bezorgen in heel Kalmthout. Bestellen gebeurt via WhatsApp: u stuurt het gewenste product en uw adres door, wij bevestigen de prijs en laten weten wanneer onze bezorger vertrekt.",
            "Vanuit Antwerpen rijden onze bezorgers door Ekeren en Kapellen over de Kapelsesteenweg en de Kapellensteenweg, of via de A12 tot Kapellen en dan oostwaarts. Kalmthout ligt duidelijk verder dan de eerste rand, en de laatste kilometers lopen over tweevaksbanen door bos en dorp, dus houden wij een indicatie van meestal 25 tot 40 minuten aan, met Nieuwmoer en Achterbroek eerder aan de bovengrens. Op lijn 12 stoppen de treinen in Heide, Kalmthout en Kijkuit, en De Lijn verbindt de kernen met Kapellen; voor onze dienst komt u gewoon naar uw eigen voordeur.",
            "Een tuinfeest in Heide, een verjaardag in een villa aan de rand van het Arboretum of een avond met vrienden in Achterbroek: het formaat kiest u naar uw gezelschap. De 2KG past bij een kleine groep, de 4KG en de 10KG bij een grotere. Crackers en slagroompatronen staan eveneens in ons <a href=\"/assortiment/\">assortiment</a>. Wij verkopen uitsluitend aan 18-plussers en controleren zo nodig de identiteitskaart. Betalen doet u bij levering, cash of via Payconiq. Neem vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door; vragen beantwoorden wij graag via WhatsApp.",
        ],
        "wijken": "Kalmthout-Centrum, Heide, Achterbroek, Nieuwmoer, Kijkuit, Kapellensteenweg, Kalmthoutse Heide, Arboretum Kalmthout, Station Kalmthout",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Nieuwmoer en Achterbroek?", "Ja, alle kernen van Kalmthout horen bij ons bezorggebied. Nieuwmoer en Achterbroek liggen het verst van Antwerpen, zodat u daar best rekent op het hogere deel van onze indicatie van 25 tot 40 minuten."],
            ["Bezorgen jullie op het grenspark of aan een vakantiewoning bij de Heide?", "Op parkings, in het natuurgebied of aan de ingang van het grenspark leveren wij niet. Aan een vakantiewoning of B&B op Belgisch grondgebied kan wel, op voorwaarde dat iemand van 18 jaar of ouder de bestelling persoonlijk aanneemt en zich kan identificeren."],
            ["Wat doe ik met een lege tank in Kalmthout?", "Een lege lachgastank hoort nooit bij het restafval of in de PMD-zak; vraag bij het recyclagepark van uw gemeente na hoe zij drukhouders aannemen. Onze uitleg daarover vindt u in het artikel over <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">een lege lachgasfles inleveren</a>."],
        ],
        "nearby": ["kapellen", "essen", "brasschaat"],
        "lat": 51.384, "lon": 4.468,
    },
    {
        "slug": "essen",
        "name": "Essen",
        "kind": "gemeente",
        "title": "Lachgas Essen | Thuisbezorgd tot aan de grens",
        "description": "Lachgas bestellen in Essen? Lachgastanks en patronen aan huis geleverd in Essen, Wildert, Hoek en Horendonk, meestal binnen 25 tot 40 minuten.",
        "h1": "Lachgas bezorgen in Essen",
        "lead": "Lachgas aan huis in Essen, Wildert, Hoek en Horendonk: besteld via WhatsApp, geleverd aan de deur, uitsluitend op Belgisch grondgebied.",
        "intro": [
            "Essen is de noordelijkste gemeente van de provincie Antwerpen, met Roosendaal als Nederlandse buur en het station als historisch grensstation op lijn 12. Naast Essen-centrum en de wijk rond het station telt de gemeente de kernen Wildert, met een eigen halte, Hoek, Horendonk en Heikant, omringd door bossen en het grenspark van de Kalmthoutse Heide. Het Karrenmuseum en de Kiekenhoeve zijn bekende trekpleisters. Wij bezorgen in alle kernen van Essen. Bestellen doet u via WhatsApp met het gewenste product en uw adres; wij bevestigen de prijs en het verwachte tijdstip.",
            "De rit vanuit Antwerpen voert door Ekeren, Kapellen en Kalmthout, met de Kalmthoutsesteenweg als laatste stuk tot in het centrum van Essen; onze bezorgers blijven daarbij op Belgisch grondgebied en rijden niet via Nederland om. Essen is het verste punt van onze Noordrand, en daarom valt de levertijd hier meestal aan de bovenkant van onze indicatie van 25 tot 40 minuten; bestel liefst wat op voorhand. De trein rijdt vanuit Antwerpen via Kapellen en Kalmthout tot Essen en verder naar Roosendaal, en De Lijn verbindt de kernen; wij komen echter tot aan uw deur.",
            "Een familiefeest in Wildert, een verjaardag in een rijhuis bij het station of een avond met vrienden in Horendonk: het formaat kiest u op maat van uw gezelschap. De 2KG-tank volstaat voor enkele personen, de 4KG en 10KG zijn er voor grotere groepen. Crackers en slagroompatronen vindt u ook in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan 18-plussers met een geldig identiteitsbewijs en alleen op adressen in België; voor Roosendaal of Nispen kunnen wij niets betekenen. U betaalt bij levering, cash of via Payconiq. Lees vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Essen-Centrum, Station Essen, Stationsstraat, Wildert, Hoek, Horendonk, Heikant, Karrenmuseum, Kiekenhoeve",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Ik woon net over de grens in Nederland. Kunnen jullie toch leveren?", "Nee. Wij bezorgen uitsluitend op adressen in België, ook al ligt Roosendaal op een paar kilometer van Essen. Een afspraak aan de grens of op een parking maken wij evenmin; de levering gebeurt altijd aan een Belgisch woon- of verblijfsadres."],
            ["Waarom raden jullie aan om in Essen wat vroeger te bestellen?", "Essen ligt het verst van Antwerpen van alle gemeenten in onze Noordrand, en de laatste kilometers lopen over gewone steenwegen door Kapellen en Kalmthout. Daardoor zitten wij hier vaker aan de 40 dan aan de 25 minuten; wie vooruitplant, heeft zijn bestelling ruim op tijd."],
            ["Welke wetgeving geldt voor lachgas in Essen?", "Dezelfde als in de rest van België: het Koninklijk Besluit van 11 maart 2024 verbiedt verkoop, vervoer en bezit van lachgas voor andere doeleinden dan medische, technische of culinaire toepassingen, en verkoop aan minderjarigen is sinds 2021 verboden. Aan de overkant van de grens gelden Nederlandse regels, maar daar leveren wij niet. Een feitelijk overzicht leest u in ons artikel over <a href=\"/lachgas-informatie/lachgaswet-belgie-2024/\">de lachgaswet van 2024</a>."],
        ],
        "nearby": ["kalmthout", "kapellen", "brecht"],
        "lat": 51.463, "lon": 4.468,
    },
]
