# -*- coding: utf-8 -*-
# Herschreven gebiedspagina's lachgasantwerpen.be (fase 3): 7 Antwerpse districten, Mortsel en 4 Vlaamse steden.

AREAS = [
    {
        "slug": "antwerpen-centrum", "name": "Antwerpen Centrum", "kind": "district",
        "title": "Lachgas Antwerpen Centrum | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Antwerpen Centrum? Via WhatsApp aan huis bezorgd binnen de Leien en de Singel, van de Meir tot het Sint-Jansplein. Enkel voor 18+.",
        "h1": "Lachgas Antwerpen Centrum",
        "lead": "Bezorgd aan uw deur in het hart van de stad, van de Scheldekaaien tot de Leien. Bestellen doet u met één bericht via WhatsApp.",
        "intro": [
            "Met Antwerpen Centrum bedoelen wij het dichtbebouwde hart van de stad binnen de Leien en de Singel: de historische binnenstad rond de Grote Markt en de Groenplaats, de winkelas van de Meir tot De Keyserlei, de Universiteitsbuurt rond de Ossenmarkt, het Schipperskwartier, Sint-Andries met de Kloosterstraat en de Nationalestraat, de Stationsbuurt met de Diamantwijk en verder noordwaarts de Seefhoek en het Sint-Jansplein. In al die buurten komen wij aan huis. U stuurt een WhatsApp-bericht met wat u wenst en uw adres, wij bevestigen en brengen uw bestelling tot aan de voordeur, ook op een vierde verdieping zonder lift.",
            "Onze bezorgers vertrekken in de stad zelf, dus voor het centrum is er geen snelweg nodig: via de Leien, de Scheldekaaien of de Singel staan zij meestal binnen 20 tot 30 minuten voor uw deur. De lage-emissiezone, de eenrichtingsstraten rond de Meir en de knips in de binnenstad kennen zij van buiten, net als de drukte rond het Astridplein wanneer de premetro bij Opera en Astrid volloopt. Komt u zelf met de tram of de bus van De Lijn naar huis, dan hoeft u niets mee te dragen: wij brengen de tank, u opent de deur.",
            "Een appartement boven een winkel in de Kammenstraat, een kot in de Universiteitsbuurt of een verjaardag in een herenhuis aan de Amerikalei: in het centrum zijn de gezelschappen vaak klein en de ruimtes compact. Dan is een 2KG-tank doorgaans ruim genoeg; voor een groter feest kijkt u in ons <a href=\"/assortiment/\">assortiment</a> naar de 4KG, waar ook crackers en slagroompatronen staan. Wij leveren uitsluitend aan meerderjarigen en vragen uw identiteitskaart als wij twijfelen. Betalen gebeurt bij levering, cash of via Payconiq. Lees voor uw feest ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Grote Markt, Groenplaats, Meir, Centraal Station, Sint-Andries, Universiteitsbuurt, Schipperskwartier, Theaterbuurt, Stadspark, Sint-Jansplein",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de autovrije straten rond de Meir en de Groenplaats?",
             "Ja. Voor adressen in het voetgangersgebied rijden wij tot het dichtstbijzijnde punt dat met de wagen bereikbaar is en leggen wij de laatste meters te voet af. Geef in uw bericht aan via welke zijstraat uw ingang ligt, dan verliezen wij geen tijd met zoeken."],
            ["Ik woon op een kot in de Universiteitsbuurt. Gelden er extra voorwaarden?",
             "Dezelfde als overal: u bent minstens 18 jaar en toont dat bij twijfel met uw identiteitskaart. Wij leveren aan de deur van het kot, niet op straat of op de Ossenmarkt, en vragen u rekening te houden met de regels van uw kotbaas. Meer leest u op onze pagina voor <a href=\"/lachgas-studenten-antwerpen/\">studenten in Antwerpen</a>."],
            ["Wat zegt de Belgische wet over lachgas?",
             "De regels zijn de voorbije jaren sterk aangescherpt: het Koninklijk Besluit van 11 maart 2024 verbiedt de verkoop, het vervoer en het bezit van lachgas voor andere dan medische, technische of voedingsdoeleinden, en verkoop aan minderjarigen is al sinds 2021 verboden. Wij leveren uitsluitend aan volwassenen. Een overzicht van het kader vindt u op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
        ],
        "nearby": ["antwerpen-zuid", "eilandje", "borgerhout"],
        "lat": 51.2194, "lon": 4.4025,
    },
    {
        "slug": "berchem", "name": "Berchem", "kind": "district",
        "title": "Lachgas Berchem | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Berchem? Aan huis bezorgd via WhatsApp, van Oud-Berchem en het station tot Groenenhoek, Pulhof en Nieuw Kwartier. Enkel voor 18+.",
        "h1": "Lachgas Berchem",
        "lead": "Van de Driekoningenstraat tot Groenenhoek: één WhatsApp-bericht en wij staan aan uw deur in Berchem.",
        "intro": [
            "Berchem ligt ten zuidoosten van het centrum en wordt door de Ring R1 in twee gesneden. Aan de stadskant vindt u Oud-Berchem met de Driekoningenstraat, de Statiestraat en het station Antwerpen-Berchem, aan de buitenkant de rustigere woonwijken Groenenhoek, Pulhof, Nieuw Kwartier en Het Rooi tot aan de grens met Mortsel. Ook de Fruithoflaan met haar hoge appartementsblokken en de straten rond het Brilschanspark horen erbij. Wij bezorgen aan beide kanten van de Ring. Stuur ons via WhatsApp uw bestelling en uw adres; wij bevestigen en u hoeft enkel thuis te blijven tot wij aanbellen.",
            "Vanuit de stad is Berchem snel bereikt: over de Singel, via de Grote Steenweg of met de afrit Berchem van de Ring staan onze bezorgers meestal binnen 20 tot 30 minuten aan het districtshuis. Het knooppunt rond het station, waar treinen, trams en bussen van De Lijn samenkomen, is op weekendavonden druk, maar wij kennen de alternatieven langs de Posthofbrug en de Binnensingel. Omdat Berchem op onze dagelijkse weg naar Mortsel en Wilrijk ligt, zijn wij er vaak vroeger dan de indicatie laat vermoeden.",
            "Berchem is een district van verjaardagsfeesten in rijhuizen, housewarmings in de nieuwe appartementen rond het station en rustige avonden bij vrienden in Groenenhoek. Een 2KG-tank past bij een klein gezelschap, een 4KG bij een feest met meer gasten; het volledige <a href=\"/assortiment/\">assortiment</a> met crackers en slagroompatronen bezorgen wij overal in het district. Wij verkopen uitsluitend aan personen van 18 jaar en ouder en controleren bij twijfel de identiteitskaart. U rekent af bij levering, cash of via Payconiq, en wij vragen u om vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door te nemen.",
        ],
        "wijken": "Oud-Berchem, Station Antwerpen-Berchem, Driekoningenstraat, Statiestraat, Groenenhoek, Pulhof, Nieuw Kwartier, Het Rooi, Fruithoflaan, Brilschanspark",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Berchem buiten de Ring, bijvoorbeeld in Groenenhoek of Het Rooi?",
             "Ook daar meestal binnen 20 tot 30 minuten. De wijken buiten de Ring liggen vlak bij onze route richting Mortsel, dus het verschil met Oud-Berchem is klein. Op drukke momenten houden wij u via WhatsApp op de hoogte van het exacte tijdstip."],
            ["Ik kom met de trein aan in Antwerpen-Berchem. Kunnen jullie aan het station leveren?",
             "Nee, wij leveren uitsluitend aan de deur van een woonadres of een gereserveerde locatie, niet op straat of aan het station. Geef het adres van uw bestemming door en wij stemmen het tijdstip af op uw aankomst."],
            ["Waar kan ik in Berchem een lege tank kwijt?",
             "Nooit bij het restafval en nooit op straat. Een lege fles brengt u naar een recyclagepark van de stad Antwerpen; informeer vooraf welk park gasflessen aanvaardt. Hoe dat werkt en waarom het belangrijk is, leest u op <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">lege lachgasfles inleveren</a>."],
        ],
        "nearby": ["zurenborg", "mortsel", "wilrijk"],
        "lat": 51.1945, "lon": 4.4260,
    },
    {
        "slug": "borgerhout", "name": "Borgerhout", "kind": "district",
        "title": "Lachgas Borgerhout | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Borgerhout? Via WhatsApp aan huis bezorgd, van de Turnhoutsebaan en het Laar tot Te Boelaer en de Luitenant Lippenslaan. Enkel 18+.",
        "h1": "Lachgas Borgerhout",
        "lead": "Binnen of buiten de Ring, in Borgerhout komen wij aan uw deur na één berichtje via WhatsApp.",
        "intro": [
            "Borgerhout is het kleinste en dichtstbevolkte district van Antwerpen, met de Turnhoutsebaan als levendige ruggengraat. Binnen de Ring vindt u het Laar, het Moorkensplein met het districtshuis, het Krugerplein en de huizenrijen rond De Roma; buiten de Ring, in Borgerhout extra muros, liggen de groenere straten rond het Te Boelaerpark, de Gitschotellei en de Luitenant Lippenslaan tot aan Deurne. Wij bezorgen in het hele district. Een WhatsApp-bericht met uw bestelling en adres volstaat; wij bevestigen en bellen aan wanneer wij er zijn.",
            "Vanuit het stadscentrum rijden onze bezorgers via de Leien en de Carnotstraat of over de Singel rechtstreeks de Turnhoutsebaan op; naar extra muros nemen zij de Stenenbrug over de Ring. Daardoor is Borgerhout meestal binnen 20 tot 30 minuten bediend. De Turnhoutsebaan is met de trams van De Lijn en het verkeer richting E313 en E34 een drukke as, zeker op vrijdag- en zaterdagavond, maar de zijstraten laten zich vlot aanrijden. Bij de bevestiging krijgt u een realistische tijd en een bericht zodra wij in uw straat zijn.",
            "Van een verjaardag in een rijhuis aan de Kroonstraat tot een avond met vrienden in een appartement aan de Gitschotellei: de meeste bestellingen uit Borgerhout zijn voor kleinere groepen, waarvoor de 2KG-tank uit ons <a href=\"/assortiment/\">assortiment</a> volstaat; voor meer volk kiest u de 4KG. Lachgas crackers en slagroompatronen brengen wij mee als u dat wenst. Wij leveren enkel aan meerderjarigen en kunnen om uw identiteitskaart vragen. Afrekenen doet u aan de deur, cash of via Payconiq. Neem vooraf onze aanbevelingen voor <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Turnhoutsebaan, Laar, Moorkensplein, Krugerplein, De Roma, Stenenbrug, Te Boelaerpark, Gitschotellei, Luitenant Lippenslaan, Spoor Oost",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie zowel in Borgerhout intra muros als extra muros?",
             "Ja, aan beide kanten van de Ring. Het deel binnen de Singel bereiken wij via de Turnhoutsebaan of de Plantin en Moretuslei, het deel erbuiten via de Stenenbrug. De indicatie is in beide gevallen meestal 20 tot 30 minuten."],
            ["Gelden er in Antwerpen eigen regels voor lachgas?",
             "Naast het federale kader, met sinds 11 maart 2024 een Koninklijk Besluit dat verkoop, vervoer en bezit buiten medische, technische of voedingsdoeleinden verbiedt, kan de stad Antwerpen via haar politiecodex eigen regels hanteren voor gebruik in de openbare ruimte. Wij leveren uitsluitend aan volwassenen, aan de deur van een privéadres. Meer uitleg vindt u op <a href=\"/lachgas-informatie/lachgas-regels-antwerpen/\">lachgasregels in Antwerpen</a>."],
            ["Kan ik 's avonds laat nog bestellen in Borgerhout?",
             "Ja, u kunt ons ook 's avonds en 's nachts via WhatsApp bereiken; de voorwaarden staan op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>. Ook dan leveren wij uitsluitend aan de deur van een adres, en op drukke weekendnachten gaat de levertijd eerder richting de bovengrens van de indicatie."],
        ],
        "nearby": ["antwerpen-centrum", "deurne", "zurenborg"],
        "lat": 51.2117, "lon": 4.4356,
    },
    {
        "slug": "deurne", "name": "Deurne", "kind": "district",
        "title": "Lachgas Deurne | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Deurne? Snel aan huis bezorgd via WhatsApp, van Deurne-Dorp en het Rivierenhof tot Kronenburg, Bosuil en Deurne-Zuid. Enkel voor 18+.",
        "h1": "Lachgas Deurne",
        "lead": "Van Deurne-Noord tot Deurne-Zuid: één WhatsApp-bericht en wij komen tot aan uw deur.",
        "intro": [
            "Deurne strekt zich uit van het Albertkanaal en de buurt rond het Sportpaleis in het noorden tot de luchthaven en Mortsel in het zuiden, en is daarmee een van de grootste districten van Antwerpen. Deurne-Noord met Kronenburg en de Bisschoppenhoflaan, Deurne-Dorp rond het Cogelsplein, de wijken rond het Rivierenhof en het Boekenbergpark, en Deurne-Zuid met Eksterlaar, Silsburg en de Ruggeveldlaan: overal komen wij aan huis. Stuur een WhatsApp-bericht met uw bestelling en uw volledige adres, met het busnummer als u in een appartement woont; wij bevestigen en komen eraan.",
            "Vanuit het centrum rijden wij via de Turnhoutsebaan en de Stenenbrug, over de Bisschoppenhoflaan of via de Ring met de afrit richting E313 en E34, afhankelijk van waar u woont. Zo zijn wij in Deurne meestal binnen 20 tot 30 minuten ter plaatse. De trams van De Lijn over de Herentalsebaan en de Turnhoutsebaan en het verkeer naar Wijnegem maken sommige assen druk, maar de woonwijken erachter zijn rustig aan te rijden. Woont u aan de rand richting Wommelgem of Wijnegem, reken dan op het einde van de indicatie.",
            "Deurne is een district van gezinnen, verenigingen en tuinen, en dat zien wij terug in de bestellingen: tuinfeesten in Deurne-Zuid, verjaardagen in de appartementen van Kronenburg, een avond met vrienden na een match op de Bosuil. Voor een klein gezelschap volstaat de 2KG; wie meer gasten verwacht, vindt in ons <a href=\"/assortiment/\">assortiment</a> de 4KG en de 10KG. Leveren doen wij alleen aan volwassenen, met controle van de identiteitskaart als dat nodig is, en u betaalt aan de deur cash of met Payconiq. Onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u best voor het feest begint.",
        ],
        "wijken": "Deurne-Noord, Kronenburg, Deurne-Dorp, Cogelsplein, Rivierenhof, Boekenbergpark, Deurne-Zuid, Eksterlaar, Silsburg, Bosuil",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook rond het Rivierenhof en de luchthaven?",
             "Ja, maar altijd aan de deur van een adres. In het provinciaal domein Rivierenhof zelf of op het terrein van de luchthaven leveren wij niet; de woonstraten rondom, zoals de Turnhoutsebaan, de Ruggeveldlaan en de wijk Ertbrugge, bedienen wij wel."],
            ["Hoe verloopt een bestelling in Deurne precies?",
             "U stuurt via WhatsApp wat u wenst en uw adres, wij antwoorden met een bevestiging en een levertijd, en onze bezorger meldt zich aan uw deur. De drie stappen staan uitgelegd op onze pagina <a href=\"/werkwijze/\">werkwijze</a>."],
            ["Mijn feest is in Deurne-Zuid, vlak bij de grens met Borsbeek. Is dat een probleem?",
             "Helemaal niet. Borsbeek is sinds begin 2025 zelf een district van Antwerpen en ligt net als Silsburg en Eksterlaar op onze route. Geef uw juiste postcode door, dan krijgt u een correcte indicatie."],
        ],
        "nearby": ["borgerhout", "merksem", "wijnegem"],
        "lat": 51.2250, "lon": 4.4660,
    },
    {
        "slug": "hoboken", "name": "Hoboken", "kind": "district",
        "title": "Lachgas Hoboken | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Hoboken? Via WhatsApp aan huis bezorgd, van de Kioskplaats en Moretusburg tot Polderstad, Sorghvliedt en de Zwaantjes. Enkel voor 18+.",
        "h1": "Lachgas Hoboken",
        "lead": "Aan de Schelde, aan de zuidrand van de stad: in Hoboken staan wij aan uw deur na één WhatsApp-bericht.",
        "intro": [
            "Hoboken ligt in het zuidwesten van Antwerpen, tussen de Schelde en de Sint-Bernardsesteenweg, en gaat aan de zuidkant over in Hemiksem. Het hart is de Kioskplaats met de Kapelstraat als winkelstraat; daaromheen liggen Moretusburg en Hertogvelden langs de Schelde, de nieuwere wijk Polderstad, de buurt rond het districtshuis in het park Sorghvliedt en de Zwaantjes op de grens met het Kiel. Ook de straten rond Fort 8 horen erbij. Waar u ook woont: stuur ons via WhatsApp wat u nodig heeft en uw adres, en wij komen tot aan uw deur.",
            "Vanuit het centrum rijden onze bezorgers over de Amerikalei en de Jan De Voslei door het Kiel en dan de Sint-Bernardsesteenweg af, of via de Krijgsbaan vanuit Wilrijk; voor Polderstad en Moretusburg is de Lageweg de kortste weg. Dat levert in Hoboken meestal een levertijd op van 20 tot 30 minuten. Trams en bussen van De Lijn rijden tot aan de Kioskplaats en de Lelieplaats, maar met een tank op de tram stapt u niet; wij brengen ze. Houd er rekening mee dat de Sint-Bernardsesteenweg in de avondspits traag kan zijn.",
            "Hoboken is een district van rijhuizen met een koer, verenigingslokalen en familiefeesten, en veel bestellingen zijn dan ook voor een verjaardag of een avond met vrienden thuis. Een 2KG-tank is daarvoor doorgaans ruim voldoende; voor een groter gezelschap bekijkt u de 4KG in ons <a href=\"/assortiment/\">assortiment</a>, waar ook crackers en slagroompatronen staan. Wij verkopen uitsluitend aan 18-plussers en controleren uw identiteitskaart als wij twijfelen. Betalen kan cash of via Payconiq bij levering. Lees vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Kioskplaats, Kapelstraat, Moretusburg, Hertogvelden, Polderstad, Sorghvliedt, Zwaantjes, Fort 8, Lageweg, Hobokense Polder",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in Polderstad en Moretusburg, aan de kant van de Schelde?",
             "Ja. Die wijken liggen wat verder van de Sint-Bernardsesteenweg, maar onze bezorgers kennen de weg via de Lageweg. De levertijd is er niet anders dan in de rest van Hoboken."],
            ["Ik woon net over de grens in Hemiksem. Kan dat ook?",
             "Zeker. Hemiksem ligt in het verlengde van de Sint-Bernardsesteenweg en heeft een eigen pagina: <a href=\"/bezorggebied/hemiksem/\">lachgas Hemiksem</a>. Reken daar op een iets ruimere indicatie dan in Hoboken zelf."],
            ["Wat doe ik met de lege fles na het feest?",
             "Zet ze niet bij het restafval en laat ze niet achter op straat of aan de Scheldedijk. Een lege tank kunt u binnenbrengen bij een recyclagepark van de stad; controleer vooraf welk park gasflessen aanvaardt. Onze uitleg vindt u op <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">lege lachgasflessen inleveren</a>."],
        ],
        "nearby": ["kiel", "wilrijk", "hemiksem"],
        "lat": 51.1752, "lon": 4.3496,
    },
    {
        "slug": "merksem", "name": "Merksem", "kind": "district",
        "title": "Lachgas Merksem | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Merksem? Via WhatsApp aan huis bezorgd, van de Bredabaan en het Sportpaleis tot Oude Bareel, Tuinwijk en het Dokske. Enkel voor 18+.",
        "h1": "Lachgas Merksem",
        "lead": "Over de Theunisbrug en de Bredabaan op: in Merksem komen wij aan uw deur na één WhatsApp-bericht.",
        "intro": [
            "Merksem ligt ten noorden van het Albertkanaal, tussen de haven en Schoten, en wordt doorsneden door de Bredabaan, de lange handelsstraat die van de Theunisbrug tot aan de Oude Bareel loopt. Rond die as liggen de buurten die wij bedienen: het Sportpaleis en Schijnpoort aan de zuidkant, de Tuinwijk en Lambrechtshoeken, de straten rond het Bouckenborghpark en het Runcvoortpark, het Dokske aan het kanaal en de nieuwe woonblokken aan de Groenendaallaan. Een WhatsApp-bericht met wat u wenst en uw adres is alles wat wij nodig hebben om te vertrekken.",
            "Onze bezorgers steken het Albertkanaal over via de Theunisbrug of nemen vanuit de Ring de afrit Merksem ter hoogte van het Sportpaleis; vanuit het noorden van de stad ligt de Groenendaallaan voor de hand. Daarmee halen wij in Merksem meestal een levertijd van 20 tot 30 minuten. Op avonden met een concert in het Sportpaleis of de Lotto Arena staat het verkeer rond Schijnpoort stil en kiezen wij bewust een andere route; de tram van De Lijn die daar uit de premetro komt, loopt dan ook vertraging op. U hoort het van ons als dat uw levertijd beïnvloedt.",
            "In Merksem bestellen vooral gezinnen en vriendengroepen: een verjaardag in een rijhuis in de Tuinwijk, een feest in een appartement aan de Bredabaan of een gezellige avond na een match of concert. Voor zulke gezelschappen is de 2KG uit ons <a href=\"/assortiment/\">assortiment</a> meestal de logische keuze, met de 4KG voor wie meer gasten verwacht. Crackers en slagroompatronen brengen wij desgewenst mee. Wij leveren enkel aan meerderjarigen en vragen bij twijfel uw identiteitskaart. U betaalt aan de deur, cash of via Payconiq, en wij raden u aan om vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> te lezen.",
        ],
        "wijken": "Bredabaan, Sportpaleis, Schijnpoort, Tuinwijk, Lambrechtshoeken, Bouckenborghpark, Runcvoortpark, Dokske, Oude Bareel, Groenendaallaan",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie op avonden met een concert in het Sportpaleis?",
             "Ja, maar dan plannen wij onze route om de drukte rond Schijnpoort heen en kan de levertijd naar de bovengrens gaan. Wij leveren uitsluitend aan een woonadres, niet aan het Sportpaleis, de Lotto Arena of op de parkings."],
            ["Ik woon aan de Oude Bareel, op de grens met Schoten. Welke pagina geldt voor mij?",
             "Voor de bezorging maakt het geen verschil; beide liggen op dezelfde route over de Bredabaan. Woont u officieel in Schoten, kijk dan op <a href=\"/bezorggebied/schoten/\">lachgas Schoten</a> voor de indicatie die daar geldt."],
            ["Kan ik bestellen voor een feest in een gehuurd lokaal in Merksem?",
             "Ja, als het om een privéfeest op een vast adres gaat, zoals een verenigingslokaal of een feestzaal. Meld het adres en het uur waarop iemand van 18 jaar of ouder aanwezig is om de levering aan te nemen. Voor grotere gelegenheden leest u best onze pagina <a href=\"/lachgas-feest-evenement/\">feest en evenement</a>."],
        ],
        "nearby": ["luchtbal", "deurne", "schoten"],
        "lat": 51.2420, "lon": 4.4460,
    },
    {
        "slug": "wilrijk", "name": "Wilrijk", "kind": "district",
        "title": "Lachgas Wilrijk | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Wilrijk? Via WhatsApp aan huis bezorgd rond de Bist, Valaar, Neerland, Oosterveld en Campus Drie Eiken. Enkel voor 18+.",
        "h1": "Lachgas Wilrijk",
        "lead": "Van de Bist tot de Boomsesteenweg: in Wilrijk komen wij aan uw deur na één WhatsApp-bericht.",
        "intro": [
            "Wilrijk ligt ten zuiden van het centrum, tussen Hoboken en Berchem, met de Boomsesteenweg als drukke westgrens en de Krijgsbaan als scheiding met Edegem. Het districtshuis staat aan de Bist, het plein waar de vijfjaarlijkse Geitenstoet vertrekt; daaromheen liggen de woonwijken Valaar, Neerland, Oosterveld en Koornbloem, de universiteitsbuurt rond Campus Drie Eiken en de groene rand met Fort 6, Fort 7 en het Steytelinckpark. Wij bezorgen in al die wijken aan huis. U stuurt een WhatsApp-bericht met uw bestelling en adres, wij doen de rest.",
            "Vanuit de stad rijden onze bezorgers via de Jan Van Rijswijcklaan en de Jules Moretuslei, over de Boomsesteenweg of via de Krijgsbaan vanuit Berchem; met de afrit Wilrijk van de A12 zijn ook de wijken aan de westkant snel bereikt. De levertijd in Wilrijk komt daardoor meestal uit op 20 tot 30 minuten. De Boomsesteenweg met haar winkels en het verkeer richting Boom en Brussel is op zaterdag druk, en rond de Bist stoppen veel bussen van De Lijn, maar de woonwijken erachter zijn rustig. U krijgt van ons een eerlijke inschatting zodra uw bestelling bevestigd is.",
            "Een feest in een gezinswoning in Valaar, een kotfeestje in de buurt van de campus of een verjaardag in een appartement aan de Jules Moretuslei: de meeste bestellingen uit Wilrijk zijn goed af met de 2KG-tank uit ons <a href=\"/assortiment/\">assortiment</a>; voor een groter gezelschap raden wij de 4KG aan. Crackers en slagroompatronen leveren wij op aanvraag mee. Wij verkopen uitsluitend aan personen van 18 jaar en ouder en controleren dat met uw identiteitskaart als wij twijfelen. Afrekenen gebeurt pas bij levering, cash of met Payconiq. Onze aanbevelingen voor <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u best vooraf.",
        ],
        "wijken": "Bist, Valaar, Neerland, Oosterveld, Koornbloem, Campus Drie Eiken, Boomsesteenweg, Jules Moretuslei, Steytelinckpark, Fort 7",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Leveren jullie op Campus Drie Eiken of in de studentenhomes?",
             "Op de campus zelf niet; wij leveren aan de deur van een privéadres, zoals een kot of een woning in de buurt van het Universiteitsplein. Studenten moeten net als iedereen 18 jaar of ouder zijn en dat kunnen aantonen. Meer uitleg vindt u op <a href=\"/lachgas-studenten-antwerpen/\">lachgas voor studenten in Antwerpen</a>."],
            ["Heeft de drukte op de A12 invloed op de levertijd?",
             "De Boomsesteenweg loopt dwars door het westen van Wilrijk en is vooral op zaterdagmiddag en in de avondspits druk. Onze bezorgers wijken dan uit naar de Krijgsbaan of de Jules Moretuslei, zodat de indicatie van 20 tot 30 minuten meestal gewoon haalbaar blijft."],
            ["Kan ik in Wilrijk ook enkel slagroompatronen of een cracker bestellen?",
             "Ja. Naast de tanks bezorgen wij ook losse <a href=\"/product/slagroompatronen/\">slagroompatronen</a> en lachgas crackers, ook zonder tank erbij. Vermeld in uw bericht wat u precies nodig heeft, dan bevestigen wij meteen de prijs en de levertijd."],
        ],
        "nearby": ["hoboken", "edegem", "aartselaar"],
        "lat": 51.1680, "lon": 4.3940,
    },
    {
        "slug": "mortsel", "name": "Mortsel", "kind": "gemeente",
        "title": "Lachgas Mortsel | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Mortsel? Via WhatsApp aan huis bezorgd rond Oude God, de Statielei, het Gemeenteplein, Fort 4 en Luithagen. Enkel voor 18+.",
        "h1": "Lachgas Mortsel",
        "lead": "Net voorbij Berchem, vlak over de Krijgsbaan: in Mortsel staan wij aan uw deur na één bericht via WhatsApp.",
        "intro": [
            "Mortsel sluit naadloos aan op Berchem en Deurne en voelt voor ons dan ook aan als een verlengstuk van de stad. De stad Mortsel heeft twee kernen: Oude God rond het station en de Statielei, en het centrum rond het Gemeenteplein en de Antwerpsestraat. Daartussen en daarrond liggen Fort 4 met zijn park, de wijken Luithagen, Savelkoul en Koeisteerthof, de Liersesteenweg richting Hove en de straten langs de Krijgsbaan aan de kant van de luchthaven. Wij bezorgen in heel Mortsel. U stuurt via WhatsApp uw bestelling en adres, wij bevestigen en komen tot aan uw deur.",
            "Vanuit Antwerpen rijden onze bezorgers over de Grote Steenweg door Berchem en verder de Antwerpsestraat op, of via de Ring en de Krijgsbaan langs de luchthaven. Mortsel ligt daardoor net buiten onze snelste zone, met een levertijd van meestal 25 tot 40 minuten. De trams 7 en 15 van De Lijn verbinden het Gemeenteplein met de stad, en de stations Mortsel en Mortsel-Oude God liggen op de spoorlijnen naar Mechelen en Lier; wij hebben ze niet nodig, maar de drukte rond die knooppunten op vrijdagavond zit wel in onze inschatting.",
            "Mortsel is een residentiële stad met veel gezinswoningen en appartementen; de bestellingen zijn vaak voor een verjaardag, een tuinfeest of een avond met vrienden. Voor een klein gezelschap kiest u de 2KG, voor meer volk de 4KG; beide staan samen met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan volwassenen en kunnen uw identiteitskaart vragen; u betaalt onze bezorger bij levering, cash of via Payconiq. Voor het feest begint, leest u best onze aanbevelingen voor <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Oude God, Statielei, Gemeenteplein, Antwerpsestraat, Fort 4, Luithagen, Savelkoul, Koeisteerthof, Liersesteenweg, Krijgsbaan",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Waarom is de levertijd in Mortsel langer dan in Berchem?",
             "Omdat Mortsel buiten de Antwerpse districten ligt en wij er vanuit de stad eerst Berchem of de Krijgsbaan voor moeten doorkruisen. Het verschil is klein: meestal 25 tot 40 minuten in plaats van 20 tot 30. Op rustige momenten zijn wij er vaak sneller."],
            ["Gelden in Mortsel dezelfde regels als in Antwerpen?",
             "Het federale kader is overal in België hetzelfde, maar Mortsel is een zelfstandige stad met een eigen politiereglement dat kan verschillen van dat van Antwerpen. Wij leveren aan de deur van een privéadres en nooit op straat. Het wettelijke kader vatten wij samen op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
            ["Bezorgen jullie ook aan de kant van Hove en Edegem?",
             "Ja, de wijken rond de Liersesteenweg en de Mechelsesteenweg bedienen wij volledig. Hove en <a href=\"/bezorggebied/edegem/\">Edegem</a> hebben elk een eigen pagina met een vergelijkbare indicatie; vermeld altijd uw juiste gemeente, zodat wij de rit goed inplannen."],
        ],
        "nearby": ["berchem", "edegem", "hove"],
        "lat": 51.1670, "lon": 4.4590,
    },
    {
        "slug": "brugge", "name": "Brugge", "kind": "stad",
        "title": "Lachgas Brugge | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Brugge? Via WhatsApp aan huis bezorgd, van de Markt en 't Zand tot Sint-Michiels, Assebroek en Sint-Kruis. Enkel voor 18+.",
        "h1": "Lachgas Brugge",
        "lead": "Ook in Brugge leveren wij aan huis, met een rit die wij vooraf met u inplannen via WhatsApp.",
        "intro": [
            "Brugge is onze verste bestemming in West-Vlaanderen en toch bezorgen wij er aan huis: in het historische centrum binnen de Vesten, rond de Markt, de Burg en 't Zand, in de stationsbuurt en Christus-Koning, en in de deelgemeenten Sint-Michiels, Sint-Andries, Assebroek, Sint-Kruis en Koolkerke. Ook Zeebrugge en Lissewege aan de kust zijn mogelijk, als u er wat ruimer voor plant. Bestellen gaat zoals overal: u stuurt een WhatsApp-bericht met uw bestelling en adres, wij bevestigen de rit en het tijdstip waarop u ons mag verwachten.",
            "Onze bezorgers vertrekken in Antwerpen en rijden via de E17 naar Gent en verder over de E40 richting Oostende tot de afrit Brugge, of via de E34 en de Expresweg N31 wanneer de E17 vastzit; dat is een kleine honderd kilometer. Daarom rekent u voor Brugge op een levertijd van meestal 45 tot 75 minuten na bevestiging, en vragen wij u bij voorkeur enkele uren vooraf te bestellen zodat wij de rit kunnen inplannen. Binnen de Vesten rijden wij via de Ring R30 tot de dichtstbijzijnde toegang; in de autoluwe binnenstad leggen wij de laatste meters te voet af.",
            "Bestellingen uit Brugge zijn vaak voor een weekend met vrienden in een gehuurd huis, een verjaardag in Sint-Michiels of een feest in een studentenhuis bij Howest of Vives. Omdat de rit lang is, kiest u best meteen een formaat dat de hele avond meegaat; vergelijk de 2KG en de 4KG in ons <a href=\"/assortiment/\">assortiment</a> of vraag ons advies. Onze bezorgers leveren enkel aan meerderjarigen en controleren de identiteitskaart als dat nodig is. Betalen doet u bij levering, cash of via Payconiq. Lees vooraf ook onze aanbevelingen voor <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Markt, Burg, 't Zand, Stationsbuurt, Christus-Koning, Sint-Michiels, Sint-Andries, Assebroek, Sint-Kruis, Koolkerke",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Hoe lang op voorhand moet ik bestellen voor Brugge?",
             "Liefst enkele uren, en voor een weekendavond nog vroeger. Zo kunnen wij de rit combineren en u een betrouwbaar tijdstip geven. Een spontane bestelling proberen wij ook in te passen, maar dan geldt de volledige indicatie van 45 tot 75 minuten en soms meer."],
            ["Leveren jullie ook in Zeebrugge, Lissewege of Dudzele?",
             "Ja, de noordelijke deelgemeenten van Brugge liggen binnen ons bereik, maar ze voegen wat extra tijd toe aan de rit vanaf de E40. Vermeld de deelgemeente duidelijk in uw bericht, dan houden wij daar bij de planning rekening mee."],
            ["Hoe betaal ik in Brugge?",
             "Bij levering, cash of via Payconiq; de prijs bevestigen wij vooraf via WhatsApp zodat er aan de deur geen verrassingen zijn. Vooruitbetalen is niet nodig. Meer leest u op <a href=\"/betalen-bij-levering/\">betalen bij levering</a>."],
        ],
        "nearby": ["gent", "lokeren", "antwerpen-centrum"],
        "lat": 51.2093, "lon": 3.2247,
    },
    {
        "slug": "brussel", "name": "Brussel", "kind": "stad",
        "title": "Lachgas Brussel | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Brussel? Via WhatsApp aan huis bezorgd in de 19 gemeenten, van de Vijfhoek en Elsene tot Schaarbeek, Anderlecht en Ukkel. Enkel 18+.",
        "h1": "Lachgas Brussel",
        "lead": "Vanuit Antwerpen over de E19 naar de hoofdstad: in Brussel bezorgen wij aan huis na één bericht via WhatsApp.",
        "intro": [
            "Brussel is voor ons niet alleen de Vijfhoek binnen de Kleine Ring, met de Grote Markt, de Dansaertwijk en de Marollen, maar het hele Brussels Hoofdstedelijk Gewest: Elsene en Flagey, Sint-Gillis en Vorst, Etterbeek en de Europese wijk, Schaarbeek en Sint-Joost, Anderlecht en Molenbeek, Laken bij de Heizel, Ukkel en Sint-Pieters-Woluwe. In al die gemeenten bezorgen wij aan huis. U stuurt ons via WhatsApp uw bestelling en uw adres met postcode; wij bevestigen, plannen de rit in en laten weten wanneer u ons mag verwachten.",
            "Onze bezorgers rijden vanuit Antwerpen over de E19 langs Mechelen tot de Grote Ring R0 en vervolgens via de Kleine Ring of de tunnels naar uw gemeente; voor Laken, Jette en de Heizel is de A12 via Boom en Willebroek vaak korter. Het zijn een vijftigtal kilometers tot de rand van het gewest, waardoor de levertijd in Brussel meestal 45 tot 75 minuten bedraagt. De files op de R0 wegen daarin zwaarder dan de afstand zelf, net als de Brusselse lage-emissiezone en het parkeren in dichte wijken als Sint-Gillis. Bestel bij voorkeur ruim vooraf, dan geven wij u een strak tijdvenster.",
            "Een afterwork in een appartement in Elsene, een verjaardag in een herenhuis in Schaarbeek, een avond met vrienden in een studentenhuis rond de ULB of de VUB: voor zulke gezelschappen volstaat meestal de 2KG uit ons <a href=\"/assortiment/\">assortiment</a>, voor grotere feesten de 4KG. Alleen meerderjarigen kunnen bij ons bestellen; wij controleren uw identiteitskaart bij twijfel en komen enkel aan de deur van een privéadres. De betaling gebeurt bij levering, cash of via Payconiq. Neem voor het feest onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Vijfhoek, Grote Markt, Dansaertwijk, Marollen, Elsene, Sint-Gillis, Etterbeek, Schaarbeek, Anderlecht, Laken",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Bezorgen jullie in alle 19 gemeenten van Brussel?",
             "Ja, van Anderlecht tot Watermaal-Bosvoorde en van Laken tot Ukkel. Voor adressen aan de buitenrand, zoals Sint-Pieters-Woluwe of Oudergem, kan de rit iets langer duren dan voor de Vijfhoek. Vermeld altijd de postcode, want dezelfde straatnaam komt in Brussel meer dan eens voor."],
            ["Wat zijn de regels rond lachgas in Brussel?",
             "Het federale verbod uit het Koninklijk Besluit van 11 maart 2024 geldt ook in het Brussels Hoofdstedelijk Gewest, en daarnaast kunnen Brusselse gemeenten eigen politiereglementen hebben over gebruik op straat. Onze leveringen gaan uitsluitend naar volwassenen en enkel naar de deur van een privéadres. Een overzicht van het wettelijke kader staat op <a href=\"/lachgas-informatie/is-lachgas-legaal-in-belgie/\">is lachgas legaal in België</a>."],
            ["Hoe laat kan ik in Brussel nog bestellen?",
             "Omdat de rit vanuit Antwerpen lang is, raden wij aan om in de loop van de dag of in de vroege avond te bestellen; een late bestelling proberen wij in te passen, maar dan geldt de bovengrens van de indicatie. Onze <a href=\"/bezorgtijden-antwerpen/\">bezorgtijden</a> vindt u op een aparte pagina."],
        ],
        "nearby": ["leuven", "mechelen", "gent"],
        "lat": 50.8466, "lon": 4.3528,
    },
    {
        "slug": "gent", "name": "Gent", "kind": "stad",
        "title": "Lachgas Gent | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Gent? Via WhatsApp aan huis bezorgd, van de Korenmarkt en de Overpoort tot Ledeberg, Gentbrugge en Mariakerke. Enkel voor 18+.",
        "h1": "Lachgas Gent",
        "lead": "Over de E17 naar de Arteveldestad: in Gent bezorgen wij aan huis na één bericht via WhatsApp.",
        "intro": [
            "Gent is de grootste stad op onze route naar het westen, en wij bezorgen er in de hele stad: in de Kuip rond Korenmarkt, Vrijdagmarkt en Patershol, in de studentenbuurt rond de Overpoortstraat en de Sint-Pietersnieuwstraat, in de wijken aan de stadsring R40 zoals Rabot, Brugse Poort, Muide en Dampoort, en in de deelgemeenten Ledeberg, Gentbrugge, Sint-Amandsberg, Mariakerke, Wondelgem en Zwijnaarde. Laat ons via WhatsApp weten wat u wenst en waar u woont; wij bevestigen, geven een tijdstip en komen tot aan uw deur, ook als dat een derde verdieping in een herenhuis is.",
            "Vanuit Antwerpen rijden onze bezorgers door de Kennedytunnel de E17 op, langs Sint-Niklaas en Lokeren tot Gent, ongeveer zestig kilometer, en nemen afhankelijk van uw wijk de afrit Gent-Centrum via de B401, de afrit Gentbrugge of de R4 naar het noorden van de stad. Dat maakt een levertijd van meestal 45 tot 75 minuten realistisch. Het circulatieplan met zijn autovrije centrum en zijn sectoren vraagt wat lokale kennis; in het autovrije gebied rijden wij tot het dichtstbijzijnde bereikbare punt en spreken wij via WhatsApp af hoe wij uw deur bereiken.",
            "Gent is een studentenstad, en dat weerspiegelt zich in de aanvragen: kotwoningen rond de Overpoort, huizen in Ledeberg en Sint-Amandsberg waar vrienden samenkomen, appartementen aan de Dampoort. Een 2KG-tank uit ons <a href=\"/assortiment/\">assortiment</a> volstaat voor een klein gezelschap; voor een groter feest kiest u de 4KG. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen uw identiteitskaart als wij twijfelen; aan koten leveren wij aan de voordeur, niet in de straat. Cash of via Payconiq betalen kan allebei, bij levering. Lees voor het feest onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Korenmarkt, Vrijdagmarkt, Patershol, Overpoort, Sint-Pietersnieuwstraat, Rabot, Brugse Poort, Dampoort, Ledeberg, Gentbrugge",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Bezorgen jullie in het autovrije centrum van Gent?",
             "Ja. Wij rijden tot aan de rand van het voetgangersgebied en brengen de bestelling te voet tot aan uw deur. Geef in uw bericht aan via welke straat uw ingang het best bereikbaar is, dan hoeven wij ter plaatse niet te zoeken."],
            ["Kan ik als student in Gent bestellen?",
             "Ja, als u 18 jaar of ouder bent en dat kunt aantonen met uw identiteitskaart. Wij leveren aan de deur van uw kot of huis, niet in de Overpoortstraat of op een fuif. Houd rekening met de huisregels van uw kotbaas en met de federale regels, die wij toelichten op <a href=\"/lachgas-informatie/lachgaswet-belgie-2024/\">de lachgaswet van 2024</a>."],
            ["Hoe zit het met de E17 en de levertijd?",
             "De E17 tussen de Kennedytunnel en Gent is in de avondspits en op vrijdagavond gevoelig voor file. Daarom hanteren wij voor Gent een ruime indicatie van 45 tot 75 minuten en laten wij u onderweg weten of wij vroeger of later aankomen. Vroeg bestellen helpt ons om het rustigste moment te kiezen."],
        ],
        "nearby": ["lokeren", "sint-niklaas", "brugge"],
        "lat": 51.0543, "lon": 3.7174,
    },
    {
        "slug": "leuven", "name": "Leuven", "kind": "stad",
        "title": "Lachgas Leuven | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Leuven? Via WhatsApp aan huis bezorgd rond de Oude Markt, de Vaartkom, Heverlee, Kessel-Lo en Wilsele. Vooraf gepland, enkel voor 18+.",
        "h1": "Lachgas Leuven",
        "lead": "Van de Oude Markt tot Heverlee: in Leuven leveren wij aan huis na één bericht via WhatsApp.",
        "intro": [
            "Leuven ligt ten zuidoosten van Antwerpen, voorbij Mechelen, en is de hoofdstad van Vlaams-Brabant en een van de bekendste studentensteden van het land. Wij bezorgen binnen de Ring R23: rond de Oude Markt en het Ladeuzeplein, in de Naamsestraat en de Tiensestraat met hun vele koten, rond de Bondgenotenlaan en het station aan het Martelarenplein, en in de herontwikkelde Vaartkom; daarbuiten ook in Heverlee met het Arenbergpark en de campussen, rond Gasthuisberg, in Kessel-Lo, Wilsele en Wijgmaal. Bestellen doet u met een WhatsApp-bericht waarin uw adres en uw keuze staan; wij bevestigen en plannen de rit in.",
            "De rit vanuit Antwerpen gaat over de E19 richting Brussel tot Mechelen en dan over de N26 langs het kanaal Leuven-Dijle, of via de Brusselse Ring R0 en de E40 tot de afrit Leuven; dat is ruim zestig kilometer. Daarom rekent u in Leuven op een levertijd van meestal 45 tot 75 minuten, en vragen wij om bij voorkeur vooraf te bestellen. Rond het station en de Bondgenotenlaan zijn veel straten autoluw of voorbehouden voor de bussen van De Lijn; in de binnenstad rijden wij tot het dichtstbijzijnde bereikbare punt en komen wij te voet tot aan uw deur.",
            "Een kotfeest in de Tiensestraat, een verjaardag in een rijhuis in Kessel-Lo of een avond met collega's in een appartement aan de Vaartkom: voor zulke gezelschappen is de 2KG-tank uit ons <a href=\"/assortiment/\">assortiment</a> meestal genoeg, voor meer volk de 4KG. Minderjarigen leveren wij niet en bij twijfel vragen wij uw identiteitskaart; aan koten leveren wij aan de voordeur en vragen wij u rekening te houden met het reglement van uw kot. Bij levering betaalt u cash of met Payconiq. Onze aanbevelingen voor <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> neemt u best door voor de gasten aankomen.",
        ],
        "wijken": "Oude Markt, Grote Markt, Ladeuzeplein, Naamsestraat, Tiensestraat, Bondgenotenlaan, Vaartkom, Heverlee, Kessel-Lo, Wilsele",
        "levertijd": "meestal binnen 45 tot 75 minuten",
        "faq": [
            ["Bezorgen jullie ook in Heverlee, Kessel-Lo en Wilsele?",
             "Ja, alle deelgemeenten van Leuven zitten in ons bezorggebied; Heverlee en Kessel-Lo bereiken wij via de Ring R23, Wilsele en Wijgmaal langs het kanaal. De indicatie van 45 tot 75 minuten geldt voor heel Leuven; vermeld de deelgemeente in uw bericht."],
            ["Wat als ik met een groep studenten bestel? Controleren jullie iedereen?",
             "Wij controleren de persoon die de bestelling aanneemt en betaalt; die moet 18 jaar of ouder zijn en dat kunnen aantonen. Lachgas is niet bestemd voor minderjarigen, ook niet als zij op het feest aanwezig zijn. Meer over het verkoopverbod leest u op <a href=\"/lachgas-informatie/lachgas-en-minderjarigen-belgie/\">lachgas en minderjarigen in België</a>."],
            ["Komen jullie ook naar de omliggende gemeenten, zoals Herent of Bertem?",
             "Dat bekijken wij per aanvraag; stuur uw adres en wij laten weten of het past in een rit naar Leuven. Mechelen en Lier liggen op onze vaste route en hebben elk een eigen pagina, zoals <a href=\"/bezorggebied/mechelen/\">lachgas Mechelen</a>."],
        ],
        "nearby": ["brussel", "mechelen", "lier"],
        "lat": 50.8798, "lon": 4.7005,
    },
]
