# -*- coding: utf-8 -*-
# Randgemeenten rond Antwerpen (deel B): Voorkempen, Waasland, Rupelstreek, Klein-Brabant en de Netevallei.
# Levertijd overal "meestal binnen 25 tot 40 minuten".

AREAS = [
    {
        "slug": "schilde",
        "name": "Schilde",
        "kind": "gemeente",
        "title": "Lachgas Schilde | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Schilde? Wij bezorgen lachgastanks en patronen in Schilde en ’s-Gravenwezel, meestal binnen 25 tot 40 minuten. Enkel voor 18+.",
        "h1": "Lachgas bezorgen in Schilde",
        "lead": "Lachgas aan huis in Schilde en ’s-Gravenwezel: bestel via WhatsApp, wij bevestigen de prijs vooraf en u betaalt pas aan de deur.",
        "intro": [
            "Schilde is een groene villagemeente in de Voorkempen, ten oosten van Antwerpen, met twee kernen: Schilde zelf langs de Turnhoutsebaan en het landelijke ’s-Gravenwezel met zijn kasteel en dorpsplein. Daartussen liggen bosrijke woonwijken zoals Schilde-Bergen en Vennebos, en aan de zuidkant het recreatiedomein Schildestrand. Wie hier woont en lachgas wil laten leveren, stuurt ons een WhatsApp-bericht met de gewenste producten en het adres. Wij antwoorden met een bevestiging van prijs en levermoment, zodat u precies weet waar u aan toe bent voor onze bezorger de baan op gaat.",
            "Onze bezorgers verlaten Antwerpen via de E34 richting Turnhout en nemen de afrit Ranst, of zij rijden over de N12 door Wijnegem, waarna de Turnhoutsebaan hen rechtstreeks naar het centrum van Schilde brengt. Voor ’s-Gravenwezel wijken zij via de Wijnegemsteenweg af. De afstand is beperkt, maar de lange lintbebouwing langs de steenweg en de drukte rond het winkelcentrum van Wijnegem maken dat wij meestal 25 tot 40 minuten rekenen. Schilde heeft geen treinstation; de bussen van De Lijn tussen Antwerpen en Turnhout stoppen wel om de paar honderd meter langs de Turnhoutsebaan. Voor u maakt dat geen verschil, want wij komen tot aan uw voordeur.",
            "Een tuinfeest op een ruim perceel in Schilde-Bergen, een verjaardag in een appartement langs de Turnhoutsebaan of een rustige avond thuis in ’s-Gravenwezel: kies het formaat dat bij uw gezelschap past. Voor enkele vrienden volstaat doorgaans de 2KG-tank, voor een grotere groep adviseren wij 4KG of 10KG; het hele aanbod, met ook crackers en slagroompatronen, bekijkt u in ons <a href=\"/assortiment/\">assortiment</a>. Enkel meerderjarigen kunnen bij ons bestellen; bij twijfel vragen wij uw identiteitskaart. U betaalt bij levering, cash of via Payconiq. Neem vooraf ook even onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door.",
        ],
        "wijken": "Schilde-Centrum, Turnhoutsebaan, ’s-Gravenwezel, Schilde-Bergen, Vennebos, Schildestrand, Antitankgracht, Wijnegemsteenweg, Kasteel van ’s-Gravenwezel",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in ’s-Gravenwezel?", "Ja, ’s-Gravenwezel is een deelgemeente van Schilde en valt volledig binnen ons bezorggebied. Onze bezorger rijdt via de Wijnegemsteenweg tot aan uw woning en de indicatie van meestal 25 tot 40 minuten geldt daar evengoed."],
            ["Hoe weet ik wanneer de bezorger in Schilde aankomt?", "Na uw bestelling via WhatsApp bevestigen wij de prijs en sturen wij een bericht zodra onze bezorger vanuit Antwerpen vertrekt. Loopt het vast op de E34 of de Turnhoutsebaan, dan laten wij dat meteen weten, zodat u niet onnodig hoeft te wachten."],
            ["Ik woon aan de rand van Schilde, richting Brecht of Zoersel. Komen jullie daar ook?", "Zeker, ook de verspreide bebouwing langs de grens met Zoersel, Brecht en Schoten hoort bij Schilde en dus bij ons werkgebied. Vermeld het volledige adres in uw bericht, dan houden wij in onze indicatie rekening met de extra kilometers."],
        ],
        "nearby": ["wijnegem", "zoersel", "brecht"],
        "lat": 51.240, "lon": 4.583,
    },
    {
        "slug": "brecht",
        "name": "Brecht",
        "kind": "gemeente",
        "title": "Lachgas Brecht | Aan huis in de Noorderkempen",
        "description": "Lachgas bestellen in Brecht? Lachgastanks en patronen aan huis in Brecht, Sint-Job-in-’t-Goor en Sint-Lenaarts, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Brecht",
        "lead": "Lachgas thuisbezorgd in Brecht, Sint-Job-in-’t-Goor en Sint-Lenaarts: één WhatsApp-bericht volstaat, betalen doet u aan de deur.",
        "intro": [
            "Brecht ligt in de Noorderkempen, langs de E19 die Antwerpen met Breda verbindt, en telt drie dorpskernen: het hoofddorp Brecht, Sint-Job-in-’t-Goor aan het kanaal Dessel-Schoten en Sint-Lenaarts aan de kant van Rijkevorsel. Daartussen vindt u naaldbossen, de Brechtse Heide en kleinere gehuchten zoals Overbroek. In al die kernen leveren wij lachgas aan huis. U bestelt door ons via WhatsApp te laten weten welke tank of patronen u wenst en op welk adres wij mogen aanbellen. Wij bevestigen de prijs op voorhand, zodat er bij levering niets meer te bespreken valt.",
            "Vanuit Antwerpen nemen onze bezorgers de E19 richting Breda en verlaten die aan de afrit Sint-Job-in-’t-Goor of aan de afrit Brecht, afhankelijk van uw deelgemeente. Sint-Lenaarts bereiken zij vanuit het hoofddorp via de weg richting Rijkevorsel. Omdat Brecht aan de buitenrand van onze noordelijke zone ligt en het laatste stuk over lokale wegen door de bossen loopt, rekenen wij op meestal 25 tot 40 minuten. Het station Noorderkempen langs de hogesnelheidslijn brengt pendelaars snel naar Antwerpen-Centraal, en De Lijn bedient de dorpskernen met streekbussen. Voor uw bestelling hoeft u echter nergens heen: wij leveren aan de deur.",
            "Of u nu een feestje geeft in een nieuwbouwwijk in Sint-Job, een familiebijeenkomst houdt in een hoeve in Overbroek of met vrienden samenkomt in een appartement in het centrum van Brecht: wij hebben een passend formaat. De 2KG-tank is compact en geschikt voor een klein gezelschap, de 4KG en 10KG zijn bedoeld voor grotere groepen. Daarnaast leveren wij crackers en slagroompatronen; alles staat overzichtelijk in ons <a href=\"/assortiment/\">assortiment</a>. Bestellen kan uitsluitend vanaf 18 jaar en wij vragen zo nodig een identiteitsbewijs. U rekent af bij levering, cash of via Payconiq. Onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u best vooraf.",
        ],
        "wijken": "Brecht-Centrum, Sint-Job-in-’t-Goor, Sint-Lenaarts, Overbroek, Brechtse Heide, Station Noorderkempen, Kanaal Dessel-Schoten",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Sint-Lenaarts en Overbroek?", "Ja, alle kernen van Brecht horen bij ons bezorggebied, ook Sint-Lenaarts en het landelijke Overbroek. Houd er rekening mee dat de rit naar de buitenste gehuchten eerder tegen de bovengrens van onze indicatie van 25 tot 40 minuten aanleunt."],
            ["Kan ik mijn bestelling afhalen aan het station Noorderkempen?", "Nee, wij leveren uitsluitend aan de deur van een woonadres en niet op openbare plaatsen zoals een stationsparking. Geef uw thuisadres in Brecht door, dan komt onze bezorger daar langs."],
            ["Is bestellen in Brecht ook mogelijk in het weekend?", "Ja, wij bezorgen zeven dagen per week, ook op vrijdag- en zaterdagavond. In het weekend is het drukker, waardoor de levertijd kan oplopen; meer daarover leest u op onze pagina over <a href=\"/lachgas-weekendbezorging/\">weekendbezorging</a>."],
        ],
        "nearby": ["schilde", "malle", "brasschaat"],
        "lat": 51.350, "lon": 4.638,
    },
    {
        "slug": "zoersel",
        "name": "Zoersel",
        "kind": "gemeente",
        "title": "Lachgas Zoersel | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Zoersel? Lachgastanks en patronen aan huis in Zoersel, Halle en Sint-Antonius, meestal binnen 25 tot 40 minuten. Uitsluitend voor 18+.",
        "h1": "Lachgas bezorgen in Zoersel",
        "lead": "Lachgas aan huis in Zoersel, Halle en Sint-Antonius: besteld via WhatsApp, prijs vooraf bevestigd, betaald bij levering.",
        "intro": [
            "Zoersel bestaat uit drie dorpen aan de rand van de Kempen: Zoersel zelf met het Zoerselbos, Halle met zijn kasteel en Sint-Antonius, dat langs de Handelslei bijna naadloos overgaat in Schilde. De gemeente ligt tussen de E34 en de N12 en combineert villawijken met oude dorpskernen en bosgebied. Woont u in een van die kernen en wilt u lachgas laten bezorgen, dan stuurt u ons een WhatsApp-bericht met de gewenste tank of patronen en uw adres. Wij reageren met de prijs en een realistische inschatting van het levermoment, waarna onze bezorger vertrekt.",
            "De snelste weg vanuit Antwerpen is de E34 richting Turnhout tot de afrit Zoersel, vanwaar de N14 u in enkele minuten naar het dorpscentrum of naar Halle brengt. Voor Sint-Antonius rijden wij vaak over de N12 door Wijnegem en Schilde. Door de afstand tot de stad en de rustige maar bochtige lokale wegen houden wij een indicatie van meestal 25 tot 40 minuten aan. Zoersel heeft geen station; de streekbussen van De Lijn richting Antwerpen en Turnhout stoppen langs de Handelslei en de Antwerpsesteenweg. Wij rijden evenwel tot uw voordeur, zodat u zich daar niets van hoeft aan te trekken.",
            "Een avond met vrienden in een villa aan het Zoerselbos, een verjaardag in een rijhuis in Halle of een feest in een appartement langs de Handelslei: bepaal eerst hoe groot uw gezelschap is. Voor een klein groepje is de 2KG-tank handig, voor meer gasten kiest u de 4KG of de 10KG. Alle formaten staan samen met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan wie 18 jaar of ouder is en controleren dat indien nodig aan de deur. Betalen gebeurt bij levering, cash of via Payconiq. Op onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u hoe u verantwoord met lachgas omgaat.",
        ],
        "wijken": "Zoersel-Centrum, Halle, Sint-Antonius, Handelslei, Zoerselbos, Kasteel van Halle, Antwerpsesteenweg, Westmallebaan",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Horen Halle en Sint-Antonius ook bij het bezorggebied Zoersel?", "Ja, beide deelgemeenten horen bij Zoersel en wij leveren er aan huis. Voor Sint-Antonius kiest onze bezorger meestal de N12, voor Halle en Zoersel-centrum de E34; de indicatie van 25 tot 40 minuten geldt voor alle drie."],
            ["Wat gebeurt er als het druk is op de E34?", "Bij file op de E34 rijden wij om via de N12 door Wijnegem en Schilde. Wij laten u via WhatsApp weten wanneer wij vertrekken en of de verwachte aankomsttijd daardoor verschuift."],
            ["Kan ik in Zoersel ook alleen slagroompatronen of een cracker bestellen?", "Ja, u kunt elk product uit ons aanbod afzonderlijk bestellen, ook enkel <a href=\"/product/slagroompatronen/\">slagroompatronen</a> of een cracker. Vermeld in uw bericht wat u precies wenst, dan bevestigen wij de prijs vooraf."],
        ],
        "nearby": ["schilde", "malle", "brecht"],
        "lat": 51.268, "lon": 4.713,
    },
    {
        "slug": "malle",
        "name": "Malle",
        "kind": "gemeente",
        "title": "Lachgas Malle | Bezorgd in Oostmalle en Westmalle",
        "description": "Lachgas bestellen in Malle? Lachgastanks en patronen aan huis in Westmalle en Oostmalle, meestal binnen 25 tot 40 minuten. Betalen bij levering, enkel 18+.",
        "h1": "Lachgas bezorgen in Malle",
        "lead": "Lachgas aan huis in Westmalle en Oostmalle, geregeld via WhatsApp en afgerekend bij levering, cash of via Payconiq.",
        "intro": [
            "Malle is de fusie van Westmalle, bekend van de trappistenabdij aan de Antwerpsesteenweg, en Oostmalle, met het kasteeldomein de Renesse en het voormalige militaire vliegveld. Beide dorpen liggen op de as van de N12 tussen Antwerpen en Turnhout, omringd door bossen, weiden en Kempense zandgronden. Vanuit Antwerpen leveren wij er lachgas aan huis. Wilt u bestellen, dan stuurt u ons een WhatsApp-bericht met het gewenste formaat en uw adres in Westmalle of Oostmalle; wij bevestigen meteen de prijs en laten weten wanneer onze bezorger bij u kan zijn.",
            "Onze bezorger rijdt vanuit Antwerpen over de E34 richting Turnhout tot de afrit Zoersel en volgt daarna de N14 naar Westmalle, of hij kiest de N12 die via Wijnegem, Schilde en Sint-Antonius rechtdoor naar Malle loopt. Oostmalle ligt nog een paar kilometer verder langs dezelfde steenweg. Malle is de verste gemeente in onze Voorkempenzone, waardoor leveringen vaker tegen de 40 minuten aanleunen dan tegen de 25. Een treinstation is er niet; De Lijn verbindt beide dorpen met Antwerpen, Turnhout en Zoersel. U hoeft daar echter niet op te wachten, want onze bezorger rijdt tot aan uw huis.",
            "Van een verjaardagsfeest in een nieuwbouwwijk in Oostmalle tot een avond met vrienden in een rijwoning in het centrum van Westmalle: kies de tank die bij het aantal gasten past. De 2KG is ideaal voor een klein gezelschap, de 4KG en 10KG zijn er voor wie meer mensen verwacht. Ons volledige aanbod, inclusief crackers en slagroompatronen, vindt u op de pagina <a href=\"/assortiment/\">assortiment</a>. Wij leveren enkel aan volwassenen vanaf 18 jaar en vragen bij twijfel een identiteitskaart. Afrekenen doet u bij levering, cash of via Payconiq. Lees ook onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a>.",
        ],
        "wijken": "Westmalle, Oostmalle, Antwerpsesteenweg, Trappistenabdij Westmalle, Domein de Renesse, Vliegveld Oostmalle, Turnhoutsebaan, Hoogstraatsebaan",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie zowel in Westmalle als in Oostmalle?", "Ja, beide deelgemeenten vallen onder ons bezorggebied Malle. Oostmalle ligt iets verder van Antwerpen, dus daar kan de levertijd dichter bij de bovengrens van meestal 25 tot 40 minuten uitkomen."],
            ["Hoe plaats ik een bestelling vanuit Malle?", "U stuurt ons een WhatsApp-bericht met het gewenste product en uw adres. Wij antwoorden met de prijs en een indicatie van de levertijd; pas na uw akkoord vertrekt onze bezorger. Hoe dat precies verloopt, staat op onze pagina over de <a href=\"/werkwijze/\">werkwijze</a>."],
            ["Is Malle de verste gemeente waar jullie nog binnen 40 minuten leveren?", "Malle hoort bij de buitenrand van onze zone met 25 tot 40 minuten; verder richting Turnhout en Herentals rekenen wij meestal 45 tot 75 minuten. Woont u aan de grens van Malle, geef dan uw volledige adres door zodat wij de inschatting kunnen aanpassen."],
        ],
        "nearby": ["zoersel", "brecht", "turnhout"],
        "lat": 51.298, "lon": 4.700,
    },
    {
        "slug": "kruibeke",
        "name": "Kruibeke",
        "kind": "gemeente",
        "title": "Lachgas Kruibeke | Bezorgd in Bazel en Rupelmonde",
        "description": "Lachgas bestellen in Kruibeke? Lachgastanks en patronen aan huis in Kruibeke, Bazel en Rupelmonde aan de Schelde, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Kruibeke",
        "lead": "Lachgas aan huis op de linkeroever van de Schelde: Kruibeke, Bazel en Rupelmonde, besteld via WhatsApp en betaald bij levering.",
        "intro": [
            "Kruibeke ligt op de Wase oever van de Schelde, recht tegenover Hoboken en Hemiksem, en bestaat uit drie dorpen: Kruibeke met zijn uitgestrekte polders, Bazel met het kasteel Wissekerke en het veer naar Hemiksem, en Rupelmonde met de getijdenmolen en het Mercatorplein. De Polders van Kruibeke vormen het grootste gecontroleerde overstromingsgebied van Vlaanderen. Sinds 2025 maakt Kruibeke deel uit van de fusiegemeente met Beveren en Zwijndrecht, maar voor onze bezorging verandert dat niets. Bestel via WhatsApp met uw adres en de gewenste producten; wij bevestigen prijs en levertijd.",
            "Vanuit Antwerpen rijdt onze bezorger door de Kennedytunnel en volgt hij de E17 richting Gent tot de afrit Kruibeke, vanwaar hij via de dorpskern of langs de Schelde naar Bazel en Rupelmonde doorrijdt. Het veer tussen Hemiksem en Bazel is enkel voor voetgangers en fietsers, dus dat gebruiken wij niet. De tunnel en de E17 zijn op piekmomenten gevoelig voor file, en daarom geven wij een indicatie van meestal 25 tot 40 minuten. Kruibeke heeft geen eigen station; de bussen van De Lijn rijden via Zwijndrecht naar Antwerpen en naar Temse. Voor onze levering hoeft u enkel thuis te zijn.",
            "Een verjaardag in een polderwoning in Kruibeke, een avond met vrienden in een appartement aan het Mercatorplein of een familiefeest in Bazel: wij leveren het formaat dat u nodig heeft. Een klein gezelschap is doorgaans goed af met de 2KG-tank; voor meer gasten zijn er de 4KG en de 10KG. Het overzicht van tanks, crackers en slagroompatronen staat in ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen uitsluitend aan personen van 18 jaar of ouder en kunnen daarvoor een identiteitsbewijs vragen. Betalen doet u bij levering, cash of via Payconiq. Onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> raden wij iedereen aan.",
        ],
        "wijken": "Kruibeke-Centrum, Bazel, Rupelmonde, Polders van Kruibeke, Kasteel Wissekerke, Mercatorplein, Scheldedijk, Veer Bazel-Hemiksem",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Rupelmonde en Bazel?", "Ja, alle drie de dorpen van Kruibeke horen bij ons bezorggebied. Onze bezorger rijdt na de afrit Kruibeke door naar Bazel of Rupelmonde; reken daar op een levertijd aan de bovenkant van meestal 25 tot 40 minuten."],
            ["Verandert de fusie met Beveren en Zwijndrecht iets aan de bezorging?", "Nee. Kruibeke, Beveren en Zwijndrecht hebben elk een eigen pagina op onze site en dezelfde levertijdindicatie. U vermeldt gewoon uw straat en huisnummer; onze bezorger kent de weg in het hele Waasland."],
            ["Wat als de Kennedytunnel vaststaat?", "Dan wijkt onze bezorger uit via de Waaslandtunnel en Zwijndrecht of via de Liefkenshoektunnel. Wij melden u via WhatsApp of de aankomsttijd daardoor verschuift, zodat u niet in het ongewisse blijft."],
        ],
        "nearby": ["zwijndrecht", "temse", "beveren"],
        "lat": 51.172, "lon": 4.311,
    },
    {
        "slug": "temse",
        "name": "Temse",
        "kind": "gemeente",
        "title": "Lachgas Temse | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Temse? Wij bezorgen lachgastanks en patronen in Temse, Steendorp, Tielrode en Elversele, meestal binnen 25 tot 40 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Temse",
        "lead": "Van de Wilfordkaai tot Tielrode en Elversele: lachgas aan huis in Temse, besteld via WhatsApp en betaald aan de deur.",
        "intro": [
            "Temse is de Scheldegemeente van het Waasland, met de lange Scheldebrug van de N16 naar Bornem als herkenningspunt en de voormalige scheepswerf aan De Zaat, waar nu woningen en kantoren staan. De gemeente omvat naast Temse zelf de dorpen Steendorp, Tielrode aan de monding van de Durme en Elversele richting Waasmunster. Het centrum rond de Markt en de Wilfordkaai is het levendigste deel. Woont u in een van deze kernen, dan bestelt u lachgas door ons een WhatsApp-bericht te sturen met uw adres en de gewenste producten; wij bevestigen de prijs voor onze bezorger vertrekt.",
            "Onze bezorger kiest vanuit Antwerpen doorgaans de E17 door het Waasland en rijdt vanaf de afrit Haasdonk naar Temse, of hij volgt de Schelde via Kruibeke, Bazel en Rupelmonde tot aan Steendorp en het centrum. Temse ligt verder van de stad dan de eerste Wase gemeenten, en de drukte aan de Scheldebrug of in de Kennedytunnel kan de rit vertragen; daarom rekenen wij op meestal 25 tot 40 minuten. Het station Temse ligt op lijn 54 tussen Sint-Niklaas en Mechelen en De Lijn bedient de deelgemeenten. Wij leveren aan de deur, dus u hoeft zich niet te verplaatsen.",
            "Een appartement aan De Zaat, een rijhuis in Steendorp of een woning in het landelijke Elversele: overal in Temse brengen wij de tank die bij uw gelegenheid past. Voor een avond met een handvol vrienden is de 2KG-tank meestal ruim genoeg, voor een groter feest kiest u 4KG of 10KG. Crackers en slagroompatronen leveren wij er desgewenst bij; alles staat in ons <a href=\"/assortiment/\">assortiment</a>. Bestellen is voorbehouden aan 18-plussers en wij controleren dat zo nodig met een identiteitsbewijs. Afrekenen gebeurt bij levering, cash of via Payconiq. Lees vooraf onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>, zodat u weet waar u op let.",
        ],
        "wijken": "Temse-Centrum, Markt, Wilfordkaai, De Zaat, Steendorp, Tielrode, Elversele, Scheldebrug, Station Temse",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Tielrode en Elversele?", "Ja, alle deelgemeenten van Temse horen bij ons bezorggebied, ook Tielrode aan de Durme en Elversele aan de rand van het Waasland. Voor die buitenste dorpen kan de levertijd dichter bij de 40 minuten liggen dan bij de 25."],
            ["Rijden jullie over de Scheldebrug om in Temse te komen?", "Niet noodzakelijk: vanuit Antwerpen komt onze bezorger via het Waasland aan de noordkant van de Schelde en hoeft hij de brug niet over. De brug gebruiken wij wel voor ritten tussen Temse en Bornem of Puurs-Sint-Amands."],
            ["Mag lachgas in België nog geleverd worden?", "De Belgische regelgeving is sinds het Koninklijk Besluit van 11 maart 2024 strenger geworden en beperkt verkoop en bezit tot medische, technische en culinaire doeleinden. Wij leveren uitsluitend aan volwassenen en zetten het wettelijke kader uiteen op onze pagina over de <a href=\"/lachgas-informatie/lachgaswet-belgie-2024/\">lachgaswet van 2024</a>."],
        ],
        "nearby": ["kruibeke", "bornem", "sint-niklaas"],
        "lat": 51.128, "lon": 4.214,
    },
    {
        "slug": "rumst",
        "name": "Rumst",
        "kind": "gemeente",
        "title": "Lachgas Rumst | Bezorgd in Rumst, Reet en Terhagen",
        "description": "Lachgas bestellen in Rumst? Lachgastanks en patronen aan huis in Rumst, Reet en Terhagen aan de Rupel, meestal binnen 25 tot 40 minuten. Uitsluitend 18+.",
        "h1": "Lachgas bezorgen in Rumst",
        "lead": "Lachgas aan huis in Rumst, Reet en Terhagen: bestellen via WhatsApp, prijs vooraf bevestigd, betalen bij levering.",
        "intro": [
            "Rumst ligt precies op het punt waar de Nete en de Dijle samenvloeien tot de Rupel, tussen Boom en Mechelen. De gemeente telt drie kernen: Rumst zelf aan de N1 tussen Antwerpen en Mechelen, Reet aan de kant van de A12 en Terhagen aan de Rupel, waar de oude kleiputten van de steenbakkerijen het landschap bepalen. Rustige woonwijken worden afgewisseld met weiden en natuur langs de rivieren. Lachgas laten leveren doet u door ons via WhatsApp uw adres en het gewenste formaat door te geven; wij bevestigen de prijs en het verwachte levermoment voordat onze bezorger de baan op gaat.",
            "Vanuit Antwerpen rijden wij via de E19 tot de afrit Rumst en zo over de N1 het centrum binnen, of via de A12 richting Boom en de N171 naar Reet en Terhagen. Beide routes zijn vlot, maar de avondspits op de E19 en de A12 is berucht, en daarom houden wij een indicatie aan van meestal 25 tot 40 minuten. Rumst heeft geen eigen treinstation: de dichtstbijzijnde zijn Boom en Kontich-Lint, en De Lijn rijdt via de N1 en door Reet. Dat is enkel ter informatie, want onze bezorger komt tot aan uw voordeur, in welke kern u ook woont.",
            "Een feest in een gezinswoning in Reet, een verjaardag in een appartement aan de Rupeldijk in Terhagen of een avond met vrienden in het centrum van Rumst: wij hebben voor elke groepsgrootte een tank. Met de 2KG bent u goed af voor een klein gezelschap; de 4KG en 10KG zijn er voor grotere groepen. Het volledige gamma, inclusief crackers en slagroompatronen, staat in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan meerderjarigen en vragen bij twijfel om een identiteitskaart. U betaalt bij levering, cash of via Payconiq. Neem vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord gebruik</a> door, zodat u weet waar u op moet letten.",
        ],
        "wijken": "Rumst-Centrum, Markt, Reet, Terhagen, Rupeldijk, Kleiputten Terhagen, Eikenstraat, Nete en Dijle",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Terhagen en Reet?", "Ja, de drie kernen van Rumst behoren alle tot ons bezorggebied. Voor Reet komt onze bezorger meestal via de A12, voor Rumst-centrum en Terhagen via de E19 en de N1; de indicatie blijft overal 25 tot 40 minuten."],
            ["Wat als ik net over de gemeentegrens in Boom of Kontich woon?", "Geen probleem: zowel <a href=\"/bezorggebied/boom/\">Boom</a> als Kontich hebben een eigen pagina en vallen in dezelfde zone. Geef uw exacte adres door, dan weet onze bezorger meteen welke route hij moet nemen."],
            ["Hoe weet ik dat mijn bestelling in Rumst onderweg is?", "Zodra onze bezorger vanuit Antwerpen vertrekt, krijgt u een WhatsApp-bericht. Verwacht hij vertraging op de E19 of de A12, dan meldt hij dat ook, zodat u weet wanneer u mag opendoen."],
        ],
        "nearby": ["boom", "kontich", "duffel"],
        "lat": 51.081, "lon": 4.422,
    },
    {
        "slug": "bornem",
        "name": "Bornem",
        "kind": "gemeente",
        "title": "Lachgas Bornem | Aan huis in Klein-Brabant",
        "description": "Lachgas bestellen in Bornem? Lachgastanks en patronen aan huis in Bornem, Hingene, Mariekerke en Weert, meestal binnen 25 tot 40 minuten. Uitsluitend 18+.",
        "h1": "Lachgas bezorgen in Bornem",
        "lead": "Lachgas aan huis in Bornem, Hingene, Mariekerke en Weert: één WhatsApp-bericht, prijs vooraf bevestigd, betalen bij levering.",
        "intro": [
            "Bornem is het hart van Klein-Brabant, ingesloten tussen de Schelde, de Oude Schelde en de Rupel, en bekend van het kasteel Marnix de Sainte-Aldegonde, de Sint-Bernardusabdij en de Dodentocht die elk jaar in augustus duizenden stappers lokt. Naast het centrum horen Hingene met het kasteeldomein d’Ursel, het vissersdorp Mariekerke en Weert aan de Oude Schelde bij de gemeente. Wij bezorgen er lachgas aan huis vanuit Antwerpen. Stuur ons via WhatsApp uw adres en het gewenste product; u krijgt de prijs en een indicatie van de levertijd terug voordat wij vertrekken.",
            "Onze bezorger rijdt vanuit Antwerpen over de A12 richting Brussel tot de N16 bij Breendonk en volgt die westwaarts door Puurs tot in Bornem; komt hij vanuit het Waasland, dan steekt hij de Scheldebrug bij Temse over. Bornem ligt aan de buitenrand van onze zone met 25 tot 40 minuten, zodat de rit vaker richting de bovengrens gaat dan bij gemeenten dichter bij de stad. Het station Bornem ligt op lijn 54 tussen Mechelen en Sint-Niklaas, en De Lijn verbindt de dorpen met Puurs en Temse. Dat openbaar vervoer heeft u voor uw bestelling niet nodig: wij komen tot bij u thuis.",
            "Een feestje in een rijhuis in het centrum, een verjaardag in een hoeve in Hingene of een avond met vrienden aan de Scheldedijk in Mariekerke: laat ons weten hoeveel gasten u verwacht, dan adviseren wij het formaat. De 2KG-tank is er voor kleine groepen, de 4KG en 10KG voor grotere gelegenheden, en crackers en slagroompatronen bestelt u er desgewenst bij; u vindt ze alle in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan wie 18 jaar of ouder is en vragen zo nodig een identiteitsbewijs. Betalen doet u bij levering, cash of via Payconiq. Lees ook hoe u <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig met lachgas omgaat</a>.",
        ],
        "wijken": "Bornem-Centrum, Hingene, Mariekerke, Weert, Wintam, Branst, Kasteel Marnix de Sainte-Aldegonde, Oude Schelde, Station Bornem",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Mariekerke en Weert?", "Ja, ook de buitenste kernen van Bornem, zoals Mariekerke en Weert aan de Oude Schelde, horen bij ons bezorggebied. Reken daar op een levertijd aan de bovenkant van onze indicatie van meestal 25 tot 40 minuten."],
            ["Kunnen jullie tijdens de Dodentocht in Bornem leveren?", "Ja, maar tijdens dat weekend zijn veel straten in het centrum afgesloten en is het verkeer omgeleid, waardoor de levertijd kan oplopen. Wij overleggen dan via WhatsApp over een bereikbaar woonadres en een realistisch tijdstip."],
            ["Welke tank kies ik voor een feest in Bornem?", "Dat hangt af van de grootte van uw gezelschap en de duur van de avond. In ons artikel <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">2KG, 4KG of 10KG</a> leggen wij de verschillen uit, en via WhatsApp denken wij graag met u mee."],
        ],
        "nearby": ["puurs", "temse", "willebroek"],
        "lat": 51.097, "lon": 4.243,
    },
    {
        "slug": "puurs",
        "name": "Puurs-Sint-Amands",
        "kind": "gemeente",
        "title": "Lachgas Puurs-Sint-Amands | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Puurs-Sint-Amands? Lachgastanks en patronen aan huis in Puurs, Breendonk en Sint-Amands, meestal binnen 25 tot 40 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Puurs-Sint-Amands",
        "lead": "Lachgas aan huis in Puurs, Breendonk, Liezele, Ruisbroek en Sint-Amands: bestellen via WhatsApp, betalen bij levering.",
        "intro": [
            "Puurs-Sint-Amands ontstond in 2019 uit de fusie van Puurs en Sint-Amands en strekt zich uit van de A12 bij Breendonk tot de Scheldebocht bij Sint-Amands. Tot de gemeente behoren Puurs met de wijk Kalfort, Breendonk met zijn brouwerij, Liezele met het fort uit de Antwerpse vestinggordel, Ruisbroek en aan de Schelde Sint-Amands, Lippelo en Oppuurs. Industrie, woonwijken en Klein-Brabants platteland wisselen elkaar af. Lachgas bestelt u door ons via WhatsApp uw adres en het gewenste formaat te sturen; wij bevestigen de prijs en melden wanneer onze bezorger vertrekt.",
            "De route vanuit Antwerpen loopt over de A12 richting Brussel tot de N16 ter hoogte van Breendonk en Willebroek, en daarna via de N16 of de lokale wegen naar Puurs, Ruisbroek of verder naar Sint-Amands. De gemeente is uitgestrekt, dus de ligging van uw adres bepaalt of de levering eerder 25 of eerder 40 minuten duurt. Puurs heeft een station waar lijn 52 vanuit Antwerpen eindigt en lijn 54 tussen Mechelen en Sint-Niklaas passeert; De Lijn verbindt de deelgemeenten met Puurs en Bornem. Wij leveren onafhankelijk daarvan tot aan uw voordeur.",
            "Een familiefeest in een hoeve in Lippelo, een verjaardag in een appartement bij het station van Puurs of een avond met vrienden aan de Schelde in Sint-Amands: laat ons via WhatsApp weten wat u nodig heeft. Kleine groepen kiezen meestal de 2KG-tank, grotere gezelschappen de 4KG of 10KG; samen met crackers en slagroompatronen vindt u ze in ons <a href=\"/assortiment/\">assortiment</a>. Bestellen kan uitsluitend vanaf 18 jaar en wij vragen bij twijfel een identiteitskaart te tonen. Afrekenen gebeurt bij levering, cash of via Payconiq. Op de pagina <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u hoe u verantwoord omgaat met lachgas.",
        ],
        "wijken": "Puurs-Centrum, Kalfort, Breendonk, Liezele, Ruisbroek, Sint-Amands, Lippelo, Oppuurs, Fort Liezele, Station Puurs",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie ook in Sint-Amands, Lippelo en Oppuurs?", "Ja, de hele fusiegemeente Puurs-Sint-Amands hoort bij ons bezorggebied, inclusief de dorpen aan de Schelde. Die liggen het verst van Antwerpen, dus daar leunt de levertijd eerder aan tegen de 40 minuten uit onze indicatie."],
            ["Bezorgen jullie ook in Breendonk en Kalfort?", "Zeker, Breendonk en de Puurse wijk Kalfort liggen dicht bij de A12 en zijn voor onze bezorger het snelst bereikbaar van de hele gemeente. Levering gebeurt aan de deur van uw woonadres."],
            ["Wat doe ik met een lege tank in Puurs-Sint-Amands?", "Een lege lachgastank hoort nooit bij het restafval. Meestal kunt u ze afgeven op het recyclagepark; informeer vooraf bij uw gemeente en lees ons artikel over <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">een lege lachgasfles inleveren</a>."],
        ],
        "nearby": ["bornem", "willebroek", "boom"],
        "lat": 51.074, "lon": 4.287,
    },
    {
        "slug": "boom",
        "name": "Boom",
        "kind": "gemeente",
        "title": "Lachgas Boom | Snel bezorgd in de Rupelstreek",
        "description": "Lachgas bestellen in Boom? Lachgastanks en patronen aan huis in heel Boom, van de Kaai tot Noeveren en de Bosstraat, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Boom",
        "lead": "Lachgas aan huis in Boom: van de Grote Markt tot Noeveren, besteld via WhatsApp en afgerekend bij levering.",
        "intro": [
            "Boom is de centrumgemeente van de Rupelstreek, aan de noordoever van de Rupel tegenover Klein-Willebroek. Het steenbakkersverleden leeft voort in Noeveren, met zijn oude ovens en arbeidershuisjes, en in de kleiputten die werden omgevormd tot het provinciaal domein De Schorre. De A12 loopt dwars door de gemeente, met de Grote Markt en de Kaai in het oude centrum en nieuwere woonwijken en bedrijventerreinen zoals Krekelenberg daarbuiten. Lachgas laten leveren doet u door ons via WhatsApp uw adres en het gewenste product te sturen; wij bevestigen de prijs en het levermoment voordat wij vertrekken.",
            "Vanuit Antwerpen is Boom eenvoudig te bereiken: onze bezorger volgt de A12 richting Brussel en verlaat die aan de afrit Boom, waarna de N177 of de Antwerpsestraat hem naar uw wijk brengt. Op gewone dagen is dat een korte rit, maar in de spits en op zaterdagnamiddag staat de A12 vaak stil, en bij grote evenementen op De Schorre gelden omleidingen; vandaar onze indicatie van meestal 25 tot 40 minuten. Het station Boom ligt op lijn 52 richting Antwerpen en Puurs, en De Lijn rijdt via de Antwerpsestraat door het centrum. Wij komen echter tot aan uw deur, zodat u niets hoeft te regelen.",
            "Een verjaardag in een appartement aan de Kaai, een feestje in een arbeiderswoning in Noeveren of een avond met vrienden in de Bosstraat: kies de tank die past bij uw gezelschap. De 2KG is geschikt voor een klein groepje, de 4KG en de 10KG voor wie meer gasten verwacht. Alle formaten, crackers en slagroompatronen staan samen in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan 18-plussers en vragen zo nodig een identiteitsbewijs aan de deur. Betalen doet u bij levering, cash of via Payconiq. Lees ook onze aanbevelingen over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> voor u bestelt.",
        ],
        "wijken": "Boom-Centrum, Grote Markt, Kaai, Antwerpsestraat, Noeveren, Bosstraat, De Schorre, Krekelenberg, Rupelbrug, Station Boom",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Leveren jullie tijdens festivals op De Schorre?", "Ja, maar tijdens die weekends zijn delen van Boom afgesloten en worden wegen omgeleid, waardoor de levertijd kan oplopen. Wij leveren uitsluitend aan een woonadres en nooit op het festivalterrein of op campings."],
            ["Bezorgen jullie ook in Noeveren en aan de Rupeldijk?", "Zeker, heel Boom hoort bij ons bezorggebied, ook de oude steenbakkerswijk Noeveren en de woningen langs de Rupel. Onze bezorger belt aan op het adres dat u via WhatsApp doorgeeft."],
            ["Kan ik in Boom ook laat op de avond bestellen?", "Ja, wij zijn elke dag ook ’s avonds en ’s nachts bereikbaar via WhatsApp. Hoe de levering op latere uren verloopt, leest u op onze pagina over <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["niel", "rumst", "willebroek"],
        "lat": 51.092, "lon": 4.367,
    },
    {
        "slug": "willebroek",
        "name": "Willebroek",
        "kind": "gemeente",
        "title": "Lachgas Willebroek | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Willebroek? Lachgastanks en patronen aan huis in Willebroek, Blaasveld, Tisselt en Heindonk, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Willebroek",
        "lead": "Lachgas aan huis in Willebroek en zijn deelgemeenten, geregeld via WhatsApp en betaald bij levering, cash of via Payconiq.",
        "intro": [
            "Willebroek ligt aan het Zeekanaal Brussel-Schelde, halfweg tussen Antwerpen en Brussel, en is bekend van het Fort van Breendonk, dat als memoriaal op het grondgebied van de gemeente ligt, en van de watersportbaan Hazewinkel. Naast het centrum rond de Dendermondsesteenweg en het kanaal horen Blaasveld, Tisselt, Heindonk en het pittoreske Klein-Willebroek aan de Rupel bij de gemeente. Lachgas bestelt u door ons via WhatsApp uw adres en het gewenste formaat te sturen; wij antwoorden met de prijs en een indicatie van het levermoment, en pas na uw akkoord gaat onze bezorger op weg.",
            "Onze bezorger rijdt vanuit Antwerpen over de A12 richting Brussel en neemt de afrit Willebroek, vanwaar de N16 hem in enkele minuten naar het centrum brengt; Klein-Willebroek bereikt hij via Boom en de Rupelbrug. De A12 is in de spits gevoelig voor file en de bruggen over het kanaal gaan af en toe open voor de scheepvaart, zodat wij een indicatie van meestal 25 tot 40 minuten hanteren. Het station Willebroek ligt op lijn 54 tussen Mechelen en Sint-Niklaas, en De Lijn verbindt de deelgemeenten met Boom en Mechelen. Voor onze levering is dat niet van belang: wij komen tot aan uw voordeur.",
            "Een feest in een rijhuis bij het kanaal, een verjaardag in een nieuwbouwwoning in Blaasveld of een avond met vrienden in Tisselt: wij leveren de tank die bij uw gezelschap hoort. Voor kleine groepen volstaat meestal de 2KG, voor grotere groepen kiest u 4KG of 10KG, en crackers en slagroompatronen bestelt u er eenvoudig bij via ons <a href=\"/assortiment/\">assortiment</a>. Wij bezorgen alleen aan personen van 18 jaar en ouder en kunnen een identiteitskaart vragen. Betalen doet u bij levering, cash of via Payconiq. Op onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u waar u op let.",
        ],
        "wijken": "Willebroek-Centrum, Dendermondsesteenweg, Blaasveld, Tisselt, Heindonk, Klein-Willebroek, Fort van Breendonk, Hazewinkel, Station Willebroek",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Horen Heindonk en Klein-Willebroek ook bij het bezorggebied?", "Ja, alle deelgemeenten van Willebroek vallen onder ons bezorggebied, ook Heindonk bij Hazewinkel en Klein-Willebroek aan de Rupel. Voor die kernen kan de rit iets langer duren, binnen onze indicatie van meestal 25 tot 40 minuten."],
            ["Wat als de brug over het kanaal openstaat?", "Dan wacht onze bezorger even of kiest hij een andere brug over het Zeekanaal. Wij houden u via WhatsApp op de hoogte als dat de aankomsttijd beïnvloedt."],
            ["Kan ik in Willebroek met Payconiq betalen?", "Ja, bij levering betaalt u cash of via Payconiq op uw GSM. Vooraf overschrijven is niet nodig; meer over de mogelijkheden leest u op onze pagina <a href=\"/betalen-bij-levering/\">betalen bij levering</a>."],
        ],
        "nearby": ["boom", "puurs", "mechelen"],
        "lat": 51.060, "lon": 4.360,
    },
    {
        "slug": "duffel",
        "name": "Duffel",
        "kind": "gemeente",
        "title": "Lachgas Duffel | Aan huis aan de Nete",
        "description": "Lachgas bestellen in Duffel? Lachgastanks en patronen aan huis in Duffel-Oost en Duffel-West, aan de Nete, meestal binnen 25 tot 40 minuten. Enkel 18+.",
        "h1": "Lachgas bezorgen in Duffel",
        "lead": "Lachgas aan huis in Duffel, aan beide kanten van de Nete: bestellen via WhatsApp, prijs vooraf bevestigd, betalen bij levering.",
        "intro": [
            "Duffel ligt tussen Lier en Mechelen en wordt door de Nete in twee helften verdeeld: Duffel-West met het station en het oude centrum rond de Sint-Martinuskerk, en Duffel-Oost in de richting van Lier en Sint-Katelijne-Waver. De gemeente gaf haar naam aan de stevige wollen stof van de duffelcoat en telt met het Fort van Duffel een schakel uit de Antwerpse vestinggordel. Woont u in Duffel en wilt u lachgas laten leveren, stuur ons dan een WhatsApp-bericht met uw adres en het gewenste product; wij bevestigen de prijs en het levermoment vooraf.",
            "Onze bezorgers verlaten Antwerpen via de E19 richting Brussel, nemen de afrit Kontich en volgen de Duffelsesteenweg tot in het centrum; voor Duffel-Oost steken zij in het centrum de Nete over. De rit is vrij kort, maar de E19 staat in de spits regelmatig vast en de doortocht door Kontich kent veel verkeerslichten; daarom rekenen wij op meestal 25 tot 40 minuten. Het station Duffel ligt op de spoorlijn Antwerpen-Mechelen-Brussel en De Lijn rijdt via de steenwegen naar Lier, Mechelen en Kontich. Voor uw levering is dat bijzaak: onze bezorger belt aan op het adres dat u opgeeft.",
            "Een verjaardag in een appartement bij het station, een feest in een gezinswoning aan de Mijlstraat of een avond met vrienden in Duffel-Oost: wij leveren het formaat dat u nodig heeft. De 2KG-tank volstaat doorgaans voor een klein gezelschap, de 4KG en 10KG zijn er voor grotere groepen; alle tanks, crackers en slagroompatronen vindt u in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren enkel aan meerderjarigen en vragen zo nodig uw identiteitskaart. Betalen doet u bij levering, cash of via Payconiq. Onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> leest u best voor de avond begint.",
        ],
        "wijken": "Duffel-Centrum, Duffel-West, Duffel-Oost, Station Duffel, Mijlstraat, Notmeir, Fort van Duffel, Netedijk, Sint-Martinuskerk",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie aan beide kanten van de Nete?", "Ja, zowel Duffel-West als Duffel-Oost hoort bij ons bezorggebied. Onze bezorger kiest zelf de handigste brug over de Nete; de indicatie van meestal 25 tot 40 minuten geldt voor de hele gemeente."],
            ["Ik woon in een kot of studio bij het station van Duffel. Kan ik bestellen?", "Ja, zolang u 18 jaar of ouder bent en de levering op uw woonadres gebeurt. Houd uw identiteitskaart bij de hand en respecteer de huisregels van het gebouw; meer tips leest u op onze pagina voor <a href=\"/lachgas-studenten-antwerpen/\">studenten</a>."],
            ["Welke route nemen jullie als de E19 vaststaat?", "Dan rijden wij via de N1 of door Kontich en Lint naar Duffel. U krijgt via WhatsApp een bericht wanneer onze bezorger vertrekt en of de verwachte aankomsttijd verandert."],
        ],
        "nearby": ["kontich", "lier", "mechelen"],
        "lat": 51.097, "lon": 4.508,
    },
    {
        "slug": "beveren",
        "name": "Beveren",
        "kind": "gemeente",
        "title": "Lachgas Beveren | Bezorgd in het Waasland",
        "description": "Lachgas bestellen in Beveren? Lachgastanks en patronen aan huis in Beveren, Melsele, Haasdonk, Vrasene en Kallo, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas bezorgen in Beveren",
        "lead": "Lachgas aan huis in Beveren en de Wase polderdorpen: besteld via WhatsApp, prijs vooraf bevestigd, betaald bij levering.",
        "intro": [
            "Beveren is de grootste gemeente van het Waasland en reikt van de woonkernen Beveren, Melsele en Haasdonk langs de N70 tot de polderdorpen Vrasene, Verrebroek, Kieldrecht en Doel aan de rand van de Waaslandhaven. In het centrum vallen het kasteel Cortewalle en het domein Hof ter Saksen op; Kallo ligt tegen de havendokken en het Fort Liefkenshoek. Sinds 2025 vormt Beveren samen met Kruibeke en Zwijndrecht één fusiegemeente. Lachgas laten bezorgen doet u door ons via WhatsApp uw adres en het gewenste formaat te sturen; wij bevestigen de prijs en melden wanneer onze bezorger vertrekt.",
            "Vanuit Antwerpen rijdt onze bezorger door de Kennedytunnel en volgt hij de E17 tot de afrit Zwijndrecht en vervolgens de N70 door Melsele naar Beveren, of hij neemt de E34 richting Zelzate met afritten voor Melsele, Beveren en Vrasene; Kallo en de polderdorpen bereikt hij via de Liefkenshoektunnel of de Expresweg. De tunnels onder de Schelde zijn in de spits het grootste struikelblok, en de gemeente is uitgestrekt, dus wij geven een indicatie van meestal 25 tot 40 minuten. Beveren en Melsele hebben elk een station op lijn 59 tussen Antwerpen en Gent, en De Lijn verbindt de polderdorpen met het centrum. Onze bezorger komt evenwel tot aan uw voordeur.",
            "Een feest in een rijhuis in het centrum van Beveren, een verjaardag in een nieuwbouwwijk in Melsele of een avond met vrienden in een polderwoning in Kieldrecht: laat ons weten hoeveel gasten u verwacht. Voor kleine groepen is de 2KG-tank het handigst, voor grotere gezelschappen kiest u de 4KG of de 10KG; samen met crackers en slagroompatronen staan ze in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan 18-plussers en controleren dat zo nodig met een identiteitsbewijs. Betalen gebeurt bij levering, cash of via Payconiq. Lees vooraf ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Beveren-Centrum, Melsele, Haasdonk, Vrasene, Kallo, Verrebroek, Kieldrecht, Doel, Kasteel Cortewalle, Hof ter Saksen",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Kieldrecht, Verrebroek en Doel?", "Ja, ook de polderdorpen aan de rand van de Waaslandhaven horen bij Beveren en dus bij ons bezorggebied. Omdat zij het verst van Antwerpen liggen, komt de levertijd daar eerder op 40 dan op 25 minuten uit."],
            ["Leveren jullie op bedrijventerreinen in de Waaslandhaven?", "Nee, wij bezorgen uitsluitend aan woonadressen en niet op haventerreinen, parkings of in bedrijfsgebouwen. Woont u in Kallo of een ander dorp bij de haven, dan komen wij gewoon tot aan uw voordeur."],
            ["Wat als er file staat in de Kennedytunnel?", "Dan kiest onze bezorger de Liefkenshoektunnel of de Waaslandtunnel om Beveren te bereiken. Via WhatsApp hoort u wanneer hij vertrekt en of de aankomsttijd door de omleiding verschuift."],
        ],
        "nearby": ["zwijndrecht", "kruibeke", "sint-niklaas"],
        "lat": 51.212, "lon": 4.256,
    },
]
