# -*- coding: utf-8 -*-
# FAQ-thema's lachgasantwerpen.be (fase 3). Alleen data; schema zie ../BRIEF_TEMPLATE.md.

FAQ_TOPICS = [
    {
        "slug": "bestellen",
        "title": "Vragen over bestellen bij Lachgas Antwerpen",
        "description": "Antwoorden op vragen over bestellen via WhatsApp bij Lachgas Antwerpen: welke gegevens wij nodig hebben, bevestiging, formaten en bestellen voor bedrijven.",
        "h1": "Vragen over bestellen",
        "lead": "Alles over het plaatsen van een bestelling via WhatsApp: van uw eerste bericht tot de bevestiging van uw levering in Antwerpen of daarbuiten.",
        "intro": [
            "Bestellen bij Lachgas Antwerpen verloopt volledig via WhatsApp, zonder webshop en zonder account. Dat houdt het eenvoudig, maar roept wel praktische vragen op: wat moet er in een bericht staan, hoe snel reageren wij, kunt u producten combineren en hoe gaat het als een horecazaak of een vereniging bestelt. Op deze pagina bundelen wij de vragen die daarover het vaakst terugkomen. Vragen over levertijden en zones vindt u bij het thema bezorgen, vragen over cash en Payconiq bij het thema betalen."
        ],
        "items": [
            ["Hoe plaats ik een bestelling bij Lachgas Antwerpen?",
             "U stuurt ons een WhatsApp-bericht met het product dat u wenst, het leveradres en het moment waarop u de levering verwacht. Wij antwoorden met een bevestiging waarin alles samengevat staat, inclusief de prijs die vooraf via WhatsApp wordt bevestigd. Pas na uw akkoord vertrekt de bezorger. Hoe dat stap voor stap gaat, leest u op onze pagina over de <a href=\"/werkwijze/\">werkwijze</a>."],
            ["Kan ik ook bestellen via e-mail of het contactformulier?",
             "Bestellingen nemen wij enkel aan via WhatsApp, omdat wij daar meteen kunnen terugkoppelen over beschikbaarheid en levertijd. E-mail en het contactformulier zijn geschikt voor vragen die niet dringend zijn, bijvoorbeeld over een factuur of een samenwerking. Een bestelling die via e-mail binnenkomt, verwerken wij pas nadat u ze via WhatsApp hebt bevestigd."],
            ["Welke gegevens hebt u nodig voordat de bezorger vertrekt?",
             "Wij hebben een volledig adres nodig met huisnummer, en bij een appartement ook het busnummer of de verdieping en de naam op de bel. Vermeld daarnaast het gewenste tijdstip als u de levering niet meteen verwacht. Wij gaan er bij elke bestelling van uit dat de ontvanger meerderjarig is; hoe dat aan de deur wordt nagekeken, leest u bij het thema regels."],
            ["Hoe snel krijg ik antwoord op mijn bericht?",
             "Tijdens onze bezorguren leest een medewerker uw bericht meestal binnen enkele minuten. Op drukke avonden, zoals vrijdag en zaterdag na tien uur, kan het iets langer duren voordat u een bevestiging ontvangt. Krijgt u geen reactie, stuur dan gerust een herinnering in hetzelfde gesprek in plaats van een nieuw gesprek te starten."],
            ["Kan ik verschillende producten in één bestelling combineren?",
             "Ja, u kunt bijvoorbeeld een lachgastank samen met crackers of slagroompatronen laten leveren. Zet elk product met het gewenste formaat of aantal doosjes in uw bericht, dan bundelen wij alles in één levering en één bevestiging. Het volledige aanbod staat op de pagina <a href=\"/assortiment/\">assortiment</a>."],
            ["Hoe kies ik tussen de tank van 2KG, 4KG en 10KG?",
             "De keuze hangt vooral af van de duur van de gelegenheid en van de plaats waar de fles komt te staan. Een kleiner formaat is handiger om te verplaatsen en te bewaren; een groter formaat is enkel zinvol wanneer u de inhoud ook werkelijk zult gebruiken. Onze <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">keuzehulp</a> zet de drie formaten zakelijk naast elkaar."],
            ["Kan ik bestellen voor iemand anders of op een ander adres laten leveren?",
             "Dat kan, zolang de persoon die de bestelling aanneemt zelf meerderjarig is en dat aan de deur kan aantonen. Geef in uw bericht duidelijk door wie de ontvanger is, zodat de bezorger weet naar wie hij moet vragen. Is er op het adres niemand aanwezig die aan die voorwaarde voldoet, dan gaat de bestelling terug mee."],
            ["Is er een minimumbestelling?",
             "Nee, één product volstaat om een bestelling te plaatsen, of dat nu een cracker, een doosje slagroompatronen of een tank is. Voor de tank van 10KG kan het zijn dat wij een moment met u afspreken, omdat dat formaat meer ruimte in de wagen vraagt. Grotere hoeveelheden voor horeca of een evenement bespreken wij op maat."],
            ["Hoe weet ik dat mijn bestelling goed is aangekomen?",
             "Elke bestelling krijgt in het WhatsApp-gesprek een bevestiging met het product, het adres, het verwachte tijdstip en de betaalwijze. Controleer die samenvatting even; staat er iets fout, dan past u het direct aan in hetzelfde gesprek. Zonder bevestiging van onze kant is er nog geen bestelling geplaatst."],
            ["Kunnen horecazaken, cateraars of bedrijven bij u bestellen?",
             "Ja. Voor horeca en catering leveren wij vooral slagroompatronen in grotere aantallen, bijvoorbeeld voor een druk weekend of een cateringopdracht. Vermeld in uw bericht dat het om een zakelijke bestelling gaat en hoeveel doosjes u ongeveer verwacht, dan stemmen wij de levering daarop af. Het product zelf vindt u bij de <a href=\"/product/slagroompatronen/\">slagroompatronen</a>."],
            ["Welke gegevens bewaart u na mijn bestelling?",
             "Wij bewaren enkel wat nodig is om uw bestelling uit te voeren en eventuele vragen achteraf te beantwoorden: het gesprek, het leveradres en de afgesproken betaalwijze. Wij verkopen geen gegevens en sturen geen reclame via WhatsApp. Wat wij precies bewaren en hoe lang, staat in ons <a href=\"/privacy/\">privacybeleid</a>."],
        ],
        "related": ["bezorgen", "betalen", "werkwijze"],
    },
    {
        "slug": "bezorgen",
        "title": "Vragen over bezorgen in Antwerpen en omgeving",
        "description": "Vragen over de bezorging van lachgas in Antwerpen, de districten, randgemeenten en Vlaamse steden: levertijden, verpakking en wat als u niet thuis bent.",
        "h1": "Vragen over bezorgen",
        "lead": "Hoe lang een levering meestal duurt, waar wij bezorgen en hoe uw bestelling aan de deur wordt afgegeven.",
        "intro": [
            "Onze bezorgers vertrekken vanuit Antwerpen en rijden naar de stad, de districten, de randgemeenten en een reeks Vlaamse steden. Hoe verder het adres, hoe ruimer de indicatie van de levertijd die u in uw bevestiging krijgt. Hieronder leest u welke zones wij onderscheiden, hoe u uw levering kunt volgen, wat er gebeurt als u even niet thuis bent en hoe een tank verpakt bij u aankomt. Voor de volledige lijst met gemeenten verwijzen wij naar het overzicht van ons bezorggebied."
        ],
        "items": [
            ["In welke delen van Antwerpen bezorgt u?",
             "Wij bezorgen in het centrum en in de districten, waaronder Berchem, Borgerhout, Deurne, Hoboken, Merksem en Wilrijk, en ook op Linkeroever, het Eilandje en het Zuid. Binnen de stad duurt een levering meestal 20 tot 30 minuten na onze bevestiging. Alle plaatsen met hun eigen pagina vindt u in het <a href=\"/bezorggebied/\">bezorggebied</a>."],
            ["Hoe lang duurt een levering naar de randgemeenten?",
             "Voor gemeenten rond de stad, zoals Aartselaar, Kapellen, Wijnegem, Boom, Kruibeke of Beveren, rekent u meestal op 25 tot 40 minuten. De extra tijd komt vooral door de afstand tot de ring en de drukte op de invalswegen. In de bevestiging noemen wij altijd de indicatie die voor uw adres geldt."],
            ["Levert u ook in Gent, Leuven, Brussel of Mechelen?",
             "Ja, naast Mechelen, Lier, Sint-Niklaas en Turnhout bezorgen wij onder meer in Gent, Leuven, Brussel, Brugge, Hasselt, Aalst, Herentals, Geel en Lokeren. Voor die steden ligt de levertijd meestal tussen 45 en 75 minuten en vragen wij om uw bestelling bij voorkeur wat vroeger op de dag door te geven. Een overzicht per regio staat op de pagina over <a href=\"/bezorggebied/provincie-antwerpen/\">Provincie Antwerpen en Vlaanderen</a>."],
            ["Waarvan hangt de werkelijke levertijd af?",
             "De indicatie die wij geven is gebaseerd op een normale rit zonder bijzondere omstandigheden. Files aan de Kennedytunnel of op de Antwerpse ring, werken aan de Oosterweelverbinding, slecht weer en het aantal bestellingen dat op dat moment openstaat, kunnen de rit verlengen. Loopt een levering uit, dan laten wij u dat via WhatsApp weten."],
            ["Kan ik volgen waar mijn bestelling is?",
             "Wij werken niet met een trackingpagina, maar u krijgt een bericht zodra de bezorger vertrekt en kunt in het gesprek altijd vragen hoe laat hij ongeveer aankomt. Vlak voor aankomst stuurt de bezorger meestal nog een kort bericht of belt hij aan het afgesproken adres aan. Zo hoeft u niet onnodig te wachten."],
            ["Wat als ik niet thuis ben wanneer de bezorger aankomt?",
             "De bezorger neemt eerst contact met u op via WhatsApp en wacht een korte tijd aan de deur. Wij laten een bestelling nooit achter bij buren, in een gang of op straat, omdat wij de leeftijd van de ontvanger moeten controleren. Lukt het die dag niet, dan plannen wij in overleg een nieuw moment in."],
            ["Levert u op een studentenkot of in een appartementsgebouw?",
             "Ja, op voorwaarde dat u het busnummer, de verdieping en de naam op de bel doorgeeft, zodat de bezorger de juiste deur vindt. In gebouwen met een gemeenschappelijke inkomhal vragen wij u om zelf naar beneden te komen, zodat de controle van uw identiteitskaart rustig kan gebeuren. Specifieke informatie voor kotbewoners staat op de pagina over <a href=\"/lachgas-studenten-antwerpen/\">lachgas voor studenten in Antwerpen</a>."],
            ["Levert u aan een feestzaal, hotel of evenementlocatie?",
             "Wij leveren aan een privéadres of aan een gehuurde locatie waar u als organisator zelf aanwezig bent om de bestelling in ontvangst te nemen. Wij leveren niet aan de ingang van festivals, concertzalen of openbare evenementen, omdat organisatoren lachgas doorgaans verbieden en dat ook voor onze bezorgers problemen geeft. Wat wel kan, leest u op onze pagina over <a href=\"/lachgas-feest-evenement/\">feesten en evenementen</a>."],
            ["Bezorgt u ook 's avonds laat, 's nachts en in het weekend?",
             "Onze bezorguren lopen door tot diep in de avond en in het weekend ook na middernacht; de exacte tijden geven wij in het WhatsApp-gesprek door, omdat ze per dag kunnen verschillen. Na middernacht hanteren wij dezelfde indicaties per zone, al zijn de wegen dan meestal rustiger. Meer hierover vindt u op de pagina over <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
            ["Hoe wordt een lachgastank verpakt en afgegeven?",
             "Elke tank wordt verzegeld en rechtop vervoerd, in een neutrale verpakking zonder opdruk. De bezorger geeft de bestelling persoonlijk aan u af en wijst u kort op de juiste manier van bewaren. Hoe u een tank daarna thuis bewaart of verplaatst, staat in ons artikel over <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."],
            ["Kan ik mijn bestelling zelf komen ophalen?",
             "Nee, wij werken uitsluitend met levering aan huis en hebben geen winkel of afhaalpunt. Zo blijft de overdracht aan de deur de vaste stap bij elke bestelling en vermijden wij dat er flessen op straat worden overhandigd. Woont u buiten ons bezorggebied, stuur dan toch een bericht; soms kunnen wij een levering combineren met een rit in de buurt."],
        ],
        "related": ["bestellen", "regels", "bezorgtijden-antwerpen"],
    },
    {
        "slug": "betalen",
        "title": "Vragen over betalen bij levering",
        "description": "Alles over betalen bij Lachgas Antwerpen: cash of via Payconiq bij levering, prijs vooraf bevestigd via WhatsApp en een factuur op verzoek.",
        "h1": "Vragen over betalen",
        "lead": "U betaalt pas wanneer de bestelling voor u staat: cash of via Payconiq bij levering, zonder vooruitbetaling.",
        "intro": [
            "Bij Lachgas Antwerpen hoeft u niets vooraf over te schrijven en maakt u geen account aan. De prijs wordt vooraf bevestigd via WhatsApp en u betaalt bij levering, cash of via Payconiq. Toch komen er regelmatig vragen over de praktische kant: wat als de app geen verbinding heeft, kunt u gepast betalen, krijgt u een betaalbewijs en hoe gaat het als iemand anders de bestelling aanneemt. De antwoorden leest u hieronder; bedragen noemen wij hier bewust niet."
        ],
        "items": [
            ["Welke betaalmogelijkheden hebt u?",
             "U betaalt cash of via Payconiq bij levering, aan de bezorger die uw bestelling afgeeft. Andere methodes, zoals een overschrijving vooraf of betalen op factuur na levering, bieden wij voor particulieren niet aan. Alle details over beide manieren staan op de pagina <a href=\"/betalen-bij-levering/\">betalen bij levering</a>."],
            ["Kan ik met mijn bankkaart betalen op een terminal?",
             "Onze bezorgers hebben geen betaalterminal bij zich, dus een klassieke kaartbetaling met pincode is niet mogelijk. Wie liever niet met cash werkt, gebruikt de app Payconiq by Bancontact op de GSM, gekoppeld aan de eigen bankrekening. Controleer vooraf of de app geïnstalleerd en geactiveerd is."],
            ["Moet ik vooraf overschrijven of een voorschot betalen?",
             "Nee, wij vragen nooit een voorschot of een overschrijving voordat de bezorger vertrekt. Ontvangt u een bericht dat zogezegd van ons komt en waarin om vooruitbetaling wordt gevraagd, ga daar dan niet op in en meld het ons via het gewone WhatsApp-gesprek. Betalen gebeurt uitsluitend op het moment van de levering."],
            ["Hoe weet ik vooraf wat ik moet betalen?",
             "In de bevestiging die u na uw bestelling via WhatsApp ontvangt, staat het volledige bedrag, inclusief eventuele kosten voor de rit. Dat bedrag verandert niet meer aan de deur, tenzij u zelf nog iets aan de bestelling toevoegt. Zo weet u precies wat u moet klaarleggen of in de app moet goedkeuren."],
            ["Rekent u een bezorgbijdrage aan?",
             "Of er een bijdrage voor de rit geldt, hangt af van de afstand tot uw adres en van het moment van de levering. Wij vermelden dit altijd apart in de bevestiging, zodat u het vooraf weet en er aan de deur niets bijkomt."],
            ["Moet ik gepast betalen als ik cash betaal?",
             "Gepast betalen is niet verplicht, maar onze bezorgers hebben om veiligheidsredenen slechts een beperkte hoeveelheid wisselgeld bij zich. Laat ons in het gesprek weten als u met een groot biljet wilt betalen, dan zorgt de bezorger dat hij voldoende kan teruggeven. Payconiq is in dat geval vaak de eenvoudigste oplossing."],
            ["Krijg ik een betaalbewijs of een factuur?",
             "Bij een betaling via Payconiq ziet u de transactie meteen in uw app, wat voor de meeste klanten als bewijs volstaat. Wilt u een factuur, bijvoorbeeld voor een horecazaak of een vereniging, dan vermeldt u uw bedrijfsnaam en btw-nummer vooraf in het WhatsApp-gesprek. Een factuur achteraf opmaken op een andere naam dan de besteller is niet mogelijk."],
            ["Wat als Payconiq niet werkt op het moment van de levering?",
             "Soms lukt een betaling niet door een zwak netwerk in een inkomhal of kelder, of door een storing bij de bank. De bezorger wacht dan even terwijl u het opnieuw probeert, bijvoorbeeld op een plek met beter bereik. Lukt het echt niet, dan kunt u alsnog cash betalen; zonder betaling kan de bestelling niet worden afgegeven."],
            ["Mag iemand anders de bestelling voor mij betalen?",
             "Ja, de persoon die betaalt hoeft niet dezelfde te zijn als wie heeft besteld, zolang wie de deur opent door de leeftijdscontrole komt. Bij een gezamenlijke bestelling voor een feest regelt u de verdeling onderling; de bezorger neemt één betaling aan en splitst geen bedragen."],
            ["Wat gebeurt er als ik niet kan betalen bij levering?",
             "Dan neemt de bezorger de bestelling terug mee en vervalt de levering. Wij leveren niet op krediet en spreken geen latere betaling af, ook niet voor vaste klanten. Verwacht u dat er een probleem kan zijn met cash of met uw app, meld dat dan voor de bezorger vertrekt, zodat wij samen een oplossing kunnen zoeken."],
            ["Waar vind ik de voorwaarden die bij mijn aankoop gelden?",
             "De afspraken over bestellen, betalen, leveren en annuleren staan in onze <a href=\"/algemene-voorwaarden/\">algemene voorwaarden</a>. Door een bestelling te bevestigen via WhatsApp aanvaardt u die voorwaarden. Vindt u iets onduidelijk, stel uw vraag dan gerust voordat u bestelt."],
        ],
        "related": ["bestellen", "betalen-bij-levering", "bezorgen"],
    },
    {
        "slug": "veiligheid",
        "title": "Vragen over veiligheid en gezondheid",
        "description": "Vragen over de gezondheidsrisico's van lachgas, het bewaren van een tank, een lekkende fles en waar u in Vlaanderen hulp vindt bij problematisch gebruik.",
        "h1": "Vragen over veiligheid",
        "lead": "Eerlijke informatie over de risico's van lachgas, het bewaren van een fles en waar u terechtkunt met zorgen over gebruik.",
        "intro": [
            "Lachgas is geen product zonder risico's: distikstofmonoxide verdringt zuurstof, blokkeert vitamine B12 en komt uit een stalen drukhouder die ijskoud wordt wanneer gas ontsnapt. Wij vinden dat wie bij ons bestelt daar duidelijk over geïnformeerd moet zijn. Op deze pagina beantwoorden wij vragen over gezondheidsrisico's, de combinatie met alcohol, het bewaren van een tank in huis, wat u doet bij een lek en waar u in Vlaanderen hulp vindt. Wij geven hier geen gebruiksinstructies."
        ],
        "items": [
            ["Wat zijn de belangrijkste gezondheidsrisico's van lachgas?",
             "Het grootste acute risico is zuurstoftekort, dat tot duizeligheid, bewustzijnsverlies en valpartijen kan leiden. Bij herhaald gebruik kan het blokkeren van vitamine B12 zenuwschade veroorzaken, met tintelingen en krachtverlies als eerste tekenen. Daarnaast kan contact met een ijskoude fles of met ontsnappend gas bevriezingsletsels geven. Een overzicht van klachten en wat u dan doet, staat in ons artikel over <a href=\"/lachgas-informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>."],
            ["Is lachgas combineren met alcohol extra riskant?",
             "Ja. Alcohol vermindert de controle over wat u doet en verhoogt de kans op vallen, braken en een lagere ademhaling, en lachgas versterkt die effecten. Ook de inschatting of iemand nog in orde is, wordt moeilijker wanneer beide tegelijk in het spel zijn. Lees waarom wij die combinatie afraden in het artikel over <a href=\"/lachgas-informatie/lachgas-en-alcohol/\">lachgas en alcohol</a>."],
            ["Hoe bewaar ik een lachgastank veilig in huis?",
             "Bewaar een tank rechtop, op een koele en droge plek zonder direct zonlicht, en nooit naast een verwarming, fornuis of in een afgesloten auto. Houd de fles buiten het bereik van kinderen en huisdieren en laat de verzegeling zitten tot u de tank nodig heeft. Uitgebreidere richtlijnen vindt u in het artikel over <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">een tank bewaren en vervoeren</a>."],
            ["Waarom wordt een fles zo koud en is dat gevaarlijk?",
             "Lachgas zit vloeibaar onder druk in de fles en onttrekt warmte aan de omgeving zodra er gas ontsnapt. De buitenkant kan daardoor ver onder nul gaan, en blote huid die eraan vastvriest raakt beschadigd. Raak een koude fles enkel aan met handschoenen of een doek en laat ze op kamertemperatuur komen voordat u ze verplaatst."],
            ["Wat doe ik met een fles die sist of lekt?",
             "Zet ramen en deuren open, blijf uit de buurt van de fles en probeer niets te herstellen of vast te draaien. Verplaats de fles, als dat zonder risico kan, naar een goed geventileerde plek buiten, weg van warmte en van mensen, en laat ze daar staan. Een beschadigde fles neemt u niet mee in de auto; laat het ons weten via WhatsApp, dan bekijken wij samen hoe ze veilig weg kan."],
            ["Waarom is ventilatie belangrijk in de ruimte waar een fles staat?",
             "Lachgas is zwaarder dan lucht en kan zich bij een lek ophopen in een kleine of lage ruimte, waar het de zuurstof verdringt zonder dat u het ruikt of ziet. In een kelder, berging of slaapkamer zonder raam is dat risico groter dan in een ruime woonkamer. Zorg daarom dat een fles altijd in een ruimte staat waar frisse lucht kan binnenkomen."],
            ["Welke signalen wijzen op te frequent gebruik?",
             "Tintelingen of een doof gevoel in handen en voeten, moeite met evenwicht, concentratieproblemen en een aanhoudend gevoel van vermoeidheid zijn signalen die u ernstig moet nemen. Ze kunnen wijzen op een tekort aan werkzaam vitamine B12 en op beginnende zenuwschade. Neem bij zulke klachten contact op met uw huisarts en lees ons artikel over <a href=\"/lachgas-informatie/problematisch-lachgasgebruik-hulp/\">hulp bij problematisch gebruik</a>."],
            ["Waar kan ik terecht met zorgen over mijn gebruik of dat van een vriend?",
             "De DrugLijn is in Vlaanderen het eerste aanspreekpunt: anoniem, zonder oordeel en bereikbaar via telefoon, chat en e-mail. U kunt er zowel voor uzelf als voor een vriend, partner of familielid terecht, ook als u enkel wat informatie wilt. Alle contactmogelijkheden staan op <a href=\"https://www.druglijn.be\">druglijn.be</a>."],
            ["Kan lachgas verslavend zijn?",
             "Lichamelijke afhankelijkheid zoals bij alcohol of opiaten wordt zelden beschreven, maar gewoontevorming en psychische afhankelijkheid komen wel voor, vooral bij wie het vaak en alleen gebruikt. Het korte effect maakt dat gebruik snel wordt herhaald, wat de kans op B12-problemen vergroot. Achtergrondinformatie van het Vlaams expertisecentrum vindt u op <a href=\"https://www.vad.be\">vad.be</a>."],
            ["Is lachgas gevaarlijk tijdens de zwangerschap?",
             "Ja, wij raden het gebruik tijdens de zwangerschap en bij een zwangerschapswens sterk af. Het zuurstoftekort en de verstoring van vitamine B12 kunnen de ontwikkeling van het ongeboren kind beïnvloeden, en de risico's zijn onvoldoende onderzocht om een veilige grens te noemen. Bespreek vragen hierover met uw huisarts of gynaecoloog."],
            ["Wat gebeurt er met een lachgasfles bij brand?",
             "Een drukhouder die sterk verhit wordt, kan openbarsten en het gas versterkt bovendien de verbranding van andere materialen. Breekt er brand uit in een ruimte waar een fles staat, verlaat dan het gebouw, verwittig de brandweer via het noodnummer 112 en meld dat er een gasfles aanwezig is. Probeer de fles nooit zelf uit een brandende ruimte te halen."],
        ],
        "related": ["regels", "lachgas-bijwerkingen-en-eerste-hulp", "veilig-gebruik"],
    },
    {
        "slug": "regels",
        "title": "Vragen over regels en wetgeving in België",
        "description": "Vragen over de Belgische lachgaswetgeving: het KB van 2024, verkoop aan minderjarigen, het waarschuwingslabel, regels in Antwerpen en lege flessen.",
        "h1": "Vragen over regels",
        "lead": "Wat de Belgische wet en de stad Antwerpen regelen over lachgas, voorzichtig samengevat en met verwijzing naar de officiële bronnen.",
        "intro": [
            "De regels rond lachgas in België zijn de voorbije jaren grondig veranderd. Na het verkoopverbod aan minderjarigen in 2021 en het verplichte waarschuwingslabel in 2022 kwam er in 2024 een federaal Koninklijk Besluit dat het gas buiten medische, technische en culinaire toepassingen aan banden legt. Daarbovenop gelden in Antwerpen de politiecodex en de huisregels van organisatoren. Wij vatten de meest gestelde vragen hieronder samen, zonder juridisch advies te geven, en verwijzen telkens naar de bron."
        ],
        "items": [
            ["Is lachgas legaal in België?",
             "Sinds het Koninklijk Besluit van 11 maart 2024 zijn de verkoop, het te koop aanbieden, het vervoer en het bezit van lachgas in België verboden voor andere doeleinden dan medisch, technisch of als voedingsadditief. Recreatief gebruik valt niet onder die uitzonderingen. Wat het besluit precies regelt, leest u in ons artikel over de <a href=\"/lachgas-informatie/lachgaswet-belgie-2024/\">lachgaswet van 2024</a>."],
            ["Wat veranderde er in 2024 ten opzichte van de jaren daarvoor?",
             "Voor 2024 bestonden er federaal enkel een verkoopverbod aan minderjarigen en een labelplicht; het aanpakken van overlast was een zaak van gemeenten. Het besluit van 2024 maakte van lachgas een federale kwestie en bracht het onder de bestaande drugswetgeving, waardoor de strafbepalingen daarvan van toepassing kunnen zijn. De officiële informatie van de overheid vindt u op <a href=\"https://www.belgium.be\">belgium.be</a>."],
            ["Zijn slagroompatronen en crackers ook verboden?",
             "Distikstofmonoxide als voedingsadditief, erkend onder nummer E942, valt onder een uitzondering van het besluit, zodat slagroompatronen voor culinair gebruik verkrijgbaar blijven. Een cracker is op zich een toestel en geen gas; of het bezit of gebruik ervan binnen de regels valt, hangt af van het doel waarvoor de patronen worden gebruikt. Meer over het culinaire kader staat in ons artikel over <a href=\"/lachgas-informatie/slagroompatronen-en-horeca/\">slagroompatronen en horeca</a>."],
            ["Vanaf welke leeftijd kan ik bij u bestellen?",
             "Wij leveren uitsluitend aan volwassenen vanaf achttien jaar, zonder uitzondering. De verkoop van lachgas aan minderjarigen is in België al sinds 2021 verboden, los van de regels die later zijn bijgekomen. Wat die maatregel inhoudt en wat ouders kunnen weten, leest u in het artikel over <a href=\"/lachgas-informatie/lachgas-en-minderjarigen-belgie/\">lachgas en minderjarigen</a>."],
            ["Hoe controleert de bezorger mijn leeftijd?",
             "De bezorger vraagt aan de deur naar een geldig identiteitsbewijs: uw identiteitskaart, rijbewijs of paspoort. Hij kijkt enkel naar de geboortedatum en de foto en maakt geen kopie of scan van het document. Kunt u geen bewijs tonen, dan wordt de bestelling niet afgegeven; hoe wij dat precies aanpakken staat op de pagina over <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole</a>."],
            ["Wat betekent het waarschuwingslabel op de verpakking?",
             "Sinds 2022 moet een verpakking van lachgas die aan particulieren wordt verkocht een duidelijk zichtbare waarschuwing dragen over de gezondheidsrisico's. Die waarschuwing moet goed leesbaar zijn en mag niet verstopt zitten in de kleine lettertjes. Ontbreekt zo'n label, dan voldoet het product niet aan de Belgische regels."],
            ["Gelden er in Antwerpen aparte stedelijke regels?",
             "De stad kan via haar politiecodex en gemeentelijke administratieve sancties optreden tegen overlast, zoals achtergelaten flessen, lawaai of samenscholing, maar kan het federale verbod niet versoepelen. Welke lokale bepalingen precies gelden, verandert geregeld en controleert u best op <a href=\"https://www.antwerpen.be\">antwerpen.be</a>. Hoe de federale en stedelijke lagen zich tot elkaar verhouden, beschrijven wij in een apart artikel."],
            ["Mag ik lachgas meenemen naar een festival of evenement?",
             "Nee. Organisatoren van festivals, concerten, kermissen en nachtclubs in en rond Antwerpen zetten lachgas doorgaans op de lijst van verboden voorwerpen, en wat bij de toegangscontrole wordt gevonden, wordt meestal afgenomen. Een organisator mag daarin strenger zijn dan de wet. Wat wij wel voor een privéfeest kunnen betekenen, leest u bij <a href=\"/lachgas-feest-evenement/\">feesten en evenementen</a>."],
            ["Wat moet ik doen met een lege fles?",
             "Een lege fles hoort bij het recyclagepark, bij de afvalstroom voor gasflessen, en nooit bij het restafval, de PMD-zak of op straat. In de verbrandingsoven of de sorteerinstallatie kan een drukhouder openbarsten en mensen verwonden of de installatie beschadigen. De juiste route in Antwerpen en omgeving staat in ons artikel over <a href=\"/lachgas-informatie/lege-lachgasfles-inleveren-antwerpen/\">het inleveren van een lege fles</a>."],
            ["Gelden in de randgemeenten dezelfde regels als in de stad?",
             "Het federale besluit van 2024 geldt in het hele land en dus even goed in Mortsel, Schoten of Beveren als in Antwerpen zelf. De lokale aanpak van overlast kan wel verschillen, omdat elke gemeente een eigen politiereglement heeft en onder een andere politiezone valt. Raadpleeg daarom de website van uw eigen gemeente voor de bepalingen die daar gelden."],
            ["Hoe gaat Lachgas Antwerpen zelf om met de wetgeving?",
             "Wij leveren enkel aan meerderjarigen die zich aan de deur kunnen identificeren, wij leveren niet op straat of aan evenementen en wij bevestigen elke bestelling vooraf via WhatsApp. Wij beweren nergens dat recreatief gebruik in België toegelaten is en passen onze manier van werken aan wanneer de regels veranderen. Meer over onze aanpak vindt u op de pagina <a href=\"/werkwijze/\">werkwijze</a>."],
            ["Waar vind ik de officiële tekst van de wet?",
             "Het Koninklijk Besluit van 11 maart 2024 is gepubliceerd in het Belgisch Staatsblad en is via de federale overheidswebsites raadpleegbaar, waar ook toelichting bij de regels te vinden is. Wij vatten de inhoud op deze site samen zoals wij ze begrijpen, maar bij twijfel over uw eigen situatie raadpleegt u best de officiële tekst of een jurist. Een goed startpunt is <a href=\"https://www.belgium.be\">belgium.be</a>."],
        ],
        "related": ["veiligheid", "lachgaswet-belgie-2024", "leeftijdscontrole-18-plus"],
    },
]
