# -*- coding: utf-8 -*-
# Nieuwe plaatsen West-Brabant, deel B (Drimmelen, Langstraat, richting Tilburg, grensstreek, westkant)
AREAS = [
    {
        'slug': 'made', 'name': 'Made', 'kind': 'dorp',
        'title': 'Lachgas Made | Bezorgd via WhatsApp, ook ’s avonds',
        'description': 'Lachgas bestellen in Made? Lachgas Breda bezorgt in Made en Drimmelen, meestal binnen 25 tot 40 minuten. Verzegelde tanks, 18+, betalen bij levering.',
        'h1': 'Lachgas Made',
        'lead': 'Lachgastanks aan de deur in Made en de kernen van Drimmelen, besteld via WhatsApp en meestal binnen 25 tot 40 minuten bij je.',
        'intro': [
            'Made is de grootste kern van de gemeente Drimmelen en ligt ten noorden van Breda, tussen de A59 en de polders richting de Biesbosch. Het dorp heeft een compact centrum rond de Marktstraat en de Nieuwstraat, met daaromheen woonbuurten als Prinsenpolder en de straten richting de Haasdijk en de Brandestraat. Ook in Drimmelen zelf, bij de jachthaven, en in Wagenberg komen we langs. Bestellen gaat via WhatsApp: je stuurt je adres, het gewenste formaat tank en een moment waarop je thuis bent, en wij bevestigen de prijs en de verwachte aankomsttijd in hetzelfde gesprek.',
            'Vanuit Breda rijden onze bezorgers via de A16 en de A59 naar de afslag bij Made, of binnendoor over Terheijden en Wagenberg wanneer het op de snelweg vastloopt. Het is een rit van ruim een kwartier zonder verkeer, maar de spitsdrukte bij knooppunt Zonzeel en op de weg door Terheijden maakt het soms langer. Daarom rekenen we voor Made met meestal 25 tot 40 minuten. Met de bus kom je vanaf station Breda ook in Made, maar voor een tank van enkele kilo’s is dat geen handige optie; wij komen gewoon tot aan je voordeur.',
            'Een avond met vrienden na een dag varen in de Biesbosch, een tuinfeest in Prinsenpolder of een verjaardag in een van de oudere straten rond de kerk: in Made bezorgen we op elk woonadres. In ons <a href="/assortiment/">assortiment</a> vind je de Lachgastank 2KG en 4KG voor een kleine groep en de 10KG voor een grotere gelegenheid, aangevuld met crackers en slagroompatronen. Je betaalt bij levering contant of via Tikkie, en we leveren alleen aan personen van 18 jaar en ouder; houd je legitimatie bij de hand. Lees voor je bestelt onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">verantwoord omgaan met lachgas</a>.',
        ],
        'wijken': 'Marktstraat, Nieuwstraat, Adelstraat, Haasdijk, Brandestraat, Prinsenpolder, Drimmelen, Wagenberg',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie ook in Drimmelen aan de haven?', 'Ja, Drimmelen hoort bij ons gebied rond Made. We leveren op een woonadres of op een vooraf afgesproken adres bij de haven, niet op een boot of op het water. Geef in je bericht duidelijk aan waar je staat, dan zoekt onze bezorger niet onnodig.'],
            ['Hoe lang moet ik in Made wachten op mijn bestelling?', 'Reken op meestal 25 tot 40 minuten vanaf het moment dat we je bestelling via WhatsApp hebben bevestigd. Op vrijdag- en zaterdagavond kan het aan de bovenkant van die marge zitten; je krijgt bij het bevestigen altijd een realistische inschatting.'],
            ['Komen jullie ook ’s avonds laat naar Made?', 'Ja, ook in de late uren rijden we naar Made. Stuur je bericht met adres en formaat, dan hoor je direct of we onderweg kunnen; hoe dat ’s nachts werkt, staat op onze pagina over <a href="/lachgas-nachtbezorging/">nachtbezorging</a>.'],
        ],
        'nearby': ['terheijden', 'raamsdonksveer', 'oosterhout'],
        'lat': 51.676, 'lon': 4.793,
    },
    {
        'slug': 'terheijden', 'name': 'Terheijden', 'kind': 'dorp',
        'title': 'Lachgas Terheijden | Snel bezorgd via WhatsApp',
        'description': 'Lachgas bestellen in Terheijden? Vanuit Breda zijn we er meestal binnen 20 tot 30 minuten. Verzegelde lachgastanks, uitsluitend 18+, betalen bij levering.',
        'h1': 'Lachgas Terheijden',
        'lead': 'Direct over de Mark vanuit Breda: in Terheijden staat je lachgastank meestal binnen 20 tot 30 minuten voor de deur, besteld via WhatsApp.',
        'intro': [
            'Terheijden ligt pal ten noorden van Breda, aan de overkant van de Mark en het Markkanaal, en is daarmee het dichtstbijzijnde dorp van de gemeente Drimmelen. Het oude centrum rond de Hoofdstraat, de Markstraat en de Raadhuisstraat gaat over in rustige woonstraten richting de Zeggelaan en de Bredaseweg, en aan de rand ligt de Kleine Schans uit de tijd van de Tachtigjarige Oorlog. We bezorgen in het hele dorp en in het buurdorp Wagenberg. Je bestelt met een WhatsApp-bericht waarin je adres en het formaat tank staan; wij antwoorden met de prijs en een tijdsindicatie.',
            'De Terheijdenseweg loopt vanaf de noordkant van Breda rechtstreeks het dorp in en gaat daar over in de Bredaseweg. Onze bezorgers hoeven dus niet via de snelweg: vanaf de Belcrum of de Hoge Vucht is het een paar kilometer rechtdoor. Dat verklaart waarom Terheijden dezelfde levertijd heeft als de Bredase wijken, meestal 20 tot 30 minuten. Alleen op drukke avonden kan het iets langer duren. De bus tussen Breda en Terheijden rijdt overdag regelmatig, maar een tank laat je natuurlijk liever gewoon thuisbezorgen.',
            'Of het nu een borrel aan de Markstraat is, een tuinfeest in een nieuwbouwwoning of een avond met vrienden na een wandeling langs de Mark: je kiest het formaat dat bij het gezelschap past. Voor een klein groepje volstaat de <a href="/product/lachgas-tank-2kg/">Lachgastank 2KG</a>; de 4KG en 10KG zijn er voor grotere gelegenheden, en crackers en slagroompatronen leveren we erbij. Afrekenen doe je bij de deur, contant of via Tikkie. We leveren uitsluitend aan volwassenen van 18 jaar of ouder en vragen daarom om een legitimatie. Meer over verantwoord gebruik lees je in onze <a href="/lachgas-informatie/veilig-gebruik/">informatie over veilig gebruik</a>.',
        ],
        'wijken': 'Hoofdstraat, Markstraat, Raadhuisstraat, Molenstraat, Bredaseweg, Zeggelaan, Kleine Schans, Wagenberg',
        'levertijd': 'meestal binnen 20 tot 30 minuten',
        'faq': [
            ['Waarom is de levertijd in Terheijden even kort als in Breda?', 'Omdat het dorp direct aan de noordkant van de stad ligt en de Terheijdenseweg zonder omwegen het centrum van Terheijden in loopt. Daarom hanteren we hier meestal 20 tot 30 minuten.'],
            ['Leveren jullie ook in Wagenberg?', 'Ja, Wagenberg nemen we mee in onze ritten naar Terheijden. Houd er rekening mee dat de rit iets langer is; we geven bij het bevestigen een passende indicatie.'],
            ['Kan ik voor een feest in Terheijden vooraf een tijd afspreken?', 'Dat kan. Stuur ons via WhatsApp het adres, het formaat en het gewenste tijdvak, dan plannen we de levering in. Op onze pagina over <a href="/lachgas-feest-evenement/">lachgas voor feesten</a> lees je waar je verder op moet letten.'],
        ],
        'nearby': ['made', 'prinsenbeek', 'teteringen'],
        'lat': 51.643, 'lon': 4.754,
    },
    {
        'slug': 'waalwijk', 'name': 'Waalwijk', 'kind': 'stad',
        'title': 'Lachgas Waalwijk | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Waalwijk? Lachgas Breda rijdt via de A59 naar alle wijken van Waalwijk, meestal binnen 35 tot 50 minuten.',
        'h1': 'Lachgas Waalwijk',
        'lead': 'Van Baardwijk tot Landgoed Driessen: in Waalwijk bezorgen we lachgastanks meestal binnen 35 tot 50 minuten na je bestelling via WhatsApp.',
        'intro': [
            'Waalwijk is de grootste plaats van de Langstraat en ligt aan de A59 tussen Waspik en Drunen, met de Loonse en Drunense Duinen aan de zuidkant. De stad bestaat uit duidelijk herkenbare wijken: het centrum rond de Grotestraat, de oudere buurten Baardwijk en Besoyen, Zanddonk en Bloemenoord richting de duinen, en het nieuwere Landgoed Driessen aan de westkant. Ook in Sprang-Capelle en Waspik, die bij de gemeente horen, komen we aan huis. Een WhatsApp-bericht met je adres en het gewenste formaat is genoeg om te bestellen; de prijs bevestigen we vooraf.',
            'Vanuit Breda is Waalwijk een snelwegrit: de A27 naar het noorden tot knooppunt Hooipolder en daarna de A59 richting ’s-Hertogenbosch, met afslagen voor Waalwijk-West, Centrum en Oost. Zonder oponthoud is dat een half uur, maar de A27 en het knooppunt zijn gevoelig voor files, vooral aan het einde van de middag. Vandaar dat we voor Waalwijk meestal 35 tot 50 minuten aanhouden. Een treinstation heeft Waalwijk niet meer; het oude spoor is nu het Halve Zolenpad. Wie geen auto heeft, laat de tank dus het liefst bezorgen in plaats van zelf te reizen.',
            'Een verjaardag in Besoyen, een avond met collega’s na een lange dag op het bedrijventerrein aan de Haven of een huisfeest in Landgoed Driessen: we komen op ieder woonadres. Welk formaat past, hangt af van het gezelschap; onze keuzehulp <a href="/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/">2KG, 4KG of 10KG</a> helpt je kiezen en in het assortiment staan ook crackers en slagroompatronen. Betalen gebeurt bij levering, contant of via Tikkie. We leveren alleen aan 18-plussers en controleren dat aan de deur. Lees ook onze <a href="/lachgas-informatie/veilig-gebruik/">tips voor veilig gebruik</a> voordat je bestelt.',
        ],
        'wijken': 'Centrum, Grotestraat, Baardwijk, Besoyen, Zanddonk, Bloemenoord, De Hoef, Landgoed Driessen, Sprang-Capelle, Waspik',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Bezorgen jullie ook in Sprang-Capelle en Waspik?', 'Ja, beide kernen van de gemeente Waalwijk vallen binnen ons gebied. Omdat Waspik aan de westkant ligt, dichter bij de A27, is de rit daarheen iets korter; je krijgt per bestelling een eigen tijdsindicatie.'],
            ['Wat als het vastloopt op de A27 bij Hooipolder?', 'Dan kiezen onze bezorgers waar mogelijk een alternatieve route, bijvoorbeeld via Oosterhout en Raamsdonksveer binnendoor. Loopt de levertijd daardoor uit, dan laten we dat via WhatsApp weten zodat je niet voor niets zit te wachten.'],
            ['Kan ik ook midden in de nacht in Waalwijk bestellen?', 'We rijden ook ’s nachts, al kan de wachttijd in de late uren afwijken van de dagindicatie. Hoe nachtlevering precies werkt staat op onze pagina over <a href="/lachgas-nachtbezorging/">nachtbezorging</a>.'],
        ],
        'nearby': ['kaatsheuvel', 'dongen', 'tilburg'],
        'lat': 51.687, 'lon': 5.072,
    },
    {
        'slug': 'kaatsheuvel', 'name': 'Kaatsheuvel', 'kind': 'dorp',
        'title': 'Lachgas Kaatsheuvel | Bestellen via WhatsApp',
        'description': 'Lachgas bestellen in Kaatsheuvel? Wij bezorgen lachgastanks via de A59 en N261 in Kaatsheuvel, Loon op Zand en De Moer, meestal binnen 35 tot 50 minuten.',
        'h1': 'Lachgas Kaatsheuvel',
        'lead': 'Lachgastanks bezorgd in Kaatsheuvel en Loon op Zand, besteld via WhatsApp en meestal binnen 35 tot 50 minuten bij je thuis.',
        'intro': [
            'Kaatsheuvel is het grootste dorp van de gemeente Loon op Zand en ligt aan de N261 tussen Waalwijk en Tilburg, met de Loonse en Drunense Duinen direct ten oosten ervan. Voor veel mensen is het dorp vooral bekend door de Efteling aan de rand, maar wij bezorgen natuurlijk op woonadressen: in het centrum rond de Hoofdstraat, de Gasthuisstraat en de Peperstraat, in de woonbuurten tussen het centrum en de Europalaan, en in het buitengebied richting Loon op Zand en De Moer. Bestellen doe je via WhatsApp met je adres en het gewenste formaat; wij noemen vooraf de prijs en de verwachte aankomsttijd.',
            'Onze bezorgers rijden vanuit Breda over de A27 en de A59 naar Waalwijk en nemen daar de N261 een paar kilometer naar het zuiden; via Tilburg over de A58 en dan de N261 naar het noorden is het alternatief wanneer de A27 vol staat. Beide routes kosten ruim een half uur, en rond de spits of op drukke dagen bij het park loopt het verkeer op de N261 merkbaar vol. Daarom geven we voor Kaatsheuvel meestal 35 tot 50 minuten aan. Een station is er niet; de bus naar Tilburg en Waalwijk stopt wel in het dorp.',
            'Een feestje in een rijtjeshuis in het centrum, een weekend met vrienden in een huurwoning aan de rand van het dorp of een verjaardag in Loon op Zand: geef bij je bestelling altijd het exacte adres door, want in het buitengebied liggen de huisnummers ver uit elkaar. Uit het <a href="/assortiment/">assortiment</a> kies je een Lachgastank 2KG, 4KG of 10KG, eventueel met crackers en slagroompatronen. Je rekent bij de deur af, contant of via Tikkie, en we leveren alleen aan personen van 18 jaar en ouder. Hoe je verantwoord met lachgas omgaat, lees je in ons artikel over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Hoofdstraat, Gasthuisstraat, Peperstraat, Marktstraat, Europalaan, Het Klavier, Loon op Zand, De Moer',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Bezorgen jullie bij de Efteling of op een vakantiepark?', 'Nee, we leveren niet op het terrein van het park of op een vakantiepark; daar gelden de regels van de beheerder. We bezorgen op een woonadres in Kaatsheuvel of op een adres dat je vooraf met ons afspreekt.'],
            ['Hoe lang duurt het voordat jullie in Kaatsheuvel zijn?', 'Houd rekening met meestal 35 tot 50 minuten na onze bevestiging. Op dagen dat het druk is op de N261, bijvoorbeeld bij mooi weer of in de vakantie, zitten we eerder aan de bovenkant van die marge.'],
            ['Komen jullie ook in Loon op Zand en De Moer?', 'Ja, de andere kernen van de gemeente horen bij ons bezorggebied rond Kaatsheuvel. Vermeld bij een adres in het buitengebied een herkenningspunt, dan vindt de bezorger je sneller.'],
        ],
        'nearby': ['waalwijk', 'dongen', 'tilburg'],
        'lat': 51.657, 'lon': 5.040,
    },
    {
        'slug': 'goirle', 'name': 'Goirle', 'kind': 'dorp',
        'title': 'Lachgas Goirle | Bezorgd via WhatsApp, ook ’s nachts',
        'description': 'Lachgas bestellen in Goirle? Wij bezorgen via de A58 in Goirle en Riel, meestal binnen 35 tot 50 minuten. Verzegelde tanks, 18+, betalen bij levering.',
        'h1': 'Lachgas Goirle',
        'lead': 'Ten zuiden van Tilburg, vlak bij de Belgische grens: in Goirle en Riel bezorgen we lachgastanks meestal binnen 35 tot 50 minuten na je WhatsApp.',
        'intro': [
            'Goirle ligt direct ten zuiden van Tilburg, aan de A58 en op een paar kilometer van de Belgische grens bij Poppel. Het dorp heeft een levendig centrum rond de Tilburgseweg en de Kalverstraat, met daaromheen de wijken Abcoven, Grobbendonck en De Hellen en aan de noordkant de nieuwere buurt Boschkens. Ten zuiden begint het buitengebied met de Regte Heide en het landgoed Gorp en Roovert. Riel, de tweede kern van de gemeente, bedienen we vanuit dezelfde rit. Bestellen gaat via WhatsApp: adres, formaat en eventueel een gewenst tijdstip, en wij bevestigen de prijs.',
            'Vanuit Breda volgen onze bezorgers de A58 richting Tilburg en nemen ze de afslag voor Goirle, waarna de Tilburgseweg hen rechtstreeks het dorp in brengt. Binnendoor via Gilze, Alphen en Riel is een rustig alternatief als de snelweg rond Tilburg vaststaat. In beide gevallen is het een rit van ongeveer een half uur, en omdat de A58 bij Tilburg regelmatig vertraging kent, houden we voor Goirle meestal 35 tot 50 minuten aan. Een eigen station heeft het dorp niet; vanaf Tilburg rijdt een stadsbus door Goirle.',
            'Een verjaardag in Abcoven, een avond met vrienden in Boschkens of een feestje in Riel: we bezorgen op elk woonadres in de gemeente. Twijfel je tussen de formaten, lees dan <a href="/lachgas-informatie/welke-lachgastank-heb-ik-nodig/">welke lachgastank je nodig hebt</a>; we leveren 2KG, 4KG en 10KG, plus crackers en slagroompatronen. Betalen doe je contant of via Tikkie bij de deur. We leveren uitsluitend aan 18-plussers en vragen om een geldig legitimatiebewijs. Over de regels aan de grens lees je meer op onze pagina over de <a href="/lachgas-grensregio-belgie/">grensregio met België</a>.',
        ],
        'wijken': 'Centrum, Tilburgseweg, Kalverstraat, Abcoven, Grobbendonck, De Hellen, Boschkens, Riel, Regte Heide',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Leveren jullie ook over de grens in Poppel?', 'Nee, we bezorgen alleen op Nederlands grondgebied. Een lachgastank meenemen naar België valt onder de Belgische regels; op onze pagina over de <a href="/lachgas-grensregio-belgie/">grensregio</a> leggen we uit wat wel en niet kan.'],
            ['Ik woon in Boschkens, telt dat als Goirle of als Tilburg?', 'Boschkens hoort bij Goirle, maar ligt zo dicht tegen Tilburg aan dat de levertijd in de praktijk tussen beide in zit. Noem bij je bestelling gewoon je straat en huisnummer, dan geven we een indicatie die bij dat adres past.'],
            ['Kunnen jullie ook laat op de avond naar Goirle komen?', 'Ja, ook in de avond en nacht rijden we naar Goirle. Reken in de late uren op dezelfde indicatie van meestal 35 tot 50 minuten, met mogelijk wat afwijking als het druk is.'],
        ],
        'nearby': ['tilburg', 'gilze', 'baarle-nassau'],
        'lat': 51.520, 'lon': 5.067,
    },
    {
        'slug': 'oisterwijk', 'name': 'Oisterwijk', 'kind': 'dorp',
        'title': 'Lachgas Oisterwijk | Via WhatsApp aan de deur bezorgd',
        'description': 'Lachgas bestellen in Oisterwijk? Wij bezorgen in Oisterwijk, Moergestel en Haaren, meestal binnen 35 tot 50 minuten na je WhatsApp.',
        'h1': 'Lachgas Oisterwijk',
        'lead': 'Lachgastanks bezorgd in Oisterwijk, Moergestel en Haaren: bestellen via WhatsApp, meestal binnen 35 tot 50 minuten aan de deur.',
        'intro': [
            'Oisterwijk ligt ten oosten van Tilburg, tussen de A58 en de N65, en staat bekend om De Lind met zijn lindebomen en om de vennen en bossen van de Oisterwijkse Vennen en de Kampina. Het dorp zelf bestaat uit het centrum rond De Lind en de Dorpsstraat, de woonwijken Pannenschuur en Westend, de Bunders en De Waterhoef, en de buurt Kerkhoven. Sinds de gemeente in 2021 is uitgebreid, horen ook Moergestel, Heukelom en Haaren erbij; we bezorgen in al die kernen. Een WhatsApp-bericht met adres en gewenst formaat volstaat; de prijs en verwachte aankomsttijd krijg je direct terug.',
            'Onze bezorgers rijden vanuit Breda over de A58, langs Tilburg, tot de afslag Oisterwijk en Moergestel, en daarna via de Moergestelseweg het dorp in. Zonder files is dat ongeveer veertig minuten, waarbij vooral het stuk rond Tilburg en knooppunt De Baars gevoelig is voor vertraging. Oisterwijk is de verste plaats in deze richting die we bedienen, en daarom rekenen we met meestal 35 tot 50 minuten. Het dorp heeft wel een station aan de lijn Tilburg–Eindhoven, maar een tank vervoer je liever niet in de trein; wij brengen hem gewoon thuis.',
            'Een feest in een van de ruime huizen rond de Vennen, een verjaardag in Pannenschuur of een avond met vrienden in Moergestel: we komen op elk woonadres in de gemeente. Voor een klein gezelschap is de Lachgastank 2KG of 4KG meestal passend; voor een grotere groep is er de <a href="/product/lachgas-tank-10kg/">Lachgastank 10KG</a>, en crackers en slagroompatronen leveren we mee. Je betaalt bij aflevering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees ook onze informatie over <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">het bewaren en vervoeren van een tank</a>.',
        ],
        'wijken': 'Centrum, De Lind, Dorpsstraat, Pannenschuur, Westend, Bunders, De Waterhoef, Kerkhoven, Moergestel, Haaren',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Bezorgen jullie ook in Moergestel, Heukelom en Haaren?', 'Ja, alle kernen van de gemeente Oisterwijk vallen binnen ons gebied. Haaren ligt het verst van de A58, dus daar kan de rit iets langer duren dan in het dorp zelf.'],
            ['Kan ik bij een vakantiehuisje bij de Oisterwijkse Vennen laten bezorgen?', 'Alleen als het om een adres gaat waar je zelf verblijft en waar we gewoon aan de deur kunnen leveren. Op campings en recreatieparken gelden huisregels van de beheerder; check die vooraf en geef ons een duidelijk adres of herkenningspunt.'],
            ['Hoe nauwkeurig is de levertijd van 35 tot 50 minuten?', 'Het is een indicatie op basis van een normale rit over de A58. Bij files rond Tilburg laten we je via WhatsApp weten als het later wordt, zodat je weet waar je aan toe bent.'],
        ],
        'nearby': ['tilburg', 'goirle', 'waalwijk'],
        'lat': 51.579, 'lon': 5.190,
    },
    {
        'slug': 'baarle-nassau', 'name': 'Baarle-Nassau', 'kind': 'dorp',
        'title': 'Lachgas Baarle-Nassau | Bezorgd via WhatsApp',
        'description': 'Lachgas bestellen in Baarle-Nassau? Lachgas Breda levert op Nederlandse adressen in Baarle-Nassau en Ulicoten, meestal binnen 35 tot 50 minuten.',
        'h1': 'Lachgas Baarle-Nassau',
        'lead': 'Lachgastanks bezorgd in Baarle-Nassau, Ulicoten en Castelré, op adressen op Nederlands grondgebied, meestal binnen 35 tot 50 minuten na je WhatsApp.',
        'intro': [
            'Baarle-Nassau is het grensdorp ten zuiden van Breda waar de Belgische gemeente Baarle-Hertog in de vorm van enclaves doorheen loopt. De grens volgt geen rechte lijn maar slingert door straten als de Singel en de Nieuwstraat en soms dwars door panden; bij welke gemeente een huis hoort, wordt bepaald door de plek van de voordeur. Wij leveren uitsluitend op adressen op Nederlands grondgebied, dus in het Nederlandse deel van het dorp, in Ulicoten en in Castelré. Stuur bij je bestelling via WhatsApp je volledige adres door, dan controleren wij of het onder Baarle-Nassau valt en bevestigen we de prijs.',
            'De rit vanuit Breda gaat over de N639: via Ulvenhout en Chaam loopt die provinciale weg rechtstreeks naar Baarle-Nassau. Het is een route zonder snelweg, met landbouwverkeer en een lagere maximumsnelheid dan op de A58 richting Tilburg; daarom duurt het hier langer dan de afstand doet vermoeden en houden we meestal 35 tot 50 minuten aan. Een treinverbinding is er niet meer, het oude spoor naar Turnhout is nu het fietspad Bels Lijntje. Wel rijdt een bus tussen Breda en Baarle, maar voor een tank is bezorgen de praktische keuze.',
            'Een verjaardag in een woning aan de Chaamseweg, een avond met vrienden in Ulicoten of een feestje in het Nederlandse deel van het centrum: zolang de voordeur in Nederland staat, komen we langs. Kies uit de Lachgastank 2KG, 4KG of 10KG in ons <a href="/assortiment/">assortiment</a>; crackers en slagroompatronen leveren we mee. Afrekenen gebeurt bij levering, contant of via Tikkie, en we leveren alleen aan 18-plussers na het tonen van een legitimatie. Wat je over de grens wel en niet mag, lees je op onze pagina over de <a href="/lachgas-grensregio-belgie/">grensregio met België</a>.',
        ],
        'wijken': 'Singel, Nieuwstraat, Stationsstraat, Chaamseweg, Alphenseweg, Sint Annaplein, Ulicoten, Castelré, Bels Lijntje',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Mijn adres ligt in Baarle-Hertog, kunnen jullie toch leveren?', 'Nee. Adressen in Baarle-Hertog liggen op Belgisch grondgebied en daar leveren wij niet, ook niet als het huis midden in het dorp staat. Voor België verwijzen we naar <a href="https://lachgasantwerpen.be">lachgasantwerpen.be</a>.'],
            ['Hoe weet ik of mijn huis bij Baarle-Nassau of Baarle-Hertog hoort?', 'Kijk naar het huisnummerbordje: in Baarle dragen de nummers een Nederlands of Belgisch vlaggetje dat aangeeft onder welke gemeente de voordeur valt. Twijfel je, stuur dan je postcode mee, dan kijken wij het na.'],
            ['Bezorgen jullie ook in Ulicoten en Castelré?', 'Ja, beide kernen horen bij de gemeente Baarle-Nassau en liggen op Nederlands grondgebied. Castelré ligt afgelegen tegen de grens, dus de rit daarheen kan aan de bovenkant van de indicatie zitten.'],
        ],
        'nearby': ['chaam', 'gilze', 'goirle'],
        'lat': 51.447, 'lon': 4.932,
    },
    {
        'slug': 'chaam', 'name': 'Chaam', 'kind': 'dorp',
        'title': 'Lachgas Chaam | Bezorgd via WhatsApp vanuit Breda',
        'description': 'Lachgas bestellen in Chaam? Vanuit Breda via Ulvenhout zijn we in Chaam, Galder en Strijbeek meestal binnen 25 tot 40 minuten.',
        'h1': 'Lachgas Chaam',
        'lead': 'Lachgastanks aan de deur in Chaam en de omliggende kernen van Alphen-Chaam, besteld via WhatsApp en meestal binnen 25 tot 40 minuten geleverd.',
        'intro': [
            'Chaam is een bosrijk dorp ten zuidoosten van Breda, halverwege Ulvenhout en Baarle-Nassau in de gemeente Alphen-Chaam. Het dorp is in de regio vooral bekend van de Chaamse Bossen en de jaarlijkse wielerronde Acht van Chaam. We bezorgen in het hele dorp, van de Dorpsstraat en de Bredaseweg tot de woonstraten richting de Gilzeweg en de Baarleseweg, en ook in de kleinere kernen Galder en Strijbeek en bij de vakantiehuizen rond De Flaasbloem, mits het om een gewoon afleveradres gaat. Bestellen doe je door via WhatsApp je adres en het gewenste formaat te sturen; wij reageren met de prijs en een tijdsindicatie.',
            'Vanuit Breda rijden onze bezorgers via het Ginneken en Ulvenhout de N639 op, die rechtstreeks door Chaam loopt. Het is geen snelwegrit, maar wel een overzichtelijke provinciale weg, zodat we er doorgaans in een kleine twintig minuten zijn. Omdat Chaam net buiten de directe ring rond Breda ligt en het laatste stuk door het buitengebied gaat, geven we meestal 25 tot 40 minuten op. Het openbaar vervoer beperkt zich tot een buslijn tussen Breda en Baarle die door het dorp rijdt; voor een tank is thuislevering eenvoudiger.',
            'Een tuinfeest aan de rand van de bossen, een verjaardag in een nieuwbouwwoning of een avond met vrienden die in Galder of Strijbeek wonen: we komen overal in de gemeente aan de deur. In ons <a href="/assortiment/">assortiment</a> kies je een Lachgastank 2KG of 4KG voor een klein gezelschap of een 10KG voor een grotere groep, met crackers en slagroompatronen erbij. Betalen kan contant of via Tikkie bij aflevering, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees voor je bestelt ook onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> van lachgas.',
        ],
        'wijken': 'Dorpsstraat, Bredaseweg, Gilzeweg, Baarleseweg, Chaamse Bossen, De Flaasbloem, Galder, Strijbeek',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Leveren jullie ook tijdens het weekend van de Acht van Chaam?', 'Ja, maar houd er rekening mee dat delen van het dorp dan zijn afgesloten en de levertijd kan oplopen. Bestel bij voorkeur ruim vooraf en geef aan via welke kant je adres bereikbaar is.'],
            ['Komen jullie ook naar Galder en Strijbeek?', 'Ja, beide kernen van Alphen-Chaam bedienen we vanuit dezelfde route. Strijbeek ligt vlak tegen de Belgische grens; we leveren daar alleen op adressen aan de Nederlandse kant.'],
            ['Kan ik in Chaam ook een kleine tank bestellen voor een paar personen?', 'Zeker, voor een klein gezelschap is de <a href="/product/lachgas-tank-2kg/">Lachgastank 2KG</a> het meest gangbare formaat. Twijfel je, dan denken we via WhatsApp met je mee over wat past bij de gelegenheid.'],
        ],
        'nearby': ['ulvenhout', 'baarle-nassau', 'gilze'],
        'lat': 51.506, 'lon': 4.861,
    },
    {
        'slug': 'dorst', 'name': 'Dorst', 'kind': 'dorp',
        'title': 'Lachgas Dorst | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Dorst? Het dorp ligt aan de N282 vlak bij Breda, dus we zijn er meestal binnen 20 tot 30 minuten. Verzegelde tanks, 18+.',
        'h1': 'Lachgas Dorst',
        'lead': 'Dorst ligt aan de oostrand van Breda, dus je lachgastank is er meestal binnen 20 tot 30 minuten na je bestelling via WhatsApp.',
        'intro': [
            'Dorst is een kerkdorp van de gemeente Oosterhout, ingeklemd tussen Breda, Oosterhout en Rijen, aan de N282 en de spoorlijn Breda–Tilburg. Het dorp is klein en overzichtelijk: woonstraten als de Baarschotsestraat en de Spoorstraat, de lintbebouwing langs de Rijksweg en het buurtschap Baarschot, met rondom de Boswachterij Dorst, de bossen bij Seters en het recreatiegebied Surae. Omdat de A27 en de Tilburgseweg vlakbij liggen, hoort Dorst bij de snelste bestemmingen buiten Breda. Bestellen gaat via WhatsApp: je adres en het gewenste formaat zijn genoeg; wij bevestigen de prijs en de tijd.',
            'Vanaf de oostkant van Breda rijden onze bezorgers via de Tilburgseweg en de N282 rechtstreeks naar Dorst; vanuit Bavel kan het ook via de Dorstseweg. Het is maar een paar kilometer, en de weg is zelden echt druk, zodat Dorst dezelfde indicatie heeft als de Bredase wijken: meestal 20 tot 30 minuten. De trein tussen Breda en Tilburg rijdt wel langs het dorp maar stopt er niet, en de bus komt niet heel vaak. Juist daarom is thuisbezorging in Dorst praktisch: je hoeft niet naar de stad voor een tank.',
            'Een verjaardag in een woning aan de Spoorstraat, een avond met vrienden na een dag in de Boswachterij of een feestje bij de buren: we komen tot de voordeur. Je kiest een Lachgastank 2KG, 4KG of 10KG uit het <a href="/assortiment/">assortiment</a>, met eventueel crackers en slagroompatronen. Afrekenen doe je bij levering, contant of via Tikkie, en we leveren alleen aan volwassenen van 18 jaar en ouder. Gebruik je de tank niet meteen, lees dan hoe je hem het beste <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">bewaart en vervoert</a>.',
        ],
        'wijken': 'Baarschotsestraat, Spoorstraat, Rijksweg, Baarschot, Seters, Boswachterij Dorst, Surae',
        'levertijd': 'meestal binnen 20 tot 30 minuten',
        'faq': [
            ['Dorst hoort bij Oosterhout, geldt dan de levertijd van Oosterhout?', 'Nee. Dorst ligt veel dichter bij Breda dan bij het centrum van Oosterhout, dus we rekenen hier met meestal 20 tot 30 minuten, net als in de Bredase wijken.'],
            ['Bezorgen jullie ook bij Surae of in de bossen?', 'We leveren op een woonadres of op een vooraf afgesproken adres in het dorp, niet in het recreatiegebied of in de bossen zelf. Spreek je af bij iemand thuis, geef dan dat adres door.'],
            ['Moet ik een account aanmaken om in Dorst te bestellen?', 'Nee, een account is niet nodig. Je stuurt een WhatsApp-bericht met adres en formaat, krijgt de prijs bevestigd en betaalt bij de deur; de drie stappen staan op onze pagina over de <a href="/werkwijze/">werkwijze</a>.'],
        ],
        'nearby': ['bavel', 'rijen', 'oosterhout'],
        'lat': 51.577, 'lon': 4.858,
    },
    {
        'slug': 'gilze', 'name': 'Gilze', 'kind': 'dorp',
        'title': 'Lachgas Gilze | Bestellen via WhatsApp, snel bezorgd',
        'description': 'Lachgas bestellen in Gilze? Wij bezorgen via de A58 in Gilze, Hulten en Molenschot, meestal binnen 25 tot 40 minuten. Verzegeld, 18+, betalen bij levering.',
        'h1': 'Lachgas Gilze',
        'lead': 'Lachgastanks bezorgd in Gilze, Molenschot en Hulten: bestellen via WhatsApp, meestal binnen 25 tot 40 minuten aan de deur.',
        'intro': [
            'Gilze ligt ten zuidoosten van Breda, direct aan de A58 en tegen de vliegbasis Gilze-Rijen aan, en vormt samen met Rijen, Hulten en Molenschot de gemeente Gilze en Rijen. Het dorp heeft een centrum rond het Bisschop de Vetplein en het Steenakkerplein, met woonstraten als de Nieuwstraat, de Raadhuisstraat en de Lange Wagenstraat en aan de zuidkant de Alphenseweg richting het buitengebied. We bezorgen in Gilze zelf en in de kleinere kernen Molenschot en Hulten. Een WhatsApp-bericht met je adres en het gewenste formaat is voldoende; we bevestigen vooraf de prijs en noemen een verwachte aankomsttijd.',
            'Onze bezorgers nemen vanuit Breda de A58 richting Tilburg en verlaten de snelweg bij de afslag Gilze; wie binnendoor rijdt, komt via Bavel en de Gilzeweg het dorp binnen. Beide routes duren ongeveer een kwartier tot twintig minuten, en omdat de A58 op dit stuk doorgaans goed te rijden is, hoort Gilze bij de vlottere bestemmingen in deze richting. We houden daarom meestal 25 tot 40 minuten aan. Let op: het station Gilze-Rijen ligt in Rijen, zo’n vijf kilometer verderop, en niet in Gilze zelf.',
            'Een verjaardag in een woning aan de Lange Wagenstraat, een feestje in Molenschot of een avond met vrienden in een boerderijwoning langs de Alphenseweg: geef bij adressen in het buitengebied even een herkenningspunt door. Kies uit de <a href="/product/lachgas-tank-4kg/">Lachgastank 4KG</a> voor een gemiddeld gezelschap, de 2KG voor een klein groepje of de 10KG voor een grotere groep, met crackers en slagroompatronen erbij. Betalen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar en ouder en controleren je leeftijd aan de deur; lees ook over onze <a href="/leeftijdscontrole-18-plus/">leeftijdscontrole</a>.',
        ],
        'wijken': 'Bisschop de Vetplein, Steenakkerplein, Nieuwstraat, Raadhuisstraat, Lange Wagenstraat, Alphenseweg, Molenschot, Hulten',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Waarom geldt voor Gilze een levertijd van 25 tot 40 minuten?', 'Gilze ligt aan de andere kant van de vliegbasis dan Rijen en is vanuit Breda via de A58 of binnendoor via Bavel te bereiken. Die rit is net wat langer dan naar de dorpen direct rond de stad; daarom hanteren we hier meestal 25 tot 40 minuten.'],
            ['Bezorgen jullie ook in Hulten en Molenschot?', 'Ja, beide kernen bedienen we vanuit de rit naar Gilze. Molenschot ligt tussen Gilze en Rijen en Hulten aan de N282; vermeld je adres volledig, dan kiezen we de handigste route.'],
            ['Hoe geef ik een adres in het buitengebied van Gilze door?', 'Stuur je straat en huisnummer en, als het kan, een herkenningspunt zoals een kruising of een bedrijf in de buurt. In het buitengebied liggen huisnummers soms ver uit elkaar, en met die aanwijzing vindt onze bezorger je zonder zoeken.'],
        ],
        'nearby': ['rijen', 'dorst', 'chaam'],
        'lat': 51.543, 'lon': 4.936,
    },
    {
        'slug': 'wouw', 'name': 'Wouw', 'kind': 'dorp',
        'title': 'Lachgas Wouw | Bezorgd via WhatsApp, ook ’s avonds',
        'description': 'Lachgas bestellen in Wouw? Lachgas Breda rijdt via de A58 naar Wouw, Heerle en Wouwse Plantage, meestal binnen 35 tot 50 minuten.',
        'h1': 'Lachgas Wouw',
        'lead': 'Lachgastanks bezorgd in Wouw en de kernen ten westen van Roosendaal, besteld via WhatsApp en meestal binnen 35 tot 50 minuten geleverd.',
        'intro': [
            'Wouw is een dorp van de gemeente Roosendaal, ten westen van de stad aan de A58 richting Bergen op Zoom. Het historische centrum rond de Markt met de Sint-Lambertuskerk is het hart van het dorp; daaromheen liggen woonstraten als de Bergsestraat, de Roosendaalsestraat en de Kloosterstraat, en via de Plantagebaan kom je in het buitengebied richting Wouwse Plantage. Ook Heerle en Moerstraten, de andere kernen aan deze kant van Roosendaal, nemen we mee. Bestellen gaat via WhatsApp met je adres en het gewenste formaat; wij bevestigen de prijs voordat we vertrekken.',
            'Vanuit Breda rijden onze bezorgers over de A58 via Etten-Leur en langs Roosendaal naar de afslag voor Wouw; het is een rit van ruim dertig kilometer die zonder oponthoud rond de dertig minuten duurt. Rond de spits kan het bij Roosendaal en knooppunt De Stok vertragen, en daarom hanteren we voor Wouw meestal 35 tot 50 minuten. De spoorlijn Roosendaal–Bergen op Zoom loopt langs het dorp maar heeft hier geen station; de dichtstbijzijnde treinen vertrekken vanuit Roosendaal, en vanaf daar rijdt een bus door Wouw.',
            'Een verjaardag aan de Markt, een avond met vrienden in Heerle of een feestje in een nieuwbouwwoning aan de rand van het dorp: we komen op elk woonadres aan de deur. In ons <a href="/assortiment/">assortiment</a> vind je de Lachgastank 2KG, 4KG en 10KG, aangevuld met crackers en slagroompatronen. Betalen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan 18-plussers en controleren dat met een legitimatie. Over lachgas en autorijden lees je meer in ons artikel over <a href="/lachgas-informatie/lachgas-in-het-verkeer/">lachgas in het verkeer</a>.',
        ],
        'wijken': 'Markt, Bergsestraat, Roosendaalsestraat, Kloosterstraat, Plantagebaan, Wouwse Plantage, Heerle, Moerstraten',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Bezorgen jullie ook in Wouwse Plantage, Heerle en Moerstraten?', 'Ja, de dorpen rond Wouw horen bij ons gebied aan de westkant van Roosendaal. Wouwse Plantage ligt een stuk zuidelijker in het bosgebied, dus daar kan de rit wat langer duren dan in Wouw zelf.'],
            ['Wat is de verwachte levertijd in Wouw?', 'Reken op meestal 35 tot 50 minuten vanaf onze bevestiging via WhatsApp. Staat het vast op de A58 bij Roosendaal, dan hoor je dat van ons, zodat je niet in het ongewisse zit.'],
            ['Is Wouw voor jullie niet erg ver van Breda?', 'Het is een van onze verdere bestemmingen aan de westkant, maar de A58 maakt de rit overzichtelijk. We bezorgen hier gewoon aan huis; alleen de indicatie is wat ruimer dan in de dorpen direct rond Breda.'],
        ],
        'nearby': ['roosendaal', 'bergen-op-zoom', 'halsteren'],
        'lat': 51.522, 'lon': 4.388,
    },
    {
        'slug': 'willemstad', 'name': 'Willemstad', 'kind': 'dorp',
        'title': 'Lachgas Willemstad | Bezorgd via WhatsApp vanuit Breda',
        'description': 'Lachgas bestellen in Willemstad? Wij bezorgen in de vesting en in Helwijk, meestal binnen 35 tot 50 minuten na je WhatsApp.',
        'h1': 'Lachgas Willemstad',
        'lead': 'Lachgastanks bezorgd in de vestingstad Willemstad en in Helwijk, besteld via WhatsApp en meestal binnen 35 tot 50 minuten aan de deur.',
        'intro': [
            'Willemstad is de vestingstad van de gemeente Moerdijk, gelegen aan het Hollands Diep in het uiterste noordwesten van Brabant. Binnen de zevenpuntige vestingwallen liggen de Voorstraat, de Landpoortstraat, de Hofstraat en de kades rond de jachthaven, met het Mauritshuis en de Koepelkerk als bekende gebouwen. Buiten de wallen is het dorp uitgebreid met de woonbuurt Helwijk, en richting Fijnaart ligt Heijningen. We bezorgen zowel binnen als buiten de vesting, overal waar een gewoon woonadres is. Bestellen doe je via WhatsApp met je adres en het gewenste formaat; wij bevestigen vooraf de prijs.',
            'De rit vanuit Breda gaat over de A16 naar het noorden, bij knooppunt Klaverpolder de A17 op en vervolgens bij Noordhoek het westelijke deel van de A59 richting knooppunt Sabina, waar de afslag voor Willemstad en Helwijk ligt. Het is een afstand van ruim veertig kilometer, grotendeels snelweg, die zonder files iets meer dan een half uur kost. Door die afstand en de kans op vertraging rond Moerdijk hanteren we meestal 35 tot 50 minuten. Openbaar vervoer naar Willemstad is beperkt tot een buslijn; een tank laat je dus het liefst thuisbezorgen.',
            'Een avond met vrienden in een monumentaal pand aan de Voorstraat, een verjaardag in Helwijk of een feestje na een dag aan het water: geef binnen de vesting duidelijk aan waar we kunnen stoppen, want de straten binnen de wallen zijn smal. Uit het <a href="/assortiment/">assortiment</a> kies je een Lachgastank 2KG, 4KG of 10KG, met crackers en slagroompatronen als je wilt. Betalen gebeurt bij levering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Wat je in Nederland wel en niet mag met lachgas, lees je in ons artikel <a href="/lachgas-informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a>.',
        ],
        'wijken': 'Voorstraat, Landpoortstraat, Hofstraat, Benedenkade, Bovenkade, Mauritshuis, de jachthaven, Helwijk',
        'levertijd': 'meestal binnen 35 tot 50 minuten',
        'faq': [
            ['Bezorgen jullie ook op een boot in de jachthaven van Willemstad?', 'Nee, we leveren op een woonadres of op een vooraf afgesproken plek aan de wal, niet aan boord. Verblijf je op een boot, spreek dan een adres bij de haven af en zorg dat je daar zelf aanwezig bent.'],
            ['Hoe snel zijn jullie in Willemstad vanuit Breda?', 'Meestal binnen 35 tot 50 minuten na onze bevestiging; het is grotendeels snelweg via de A16, A17 en A59. Bij werkzaamheden of files rond Moerdijk melden we een eventuele vertraging via WhatsApp.'],
            ['Komen jullie ook in Helwijk en Heijningen?', 'Ja, Helwijk hoort bij Willemstad en Heijningen ligt op de route richting Fijnaart. Beide nemen we mee in onze ritten naar de noordwesthoek van Brabant.'],
        ],
        'nearby': ['fijnaart', 'klundert', 'dinteloord'],
        'lat': 51.690, 'lon': 4.437,
    },
]
