# -*- coding: utf-8 -*-
# West-Brabant regio A: twaalf nieuwe plaatsen voor lachgasbreda.nl (Bergen op Zoom, Halsteren, Oudenbosch, Hoeven,
# Rijsbergen, Sint Willebrord, Klundert, Fijnaart, Steenbergen, Dinteloord, Hoogerheide, Raamsdonksveer).
AREAS = [
    {
        "slug": "bergen-op-zoom", "name": "Bergen op Zoom", "kind": "stad",
        "title": "Lachgas Bergen op Zoom | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Bergen op Zoom? Lachgas Breda bezorgt verzegelde lachgastanks 2KG, 4KG en 10KG aan huis, van de Grote Markt tot de Bergse Plaat. 18+.",
        "h1": "Lachgas bezorgen in Bergen op Zoom",
        "lead": "Bestel via WhatsApp en ontvang je lachgastank verzegeld aan de deur in Bergen op Zoom, meestal binnen 35 tot 50 minuten na bevestiging.",
        "intro": [
            "Bergen op Zoom ligt op de rand van de Brabantse Wal, waar het zand van Brabant abrupt overgaat in de Zeeuwse polders en het water van de Oosterschelde, het Markiezaatsmeer en de Binnenschelde. De oude binnenstad rond de Grote Markt, het Markiezenhof en de Peperbus is compact, maar de woonwijken reiken ver: Fort-Zeekant en Gageldonk aan de westkant, Noordgeest en Meilust richting Halsteren, Warande en Tuinwijk in het oosten en de Bergse Plaat aan het water. Wij bezorgen in al die wijken en ook in Lepelstraat. Bestellen gaat met één WhatsApp-bericht met je adres en het gewenste formaat tank.",
            "De route vanuit Breda loopt over de A58 langs Etten-Leur en Roosendaal, een rit van ruim veertig kilometer die bij vlot verkeer ongeveer een half uur duurt. Rond de spits en bij werkzaamheden op knooppunt De Stok loopt dat uit, en ook de laatste kilometers door de singels van de binnenstad vragen tijd. Daarom rekenen we voor Bergen op Zoom op meestal binnen 35 tot 50 minuten en noemen we vooraf een realistisch tijdvak. Het station aan de lijn Roosendaal–Vlissingen is handig voor wie zelf reist, maar voor een levering aan huis speelt het geen rol: onze bezorger komt tot aan je voordeur.",
            "Een avond met een paar vrienden in een appartement op de Scheldevesting vraagt om iets anders dan een verjaardag in een hoekwoning in Meilust. In ons <a href=\"/assortiment/\">assortiment</a> staan de lachgastank 2KG, 4KG en 10KG naast crackers en slagroompatronen, zodat je het formaat kiest dat bij je gezelschap past. De prijs bevestigen we vooraf in de chat en je betaalt contant of via Tikkie bij levering; de tank komt verzegeld aan. We leveren uitsluitend aan personen van 18 jaar en ouder en vragen bij twijfel om een legitimatiebewijs. Lees voordat je bestelt onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Centrum, Fort-Zeekant, Gageldonk, Noordgeest, Meilust, Warande, Tuinwijk, Bergse Plaat, Borgvliet, Lepelstraat",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook op de Bergse Plaat en in Lepelstraat?", "Ja, de hele gemeente Bergen op Zoom valt binnen ons bezorggebied, inclusief de Bergse Plaat aan de Binnenschelde en het dorp Lepelstraat in het noorden. Voor Halsteren hebben we een <a href=\"/bezorggebied/halsteren/\">eigen pagina</a> met dezelfde levertijd."],
            ["Hoe lang duurt bezorging in Bergen op Zoom vanuit Breda?", "Houd rekening met meestal binnen 35 tot 50 minuten. De rit over de A58 is de grootste factor; zodra je bestelling via WhatsApp is bevestigd, krijg je een tijdvak dat past bij het verkeer van dat moment."],
            ["Kunnen jullie tijdens Vastenavend in het Krabbegat leveren?", "Tijdens de carnavalsdagen is de binnenstad grotendeels afgesloten en bezorgen we alleen op woonadressen die bereikbaar blijven, dus niet op de Grote Markt of in de feesttenten. Plaats je bestelling dan ruim vooraf, want de levertijd kan die dagen oplopen."],
        ],
        "nearby": ["halsteren", "hoogerheide", "roosendaal"],
        "lat": 51.4950, "lon": 4.2917,
    },
    {
        "slug": "halsteren", "name": "Halsteren", "kind": "dorp",
        "title": "Lachgas Halsteren | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Halsteren? Verzegelde lachgastanks 2KG, 4KG en 10KG aan huis bezorgd, van de Dorpsstraat tot Fort de Roovere en Lepelstraat. Voor 18+.",
        "h1": "Lachgas bezorgen in Halsteren",
        "lead": "Lachgas Breda brengt je lachgastank verzegeld naar Halsteren, besteld via WhatsApp en meestal binnen 35 tot 50 minuten bij je thuis.",
        "intro": [
            "Halsteren hoort sinds 1997 bij de gemeente Bergen op Zoom, maar heeft met de Sint-Quirinuskerk en de Dorpsstraat als winkelas nog steeds een eigen dorpskern. Aan de oostkant ligt Fort de Roovere met de verzonken Mozesbrug, een restant van de West-Brabantse Waterlinie, en aan de westkant voert de Tholenseweg over de Eendracht naar Tholen. Wij bezorgen in alle buurten, van de Rode Schouw en Vogelenzang tot De Beek en de straten langs de Steenbergseweg, en nemen het dorp Lepelstraat gewoon mee. Een bestelling plaats je via WhatsApp met je adres, de gewenste tank en het tijdstip waarop je thuis bent.",
            "Onze bezorger rijdt vanuit Breda over de A58 naar Bergen op Zoom en vervolgens over de A4 noordwaarts tot de afrit Halsteren, of bij drukte op de randweg via de Halsterseweg door Bergen op Zoom zelf. Het is een rit van ongeveer 45 kilometer, en inclusief laden en het laatste stuk door het dorp komen we uit op meestal binnen 35 tot 50 minuten. Halsteren heeft geen eigen station; het dichtstbijzijnde is Bergen op Zoom, met een bus naar het dorp. Voor een levering aan huis maakt dat niets uit, want we komen tot aan de voordeur en sturen vooraf een tijdvak zodat je weet wanneer je ons kunt verwachten.",
            "Of het nu gaat om een kleine borrel in een rijtjeshuis aan de Rode Schouw of een tuinfeest in het buitengebied richting Lepelstraat, het formaat van de tank bepaalt het gemak. De <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> is het meest compacte formaat; voor grotere groepen zijn de 4KG en 10KG verstandiger, en in de chat helpen we je kiezen. Je ziet de prijs vooraf in de WhatsApp-bevestiging en betaalt contant of via Tikkie bij levering. Wij leveren alleen aan 18-plussers en controleren zo nodig een legitimatiebewijs. Hoe je een tank thuis bewaart, lees je op de pagina <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">tank bewaren en vervoeren</a>.",
        ],
        "wijken": "Centrum rond de Dorpsstraat, Rode Schouw, Vogelenzang, De Beek, Steenbergseweg, Tholenseweg, Fort de Roovere, Lepelstraat",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Lepelstraat en bij Fort de Roovere?", "Ja, Lepelstraat en de verspreide adressen in het buitengebied rond het fort horen bij onze route voor Halsteren. Zorg bij een adres aan een dijk of polderweg voor een duidelijk huisnummer, dan hoeft de bezorger niet te zoeken."],
            ["Waarom geldt voor Halsteren dezelfde levertijd als voor Bergen op Zoom?", "Het dorp ligt direct ten noorden van Bergen op Zoom en de bezorger rijdt vanaf de A58 of de A4 in een paar minuten door. Het verschil zit vooral in de rit vanuit Breda, en daarom hanteren we voor beide meestal binnen 35 tot 50 minuten."],
            ["Kan ik in Halsteren ook later op de avond bestellen?", "Dat kan; we bezorgen ook ’s avonds en ’s nachts, waarbij de levertijd buiten de drukke uren meestal aan de korte kant van het tijdvak zit. Kijk voor de details op de pagina over <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["bergen-op-zoom", "steenbergen", "wouw"],
        "lat": 51.5283, "lon": 4.2767,
    },
    {
        "slug": "oudenbosch", "name": "Oudenbosch", "kind": "dorp",
        "title": "Lachgas Oudenbosch | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Oudenbosch? Lachgas Breda bezorgt lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Markt bij de Basiliek tot Pagnevaart. 18+.",
        "h1": "Lachgas bezorgen in Oudenbosch",
        "lead": "Via WhatsApp bestel je een lachgastank voor Oudenbosch; we bezorgen verzegeld aan de deur, meestal binnen 25 tot 40 minuten.",
        "intro": [
            "Oudenbosch is de grootste kern van de gemeente Halderberge en al van ver herkenbaar aan de koepel van de Basiliek van de H.H. Agatha en Barbara, gebouwd naar het voorbeeld van de Sint-Pieter in Rome. Rond de Markt en de Sint Bernaertsstraat vind je het Zouavenmuseum, het voormalige internaat Saint Louis en het Arboretum; daaromheen liggen woonwijken als Pagnevaart, Velletri en Albano. Wij bezorgen in al die buurten, langs de Bosschendijk en de Stationsstraat, en ook in Bosschenhoofd. Je stuurt ons via WhatsApp je adres en het formaat tank dat je wilt hebben, en wij bevestigen de prijs en een tijdvak.",
            "Vanuit Breda rijdt de bezorger over de A58 tot Etten-Leur en daarna over de N640 door Hoeven het dorp binnen; bij werkzaamheden op die provinciale weg wijken we uit via Bosschenhoofd. De afstand is ongeveer 25 kilometer en de rit duurt zelden langer dan een half uur, zodat we hier meestal binnen 25 tot 40 minuten kunnen leveren. Oudenbosch heeft een station aan de spoorlijn Roosendaal–Dordrecht en ligt vlak bij de A17, wat het dorp goed bereikbaar maakt, maar wie hier woont of logeert hoeft zelf niets op te halen: we brengen de tank tot aan de voordeur en sturen vooraf een tijdvak.",
            "Een huiskamerfeest in Velletri, een afstudeerborrel in een appartement aan de Fenkelstraat of een tuinfeest aan de rand van Bosschenhoofd: in elke situatie past een ander formaat. Voor kleine gezelschappen is de 2KG genoeg; wie meer gasten verwacht kijkt in ons <a href=\"/assortiment/\">assortiment</a> naar de 4KG of 10KG. Alle tanks worden verzegeld geleverd, de prijs staat vooraf vast in de WhatsApp-bevestiging en je betaalt contant of via Tikkie bij levering. We leveren uitsluitend aan personen van 18 jaar of ouder en kunnen om een legitimatiebewijs vragen. Meer achtergrond vind je op de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Centrum rond de Markt, Fenkelstraat, Sint Bernaertsstraat, Pagnevaart, Velletri, Albano, Bosschendijk, Stationsstraat, Bosschenhoofd",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Bosschenhoofd en Oud Gastel?", "Bosschenhoofd nemen we mee in de route voor Oudenbosch, dus daar geldt dezelfde levertijd. Oud Gastel en Stampersgat liggen verder naar het westen; ook daar bezorgen we, maar reken dan op een iets ruimer tijdvak dat we vooraf in de chat afstemmen."],
            ["Kan ik de tank afhalen bij station Oudenbosch?", "Nee, we werken alleen met levering op een woonadres, zodat we rustig de leeftijd kunnen controleren en de tank verzegeld kunnen overhandigen. Het station of een parkeerplaats is daarvoor geen geschikte plek."],
            ["Hoe snel zijn jullie in Oudenbosch op een zaterdagavond?", "Ook dan houden we meestal binnen 25 tot 40 minuten aan, al kan het rond de spits op de A58 en bij evenementen in Etten-Leur iets langer duren. Je krijgt na je bestelling altijd een concreet tijdvak; hoe dat werkt lees je op de pagina <a href=\"/bezorgtijden-breda/\">bezorgtijden</a>."],
        ],
        "nearby": ["hoeven", "etten-leur", "roosendaal"],
        "lat": 51.5883, "lon": 4.5267,
    },
    {
        "slug": "hoeven", "name": "Hoeven", "kind": "dorp",
        "title": "Lachgas Hoeven | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Hoeven? Verzegelde lachgastanks 2KG, 4KG en 10KG aan huis bezorgd in Hoeven en Bosschenhoofd, van Bovendonk tot het Bosbad. 18+.",
        "h1": "Lachgas bezorgen in Hoeven",
        "lead": "Lachgastanks verzegeld aan huis in Hoeven, besteld via WhatsApp en meestal binnen 25 tot 40 minuten geleverd vanuit Breda.",
        "intro": [
            "Hoeven ligt tussen Etten-Leur en Oudenbosch aan de N640 en hoort bij de gemeente Halderberge. Het dorp is vooral bekend van Bovendonk, het voormalige grootseminarie aan de Hofstraat dat nu als conferentiecentrum dient, en van het Bosbad met het bungalowpark aan de zuidkant. De Sint Janstraat vormt de ruggengraat van het dorp, met daaromheen de woonstraten rond de Halderbergselaan en de Bovenstraat en het buitengebied richting de Hoevense Beemden. Wij bezorgen op elk adres in de kern en in het buitengebied. Een WhatsApp-bericht met je straat, huisnummer en de gewenste tank is voldoende om te bestellen.",
            "Onze bezorger neemt vanuit Breda de A58 tot Etten-Leur en rijdt daarna over de N640 het dorp in; de snelweg zelf loopt een paar kilometer ten zuiden van Hoeven, langs Bosschenhoofd en Breda International Airport. Het is een rit van ruim twintig kilometer die in de praktijk een kwartier tot twintig minuten kost, en inclusief laden en de laatste meters door de wijk komen we uit op meestal binnen 25 tot 40 minuten. Een treinstation heeft Hoeven niet; de bus naar Etten-Leur en Oudenbosch rijdt beperkt. Voor een levering aan de deur speelt dat geen rol, we komen tot op je stoep.",
            "Een weekend met vrienden in een huisje op het Bosbad vraagt om een ander formaat dan een verjaardag in een gezinswoning aan de Halderbergselaan. De <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> is voor veel gezelschappen de middenweg; de 2KG en 10KG staan ook in ons assortiment en we denken in de chat met je mee. Elke tank komt verzegeld aan en de prijs is vooraf bevestigd, zodat je bij de deur alleen nog contant of via Tikkie afrekent. Leveren doen we uitsluitend aan 18-plussers, met een controle van je legitimatie als daar aanleiding voor is. Lees ook onze uitleg over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> voordat je bestelt.",
        ],
        "wijken": "Sint Janstraat, Bovendonk, Hofstraat, Halderbergselaan, Bovenstraat, Oude Antwerpsepostbaan, Bosbad Hoeven, Hoevense Beemden, Bosschenhoofd",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie op het Bosbad in Hoeven?", "Op het bungalowpark bezorgen we aan de huisjes die een eigen adres of nummer hebben, zolang het park dat toestaat; bij de receptie of op de camping zelf leveren we niet. Geef in je bericht het nummer van het huisje door en wees zelf aanwezig om te ontvangen."],
            ["Hoe lang duurt bezorging in Hoeven?", "Vanuit Breda zijn we hier meestal binnen 25 tot 40 minuten, omdat de A58 en de N640 een vlotte verbinding vormen. Tijdens de avondspits bij Etten-Leur kan het aan de lange kant van dat tijdvak zitten."],
            ["Komen jullie ook in Bosschenhoofd?", "Ja, Bosschenhoofd ligt op de route en krijgt dezelfde levertijd als Hoeven. Woon je dichter bij Oudenbosch, kijk dan ook op onze <a href=\"/bezorggebied/oudenbosch/\">pagina voor Oudenbosch</a>."],
        ],
        "nearby": ["oudenbosch", "etten-leur", "sint-willebrord"],
        "lat": 51.5833, "lon": 4.5833,
    },
    {
        "slug": "rijsbergen", "name": "Rijsbergen", "kind": "dorp",
        "title": "Lachgas Rijsbergen | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Rijsbergen? Wij bezorgen lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Sint Bavostraat tot Koekelberg en Tiggelt. 18+.",
        "h1": "Lachgas bezorgen in Rijsbergen",
        "lead": "Een lachgastank voor Rijsbergen bestel je via WhatsApp; we bezorgen verzegeld aan de deur, meestal binnen 25 tot 40 minuten.",
        "intro": [
            "Rijsbergen ligt halverwege Breda en Zundert aan de N263, de oude weg naar Antwerpen, en is na Zundert de grootste kern van de gemeente Zundert. De Sint Bavokerk en de Sint Bavostraat vormen het hart, met daaromheen woonbuurten als Koekelberg en de straten rond de Lagestraat, en aan de randen de buurtschappen Tiggelt en Risten. Ten westen van het dorp ligt natuurgebied de Pannenhoef, ten oosten het Oekelsbos en de A16. Wij bezorgen in de kern en in het buitengebied. Bestellen doe je door via WhatsApp je adres en de gewenste tank te sturen; we bevestigen de prijs voordat we vertrekken.",
            "Vanuit Princenhage rijdt onze bezorger over de Rijsbergseweg rechtstreeks het dorp in, een afstand van een kleine twaalf kilometer die zonder oponthoud een kwartier kost. Loopt het verkeer op de N263 vast, dan is de A16 richting Hazeldonk een alternatief. Omdat Rijsbergen buiten de stad ligt en we rekening houden met laden en het laatste stuk over de dorpsstraten, hanteren we hier meestal binnen 25 tot 40 minuten in plaats van de Bredase stadstijd. Het dorp heeft geen station; de bus tussen Breda en Zundert stopt op de doorgaande weg. Voor een bestelling hoef je dus niets te regelen, wij komen naar jou.",
            "Een verjaardag in een vrijstaand huis aan de Lagestraat of een avond met een paar vrienden in een appartement boven een winkel aan de Sint Bavostraat: de omvang van je gezelschap bepaalt het formaat. Alle formaten vind je in ons <a href=\"/assortiment/\">assortiment</a>, waar we naast de lachgastank 2KG, 4KG en 10KG ook crackers en slagroompatronen aanbieden. Je rekent contant of via Tikkie af bij levering, tegen de prijs die we vooraf in de chat hebben bevestigd, en de tank komt verzegeld aan. Leveren doen we alleen aan personen van 18 jaar of ouder, zo nodig na controle van een legitimatiebewijs. Lees vooraf ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Sint Bavostraat, Koekelberg, Lagestraat, Bredaseweg, Antwerpseweg, Tiggelt, Risten, Pannenhoef, Oekelsbos",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Tiggelt en in het buitengebied richting de Pannenhoef?", "Ja, de buurtschappen rond Rijsbergen horen bij ons bezorggebied. Zorg bij een adres aan een landweg voor een goed zichtbaar huisnummer of stuur een locatie mee in WhatsApp, dan vinden we je zonder omrijden."],
            ["Is de levertijd in Rijsbergen anders dan in Zundert?", "Rijsbergen ligt dichter bij Breda, maar we hanteren voor beide dorpen meestal binnen 25 tot 40 minuten omdat de route grotendeels dezelfde is. Voor Zundert zelf hebben we een <a href=\"/bezorggebied/zundert/\">aparte pagina</a>."],
            ["Kunnen jullie leveren bij een feest in een schuur of loods?", "Dat kan als het om een privéadres gaat waar iemand van 18 jaar of ouder de tank in ontvangst neemt. Voor evenementen met publiek of commerciële locaties gelden andere regels en bezorgen we niet."],
        ],
        "nearby": ["zundert", "princenhage", "etten-leur"],
        "lat": 51.5183, "lon": 4.6967,
    },
    {
        "slug": "sint-willebrord", "name": "Sint Willebrord", "kind": "dorp",
        "title": "Lachgas Sint Willebrord | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Sint Willebrord? Lachgas Breda levert lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Dorpsstraat tot het Processiepark. 18+.",
        "h1": "Lachgas bezorgen in Sint Willebrord",
        "lead": "Bestel via WhatsApp en ontvang je lachgastank verzegeld aan huis in Sint Willebrord, meestal binnen 25 tot 40 minuten.",
        "intro": [
            "Sint Willebrord, in de volksmond nog altijd ’t Heike, is de grootste kern van de gemeente Rucphen en ligt direct ten westen van Etten-Leur, tegen de A58 aan. Het dorp is bekend om de Lourdesgrot en het Processiepark bij de Sint-Willibrorduskerk en om zijn wielerverleden, met renners als Wim van Est. De Dorpsstraat en de Kaaistraat vormen het centrum; daaromheen liggen de woonstraten rond de Irenestraat en de Pastoor Bastiaansensingel en het buitengebied richting Sprundel en Rucphen. Wij bezorgen in heel het dorp. Je bestelt met een WhatsApp-bericht waarin je adres en het gewenste formaat tank staan.",
            "De bezorger rijdt vanuit Breda over de A58 richting Roosendaal; de snelweg loopt langs de zuidrand van Sint Willebrord en heeft een eigen afrit, zodat je na de afslag binnen een paar minuten in de Dorpsstraat staat. Het is een rit van ongeveer twintig kilometer die zelden meer dan een kwartier kost, en inclusief laden en het laatste stuk door de woonstraten komen we op meestal binnen 25 tot 40 minuten. Een station is er niet; de bus naar Etten-Leur en Roosendaal rijdt via de Dorpsstraat. Thuisblijven is dus het eenvoudigst: we sturen vooraf een tijdvak en komen tot aan je voordeur.",
            "Voor een avond in een rijtjeshuis aan de Irenestraat is de <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> vaak voldoende, terwijl een groter gezelschap in het buitengebied richting Sprundel beter uitkomt met de 4KG of 10KG. Crackers en slagroompatronen leveren we ook, allemaal verzegeld en tegen een prijs die vooraf in WhatsApp is bevestigd. Afrekenen doe je contant of via Tikkie bij levering. We leveren uitsluitend aan 18-plussers en kunnen om een identiteitsbewijs vragen voordat we de tank overhandigen. Over wat lachgas met je lichaam doet lees je meer op de pagina <a href=\"/lachgas-informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>.",
        ],
        "wijken": "Dorpsstraat, Kaaistraat, Irenestraat, Pastoor Bastiaansensingel, Processiepark, Lourdesgrot, Sprundel, Rucphen",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Sprundel, Rucphen en Zegge?", "Ja, alle kernen van de gemeente Rucphen vallen binnen ons gebied. Sprundel en Rucphen krijgen dezelfde levertijd als Sint Willebrord; voor Zegge en Schijf rekenen we op een iets ruimer tijdvak, dat we vooraf in de chat doorgeven."],
            ["Hoe snel kunnen jullie in Sint Willebrord zijn?", "Door de ligging direct aan de A58 zijn we hier meestal binnen 25 tot 40 minuten na bevestiging. Bij druk verkeer rond Etten-Leur of bij een wielerevenement in het dorp kan het iets langer duren, en dat melden we dan vooraf."],
            ["Moet ik mijn ID laten zien bij de deur?", "Als de bezorger twijfelt of je 18 bent, vraagt hij om een geldig legitimatiebewijs; zonder dat nemen we de tank weer mee. Hoe die controle werkt staat op de pagina <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole</a>."],
        ],
        "nearby": ["etten-leur", "hoeven", "roosendaal"],
        "lat": 51.5483, "lon": 4.5867,
    },
    {
        "slug": "klundert", "name": "Klundert", "kind": "dorp",
        "title": "Lachgas Klundert | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Klundert? Wij bezorgen verzegelde lachgastanks 2KG, 4KG en 10KG aan huis, van de Voorstraat tot Noordschans en Tonnekreek. Voor 18+.",
        "h1": "Lachgas bezorgen in Klundert",
        "lead": "Lachgastanks verzegeld aan huis in Klundert, besteld via WhatsApp en meestal binnen 25 tot 40 minuten geleverd vanuit Breda.",
        "intro": [
            "Klundert is een oud vestingstadje in de gemeente Moerdijk, met het zeventiende-eeuwse stadhuis aan de Voorstraat en de Stenen Poppen als restanten van de vroegere verdedigingswerken. De kern is klein en overzichtelijk: rond de Voorstraat, de Molenstraat en de Westerstraat liggen de woonbuurten, met sportpark De Blauwe Hoef aan de rand en zorgcentrum De Niervaert in het midden. Buiten de wallen liggen de buurtschappen Noordschans aan het Hollandsch Diep, Tonnekreek en Zwingelspaan, en aan de westkant het industrieterrein Moerdijk. Wij bezorgen in de hele kern en de buurtschappen. Via WhatsApp stuur je je adres en het formaat tank, en wij regelen de rest.",
            "Onze bezorger rijdt vanuit Breda over de A16 naar het noorden, gaat bij knooppunt Klaverpolder de A17 op en neemt de afrit Klundert, een route van ruim twintig kilometer die bij normaal verkeer rond de twintig minuten kost. Binnendoor via Zevenbergen is een alternatief als de A16 bij Prinsenbeek vaststaat. Met laden en de laatste meters door het stadje komen we uit op meestal binnen 25 tot 40 minuten. Klundert heeft geen station; het dichtstbijzijnde is Zevenbergen, aan de lijn Roosendaal–Dordrecht. Voor een levering aan huis speelt dat niet mee, we sturen vooraf een tijdvak en komen tot aan de deur.",
            "Of je nu een verjaardag viert in een huis aan de Molenstraat of met vrienden samenkomt in een boerderij bij Tonnekreek, de keuze voor een formaat hangt af van je gezelschap. De compacte 2KG en de ruimere 4KG en 10KG staan in ons <a href=\"/assortiment/\">assortiment</a>, net als crackers en slagroompatronen. De prijs bevestigen we vooraf via WhatsApp en je betaalt contant of via Tikkie bij levering; iedere tank komt verzegeld aan. We leveren alleen aan personen van 18 jaar en ouder en vragen bij twijfel om legitimatie. Verstandig omgaan met lachgas begint bij informatie, daarom verwijzen we je naar onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Voorstraat, Molenstraat, Westerstraat, Stenen Poppen, De Blauwe Hoef, De Niervaert, Noordschans, Tonnekreek, Zwingelspaan",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook op het industrieterrein Moerdijk?", "Nee, op bedrijventerreinen en in havens leveren we niet, ook niet aan personeel in nachtdienst. We bezorgen uitsluitend op woonadressen in Klundert, de buurtschappen en het dorp Moerdijk zelf."],
            ["Wat is de levertijd voor Klundert en Zevenbergen?", "Voor beide plaatsen rekenen we op meestal binnen 25 tot 40 minuten vanuit Breda, via de A16 en de A17. Zevenbergen ligt een paar minuten dichterbij, maar het verschil valt binnen hetzelfde tijdvak."],
            ["Kan ik ook in Noordschans of Zwingelspaan bezorgd krijgen?", "Ja, de buurtschappen rond Klundert horen bij de route. Stuur bij een adres aan een dijk of polderweg een locatie mee in WhatsApp, dan hoeft de bezorger in het donker niet te zoeken."],
        ],
        "nearby": ["fijnaart", "willemstad", "prinsenbeek"],
        "lat": 51.6633, "lon": 4.5333,
    },
    {
        "slug": "fijnaart", "name": "Fijnaart", "kind": "dorp",
        "title": "Lachgas Fijnaart | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Fijnaart? Verzegelde lachgastanks 2KG, 4KG en 10KG aan huis bezorgd in Fijnaart en Heijningen, van de Voorstraat tot de Kadedijk. 18+.",
        "h1": "Lachgas bezorgen in Fijnaart",
        "lead": "Via WhatsApp bestel je een lachgastank voor Fijnaart; we bezorgen verzegeld aan de deur, meestal binnen 35 tot 50 minuten.",
        "intro": [
            "Fijnaart ligt in het westen van de gemeente Moerdijk, in de polders tussen de Dintel en het Hollandsch Diep, met het Volkerak en de Volkeraksluizen op een paar kilometer afstand. Het dorp heeft een klassiek rechthoekig stratenplan rond de Voorstraat, de Kerkring met de hervormde kerk en de Molenstraat; daaromheen liggen nieuwere woonstraten en de Kadedijk aan de zuidkant. Even verderop liggen Heijningen met Fort Sabina en de buurtschap Oudemolen. Wij bezorgen in Fijnaart, Heijningen en het omliggende buitengebied. Een WhatsApp-bericht met je adres en het formaat tank is genoeg; wij bevestigen prijs en tijdvak.",
            "Vanuit Breda rijdt onze bezorger over de A16 en bij knooppunt Zonzeel de A59 op naar het westen, langs Zevenbergen en knooppunt Noordhoek tot de afrit Fijnaart. De afstand is rond de dertig kilometer en in de praktijk kost de rit een half uur, waardoor we voor dit deel van Moerdijk uitkomen op meestal binnen 35 tot 50 minuten. Fijnaart heeft geen station en de busverbinding met Zevenbergen en Oudenbosch is beperkt, dus thuis bezorgd krijgen is hier de logische keuze. Na je bestelling sturen we een realistisch tijdvak dat rekening houdt met het verkeer op de A59 en de A16.",
            "Een verjaardag in een gezinswoning aan de Molenstraat vraagt om een ander formaat dan een klein samenzijn in een appartement aan de Voorstraat. De <a href=\"/product/lachgas-tank-10kg/\">lachgastank 10KG</a> is het grootste formaat en bedoeld voor grotere gezelschappen; de 2KG en 4KG zijn de handzame alternatieven. Alle tanks komen verzegeld aan, met een prijs die vooraf in WhatsApp is vastgelegd, en je betaalt contant of via Tikkie bij levering. We leveren uitsluitend aan 18-plussers en controleren zo nodig een legitimatiebewijs. Wat je over bewaren en vervoeren moet weten, staat op onze pagina <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">tank bewaren en vervoeren</a>.",
        ],
        "wijken": "Voorstraat, Kerkring, Molenstraat, Kadedijk, Oude Heijningsedijk, Appelaarsedijk, Heijningen, Oudemolen, Fort Sabina",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Heijningen en Willemstad?", "Heijningen nemen we mee in de route voor Fijnaart en krijgt dezelfde levertijd. Willemstad ligt een paar kilometer verder aan het Hollandsch Diep en heeft een <a href=\"/bezorggebied/willemstad/\">eigen pagina</a>, met eveneens meestal binnen 35 tot 50 minuten."],
            ["Waarom is de levertijd voor Fijnaart langer dan voor Klundert?", "Klundert ligt direct aan de A17, terwijl de bezorger voor Fijnaart verder over de A59 moet doorrijden tot voorbij knooppunt Noordhoek. Die extra kilometers maken dat we hier meestal binnen 35 tot 50 minuten hanteren."],
            ["Kan ik een tank laten bezorgen bij een vakantiehuisje aan het Volkerak?", "Op een recreatiepark leveren we alleen aan huisjes met een eigen adres, als het park dat toelaat en er iemand van 18 jaar of ouder aanwezig is. Op jachthavens en in de buurt van de sluizen bezorgen we niet."],
        ],
        "nearby": ["klundert", "willemstad", "dinteloord"],
        "lat": 51.6383, "lon": 4.4667,
    },
    {
        "slug": "steenbergen", "name": "Steenbergen", "kind": "stad",
        "title": "Lachgas Steenbergen | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Steenbergen? Lachgas Breda bezorgt lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Markt tot Buiten de Veste en Welberg. 18+.",
        "h1": "Lachgas bezorgen in Steenbergen",
        "lead": "Bestel via WhatsApp en ontvang je lachgastank verzegeld aan huis in Steenbergen, meestal binnen 35 tot 50 minuten na bevestiging.",
        "intro": [
            "Steenbergen is een voormalige vestingstad in het uiterste westen van Brabant, met de hoge toren van de Sint-Gummaruskerk als baken boven de polders en de Steenbergse Vliet die via het Benedensas uitkomt op het Volkerak. Het centrum rond de Markt en de Kaaistraat wordt omringd door woonstraten langs de Noordwal en de Zuidwal en door de nieuwbouw van Buiten de Veste; aan de zuidkant ligt het dorp Welberg bijna tegen de stad aan. De gemeente omvat ook Kruisland, De Heen, Nieuw-Vossemeer en Dinteloord. Wij bezorgen in de stad en in alle kernen. Via WhatsApp geef je je adres en het gewenste formaat door en wij bevestigen de prijs.",
            "Vanuit Breda zijn er twee routes: over de A58 naar Roosendaal en dan binnendoor via Wouw en Kruisland, of over de A16 en de A59 naar knooppunt Sabina en vervolgens de A4 naar het zuiden tot de afrit Steenbergen. Beide ritten zijn rond de vijftig kilometer en kosten bij vlot verkeer ongeveer veertig minuten, zodat we hier meestal binnen 35 tot 50 minuten hanteren. Steenbergen heeft geen treinstation; de bus verbindt de stad met Bergen op Zoom en Roosendaal. Je hoeft dus nergens heen: na je bestelling krijg je een tijdvak dat past bij het verkeer op dat moment.",
            "Een huiskamerfeest aan de Kaaistraat, een verjaardag in een nieuwbouwwoning in Buiten de Veste of een rustige avond in Welberg: het aantal gasten bepaalt welk formaat zinvol is. In ons <a href=\"/assortiment/\">assortiment</a> vind je de lachgastank 2KG, 4KG en 10KG, en daarnaast crackers en slagroompatronen. De prijs staat vooraf vast in de WhatsApp-bevestiging, de tank komt verzegeld aan en je betaalt contant of via Tikkie bij levering. Wij leveren alleen aan personen van 18 jaar of ouder en vragen bij twijfel om een legitimatiebewijs. Lees voor je bestelt ook wat we schrijven over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Centrum rond de Markt, Kaaistraat, Noordwal, Zuidwal, Buiten de Veste, Welberg, Kruisland, De Heen, Nieuw-Vossemeer, Benedensas",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Kruisland, De Heen en Nieuw-Vossemeer?", "Ja, alle kernen van de gemeente Steenbergen vallen binnen ons gebied. Kruisland ligt op de route vanuit Roosendaal en is vaak iets eerder aan de beurt; voor De Heen en Nieuw-Vossemeer kan het tijdvak aan de ruime kant uitvallen, en dat melden we vooraf. Dinteloord heeft een <a href=\"/bezorggebied/dinteloord/\">eigen pagina</a>."],
            ["Hoe lang duurt bezorging in Steenbergen?", "Reken op meestal binnen 35 tot 50 minuten na bevestiging via WhatsApp. De afstand vanuit Breda is de belangrijkste factor; de route via de A4 of binnendoor via Wouw kiezen we op basis van het verkeer."],
            ["Leveren jullie ook op boten of aan de jachthaven bij het Benedensas?", "Nee, op het water en in havens bezorgen we niet. We leveren uitsluitend op een woonadres waar iemand van 18 jaar of ouder de verzegelde tank persoonlijk in ontvangst neemt."],
        ],
        "nearby": ["dinteloord", "halsteren", "bergen-op-zoom"],
        "lat": 51.5833, "lon": 4.3167,
    },
    {
        "slug": "dinteloord", "name": "Dinteloord", "kind": "dorp",
        "title": "Lachgas Dinteloord | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Dinteloord? Lachgas Breda levert verzegelde lachgastanks 2KG, 4KG en 10KG aan huis, van de Westvoorstraat tot Dintelsas. 18+.",
        "h1": "Lachgas bezorgen in Dinteloord",
        "lead": "Lachgastanks verzegeld aan huis in Dinteloord, besteld via WhatsApp en meestal binnen 35 tot 50 minuten geleverd vanuit Breda.",
        "intro": [
            "Dinteloord is het noordelijkste dorp van de gemeente Steenbergen en ligt in de Prinsenlandse polder tussen de Dintel en het Volkerak, met de suikerfabriek en het agro-foodcluster Nieuw Prinsenland als grootste werkgevers aan de rand. Het dorp is gebouwd rond de Westvoorstraat en de Oostvoorstraat, die bij het Raadhuisplein samenkomen; daaromheen liggen de woonstraten langs de Molendijk en de Steenbergseweg en aan het water de buurtschap Dintelsas met de sluis. Wij bezorgen in de kern, in Dintelsas en in het buitengebied. Bestellen gaat met één WhatsApp-bericht waarin je adres en het gewenste formaat tank staan.",
            "Onze bezorger rijdt vanuit Breda over de A16 en de A59 naar het westen, voorbij Zevenbergen en Fijnaart, tot knooppunt Sabina waar de A4 begint; Dinteloord ligt direct naast dat knooppunt. De rit is ongeveer veertig kilometer en kost bij normaal verkeer ruim een half uur, waardoor we hier uitkomen op meestal binnen 35 tot 50 minuten. Een station heeft het dorp niet; de bus rijdt naar Steenbergen en Bergen op Zoom. Omdat Dinteloord aan de rand van ons gebied ligt, sturen we na elke bestelling een tijdvak dat is afgestemd op de drukte van dat moment, zodat je weet wanneer je ons kunt verwachten.",
            "Een avond met vrienden in een arbeiderswoning aan de Oostvoorstraat of een feest in een boerderij in de polder: de situatie bepaalt het formaat. De <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> is voor middelgrote gezelschappen een logische keuze, de 2KG voor kleinere groepen en de 10KG voor wie veel gasten verwacht. Iedere tank komt verzegeld aan, tegen een prijs die vooraf in de chat is bevestigd, en je betaalt contant of via Tikkie bij levering. We leveren uitsluitend aan 18-plussers en vragen zo nodig een legitimatiebewijs. Wat de wet zegt, lees je op onze pagina <a href=\"/lachgas-informatie/is-lachgas-legaal-in-nederland/\">is lachgas legaal in Nederland</a>.",
        ],
        "wijken": "Westvoorstraat, Oostvoorstraat, Raadhuisplein, Molendijk, Steenbergseweg, Dintelsas, Nieuw Prinsenland, Stampersgat",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Stampersgat en Oud Gastel?", "Ja, Stampersgat ligt aan de overkant van de Dintel en nemen we mee met dezelfde levertijd als Dinteloord. Oud Gastel ligt meer richting Roosendaal en krijgt een tijdvak dat we vooraf afstemmen."],
            ["Hoe snel zijn jullie in Dinteloord?", "Meestal binnen 35 tot 50 minuten na bevestiging. De route over de A59 en knooppunt Sabina is vrijwel altijd vlot, maar de afstand vanuit Breda maakt een korter tijdvak niet realistisch."],
            ["Kan ik ook bezorgd krijgen aan de haven van Dintelsas?", "Op een woonadres in de buurtschap Dintelsas wel, op boten, in de jachthaven of bij de sluis niet. We leveren alleen aan de deur, aan iemand van 18 jaar of ouder die zich zo nodig kan <a href=\"/leeftijdscontrole-18-plus/\">legitimeren</a>."],
        ],
        "nearby": ["steenbergen", "fijnaart", "willemstad"],
        "lat": 51.6367, "lon": 4.3700,
    },
    {
        "slug": "hoogerheide", "name": "Hoogerheide", "kind": "dorp",
        "title": "Lachgas Hoogerheide | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Hoogerheide? Lachgas Breda bezorgt lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Raadhuisstraat tot Woensdrecht. 18+.",
        "h1": "Lachgas bezorgen in Hoogerheide",
        "lead": "Via WhatsApp bestel je een lachgastank voor Hoogerheide; we bezorgen verzegeld aan de deur, meestal binnen 35 tot 50 minuten.",
        "intro": [
            "Hoogerheide is de hoofdkern van de gemeente Woensdrecht en ligt boven op de steilrand van de Brabantse Wal, met uitzicht over de Zeeuwse polders en op een steenworp van de Belgische grens en de Kalmthoutse Heide. De Raadhuisstraat is de winkelstraat van het dorp; daaromheen liggen woonstraten rond de Huijbergseweg, de Scheldeweg en de Duinstraat, en aan de zuidkant Vliegbasis Woensdrecht met het bedrijvenpark Aviolanda. Het dorp Woensdrecht ligt er direct tegenaan. Wij bezorgen in Hoogerheide, Woensdrecht en de andere kernen van de gemeente. Bestellen doe je via WhatsApp met je adres en het formaat tank dat je wilt.",
            "Vanuit Breda rijdt de bezorger over de A58 naar Bergen op Zoom en vervolgens over de A4 richting Antwerpen tot de afrit Hoogerheide, een rit van ongeveer 55 kilometer die bij vlot verkeer rond de veertig minuten duurt. Via de N289 langs landgoed Mattemburgh kan het ook, maar dat is zelden sneller. Hoogerheide is daarmee een van de verste punten in ons gebied en we hanteren hier meestal binnen 35 tot 50 minuten. Een station is er niet; de bus naar Bergen op Zoom rijdt over de Scheldeweg. Je hoeft dus niets te regelen: wij sturen een tijdvak en komen tot aan je voordeur.",
            "Voor een avond in een appartement aan de Raadhuisstraat is de <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> meestal passend; voor een grotere groep in een vrijstaand huis aan de bosrand zijn de 4KG en 10KG geschikter. Alle tanks komen verzegeld aan en de prijs is vooraf via WhatsApp bevestigd, zodat je bij de deur alleen nog contant of via Tikkie afrekent. Wij leveren uitsluitend aan personen van 18 jaar of ouder, zo nodig na een controle van je legitimatiebewijs. Woon je net over de grens in Kalmthout of Essen, lees dan onze pagina over de <a href=\"/lachgas-grensregio-belgie/\">grensregio met België</a>, want daar bezorgen we niet vanuit Breda.",
        ],
        "wijken": "Centrum rond de Raadhuisstraat, Huijbergseweg, Scheldeweg, Duinstraat, Onderstal, Aviolanda, Vliegbasis Woensdrecht, Mattemburgh, Woensdrecht",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Ossendrecht, Putte en Huijbergen?", "Ja, alle kernen van de gemeente Woensdrecht vallen binnen ons gebied, met dezelfde indicatie van meestal binnen 35 tot 50 minuten. Voor Putte, dat tegen de grens ligt, bezorgen we uitsluitend aan het Nederlandse deel van het dorp."],
            ["Kunnen jullie leveren op de vliegbasis of op Aviolanda?", "Nee, militaire terreinen en bedrijvenparken vallen buiten ons bezorggebied. We leveren alleen op woonadressen, waar iemand van 18 jaar of ouder de tank persoonlijk aanneemt."],
            ["Geldt voor Hoogerheide dezelfde levertijd als voor Bergen op Zoom?", "Ja, voor beide hanteren we meestal binnen 35 tot 50 minuten, al zit Hoogerheide door het extra stuk over de A4 vaker aan de ruime kant van dat tijdvak. Hoe we met tijdvakken omgaan lees je op de pagina over <a href=\"/bezorgtijden-breda/\">bezorgtijden</a>."],
        ],
        "nearby": ["bergen-op-zoom", "halsteren", "roosendaal"],
        "lat": 51.4267, "lon": 4.3217,
    },
    {
        "slug": "raamsdonksveer", "name": "Raamsdonksveer", "kind": "dorp",
        "title": "Lachgas Raamsdonksveer | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Raamsdonksveer? Wij bezorgen lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Keizersdijk tot Boterpolder en Sandoel. 18+.",
        "h1": "Lachgas bezorgen in Raamsdonksveer",
        "lead": "Bestel via WhatsApp en ontvang je lachgastank verzegeld aan huis in Raamsdonksveer, meestal binnen 25 tot 40 minuten.",
        "intro": [
            "Raamsdonksveer is de grootste kern van de gemeente Geertruidenberg en ligt aan de Donge, vlak bij de plek waar die rivier uitmondt in de Bergsche Maas. Het dorp is vergroeid met knooppunt Hooipolder, waar de A27 en de A59 elkaar kruisen, en met het bedrijventerrein Dombosch langs de snelweg. De Keizersdijk is de winkelstraat, met het Heereplein als centrum; daaromheen liggen woonwijken als Boterpolder, Sandoel en Gasthuiswaard. Aan de overkant van de Donge ligt de vestingstad Geertruidenberg, iets zuidelijker het dorp Raamsdonk. Wij bezorgen in alle drie de kernen. Via WhatsApp stuur je je adres en het gewenste formaat tank.",
            "Vanuit Breda rijdt onze bezorger over de A27 naar het noorden, langs Oosterhout tot aan knooppunt Hooipolder, en neemt daar de afslag naar het dorp. Het is een rit van nog geen twintig kilometer, maar de verkeerslichten en de werkzaamheden op Hooipolder kunnen voor oponthoud zorgen, zeker in de avondspits. Daarom hanteren we voor Raamsdonksveer meestal binnen 25 tot 40 minuten en geven we na je bestelling een tijdvak door dat past bij de situatie op de weg. Een treinstation is er niet en de bus naar Breda en Oosterhout rijdt niet de hele nacht, maar wie bestelt hoeft de deur niet uit.",
            "Een borrel in een appartement aan het Heereplein of een feest in een gezinswoning in Boterpolder: het formaat van de tank hangt af van wat je organiseert. In ons <a href=\"/assortiment/\">assortiment</a> staan de lachgastank 2KG, 4KG en 10KG, aangevuld met crackers en slagroompatronen; in de chat helpen we je kiezen. Je betaalt contant of via Tikkie bij levering, tegen de prijs die we vooraf hebben bevestigd, en de tank wordt verzegeld overhandigd. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen bij twijfel naar een legitimatiebewijs. Over verantwoord omgaan met lachgas lees je meer op de pagina <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Keizersdijk, Heereplein, Boterpolder, Sandoel, Gasthuiswaard, Dombosch, Hooipolder, Raamsdonk, Geertruidenberg",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Geertruidenberg en Raamsdonk?", "Ja, de hele gemeente Geertruidenberg hoort bij ons gebied en krijgt dezelfde levertijd als Raamsdonksveer. Ook de binnenstad van Geertruidenberg rond de Markt is bereikbaar, al kan het bij evenementen daar even zoeken zijn naar een plek om te stoppen."],
            ["Hoe snel zijn jullie in Raamsdonksveer?", "Meestal binnen 25 tot 40 minuten na bevestiging via WhatsApp. De A27 is kort, maar knooppunt Hooipolder bepaalt in de praktijk hoe snel we het dorp binnenkomen; staat het daar vast, dan kiezen we een route binnendoor via <a href=\"/bezorggebied/oosterhout/\">Oosterhout</a>."],
            ["Leveren jullie ook op het bedrijventerrein Dombosch?", "Nee, op bedrijventerreinen en bij horeca bezorgen we niet. We leveren alleen op woonadressen in Raamsdonksveer, Raamsdonk en Geertruidenberg, aan iemand van 18 jaar of ouder die de verzegelde tank persoonlijk aanneemt."],
        ],
        "nearby": ["oosterhout", "made", "dongen"],
        "lat": 51.6950, "lon": 4.8733,
    },
]
