# -*- coding: utf-8 -*-
# Nieuwe Bredase wijken (fase 3) en de regio-hub West-Brabant voor lachgasbreda.nl. Alleen data.

AREAS = [
    {
        "slug": "tuinzigt",
        "name": "Tuinzigt",
        "kind": "wijk",
        "title": "Lachgas Tuinzigt | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Tuinzigt, Breda-West? Bezorgd aan huis rond de Tuinzigtlaan en de Dijklaan, meestal binnen 20 tot 30 minuten. Uitsluitend 18+.",
        "h1": "Lachgas Tuinzigt",
        "lead": "Lachgastanks aan de deur in Tuinzigt, vlak ten westen van het centrum van Breda. Bestel via WhatsApp en reken op meestal 20 tot 30 minuten.",
        "intro": [
            "Tuinzigt is een rustige woonwijk aan de westkant van Breda, voorbij de Tramsingel en ten noorden van Haagpoort en de Haagweg. De Tuinzigtlaan en de Dijklaan vormen de ruggengraat; daartussen liggen straten met rijtjeshuizen en kleine voortuinen, met aan de noordkant het spoor richting Roosendaal en aan de zuidwestkant de Ettensebaan. Wij bezorgen in de hele wijk. Je stuurt via WhatsApp door wat je wilt bestellen en op welk adres je bent, wij bevestigen de prijs en noemen een verwachte aankomsttijd, en daarna komt de bezorger naar je voordeur.",
            "De afstand tot de binnenstad is klein: vanaf de Haagdijk steek je de Tramsingel over en je bent er bijna. Onze bezorgers rijden meestal via de Tuinzigtlaan de wijk in, of vanaf de Ettensebaan als ze uit Westerpark of Princenhage komen. Omdat er geen snelweg of brug tussen zit, is dit een van de snelste ritten die we in de stad maken en blijft de levertijd meestal binnen 20 tot 30 minuten. Station Breda is vanuit Tuinzigt in een paar minuten fietsen bereikt. In de smallere straten is parkeren voor de deur niet altijd mogelijk; de bezorger zet de wagen dan even verderop neer en loopt naar je toe.",
            "Een verjaardag in een rijtjeshuis aan de Dijklaan, een avond met huisgenoten bij de Tuinzigtlaan of een borrel met buren in een van de zijstraten: je kiest zelf het formaat dat bij het gezelschap past. De <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> is handig voor een klein groepje, de 4KG en 10KG voor meer mensen; crackers en slagroompatronen nemen we mee als je dat aangeeft. Je betaalt bij de deur, contant of via Tikkie, tegen de prijs die vooraf in WhatsApp is bevestigd. We leveren alleen aan 18-plussers en vragen om een identiteitsbewijs. Wat je verder moet weten over verantwoord omgaan met lachgas staat bij <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Tuinzigtlaan, Dijklaan, Rozenlaan, Ettensebaan, Lunetstraat, Tramsingel",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Tuinzigt vanuit het centrum?",
             "Heel snel: Tuinzigt grenst aan de singels, dus de rit duurt maar een paar minuten. We noemen bij elke bestelling een indicatie, meestal 20 tot 30 minuten, en melden het als het op een druk moment iets langer wordt."],
            ["Ik woon in een hofje achter de Tuinzigtlaan, vindt de bezorger dat?",
             "Ja, maar help even mee: zet in je bericht de volledige straatnaam, het huisnummer en of de ingang aan de voor- of achterkant zit. Zo hoeft de bezorger niet rond te lopen als hij er is."],
            ["Bezorgen jullie in Tuinzigt ook laat op de avond of ’s nachts?",
             "Ja, ook na middernacht komen we naar Tuinzigt; de indicatie blijft dan meestal 20 tot 30 minuten. Hoe nachtlevering precies werkt, lees je op <a href=\"/lachgas-nachtbezorging/\">lachgas nachtbezorging</a>."],
        ],
        "nearby": ["haagpoort", "westerpark", "breda-centrum"],
        "lat": 51.591, "lon": 4.757,
    },
    {
        "slug": "boeimeer",
        "name": "Boeimeer",
        "kind": "wijk",
        "title": "Lachgas Boeimeer | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Boeimeer? Aan huis bezorgd tussen de Mark en de Heuvel, van de Boeimeerweg tot Ruitersbos, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Boeimeer",
        "lead": "Bezorging aan de deur in Boeimeer en Ruitersbos, ten zuidwesten van het centrum van Breda. Via WhatsApp besteld, meestal binnen 20 tot 30 minuten gebracht.",
        "intro": [
            "Boeimeer ligt ten zuidwesten van de Bredase binnenstad, met de rivier de Mark als oostgrens en de Heuvel als buur aan de westkant. Het noordelijke deel bestaat uit woonstraten rond de Boeimeerweg en de Dr. Batenburglaan, waar ook het terrein van het voormalige ziekenhuis aan de Langendijk een nieuwe bestemming krijgt; voorbij de Graaf Engelbertlaan gaat de wijk over in Ruitersbos, een groene buurt met ruime huizen tegen het Mastbos. Wij bezorgen in beide delen. Via WhatsApp geef je door wat je nodig hebt en waar je zit; je krijgt de prijs bevestigd en hoort wanneer de bezorger er ongeveer is.",
            "Vanuit het centrum is Boeimeer een rit van enkele minuten langs de Mark, en vanaf de A16 brengt de Graaf Engelbertlaan je rechtstreeks de wijk in. Die korte afstand zonder obstakels maakt dat de levertijd hier meestal binnen 20 tot 30 minuten blijft, ook aan het begin van een drukke avond. Ruitersbos ligt iets verder van het centrum, maar via de Burgemeester de Manlaan is ook dat deel vlot bereikt. De lanen daar zijn ruim en rustig; in het noordelijke deel staat het soms voller met auto’s, dus een duidelijke aanwijzing over je voordeur is welkom.",
            "Of je nu een etentje hebt in een huis aan de Boeimeerweg, een feestje in een appartement bij de Dr. Batenburglaan of een tuinborrel in Ruitersbos: in ons <a href=\"/assortiment/\">assortiment</a> vind je lachgastanks van 2KG, 4KG en 10KG, naast crackers en slagroompatronen. Welk formaat verstandig is, hangt af van het aantal mensen en de duur van de avond; onze <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">keuzehulp</a> zet de verschillen op een rij. Betalen doe je bij de overdracht, contant of via Tikkie, tegen de vooraf bevestigde prijs. We bezorgen uitsluitend aan personen van 18 jaar en ouder en controleren een geldig identiteitsbewijs aan de deur.",
        ],
        "wijken": "Boeimeerweg, Dr. Batenburglaan, Langendijk, Graaf Engelbertlaan, Ruitersbos, Burgemeester de Manlaan, Mastbos",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Valt Ruitersbos ook onder jullie bezorging in Boeimeer?",
             "Ja, Ruitersbos hoort bij hetzelfde gebied. De huizen tegen het Mastbos liggen iets verder van het centrum, maar de indicatie blijft meestal 20 tot 30 minuten. Vermeld bij een lange oprit even waar de bezorger kan aanbellen."],
            ["Ik woon aan de Mark, kan ik de tank op het terras laten bezorgen?",
             "De overdracht gebeurt aan je voordeur of in de hal van je gebouw, niet op een openbare plek langs het water. Je laat je ID zien, betaalt en neemt de verzegelde tank zelf mee naar binnen."],
            ["Hoe bewaar ik een tank in een warm huis of op zolder?",
             "Zet de tank rechtop op een koele, droge plek uit de zon en uit de buurt van kachels of ovens; een zolder onder een plat dak wordt in de zomer te warm. Meer aanwijzingen staan in <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">lachgastank bewaren en vervoeren</a>."],
        ],
        "nearby": ["breda-centrum", "heuvel", "ginneken"],
        "lat": 51.579, "lon": 4.768,
    },
    {
        "slug": "zandberg",
        "name": "Zandberg",
        "kind": "wijk",
        "title": "Lachgas Zandberg | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Zandberg? Bezorgd in Zandberg-West en -Oost, rond het Wilhelminapark en de Zandberglaan, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Zandberg",
        "lead": "Lachgas aan de deur in Zandberg, de wijk tussen de Wilhelminasingel en het Ginneken. Bestellen via WhatsApp, meestal binnen 20 tot 30 minuten geleverd.",
        "intro": [
            "Zandberg ligt direct ten zuidoosten van het Bredase centrum, net buiten de Wilhelminasingel. De Zandberglaan deelt de wijk in Zandberg-West, met het Wilhelminapark, de herenhuizen van de Baronielaan en de winkels aan de Ginnekenweg, en Zandberg-Oost, met rustigere woonstraten tot aan het Sportpark. Veel studenten en jonge huishoudens wonen hier naast gezinnen die er al lang zitten. Wij bezorgen in beide helften. Stuur via WhatsApp je bestelling en adres, dan krijg je de prijs en een tijdsindicatie terug en komt de bezorger naar de deur die je hebt opgegeven.",
            "Dichter bij de binnenstad dan Zandberg kun je bijna niet wonen: vanaf de Wilhelminasingel rijd je de wijk in via de Ginnekenweg of de Zandberglaan. Daarom hoort Zandberg bij de snelste adressen in ons gebied en geldt hier meestal 20 tot 30 minuten. Vanaf de snelweg komen onze bezorgers via de Zuidelijke Rondweg naar de zuidkant van de wijk. De straten rond de Ginnekenweg zijn smal en staan ’s avonds vol geparkeerd; wie boven een winkel woont, doet er goed aan de ingang te beschrijven. Bussen vanaf station Breda stoppen op de Ginnekenweg.",
            "Een studentenhuis bij de Ginnekenweg, een verjaardag in een bovenwoning aan de Baronielaan of een avond met vrienden in Zandberg-Oost: kies het formaat dat erbij past. Voor een klein gezelschap is een <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> vaak voldoende, voor een groter huis een 4KG of 10KG, en crackers en slagroompatronen bestel je er los bij. De prijs krijg je vooraf via WhatsApp, betalen doe je bij aflevering, contant of via Tikkie. Wij leveren uitsluitend aan 18-plussers en vragen iedereen om een geldig identiteitsbewijs, ook in studentenhuizen. Wat daarbij geldt, lees je op <a href=\"/lachgas-studenten-breda/\">lachgas voor studenten in Breda</a>.",
        ],
        "wijken": "Zandberg-West, Zandberg-Oost, Wilhelminapark, Baronielaan, Zandberglaan, Ginnekenweg, Generaal Maczekstraat, Sportpark",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie aan een studentenhuis aan de Ginnekenweg of de Baronielaan?",
             "Ja, zolang degene die bestelt zelf opendoet, 18 jaar of ouder is en een geldig ID laat zien. We geven de tank niet af aan een huisgenoot die dat niet kan aantonen. Zet het belnummer in je bericht als er meerdere bellen zijn."],
            ["Hoort het Sportpark bij Zandberg voor jullie levertijd?",
             "Ja, de straten rond het Sportpark rekenen we tot Zandberg-Oost en daarvoor geldt dezelfde indicatie van meestal 20 tot 30 minuten. Je hoeft dus niets anders te doen dan je adres doorgeven."],
            ["Kan ik een tank bestellen voor een picknick in het Wilhelminapark?",
             "Nee. Wij bezorgen alleen aan een woon- of verblijfadres en niet in parken of op straat; in de openbare ruimte van Breda gelden bovendien aparte regels voor lachgas. Lees meer in <a href=\"/lachgas-informatie/lachgas-regels-breda/\">lachgas en de regels in Breda</a>."],
        ],
        "nearby": ["breda-centrum", "ginneken", "blauwe-kei"],
        "lat": 51.582, "lon": 4.790,
    },
    {
        "slug": "hoge-vucht",
        "name": "Hoge Vucht",
        "kind": "wijk",
        "title": "Lachgas Hoge Vucht | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in de Hoge Vucht, Breda-Noord? Bezorgd in Wisselaar, Biesdonk en de Geeren, meestal binnen 20 tot 30 minuten. Via WhatsApp, 18+.",
        "h1": "Lachgas Hoge Vucht",
        "lead": "Aan huis bezorgd in de Hoge Vucht, van Geeren-Zuid tot Wisselaar. Bestel via WhatsApp en de bezorger staat meestal binnen 20 tot 30 minuten voor je deur.",
        "intro": [
            "De Hoge Vucht is de grote woonwijk in Breda-Noord, ten noorden van de Noordelijke Rondweg en ten oosten van de Terheijdenseweg. De wijk is in de jaren zestig en zeventig gebouwd en bestaat uit vier buurten: Geeren-Zuid en Geeren-Noord aan de kant van de rondweg, Biesdonk in het oosten en Wisselaar in het noorden, tegen de open polder. Winkelcentrum Moerwijk is het dagelijkse middelpunt. Wij bezorgen in alle vier de buurten, in de flats en in de rijtjeshuizen. Stuur je bestelling en adres via WhatsApp; je krijgt de prijs bevestigd en hoort meteen wanneer je ons kunt verwachten.",
            "Vanuit het centrum rijden onze bezorgers via Belcrum en de Terheijdenseweg of over de Noordelijke Rondweg de wijk in; vanaf de A27 is het via die rondweg eveneens een paar minuten. De afstand tot de binnenstad is iets groter dan naar de wijken rond de singels, maar de wegen zijn breed en de doorstroming is goed, zodat we hier meestal binnen 20 tot 30 minuten aan de deur staan. In de flatbuurten helpt het als je de naam van het gebouw, de verdieping en het belnummer doorgeeft, want de ingangen liggen niet altijd aan de straatkant. De wijk is per bus goed verbonden met het station.",
            "Een verjaardag in een flat in Geeren-Noord, een feestje in een hoekwoning in Biesdonk of een rustige avond met vrienden in Wisselaar: het formaat bepaal je zelf. In ons <a href=\"/assortiment/\">assortiment</a> staan tanks van 2KG, 4KG en 10KG, plus crackers en slagroompatronen. Je betaalt bij de deur, contant of via Tikkie, tegen de prijs die we vooraf via WhatsApp hebben bevestigd. We verkopen alleen aan personen van 18 jaar en ouder en controleren het identiteitsbewijs bij elke levering, ook als we je al kennen. Hoe die controle werkt, lees je op <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole 18+</a>.",
        ],
        "wijken": "Wisselaar, Biesdonk, Geeren-Noord, Geeren-Zuid, winkelcentrum Moerwijk, Groenedijk, Terheijdenseweg, Nieuwe Kadijk",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Is de Hoge Vucht voor jullie verder weg dan de rest van Breda?",
             "Een paar minuten rijden meer dan de singelwijken, maar de indicatie is hetzelfde: meestal 20 tot 30 minuten. Via de Terheijdenseweg of de Noordelijke Rondweg zijn we vlot in Wisselaar, Biesdonk of de Geeren."],
            ["Bezorgen jullie ook aan de flats bij winkelcentrum Moerwijk?",
             "Ja. Geef de naam of het nummer van het gebouw, de verdieping en het belnummer door, dan belt de bezorger aan en komt hij naar je deur of ontmoet je hem in de hal. We laten nooit iets achter bij een centrale ingang."],
            ["Wat gebeurt er als ik niet thuis ben wanneer de bezorger aankomt?",
             "Dan nemen we de tank mee terug; we leveren alleen persoonlijk aan de besteller na controle van het ID. Laat het via WhatsApp weten als je later bent, dan passen we de rit aan. Zie ook <a href=\"/werkwijze/\">onze werkwijze</a>."],
        ],
        "nearby": ["belcrum", "doornbos-linie", "teteringen"],
        "lat": 51.613, "lon": 4.788,
    },
    {
        "slug": "ijpelaar",
        "name": "IJpelaar",
        "kind": "wijk",
        "title": "Lachgas IJpelaar | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in IJpelaar of Overakker? Bezorgd in Breda-Zuidoost, bij de Molengracht en de Bavelselaan, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas IJpelaar",
        "lead": "Lachgastanks aan de deur in IJpelaar en Overakker, in het zuidoosten van Breda. Via WhatsApp bestellen, meestal binnen 20 tot 30 minuten bezorgd.",
        "intro": [
            "IJpelaar ligt in het zuidoosten van Breda, ten zuiden van Brabantpark en het Amphia-ziekenhuis aan de Molengracht, met het Ginneken en de Blauwe Kei aan de westkant en Bavel een stuk verder naar het zuidoosten. De woonstraten dragen namen van kastelen, zoals de Loevesteinstraat en de Muiderslotstraat, en aan de kant van het Ginneken ligt de buurt Overakker. Wij bezorgen in de hele wijk, inclusief Overakker en de straten langs de Bavelselaan. Via WhatsApp stuur je je bestelling en adres; je ontvangt de prijs en een verwachte aankomsttijd en daarna komt de bezorger naar je toe.",
            "Vanuit het centrum is IJpelaar via de Claudius Prinsenlaan en de Molengracht of via het Ginneken in enkele minuten bereikt, en ook vanaf de A27 aan de oostkant van de stad is het een korte rit. Daardoor geldt hier dezelfde indicatie als in de rest van Breda: meestal binnen 20 tot 30 minuten. Rond het ziekenhuis is het verkeer soms druk, maar dat kost zelden meer dan een paar minuten. IJpelaar is overwegend een wijk van eengezinswoningen met een eigen voordeur, wat de overdracht eenvoudig maakt; in de flats aan de randen vragen we om de verdieping en het belnummer.",
            "Een familiefeest in een hoekwoning aan de Loevesteinstraat, een avond met vrienden in Overakker of een borrel in een tuin aan de rand van de wijk: voor elk gezelschap is er een passend formaat. De verschillen tussen de <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> en de kleinere en grotere varianten leggen we graag uit via WhatsApp, zodat je niet meer neemt dan nodig. Crackers en slagroompatronen leveren we erbij. Betalen gaat bij aflevering, contant of via Tikkie, tegen de vooraf bevestigde prijs. We leveren uitsluitend aan 18-plussers met een geldig identiteitsbewijs. Lees voor de avond ook onze pagina over <a href=\"/lachgas-informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>.",
        ],
        "wijken": "Overakker, Molengracht, Amphia Molengracht, Loevesteinstraat, Muiderslotstraat, Bavelselaan, Overakkerstraat",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoort Overakker bij IJpelaar of bij het Ginneken?",
             "Voor ons maakt het niet uit: Overakker ligt tussen beide in en we bezorgen er met dezelfde indicatie van meestal 20 tot 30 minuten. Geef je straat en huisnummer door, dan weet de bezorger genoeg."],
            ["Ik werk in het Amphia aan de Molengracht, kunnen jullie daar leveren?",
             "Nee, aan het ziekenhuis of op het parkeerterrein leveren we niet. We bezorgen alleen aan een woon- of verblijfadres waar je zelf aanwezig bent en je ID kunt tonen. Stuur je thuisadres door, dan komen we daar."],
            ["Hoe snel kan het als we vanavond spontaan besluiten te bestellen?",
             "In IJpelaar meestal binnen 20 tot 30 minuten na de bevestiging, ook ’s avonds laat. Heb je echt haast, kijk dan op <a href=\"/lachgas-spoedbezorging/\">lachgas spoedbezorging</a> wat we wel en niet kunnen toezeggen."],
        ],
        "nearby": ["brabantpark", "blauwe-kei", "bavel"],
        "lat": 51.579, "lon": 4.813,
    },
    {
        "slug": "heusdenhout",
        "name": "Heusdenhout",
        "kind": "wijk",
        "title": "Lachgas Heusdenhout | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Heusdenhout? Bezorgd aan huis rond winkelcentrum Bisschopshoeve en de Heusdenhoutseweg, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Heusdenhout",
        "lead": "Bezorging aan de deur in Heusdenhout, de oostelijke wijk van Breda tegen de A27. Bestel via WhatsApp, meestal binnen 20 tot 30 minuten geleverd.",
        "intro": [
            "Heusdenhout is de meest oostelijke woonwijk van Breda, tussen de Heerbaan en de A27, met Brabantpark als buur aan de westkant en Teteringen verder naar het noorden. Ooit was het een buurtschap met een eeuwenoude kapel; nu is het een ruime naoorlogse wijk met winkelcentrum Bisschopshoeve als middelpunt en de Heusdenhoutseweg als oude dorpsas. Wij bezorgen in heel Heusdenhout, van de Tilburgseweg aan de zuidkant tot de noordrand van de wijk. Een WhatsApp-bericht met je bestelling en adres is genoeg: wij bevestigen de prijs en laten weten hoe laat je de bezorger kunt verwachten.",
            "Onze bezorgers rijden vanuit het centrum via de Claudius Prinsenlaan en de Heerbaan naar Heusdenhout, een rit van enkele minuten, en wie vanaf de A27 komt, is via de oostkant van de stad net zo snel binnen. Daardoor halen we hier meestal 20 tot 30 minuten, ook als het in de binnenstad druk is. De wijk heeft brede straten en veel eengezinswoningen met een eigen voordeur, wat de overdracht eenvoudig maakt. In de flats rond Bisschopshoeve vragen we je de verdieping en het belnummer te noemen. Per bus is de wijk goed verbonden met het station en het centrum.",
            "Een verjaardag in een rijtjeshuis bij Bisschopshoeve, een avond met collega’s in een flat aan de Heerbaan of een familieweekend in een vrijstaand huis aan de rand van de wijk: welk formaat past, hangt af van de groep. In ons <a href=\"/assortiment/\">assortiment</a> staan de lachgastank 2KG, 4KG en 10KG, naast crackers en slagroompatronen. De prijs bevestigen we vooraf via WhatsApp; betalen doe je bij levering, contant of via Tikkie, zoals uitgelegd op <a href=\"/betalen-bij-levering/\">betalen bij levering</a>. We leveren uitsluitend aan 18-plussers en controleren het identiteitsbewijs aan de deur. Zorg dat je zelf opendoet, want aan derden geven we niets af.",
        ],
        "wijken": "Bisschopshoeve, Heusdenhoutseweg, Heusdenhoutsestraat, Heerbaan, Tilburgseweg, Sint-Annakapel",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ligt Heusdenhout voor jullie te ver aan de rand van Breda?",
             "Nee, het is een gewone stadsrit. Via de Claudius Prinsenlaan en de Heerbaan zijn we er meestal binnen 20 tot 30 minuten, dezelfde indicatie als voor Brabantpark en de rest van de stad."],
            ["Kunnen jullie ook leveren aan een adres vlak bij de A27, aan de oostrand van de wijk?",
             "Ja, de hele wijk tot aan de snelweg hoort erbij. Zet bij een adres aan een doodlopende straat of een parkeerhof even een herkenningspunt in je bericht, dan rijdt de bezorger niet eerst verkeerd."],
            ["Wat is het verschil tussen een cracker en een kraan op de tank?",
             "Een cracker hoort bij losse patronen, een kraan of regulator bij een tank; het zijn verschillende hulpstukken voor verschillende producten. Wat je over de verschillen en de veiligheid moet weten, lees je in <a href=\"/lachgas-informatie/kraan-regulator-of-cracker/\">kraan, regulator of cracker</a>."],
        ],
        "nearby": ["brabantpark", "teteringen", "dorst"],
        "lat": 51.592, "lon": 4.818,
    },
    {
        "slug": "doornbos-linie",
        "name": "Doornbos-Linie",
        "kind": "wijk",
        "title": "Lachgas Doornbos-Linie | 20-30 min via WhatsApp",
        "description": "Lachgas bestellen in Doornbos-Linie? Bezorgd aan huis ten oosten van Belcrum en station Breda, meestal binnen 20 tot 30 minuten. Via WhatsApp, 18+.",
        "h1": "Lachgas Doornbos-Linie",
        "lead": "Lachgas aan de deur in Doornbos en de Linie, de wijk tussen Belcrum en de Hoge Vucht in Breda-Noord. Bestellen via WhatsApp, meestal binnen 20 tot 30 minuten.",
        "intro": [
            "Doornbos-Linie ligt ten noordoosten van het centrum van Breda, aan de overkant van het spoor, met Belcrum als buur aan de westkant en de Noordelijke Rondweg en de Hoge Vucht aan de noordkant. De wijk bestaat uit twee buurten, Doornbos rond de Doornboslaan en de Linie, met een mix van oudere straten, naoorlogse flats en nieuwere invullingen. Wij bezorgen in beide buurten. Je stuurt via WhatsApp door wat je wilt bestellen en op welk adres, wij bevestigen de prijs en laten weten wanneer de bezorger er ongeveer is, en daarna hoef je alleen nog open te doen.",
            "Vanuit de binnenstad is het een korte rit: langs het station en via de Terheijdenseweg of de Doornboslaan ben je zo in de wijk, en vanaf de Noordelijke Rondweg rijd je er vanuit het noorden direct in. Omdat de afstand tot het centrum klein is, hanteren we hier meestal 20 tot 30 minuten. Rond de spoorzone wordt gebouwd en veranderen routes af en toe; onze bezorgers kennen de omleidingen, maar noem bij nieuwbouw altijd de volledige straatnaam, want sommige straten staan nog niet in elke navigatie. Station Breda ligt op loopafstand, aan de kant van Belcrum.",
            "Een verjaardag in een flat aan de Doornboslaan, een avond met vrienden in een nieuwbouwappartement bij het spoor of een borrel in een oud huis in de Linie: kies het formaat dat bij de groep past. In ons <a href=\"/assortiment/\">assortiment</a> staan lachgastanks van 2KG, 4KG en 10KG, crackers en slagroompatronen. De prijs ligt vooraf vast via WhatsApp en je betaalt bij aflevering, contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar en ouder en vragen altijd om een geldig identiteitsbewijs. Wie na een avond in het centrum thuis verder gaat, leest vooraf best even <a href=\"/lachgas-informatie/lachgas-en-alcohol/\">lachgas en alcohol</a>.",
        ],
        "wijken": "Doornbos, Linie, Doornboslaan, Terheijdenseweg, Teteringsedijk, Noordelijke Rondweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ik woon in de Linie, vlak bij het spoor. Hoe vindt de bezorger mijn adres?",
             "Geef de volledige straatnaam en het huisnummer door en, bij een appartementencomplex, de naam van het gebouw en het belnummer. Bij nieuwe straten die nog niet in de navigatie staan, helpt een bekend punt in de buurt."],
            ["Rekenen jullie voor Doornbos-Linie dezelfde levertijd als voor Belcrum?",
             "Ja. Beide wijken liggen aan de noordkant van het station en worden vaak in één rit gecombineerd, dus ook hier geldt meestal 20 tot 30 minuten. De zones staan op <a href=\"/bezorgtijden-breda/\">bezorgtijden in Breda</a>."],
            ["Kan ik na het uitgaan in het centrum nog bij mij thuis in Doornbos laten bezorgen?",
             "Ja, we bezorgen tot diep in de nacht aan je woonadres; stuur het adres door zodra je onderweg bent, dan plannen we de rit. We leveren niet bij het station of op straat, alleen aan de deur na controle van je ID."],
        ],
        "nearby": ["belcrum", "hoge-vucht", "breda-centrum"],
        "lat": 51.602, "lon": 4.791,
    },
    {
        "slug": "westerpark",
        "name": "Westerpark",
        "kind": "wijk",
        "title": "Lachgas Westerpark | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Westerpark, Breda-West? Bezorgd aan huis tussen Tuinzigt en de A16, rond de Westerparklaan, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Westerpark",
        "lead": "Bezorging aan huis in Westerpark, aan de westrand van Breda. Via WhatsApp bestellen en meestal binnen 20 tot 30 minuten geleverd.",
        "intro": [
            "Westerpark is de woonwijk aan de westrand van Breda, tussen Tuinzigt en de A16, met de spoorlijn richting Roosendaal aan de noordkant en de Ettensebaan aan de zuidkant. De wijk is een van de jongere uitbreidingen aan deze kant van de stad en dankt haar naam aan het gelijknamige park; de Westerparklaan is de hoofdroute waarlangs de woonstraten liggen. Princenhage ligt aan de zuidkant, Tuinzigt aan de oostkant. Wij bezorgen in heel Westerpark. Stuur via WhatsApp wat je wilt bestellen en je adres; wij bevestigen de prijs en noemen een verwachte aankomsttijd, zodat je weet wanneer je moet opendoen.",
            "Vanuit het centrum rijden onze bezorgers via de Haagweg of de Tuinzigtlaan en de Ettensebaan naar Westerpark, een rit van enkele minuten; wie vanaf de A16 komt, is via de westkant net zo snel binnen. Daarom geldt hier dezelfde indicatie als in de rest van de stad: meestal binnen 20 tot 30 minuten. De wijk is ruim opgezet, met woonerven en doodlopende straten, en dat is tegelijk de enige valkuil: huisnummers zijn vanaf de doorgaande weg niet altijd zichtbaar. Noem daarom in je bericht de volledige straatnaam en, als je in een hof woont, waar de ingang zit of waar de bezorger kan parkeren.",
            "Een tuinfeest op een zomeravond, een verjaardag in een eengezinswoning bij het park of een avond met vrienden aan de Westerparklaan: je kiest het formaat dat past. Een <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> volstaat voor een klein gezelschap; voor meer mensen is de 4KG of 10KG logischer, en crackers en slagroompatronen leveren we op verzoek mee. Afrekenen doe je aan de deur, contant of via Tikkie, voor de prijs die we vooraf via WhatsApp hebben doorgegeven. We verkopen alleen aan 18-plussers en vragen om een geldig identiteitsbewijs. Wat we wel en niet doen en waarom, lees je op <a href=\"/over-ons/\">over ons</a>.",
        ],
        "wijken": "Westerpark, Westerparklaan, Ettensebaan, Lunetstraat, A16, spoorlijn richting Roosendaal",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Is Westerpark voor jullie nog Breda of al buiten de stad?",
             "Gewoon Breda: de wijk ligt binnen de A16 en hoort bij de stadszone met meestal 20 tot 30 minuten. Pas verder weg, richting Etten-Leur, rekenen we met een ruimere indicatie."],
            ["Mijn straat is een woonerf zonder doorgaand verkeer, hoe gaat dat?",
             "De bezorger parkeert aan het begin van het erf en loopt naar je deur; dat kost geen extra tijd. Zet in je bericht het huisnummer en eventueel een herkenbaar punt, zoals de ingang van het erf of een speelplek."],
            ["Bezorgen jullie in Westerpark ook op feestdagen en rond Oud en Nieuw?",
             "Ja, maar op die avonden is het druk en kan de indicatie oplopen; bestel dan ruim van tevoren, dan plannen we je adres in. Lees meer op <a href=\"/lachgas-feestdagen/\">lachgas op feestdagen</a>."],
        ],
        "nearby": ["tuinzigt", "princenhage", "haagse-beemden"],
        "lat": 51.593, "lon": 4.740,
    },
    {
        "slug": "haagpoort",
        "name": "Haagpoort",
        "kind": "wijk",
        "title": "Lachgas Haagpoort | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Haagpoort? Bezorgd aan huis net buiten de Tramsingel, aan de Haagweg en de Haagdijk, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Haagpoort",
        "lead": "Lachgas aan de deur in Haagpoort, de kleine wijk direct ten westen van het centrum van Breda. Via WhatsApp besteld, meestal binnen 20 tot 30 minuten gebracht.",
        "intro": [
            "Haagpoort is een compacte wijk direct ten westen van de Bredase binnenstad: je steekt vanaf de Haagdijk de Tramsingel over en je bent er. De naam verwijst naar de oude stadspoort aan de weg naar Princenhage, en de Haagweg is nog altijd de as van de wijk, met woningen, winkels en bedrijfjes. Rondom liggen straten met oudere stadshuizen en nieuwere appartementen, met Tuinzigt aan de noordkant en de Heuvel verder naar het westen. Wij bezorgen in heel Haagpoort. Een WhatsApp-bericht met je bestelling en adres volstaat; wij bevestigen de prijs en zeggen wanneer we er zijn.",
            "Voor onze bezorgers is Haagpoort een van de kortste ritten die er zijn: vanuit het centrum is het één oversteek van de singel, en vanaf de A16 brengt de Haagweg je via Princenhage en de Heuvel rechtstreeks de wijk in. Daardoor geldt hier, net als in de rest van de stad, meestal 20 tot 30 minuten. De straten zijn smal en parkeren is beperkt, dus de bezorger stopt kort en loopt het laatste stuk; woon je boven een winkel aan de Haagweg, beschrijf dan waar de deur van de bovenwoning zit. Station Breda is op een paar minuten fietsen.",
            "Een borrel in een bovenwoning aan de Haagweg, een verjaardag in een stadshuis in een van de zijstraten of een avond met vrienden in een nieuw appartement: in ons <a href=\"/assortiment/\">assortiment</a> vind je het formaat dat past, van de lachgastank 2KG tot de 10KG, met crackers en slagroompatronen erbij. Betalen doe je bij levering, contant of via Tikkie, tegen de prijs die vooraf via WhatsApp is bevestigd. We leveren uitsluitend aan 18-plussers en controleren het identiteitsbewijs bij elke overdracht. Benieuwd wat lachgas precies is en hoe het werkt? Lees dan eerst <a href=\"/lachgas-informatie/wat-is-lachgas/\">wat is lachgas</a>.",
        ],
        "wijken": "Haagweg, Tramsingel, Haagdijk, Oranjeboomstraat, Graaf Hendrik III-laan",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ik woon boven een zaak aan de Haagweg, hoe werkt de overdracht?",
             "De bezorger belt aan bij de deur van de bovenwoning en wacht tot je opendoet; geef in je bericht aan waar die deur zit als die niet aan de Haagweg zelf is. Je toont je ID en betaalt direct bij de overdracht."],
            ["Kunnen jullie ook aan een adres aan de Tramsingel of de Haagdijk leveren?",
             "Ja, de panden aan de Tramsingel en de Haagdijk rekenen we tot hetzelfde gebied als Haagpoort en het centrum, met dezelfde indicatie van meestal 20 tot 30 minuten. Geef gewoon je adres door."],
            ["Hoe zit het met de prijs, kan die bij de deur nog veranderen?",
             "Nee. Je krijgt de prijs vooraf in WhatsApp bevestigd en dat is wat je bij de deur betaalt, contant of via Tikkie. Alle antwoorden over betalen staan bij <a href=\"/veelgestelde-vragen/betalen/\">vragen over betalen</a>."],
        ],
        "nearby": ["breda-centrum", "tuinzigt", "heuvel"],
        "lat": 51.588, "lon": 4.765,
    },
    {
        "slug": "blauwe-kei",
        "name": "Blauwe Kei",
        "kind": "wijk",
        "title": "Lachgas Blauwe Kei | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in de Blauwe Kei? Bezorgd aan huis in Breda-Zuidoost, tussen Zandberg, het Ginneken en IJpelaar, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Blauwe Kei",
        "lead": "Lachgas aan de deur in de Blauwe Kei, de woonwijk ten zuiden van Zandberg in Breda. Bestellen via WhatsApp, meestal binnen 20 tot 30 minuten bezorgd.",
        "intro": [
            "De Blauwe Kei is een overzichtelijke woonwijk in het zuidoosten van Breda, ingeklemd tussen Zandberg aan de noordkant, het Ginneken aan de westkant en IJpelaar en Overakker aan de oostkant, op een paar minuten van het centrum. De wijk bestaat vooral uit eengezinswoningen en enkele flats en ligt vlak bij de Zuidelijke Rondweg, waardoor je er vanuit alle richtingen makkelijk komt. Wij bezorgen in de hele wijk. Stuur je bestelling en adres via WhatsApp, dan krijg je de prijs en een tijdsindicatie terug en komt de bezorger naar je deur.",
            "Vanuit het centrum rijden onze bezorgers via de Ginnekenweg of de Zandberglaan in enkele minuten naar de Blauwe Kei, en vanaf de A27 of de A16 is de wijk via de Zuidelijke Rondweg direct bereikbaar. Daardoor geldt hier dezelfde indicatie als in Zandberg en het Ginneken: meestal binnen 20 tot 30 minuten. De wijk is rustig en overzichtelijk, met rechte straten en huizen met een eigen voordeur, zodat de bezorger zelden hoeft te zoeken. Woon je in een van de flats, noem dan de verdieping en het belnummer, dan hoeft hij niet te bellen als hij er staat.",
            "Een verjaardag in een hoekwoning, een avond met vrienden in een flat aan de rand van de wijk of een familieborrel in de tuin: kies het formaat dat bij het gezelschap past. De <a href=\"/product/lachgas-tank-10kg/\">lachgastank 10KG</a> is bedoeld voor grotere groepen, de 2KG en 4KG voor kleinere; crackers en slagroompatronen leveren we desgewenst mee. De prijs bevestigen we vooraf via WhatsApp en je betaalt bij levering, contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar en ouder en willen bij de overdracht een geldig identiteitsbewijs zien. Heb je twijfels over je eigen gebruik of dat van iemand anders, kijk dan bij <a href=\"/lachgas-informatie/problematisch-lachgasgebruik-hulp/\">hulp bij problematisch lachgasgebruik</a>.",
        ],
        "wijken": "Franklin Rooseveltlaan, Allerheiligenweg, Zuidelijke Rondweg, rand van Zandberg, rand van het Ginneken, Overakker",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Waar ligt de Blauwe Kei precies? Ik ken alleen Zandberg en het Ginneken.",
             "De Blauwe Kei ligt tussen die twee wijken en IJpelaar in, vlak bij de Zuidelijke Rondweg. Twijfel je of je adres erbij hoort, stuur het dan gewoon door; de indicatie is in dit hele deel van de stad meestal 20 tot 30 minuten."],
            ["We gaan na het feest nog met de auto naar huis, waar moet ik op letten?",
             "Wie rijdt, gebruikt niet: lachgas en autorijden gaan niet samen en rijden onder invloed is strafbaar. Regel vooraf een nuchtere bestuurder of blijf slapen; de achtergrond lees je in <a href=\"/lachgas-informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>."],
            ["Hoe snel zijn jullie in de Blauwe Kei op een zaterdagavond?",
             "Meestal binnen 20 tot 30 minuten, net als in Zandberg en het Ginneken; bij uitgaansdrukte rond de Ginnekenmarkt kan het iets langer duren. Je krijgt bij de bevestiging altijd een actuele indicatie, zie ook <a href=\"/bezorgtijden-breda/\">bezorgtijden Breda</a>."],
        ],
        "nearby": ["zandberg", "ginneken", "ijpelaar"],
        "lat": 51.577, "lon": 4.799,
    },
]

HUBS = [
    {
        "slug": "west-brabant",
        "name": "West-Brabant",
        "title": "Lachgas bezorgen in West-Brabant | Lachgas Breda",
        "description": "Ons bezorggebied in West-Brabant: de wijken van Breda, de randgemeenten en de plaatsen tot Bergen op Zoom en Waalwijk, met de levertijd per zone. 18+.",
        "h1": "Lachgas bezorgen in West-Brabant",
        "lead": "Vanuit Breda bezorgen we lachgastanks in heel West-Brabant, van de singels tot Bergen op Zoom, Steenbergen en Waalwijk. De levertijd groeit mee met de afstand.",
        "intro": [
            "West-Brabant is het westelijke deel van Noord-Brabant, met Breda als grootste stad en Roosendaal en Bergen op Zoom als tweede en derde kern. Daartussen en daaromheen liggen tientallen dorpen: de kerkdorpen van de gemeente Breda, de randgemeenten Etten-Leur, Oosterhout en Drimmelen, de polderdorpen van Moerdijk en Steenbergen aan het Hollandsch Diep en het Volkerak, de Brabantse Wal bij Hoogerheide en, richting het oosten, de gemeenten rond Tilburg en Waalwijk. Vanuit onze basis in Breda rijden we naar al die plaatsen. Op deze pagina vind je het gebied per deelregio, met voor elke plaats een eigen pagina met buurten, route en lokale vragen.",
            "Hoe lang je wacht, hangt vooral af van de afstand tot Breda. In de stad zelf, inclusief Prinsenbeek, Teteringen, Bavel en Ulvenhout, staan we meestal binnen 20 tot 30 minuten voor de deur. Voor de directe buurgemeenten, zoals Etten-Leur, Oosterhout, Rijen, Zundert, Roosendaal en Made, rekenen we op meestal 25 tot 40 minuten: de rit gaat deels over provinciale wegen of de snelweg en soms door een dorpskern. Verder weg, in Bergen op Zoom, Steenbergen, Hoogerheide, Waalwijk, Kaatsheuvel, Tilburg, Goirle, Oisterwijk en Baarle-Nassau, geldt meestal 35 tot 50 minuten. Bij drukte of wegwerkzaamheden zeggen we dat vooraf, zodat je weet waar je aan toe bent.",
            "Bestellen werkt in de hele regio op dezelfde manier. Je stuurt via WhatsApp je adres en het formaat dat je wilt hebben; wij bevestigen de prijs en noemen een realistische aankomsttijd voor jouw plaats. Daarna komt de bezorger naar je deur, controleert je identiteitsbewijs en neemt de betaling aan, contant of via Tikkie. De stappen staan uitgewerkt op onze pagina <a href=\"/werkwijze/\">werkwijze</a>, en de formaten, van de lachgastank 2KG tot de 10KG met crackers en slagroompatronen, vind je in het <a href=\"/assortiment/\">assortiment</a>. We leveren uitsluitend aan personen van 18 jaar en ouder, alleen aan een woon- of verblijfadres en nergens op straat of op een evenemententerrein.",
        ],
        "groups": [
            {"h2": "Breda en wijken",
             "text": "Alle wijken van Breda plus de kerkdorpen Prinsenbeek, Teteringen, Bavel en Ulvenhout, meestal binnen 20 tot 30 minuten.",
             "slugs": ["breda-centrum", "belcrum", "doornbos-linie", "hoge-vucht", "haagse-beemden", "tuinzigt", "westerpark", "haagpoort", "heuvel", "princenhage", "boeimeer", "zandberg", "blauwe-kei", "ginneken", "ijpelaar", "brabantpark", "heusdenhout", "prinsenbeek", "teteringen", "bavel", "ulvenhout"]},
            {"h2": "Rondom Breda",
             "text": "De buurgemeenten direct rond de stad: Dorst meestal binnen 20 tot 30 minuten, Etten-Leur, Rijsbergen, Zundert, Chaam en Oosterhout meestal binnen 25 tot 40 minuten.",
             "slugs": ["etten-leur", "rijsbergen", "zundert", "chaam", "oosterhout", "dorst"]},
            {"h2": "Roosendaal, Bergen op Zoom en de westkant",
             "text": "Roosendaal, Oudenbosch, Hoeven en Sint Willebrord meestal binnen 25 tot 40 minuten; Wouw, Bergen op Zoom, Halsteren, Hoogerheide, Steenbergen en Dinteloord meestal binnen 35 tot 50 minuten.",
             "slugs": ["roosendaal", "oudenbosch", "hoeven", "sint-willebrord", "wouw", "bergen-op-zoom", "halsteren", "hoogerheide", "steenbergen", "dinteloord"]},
            {"h2": "Moerdijk en Drimmelen",
             "text": "De dorpen aan de noordkant: Terheijden meestal binnen 20 tot 30 minuten, Made, Raamsdonksveer en Klundert meestal binnen 25 tot 40 minuten, Fijnaart en Willemstad meestal binnen 35 tot 50 minuten.",
             "slugs": ["terheijden", "made", "raamsdonksveer", "klundert", "fijnaart", "willemstad"]},
            {"h2": "Richting Tilburg en Waalwijk",
             "text": "Gilze, Rijen en Dongen meestal binnen 25 tot 40 minuten; Tilburg, Goirle, Oisterwijk, Baarle-Nassau, Waalwijk en Kaatsheuvel meestal binnen 35 tot 50 minuten.",
             "slugs": ["gilze", "rijen", "dongen", "tilburg", "goirle", "oisterwijk", "baarle-nassau", "waalwijk", "kaatsheuvel"]},
        ],
        "faq": [
            ["Hoe weet ik in welke zone mijn woonplaats valt?",
             "Kijk hierboven bij de deelregio waar je plaats staat; daar staat de indicatie die wij ervoor hanteren. Op <a href=\"/bezorgtijden-breda/\">bezorgtijden Breda</a> staan de zones nog eens op een rij, en bij je bestelling noemen we altijd de actuele verwachting."],
            ["Bezorgen jullie ook in een dorp dat hier niet genoemd wordt?",
             "Ligt het tussen of vlak bij de genoemde plaatsen in West-Brabant, dan meestal wel. Stuur je adres via WhatsApp, dan hoor je direct of we kunnen komen en hoe lang het ongeveer duurt."],
            ["Is bezorgen in Bergen op Zoom of Waalwijk net zo snel als in Breda?",
             "Nee, dat zijn ritten van een half uur of meer over de A58, A27 of A59, dus daar rekenen we met meestal 35 tot 50 minuten. We plannen die ritten zorgvuldig en melden het vooraf als het op een drukke avond langer wordt."],
            ["Komen jullie ook ’s nachts naar de dorpen buiten Breda?",
             "In de randgemeenten vaak wel; voor plaatsen verder weg hangt het af van de planning van die nacht, dus vraag het gewoon via WhatsApp. Hoe nachtlevering werkt, staat op <a href=\"/lachgas-nachtbezorging/\">lachgas nachtbezorging</a>."],
            ["Bezorgen jullie ook net over de grens, in Essen of Hoogstraten?",
             "Nee, wij bezorgen uitsluitend op Nederlandse adressen; Zundert, Baarle-Nassau en Hoogerheide zijn onze zuidelijkste plaatsen. Wat er in de grensstreek wel en niet kan en waar je in België terechtkunt, lees je op <a href=\"/lachgas-grensregio-belgie/\">lachgas in de grensregio met België</a>."],
        ],
    },
]
