# -*- coding: utf-8 -*-
# Herschreven bezorggebieden lachgasbreda.nl (fase 3): bestaande slugs, volledig nieuwe tekst.

AREAS = [
    {
        "slug": "belcrum",
        "name": "Belcrum",
        "kind": "wijk",
        "title": "Lachgas Belcrum | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Belcrum? Bezorgd aan de deur rond de Belcrumweg, de Speelhuislaan en het Havenkwartier, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Belcrum",
        "lead": "Bezorging aan huis in Belcrum, van de Speelhuislaan tot het Havenkwartier. Bestellen gaat via WhatsApp, meestal binnen 20 tot 30 minuten aan de deur.",
        "intro": [
            "Belcrum is de wijk direct ten noorden van station Breda, tussen het spoor en de Belcrumhaven. Het is een gebied in beweging: de oude arbeidersstraten rond de Belcrumweg, de Speelhuislaan en het Pastoor Pottersplein grenzen aan het Havenkwartier, waar fabriekshallen plaatsmaken voor woningen, horeca en ateliers. Wij bezorgen in de hele wijk, van de Konijnenberg aan de noordkant tot de Stationslaan achter het station. Je stuurt een WhatsApp-bericht met wat je wilt hebben en je adres, je krijgt de prijs en een tijdsindicatie terug, en daarna komt een bezorger naar je toe.",
            "Vanuit het centrum is Belcrum een korte rit: onder het spoor door via de Stationslaan of over de Terheijdenseweg en de Belcrumweg. Ook vanaf de Noordelijke Rondweg en de A16 is de wijk vlot te bereiken, waardoor de levertijd hier meestal binnen 20 tot 30 minuten blijft. Kom je zelf met het OV, dan stap je uit aan de noordzijde van station Breda en sta je binnen een paar minuten in de wijk. Op drukke avonden kan het rond het station even vol staan; houd daar bij je bestelling rekening mee, we noemen vooraf altijd een realistische verwachting.",
            "Of het nu gaat om een borrel in een nieuw appartement aan de Belcrumhaven, een avond in een van de oude huizen rond de Speelhuislaan of een bijeenkomst in het Havenkwartier: je kiest zelf het formaat dat past. In ons <a href=\"/assortiment/\">assortiment</a> vind je lachgastanks van 2KG, 4KG en 10KG, plus crackers en slagroompatronen. Betalen doe je bij aflevering, contant of via Tikkie, en de prijs is vooraf via WhatsApp bevestigd. We leveren uitsluitend aan personen van 18 jaar en ouder en vragen om een geldig identiteitsbewijs. Lees voor je bestelt ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Belcrumweg, Speelhuislaan, Pastoor Pottersplein, Belcrumhaven, Havenkwartier, Konijnenberg, Stationslaan, Veilingkade",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook aan de nieuwe appartementen in het Havenkwartier?",
             "Ja. In de nieuwbouw rond de Belcrumhaven zijn de ingangen niet altijd direct te vinden, dus zet in je bericht de naam van het complex, de verdieping en het nummer van de bel. De bezorger meldt zich bij de hoofdingang en belt aan; wij laten niets onbeheerd achter."],
            ["Ik sta aan de achterkant van station Breda, kan ik daar iets ophalen?",
             "Nee, we hebben geen afhaalpunt en leveren alleen aan een woon- of verblijfadres in Belcrum. Een overdracht op straat of op het stationsplein doen we niet. Geef een adres door waar je zelf aanwezig bent, dan komt de bezorger daar naartoe."],
            ["Hoe snel zijn jullie in Belcrum op een vrijdagavond?",
             "Belcrum ligt dicht bij het centrum, dus meestal zijn we er binnen 20 tot 30 minuten. Bij drukte rond het station of aan het begin van de avond kan het iets langer duren; je ontvangt bij je bestelling altijd een indicatie via WhatsApp. Bekijk ook onze <a href=\"/bezorgtijden-breda/\">bezorgtijden per zone</a>."],
        ],
        "nearby": ["breda-centrum", "doornbos-linie", "tuinzigt"],
        "lat": 51.601, "lon": 4.776,
    },
    {
        "slug": "brabantpark",
        "name": "Brabantpark",
        "kind": "wijk",
        "title": "Lachgas Brabantpark | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Brabantpark? Bezorgd rond het Brabantplein, de Hogeschoollaan en de Molengracht, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Brabantpark",
        "lead": "Aan huis bezorgd in Brabantpark, van het Brabantplein tot de Heerbaan. Bestel via WhatsApp en reken op meestal 20 tot 30 minuten.",
        "intro": [
            "Brabantpark ligt aan de oostkant van Breda, tussen de Claudius Prinsenlaan en de Heerbaan, met Heusdenhout als buur. Het hart van de wijk is het Brabantplein met zijn winkels, en rond de Hogeschoollaan en de Lovensdijkstraat staan de gebouwen van Avans Hogeschool; de campus van BUas aan de Mgr. Hopmansstraat ligt op loopafstand. Daardoor wonen hier veel studenten naast gezinnen die er al jaren zitten. Wij bezorgen in de hele wijk, tot aan de Molengracht en de Beverweg. Een bericht via WhatsApp met je bestelling en adres is voldoende; je krijgt de prijs en een verwachte aankomsttijd terug.",
            "Vanuit de binnenstad rijd je via de Claudius Prinsenlaan zo Brabantpark in; het is een van de kortste ritten die we maken, en daarom ligt de levertijd meestal binnen 20 tot 30 minuten. Vanaf de A27 is de wijk via de Heerbaan te bereiken. Met de bus stap je uit op de Claudius Prinsenlaan of bij het Brabantplein. Rond de studentencomplexen aan de Hogeschoollaan kan parkeren even zoeken zijn, dus een huisnummer met een duidelijke ingang scheelt tijd voor onze bezorger. Woon je in een flat, noem dan ook de verdieping en het belnummer.",
            "Een huisfeest in een studentenhuis bij de Hogeschoollaan, een verjaardag aan de Sint-Ignatiusstraat of een avond met vrienden achter het Brabantplein: voor een paar mensen is een <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> vaak genoeg, voor een grotere groep kies je een 4KG of 10KG. Crackers en slagroompatronen leveren we erbij. Je betaalt bij de deur, contant of via Tikkie, tegen de prijs die vooraf via WhatsApp is bevestigd. Wij leveren alleen aan 18-plussers en controleren je identiteitsbewijs, ook in studentenhuizen. Informatie over verantwoord omgaan met lachgas vind je bij <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Brabantplein, Hogeschoollaan, Lovensdijkstraat, Claudius Prinsenlaan, Beverweg, Heerbaan, Molengracht, Sint-Ignatiusstraat, Epelenberg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Kunnen jullie bezorgen aan een studentenhuis in Brabantpark?",
             "Ja, dat doen we regelmatig. De besteller moet zelf aanwezig zijn, 18 jaar of ouder zijn en een geldig ID kunnen tonen; we geven niets aan huisgenoten die daar niet aan voldoen. Wat je verder moet weten staat op <a href=\"/lachgas-studenten-breda/\">lachgas voor studenten in Breda</a>."],
            ["Ik woon aan de Molengracht, vlak bij het Amphia. Is dat nog Brabantpark voor jullie?",
             "Voor de levertijd maakt het geen verschil: de straten rond het Amphia aan de Molengracht rekenen we tot hetzelfde gebied als de rest van Brabantpark en Heusdenhout. Geef je adres door en we zijn er meestal binnen 20 tot 30 minuten."],
            ["Welke tank past bij een avond met een klein gezelschap?",
             "Voor een kleine groep is de 2KG-tank meestal passend; bij meer mensen of een langere avond is de 4KG praktischer. Twijfel je, stuur dan een berichtje met het aantal gasten, dan adviseren we zonder dat je meer neemt dan nodig. Een vergelijking staat in onze <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">keuzehulp</a>."],
        ],
        "nearby": ["heusdenhout", "zandberg", "ijpelaar"],
        "lat": 51.590, "lon": 4.800,
    },
    {
        "slug": "breda-centrum",
        "name": "Breda Centrum",
        "kind": "wijk",
        "title": "Lachgas Breda Centrum | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Breda Centrum? Bezorgd binnen de singels, van de Grote Markt tot Chassé Park en station, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Breda Centrum",
        "lead": "Bezorging in de binnenstad van Breda: Grote Markt, Haven, Chassé Park en de straten rond het station. Via WhatsApp besteld, meestal binnen 20 tot 30 minuten.",
        "intro": [
            "Het centrum van Breda is het gebied binnen de singels: van de Grote Markt en de Grote Kerk via de Havermarkt en de Haven naar het Valkenberg en het Stationskwartier, en aan de zuidkant het Chassé Park met zijn appartementen en het theater. Daartussen liggen de winkelstraten rond de Ginnekenstraat en de Veemarktstraat, de woonstraten bij de Boschstraat en het Begijnhof, en de nieuwe kades langs de Nieuwe Mark. Wij bezorgen in dit hele gebied. Je stuurt via WhatsApp je bestelling en adres, krijgt de prijs bevestigd en hoort meteen hoe laat je ons kunt verwachten.",
            "In de binnenstad is afstand niet het probleem, maar de route wel: veel straten zijn autoluw of eenrichting, en de Grote Markt en de Havermarkt zijn voetgangersgebied. Onze bezorgers kennen de doorsteken via de Nassausingel, de Wilhelminasingel en de Markendaalseweg, zodat de levertijd meestal binnen 20 tot 30 minuten blijft. Woon je in een appartement boven een winkel of in een van de torens bij het Chassé Park, zet dan de ingang en de verdieping in je bericht. Station Breda ligt aan de noordrand, dus ook wie met de trein thuiskomt kan onderweg al bestellen.",
            "Een verjaardag in een bovenwoning aan de Boschstraat, een etentje met vrienden aan de Haven of een avond in een appartement aan de Nieuwe Prinsenkade: kies het formaat dat bij je gezelschap past. De tanks van 2KG, 4KG en 10KG staan met crackers en slagroompatronen in ons <a href=\"/assortiment/\">assortiment</a>. De prijs wordt vooraf via WhatsApp bevestigd en je betaalt bij aflevering, contant of via Tikkie. We verkopen uitsluitend aan 18-plussers en vragen om een ID. Houd er rekening mee dat voor de openbare ruimte in Breda aparte regels gelden; lees daarover meer in <a href=\"/lachgas-informatie/lachgas-regels-breda/\">lachgas en de regels in Breda</a>.",
        ],
        "wijken": "Grote Markt, Havermarkt, Haven, Valkenberg, Chassé Park, Stationskwartier, Ginnekenstraat, Begijnhof, Nieuwe Mark, Boschstraat",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Kunnen jullie bezorgen bij een café of op de Grote Markt?",
             "Nee. Wij leveren uitsluitend aan een woon- of verblijfadres, niet aan horeca, op terrassen of op straat. In de binnenstad gelden voor de openbare ruimte bovendien aparte regels. Ga je na het uitgaan bij iemand thuis verder, stuur dan dat adres door."],
            ["Ik woon in een appartement in het Chassé Park, hoe gaat de overdracht?",
             "De bezorger belt aan bij de hoofdingang en komt naar je deur of ontmoet je in de hal, zoals jij aangeeft. Vermeld de naam van het gebouw, de verdieping en het belnummer in je bericht, dan hoeft hij niet te zoeken. Je toont je ID en betaalt ter plekke."],
            ["Hoe laat kan ik in het centrum nog bestellen?",
             "We bezorgen tot diep in de nacht, ook in het weekend wanneer de binnenstad druk is. Op die momenten kan de levertijd aan de bovenkant van de 20 tot 30 minuten zitten; je krijgt vooraf een eerlijke inschatting. Zie ook <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["belcrum", "zandberg", "boeimeer"],
        "lat": 51.589, "lon": 4.776,
    },
    {
        "slug": "etten-leur",
        "name": "Etten-Leur",
        "kind": "stad",
        "title": "Lachgas Etten-Leur | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Etten-Leur? Bezorging aan huis in Etten, de Leur en de wijken rond Schoenmakershoek, meestal binnen 25 tot 40 minuten. Alleen 18+.",
        "h1": "Lachgas Etten-Leur",
        "lead": "Bezorging in heel Etten-Leur, van het Winkelhart tot de Leur en Schoenmakershoek. Bestellen via WhatsApp, meestal binnen 25 tot 40 minuten geleverd.",
        "intro": [
            "Etten-Leur ligt tien kilometer ten westen van Breda en bestaat uit twee oude kernen die aan elkaar zijn gegroeid: Etten rond de Markt en het Van Bergenplein, en de Leur rond de Lange Brugstraat aan de noordkant. In het midden ligt het Winkelhart met de Nieuwe Nobelaer ernaast, en daaromheen de woonwijken Grauwe Polder, Hooghuis, Banakkers, Sanderbanken en het nieuwere Schoenmakershoek. Wij bezorgen in al deze delen, en ook op het bedrijventerrein Vosdonk als je daar werkt of een ruimte huurt. Bestellen doe je door een WhatsApp-bericht te sturen met je bestelling en adres.",
            "Vanuit Breda rijden onze bezorgers via de A58 of over de Liesboslaan door het Liesbos naar Etten-Leur; beide routes zijn kort, maar het zijn wel een paar kilometer meer dan binnen Breda. Daarom hanteren we hier meestal 25 tot 40 minuten, afhankelijk van het moment en het verkeer bij de afslag. Etten-Leur heeft een eigen station aan de lijn Breda–Roosendaal en het centrum ligt daar op loopafstand van. Woon je in Schoenmakershoek of aan de rand van de Leur, dan vermeld je het beste een herkenbaar punt; de nieuwbouw staat nog niet in iedere kaart even goed.",
            "Een feest in een tuin aan de Grauwe Polder, een verjaardag in Hooghuis of een avond met vrienden in een appartement bij het Winkelhart: je kiest de tank die past. Voor een klein gezelschap is 2KG gebruikelijk, voor meer mensen 4KG of 10KG; vergelijk ze op onze pagina <a href=\"/lachgas-informatie/welke-lachgastank-heb-ik-nodig/\">welke lachgastank heb ik nodig</a>. Crackers en slagroompatronen leveren we mee. De prijs wordt vooraf via WhatsApp bevestigd en je betaalt contant of via Tikkie bij aflevering, na controle van je ID. Wij leveren uitsluitend aan personen van 18 jaar en ouder en raden iedereen aan eerst <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> te lezen.",
        ],
        "wijken": "Winkelhart, Markt, Van Bergenplein, Lange Brugstraat, Nieuwe Nobelaer, Grauwe Polder, Hooghuis, Banakkers, Sanderbanken, Schoenmakershoek",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in de Leur en in Schoenmakershoek?",
             "Ja, we bezorgen in heel Etten-Leur, dus ook aan de noordkant rond de Lange Brugstraat en in de nieuwbouw van Schoenmakershoek. Zet bij nieuwe straten een herkenningspunt in je bericht, dan is de bezorger er zonder omwegen."],
            ["Waarom is de levertijd in Etten-Leur langer dan in Breda?",
             "Onze bezorgers vertrekken vanuit Breda en rijden via de A58 of de Liesboslaan naar Etten-Leur. Die extra kilometers maken het verschil met de Bredase wijken: hier rekenen we meestal op 25 tot 40 minuten. Bij je bestelling krijg je een concrete indicatie."],
            ["Kan ik ook op mijn werk op Vosdonk laten bezorgen?",
             "Dat kan, zolang je zelf op het adres aanwezig bent, 18 jaar of ouder bent en een geldig identiteitsbewijs laat zien. We leveren niet af bij een receptie of bij collega’s. Geef het bedrijfsadres en een bereikbare ingang door."],
        ],
        "nearby": ["princenhage", "rijsbergen", "hoeven"],
        "lat": 51.571, "lon": 4.636,
    },
    {
        "slug": "ginneken",
        "name": "Ginneken",
        "kind": "wijk",
        "title": "Lachgas Ginneken | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Ginneken? Bezorgd aan de deur rond de Ginnekenmarkt, de Ginnekenweg en de rand van het Mastbos, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Ginneken",
        "lead": "Thuisbezorging in het Ginneken, van de Ginnekenmarkt tot de Duivelsbruglaan en het Mastbos. Via WhatsApp besteld, meestal binnen 20 tot 30 minuten.",
        "intro": [
            "Het Ginneken was tot 1942 een eigen gemeente en dat voel je nog: de Ginnekenmarkt met de Laurentiuskerk, de Ginnekenweg met zijn winkels en cafés en de rustige lanen richting het Mastbos en kasteel Bouvigne hebben een dorps karakter midden in Breda. Aan de oostkant stroomt de Mark door het Markdal, aan de westkant ligt de Baronielaan met de brede herenhuizen, en naar het zuiden gaat de wijk over in Overakker en Ulvenhout. We bezorgen in het hele Ginneken. Een WhatsApp-bericht met bestelling en adres is genoeg om je bestelling in gang te zetten.",
            "Vanuit het centrum is het Ginneken via de Ginnekenweg of de Baronielaan een rit van een paar minuten, en vanaf de A27 kom je er via Ulvenhout en de Ulvenhoutselaan. Daardoor halen we hier meestal 20 tot 30 minuten, ook op een drukke zaterdagavond wanneer de terrassen aan de Ginnekenmarkt vol zitten. Buslijnen vanaf station Breda stoppen op de Ginnekenweg en de Duivelsbruglaan. In de lanen richting het Mastbos staan huizen vaak wat verder van de weg; een korte aanwijzing over de oprit of de voordeur helpt onze bezorger bij het vinden van het juiste adres.",
            "Een borrel in een herenhuis aan de Baronielaan, een tuinfeest aan de Ulvenhoutselaan of een verjaardag in een appartement boven de winkels aan de Ginnekenweg: kies het formaat dat past bij de avond. Een <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> is voor een middelgroot gezelschap een gangbare keuze; voor minder mensen is er 2KG, voor meer 10KG. Crackers en slagroompatronen leveren we erbij. Je betaalt bij de deur, contant of via Tikkie, en de prijs is al via WhatsApp bevestigd. Leveren doen we uitsluitend aan 18-plussers met een geldig ID; lees ook onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Ginnekenmarkt, Ginnekenweg, Laurentiuskerk, Duivelsbruglaan, Ulvenhoutselaan, Baronielaan, Markdal, Bouvigne, Mastbos, Overakker",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["We zitten met een groep in het Mastbos, kunnen jullie daar komen?",
             "Nee, in het bos, bij Bouvigne of op een parkeerplaats bezorgen we niet; dat is openbare ruimte en daar leveren we niet. We komen alleen aan een woon- of verblijfadres in het Ginneken waar de besteller zelf aanwezig is."],
            ["Hoe druk is het in het Ginneken op een weekendavond voor jullie?",
             "De Ginnekenmarkt en de Ginnekenweg zijn op vrijdag en zaterdag levendig, maar de aanrijroutes via de Baronielaan en de Duivelsbruglaan blijven goed rijdbaar. We halen hier meestal 20 tot 30 minuten; bij een drukke avond geven we dat vooraf aan via WhatsApp."],
            ["Wat doe ik met de lege tank na het weekend?",
             "Een lege tank hoort niet bij het huisvuil en ook niet in de glasbak of bij het oud ijzer op straat. Je kunt hem inleveren bij de milieustraat van Breda; hoe dat werkt lees je in <a href=\"/lachgas-informatie/lege-lachgastank-inleveren-breda/\">lege lachgastank inleveren in Breda</a>."],
        ],
        "nearby": ["ulvenhout", "zandberg", "blauwe-kei"],
        "lat": 51.573, "lon": 4.785,
    },
    {
        "slug": "haagse-beemden",
        "name": "Haagse Beemden",
        "kind": "wijk",
        "title": "Lachgas Haagse Beemden | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Haagse Beemden? Bezorging aan huis in Kesteren, Muizenberg, Kroeten, Burgst en bij Heksenwiel, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Haagse Beemden",
        "lead": "Bezorging in de hele Haagse Beemden, van winkelcentrum Heksenwiel tot Burgst en de Waterdonken. Bestel via WhatsApp, meestal binnen 20 tot 30 minuten.",
        "intro": [
            "De Haagse Beemden is de grootste wijk van Breda, gebouwd vanaf de jaren zeventig ten noorden van de Noordelijke Rondweg, tussen de A16 en de Mark. De wijk is opgedeeld in buurten met eigen namen: Kesteren, Muizenberg en Kroeten in het midden, Gageldonk en Kievitsloop aan de westkant, de Asterd en Overkroeten verder naar het noorden en de nieuwere Waterdonken aan de oostrand. Winkelen gebeurt bij Heksenwiel en De Donk, en het oude landgoed Burgst ligt er als groene kern middenin. Wij bezorgen in alle buurten; stuur je bestelling en adres via WhatsApp en je krijgt de prijs en een tijdsindicatie terug.",
            "Vanuit het centrum rijden onze bezorgers via de Noordelijke Rondweg en de Backer en Ruebweg naar de Westerhagelaan, de ringweg die de hele wijk ontsluit. De afstand is iets groter dan naar de wijken rond de singels, maar de doorstroming is goed, zodat we meestal binnen 20 tot 30 minuten aan de deur staan. Binnen de buurten is het netwerk van woonerven en hofjes wel een doolhof voor wie er niet woont. Noem daarom in je bericht altijd je volledige straatnaam en huisnummer en, als je in een hof woont, een herkenningspunt bij de ingang.",
            "Een verjaardag in een gezinswoning in Kesteren, een avond met buren in de Asterd of een feestje in een hoekwoning aan de Waterdonken: je bepaalt zelf het formaat. In ons <a href=\"/assortiment/\">assortiment</a> staan tanks van 2KG, 4KG en 10KG en daarnaast crackers en slagroompatronen. De prijs krijg je vooraf via WhatsApp bevestigd en je betaalt bij aflevering, contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar en ouder, met controle van het identiteitsbewijs aan de deur. Hoe je een tank thuis op een verantwoorde manier bewaart, lees je in <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">lachgastank bewaren en vervoeren</a>.",
        ],
        "wijken": "Heksenwiel, Kesteren, Muizenberg, Kroeten, Overkroeten, Asterd, Gageldonk, Kievitsloop, Burgst, Waterdonken",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["De bezorger vindt mijn hof niet, wat kan ik doen?",
             "Veel buurten in de Haagse Beemden bestaan uit hofjes die vanaf de doorgaande weg niet zichtbaar zijn. Geef in je bericht de naam van het hof, je huisnummer en eventueel de dichtstbijzijnde parkeerplaats op; als de bezorger onderweg is kun je via WhatsApp nog bijsturen."],
            ["Bezorgen jullie ook in de Waterdonken en aan de Asterd?",
             "Ja, de hele wijk valt in ons gebied, van de oudste buurten rond De Donk tot de nieuwbouw van de Waterdonken aan de Mark. Voor al die adressen geldt dezelfde indicatie van meestal 20 tot 30 minuten."],
            ["Mag ik de tank in de schuur of op het balkon bewaren?",
             "Zet een tank rechtop, buiten de zon en uit de buurt van warmtebronnen, en laat hem niet in een afgesloten auto staan. Een droge schuur is prima, een balkon in de volle zon niet. Uitgebreidere aanwijzingen staan in <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."],
        ],
        "nearby": ["prinsenbeek", "terheijden", "tuinzigt"],
        "lat": 51.613, "lon": 4.748,
    },
    {
        "slug": "heuvel",
        "name": "Heuvel",
        "kind": "wijk",
        "title": "Lachgas Heuvel | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Heuvel? Bezorgd rond het Heuvelplein, het Dr. Struyckenplein en de Heuvelbrink in Breda, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Heuvel",
        "lead": "Bezorging in de Bredase wijk Heuvel, van het Heuvelplein tot de Talmazone. Bestel via WhatsApp, meestal binnen 20 tot 30 minuten aan de deur.",
        "intro": [
            "De Heuvel is de naoorlogse wijk ten westen van het centrum, gebouwd in de jaren vijftig tussen de Haagweg en de Graaf Engelbertlaan, met Princenhage als buur aan de zuidwestkant en Boeimeer aan de oostkant. Het Heuvelplein en het Dr. Struyckenplein zijn de twee pleinen waar de winkels en de bushaltes zitten; daaromheen liggen portiekflats, rijtjeshuizen en de vernieuwde delen rond de Heuvelbrink en de Talmazone. Wij bezorgen in de hele wijk, tot aan het Mgr. Nolensplein. Stuur een bericht via WhatsApp met wat je wilt bestellen en je adres, en je krijgt de prijs en een tijdsindicatie terug.",
            "Vanuit de binnenstad is de Heuvel via de Haagweg of de Graaf Hendrik III-laan binnen een paar minuten bereikt, en vanaf de A16 kom je er via de Graaf Engelbertlaan. Het is een van de dichtstbijzijnde wijken voor ons, en daarom geldt hier meestal 20 tot 30 minuten. Bussen vanaf het station stoppen op de Haagweg en bij het Dr. Struyckenplein. Bij de portiekflats is het handig om te weten op welke verdieping je woont en welk nummer op de bel staat; dat voorkomt heen en weer bellen op het moment dat de bezorger voor de deur staat.",
            "Een verjaardag in een flat aan de Heuvelbrink, een feestje in een eengezinswoning bij het Mgr. Nolensplein of een avondje met vrienden rond het Heuvelplein: het formaat kies je zelf. Voor een paar mensen volstaat meestal een 2KG, voor een groter gezelschap kies je 4KG of de <a href=\"/product/lachgas-tank-10kg/\">lachgastank 10KG</a>; crackers en slagroompatronen leveren we mee. Je betaalt bij aflevering, contant of via Tikkie, tegen de via WhatsApp bevestigde prijs. Wij verkopen uitsluitend aan 18-plussers en vragen om een geldig identiteitsbewijs. Lees voor een avond zonder gedoe eerst onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Heuvelplein, Dr. Struyckenplein, Mgr. Nolensplein, Heuvelbrink, Heuvelstraat, Dr. Struyckenstraat, Talmazone, Haagweg, Graaf Engelbertlaan",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ik woon in een portiekflat bij het Dr. Struyckenplein, hoe werkt de bezorging?",
             "De bezorger belt aan bij jouw bel en komt naar de deur van je woning, of je komt zelf naar beneden als je dat liever hebt. Zet het belnummer en de verdieping in je bericht. Je laat je ID zien en betaalt direct bij de overdracht."],
            ["Is de levertijd in de Heuvel anders dan in Princenhage?",
             "Nee, voor de Heuvel en Princenhage hanteren we dezelfde indicatie van meestal 20 tot 30 minuten; beide wijken liggen aan dezelfde kant van de stad en worden vaak in één rit gecombineerd. Bekijk de indeling op <a href=\"/bezorgtijden-breda/\">bezorgtijden Breda</a>."],
            ["Kan ik ook alleen crackers of slagroompatronen bestellen?",
             "Ja, crackers en slagroompatronen bestel je los of in combinatie met een tank. Vermeld het gewoon in je bericht, dan nemen we het mee in de prijsbevestiging. Een overzicht staat op onze pagina <a href=\"/product/slagroompatronen/\">slagroompatronen</a>."],
        ],
        "nearby": ["princenhage", "boeimeer", "westerpark"],
        "lat": 51.583, "lon": 4.757,
    },
    {
        "slug": "oosterhout",
        "name": "Oosterhout",
        "kind": "stad",
        "title": "Lachgas Oosterhout | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Oosterhout? Bezorging aan huis rond de Heuvel, de Markt, Slotjes, Oosterheide en Dommelbergen, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas Oosterhout",
        "lead": "Thuisbezorging in Oosterhout, van de Heuvel en het Arendsplein tot Dommelbergen en Vrachelen. Besteld via WhatsApp, meestal binnen 25 tot 40 minuten.",
        "intro": [
            "Oosterhout ligt ten noordoosten van Breda, aan de A27 en het Wilhelminakanaal. Het centrum draait om de Heuvel, de langgerekte brink met horeca, en de Markt met de Sint-Jansbasiliek; het winkelgebied loopt door naar het Arendsplein en het vernieuwde Santrijngebied. Daaromheen liggen de woonwijken Slotjes en Oosterheide aan de zuidkant, Strijen en Dommelbergen in het noorden en Vrachelen aan de westkant richting Den Hout. Wij bezorgen in de hele stad en in de kerkdorpen Dorst en Den Hout. Een WhatsApp-bericht met je bestelling en adres is het begin; je krijgt direct de prijs en een verwachte aankomsttijd.",
            "Vanuit Breda zijn er twee logische routes: over de A27 tot de afslag Oosterhout, of binnendoor via Teteringen over de Oosterhoutseweg. Beide ritten duren een kwartier of iets meer, en dat is de reden dat we voor Oosterhout meestal 25 tot 40 minuten aanhouden in plaats van de Bredase tijden. Oosterhout heeft geen treinstation; het busstation bij het centrum verbindt de stad met Breda en Utrecht. Woon je in Vrachelen of Dommelbergen, dan ligt je adres aan de verre kant van de stad en zit je eerder aan de bovenkant van die indicatie, zeker op vrijdag- en zaterdagavond.",
            "Een huisfeest in Slotjes, een verjaardag in een gezinswoning in Oosterheide of een avond met vrienden in een appartement aan de Heuvel: je bestelt wat past bij je gezelschap. De drie tankformaten en de bijbehorende crackers en slagroompatronen vind je in ons <a href=\"/assortiment/\">assortiment</a>; voor een kleine groep is 2KG gebruikelijk, grotere avonden vragen om 4KG of 10KG. De prijs wordt vooraf via WhatsApp bevestigd, je betaalt bij aflevering contant of via Tikkie, en we controleren bij iedere levering het ID: uitsluitend 18 jaar en ouder. Lees voor je bestelt ook <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Heuvel, Markt, Arendsplein, Santrijngebied, Slotjes, Oosterheide, Strijen, Dommelbergen, Vrachelen, Weststad",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Den Hout en Dorst?",
             "Ja. Dorst en Den Hout horen bij de gemeente Oosterhout en liggen op onze route; voor Dorst, dat vlak bij Breda ligt, hebben we een <a href=\"/bezorggebied/dorst/\">eigen pagina</a> met een kortere indicatie. Voor Den Hout houden we dezelfde 25 tot 40 minuten aan als voor Oosterhout."],
            ["Komen jullie ook ’s avonds laat naar Oosterhout?",
             "We bezorgen tot in de late uren, ook buiten Breda. Omdat de rit over de A27 of via Teteringen wat langer is, vragen we je in Oosterhout iets eerder te bestellen dan je in Breda zou doen; we geven bij elke aanvraag meteen aan hoe laat we er kunnen zijn."],
            ["Wat als ik bij aankomst van de bezorger geen ID kan tonen?",
             "Dan kunnen we niet leveren, ook niet als iemand anders in huis wel een ID heeft. We verkopen uitsluitend aan de besteller zelf, 18 jaar of ouder, na controle van een geldig identiteitsbewijs. Leg je rijbewijs, ID-kaart of paspoort dus klaar; lees meer op <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole 18+</a>."],
        ],
        "nearby": ["teteringen", "dorst", "raamsdonksveer"],
        "lat": 51.645, "lon": 4.859,
    },
    {
        "slug": "princenhage",
        "name": "Princenhage",
        "kind": "wijk",
        "title": "Lachgas Princenhage | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Princenhage? Bezorging aan huis rond de Haagsemarkt, de Dreef en de Liesboslaan tot aan Effen, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Princenhage",
        "lead": "Bezorging in heel Princenhage, van de Haagsemarkt tot Heilaar en Effen. Bestellen via WhatsApp, meestal binnen 20 tot 30 minuten aan de deur.",
        "intro": [
            "Princenhage was tot 1942 een zelfstandige gemeente en is nog altijd een dorp in de stad: de Haagsemarkt met de Martinuskerk, de Dreef met zijn cafés en winkels en de smalle straatjes rond de Doelen vormen het hart. Aan de westkant ligt het Liesbos, aan de zuidkant het buurtschap Effen, en richting de A16 het bedrijventerrein Heilaar. De wijk ligt direct naast knooppunt Princeville, waar de A16 en de A58 samenkomen. Wij bezorgen in heel Princenhage, van de Haagweg tot Effen. Je stuurt via WhatsApp je bestelling en adres en krijgt de prijs en een tijdsindicatie terug.",
            "Vanuit het centrum rijd je via de Haagweg door Haagpoort en de Heuvel recht op de Haagsemarkt af, een rit van enkele minuten; vanaf de A16 en de A58 ben je via Princeville en de Liesboslaan net zo snel binnen. Daardoor halen we in Princenhage meestal 20 tot 30 minuten, net als in de andere wijken aan de westkant. De bus vanaf station Breda stopt op de Haagweg en de Dreef. Woon je aan de rand bij Effen of langs de Liesboslaan, geef dan een herkenbaar punt op; de huizen staan daar verder uit elkaar en de nummering springt soms.",
            "Een borrel in een jarendertighuis aan de Dreef, een tuinfeest in Effen of een avond met vrienden in een appartement bij de Haagsemarkt: kies het formaat dat erbij past. Een 2KG is geschikt voor een klein gezelschap, een 4KG of 10KG voor een groter; de verschillen staan in onze <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">keuzehulp 2KG, 4KG of 10KG</a>. Ook crackers en slagroompatronen bezorgen we. Je betaalt bij aflevering, contant of via Tikkie, tegen de vooraf via WhatsApp bevestigde prijs. Wij leveren uitsluitend aan 18-plussers en controleren het ID aan de deur. Meer achtergrond lees je bij <a href=\"/lachgas-informatie/wat-is-lachgas/\">wat is lachgas</a>.",
        ],
        "wijken": "Haagsemarkt, Dreef, Martinuskerk, Doelen, Haagweg, Liesboslaan, Liesbos, Heilaar, Effen, Princeville",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in Effen en langs de Liesboslaan?",
             "Ja, het buurtschap Effen en de huizen langs de Liesboslaan tot aan het Liesbos vallen onder Princenhage. De indicatie blijft meestal 20 tot 30 minuten; zet bij een afgelegen adres een herkenningspunt in je bericht."],
            ["Het is kermis of een feestweekend op de Haagsemarkt, kunnen jullie dan nog bij mij komen?",
             "Ja, maar bij evenementen rond de Haagsemarkt zijn straten soms afgesloten en rijden we om via de Dreef of de Haagweg. Dat kan een paar minuten kosten; we melden het vooraf. We bezorgen alleen aan een woonadres, niet op het feestterrein."],
            ["Hoe zit het met de regels rond lachgas in Nederland?",
             "Lachgas staat sinds 1 januari 2023 op lijst II van de Opiumwet, met uitzonderingen voor onder meer voedselbereiding en technische toepassingen. De actuele regels vind je op <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a>; wij leveren in elk geval uitsluitend aan 18-plussers en niet in de openbare ruimte."],
        ],
        "nearby": ["heuvel", "westerpark", "etten-leur"],
        "lat": 51.578, "lon": 4.738,
    },
    {
        "slug": "prinsenbeek",
        "name": "Prinsenbeek",
        "kind": "dorp",
        "title": "Lachgas Prinsenbeek | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Prinsenbeek? Bezorging rond de Markt, de Valdijk, Westrik en station Breda-Prinsenbeek, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Prinsenbeek",
        "lead": "Bezorging in heel Prinsenbeek, van de Markt tot Westrik en Overveld. Bestel via WhatsApp, meestal binnen 20 tot 30 minuten aan de deur.",
        "intro": [
            "Prinsenbeek is het dorp aan de noordwestkant van Breda, sinds 1997 onderdeel van de gemeente maar met een eigen gezicht. De Markt met de kerk en de terrassen is het centrum; de Valdijk, de Groenstraat en de Schoolstraat lopen er vanaf richting de polders en het buitengebied van Overveld. Aan de zuidoostkant ligt Westrik, met daarnaast station Breda-Prinsenbeek aan de spoorlijn naar Dordrecht. Wij bezorgen in het hele dorp en in het buitengebied. Een WhatsApp-bericht met je bestelling en adres is genoeg; je krijgt de prijs bevestigd en hoort hoe laat je ons kunt verwachten.",
            "Het dorp ligt direct ten westen van de A16 en de HSL, op een paar minuten rijden van de Haagse Beemden en Tuinzigt. Omdat de afstand tot het centrum klein is, hanteren we hier dezelfde indicatie als voor de Bredase wijken: meestal 20 tot 30 minuten. Met de trein ben je vanaf station Breda in een paar minuten op Breda-Prinsenbeek, en vandaar is het een korte wandeling naar de Markt. In het buitengebied rond Overveld liggen adressen verder uit elkaar; een huisnummer alleen is daar soms niet genoeg, dus beschrijf kort hoe de oprit te vinden is en of er een naambord staat.",
            "Een verjaardag in een vrijstaand huis aan de Groenstraat, een tuinfeest in Westrik of een avond met vrienden in een appartement aan de Markt: je kiest het formaat dat past. In ons <a href=\"/assortiment/\">assortiment</a> vind je tanks van 2KG, 4KG en 10KG, aangevuld met crackers en slagroompatronen. De prijs is vooraf via WhatsApp bevestigd en je betaalt bij aflevering, contant of via Tikkie. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen aan de deur om een geldig identiteitsbewijs. Rijd je zelf nog ergens naartoe, lees dan eerst <a href=\"/lachgas-informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>.",
        ],
        "wijken": "Markt, Valdijk, Groenstraat, Beeksestraat, Schoolstraat, Westrik, Overveld, Station Breda-Prinsenbeek",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in het buitengebied van Overveld?",
             "Ja, de polders en het buitengebied rond Prinsenbeek horen bij ons gebied. Omdat adressen daar ver uit elkaar liggen, vragen we je in je bericht aan te geven aan welke kant van de weg de oprit zit of welk herkenningspunt de bezorger kan gebruiken."],
            ["Is Prinsenbeek voor jullie een dorp buiten Breda met een langere levertijd?",
             "Nee. Prinsenbeek hoort sinds 1997 bij de gemeente Breda en ligt vlak achter de A16, dus we rekenen hier met dezelfde indicatie als in de Bredase wijken: meestal 20 tot 30 minuten. Alle zones staan op <a href=\"/bezorgtijden-breda/\">bezorgtijden Breda</a>."],
            ["Ik huur een weekend een huis in Prinsenbeek, kan ik daar laten bezorgen?",
             "Ja, een tijdelijk verblijfadres is prima, zolang jij als besteller zelf aanwezig bent en een geldig ID laat zien. We leveren niet op straat of bij een openbare gelegenheid. Meer over bestellen voor een feest lees je op <a href=\"/lachgas-feest-evenement/\">lachgas voor feest en evenement</a>."],
        ],
        "nearby": ["haagse-beemden", "terheijden", "princenhage"],
        "lat": 51.598, "lon": 4.711,
    },
    {
        "slug": "roosendaal",
        "name": "Roosendaal",
        "kind": "stad",
        "title": "Lachgas Roosendaal | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Roosendaal? Bezorging aan huis rond de Markt, het station, in Kroeven, Tolberg en Kortendijk, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas Roosendaal",
        "lead": "Thuisbezorging in Roosendaal, van de Nieuwe Markt tot Tolberg en Kortendijk. Besteld via WhatsApp, meestal binnen 25 tot 40 minuten geleverd.",
        "intro": [
            "Roosendaal is de grootste stad ten westen van Breda, een spoorwegknooppunt op de lijn naar Antwerpen met een compact centrum rond de Markt, de Nieuwe Markt en winkelcentrum Roselaar. Bij het station wordt gebouwd aan Stadsoevers, aan de zuidrand ligt het outletcentrum Rosada, en daaromheen liggen de woonwijken Kroeven, Langdonk, Kortendijk en Tolberg in het zuiden en westen, Kalsdonk en Burgerhout in het noorden en oosten. Wij bezorgen in de hele stad, inclusief de bedrijventerreinen Majoppeveld en Borchwerf als je daar aanwezig bent. Je stuurt je bestelling en adres via WhatsApp en krijgt de prijs en een tijdsindicatie terug.",
            "Vanuit Breda is Roosendaal een rit van ruim twintig minuten over de A58, die aan de zuidkant langs de stad loopt. Het is een van de verste bestemmingen die we vanuit Breda bedienen, en daarom rekenen we hier meestal op 25 tot 40 minuten; op een drukke avond kan het aan de bovenkant daarvan uitkomen. Station Roosendaal is een intercitystation met directe treinen naar Breda, Vlissingen en Antwerpen, en het centrum ligt er direct naast. Woon je in Kalsdonk of Burgerhout aan de noord- of oostkant, reken dan iets ruimer dan iemand die vlak bij de afslag woont.",
            "Een huisfeest in Kroeven, een verjaardag in een nieuwbouwappartement aan Stadsoevers of een avond met vrienden in Burgerhout: je bestelt het formaat dat bij je gezelschap past. Een <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> is voor een kleine groep gangbaar, voor meer mensen is er 4KG of 10KG, en crackers en slagroompatronen bezorgen we erbij. De prijs wordt vooraf via WhatsApp bevestigd, je betaalt bij aflevering contant of via Tikkie, en we controleren het ID: uitsluitend 18 jaar en ouder. Wie meer wil weten over werking en risico’s leest eerst <a href=\"/lachgas-informatie/wat-is-lachgas/\">wat is lachgas</a>.",
        ],
        "wijken": "Markt, Nieuwe Markt, Roselaar, Station Roosendaal, Stadsoevers, Rosada, Kroeven, Langdonk, Kortendijk, Tolberg",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Wouw, Nispen of Heerle?",
             "Wouw heeft een <a href=\"/bezorggebied/wouw/\">eigen pagina</a> met een ruimere indicatie. Voor Nispen, Heerle, Moerstraten en Wouwse Plantage kun je het beste even via WhatsApp vragen of het die avond past; die kerkdorpen liggen buiten de stad en we plannen ze alleen in als de route het toelaat."],
            ["Ik woon vlak bij Rosada, aan de zuidkant. Maakt dat uit voor de levertijd?",
             "Nauwelijks. De A58 loopt aan de zuidkant langs Roosendaal, dus de buurten bij Rosada en Tolberg zijn vanuit Breda juist snel bereikt. Voor de hele stad geldt meestal 25 tot 40 minuten; bij je bestelling noemen we een concrete verwachting."],
            ["Kan ik na een avond uit in het centrum nog bestellen?",
             "Ja, we bezorgen ook laat op de avond en in de nacht in Roosendaal, maar alleen aan een woon- of verblijfadres, niet bij horeca of op de Markt. Omdat de rit vanuit Breda langer is, loont het om vóór het einde van je avond te bestellen; zie <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["wouw", "oudenbosch", "bergen-op-zoom"],
        "lat": 51.531, "lon": 4.465,
    },
    {
        "slug": "tilburg",
        "name": "Tilburg",
        "kind": "stad",
        "title": "Lachgas Tilburg | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Tilburg? Bezorging in de Spoorzone, rond de Piushaven, in de Reeshof en bij de universiteit, meestal binnen 35 tot 50 minuten. 18+.",
        "h1": "Lachgas Tilburg",
        "lead": "Thuisbezorging in Tilburg, van de Spoorzone en de Piushaven tot de Reeshof en Stappegoor. Besteld via WhatsApp, meestal binnen 35 tot 50 minuten.",
        "intro": [
            "Tilburg is na Eindhoven de grootste stad van Brabant en ligt ruim twintig kilometer ten oosten van Breda, aan de A58 en het Wilhelminakanaal. Het centrum heeft de afgelopen jaren een nieuw gezicht gekregen met de Spoorzone rond de LocHal en de Koepelhal, terwijl de Heuvel, het Pieter Vreedeplein en de Piushaven de plekken zijn waar de stad uitgaat en woont. Daaromheen liggen oude volkswijken als Korvel, Theresia en Goirke, de universiteitsbuurt rond de Warandelaan en Stappegoor in het zuiden, en helemaal in het westen de Reeshof. Wij bezorgen in de hele stad. Een WhatsApp-bericht met bestelling en adres is genoeg.",
            "Van Breda naar Tilburg is het een halfuur rijden over de A58; via de afslagen aan de zuidkant en de Ringbaan West of Ringbaan Zuid komen we de stad in. Die afstand is de reden dat Tilburg onze ruimste indicatie krijgt: meestal 35 tot 50 minuten, en bij drukte eerder aan de bovenkant. Tilburg heeft drie stations, Centraal, Universiteit en Reeshof, allemaal met directe treinen naar Breda. Omdat de rit lang is, combineren we bestellingen in Tilburg waar dat kan; bestel je vroeg op de avond, dan ben je bijna altijd sneller geholpen dan rond middernacht.",
            "Een huisfeest in een studentenhuis in Korvel, een verjaardag in een appartement aan de Piushaven of een avond met vrienden in een gezinswoning in de Reeshof: kies het formaat dat erbij past. Voor een grote groep is de <a href=\"/product/lachgas-tank-10kg/\">lachgastank 10KG</a> het praktischst; voor kleinere avonden zijn er 2KG en 4KG, en crackers en slagroompatronen leveren we mee. De prijs krijg je vooraf via WhatsApp bevestigd, je betaalt bij aflevering contant of via Tikkie, en we controleren het ID: uitsluitend 18 jaar en ouder, ook bij studentenhuizen. Lees voor je bestelt ook <a href=\"/lachgas-informatie/lachgas-en-alcohol/\">lachgas en alcohol</a>.",
        ],
        "wijken": "Spoorzone, Piushaven, Heuvel, Pieter Vreedeplein, Korvel, Theresia, Goirke, Oud-Noord, Reeshof, Stappegoor",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Berkel-Enschot en Udenhout?",
             "Berkel-Enschot ligt direct tegen Tilburg aan en nemen we mee met dezelfde indicatie van meestal 35 tot 50 minuten. Udenhout ligt verder naar het noorden; vraag daarvoor even via WhatsApp of het die avond in de route past."],
            ["Waarom is de levertijd in Tilburg zoveel langer dan in Breda?",
             "Onze bezorgers vertrekken vanuit Breda en de rit over de A58 naar Tilburg duurt al een halfuur voordat we de stad in zijn. Daarom houden we meestal 35 tot 50 minuten aan. Een overzicht van alle zones vind je op <a href=\"/bezorgtijden-breda/\">bezorgtijden Breda</a>."],
            ["Ik woon in een studentencomplex bij de universiteit, kan daar bezorgd worden?",
             "Ja, mits je zelf aan de deur komt, 18 jaar of ouder bent en een geldig ID laat zien; we geven niets af aan huisgenoten of bij een receptie. Geef het gebouw, de verdieping en het belnummer door. Zie ook onze pagina voor <a href=\"/lachgas-studenten-breda/\">studenten</a>."],
        ],
        "nearby": ["goirle", "oisterwijk", "rijen"],
        "lat": 51.560, "lon": 5.084,
    },
]
