# -*- coding: utf-8 -*-
# FAQ-thema's lachgasbreda.nl (fase 3): /veelgestelde-vragen/<slug>/

FAQ_TOPICS = [
    {
        "slug": "bestellen",
        "title": "Vragen over lachgas bestellen in Breda | Lachgas Breda",
        "description": "Hoe bestel je een lachgastank in Breda via WhatsApp, wat zet je in je bericht en hoe wordt de prijs bevestigd? Antwoorden op veelgestelde bestelvragen.",
        "h1": "Vragen over bestellen",
        "lead": "Alles over het plaatsen van een bestelling bij Lachgas Breda: van je eerste WhatsApp-bericht tot de bevestiging, voor Breda en de rest van West-Brabant.",
        "intro": [
            "Bestellen bij Lachgas Breda loopt volledig via WhatsApp. Je stuurt een bericht met wat je wilt hebben en waar het heen moet, wij reageren met een bevestiging en de prijs, en daarna gaat de bestelling de deur uit. Op deze pagina bundelen we de vragen die daarover binnenkomen, van het eerste bericht tot wijzigingen op het laatste moment. Vragen over levertijden en wijken staan onder <a href=\"/veelgestelde-vragen/bezorgen/\">bezorgen</a>, vragen over contant of Tikkie onder betalen. Bestellen kan uitsluitend als je 18 jaar of ouder bent.",
        ],
        "items": [
            ["Hoe plaats ik een bestelling bij Lachgas Breda?",
             "Je stuurt ons een WhatsApp-bericht met het gewenste product, het bezorgadres en het moment waarop je de levering wilt. Wij lezen mee, controleren of het adres binnen ons gebied valt en sturen een bevestiging terug. Pas als die bevestiging er is, staat je bestelling vast. Een uitgebreidere uitleg in drie stappen staat op de pagina <a href=\"/werkwijze/\">werkwijze</a>."],
            ["Welke gegevens hebben jullie nodig om mijn bestelling te verwerken?",
             "Naast het product en het aantal hebben we het volledige adres nodig, inclusief huisnummer, eventuele toevoeging en de naam die op de bel staat. Woon je in een flat in de Hoge Vucht of in een studentenhuis bij de Hogeschoollaan, vermeld dan ook de verdieping. Een telefoonnummer hebben we al via WhatsApp, dus dat hoef je niet apart te sturen."],
            ["Krijg ik vooraf te horen wat de bestelling kost?",
             "Ja, in de bevestiging via WhatsApp staat het totaalbedrag voor jouw bestelling, inclusief de bezorging naar jouw adres. Zo zijn er aan de deur geen verrassingen en weet je vooraf precies waar je aan toe bent. Prijzen staan bewust niet op de website, omdat ze per formaat en bezorgzone kunnen verschillen; vraag ze gerust op in je bericht."],
            ["Kan ik vooruit bestellen voor het weekend of voor een feest?",
             "Dat kan en voor drukke momenten raden we het aan. Geef in je bericht de dag en het tijdvak door, dan zetten we de bestelling alvast in de planning en bevestigen we die direct. Vooruit bestellen is vooral handig voor de 10KG tank, die we alleen in overleg leveren, en voor avonden waarop half Breda tegelijk iets wil laten bezorgen."],
            ["Kan ik tijdens carnaval gewoon bestellen?",
             "Tijdens carnaval, in Breda bekend als Kielegat, blijven we bezorgen, maar de drukte is dan groter dan op een normaal weekend en delen van de binnenstad zijn afgesloten voor verkeer. Bestel daarom bij voorkeur een dag van tevoren en geef een adres op waar de bezorger goed kan komen. Meer over onze aanpak in die dagen lees je op <a href=\"/lachgas-carnaval-breda/\">lachgas tijdens carnaval in Breda</a>."],
            ["Welk formaat tank moet ik kiezen?",
             "Dat hangt af van de grootte van je gezelschap en van hoe lang de avond duurt. De 2KG is het instapformaat voor een kleine groep, de 4KG past bij een groter huisfeest en de 10KG is bedoeld voor evenementen en horeca. Een nuchtere vergelijking van de drie formaten vind je in onze <a href=\"/lachgas-informatie/lachgastank-2kg-4kg-of-10kg/\">keuzehulp</a>."],
            ["Kan ik ook alleen crackers of slagroompatronen bestellen?",
             "Ja, crackers en slagroompatronen zijn los te bestellen en hoeven niet gecombineerd te worden met een tank. Zet in je bericht welk product en hoeveel doosjes je wilt, dan nemen we het op in de bevestiging. Het volledige aanbod staat op de pagina <a href=\"/assortiment/\">assortiment</a>."],
            ["Werkt bestellen ook zonder account of webshop?",
             "Ja, er is geen webshop en geen account. Je hele bestelling verloopt via het WhatsApp-gesprek dat je zelf begint, en dat gesprek is tegelijk je bevestiging en je bewijs van wat is afgesproken. Wij bewaren niet meer gegevens dan nodig is om te bezorgen; hoe we daarmee omgaan staat in onze <a href=\"/privacy/\">privacyverklaring</a>."],
            ["Ik heb me vergist in het formaat, kan dat nog worden aangepast?",
             "Stuur zo snel mogelijk een berichtje in hetzelfde WhatsApp-gesprek. Zolang de bezorger nog niet vertrokken is, wisselen we het product zonder gedoe en sturen we een nieuwe bevestiging. Is hij al onderweg, dan overleggen we of de wijziging bij de deur nog mogelijk is."],
            ["Kan ik bestellen voor iemand anders of voor een groep?",
             "Je kunt een bestelling plaatsen voor een adres waar je zelf niet bent, bijvoorbeeld voor vrienden in Tilburg of Oosterhout. Degene die de bestelling aanneemt, moet dan wel zelf 18 jaar of ouder zijn en dat kunnen aantonen. Geef in je bericht de naam van de ontvanger door, zodat de bezorger weet wie hij aan de deur mag verwachten."],
            ["Nemen jullie ook bestellingen aan van horeca, bedrijven of evenementen?",
             "Ja, voor een bedrijfsfeest, een festivalbar of een evenementenlocatie bespreken we de bestelling vooraf in een aparte afspraak, omdat de aantallen en de levermomenten dan anders liggen. Vermeld in je bericht om wat voor locatie en datum het gaat, dan nemen we het van daar over. Op <a href=\"/lachgas-feest-evenement/\">feest en evenement</a> staat hoe zo’n levering verloopt."],
            ["Kan ik ook via e-mail of het contactformulier bestellen?",
             "Bestellingen nemen we alleen via WhatsApp aan, omdat we daar direct kunnen bevestigen en vragen kunnen stellen over het adres. Het contactformulier en e-mail zijn bedoeld voor algemene vragen, klachten of zakelijke afspraken en worden minder snel gelezen. Via de pagina <a href=\"/contact/\">contact</a> kom je bij beide kanalen uit."],
        ],
        "related": ["bezorgen", "betalen"],
    },
    {
        "slug": "bezorgen",
        "title": "Vragen over lachgas bezorgen in Breda en West-Brabant",
        "description": "Levertijden per zone, welke wijken en plaatsen in West-Brabant we aandoen, hoe discreet de bezorger werkt en wat er gebeurt als je niet thuis bent.",
        "h1": "Vragen over bezorgen",
        "lead": "Van de Haagse Beemden tot Bergen op Zoom: hoe lang het meestal duurt, waar we komen en hoe de overdracht aan de deur verloopt.",
        "intro": [
            "Bezorgen is de kern van wat we doen en het onderwerp waar de meeste vragen over gaan. In Breda zelf rijden we meestal binnen 20 tot 30 minuten, in de gemeenten direct om de stad meestal binnen 25 tot 40 minuten en in de verder gelegen plaatsen van West-Brabant meestal binnen 35 tot 50 minuten. Hieronder leggen we uit hoe die zones werken, wat de bezorger aan de deur doet en wat je kunt verwachten op drukke avonden. Het complete overzicht per plaats vind je in het <a href=\"/bezorggebied/\">bezorggebied</a>.",
        ],
        "items": [
            ["Hoe snel is de bestelling in Breda bij mij?",
             "Binnen de stadsgrenzen van Breda, dus in wijken als Belcrum, Brabantpark, Tuinzigt, Zandberg en de Haagse Beemden, is een bestelling meestal binnen 20 tot 30 minuten bij je. Dat is een indicatie op basis van een normale avond; bij regen, files op de rondweg of een piek in bestellingen kan het iets langer duren. In de bevestiging noemen we altijd de verwachte tijd voor dat moment."],
            ["Welke plaatsen vallen onder de zone van 25 tot 40 minuten?",
             "Dat zijn de gemeenten die direct aan Breda grenzen of er vlak achter liggen: onder meer Oosterhout, Etten-Leur, Roosendaal, Rijen, Dongen, Zundert, Oudenbosch, Hoeven, Rijsbergen, Made, Raamsdonksveer, Chaam en Gilze. Daar duurt een levering meestal 25 tot 40 minuten, afhankelijk van de route over de A16, A27 of A58. Welke zone bij jouw plaats hoort, staat op de eigen pagina in het bezorggebied."],
            ["Komen jullie ook in Bergen op Zoom, Waalwijk of Baarle-Nassau?",
             "Ja, de buitenste ring van ons gebied loopt van Bergen op Zoom en Halsteren in het westen via Steenbergen, Dinteloord en Willemstad naar Waalwijk, Kaatsheuvel, Oisterwijk, Goirle en Tilburg aan de oostkant, en in het zuiden tot Hoogerheide en Baarle-Nassau. Omdat de afstand groter is, rekenen we daar meestal op 35 tot 50 minuten. De pagina <a href=\"/bezorggebied/west-brabant/\">West-Brabant</a> toont alle plaatsen per deelgebied."],
            ["Wat merken de buren van een levering?",
             "Weinig. De bezorger komt in een gewone auto zonder reclame en in neutrale kleding, en overhandigt de bestelling bij de voordeur zonder uitleg op straat. De tank zit in een onopvallende verpakking, zodat het eruitziet als iedere andere bezorging. Vragen beantwoorden we via WhatsApp en niet hardop in het portiek."],
            ["Wat gebeurt er als ik niet thuis ben als de bezorger aankomt?",
             "De bezorger stuurt een bericht zodra hij voor de deur staat en wacht een paar minuten. Reageer je niet, dan nemen we de bestelling weer mee; we laten een tank nooit onbeheerd achter bij een deur, in een schuur of bij de buren. Een nieuwe poging plannen we daarna in overleg, zodra je weer bereikbaar bent."],
            ["Bezorgen jullie op een studentenadres of een kamer in een groot pand?",
             "Ja, in Breda bezorgen we regelmatig aan studentenhuizen rond de Hogeschoollaan, in het Stationskwartier en in de binnenstad. Zorg dat de bezorger bij de juiste bel uitkomt en dat degene die opent zelf de bestelling aanneemt. Wat we daarbij van bewoners vragen, staat op de pagina <a href=\"/lachgas-studenten-breda/\">lachgas voor studenten in Breda</a>."],
            ["Kan ik ook ’s avonds laat of ’s nachts laten bezorgen?",
             "Ja, we rijden ook in de avond en in de nacht, met name in Breda zelf en de directe omgeving. Houd er rekening mee dat de levertijd dan iets ruimer kan zijn dan overdag en dat we bij een adres met veel buren extra stil te werk gaan. De tijdvakken en voorwaarden vind je op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
            ["Kan het sneller dan de normale levertijd als het echt dringend is?",
             "We kunnen een spoedlevering voorrang proberen te geven, maar alleen binnen Breda en zonder belofte over de exacte minuten. Zeg in je bericht dat het haast heeft, dan kijken we direct of er een bezorger in jouw buurt is. Op <a href=\"/lachgas-spoedbezorging/\">spoedbezorging</a> lees je wat wel en niet kan."],
            ["Bezorgen jullie op straat, in een park of bij een horecazaak?",
             "Nee. We leveren uitsluitend op een woonadres of op een vooraf afgesproken privé- of bedrijfslocatie waar de ontvanger ons kan binnenlaten. Een afspreekpunt op de Grote Markt, in het Valkenberg of voor een café is geen bezorgadres, ook niet tijdens evenementen."],
            ["Hoe weet ik wanneer de bezorger onderweg is?",
             "Na de bevestiging krijg je in hetzelfde WhatsApp-gesprek een bericht zodra de bezorger vertrekt, en nog een bericht als hij voor de deur staat. Tussendoor kun je altijd even vragen hoe laat het ongeveer wordt. Een live kaart met een rijdend icoontje hebben we niet; het contact loopt via de chat."],
            ["Wat als de bezorging door drukte of weer langer duurt?",
             "Op een vrijdagavond, tijdens Breda Live of bij winterweer kan het voorkomen dat we de indicatie niet halen. We laten dat zo snel mogelijk weten via WhatsApp met een nieuwe inschatting, en je kunt op dat moment kosteloos afzeggen als het je niet meer uitkomt. Op <a href=\"/bezorgtijden-breda/\">bezorgtijden in Breda</a> staan de zones en de momenten waarop het doorgaans druk is."],
            ["Tot waar loopt het bezorggebied in het zuiden, richting de grens?",
             "In het zuiden eindigt ons gebied bij de Nederlandse grens: Zundert, Rijsbergen, Baarle-Nassau, Chaam en Hoogerheide bezorgen we, de Belgische plaatsen aan de andere kant niet. Voor leveringen in België verwijzen we naar <a href=\"https://lachgasantwerpen.be\">lachgasantwerpen.be</a>, dat onder de Belgische regels werkt. Wat dat betekent als je vlak bij de grens woont, staat onder het thema regels."],
        ],
        "related": ["bestellen", "betalen", "regels"],
    },
    {
        "slug": "betalen",
        "title": "Vragen over betalen bij levering | Lachgas Breda",
        "description": "Contant of via Tikkie bij levering, geen vooruitbetaling en de prijs vooraf bevestigd via WhatsApp. Antwoorden op vragen over betalen bij Lachgas Breda.",
        "h1": "Vragen over betalen",
        "lead": "Bij Lachgas Breda betaal je pas als de bestelling voor je staat, contant of via Tikkie. Zo werkt dat in de praktijk.",
        "intro": [
            "Betalen houden we bewust simpel: je rekent af op het moment van levering, met contant geld of via een Tikkie die de bezorger stuurt. Vooruitbetalen hoeft niet en kan ook niet, en het bedrag dat je betaalt is altijd het bedrag dat eerder in de WhatsApp-bevestiging stond. Hieronder beantwoorden we de vragen die hierover binnenkomen, van gepast betalen tot wat er gebeurt als een betaalverzoek niet lukt. Hoe de afrekening aan de deur precies verloopt, staat ook op <a href=\"/betalen-bij-levering/\">betalen bij levering</a>.",
        ],
        "items": [
            ["Welke betaalmethoden accepteren jullie aan de deur?",
             "Twee: contant geld of een Tikkie-betaalverzoek dat de bezorger ter plekke stuurt. Pinnen met een betaalpas is niet mogelijk, omdat de bezorger geen pinapparaat bij zich heeft. Laat bij het bestellen weten welke methode je wilt gebruiken, dan is dat aan de deur al bekend."],
            ["Hoe werkt betalen via Tikkie precies?",
             "De bezorger stuurt bij de overdracht een Tikkie-link in het WhatsApp-gesprek, of laat je een QR-code scannen. Je opent de link, betaalt met iDEAL via je eigen bank-app en de bezorger ziet de bevestiging direct binnenkomen. Je hebt er geen Tikkie-account voor nodig; een bank-app op je telefoon is voldoende."],
            ["Kan ik vooraf overmaken zodat het aan de deur sneller gaat?",
             "Nee, we vragen nooit om een betaling voordat de bestelling is geleverd. Dat beschermt jou: je betaalt pas als de verzegelde tank daadwerkelijk voor je staat en je gecontroleerd hebt dat alles klopt. Krijg je toch een betaalverzoek voordat er iets is bezorgd, dan komt dat niet van ons."],
            ["Moet ik gepast betalen als ik contant afreken?",
             "Dat is prettig, maar niet verplicht. De bezorger heeft beperkt wisselgeld bij zich, dus met een groot biljet voor een kleine bestelling kan het even duren of lukt het niet. Twijfel je, kies dan voor Tikkie, dan speelt wisselgeld geen rol."],
            ["Wat als de Tikkie-betaling niet lukt door een storing?",
             "Dan wachten we een paar minuten en proberen we het nog een keer; soms is slecht mobiel bereik in een kelder of achterhuis de oorzaak. Blijft het haperen, dan kan contant betalen een uitkomst zijn als je dat bij de hand hebt. Lukt het echt niet, dan gaat de bestelling helaas weer mee terug en spreken we een nieuw moment af."],
            ["Zit de bezorging in het bedrag dat ik betaal?",
             "Ja, het totaal dat in de WhatsApp-bevestiging staat, is inclusief het bezorgen naar jouw adres. Voor plaatsen verder van Breda, zoals Bergen op Zoom of Waalwijk, kan dat totaal anders uitvallen dan voor een adres in de stad; dat zie je dan vooraf in de bevestiging. Aan de deur komen er geen toeslagen bij."],
            ["Krijg ik een bon of betaalbewijs?",
             "Bij een Tikkie-betaling heb je automatisch een bewijs in je bank-app en in het gesprek. Betaal je contant en wil je een bewijs, vraag dan bij het bestellen om een bevestiging achteraf in WhatsApp; die sturen we na de levering. Een papieren bon geven we niet mee."],
            ["Kan ik een factuur krijgen voor een zakelijke bestelling?",
             "Voor horeca en evenementen kan dat, mits je dit bij het plaatsen van de bestelling aangeeft en de bedrijfsgegevens doorgeeft. De betaling zelf blijft bij levering, contant of via Tikkie; we leveren niet op rekening. Voor particuliere bestellingen maken we geen facturen op."],
            ["Wie betaalt als ik voor een groep bestel?",
             "Degene die de bestelling aan de deur aanneemt, rekent af; het maakt niet uit of dat de besteller is of een huisgenoot. Spreek met je gezelschap dus vooraf af wie het bedrag voorschiet, of laat de Tikkie-link doorsturen naar wie betaalt. De bezorger splitst geen betalingen over meerdere personen."],
            ["Moet ik betalen als ik de bestelling weiger of de levering niet doorgaat?",
             "Nee. Betalen gebeurt alleen bij een geslaagde overdracht, dus als je de bestelling om een geldige reden niet aanneemt, bijvoorbeeld omdat de verzegeling niet intact is, betaal je niets. Ook als wij de levering moeten afbreken omdat niemand aan de deur 18 jaar of ouder blijkt, vindt er geen betaling plaats."],
            ["Veranderen jullie prijzen op drukke dagen zoals Oud en Nieuw?",
             "Het bedrag dat je betaalt, is altijd het bedrag uit de bevestiging die je vooraf hebt gekregen, ook tijdens Koningsdag of de jaarwisseling. Wat we niet doen, is onderweg bijstellen omdat het druk is. Vraag bij twijfel in je bericht om een bevestiging van het totaal voordat de bezorger vertrekt."],
        ],
        "related": ["bestellen", "bezorgen"],
    },
    {
        "slug": "veiligheid",
        "title": "Vragen over veiligheid en lachgas | Lachgas Breda",
        "description": "Hoe bewaar en vervoer je een lachgastank, welke risico's heeft lachgas voor je gezondheid en waar vind je hulp in Breda? Antwoorden op veiligheidsvragen.",
        "h1": "Vragen over veiligheid",
        "lead": "Een lachgastank is een drukhouder en lachgas is niet zonder risico. Hier staan de vragen over bewaren, gezondheid en hulp in Breda.",
        "intro": [
            "Veiligheid gaat bij lachgas over twee dingen: de tank als voorwerp en het gas als middel. Een tank staat onder hoge druk en vraagt om zorgvuldig bewaren en vervoeren; het gas zelf heeft effecten op je lichaam die bij vaker of veel gebruik serieus kunnen worden. Op deze pagina beantwoorden we de vragen die daarover gaan, zonder gebruiksaanwijzing en zonder het risico kleiner te maken dan het is. Voor achtergrond en onafhankelijke informatie verwijzen we naar <a href=\"https://www.drugsinfo.nl\">drugsinfo.nl</a>.",
        ],
        "items": [
            ["Hoe bewaar ik een tank in huis op een veilige manier?",
             "Rechtop, op een koele en droge plek, uit de zon en weg van verwarming, kachel of open vuur. Een berging of een kast op de begane grond is beter dan een vensterbank of een warme auto. Zorg dat kinderen er niet bij kunnen en laat de kraan gesloten als de tank niet in gebruik is; meer details staan op <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."],
            ["Mag een tank in de kofferbak als ik hem meeneem naar een ander adres?",
             "Vervoer de tank rechtop en goed vastgezet, zodat hij niet kan omrollen, en laat hem nooit achter in een auto die in de zon staat; de druk in de cilinder loopt dan op. Houd de rit kort en zet de tank niet in een afgesloten ruimte samen met passagiers zonder dat er ventilatie is. Is de kraan of de aansluiting beschadigd, laat de tank dan staan en neem contact met ons op."],
            ["Hoe weet ik dat de tank die ik krijg in orde is?",
             "Elke tank leveren we verzegeld en met een onbeschadigde kraan en aansluiting. Controleer bij de overdracht of de verzegeling intact is, of er geen deuken of roest op de cilinder zitten en of je geen sissend geluid hoort. Is er iets niet in orde, neem de tank dan niet aan; de bezorger neemt hem mee terug."],
            ["Kan lachgas uit een tank vrieswonden veroorzaken?",
             "Ja. Gas dat onder druk uit een tank of cracker vrijkomt, is extreem koud en kan huid, lippen en luchtwegen bevriezen. Neem daarom nooit gas rechtstreeks uit de kraan of uit het apparaat en stop direct als metaal wit uitslaat of aan je huid plakt. Bij een vrieswond: voorzichtig opwarmen met lauw water en bij blaren of gevoelloosheid een arts raadplegen."],
            ["Wat zijn de risico’s van lachgas voor mijn gezondheid?",
             "Op korte termijn: duizeligheid, hoofdpijn, misselijkheid en vallen door evenwichtsverlies, met kans op letsel. Bij regelmatig gebruik blokkeert lachgas de werking van vitamine B12, wat kan leiden tot tintelingen, gevoelloosheid en zenuwschade die niet altijd herstelt. Een uitgebreide uitleg staat in ons artikel over <a href=\"/lachgas-informatie/lachgas-en-vitamine-b12/\">lachgas en vitamine B12</a>."],
            ["Is lachgas in combinatie met alcohol extra riskant?",
             "Ja. Alcohol en lachgas versterken elkaars effect op evenwicht, reactievermogen en bewustzijn, waardoor de kans op flauwvallen, vallen en verslikken bij braken groter wordt. Hoe de combinatie precies werkt en waarom we die afraden, lees je in <a href=\"/lachgas-informatie/lachgas-en-alcohol/\">lachgas en alcohol</a>."],
            ["Wanneer moet ik 112 bellen?",
             "Als iemand niet meer reageert op aanspreken, blauw of grauw kleurt, moeite heeft met ademen, een epileptische aanval krijgt of langer dan een paar minuten verward blijft. Leg de persoon op de zij, zorg voor frisse lucht en blijf erbij tot hulp er is; schaam je niet om hulpdiensten te bellen, zij zijn er niet om te oordelen. Minder acute klachten en de eerste stappen staan in <a href=\"/lachgas-informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>."],
            ["Zijn er mensen die lachgas beter helemaal kunnen vermijden?",
             "Ja. Wie zwanger is, een bestaand vitamine B12-tekort heeft, hart- of longklachten heeft of medicijnen gebruikt die het bewustzijn beïnvloeden, loopt extra risico. Ook jongeren onder de 18, aan wie we om die reden niet leveren, en mensen met eerdere tintelingen of gevoelloosheid na gebruik horen bij die groep. Bij twijfel is de huisarts de juiste plek voor advies."],
            ["Waar kan ik in Breda terecht als lachgasgebruik uit de hand loopt?",
             "Novadic-Kentron is de instelling voor verslavingszorg in Brabant en werkt ook in de regio Breda; je kunt daar zelf aankloppen of via de huisarts worden verwezen. Ook de huisarts zelf of de praktijkondersteuner is een laagdrempelige eerste stap, zeker als er lichamelijke klachten bij komen. Hoe je herkent dat gebruik problematisch wordt, staat in <a href=\"/lachgas-informatie/problematisch-lachgasgebruik-hulp/\">hulp bij problematisch lachgasgebruik</a>."],
            ["Wat doe ik met een tank die leeg is of die ik niet meer gebruik?",
             "Zet hem niet bij het restafval, in de glasbak of bij het oud ijzer in de wijk; er zit vaak nog restdruk in. Bewaar hem tot je gaat rechtop en met de kraan dicht, en breng hem naar de milieustraat van je gemeente, waar drukhouders apart worden ingenomen. De route in Breda beschrijven we op <a href=\"/lachgas-informatie/lege-lachgastank-inleveren-breda/\">lege lachgastank inleveren in Breda</a>."],
            ["Wat is het verschil in veiligheid tussen een kraan, een drukregelaar en een cracker?",
             "Een kraan geeft gas direct af en is daarmee het meest gevoelig voor bevriezing en te snel vrijkomend gas; een drukregelaar dempt dat, maar moet wel passen op de tank en onbeschadigd zijn. Een cracker werkt met kleine patronen en heeft een ander risico: scherpe randen en snel afkoelend metaal. Wat elk onderdeel doet en waar je op let, lees je in <a href=\"/lachgas-informatie/kraan-regulator-of-cracker/\">kraan, regulator of cracker</a>."],
            ["Is lachgas brandbaar of explosief?",
             "Lachgas zelf brandt niet, maar het is een oxidator: het laat andere stoffen feller branden en een tank kan bij sterke verhitting openbarsten. Houd een tank daarom weg van barbecue, vuurkorf, kachel en sigaretten en rook niet in de buurt van een open kraan. Een gevulde cilinder in een brandende ruimte is voor de brandweer een serieus gevaar; zeg het bij een brand als er een tank in huis staat."],
        ],
        "related": ["regels", "bezorgen"],
    },
    {
        "slug": "regels",
        "title": "Vragen over lachgas en de regels in Breda | Lachgas Breda",
        "description": "Opiumwet lijst II, de APV van Breda, leeftijdscontrole aan de deur en strengere regels over de grens in België: wat mag wel en niet rond lachgas?",
        "h1": "Vragen over regels",
        "lead": "Wat de Opiumwet, de gemeente Breda en onze eigen huisregels betekenen voor het bestellen en gebruiken van lachgas.",
        "intro": [
            "Sinds 1 januari 2023 staat lachgas op lijst II van de Opiumwet, met uitzonderingen voor onder meer medische, technische en voedingstoepassingen. Daarnaast heeft de gemeente Breda via de Algemene Plaatselijke Verordening mogelijkheden om gebruik in de openbare ruimte aan te pakken, en gelden er eigen regels in het verkeer en bij evenementen. Wij vatten hieronder samen wat dat betekent, voorzichtig geformuleerd en met verwijzing naar de officiële bronnen. Voor de volledige wettekst en toelichting is <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a> de juiste plek.",
        ],
        "items": [
            ["Wat betekent het dat lachgas op lijst II van de Opiumwet staat?",
             "Lijst II is de lijst van middelen die de wet als minder risicovol dan lijst I beschouwt, maar waarvoor bezit, verkoop en vervoer buiten de uitzonderingen toch verboden zijn. Voor lachgas gelden uitzonderingen voor onder meer medisch gebruik, technische toepassingen en gebruik als voedingsadditief, bijvoorbeeld in slagroompatronen. Hoe dat uitpakt voor consumenten lees je in <a href=\"/lachgas-informatie/is-lachgas-legaal-in-nederland/\">is lachgas legaal in Nederland</a>."],
            ["Wat zegt de APV van Breda over lachgas?",
             "De Algemene Plaatselijke Verordening van Breda geeft de gemeente ruimte om hinderlijk gebruik van lachgas in de openbare ruimte aan te pakken, bijvoorbeeld door gebieden aan te wijzen waar gebruik verboden is of door handhaving bij overlast. Welke bepalingen op dit moment gelden en voor welke plekken, verandert soms; raadpleeg daarvoor <a href=\"https://www.breda.nl\">breda.nl</a>. Een toelichting op de lokale situatie staat in ons artikel over lachgasregels in Breda."],
            ["Is lachgas gebruiken in de openbare ruimte van Breda toegestaan?",
             "Ga daar niet van uit. Op grond van de APV kan de gemeente gebruik in parken, op pleinen en rond uitgaansgebieden zoals de Grote Markt en de Havermarkt verbieden en daarop handhaven, en de politie kan daarnaast optreden op basis van de Opiumwet. Wat wij bezorgen, is bedoeld voor een privéadres en niet voor de straat."],
            ["Hoe controleren jullie of ik 18 jaar of ouder ben?",
             "De bezorger kan aan de deur om een geldig identiteitsbewijs vragen: paspoort, ID-kaart, rijbewijs of verblijfsdocument, geen foto op je telefoon. Zonder bewijs van leeftijd leveren we niet, ook niet als de besteller zelf wel 18 is maar de persoon aan de deur niet. Alles over de controle staat op <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole 18+</a>."],
            ["Is rijden onder invloed van lachgas strafbaar?",
             "Ja. De Wegenverkeerswet verbiedt rijden onder invloed van elke stof die de rijvaardigheid beïnvloedt, en lachgas valt daaronder; dat geldt voor auto, scooter en fiets. De politie kan je bij verdenking staande houden en een rijverbod of boete opleggen, en bij een ongeval weegt het zwaar mee. Lees meer op <a href=\"/lachgas-informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>."],
            ["Zijn de regels in België anders dan in Nederland?",
             "Ja, en strenger. In België is verkoop van lachgas aan minderjarigen landelijk verboden en hebben veel gemeenten, ook grensgemeenten als Hoogstraten, Essen en Kalmthout, bezit en gebruik in de openbare ruimte via een politiereglement verboden, met de mogelijkheid tanks in beslag te nemen. Een tank meenemen over de grens is dus geen goed idee; voor de Belgische situatie verwijzen we naar <a href=\"/lachgas-grensregio-belgie/\">lachgas in de grensregio</a>."],
            ["Mag ik lachgas doorverkopen aan vrienden of op een feest?",
             "Nee. Doorverkoop aan derden is op grond van de Opiumwet niet toegestaan; wat wij leveren, is bedoeld voor het adres en het gezelschap waarvoor je bestelt. Ook een tank delen tegen een bijdrage op een feest valt daaronder. Wil je iets voor een groep regelen, laat dan de organisator zelf bestellen en de levering aannemen."],
            ["Gelden er extra regels tijdens carnaval of grote evenementen?",
             "Ja. Tijdens Kielegat, Koningsdag en festivals op het Chasséveld geldt doorgaans een evenementenvergunning met eigen voorschriften, en handhaving op lachgas in de binnenstad is dan intensiever. Op een feestterrein of in de horeca bepalen de organisator en de uitbater de huisregels, en die staan lachgas vrijwel nooit toe. Wat dat voor bestellen in die dagen betekent, staat onder het thema bestellen."],
            ["Mag een verhuurder of een studentenhuis lachgas verbieden?",
             "Ja. Huisregels van een verhuurder, woningcorporatie of studentenvereniging mogen strenger zijn dan de wet, en in veel huurcontracten staat een bepaling over overlast of gevaarlijke stoffen. Houd daar rekening mee als je in een gedeeld pand in Breda woont en overleg met huisgenoten voordat je bestelt. Een conflict met de verhuurder is niet iets wat wij voor je kunnen oplossen."],
            ["Vallen slagroompatronen en crackers ook onder de Opiumwet?",
             "Slagroompatronen vallen onder de uitzondering voor voedingstoepassingen, voor zover ze voor dat doel worden verkocht en gebruikt. Een cracker is op zichzelf een metalen hulpmiddel zonder gas en staat niet op een lijst, maar het gebruik van patronen om lachgas te inhaleren valt wel onder het verbod. Wij noemen beide producten op de site zonder uitleg over gebruik, en dat is een bewuste keuze."],
            ["Welke eigen voorwaarden hanteren jullie naast de wet?",
             "Wij leveren uitsluitend aan personen van 18 jaar en ouder, alleen op een privé- of afgesproken adres, en weigeren levering als iemand aan de deur duidelijk onder invloed is of als er minderjarigen bij de overdracht betrokken zijn. We bezorgen geen tanks naar de openbare ruimte en nemen een tank mee terug als de situatie niet klopt. De volledige set staat in onze <a href=\"/algemene-voorwaarden/\">algemene voorwaarden</a>."],
            ["Waar vind ik betrouwbare informatie over de wet en over lachgas?",
             "Voor de wet is rijksoverheid.nl de bron, voor gemeentelijke regels breda.nl, en voor neutrale informatie over het middel zelf drugsinfo.nl en het Trimbos-instituut. Wij linken daar bewust naar in plaats van zelf de wettekst samen te vatten, omdat regels veranderen. Twijfel je over een specifieke situatie, dan geeft <a href=\"https://www.trimbos.nl\">trimbos.nl</a> onderbouwde achtergrond."],
        ],
        "related": ["veiligheid", "bezorgen"],
    },
]
