# -*- coding: utf-8 -*-
# Herschreven stadsgebieden (district) + nieuwe wijken voor lachgasrotterdam.nl (fase 3)

AREAS = [
    # ---------------------------------------------------------------- CENTRUM
    {
        "slug": "centrum", "name": "Centrum", "kind": "district",
        "title": "Lachgas Centrum Rotterdam | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Centrum? Lachgastanks bezorgd in de Stadsdriehoek, Cool, het Oude Westen en Scheepvaartkwartier, meestal binnen 20 tot 30 minuten.",
        "h1": "Lachgas Centrum",
        "lead": "Lachgastanks aan de deur in het centrum van Rotterdam, van de Coolsingel tot het Scheepvaartkwartier. Bestellen gaat via WhatsApp, alleen voor 18+.",
        "intro": [
            "Het stadsgebied Centrum is het kleinste van Rotterdam, maar wel het drukste: hier liggen de Stadsdriehoek rond de Coolsingel en de Markthal, Cool met de Witte de Withstraat, het Oude Westen, Dijkzigt met het Erasmus MC en het Scheepvaartkwartier aan de Veerhaven. Daar komen de woontorens aan de Wijnhaven en de Boompjes en het Laurenskwartier nog bij. Wij bezorgen lachgastanks op elk adres in dit gebied. Je stuurt via WhatsApp je straat, huisnummer en het gewenste formaat, wij bevestigen de prijs en het tijdstip, en daarna hoef je alleen nog de deur open te doen.",
            "Omdat alles in het centrum dicht bij elkaar ligt, is de rit zelf kort; wat tijd kost zijn de eenrichtingsstraten, de tramsporen op de Coolsingel en het parkeren bij een woontoren. Daarom houden we ook hier 20 tot 30 minuten aan, meestal aan de onderkant van die marge. Onze bezorgers kennen de ingangen van de complexen aan de Blaak, de Wijnhaven en het Weena, en weten hoe ze via de Westzeedijk of de Schiedamsedijk de drukte rond de Lijnbaan ontwijken. Woon je boven een winkel in het Oude Westen? Geef dan de naam op de bel mee, dat scheelt zoeken.",
            "Een etentje in een appartement aan de Westersingel, een borrel na een avond op de Witte de Withstraat of een weekend met logees in het Scheepvaartkwartier: voor elke groepsgrootte is er een passende <a href=\"/lachgas-tanks/\">lachgastank van 2KG, 4KG of 10KG</a>, verzegeld en met de prijs vooraf bevestigd. Afrekenen kan contant of via Tikkie zodra de tank bij je binnen staat. We vragen om een legitimatie als er twijfel is over de leeftijd, want we leveren uitsluitend aan 18+. Houd er rekening mee dat gebruik op straat in het centrum niet is toegestaan en lees de aandachtspunten op <a href=\"/veilig-gebruik/\">veilig gebruik</a> voordat je bestelt.",
        ],
        "wijken": "Stadsdriehoek, Cool, Oude Westen, Dijkzigt, Scheepvaartkwartier, Laurenskwartier, Wijnhaven, Coolsingel, Witte de Withstraat, Rotterdam Centraal",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de woontorens aan de Wijnhaven en de Boompjes?",
             "Ja, dat zijn adressen waar we vaak komen. Stuur de naam van het complex mee en geef aan of we ons bij de intercom moeten melden of beneden in de hal worden opgewacht; dan verloopt de overdracht in één keer goed."],
            ["Hoe snel kunnen jullie in het Oude Westen of op de Witte de Withstraat zijn?",
             "Meestal binnen 20 tot 30 minuten, en op rustige momenten eerder. Op vrijdag- en zaterdagavond is het rond de Witte de Withstraat en de Nieuwe Binnenweg druk met taxi's en bezoekers; dan plannen we iets ruimer en zeggen we dat vooraf in de chat."],
            ["Mag ik een lachgastank meenemen naar een terras of het Museumpark?",
             "Nee. Rotterdam heeft in de APV regels opgenomen tegen lachgasgebruik in de openbare ruimte en handhaaft daarop in het centrum. Wij bezorgen alleen op een woon- of verblijfadres; wat de gemeente precies toestaat lees je op <a href=\"https://www.rotterdam.nl\">rotterdam.nl</a>."],
        ],
        "nearby": ["noord", "delfshaven", "kop-van-zuid"],
        "lat": 51.922, "lon": 4.479,
    },
    # ---------------------------------------------------------------- CHARLOIS
    {
        "slug": "charlois", "name": "Charlois", "kind": "district",
        "title": "Lachgas Charlois | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Charlois? Lachgastanks bezorgd van Zuidplein tot Pendrecht, Carnisse en Heijplaat, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Charlois",
        "lead": "Lachgastanks bezorgd in heel Charlois, van de Maastunnel tot aan de A15. Besteld via WhatsApp, betaald bij levering, alleen voor 18+.",
        "intro": [
            "Charlois beslaat het westelijke deel van Rotterdam-Zuid, tussen de Maashaven en de Waalhaven in het noorden en de A15 bij het Vaanplein in het zuiden. De wijken die eronder vallen zijn Oud-Charlois, Carnisse, Tarwewijk, Zuidwijk, Pendrecht, Wielewaal en het tuindorp Heijplaat aan de Waalhaven, met Zuidplein en het Zuiderpark als middelpunt. Op al die adressen bezorgen we lachgastanks. Bestellen doe je door via WhatsApp je adres en het gewenste formaat te sturen; wij antwoorden met de prijs en een tijdsindicatie, en zodra je bevestigt gaat de bezorger op weg.",
            "Vanuit het centrum is de Maastunnel de snelste route naar Charlois: aan de zuidkant kom je uit op de Pleinweg en van daar is het via de Dorpsweg of de Wolphaertsbocht nog een paar minuten naar Carnisse en Oud-Charlois. Voor Zuidwijk en Pendrecht gebruiken we de Zuiderparkweg of de Slinge, en Heijplaat bereiken we via de Waalhavenweg. De metrostations Zuidplein en Slinge op de lijnen D en E liggen midden in het gebied, net als het busstation bij Ahoy. Een levertijd van 20 tot 30 minuten is hier meestal haalbaar; bij een concert in Ahoy of een storing in de tunnel wijken we uit via de Erasmusbrug.",
            "Voor een verjaardag in een portiekwoning in Carnisse, een avond in een eengezinswoning in Pendrecht of een huisfeest in Zuidwijk zoek je zelf het formaat uit: een <a href=\"/lachgas-tanks/\">2KG, 4KG of 10KG lachgastank</a>, altijd verzegeld en met de prijs vooraf in de chat bevestigd. Je betaalt bij de deur, contant of met een Tikkie, en we leveren alleen aan volwassenen; bij twijfel vragen we een legitimatie te laten zien. Wat wij adviseren om verantwoord met een tank om te gaan, staat op onze pagina over <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Oud-Charlois, Carnisse, Tarwewijk, Zuidwijk, Pendrecht, Wielewaal, Heijplaat, Zuidplein, Zuiderpark, Ahoy",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Is het bij evenementen in Ahoy druk voor jullie bezorgers?",
             "Bij een groot concert of een beurs in Ahoy staan de Zuiderparkweg en de parkeerterreinen rond Zuidplein vol. We rijden dan via de Dorpsweg of de Slinge om en geven je vooraf een ruimere tijdsindicatie, zodat je weet waar je aan toe bent."],
            ["Komen jullie ook in Heijplaat, aan de andere kant van de Waalhaven?",
             "Ja. Heijplaat ligt afgelegen maar hoort gewoon bij Charlois; we rijden via de Waalhavenweg naar het dorp en het RDM-terrein. Reken op het hogere deel van de 20 tot 30 minuten, omdat het één weg heen en dezelfde weg terug is."],
            ["Kan ik in Charlois ook laat op de avond nog bestellen?",
             "Dat kan, we zijn ook ’s avonds en ’s nachts bereikbaar via WhatsApp. Na middernacht is de Maastunnel rustig en zijn we vaak sneller in Oud-Charlois en Carnisse dan overdag; de mogelijkheden staan op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["feijenoord", "pernis", "ijsselmonde"],
        "lat": 51.882, "lon": 4.478,
    },
    # ---------------------------------------------------------------- DELFSHAVEN
    {
        "slug": "delfshaven", "name": "Delfshaven", "kind": "district",
        "title": "Lachgas Delfshaven | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Delfshaven? Lachgastanks bezorgd in Spangen, Middelland, Tussendijken en het Lloydkwartier, meestal binnen 20 tot 30 minuten.",
        "h1": "Lachgas Delfshaven",
        "lead": "Van de Nieuwe Binnenweg tot het Marconiplein en van Spangen tot de Müllerpier: lachgastanks bezorgd in Delfshaven, via WhatsApp besteld. Alleen 18+.",
        "intro": [
            "Delfshaven is het stadsgebied direct ten westen van het centrum, ingeklemd tussen de Schiedamse grens, de A20 en de Nieuwe Maas. Het historische havenkwartier rond de Voorhaven en de Achterhaven geeft het gebied zijn naam, maar het grootste deel bestaat uit dichtbebouwde woonwijken: Middelland en het Nieuwe Westen rond de Heemraadssingel, Bospolder en Tussendijken bij het Dakpark, Spangen rond Het Kasteel, Oud-Mathenesse met het Witte Dorp, en aan het water het Lloydkwartier, de Müllerpier en Schiemond. Wij bezorgen in al deze wijken. Een appje met je adres en het formaat van de tank is voldoende; de prijs en de verwachte aankomsttijd krijg je direct terug.",
            "Vanaf het centrum rijden we via de Nieuwe Binnenweg of de Mathenesserlaan, twee doorgaande straten die Delfshaven in de lengte doorsnijden. Voor Spangen en Oud-Mathenesse pakken we de Tjalklaan vanaf de A20, voor het Lloydkwartier de Westzeedijk langs de Coolhaven, vlak bij de noordelijke ingang van de Maastunnel. De metrolijnen A, B en C rijden onder het gebied door met de haltes Coolhaven, Delfshaven en Marconiplein, en over de Schiedamseweg lopen tramsporen. De afstanden zijn klein, waardoor 20 tot 30 minuten hier realistisch is; op de Nieuwe Binnenweg is het op vrijdagavond wel vaak langzaam rijden.",
            "Of het nu gaat om een huisfeest in een bovenwoning aan de Heemraadssingel, een avond met huisgenoten in Tussendijken of een verjaardag in een nieuwbouwappartement op de Müllerpier: je kiest uit het <a href=\"/lachgas-tanks/\">assortiment lachgastanks</a> het formaat dat bij je groep past, van 2KG tot 10KG, en wij leveren verzegeld. Je rekent af bij levering, contant of via Tikkie, en we controleren bij twijfel de leeftijd omdat we uitsluitend aan 18+ leveren. Lees voor je bestelt de informatie over <a href=\"/veilig-gebruik/\">veilig gebruik</a>, zodat je weet waar je op moet letten bij het bewaren van een tank.",
        ],
        "wijken": "Historisch Delfshaven, Middelland, Nieuwe Westen, Bospolder, Tussendijken, Spangen, Oud-Mathenesse, Lloydkwartier, Müllerpier, Schiemond",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook op de Müllerpier en in het Lloydkwartier?",
             "Ja, de appartementen aan de Lloydstraat, de Sint-Jobsweg en op de Müllerpier horen bij ons gebied. Geef het blok en de verdieping door; bij de hogere gebouwen spreken we vaak af in de hal, zodat je niet hoeft te wachten tot de bezorger de juiste lift heeft gevonden."],
            ["Hoe zit het met bezorgen rond Het Kasteel bij een wedstrijd van Sparta?",
             "Op wedstrijddagen zijn straten rond het stadion in Spangen tijdelijk afgesloten en staat er veel verkeer op de Spaanseweg. We rijden dan via de Mathenesserweg aan en houden iets meer tijd aan; dat melden we vooraf in de chat."],
            ["Wat als ik net over de grens in Schiedam woon?",
             "Dan kunnen we ook bij je terecht. Schiedam ligt direct tegen Oud-Mathenesse en Spangen aan en hoort bij ons bezorggebied met een eigen levertijd; kijk op <a href=\"/lachgas-bestellen/schiedam/\">lachgas Schiedam</a> voor de details."],
        ],
        "nearby": ["centrum", "overschie", "schiedam"],
        "lat": 51.907, "lon": 4.443,
    },
    # ---------------------------------------------------------------- FEIJENOORD
    {
        "slug": "feijenoord", "name": "Feijenoord", "kind": "district",
        "title": "Lachgas Feijenoord | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Feijenoord? Lachgastanks bezorgd op het Noordereiland, in de Afrikaanderwijk, Hillesluis en Vreewijk.",
        "h1": "Lachgas Feijenoord",
        "lead": "Lachgastanks bezorgd in heel Feijenoord, over de Erasmusbrug of de Willemsbrug naar Zuid. Bestellen via WhatsApp, betalen bij levering, alleen 18+.",
        "intro": [
            "Feijenoord is het stadsgebied dat direct tegenover het centrum aan de zuidoever van de Nieuwe Maas ligt. Het omvat het Noordereiland midden in de rivier, de Kop van Zuid met de Wilhelminapier, het schiereiland Katendrecht, de wijk Feijenoord rond De Kuip, de Afrikaanderwijk, Bloemhof, Hillesluis en het tuindorp Vreewijk. Voor de Kop van Zuid en Katendrecht hebben we aparte pagina’s; deze pagina gaat over het hele gebied. Bestellen werkt overal hetzelfde: je appt je adres en het formaat van de lachgastank, wij bevestigen prijs en tijd en komen naar je toe.",
            "Vanuit het centrum zijn er twee directe routes: de Erasmusbrug naar de Laan op Zuid en de Willemsbrug via het Noordereiland en de Koninginnebrug naar de Oranjeboomstraat. Vanaf de A16 nemen we de afslag Feijenoord bij het stadion en rijden via de Stadionweg en de Putselaan naar Hillesluis en Bloemhof. De metrolijnen D en E stoppen op Wilhelminaplein, Rijnhaven en Maashaven, en station Rotterdam Zuid bij de Putselaan ligt tussen Hillesluis en de wijk Feijenoord. Door die ontsluiting is 20 tot 30 minuten hier gebruikelijk; alleen rond een thuiswedstrijd van Feyenoord staat het verkeer op de Stadionweg en de Colosseumweg stil.",
            "Een avond met vrienden in een woning aan de Beijerlandselaan, een feestje in een tuindorpwoning in Vreewijk of een verjaardag op het Noordereiland: kies het formaat dat past uit onze <a href=\"/lachgas-tanks/\">lachgastanks van 2KG, 4KG en 10KG</a>. De tank komt verzegeld aan en de prijs is al in de chat vastgelegd, zodat je bij de deur alleen nog contant of via Tikkie betaalt. We leveren alleen aan mensen van 18 jaar en ouder en vragen zo nodig om een identiteitsbewijs. De tips over bewaren en gebruiken staan op <a href=\"/veilig-gebruik/\">veilig gebruik</a>; lees ze vooraf even door.",
        ],
        "wijken": "Noordereiland, Kop van Zuid, Katendrecht, Afrikaanderwijk, Bloemhof, Hillesluis, Vreewijk, Wilhelminapier, De Kuip, Beijerlandselaan",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook op wedstrijddagen rond De Kuip?",
             "Ja, maar houd rekening met afsluitingen rond het stadion en file op de Stadionweg voor en na de wedstrijd. We plannen dan ruimer en rijden via de Putselaan of de Laan op Zuid om. Meld in je bericht dat je bij het stadion woont, dan stemmen we het tijdstip af."],
            ["Hoe komen jullie op het Noordereiland?",
             "Via de Willemsbrug vanaf de Boompjes of via de Koninginnebrug vanaf de Feijenoordzijde. Het eiland is klein en overzichtelijk, dus na de brug zijn we binnen een paar minuten op de Prins Hendrikkade of de Maaskade. Staat de Koninginnebrug open voor scheepvaart, dan nemen we de andere kant."],
            ["Zit Vreewijk nog binnen 20 tot 30 minuten?",
             "Meestal wel. Vreewijk ligt in het zuiden van het gebied, tegen Lombardijen en Zuidwijk aan, en we rijden er via de Groene Hilledijk of de Strevelsweg naartoe. Voor de aangrenzende wijk heeft <a href=\"/lachgas-bestellen/lombardijen/\">lachgas Lombardijen</a> een eigen pagina."],
        ],
        "nearby": ["kop-van-zuid", "katendrecht", "ijsselmonde"],
        "lat": 51.898, "lon": 4.505,
    },
    # ---------------------------------------------------------------- HILLEGERSBERG-SCHIEBROEK
    {
        "slug": "hillegersberg-schiebroek", "name": "Hillegersberg-Schiebroek", "kind": "district",
        "title": "Lachgas Hillegersberg-Schiebroek | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Hillegersberg-Schiebroek? Lachgastanks bezorgd rond de Bergse Plassen, in Schiebroek en Terbregge, meestal binnen 20 tot 30 minuten.",
        "h1": "Lachgas Hillegersberg-Schiebroek",
        "lead": "Lachgastanks bezorgd aan de noordrand van Rotterdam: Hillegersberg, Schiebroek, Terbregge en het Molenlaankwartier. Via WhatsApp, alleen 18+.",
        "intro": [
            "Hillegersberg-Schiebroek is het groene stadsgebied ten noorden van de A20, met de Bergse Voorplas en Achterplas als middelpunt. Hillegersberg-Noord en -Zuid liggen rond de Straatweg en de Kerkstraat met de oude Hillegondakerk, het Molenlaankwartier en 110-Morgen strekken zich uit richting het Lage Bergse Bos, Terbregge ligt aan de Rotte bij het Terbregseplein, en Schiebroek en het Kleiwegkwartier vormen de westkant tegen de spoorlijn naar Den Haag. In al deze buurten bezorgen we lachgastanks aan huis. Bestellen is een kwestie van je adres en het gewenste formaat appen; wij reageren met de prijs en de verwachte aankomsttijd.",
            "Vanaf het centrum rijden we over de Bergweg en de Straatweg, of via de Schieweg en de Gordelweg naar het Kleiwegkwartier en Schiebroek. Komen we van de A20, dan is de afslag richting Crooswijk en de Bosdreef het snelst voor Terbregge, en de Molenlaan voor het oostelijk deel van Hillegersberg. Met het openbaar vervoer is het gebied bereikbaar via RandstadRail-lijn E met de haltes Melanchthonweg en Meijersplein, en via station Rotterdam Noord aan de Bergweg. De ritten zijn iets langer dan binnen de ring, maar de doorstroming is goed, zodat we meestal binnen 20 tot 30 minuten voor de deur staan.",
            "Een tuinfeest bij een vrijstaande woning aan de Straatweg, een verjaardag in een jaren-dertighuis in het Kleiwegkwartier of een avond in een flat in Schiebroek: de grootte van het gezelschap bepaalt welke <a href=\"/lachgas-tanks/\">lachgastank (2KG, 4KG of 10KG)</a> het beste past, en bij twijfel adviseren we in de chat. De tank wordt verzegeld geleverd tegen de vooraf afgesproken prijs, af te rekenen bij de deur met contant geld of een Tikkie. Levering is uitsluitend aan 18+; houd een legitimatie bij de hand. Op <a href=\"/veilig-gebruik/\">veilig gebruik</a> lees je hoe je een tank bewaart en waar je op let.",
        ],
        "wijken": "Hillegersberg-Noord, Hillegersberg-Zuid, Schiebroek, Terbregge, Molenlaankwartier, 110-Morgen, Kleiwegkwartier, Bergse Plassen, Straatweg, Kleiweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Komen jullie ook in Terbregge, aan de andere kant van de Rotte?",
             "Ja. Terbregge ligt tussen de Rotte en het Terbregseplein en bereiken we via de Bosdreef of de Terbregseweg. Het is een rustige buurt met vooral eengezinswoningen, dus de bezorger staat meestal zonder zoeken voor de juiste deur."],
            ["Hoe lang duurt het naar Schiebroek, helemaal aan de westkant?",
             "Schiebroek ligt binnen dit gebied het verst van het centrum, maar via de Schieweg en de Gordelweg of de Kleiweg is het goed te bereizen. Houd rekening met het hogere deel van de 20 tot 30 minuten; op de Peppelweg en rond Meijersplein komen we regelmatig."],
            ["Woon ik in Bergschenhoek, bezorgen jullie dan ook?",
             "Ja, Lansingerland hoort bij ons bezorggebied en grenst direct aan Hillegersberg en Schiebroek. De levertijd is daar iets ruimer; de details vind je op <a href=\"/lachgas-bestellen/bergschenhoek/\">lachgas Bergschenhoek</a>."],
        ],
        "nearby": ["noord", "blijdorp", "bergschenhoek"],
        "lat": 51.953, "lon": 4.478,
    },
    # ---------------------------------------------------------------- HOEK VAN HOLLAND
    {
        "slug": "hoek-van-holland", "name": "Hoek van Holland", "kind": "district",
        "title": "Lachgas Hoek van Holland | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Hoek van Holland? Lachgastanks bezorgd in het dorp, bij de Berghaven en achter het strand, meestal binnen 25 tot 40 minuten. 18+.",
        "h1": "Lachgas Hoek van Holland",
        "lead": "Lachgastanks bezorgd aan de kust, in Hoek van Holland en rond de Berghaven. Via WhatsApp besteld, meestal binnen 25 tot 40 minuten aan de deur. 18+.",
        "intro": [
            "Hoek van Holland is officieel een stadsgebied van Rotterdam, maar voelt als een kustdorp op dertig kilometer van de Coolsingel, aan de monding van de Nieuwe Waterweg. Het dorp ligt rond de Prins Hendrikstraat en de Rietdijkstraat, met de Berghaven en de Stena Line-terminal aan het water, het strand en de duinen aan de westkant en het Westland met ’s-Gravenzande als buur. Wij bezorgen lachgastanks in het hele dorp, van de straten rond het metrostation tot de woningen aan de Badweg. Appen met je adres en het gewenste formaat volstaat; je krijgt de prijs en een tijdsindicatie terug.",
            "De rit vanuit Rotterdam gaat over de A20 tot het einde bij Maassluis en daarna over de N220 door Maasdijk naar de Hoek. Dat is een stuk verder dan welk ander stadsgebied ook, en daarom hanteren we hier 25 tot 40 minuten in plaats van de 20 tot 30 minuten elders in de stad. Het openbaar vervoer loopt via metrolijn B, die sinds de ombouw van de Hoekse Lijn eindigt op Hoek van Holland Haven. Op zonnige zomerdagen staat het verkeer richting het strand vast en kan de bovenkant van de marge in zicht komen; dat zeggen we dan eerlijk in de chat.",
            "Een vakantiehuisje op een van de parken bij het strand, een verjaardag in het dorp of een avond met vrienden na een dag aan zee: je kiest uit onze <a href=\"/lachgas-tanks/\">lachgastanks</a> het formaat dat past, 2KG voor een klein gezelschap tot 10KG voor een grotere groep, verzegeld en tegen de vooraf bevestigde prijs. Afrekenen gaat bij levering, contant of via Tikkie. Omdat we alleen aan 18+ leveren, controleren we bij twijfel een legitimatie, ook op een vakantieadres. Lees vooraf de adviezen op <a href=\"/veilig-gebruik/\">veilig gebruik</a>, en weet dat gebruik op het strand en in de duinen niet is toegestaan.",
        ],
        "wijken": "Hoek van Holland dorp, Berghaven, Prins Hendrikstraat, Badweg, Strandweg, Hoekse Bosjes, metrostation Hoek van Holland Haven, Stena Line-terminal, Nieuwe Waterweg, Maeslantkering",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Waarom is de levertijd in Hoek van Holland langer dan in Rotterdam?",
             "Omdat het dorp aan het uiterste westen van de gemeente ligt, voorbij Maassluis en Maasdijk. De afstand vanaf het centrum is ongeveer dertig kilometer over de A20 en de N220, en daarom rekenen we op 25 tot 40 minuten in plaats van 20 tot 30."],
            ["Bezorgen jullie ook op een vakantiepark of camping bij het strand?",
             "Ja, mits het een adres is waar we een volwassene met legitimatie aan de deur treffen. Stuur het nummer of de naam van het huisje mee en geef aan waar we de auto kwijt kunnen; op parken met een slagboom spreken we af bij de ingang."],
            ["Is het druk bezorgen op stranddagen?",
             "In de zomer en bij mooi weer loopt de Badweg vol en zijn parkeerplaatsen schaars. We houden dan het hogere deel van de levertijd aan en vragen je om op een goed bereikbare plek te zijn. Heb je weinig tijd, kijk dan bij <a href=\"/lachgas-spoedbezorging/\">spoedbezorging</a> wat mogelijk is."],
        ],
        "nearby": ["maassluis", "naaldwijk", "vlaardingen"],
        "lat": 51.978, "lon": 4.133,
    },
    # ---------------------------------------------------------------- HOOGVLIET
    {
        "slug": "hoogvliet", "name": "Hoogvliet", "kind": "district",
        "title": "Lachgas Hoogvliet | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Hoogvliet? Lachgastanks bezorgd in Meeuwenplaat, Zalmplaat, Westpunt en Tussenwater, meestal binnen 20 tot 30 minuten. Alleen 18+.",
        "h1": "Lachgas Hoogvliet",
        "lead": "Lachgastanks bezorgd in Hoogvliet, tussen de A15, de Oude Maas en de Botlek. Bestellen via WhatsApp, meestal binnen 20 tot 30 minuten voor de deur. 18+.",
        "intro": [
            "Hoogvliet is het zuidwestelijke stadsgebied van Rotterdam, aan de Oude Maas en op een steenworp van het havengebied bij de Botlek. Het is na de oorlog gebouwd als woonstad voor wie in de havens en de petrochemie werkte en bestaat uit ruim opgezette buurten: Hoogvliet-Noord met Tussenwater en Nieuw Engeland, en Hoogvliet-Zuid met Meeuwenplaat, Zalmplaat, Westpunt, Oudeland en Boomgaardshoek rond winkelcentrum Binnenban. Wij bezorgen lachgastanks in al deze buurten. Je stuurt via WhatsApp je adres en het formaat dat je zoekt; wij bevestigen de prijs en zeggen hoe laat we er ongeveer zijn.",
            "De snelste weg vanuit het centrum loopt via de Maastunnel en de Pleinweg naar de A15, of via de Erasmusbrug en de Vaanweg naar het Vaanplein, en dan over de A15 naar de afslag Hoogvliet. De Groene Kruisweg en de Aveling brengen ons vervolgens naar de verschillende buurten. Hoogvliet heeft drie metrostations op de lijnen C en D: Tussenwater, Hoogvliet en Zalmplaat. De afstand tot het centrum is een kleine vijftien kilometer, dus we zitten hier vaker aan de bovenkant van de 20 tot 30 minuten dan eronder, vooral als het op de A15 bij de Botlek druk is.",
            "Een avond in een portiekflat in Meeuwenplaat, een tuinfeest in Boomgaardshoek of een verjaardag in een nieuwbouwwoning in Tussenwater: in het overzicht van onze <a href=\"/lachgas-tanks/\">lachgastanks</a> zie je welk formaat bij hoeveel mensen past, van 2KG tot 10KG, steeds verzegeld geleverd. De prijs wordt in de chat vastgelegd voordat de bezorger vertrekt en je betaalt bij levering, contant of met een Tikkie. Leveren doen we uitsluitend aan 18+, met een check van het identiteitsbewijs als dat nodig is. Lees ook de pagina <a href=\"/veilig-gebruik/\">veilig gebruik</a> over het bewaren van een tank in huis.",
        ],
        "wijken": "Hoogvliet-Noord, Hoogvliet-Zuid, Meeuwenplaat, Zalmplaat, Westpunt, Oudeland, Tussenwater, Nieuw Engeland, Boomgaardshoek, Binnenban",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe lang duurt het vanaf het centrum naar Hoogvliet?",
             "Meestal 20 tot 30 minuten, waarbij we eerlijk zeggen dat het hier vaker richting de 30 gaat dan in Charlois of Feijenoord. De A15 is de bepalende factor; staat het vast bij de Botlek, dan rijden we via de Groene Kruisweg en melden we een ruimere tijd."],
            ["Bezorgen jullie ook aan de overkant van de Spijkenisserbrug?",
             "Ja, Spijkenisse hoort bij ons bezorggebied en ligt direct over de Oude Maas. De levertijd is daar iets langer dan in Hoogvliet; kijk op <a href=\"/lachgas-bestellen/spijkenisse/\">lachgas Spijkenisse</a> voor de indicatie."],
            ["Kan ik in Hoogvliet ook laat op de avond of in het weekend bestellen?",
             "Ja, we zijn in het weekend en ’s nachts bereikbaar via WhatsApp. Na middernacht is de A15 leeg en zijn we vaak sneller in Zalmplaat of Westpunt dan op een doordeweekse middag."],
        ],
        "nearby": ["pernis", "spijkenisse", "charlois"],
        "lat": 51.865, "lon": 4.360,
    },
    # ---------------------------------------------------------------- IJSSELMONDE
    {
        "slug": "ijsselmonde", "name": "IJsselmonde", "kind": "district",
        "title": "Lachgas IJsselmonde | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in IJsselmonde? Lachgastanks bezorgd in Groot-IJsselmonde, Beverwaard en rond Keizerswaard, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas IJsselmonde",
        "lead": "Lachgastanks bezorgd in heel IJsselmonde, van de Van Brienenoordbrug tot de grens met Barendrecht. Via WhatsApp besteld en bij levering betaald, alleen 18+.",
        "intro": [
            "IJsselmonde is het zuidoostelijke stadsgebied van Rotterdam, tussen de Nieuwe Maas bij de Van Brienenoordbrug en de A15 bij Barendrecht en Ridderkerk. Het bestaat uit het oude dorp Oud-IJsselmonde aan de rivier, Groot-IJsselmonde met de buurten Reyeroord, Hordijkerveld, Zomerland, Kreekhuizen en Sportdorp, de wijk Lombardijen rond het gelijknamige station en Beverwaard in het uiterste oosten. Winkelcentrum Keizerswaard is het hart van het gebied. We bezorgen lachgastanks op elk adres hier. Stuur je straat en huisnummer plus het gewenste formaat via WhatsApp en je ontvangt de prijs en een aankomsttijd.",
            "Vanuit het centrum gaan we via de Erasmusbrug en de Laan op Zuid naar de Stadionweg, of via de A16 over de Van Brienenoordbrug naar de afslag IJsselmonde. Daarna verdelen de IJsselmondse Randweg, de Groeninx van Zoelenlaan en de Adriaan Volkerlaan het gebied overzichtelijk in. Met het OV kom je er via station Rotterdam Lombardijen en de tramlijnen naar Keizerswaard en Beverwaard; een metrostation heeft IJsselmonde niet. De rit is iets langer dan naar Feijenoord, maar binnen 20 tot 30 minuten lukt het meestal, behalve wanneer een thuiswedstrijd in De Kuip de Stadionweg blokkeert.",
            "Een feestje in een rijtjeshuis in Beverwaard, een verjaardag in een flat aan de Dwarsdijk of een avond met vrienden in Oud-IJsselmonde: welk formaat je nodig hebt lees je bij onze <a href=\"/lachgas-tanks/\">lachgastanks in 2KG, 4KG en 10KG</a>; wij leveren altijd verzegeld en tegen de prijs die vooraf in de chat is afgesproken. Betalen doe je pas bij de deur, contant of via Tikkie. We leveren alleen aan 18+ en kunnen om een legitimatie vragen. Bekijk voor het bestellen ook <a href=\"/veilig-gebruik/\">veilig gebruik</a>, met praktische adviezen over het bewaren en vervoeren van een tank.",
        ],
        "wijken": "Oud-IJsselmonde, Groot-IJsselmonde, Lombardijen, Beverwaard, Reyeroord, Hordijkerveld, Zomerland, Kreekhuizen, Sportdorp, Keizerswaard",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in Beverwaard, helemaal aan de oostkant?",
             "Ja, Beverwaard hoort gewoon bij IJsselmonde en is via de IJsselmondse Randweg goed te bereiken. Het is wel het verste puntje van het gebied, dus reken op het hogere deel van de 20 tot 30 minuten, zeker als de Van Brienenoordbrug vol staat."],
            ["Lombardijen heeft een eigen pagina, moet ik daar bestellen?",
             "Dat maakt niet uit; bestellen gaat altijd via hetzelfde WhatsApp-account en de levertijd is gelijk. De pagina <a href=\"/lachgas-bestellen/lombardijen/\">lachgas Lombardijen</a> gaat alleen dieper in op die wijk."],
            ["Komen jullie ook in Barendrecht of Ridderkerk, net buiten IJsselmonde?",
             "Ja, beide gemeenten grenzen aan het gebied en vallen binnen ons bezorggebied. De levertijd ligt daar iets hoger omdat we de A15 of de Rotterdamseweg moeten kruisen; op de pagina’s van die plaatsen staat de indicatie."],
        ],
        "nearby": ["lombardijen", "feijenoord", "barendrecht"],
        "lat": 51.885, "lon": 4.545,
    },
    # ---------------------------------------------------------------- KRALINGEN-CROOSWIJK
    {
        "slug": "kralingen-crooswijk", "name": "Kralingen-Crooswijk", "kind": "district",
        "title": "Lachgas Kralingen-Crooswijk | Bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Kralingen-Crooswijk? Lachgastanks bezorgd rond de Kralingse Plas, in Crooswijk, Rubroek en De Esch, meestal binnen 20 tot 30 minuten.",
        "h1": "Lachgas Kralingen-Crooswijk",
        "lead": "Lachgastanks bezorgd in Kralingen en Crooswijk, van het Oostplein tot de Kralingse Zoom en van de Rotte tot De Esch. Via WhatsApp, alleen 18+.",
        "intro": [
            "Kralingen-Crooswijk ligt direct ten oosten van het centrum, tussen de Rotte en de A16. Crooswijk, Oud-Crooswijk, Nieuw-Crooswijk en Rubroek vormen het dichtbebouwde westelijke deel aan de Boezem en de Crooswijksesingel; Kralingen-West en Kralingen-Oost liggen rond de Oudedijk en de Kralingse Plas, met het Kralingse Bos en de campus Woudestein van de Erasmus Universiteit aan de oostkant, en De Esch en Struisenburg aan de rivier. Voor de studentenbuurt rond de universiteit hebben we een aparte pagina over Kralingen. Bestellen gaat door je adres en het formaat van de lachgastank te appen; wij bevestigen prijs en tijdstip.",
            "Vanuit het centrum rijden we over de Oostzeedijk of de Goudsesingel naar het Oostplein en vandaar de Oudedijk op, of via de Boezemsingel richting Crooswijk. Vanaf de A20 is de afslag Crooswijk met de Boezemlaan het snelst, vanaf de A16 het Kralingseplein met de Abram van Rijckevorselweg. De metrolijnen A, B en C rijden onder het gebied door met de haltes Oostplein, Gerdesiaweg, Voorschoterlaan en Kralingse Zoom, en tram 7 eindigt bij Woudestein. Omdat het gebied compact is en direct aan de ringwegen ligt, is 20 tot 30 minuten hier goed haalbaar; op de Oudedijk kan het in de spits iets langer duren.",
            "Een huisfeest in een studentenhuis aan de Lusthofstraat, een verjaardag in een herenhuis aan de Avenue Concordia of een avond met buren in Nieuw-Crooswijk: kies het formaat uit onze <a href=\"/lachgas-tanks/\">lachgastanks</a>, van 2KG voor een klein gezelschap tot 10KG voor een volle woonkamer. We leveren verzegeld tegen de vooraf bevestigde prijs en je betaalt bij de deur, contant of met een Tikkie. Leveren doen we alleen aan 18+; in een studentenhuis vragen we de besteller zelf open te doen met een legitimatie. Lees de aandachtspunten op <a href=\"/veilig-gebruik/\">veilig gebruik</a> voor je bestelt.",
        ],
        "wijken": "Kralingen-West, Kralingen-Oost, Crooswijk, Oud-Crooswijk, Nieuw-Crooswijk, Rubroek, De Esch, Struisenburg, Kralingse Plas, Woudestein",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook op de campus Woudestein?",
             "Op de studentenwoningen aan en rond de campus wel, bijvoorbeeld aan de Burgemeester Oudlaan; op universiteitsterreinen zelf of in collegezalen niet. Geef het gebouw en de verdieping door en zorg dat je zelf met een legitimatie aan de deur staat."],
            ["Hoe snel zijn jullie in Crooswijk vanuit het centrum?",
             "Crooswijk ligt op een paar minuten van het Oostplein en het Hofplein, dus hier zitten we meestal aan de onderkant van de 20 tot 30 minuten. De Crooswijkseweg en de Boezemsingel zijn de routes die we doorgaans nemen."],
            ["Wat is het verschil met de pagina over Kralingen?",
             "Deze pagina beschrijft het hele stadsgebied inclusief Crooswijk, Rubroek en De Esch. De pagina <a href=\"/lachgas-bestellen/kralingen/\">lachgas Kralingen</a> gaat specifiek over de wijk rond de Kralingse Plas en de universiteit; bestellen werkt op beide plekken hetzelfde."],
        ],
        "nearby": ["kralingen", "centrum", "prins-alexander"],
        "lat": 51.925, "lon": 4.510,
    },
    # ---------------------------------------------------------------- NOORD
    {
        "slug": "noord", "name": "Noord", "kind": "district",
        "title": "Lachgas Noord Rotterdam | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Noord? Lachgastanks bezorgd in het Oude Noorden, Provenierswijk, Liskwartier, Bergpolder en Blijdorp.",
        "h1": "Lachgas Noord",
        "lead": "Lachgastanks bezorgd in Rotterdam Noord, direct achter Rotterdam Centraal: van de Zwart Janstraat tot de Gordelweg. Via WhatsApp, alleen 18+.",
        "intro": [
            "Noord is het stadsgebied dat begint aan de achterkant van Rotterdam Centraal en doorloopt tot de A20. Het bestaat uit zes wijken: de Provenierswijk bij het station, de Agniesebuurt met het Zomerhofkwartier en de Hofbogen, het Oude Noorden rond de Zwart Janstraat en het Noordplein, het Liskwartier, Bergpolder langs de Bergselaan en Blijdorp met de Diergaarde en het Vroesenpark. Voor het Oude Noorden en Blijdorp hebben we aparte pagina’s met meer detail. Overal in Noord bezorgen we lachgastanks aan huis; je appt adres en formaat, en wij sturen de prijs en de verwachte aankomsttijd terug.",
            "De afstand tot het centrum is klein en de routes zijn recht: over de Schiekade en de Bergweg naar het Oude Noorden en het Liskwartier, over de Statenweg naar Blijdorp en via de Walenburgerweg naar de Provenierswijk. Vanaf de A20 nemen we de afslag Centrum en rijden over de Schieweg of de Stadhoudersweg de wijk in. Metrolijn E stopt op Blijdorp, station Rotterdam Noord ligt aan de Bergweg, en over de Bergweg en de Schiekade rijden trams. Door die ligging zitten we in Noord meestal aan de onderkant van de 20 tot 30 minuten; alleen in de avondspits op de Schiekade loopt het wat op.",
            "Een verjaardag in een bovenwoning aan de Noordsingel, een avond met huisgenoten in Bergpolder of een feest in een appartement bij het Vroesenpark: kies het formaat uit onze <a href=\"/lachgas-tanks/\">lachgastanks</a>, 2KG, 4KG of 10KG, verzegeld geleverd en met de prijs vooraf in de chat vastgelegd. Betalen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan 18+; bij twijfel over de leeftijd vragen we een legitimatie. Een tank hoort rechtop en uit de zon te staan; wat je verder moet weten staat op <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Oude Noorden, Agniesebuurt, Provenierswijk, Liskwartier, Bergpolder, Blijdorp, Zwart Janstraat, Noordplein, Bergweg, Hofbogen",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de Provenierswijk, direct achter Centraal?",
             "Ja. De Provenierswijk is via de Walenburgerweg of de Proveniersstraat goed te bereiken, al is parkeren er krap. De bezorger appt bij aankomst, zodat je de tank bij de voordeur kunt aannemen zonder dat hij lang hoeft te zoeken."],
            ["Wat is het verschil tussen deze pagina en die van het Oude Noorden?",
             "Noord is het hele stadsgebied met zes wijken; het Oude Noorden is er één van. Op <a href=\"/lachgas-bestellen/oude-noorden/\">lachgas Oude Noorden</a> lees je meer over die wijk, maar bestellen en levertijd zijn hetzelfde."],
            ["Kunnen jullie bij een bovenwoning zonder lift bezorgen?",
             "Ja, dat is in Noord eerder regel dan uitzondering. Vermeld de verdieping en de naam op de bel; bij een 10KG-tank helpt het als je beneden aanneemt, want die is fors zwaarder dan een 2KG."],
        ],
        "nearby": ["oude-noorden", "blijdorp", "centrum"],
        "lat": 51.935, "lon": 4.470,
    },
    # ---------------------------------------------------------------- OVERSCHIE
    {
        "slug": "overschie", "name": "Overschie", "kind": "district",
        "title": "Lachgas Overschie | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Overschie? Lachgastanks bezorgd in het oude dorp, Kleinpolder, Landzicht en Park 16Hoven, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Overschie",
        "lead": "Lachgastanks bezorgd in Overschie, tussen de Schie, de A13 en Rotterdam The Hague Airport. Bestellen via WhatsApp, betalen bij levering, 18+.",
        "intro": [
            "Overschie is het noordwestelijke stadsgebied van Rotterdam, aan beide kanten van de Delftse en Rotterdamse Schie. Het oude dorp rond de Overschiese Dorpsstraat en de Grote Kerk vormt de kern, met de Burgemeester Baumannlaan als winkelstraat; daaromheen liggen Kleinpolder bij het verkeersknooppunt, Landzicht, de nieuwbouwwijk Park 16Hoven tegen de luchthaven, Zestienhoven en de polder Schieveen. Het bedrijventerrein Spaanse Polder ligt aan de zuidkant tegen Schiedam. In alle woonbuurten bezorgen we lachgastanks. Stuur je adres en het gewenste formaat via WhatsApp en je ontvangt direct de prijs en een tijdsindicatie.",
            "Vanuit het centrum rijden we via de Statenweg naar het Kleinpolderplein of over de Schiekade en de Schieweg naar Overschie; vanaf de A13 en de A20 is het Kleinpolderplein de afslag. Vlak daarna kom je op de Burgemeester Baumannlaan uit en van daar is elk adres binnen een paar minuten te bereiken. Overschie heeft geen metrostation, maar bus 33 naar Rotterdam The Hague Airport rijdt door het gebied en halte Meijersplein van RandstadRail E ligt vlak bij Park 16Hoven. Omdat het verkeer rond het Kleinpolderplein in de spits dicht kan slibben, houden we 20 tot 30 minuten aan; ’s avonds is het vlotter.",
            "Een verjaardag in een jaren-vijftigwoning in Kleinpolder, een feestje in een nieuwbouwhuis in Park 16Hoven of een avond met vrienden in het oude dorp: in het overzicht van onze <a href=\"/lachgas-tanks/\">lachgastanks</a> kies je 2KG, 4KG of 10KG, en bij twijfel adviseren we in de chat. De prijs ligt vooraf vast, de tank komt verzegeld aan en je betaalt bij de deur met contant geld of een Tikkie. Leveren doen we alleen aan 18+ en we controleren bij twijfel een identiteitsbewijs. Op <a href=\"/veilig-gebruik/\">veilig gebruik</a> staat hoe je een tank bewaart en wat je beter niet doet.",
        ],
        "wijken": "Overschie-dorp, Kleinpolder, Landzicht, Zestienhoven, Park 16Hoven, Schieveen, Burgemeester Baumannlaan, Overschiese Dorpsstraat, Kleinpolderplein, Rotterdam The Hague Airport",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in Park 16Hoven, tegen het vliegveld aan?",
             "Ja, de nieuwbouw tussen de Van der Duijn van Maasdamweg en de luchthaven hoort bij Overschie. We rijden er via de Doenkade of door het dorp naartoe. Geef bij een nieuw adres de straatnaam zorgvuldig door, omdat navigatie er nog weleens achterloopt."],
            ["Kan ik een lachgastank laten bezorgen bij Rotterdam The Hague Airport?",
             "Op de luchthaven zelf en in de terminal niet. Bij een hotel of woonadres in de buurt wel, mits een volwassene met legitimatie de tank aanneemt; lees wat we daarbij vragen op <a href=\"/lachgas-hotel-en-bezoekers/\">lachgas voor hotelgasten en bezoekers</a>."],
            ["Hoe druk is het Kleinpolderplein voor jullie bezorgers?",
             "In de ochtend- en avondspits staat het op de A13 en de A20 bij het knooppunt vaak vast, en dan kiezen we voor de Schieweg of de Statenweg binnendoor. Buiten de spits zijn we vanuit het centrum vaak binnen een kwartier in Overschie."],
        ],
        "nearby": ["blijdorp", "delfshaven", "hillegersberg-schiebroek"],
        "lat": 51.943, "lon": 4.430,
    },
    # ---------------------------------------------------------------- PRINS ALEXANDER
    {
        "slug": "prins-alexander", "name": "Prins Alexander", "kind": "district",
        "title": "Lachgas Prins Alexander | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Prins Alexander? Lachgastanks bezorgd in Ommoord, Zevenkamp, Prinsenland, Het Lage Land en Oosterflank.",
        "h1": "Lachgas Prins Alexander",
        "lead": "Lachgastanks bezorgd in het grootste stadsgebied van Rotterdam, van Alexandrium tot de Zevenhuizerplas. Bestellen via WhatsApp, alleen 18+.",
        "intro": [
            "Prins Alexander is het oostelijke stadsgebied van Rotterdam, het grootste in oppervlakte en inwonertal, en ligt tussen de A20, de A16 bij het Terbregseplein, de Rotte en de grens met Capelle aan den IJssel en Zuidplas. Het bestaat uit Ommoord, Zevenkamp, Nesselande, Prinsenland, Het Lage Land, ’s-Gravenland, Oosterflank en Kralingseveer, met winkelcentrum Alexandrium en station Rotterdam Alexander als centrale punt. Voor Ommoord, Zevenkamp en Nesselande hebben we eigen pagina’s. Wij bezorgen lachgastanks in het hele gebied; je appt je adres en het formaat, en wij antwoorden met de prijs en een tijdsindicatie.",
            "Vanuit het centrum rijden we via de A20 naar de afslag Prins Alexander en dan over de Prins Alexanderlaan of de Hoofdweg, of via de A16 en het Kralingseplein naar de Abram van Rijckevorselweg voor ’s-Gravenland en Prinsenland. Het gebied is uitstekend ontsloten met het OV: metrolijn A rijdt via Alexander, Graskruid en Romeynshof naar Binnenhof in Ommoord, lijn B via Nieuw Verlaat en De Tochten door Zevenkamp naar Nesselande, en op Rotterdam Alexander stoppen ook de treinen van NS. Door de afstand vanaf het centrum zitten we hier vaker aan de bovenkant van de 20 tot 30 minuten, vooral in Nesselande.",
            "Een feestje in een hoogbouwflat in Ommoord, een verjaardag in een eengezinswoning in Het Lage Land of een avond met vrienden in Prinsenland: kies het formaat uit onze <a href=\"/lachgas-tanks/\">lachgastanks van 2KG, 4KG of 10KG</a>, verzegeld geleverd tegen de prijs die vooraf in de chat is bevestigd. Betalen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan 18+ en vragen bij twijfel om een identiteitsbewijs. Op <a href=\"/veilig-gebruik/\">veilig gebruik</a> lees je hoe je een tank bewaart en vervoert, ook als je hem meeneemt naar een ander adres binnen het gebied.",
        ],
        "wijken": "Ommoord, Zevenkamp, Nesselande, Prinsenland, Het Lage Land, ’s-Gravenland, Oosterflank, Kralingseveer, Alexandrium, Rotterdam Alexander",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Zijn jullie net zo snel in Nesselande als bij Alexandrium?",
             "Niet helemaal. Alexandrium en Oosterflank liggen direct aan de A20 en zijn snel bereikt; Nesselande ligt helemaal aan de oostrand bij de Zevenhuizerplas, dus daar zitten we meestal aan het einde van de 20 tot 30 minuten. Zie <a href=\"/lachgas-bestellen/nesselande/\">lachgas Nesselande</a>."],
            ["Bezorgen jullie in de hoogbouw van Ommoord?",
             "Ja, de flats aan de President Rooseveltweg en rond het Binnenhof zijn adressen waar we vaak komen. Vermeld het portiek, de verdieping en de naam op de bel; bij een afgesloten centrale hal wachten we beneden tot je opendoet."],
            ["Woon ik in Capelle aan den IJssel, geldt dan dezelfde levertijd?",
             "Capelle grenst direct aan Prinsenland, ’s-Gravenland en Kralingseveer, maar is een eigen gemeente met een eigen pagina en indicatie. Kijk op <a href=\"/lachgas-bestellen/capelle-aan-den-ijssel/\">lachgas Capelle aan den IJssel</a>; het verschil met Prins Alexander is in de praktijk klein."],
        ],
        "nearby": ["ommoord", "zevenkamp", "nesselande"],
        "lat": 51.950, "lon": 4.550,
    },
    # ================================================================ NIEUWE WIJKEN
    # ---------------------------------------------------------------- KATENDRECHT
    {
        "slug": "katendrecht", "name": "Katendrecht", "kind": "wijk",
        "title": "Lachgas Katendrecht | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Katendrecht? Lachgastanks bezorgd op de Kaap, van het Deliplein tot de Maashaven, meestal binnen 20 tot 30 minuten. Alleen voor 18+.",
        "h1": "Lachgas Katendrecht",
        "lead": "Lachgastanks bezorgd op Katendrecht, het schiereiland tussen de Rijnhaven en de Maashaven. Bestellen via WhatsApp, betalen bij levering, 18+.",
        "intro": [
            "Katendrecht, in Rotterdam beter bekend als de Kaap, is een schiereiland in Feijenoord dat aan drie kanten door water wordt omsloten: de Rijnhaven in het noorden, de Maashaven in het zuiden en de Nieuwe Maas aan de punt. De oude havenbuurt is in twintig jaar veranderd in een woonwijk met nieuwbouw aan de Rijnhavenkant, horeca rond het Deliplein, de Fenixloodsen aan de Veerlaan en het ss Rotterdam aan het Derde Katendrechtse Hoofd. Wij bezorgen lachgastanks op elk adres op de Kaap. Een WhatsApp-bericht met je straat, huisnummer en het gewenste formaat is genoeg; wij bevestigen prijs en tijd.",
            "Met de auto is Katendrecht alleen via de Brede Hilledijk te bereiken, de enige toegangsweg aan de kant van de Hillelaan. Vanuit het centrum rijden we over de Erasmusbrug en de Posthumalaan naar de Hillelaan, of door de Maastunnel en via de Pleinweg en de Mijnsherenlaan naar de Maashaven Oostzijde. Voetgangers steken via de Rijnhavenbrug over naar de Wilhelminapier, en de metrostations Rijnhaven en Maashaven op de lijnen D en E liggen aan de rand van de wijk. De afstand tot het centrum is klein, dus 20 tot 30 minuten is hier ruim bemeten; op zomeravonden is het Deliplein wel druk met terrasbezoekers.",
            "Een borrel in een nieuwbouwappartement aan de Rijnhaven, een verjaardag in een van de oude havenhuizen rond de Tolhuisstraat of een avond met vrienden na een bezoek aan de Kaap: kies het formaat uit onze <a href=\"/lachgas-tanks/\">lachgastanks</a>, 2KG, 4KG of 10KG, verzegeld en tegen de vooraf afgesproken prijs. Afrekenen gebeurt bij de deur, contant of met een Tikkie. We leveren alleen aan 18+ en vragen bij twijfel om een legitimatie. Houd er rekening mee dat gebruik op de kades en op het Deliplein niet is toegestaan; wat wij adviseren staat op <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Deliplein, Fenixloodsen, Veerlaan, Rijnhavenbrug, Brede Hilledijk, Tolhuisstraat, Kaappark, ss Rotterdam, Maashaven, Rijnhaven",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe komen jullie Katendrecht op als er maar één toegangsweg is?",
             "Via de Brede Hilledijk vanaf de Hillelaan, en dat is zelden een probleem. Alleen bij evenementen op het Deliplein of rond de Fenixloodsen staat het daar vol; dan parkeren we iets verder en lopen we het laatste stuk."],
            ["Bezorgen jullie ook bij hotelgasten op het ss Rotterdam?",
             "Dat hangt af van het hotel; we leveren alleen aan een gast van 18+ die ons zelf bij de ingang opwacht met een legitimatie, nooit bij een receptie of in de openbare ruimtes van het schip. Wat we daarbij vragen staat op <a href=\"/lachgas-hotel-en-bezoekers/\">lachgas voor hotelgasten en bezoekers</a>."],
            ["Zit Katendrecht niet gewoon bij de pagina Feijenoord of Kop van Zuid?",
             "Katendrecht hoort bij het stadsgebied Feijenoord en ligt met de Rijnhavenbrug aan de Kop van Zuid vast, maar heeft een eigen karakter en daarom een eigen pagina. Bestellen en levertijd zijn op <a href=\"/lachgas-bestellen/kop-van-zuid/\">lachgas Kop van Zuid</a> hetzelfde."],
        ],
        "nearby": ["kop-van-zuid", "feijenoord", "charlois"],
        "lat": 51.900, "lon": 4.485,
    },
    # ---------------------------------------------------------------- KRALINGEN
    {
        "slug": "kralingen", "name": "Kralingen", "kind": "wijk",
        "title": "Lachgas Kralingen | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Kralingen? Lachgastanks bezorgd rond de Kralingse Plas, de Oudedijk en de studentenhuizen bij Woudestein.",
        "h1": "Lachgas Kralingen",
        "lead": "Lachgastanks bezorgd in Kralingen, de studentenbuurt rond de Erasmus Universiteit en de Kralingse Plas. Bestellen via WhatsApp, alleen 18+.",
        "intro": [
            "Kralingen is de wijk tussen het Oostplein en de Kralingse Zoom, aan de zuidkant begrensd door de Nieuwe Maas en aan de noordkant door de Kralingse Plas en het Kralingse Bos. De buurt rond de Oudedijk, de Lusthofstraat en de Avenue Concordia hoort tot de oudere delen van Rotterdam, met herenhuizen die vaak zijn opgedeeld in studentenkamers. Aan de oostrand ligt de campus Woudestein van de Erasmus Universiteit, met studentencomplexen aan de Burgemeester Oudlaan en in De Esch. Wij bezorgen lachgastanks in heel Kralingen. Stuur via WhatsApp je adres en het formaat dat je wilt, en je krijgt de prijs en een aankomsttijd terug.",
            "Vanuit het centrum is de Oostzeedijk of de Oudedijk de kortste weg, vanaf de A16 nemen we het Kralingseplein en de Abram van Rijckevorselweg richting Woudestein. De metrolijnen A, B en C hebben haltes op Voorschoterlaan en Kralingse Zoom, de laatste met een grote P+R, en tram 7 heeft zijn eindpunt bij de campus. De wijk ligt op een paar kilometer van de Coolsingel, dus de 20 tot 30 minuten halen we hier doorgaans gemakkelijk. Op donderdagavond, de vaste uitgaansavond van studenten, en in de introductieweek in augustus is het drukker aan de Oostzeedijk en rond de campus, en plannen we iets ruimer.",
            "Een huisfeest met huisgenoten aan de Lusthofstraat, een verjaardag in een studentencomplex bij Woudestein of een rustige avond in een bovenwoning aan de Hoflaan: welke <a href=\"/lachgas-tanks/\">lachgastank</a> past, 2KG, 4KG of 10KG, hangt af van het aantal mensen; in de chat helpen we kiezen. We leveren verzegeld tegen de vooraf bevestigde prijs en je betaalt bij de deur, contant of via Tikkie. In een studentenhuis leveren we alleen aan de besteller zelf, 18 jaar of ouder en met legitimatie, niet aan een huisgenoot die toevallig opendoet. Lees vooraf ook de aandachtspunten op <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Oudedijk, Lusthofstraat, Avenue Concordia, Hoflaan, Kralingse Plas, Kralingse Bos, Woudestein, Burgemeester Oudlaan, De Esch, Kralingse Zoom",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Wat zijn de regels als ik in een studentenhuis bestel?",
             "De besteller neemt zelf aan en laat een geldig identiteitsbewijs zien waaruit blijkt dat hij of zij 18 jaar of ouder is; aan minderjarige huisgenoten leveren we niet. Hoe we dat aanpakken staat op <a href=\"/lachgas-bezorgen-studentenhuis-rotterdam/\">lachgas bezorgen bij een studentenhuis</a>."],
            ["Bezorgen jullie ook in het Kralingse Bos of aan de Plas?",
             "Nee, alleen op woon- en verblijfadressen. Het Kralingse Bos en de oevers van de Plas zijn openbare ruimte, waar lachgasgebruik in Rotterdam niet is toegestaan en waar gehandhaafd wordt; de regels van de gemeente staan op <a href=\"https://www.rotterdam.nl\">rotterdam.nl</a>."],
            ["Hoe snel zijn jullie bij de studentencomplexen aan de Burgemeester Oudlaan?",
             "Meestal binnen 20 tot 30 minuten, via de Abram van Rijckevorselweg vanaf de A16 of via de Oudedijk vanuit het centrum. Geef het gebouw en de verdieping door; bij complexen met een gesloten entree spreken we bij de hoofdingang af."],
        ],
        "nearby": ["kralingen-crooswijk", "centrum", "capelle-aan-den-ijssel"],
        "lat": 51.918, "lon": 4.520,
    },
    # ---------------------------------------------------------------- OUDE NOORDEN
    {
        "slug": "oude-noorden", "name": "Oude Noorden", "kind": "wijk",
        "title": "Lachgas Oude Noorden | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Oude Noorden? Lachgastanks bezorgd rond de Zwart Janstraat, het Noordplein en de Noordsingel, meestal binnen 20 tot 30 minuten. 18+.",
        "h1": "Lachgas Oude Noorden",
        "lead": "Lachgastanks bezorgd in het Oude Noorden, de volkswijk tussen de Rotte, de Bergweg en de Schiekade. Via WhatsApp besteld, bij levering betaald, 18+.",
        "intro": [
            "Het Oude Noorden is een van de oudste uitbreidingswijken van Rotterdam, in de negentiende eeuw gebouwd tussen de Rotte en de spoorlijn naar Den Haag. De Zwart Janstraat en de Noordmolenstraat vormen samen een van de langste winkelstraten van de stad, het Noordplein aan de Rotte is het hart van de wijk en de Noordsingel met het voormalige gerechtsgebouw de groene rand. Rondom liggen de Zaagmolenstraat, de Benthuizerstraat, het Pijnackerplein en het Zwaanshals, en aan de zuidkant het viaduct van de Hofbogen. Wij bezorgen lachgastanks in heel het Oude Noorden; stuur je adres en het gewenste formaat via WhatsApp en wij antwoorden met prijs en tijd.",
            "Vanuit het centrum is het een rechte lijn: over de Schiekade en de Bergweg of via het Hofplein en de Zomerhofstraat ben je binnen vijf minuten bij het Noordplein. Vanaf de A20 nemen we de afslag Centrum en rijden via de Schieweg of de Gordelweg de wijk in. Rotterdam Centraal ligt op loopafstand, over de Bergweg en de Schiekade rijden trams, en station Rotterdam Noord ligt net ten noorden van de Gordelweg. Het enige dat hier tijd kost is parkeren: de straten zijn smal en vol, en daarom houden we toch 20 tot 30 minuten aan, meestal aan de korte kant.",
            "Een avond met vrienden in een bovenwoning aan de Zaagmolenstraat, een verjaardag in een gerenoveerd pand aan de Noordsingel of een huisfeest in een studentenhuis aan de Benthuizerstraat: kies uit onze <a href=\"/lachgas-tanks/\">lachgastanks</a> het formaat dat past, 2KG, 4KG of 10KG, altijd verzegeld en met de prijs vooraf bevestigd in de chat. Betalen doe je bij de deur, contant of via Tikkie. We leveren uitsluitend aan 18+ en vragen bij twijfel om een legitimatie. Gebruik op het Noordplein of langs de Rotte is niet toegestaan; hoe je verantwoord met een tank omgaat lees je op <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Zwart Janstraat, Noordmolenstraat, Noordplein, Noordsingel, Zaagmolenstraat, Benthuizerstraat, Pijnackerplein, Zwaanshals, Hofbogen, Rotte",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe lossen jullie het parkeren in het Oude Noorden op?",
             "De bezorger stopt kort voor de deur of op de dichtstbijzijnde vrije plek en brengt de tank lopend naar je voordeur. Omdat dat snel moet, vragen we je om klaar te staan zodra we appen dat we er zijn; dan zijn we binnen een minuut weer weg."],
            ["Bezorgen jullie ook op marktdagen op het Noordplein?",
             "Ja, maar de straten rond het Noordplein zijn op marktdagen deels afgesloten en druk. We rijden dan via de Zaagmolenkade of de Bergweg aan en spreken zo nodig een hoek verderop af. Vermeld dat je aan het plein woont, dan weten we het vooraf."],
            ["Is het Oude Noorden hetzelfde als de pagina Noord?",
             "Nee. Noord is het stadsgebied met zes wijken, waarvan het Oude Noorden er één is. Op <a href=\"/lachgas-bestellen/noord/\">lachgas Noord</a> lees je over het hele gebied, inclusief Bergpolder, het Liskwartier en de Agniesebuurt; bestellen werkt overal hetzelfde."],
        ],
        "nearby": ["noord", "blijdorp", "kralingen-crooswijk"],
        "lat": 51.934, "lon": 4.478,
    },
]
