# -*- coding: utf-8 -*-
# Nieuwe plaatsen buiten Rotterdam (fase 3): Drechtsteden, Hoeksche Waard, Goeree-Overflakkee, Groene Hart en Den Haag-as.

AREAS = [
    {
        "slug": "papendrecht",
        "name": "Papendrecht",
        "kind": "stad",
        "title": "Lachgas Papendrecht | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Papendrecht? Lachgastanks aan huis in Westpolder, Molenvliet, Oostpolder en het centrum. Via WhatsApp, 24/7, alleen voor 18+.",
        "h1": "Lachgas Papendrecht",
        "lead": "Lachgastanks bezorgd in Papendrecht, van de Merwedeoever tot Land van Matena. Bestellen gaat via WhatsApp, dag en nacht.",
        "intro": [
            "Papendrecht ligt aan de noordoever van de Beneden-Merwede, recht tegenover Dordrecht, en hoort bij de Drechtsteden. De gemeente is compact en stedelijk gebouwd: het centrum rond winkelcentrum De Meent, de oudere buurten Kraaihoek en Westpolder, de jaren-zeventigwijken Molenvliet en Wilgendonk, Oostpolder aan de kant van Sliedrecht en de nieuwere woningen in Land van Matena en op het Merwehoofd. We bezorgen in al deze buurten. Je stuurt ons een WhatsApp-bericht met je adres, het gewenste tankformaat en wanneer je de bestelling wilt ontvangen. Wij antwoorden met een tijdsindicatie en de totaalprijs, zodat je vooraf precies weet waar je aan toe bent.",
            "Onze route loopt vanuit Rotterdam over de A16 naar knooppunt Ridderkerk en vandaar via de A15 richting Gorinchem door de Noordtunnel tot de afslag Papendrecht; de N3 brengt ons vervolgens tot in de woonwijken. Staat het in de tunnel vast, dan wijken we uit via Dordrecht en de N3-brug over de Merwede. Papendrecht heeft geen eigen treinstation, maar is per Waterbus verbonden met de Merwekade in Dordrecht en met de Erasmusbrug in Rotterdam. Omdat we de hele Drechtsteden-corridor moeten doorkruisen en de A15 rond de spits traag kan zijn, rekenen we hier meestal op 35 tot 50 minuten. Het exacte levermoment bevestigen we vooraf in het gesprek.",
            "Of het nu gaat om een feestje in een rijtjeshuis in Molenvliet, een verjaardag in een appartement langs de Merwede of een avond met vrienden in Wilgendonk: in ons <a href=\"/lachgas-tanks/\">assortiment lachgastanks</a> kies je tussen 2KG, 4KG en 10KG, afhankelijk van de grootte van je gezelschap. Twijfel je over het formaat, dan denken we via WhatsApp mee. Je betaalt contant of via Tikkie zodra de koerier bij je aan de deur staat; vooruitbetalen vragen we nooit. We leveren alleen aan volwassenen van 18 jaar en ouder en kunnen om een legitimatiebewijs vragen. Neem vooraf de informatie over <a href=\"/veilig-gebruik/\">verantwoord gebruik</a> door.",
        ],
        "wijken": "Centrum, De Meent, Kraaihoek, Westpolder, Molenvliet, Wilgendonk, Oostpolder, Middenpolder, Land van Matena, Merwehoofd",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Papendrecht?", "Reken op meestal 35 tot 50 minuten na bevestiging. De rit loopt over de A16 en de A15 en is langer dan naar onze Rotterdamse wijken; bij drukte op knooppunt Ridderkerk melden we dat meteen via WhatsApp."],
            ["Bezorgen jullie ook in Land van Matena en op het Merwehoofd?", "Ja, we komen in heel Papendrecht, inclusief de nieuwere delen aan de oostkant en aan het water. Stuur je postcode mee, dan kunnen we de rit direct inplannen."],
            ["Kan ik in Papendrecht ook laat op de avond bestellen?", "Onze WhatsApp-lijn is dag en nacht open. ’s Nachts is de A15 rustig, maar de afstand blijft gelijk, dus de indicatie verandert niet. Meer over nachtlevering lees je op <a href=\"/lachgas-nachtbezorging/\">lachgas ’s nachts</a>."],
        ],
        "nearby": ["dordrecht", "sliedrecht", "alblasserdam"],
        "lat": 51.832, "lon": 4.690,
    },
    {
        "slug": "sliedrecht",
        "name": "Sliedrecht",
        "kind": "dorp",
        "title": "Lachgas Sliedrecht | 24/7 bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Sliedrecht? Wij bezorgen lachgastanks in Baanhoek, de Kerkbuurt, Westwijk en Sliedrecht-Oost. Bestellen via WhatsApp, alleen 18+.",
        "h1": "Lachgas Sliedrecht",
        "lead": "Bezorging van lachgastanks in het baggerdorp aan de Merwede. Je bestelt eenvoudig via WhatsApp, elke dag van de week.",
        "intro": [
            "Sliedrecht is de meest oostelijke van de Drechtsteden en strekt zich uit langs de Beneden-Merwede, tussen Papendrecht en Hardinxveld-Giessendam. Het dorp staat bekend als bakermat van de baggerindustrie, met het Nationaal Baggermuseum aan de Molendijk als tastbaar bewijs. Onze koeriers bezorgen in de Kerkbuurt en het centrum, in Westwijk en Baanhoek, in de nieuwbouw van Baanhoek-West, in De Grienden en in Sliedrecht-Oost richting Benedenveer. Bestellen doe je door ons een berichtje te sturen via WhatsApp met daarin je adres, het formaat van de tank en het gewenste moment. Daarna krijg je van ons de bevestiging met tijd en prijs.",
            "Vanuit Rotterdam volgen we de A16 naar knooppunt Ridderkerk en daarna de A15 door de Noordtunnel, voorbij Alblasserdam en Papendrecht, tot de afslag Sliedrecht. Dat is een langere snelwegrit dan naar de meeste plaatsen in ons bezorggebied, en in de spits staat het rond Ridderkerk en bij de tunnel regelmatig vast. Wie met het openbaar vervoer komt, neemt de MerwedeLingelijn vanaf Dordrecht, met de stations Sliedrecht Baanhoek en Sliedrecht. Voor onze bezorging betekent de afstand dat we meestal 35 tot 50 minuten nodig hebben. We noemen een realistische tijd en laten het weten als het onderweg toch langer duurt.",
            "Een huisfeest in een hoekwoning in Baanhoek-West, een familieavond aan de Merwede of een verjaardag in De Grienden: kies in ons <a href=\"/lachgas-tanks/\">overzicht van lachgastanks</a> het formaat dat bij je plannen past. De 2KG is handig voor een klein gezelschap, de 4KG en 10KG zijn bedoeld voor grotere groepen; voor de 10KG spreken we het aflevermoment vooraf af. Betalen doe je bij de deur, contant of via Tikkie, nooit vooraf. Alle leveringen zijn uitsluitend voor personen van 18 jaar en ouder en we controleren dit als daar aanleiding voor is. Lees ook onze pagina over <a href=\"/veilig-gebruik/\">veilig gebruik</a> voordat je bestelt.",
        ],
        "wijken": "Kerkbuurt, Centrum, Westwijk, Baanhoek, Baanhoek-West, De Grienden, Sliedrecht-Oost, Benedenveer, Molendijk",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Waarom duurt bezorgen in Sliedrecht langer dan in Rotterdam?", "Sliedrecht ligt aan het einde van de Drechtsteden-strook, ruim voorbij Papendrecht, en we rijden de volledige A15 door de Noordtunnel. Daarom houden we meestal 35 tot 50 minuten aan in plaats van de kortere tijden in de stad."],
            ["Komen jullie ook in Baanhoek-West en bij Benedenveer?", "Zeker, we bezorgen in alle woonbuurten van Sliedrecht, van de nieuwbouw aan de westkant tot aan de oostelijke dorpsgrens bij Hardinxveld-Giessendam. Geef je adres door en we bevestigen het tijdstip."],
            ["Kan ik in Sliedrecht in het weekend bestellen?", "Ja, ook op vrijdag- en zaterdagavond en op zondag. Weekendavonden zijn druk, dus geef bij voorkeur ruim van tevoren door wanneer je de tank wilt ontvangen. Zie <a href=\"/lachgas-bezorgen-weekend/\">weekendbezorging</a> voor details."],
        ],
        "nearby": ["papendrecht", "alblasserdam", "dordrecht"],
        "lat": 51.822, "lon": 4.775,
    },
    {
        "slug": "alblasserdam",
        "name": "Alblasserdam",
        "kind": "dorp",
        "title": "Lachgas Alblasserdam | Via WhatsApp, 24/7 bezorgd",
        "description": "Lachgas bestellen in Alblasserdam? Lachgastanks bezorgd rond de Dam, in Blokweer, Souburgh en bij Kinderdijk. 24/7 via WhatsApp, alleen voor 18+.",
        "h1": "Lachgas Alblasserdam",
        "lead": "Lachgastanks aan huis in Alblasserdam, aan de monding van de Alblas in de Noord. Bestellen via WhatsApp, elke dag en nacht.",
        "intro": [
            "Alblasserdam ligt op de plek waar de Alblas uitmondt in de Noord, aan de rand van de Alblasserwaard en op een steenworp van de molens van Kinderdijk. Het dorp heeft een herkenbaar hart rond de Dam en de winkelstraat Cortgene, met daaromheen woonbuurten als Blokweer, Souburgh, Lange Steeg en Vinkenpolder, het Alblasserdamse deel van Kinderdijk en de nieuwe waterkant van Haven-Zuid. In al deze delen leveren wij lachgastanks aan de deur. Je plaatst je bestelling via WhatsApp: adres, formaat en gewenst tijdstip zijn voldoende. We koppelen terug met een haalbare levertijd en de prijs, en daarna gaat de koerier op pad.",
            "Vanaf Rotterdam rijden we over de A16 en de Van Brienenoordbrug naar knooppunt Ridderkerk, waar we de A15 richting Gorinchem oppakken; direct na de Noordtunnel nemen we de afslag Alblasserdam. Bij files in de tunnel rijden we via Hendrik-Ido-Ambacht en de Alblasserdamse brug op de N915 de Noord over. De Waterbus stopt aan de Kade in Alblasserdam en vaart naar de Erasmusbrug, en vanaf Ridderkerk vaart in het seizoen een veerverbinding naar Kinderdijk. Door de ligging aan de overkant van de Noord en de drukte rond Ridderkerk komen we meestal uit op 35 tot 50 minuten. Die inschatting delen we eerlijk in het WhatsApp-gesprek.",
            "Alblasserdam is een dorp van gezinswoningen en verenigingsleven, en de aanleiding voor een bestelling is dan ook meestal huiselijk: een verjaardag in Blokweer, een borrel na een dag op het water of een feestje op een zolder aan de Dam. Bekijk de <a href=\"/lachgas-tanks/\">beschikbare lachgastanks</a> van 2KG, 4KG en 10KG en kies het formaat dat past bij de grootte van je groep. Afrekenen doe je bij de levering, contant of via Tikkie; we vragen geen aanbetaling. Omdat wij uitsluitend aan 18-plussers leveren, kan de koerier je om een geldig identiteitsbewijs vragen. Lees voor je bestelt de pagina over <a href=\"/veilig-gebruik/\">verantwoord omgaan met lachgas</a>.",
        ],
        "wijken": "Centrum, Dam, Cortgene, Blokweer, Souburgh, Lange Steeg, Vinkenpolder, Kinderdijk, Haven-Zuid, Nieuwland",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang is de bezorgtijd in Alblasserdam?", "Meestal tussen 35 en 50 minuten na onze bevestiging. We moeten de Noord oversteken via de A15 of de Alblasserdamse brug, en vooral in de avondspits kost dat extra tijd ten opzichte van de Rotterdamse wijken."],
            ["Bezorgen jullie ook in Kinderdijk?", "In het deel van Kinderdijk dat bij de gemeente Alblasserdam hoort wel. Ligt je adres net over de gemeentegrens in Molenlanden, stuur dan je postcode via WhatsApp; dan kijken we of het past."],
            ["Hoe weet ik of een bericht echt van Lachgas Rotterdam komt?", "Wij vragen nooit om vooruitbetaling en bevestigen altijd adres, tijd en prijs in één bericht. Twijfel je over een account dat zich als ons voordoet, lees dan <a href=\"/whatsapp-oplichting-herkennen/\">hoe je oplichting herkent</a>."],
        ],
        "nearby": ["hendrik-ido-ambacht", "papendrecht", "ridderkerk"],
        "lat": 51.865, "lon": 4.660,
    },
    {
        "slug": "numansdorp",
        "name": "Numansdorp",
        "kind": "dorp",
        "title": "Lachgas Numansdorp | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Numansdorp? Lachgastanks bezorgd in het dorp, de Torensteepolder en de zuidelijke Hoeksche Waard. 24/7 via WhatsApp, alleen 18+.",
        "h1": "Lachgas Numansdorp",
        "lead": "Lachgastanks bezorgd in Numansdorp en de zuidelijke Hoeksche Waard, aan het Hollandsch Diep. Bestel via WhatsApp.",
        "intro": [
            "Numansdorp ligt helemaal in het zuiden van de Hoeksche Waard, aan het Hollandsch Diep en vlak voor de Haringvlietbrug. Het dorp heeft een oude kern rond de Voorstraat, een jachthaven met het historische Fort Buitensluis ernaast en nieuwe woonstraten in de Torensteepolder. We bezorgen niet alleen in Numansdorp zelf, maar ook in omliggende kernen van de gemeente Hoeksche Waard, zoals Klaaswaal, Zuid-Beijerland en Strijen. Een bestelling plaats je via WhatsApp: noem je adres of postcode, het tankformaat en het moment waarop je wilt ontvangen. Wij reageren met een eerlijke tijdsindicatie en de prijs, zodat er onderweg geen verrassingen zijn.",
            "De rit vanuit Rotterdam gaat via het Vaanplein de A29 op, door de Heinenoordtunnel onder de Oude Maas en dan in één rechte lijn door het open polderlandschap van de Hoeksche Waard naar de afslag Numansdorp. Werkzaamheden of een afgesloten tunnelbuis kunnen die route flink vertragen; dan wijken we uit via de Kiltunnel vanaf Dordrecht. Met het openbaar vervoer kom je er met de streekbussen vanaf Rotterdam Zuidplein, en in de zomer vaart een voet- en fietsveer naar Willemstad. Voor onze koeriers is dit een echte buitenrit, dus de levertijd is meestal 35 tot 50 minuten.",
            "Bestellingen uit Numansdorp komen vaak van een tuinfeest, een verjaardag in een vrijstaande woning of een avond in een huisje bij de haven. Welke tank je nodig hebt, hangt af van de groep: bekijk de <a href=\"/lachgas-tanks/\">lachgastanks van 2KG, 4KG en 10KG</a> en vraag ons gerust om advies. De prijs bevestigen we vooraf via WhatsApp en je betaalt pas bij levering, contant of met een Tikkie. Levering is uitsluitend mogelijk aan personen van 18 jaar of ouder; houd een legitimatiebewijs bij de hand. Verantwoord gebruik begint bij goede informatie, daarom verwijzen we je graag naar onze pagina <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Voorstraat, Centrum, Haven, Fort Buitensluis, Torensteepolder, Klaaswaal, Zuid-Beijerland, Strijen, Westmaas, Mijnsheerenland",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Numansdorp?", "Houd rekening met meestal 35 tot 50 minuten. Numansdorp ligt aan de zuidrand van de Hoeksche Waard, dus de koerier rijdt de volledige A29 vanaf het Vaanplein af. Bij werkzaamheden aan de Heinenoordtunnel laten we het direct weten."],
            ["Bezorgen jullie ook in Klaaswaal, Strijen en Zuid-Beijerland?", "Ja, de kleinere kernen rond Numansdorp vallen binnen ons werkgebied in de Hoeksche Waard. Omdat de afstand tussen de dorpen oploopt, kan de tijd per kern iets verschillen; we geven dat vooraf aan."],
            ["Kan ik in Numansdorp met spoed bestellen?", "Spoed is mogelijk, maar door de afstand blijft de ondergrens realistisch gezien rond de 35 minuten. Geef aan dat het snel moet, dan plannen we de eerstvolgende koerier in. Meer op <a href=\"/lachgas-spoedbezorging/\">spoedbezorging</a>."],
        ],
        "nearby": ["oud-beijerland", "spijkenisse", "barendrecht"],
        "lat": 51.733, "lon": 4.435,
    },
    {
        "slug": "middelharnis",
        "name": "Middelharnis",
        "kind": "dorp",
        "title": "Lachgas Middelharnis | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Middelharnis? Lachgastanks bezorgd in Middelharnis, Sommelsdijk en de kernen van Goeree-Overflakkee. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas Middelharnis",
        "lead": "Lachgastanks bezorgd op Goeree-Overflakkee, met Middelharnis en Sommelsdijk als uitvalsbasis. Bestellen via WhatsApp, met realistische reistijd.",
        "intro": [
            "Middelharnis is de grootste kern van Goeree-Overflakkee en vormt samen met het aangrenzende Sommelsdijk het winkel- en voorzieningenhart van het eiland. Rond de oude haven en de Kaai liggen de historische straten, daaromheen de naoorlogse buurten en aan de rand de nieuwere woonwijk Westplaat. Vanuit Middelharnis bedienen we ook de omliggende dorpen, zoals Dirksland, Nieuwe-Tonge, Oude-Tonge, Stad aan ’t Haringvliet en Den Bommel. Bestellen gaat via WhatsApp: stuur je adres of postcode, het gewenste formaat en wanneer je de tank wilt hebben. Omdat het eiland verder weg ligt, zijn we extra duidelijk over de reistijd voordat je definitief bestelt.",
            "Goeree-Overflakkee is alleen via dammen en bruggen bereikbaar. Vanuit Rotterdam rijden we via het Vaanplein de A29 af, door de Heinenoordtunnel en over de Haringvlietbrug naar het Hellegatsplein, waar de N59 het eiland op gaat; bij Oude-Tonge volgen we de N215 naar Middelharnis. Een alternatief is de N57 over de Haringvlietdam vanaf Hellevoetsluis, met name wanneer de Haringvlietbrug door werkzaamheden of een storing dichtstaat. R-net-bussen vanaf Rotterdam Zuidplein rijden dezelfde kant op. Door al die kilometers over water en polder is de levertijd meestal 40 tot 60 minuten, en bij een afgesloten brug kan het langer duren.",
            "Een vakantiewoning aan het Haringvliet, een verjaardag in Sommelsdijk of een avond met vrienden in een eengezinswoning in Westplaat: kies uit <a href=\"/lachgas-tanks/\">onze lachgastanks</a> het formaat dat past bij je gezelschap. Voor een eilandrit plannen we de 10KG het liefst vooraf in, zodat de koerier in één keer goed rijdt. De prijs bevestigen we schriftelijk via WhatsApp; betalen gebeurt bij aflevering, contant of via Tikkie. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen zo nodig om legitimatie. Neem vooraf de aandachtspunten op onze pagina <a href=\"/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Centrum, Kaai, Haven, Westplaat, Sommelsdijk, Dirksland, Nieuwe-Tonge, Oude-Tonge, Stad aan ’t Haringvliet, Den Bommel, Melissant",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Waarom is de levertijd op Goeree-Overflakkee 40 tot 60 minuten?", "Het eiland ligt achter de Haringvlietbrug of de Haringvlietdam, en beide routes zijn lang en gevoelig voor storingen en zomerdrukte. We noemen daarom een ruime indicatie en melden het direct als een brug of dam dichtstaat."],
            ["Bezorgen jullie ook in Dirksland, Oude-Tonge en Stad aan ’t Haringvliet?", "Ja, we rijden naar de meeste kernen van Goeree-Overflakkee. Voor dorpen aan de oostkant zoals Ooltgensplaat of Achthuizen kan de tijd iets afwijken; geef je postcode door en we laten weten of het past."],
            ["Hoe betaal ik op Goeree-Overflakkee?", "Precies zoals in Rotterdam: contant of via Tikkie op het moment dat de koerier bij je is. We vragen geen voorschot, ook niet voor ritten naar het eiland. Zie <a href=\"/betalen-bij-levering/\">betalen bij levering</a>."],
        ],
        "nearby": ["ouddorp", "hellevoetsluis", "numansdorp"],
        "lat": 51.757, "lon": 4.166,
    },
    {
        "slug": "ouddorp",
        "name": "Ouddorp",
        "kind": "dorp",
        "title": "Lachgas Ouddorp | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Ouddorp? Lachgastanks bezorgd in het dorp, bij de vakantieparken en richting Goedereede en Stellendam. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas Ouddorp",
        "lead": "Lachgastanks bezorgd aan de Kop van Goeree, van het dorp tot de duinrand. Bestellen via WhatsApp, met een eerlijke indicatie van de reistijd.",
        "intro": [
            "Ouddorp ligt op de Kop van Goeree, tussen de Noordzee, de Grevelingen en het Haringvliet, en is in de zomer een van de drukste badplaatsen van Zuid-Holland. Het dorp zelf is compact, met de Ring en de Raadhuisstraat als middelpunt, en daaromheen liggen de duinen, de vuurtoren Westhoofd, de campings en vakantieparken achter de duinen en de buurdorpen Goedereede en Stellendam. Wij bezorgen in het dorp én op de parken, mits het park bezorging aan het adres toestaat. Bestellen gaat via WhatsApp: stuur adres of huisjesnummer, het gewenste tankformaat en het tijdstip, en wij bevestigen tijd en prijs.",
            "Vanuit Rotterdam zijn er twee wegen naar Ouddorp en beide zijn lang. Meestal rijden we over de A15 en de N57, via de Harmsenbrug langs Brielle en Hellevoetsluis, over de Haringvlietdam naar Stellendam en dan via de N215 het dorp in. Het alternatief loopt via de A29, de Haringvlietbrug en de N59 en N215 dwars over Goeree-Overflakkee. Op zomerse weekenddagen staat het op de N57 en bij de Brouwersdam regelmatig vast. Daarom houden we meestal 40 tot 60 minuten aan, en in het hoogseizoen geven we vooraf een ruimere inschatting.",
            "Een avond in een strandhuis op een vakantiepark, een vriendenweekend in een huurwoning bij het dorp of een verjaardag bij Ouddorpers thuis: in ons <a href=\"/lachgas-tanks/\">aanbod lachgastanks</a> vind je 2KG, 4KG en 10KG. Voor een korte vakantie is de 2KG of 4KG vaak het meest praktisch, zeker omdat je een tank na gebruik niet bij het restafval van het park mag laten. Betalen doe je bij aflevering, contant of via Tikkie. We leveren alleen aan gasten en bewoners van 18 jaar en ouder en vragen bij twijfel om een legitimatie. Lees ook de informatie over <a href=\"/veilig-gebruik/\">veilig gebruik</a>, ook als je op vakantie bent.",
        ],
        "wijken": "Centrum, Ring, Raadhuisstraat, Ouddorp Duin, Westhoofd, Oostdijk, Brouwersdam, Goedereede, Havenhoofd, Stellendam",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook op campings en vakantieparken in Ouddorp?", "Ja, zolang het park bezorging aan het huisje of de plaats toestaat en de receptie dat niet verbiedt. Geef het park en je huisjesnummer door, dan weet de koerier waar hij moet zijn. Op het strand en in de duinen bezorgen we niet."],
            ["Hoe lang moet ik in de zomer op mijn bestelling wachten?", "In het hoogseizoen kan het langer duren dan de gebruikelijke 40 tot 60 minuten, vooral op zaterdag wanneer de N57 en de dammen vol staan. We geven vooraf een ruime inschatting en houden je via WhatsApp op de hoogte."],
            ["Wat doe ik met de lege tank als ik weer naar huis ga?", "Laat hem nooit achter bij het park of in een vuilcontainer. Neem de lege tank mee en lever hem in bij een milieustraat, of vraag ons bij een volgende levering naar de mogelijkheden; zie <a href=\"/lege-tank-retour-rotterdam/\">lege tank retour</a>."],
        ],
        "nearby": ["middelharnis", "hellevoetsluis", "brielle"],
        "lat": 51.810, "lon": 3.930,
    },
    {
        "slug": "waddinxveen",
        "name": "Waddinxveen",
        "kind": "dorp",
        "title": "Lachgas Waddinxveen | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Waddinxveen? Lachgastanks bezorgd in Groenswaard, Zuidplas, Triangel en het centrum aan de Gouwe. Via WhatsApp, 24/7, alleen 18+.",
        "h1": "Lachgas Waddinxveen",
        "lead": "Lachgastanks aan de deur in Waddinxveen, aan de Gouwe tussen Gouda en Boskoop. Bestel via WhatsApp, elke dag en nacht.",
        "intro": [
            "Waddinxveen ligt aan de Gouwe, net ten noorden van Gouda en aan de rand van het Groene Hart. De beroemde hefbrug verbindt het dorp met de overkant van het kanaal. Woonbuurten als Groenswaard, de Bomenwijk, de Vondelwijk, de Oranjewijk en Zuidplas liggen rond het centrum met het Gouweplein, terwijl Triangel en ’t Suyt de nieuwere uitbreidingen aan de zuid- en westkant zijn. In al deze buurten bezorgen wij lachgastanks. Je stuurt een WhatsApp-bericht met je adres, het formaat dat je wilt en het gewenste moment, en krijgt van ons een bevestiging met levertijd en prijs.",
            "Vanuit Rotterdam rijden we de A20 uit tot Gouda, gaan bij knooppunt Gouwe over op de A12 en nemen daar de afslag richting Waddinxveen; via de N207 en de hefbrug of via de westelijke toegangswegen komen we het dorp in. Een rustig alternatief binnendoor is de N219 via Nieuwerkerk aan den IJssel en Zevenhuizen, handig als de A20 bij Moordrecht vastloopt. Het dorp heeft drie R-net-stations op de spoorlijn Gouda–Alphen: Waddinxveen, Waddinxveen Noord en Waddinxveen Triangel. Doordat we eerst de hele A20 moeten afrijden en de hefbrug soms openstaat voor scheepvaart, is onze levertijd hier meestal 35 tot 50 minuten. We noemen die tijd vooraf en passen hem aan als de weg tegenzit.",
            "Waddinxveen is een gezinsdorp met veel rijtjeshuizen en tuinen, en onze leveringen passen daarbij: een verjaardag in Groenswaard, een feestje in een nieuwbouwwoning in Triangel of een gezellige avond in de Vondelwijk. Kies in ons <a href=\"/lachgas-tanks/\">assortiment</a> uit 2KG, 4KG en 10KG; de kleinere formaten zijn voor de meeste huiselijke gelegenheden ruim voldoende. Je betaalt bij levering, contant of via Tikkie, na een vooraf bevestigde prijs. De leeftijdsgrens van 18 jaar hanteren we strikt, dus houd je identiteitsbewijs bij de hand als de koerier daarom vraagt. Onze pagina over <a href=\"/veilig-gebruik/\">veilig gebruik</a> is nuttig voor iedereen die voor het eerst bestelt.",
        ],
        "wijken": "Centrum, Gouweplein, Groenswaard, Bomenwijk, Vondelwijk, Oranjewijk, Zuidplas, Triangel, ’t Suyt, Coenecoop",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt het voordat jullie in Waddinxveen zijn?", "Meestal 35 tot 50 minuten. De rit over de A20 is langer dan naar onze stadswijken, en bij knooppunt Gouwe en op de A12 staat het in de spits vaak stil. We delen de verwachte aankomsttijd vooraf via WhatsApp."],
            ["Bezorgen jullie in Triangel en ’t Suyt, de nieuwe wijken?", "Ja, ook de nieuwbouw aan de zuid- en westkant van Waddinxveen valt binnen ons bezorggebied. Omdat straatnamen daar nog niet altijd in de navigatie staan, is het prettig als je je postcode en huisnummer compleet doorgeeft."],
            ["Kan ik zonder account of registratie bestellen in Waddinxveen?", "Ja, een WhatsApp-bericht is genoeg; je hoeft geen account aan te maken of een formulier in te vullen. We bewaren niet meer gegevens dan nodig voor de levering. Lees meer op <a href=\"/lachgas-bestellen-zonder-account/\">bestellen zonder account</a>."],
        ],
        "nearby": ["gouda", "boskoop", "zoetermeer"],
        "lat": 52.044, "lon": 4.650,
    },
    {
        "slug": "boskoop",
        "name": "Boskoop",
        "kind": "dorp",
        "title": "Lachgas Boskoop | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Boskoop? Lachgastanks bezorgd in het kwekersdorp aan de Gouwe: centrum, Snijdelwijk, Waterrijk en Boskoop-Oost. Via WhatsApp, 18+.",
        "h1": "Lachgas Boskoop",
        "lead": "Lachgastanks bezorgd in Boskoop, het boomkwekersdorp aan de Gouwe in het Groene Hart. Bestellen via WhatsApp, ook ’s avonds en ’s nachts.",
        "intro": [
            "Boskoop hoort sinds 2014 bij de gemeente Alphen aan den Rijn, maar is onmiskenbaar een dorp met een eigen gezicht: een lang lint aan weerszijden van de Gouwe, omgeven door honderden boomkwekerijen die samen de Greenport vormen. De hefbrug midden in het dorp koppelt de Zijde aan de oostkant. Wij bezorgen lachgastanks in het centrum, in Snijdelwijk bij het station, in de nieuwere wijken Waterrijk en Torenpad, aan het Reijerskoop en in Boskoop-Oost. Een bestelling plaatsen doe je via WhatsApp door adres, tankformaat en gewenste tijd te sturen; wij antwoorden met een haalbare levertijd en de prijs voordat we vertrekken.",
            "Boskoop ligt voor ons aan de buitenrand van het bezorggebied. We rijden vanuit Rotterdam de A20 uit, pakken bij knooppunt Gouwe kort de A12 en volgen vervolgens de N207 noordwaarts langs de Gouwe, langs Waddinxveen. Omdat de hefbruggen over de Gouwe geregeld openstaan voor de binnenvaart, kan de laatste etappe vertraging opleveren. Per spoor is het dorp bereikbaar met de R-net-trein Gouda–Alphen aan den Rijn, die stopt op Boskoop en Boskoop Snijdelwijk. Alles bij elkaar komen we meestal uit op 40 tot 60 minuten; we zeggen dat eerlijk vooraf en melden het via WhatsApp zodra er onderweg iets verandert.",
            "Boskoop is een dorp van kwekersfamilies, ruime percelen en verenigingsleven, en de meeste bestellingen horen bij een verjaardag, een tuinfeest achter een kwekerij of een avond met vrienden in Waterrijk. In ons <a href=\"/lachgas-tanks/\">overzicht van tanks</a> kies je tussen 2KG, 4KG en 10KG op basis van je groepsgrootte; vraag ons bij twijfel om een advies. De prijs staat vooraf vast via WhatsApp en wordt pas bij levering betaald, contant of met Tikkie. We leveren uitsluitend aan personen van 18 jaar en ouder en kunnen om een identiteitsbewijs vragen. Lees voorafgaand aan je bestelling de pagina <a href=\"/veilig-gebruik/\">veilig gebruik</a> rustig door.",
        ],
        "wijken": "Centrum, Zijde, Reijerskoop, Snijdelwijk, Waterrijk, Torenpad, Boskoop-Oost, Biezen, Laag Boskoop",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Waarom rekenen jullie voor Boskoop 40 tot 60 minuten?", "Boskoop ligt voorbij Gouda en Waddinxveen, aan het einde van onze route door het Groene Hart. De A20, de A12 en de N207 zijn samen een lange rit en de hefbruggen over de Gouwe gaan regelmatig open; daarom nemen we een ruime marge."],
            ["Komen jullie ook aan de oostkant van de Gouwe en bij de kwekerijen?", "Ja, we bezorgen in heel Boskoop, dus ook in Boskoop-Oost en op adressen tussen de kwekerijen. Geef bij een afgelegen perceel een duidelijke omschrijving van de oprit of ingang mee, dan vindt de koerier je sneller."],
            ["Kan ik in Boskoop een lachgastank laten bezorgen voor een feest in de tuin?", "Dat kan. Voor een tuinfeest of een grotere groep is de 4KG of 10KG vaak geschikter; we stemmen het aflevermoment dan vooraf met je af. Meer informatie vind je op <a href=\"/lachgas-feest-evenement/\">lachgas voor feest en evenement</a>."],
        ],
        "nearby": ["waddinxveen", "gouda", "zoetermeer"],
        "lat": 52.075, "lon": 4.655,
    },
    {
        "slug": "den-haag",
        "name": "Den Haag",
        "kind": "stad",
        "title": "Lachgas Den Haag | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Den Haag? Lachgastanks bezorgd in Centrum, Scheveningen, Laak, Escamp, Segbroek en Haagse Hout. Via WhatsApp, 24/7, alleen voor 18+.",
        "h1": "Lachgas Den Haag",
        "lead": "Lachgastanks bezorgd in alle acht stadsdelen van Den Haag, vanuit Rotterdam over de A13 en de A4. Bestel via WhatsApp, dag en nacht.",
        "intro": [
            "Den Haag is de derde stad van het land en bestaat uit acht stadsdelen die onderling sterk verschillen. Het Centrum met het Binnenhof, de Grote Markt en het Zeeheldenkwartier, het mondaine Scheveningen met de boulevard en het Statenkwartier, het compacte Laak rond station Hollands Spoor en de Binckhorst, het grote Escamp met Morgenstond, Leyenburg en Wateringse Veld, Loosduinen met Kijkduin, het groene Haagse Hout met Bezuidenhout, Benoordenhout en Mariahoeve, het jonge Leidschenveen-Ypenburg en Segbroek met de Bomenbuurt en het Regentessekwartier. In al deze delen bezorgen wij lachgastanks. Bestellen doe je via WhatsApp met je adres, het gewenste formaat en het tijdstip.",
            "Vanuit Rotterdam zijn er twee logische routes: de A13 via Delft naar knooppunt Ypenburg, of de A4 langs Delft-Zuid die bij hetzelfde knooppunt uitkomt. Daarna gaat het via het Prins Clausplein en de Utrechtsebaan de stad in, of via de A4 en de N14 naar de noordelijke stadsdelen. Voor Scheveningen en Segbroek rijden we meestal om via de N14 of de Noordwestelijke Hoofdroute; voor Escamp en Loosduinen zijn de A4 en de Lozerlaan handiger. Per spoor ben je er met de intercity naar Den Haag HS en Centraal of met metro E uit Rotterdam. Door de afstand en het Haagse stadsverkeer is onze levertijd meestal 40 tot 60 minuten.",
            "Een studentenhuis in het Zeeheldenkwartier, een appartement aan de Scheveningse boulevard, een gezinswoning in Leidschenveen of een huisfeest in Laak: welk formaat je nodig hebt, hangt af van de grootte van de groep. Bekijk daarvoor onze <a href=\"/lachgas-tanks/\">lachgastanks van 2KG, 4KG en 10KG</a>. Houd in de binnenstad en Scheveningen rekening met parkeerregels; een duidelijk afleveradres helpt de koerier. Betalen doe je bij levering, contant of via Tikkie, nadat de prijs via WhatsApp is bevestigd. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen om legitimatie als dat nodig is. Lees vooraf ook onze informatie over <a href=\"/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Centrum, Zeeheldenkwartier, Scheveningen, Statenkwartier, Laak, Escamp, Loosduinen, Haagse Hout, Leidschenveen-Ypenburg, Segbroek",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Den Haag vanuit Rotterdam?", "Meestal 40 tot 60 minuten. De A13 en de A4 zijn op zich snel, maar rond Ypenburg, het Prins Clausplein en in de Haagse binnenstad lopen we vertraging op. Voor Scheveningen en Loosduinen zit je eerder aan de bovenkant van die marge."],
            ["Bezorgen jullie in alle Haagse stadsdelen, ook Scheveningen en Loosduinen?", "Ja, van Leidschenveen-Ypenburg tot Kijkduin en van Laak tot Benoordenhout. Alleen in de drukste delen van Scheveningen kan de koerier je vragen om even naar een plek te komen waar hij kort kan stoppen; dat spreken we vooraf af."],
            ["Gelden er in Den Haag andere regels voor lachgas dan in Rotterdam?", "Lachgas valt landelijk onder de Opiumwet, en gemeenten kunnen daarbovenop in de APV gebieden aanwijzen waar gebruik op straat verboden is. Veel gemeenten, waaronder Den Haag, hebben zulke bepalingen; raadpleeg de gemeente voor de actuele tekst. Zie ook <a href=\"/lachgas-informatie/is-lachgas-legaal-in-nederland/\">is lachgas legaal in Nederland</a>."],
        ],
        "nearby": ["rijswijk", "leidschendam-voorburg", "delft"],
        "lat": 52.078, "lon": 4.313,
    },
    {
        "slug": "rijswijk",
        "name": "Rijswijk",
        "kind": "stad",
        "title": "Lachgas Rijswijk | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Rijswijk? Lachgastanks bezorgd in Oud-Rijswijk, Te Werve, Steenvoorde, de Muziekbuurt en RijswijkBuiten. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas Rijswijk",
        "lead": "Lachgastanks bezorgd in Rijswijk, ingeklemd tussen Den Haag en Delft. Bestel via WhatsApp en ontvang vooraf een eerlijke tijdsindicatie.",
        "intro": [
            "Rijswijk ligt tussen Den Haag en Delft en wordt door de A4 en de A13 aan twee kanten omsloten. De gemeente combineert een oude dorpskern, Oud-Rijswijk rond de Herenstraat en het Rijswijkse Bos, met naoorlogse woonwijken als Te Werve, Leeuwendaal, Cromvliet, Steenvoorde en de Muziekbuurt, het winkelcentrum In de Bogaard en het kantorengebied Plaspoelpolder. Aan de zuidkant groeit RijswijkBuiten met de buurten Sion en ’t Haantje. Wij bezorgen lachgastanks in heel Rijswijk. Je stuurt via WhatsApp je adres, het tankformaat en het gewenste tijdstip; wij reageren met een bevestiging van tijd en prijs.",
            "Vanuit Rotterdam is de A13 onze vaste route: langs Delft tot knooppunt Ypenburg, daarna kort de A4 en bij de afslag Rijswijk via de Prinses Beatrixlaan de wijken in. Voor RijswijkBuiten en Sion verlaten we de A13 al bij Delft-Noord. Het openbaar vervoer is hier uitstekend: station Rijswijk ligt ondergronds aan de spoorlijn Rotterdam–Den Haag en tram 1 rijdt via Rijswijk tussen Delft en Scheveningen. Toch blijft het voor onze koeriers een rit van ruim twintig kilometer door een druk stuk Randstad, met Ypenburg als bekend knelpunt, dus de levertijd is meestal 40 tot 60 minuten. Wat realistisch is, hoor je vooraf.",
            "Rijswijk heeft veel appartementen uit de jaren zestig en zeventig, maar ook ruime gezinswoningen in RijswijkBuiten en karakteristieke panden in Oud-Rijswijk, en de aanleiding voor een bestelling verschilt even sterk: een verjaardag, een housewarming of een avond met vrienden. In ons <a href=\"/lachgas-tanks/\">assortiment lachgastanks</a> staan de 2KG, 4KG en 10KG met uitleg over welk formaat bij welke groep past. Je betaalt bij levering, contant of via Tikkie, op basis van een prijs die we vooraf hebben bevestigd. We leveren alleen aan volwassenen van 18 jaar en ouder en controleren dat bij twijfel. De pagina <a href=\"/veilig-gebruik/\">veilig gebruik</a> raden we iedereen aan vooraf te lezen.",
        ],
        "wijken": "Oud-Rijswijk, Herenstraat, Te Werve, Leeuwendaal, Cromvliet, Steenvoorde, Muziekbuurt, In de Bogaard, Plaspoelpolder, RijswijkBuiten, Sion",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Hoe snel kunnen jullie in Rijswijk leveren?", "Meestal binnen 40 tot 60 minuten na bevestiging. Rijswijk ligt aan het einde van de A13, en rond knooppunt Ypenburg en op de Prinses Beatrixlaan is het vooral in de spits druk. Buiten de spits zitten we vaker aan de onderkant van die marge."],
            ["Bezorgen jullie ook in appartementencomplexen en bij In de Bogaard?", "Ja. Bij flats en complexen rond het winkelcentrum vragen we je om je volledige adres met etage of portiek door te geven, zodat de koerier niet hoeft te zoeken. We leveren aan de deur en niet aan afhaalpunten."],
            ["Ik logeer in een hotel in Rijswijk; kunnen jullie daar bezorgen?", "Dat kan, mits het hotel levering aan gasten toestaat en je zelf aanwezig bent om te ontvangen en je leeftijd aan te tonen. We leveren nooit bij een receptie af. Meer op <a href=\"/lachgas-hotel-en-bezoekers/\">lachgas voor hotelgasten en bezoekers</a>."],
        ],
        "nearby": ["den-haag", "delft", "leidschendam-voorburg"],
        "lat": 52.037, "lon": 4.325,
    },
    {
        "slug": "leidschendam-voorburg",
        "name": "Leidschendam-Voorburg",
        "kind": "gemeente",
        "title": "Lachgas Leidschendam-Voorburg | Via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Leidschendam-Voorburg? Lachgastanks bezorgd in Voorburg, Leidschendam en Stompwijk, van de Vliet tot The Mall.",
        "h1": "Lachgas Leidschendam-Voorburg",
        "lead": "Lachgastanks bezorgd in Voorburg, Leidschendam en Stompwijk, aan de Vliet ten oosten van Den Haag. Bestellen via WhatsApp, met realistische reistijd.",
        "intro": [
            "Leidschendam-Voorburg is een gemeente van drie kernen aan de oostflank van Den Haag. Voorburg, met de Herenstraat en het Romeinse verleden van Forum Hadriani, ligt tegen de Utrechtsebaan en station Laan van NOI; Leidschendam groeide rond de Sluis in de Vliet en kent woonwijken als De Heuvel, Prinsenhof en Leidschendam-Zuid, plus het winkelgebied van The Mall of the Netherlands; Stompwijk is het landelijke dorp aan de kant van Zoeterwoude. Wij bezorgen lachgastanks in alle drie de kernen. Bestellen doe je via WhatsApp met je adres, het gewenste formaat en het moment van levering; daarna krijg je een bevestiging met tijd en prijs.",
            "Onze route vanuit Rotterdam gaat over de A13 of de A4 naar knooppunt Ypenburg en dan langs het Prins Clausplein. Voor Voorburg nemen we daar de A12 richting het centrum en de afslag Voorburg; voor Leidschendam blijven we op de A4 en rijden we via de N14 en de Sijtwendetunnel de kern in. Stompwijk bereiken we via de A4 en de Stompwijkseweg. Met het openbaar vervoer stap je uit op station Voorburg, Leidschendam-Voorburg of Laan van NOI, terwijl RandstadRail 3 en 4 bij Voorburg ’t Loo stoppen en tram 2 en 6 bij Leidsenhage eindigen. Door de afstand en de drukte rond het Prins Clausplein is onze levertijd meestal 40 tot 60 minuten.",
            "De gemeente heeft een gemengd woningaanbod: vooroorlogse herenhuizen in Voorburg, flats en eengezinswoningen in Leidschendam en boerderijen rond Stompwijk, en onze bestellingen komen daar overal vandaan, van een verjaardag tot een afstudeerfeest. Bekijk ons <a href=\"/lachgas-tanks/\">aanbod lachgastanks</a> om te zien of de 2KG, 4KG of 10KG het beste bij je gezelschap past. De prijs wordt vooraf via WhatsApp bevestigd en je betaalt bij levering, contant of via Tikkie. Leveren doen we uitsluitend aan personen van 18 jaar en ouder; de koerier kan daarvoor om een legitimatiebewijs vragen. Lees vooraf onze pagina over <a href=\"/veilig-gebruik/\">veilig gebruik</a>, zodat je weet waar je op moet letten.",
        ],
        "wijken": "Voorburg, Herenstraat, Bovenveen, Essesteijn, ’t Loo, Leidschendam-Centrum, De Heuvel, Prinsenhof, The Mall of the Netherlands, Stompwijk",
        "levertijd": "meestal binnen 40 tot 60 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Leidschendam-Voorburg?", "Meestal 40 tot 60 minuten. De gemeente ligt aan de Haagse kant van ons werkgebied, en de A4, het Prins Clausplein en de Utrechtsebaan zijn in de spits traag. Voorburg ligt iets dichterbij dan Leidschendam en Stompwijk, maar het verschil is klein."],
            ["Bezorgen jullie ook in Stompwijk en het buitengebied?", "Ja, Stompwijk en de verspreide adressen in de polders eromheen vallen binnen ons gebied. Door de smalle polderwegen kan het er iets langer duren; geef daarom een goede omschrijving van je adres mee."],
            ["Kan ik ook ’s nachts bestellen in Voorburg of Leidschendam?", "Ja, onze WhatsApp-lijn is 24 uur per dag bereikbaar. Ook midden in de nacht kun je bestellen; de wegen zijn dan leeg, maar de kilometers blijven dezelfde, dus de indicatie verandert niet. Lees meer op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a>."],
        ],
        "nearby": ["den-haag", "rijswijk", "zoetermeer"],
        "lat": 52.085, "lon": 4.395,
    },
]
