# -*- coding: utf-8 -*-
# West-Brabant: 16 plaatsen voor lachgasbrabant.nl (gebied-schema uit BRIEF_TEMPLATE.md, aangevuld met "region" en "gemeente").
AREAS = [
{"slug": "breda", "name": "Breda", "kind": "stad", "region": "west-brabant", "gemeente": "Breda",
 "title": "Lachgas bestellen Breda | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Breda? Lachgastanks 2KG, 4KG en 10KG verzegeld bezorgd van het Centrum tot de Haagse Beemden, meestal binnen 30 tot 45 minuten. 18+.",
 "h1": "Lachgas bezorgen in Breda",
 "lead": "Lachgastanks aan huis in heel Breda, van de Haagse Beemden tot Bavel. Bestel via WhatsApp, wij bevestigen vooraf de prijs en het tijdvak.",
 "intro": [
  "Breda is de grootste stad van West-Brabant en het punt waar de A16, A58 en A27 elkaar rond de stad kruisen. Wij bezorgen lachgastanks in alle wijken: het Centrum rond de Grote Markt en de Havermarkt, Belcrum achter het station, het Ginneken, Princenhage, Brabantpark, de Haagse Beemden en de dorpen Prinsenbeek, Teteringen, Bavel en Ulvenhout. Bestellen gaat via WhatsApp: je stuurt je adres en de gewenste tank, wij sturen de prijs en een tijdvak terug. Pas als jij dat bevestigt, gaat de koerier rijden.",
  "Binnen Breda rijdt de koerier over de Noordelijke Rondweg en de Graaf Engelbertlaan snel van wijk naar wijk; voor Prinsenbeek en Teteringen gebruiken we de A16 en de Nieuwe Kadijk. Omdat de stad compact is en de meeste West-Brabantse ritten hier beginnen, valt Breda in de snelste band: meestal binnen 30 tot 45 minuten. Op vrijdag- en zaterdagavond kan het rond de Haagse Beemden of het uitgaansgebied bij de Havermarkt iets drukker zijn, daarom noemen we altijd een tijdvak in plaats van een exact tijdstip.",
  "Of je nu in een studentenhuis in de Belcrum zit, een verjaardag viert in Ulvenhout of met vrienden afspreekt in Brabantpark: kies de tank die past bij het aantal mensen en de duur van de avond. Alle maten staan op onze <a href=\"/lachgas-tanks/\">assortimentspagina</a>, van 2KG tot 10KG. Je betaalt contant of via Tikkie bij levering, nooit vooraf. De koerier controleert een geldig ID; onder de 18 leveren we niet. Lees vooraf ook onze <a href=\"/informatie/lachgas-bijwerkingen-en-eerste-hulp/\">informatie over bijwerkingen en eerste hulp</a>."],
 "wijken": "Centrum, Ginneken, Princenhage, Haagse Beemden, Belcrum, Brabantpark, Prinsenbeek, Teteringen, Bavel, Ulvenhout",
 "levertijd": "meestal binnen 30 tot 45 minuten",
 "faq": [
  ["Bezorgen jullie ook in Prinsenbeek, Teteringen en Bavel?", "Ja, de dorpen die bij de gemeente Breda horen vallen onder dezelfde levertijd als de stad. Prinsenbeek bereiken we via de A16, Teteringen en Bavel via de oostkant van de stad. Geef in je WhatsApp-bericht het volledige adres door, dan plannen we de rit meteen in."],
  ["Kan ik lachgas laten bezorgen bij station Breda of op de Grote Markt?", "Nee, we leveren uitsluitend op een privéadres zoals een woning, studentenkamer of vakantieadres. Op straat, bij het station of op een terras bezorgen we niet; veel gemeenten verbieden lachgasgebruik in de openbare ruimte via de APV. Meer daarover lees je in ons <a href=\"/informatie/lachgas-regels-per-gemeente-brabant/\">artikel over gemeentelijke regels</a>."],
  ["Hoe laat kan ik in Breda nog bestellen?", "Onze WhatsApp staat dag en nacht aan, ook in het weekend. Na middernacht vragen we je rustig aan te bellen en de tank binnen aan te nemen, zodat buren in dichtbebouwde wijken als het Centrum of de Belcrum geen last hebben. Zie ook onze pagina over <a href=\"/service/nachtbezorging/\">nachtbezorging</a>."]],
 "nearby": ["etten-leur", "oosterhout", "rijen"], "lat": 51.589, "lon": 4.776},

{"slug": "bergen-op-zoom", "name": "Bergen op Zoom", "kind": "stad", "region": "west-brabant", "gemeente": "Bergen op Zoom",
 "title": "Lachgas bestellen Bergen op Zoom | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Bergen op Zoom? Verzegelde lachgastanks bezorgd in Gageldonk, Bergse Plaat en het centrum, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Bergen op Zoom",
 "lead": "Van de Grote Markt tot de Bergse Plaat: lachgastanks 2KG, 4KG en 10KG thuisbezorgd in Bergen op Zoom. Prijs en tijdvak bevestigen we vooraf via WhatsApp.",
 "intro": [
  "Bergen op Zoom ligt op de rand van de Brabantse Wal, met het Markiezenhof en de Peperbus als herkenningspunten in het centrum. Wij bezorgen in de hele stad: de binnenstad rond de Grote Markt, Gageldonk en Noordgeest aan de noordkant, Meilust, Warande, Fort-Zeekant en Borgvliet, de Bergse Plaat aan de Binnenschelde en de nieuwbouw in De Markiezaten. Een bestelling plaats je via WhatsApp met je adres en de gewenste maat tank; wij antwoorden met de prijs en een tijdvak, waarna jij akkoord geeft.",
  "Vanaf Breda is het ongeveer veertig kilometer over de A58 naar knooppunt Zoomland, waar de A4 aansluit en de randweg de stad in leidt. Die afstand is de reden dat Bergen op Zoom in band B valt: meestal binnen 45 tot 60 minuten. Met de trein zit je via de Zeeuwse lijn vanuit Roosendaal snel op station Bergen op Zoom, maar een lachgastank neem je liever niet mee in een volle coupé, dus laten we hem bij je thuis bezorgen, ook in Halsteren en Lepelstraat.",
  "Een avond in een appartement aan de Bergse Plaat vraagt om een andere tank dan een feest in een tuin in Borgvliet. Bekijk de maten op de pagina met <a href=\"/lachgas-tanks/\">lachgastanks</a>; twijfel je, dan denken we via WhatsApp mee. Betalen doe je contant of via Tikkie zodra de koerier er is, de tank is verzegeld. We leveren alleen aan personen van 18 jaar of ouder en vragen om een geldig identiteitsbewijs. Bewaar de tank rechtop en koel, zie onze tips over <a href=\"/informatie/lachgastank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."],
 "wijken": "Centrum, Gageldonk, Noordgeest, Meilust, Warande, Fort-Zeekant, Borgvliet, Bergse Plaat, De Markiezaten, Tuinwijk",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Leveren jullie ook in Halsteren en Lepelstraat?", "Ja, beide kernen horen bij de gemeente Bergen op Zoom en krijgen dezelfde indicatie van meestal 45 tot 60 minuten. Halsteren heeft een <a href=\"/lachgas-bezorgen/halsteren/\">eigen pagina</a> met meer informatie over de bezorging daar."],
  ["Is het druk in Bergen op Zoom tijdens Vastenavend of de kermis?", "Tijdens grote evenementen in de binnenstad zijn straten rond de Grote Markt vaak afgesloten en gelden er extra regels in de openbare ruimte. Bestel dan ruim van tevoren en kies een adres buiten het afgesloten gebied. Wij bezorgen nooit op straat of op een feestterrein, alleen op een privéadres."],
  ["Wat gebeurt er met een lege tank in Bergen op Zoom?", "Een lege lachgastank hoort niet bij het restafval. Lever hem in bij de milieustraat van de gemeente, of vraag via WhatsApp of de koerier hem bij een volgende levering kan meenemen. Meer uitleg vind je in ons artikel over het <a href=\"/informatie/lege-lachgastank-inleveren-brabant/\">inleveren van lege tanks</a>."]],
 "nearby": ["halsteren", "roosendaal", "hoogerheide"], "lat": 51.495, "lon": 4.292},

{"slug": "roosendaal", "name": "Roosendaal", "kind": "stad", "region": "west-brabant", "gemeente": "Roosendaal",
 "title": "Lachgas bestellen Roosendaal | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Roosendaal? Lachgastanks 2KG, 4KG en 10KG bezorgd in Kroeven, Tolberg, Kortendijk en centrum, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Roosendaal",
 "lead": "Lachgastanks thuisbezorgd in Roosendaal, van de Nieuwe Markt tot Tolberg en de kerkdorpen. Eén appje met je adres en je weet binnen een paar minuten de prijs en het tijdvak.",
 "intro": [
  "Roosendaal is het spoorknooppunt van West-Brabant: op het station komen de lijnen uit Breda, Dordrecht, Vlissingen en Antwerpen samen. De stad zelf is overzichtelijk opgebouwd rond het centrum met de Nieuwe Markt en de Markt. Wij bezorgen in alle wijken, waaronder Kalsdonk, Burgerhout, Kroeven, Langdonk, Kortendijk, Tolberg en Westrand, en in de dorpen Wouw, Heerle, Moerstraten, Nispen en Wouwse Plantage. Stuur via WhatsApp je adres en de tank die je wilt; je krijgt de prijs en een tijdvak terug voordat we vertrekken.",
  "De A58 loopt langs de noordkant van de stad en kruist bij knooppunt De Stok de A17 richting Moerdijk. Vanaf Breda is dat zo’n 25 kilometer, een rit van ongeveer een halfuur voordat de koerier de afslag naar het centrum of Tolberg neemt. Daarom hoort Roosendaal bij band B: meestal binnen 45 tot 60 minuten. Op koopavonden en bij drukte rond het outletcentrum aan de A58 kan het rond de afslagen even vastlopen, dus houden we een marge in het tijdvak dat we bevestigen.",
  "Een rustige avond in een rijtjeshuis in Kortendijk of een groter feest in een schuur bij Wouw: de tankmaat bepaalt hoe lang je toekomt. In ons <a href=\"/lachgas-tanks/\">overzicht van lachgastanks</a> staan 2KG, 4KG en 10KG naast elkaar met uitleg. Je betaalt bij levering, contant of via Tikkie, en de koerier controleert je leeftijd met een ID-bewijs; 18+ is de harde grens. Combineer lachgas niet met alcohol, lees waarom in ons <a href=\"/informatie/lachgas-en-alcohol/\">artikel over lachgas en alcohol</a>."],
 "wijken": "Centrum, Kalsdonk, Burgerhout, Kroeven, Langdonk, Kortendijk, Tolberg, Westrand, Wouw, Nispen",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie in Wouw, Nispen en de andere kerkdorpen van Roosendaal?", "Ja, de kerkdorpen van de gemeente Roosendaal zitten in onze route. Voor Wouwse Plantage of Nispen, dicht bij de Belgische grens, kan de rit aan de bovenkant van het tijdvak uitkomen; we geven dat eerlijk aan in de bevestiging via WhatsApp."],
  ["Kunnen jullie leveren bij station Roosendaal als ik met de trein aankom?", "Nee, we bezorgen niet op het stationsplein of elders in de openbare ruimte. Geef het adres door waar je die avond verblijft, bijvoorbeeld bij vrienden in Burgerhout of een huis in Kalsdonk vlak bij het spoor, dan komt de koerier daar langs zodra je er bent."],
  ["Wat als ik mijn bestelling in Roosendaal wil wijzigen?", "Zolang de koerier nog niet onderweg is, pas je de maat of het adres gewoon aan in hetzelfde WhatsApp-gesprek. Is hij al gaan rijden, dan overleggen we wat nog kan. De prijs die we vooraf bevestigden, geldt voor de tank die uiteindelijk wordt geleverd. Lees ook onze uitleg over <a href=\"/service/bestellen-via-whatsapp/\">bestellen via WhatsApp</a>."]],
 "nearby": ["oudenbosch", "sint-willebrord", "bergen-op-zoom"], "lat": 51.531, "lon": 4.465},

{"slug": "oosterhout", "name": "Oosterhout", "kind": "stad", "region": "west-brabant", "gemeente": "Oosterhout",
 "title": "Lachgas bestellen Oosterhout | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Oosterhout? Lachgastanks verzegeld bezorgd in Oosterheide, Dommelbergen, Vrachelen en centrum, meestal binnen 30 tot 45 minuten. 18+.",
 "h1": "Lachgas bezorgen in Oosterhout",
 "lead": "Lachgastanks aan huis in Oosterhout en in Den Hout, Dorst en Oosteind. Via WhatsApp krijg je vooraf de prijs en een tijdvak bevestigd.",
 "intro": [
  "Oosterhout ligt direct ten noordoosten van Breda, ingeklemd tussen de A27 en het Wilhelminakanaal. Het centrum rond de Markt met de Sint-Jansbasiliek en winkelcentrum Arendshof is de kern; daaromheen liggen de woonwijken Slotjes, Oosterheide, Strijen, Vrachelen en Dommelbergen, en verder weg de kerkdorpen Den Hout, Dorst en Oosteind. In al die buurten bezorgen we lachgastanks 2KG, 4KG en 10KG. Een bestelling begint met een WhatsApp-bericht met je adres; wij reageren met de prijs en het tijdvak waarin we kunnen komen.",
  "Oosterhout heeft geen treinstation, de bus naar Breda is hier het openbaar vervoer. Voor onze koerier is dat geen probleem: via de A27 of de Bredaseweg sta je in een kwartier vanuit Breda aan de Bovensteweg, de ringweg aan de oostkant. Door die korte afstand hoort Oosterhout bij de snelste band, meestal binnen 30 tot 45 minuten. Bij werkzaamheden rond knooppunt Hooipolder of files op de A27 nemen we de binnendoorroute via Teteringen, zodat het tijdvak haalbaar blijft.",
  "Een borrel in een appartement aan het Wilhelminakanaal of een tuinfeest in Dorst vraagt om een passende tank. Op onze pagina met <a href=\"/lachgas-tanks/\">lachgastanks</a> lees je per maat waarvoor hij geschikt is. Verzegeld in de hand van de koerier, contant of met Tikkie afgerekend, en altijd pas na een blik op je identiteitsbewijs: zonder 18+ geen levering. Ga na gebruik niet rijden; waarom dat ook voor lachgas geldt, lees je bij <a href=\"/informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>."],
 "wijken": "Centrum, Slotjes, Oosterheide, Strijen, Vrachelen, Dommelbergen, Den Hout, Dorst, Oosteind",
 "levertijd": "meestal binnen 30 tot 45 minuten",
 "faq": [
  ["Horen Den Hout, Dorst en Oosteind bij de levertijd van Oosterhout?", "Ja, de drie kerkdorpen tellen gewoon mee in band A, dus ook daar meestal 30 tot 45 minuten. Dorst ligt aan de kant van Rijen langs de oude Rijksweg, Den Hout bereiken we via Vrachelen. Vermeld het dorp duidelijk in je bericht."],
  ["Kan ik ’s nachts lachgas bestellen in Oosterhout?", "Dat kan, onze WhatsApp is 24 uur per dag bereikbaar. In rustige woonwijken als Dommelbergen of Slotjes vragen we je ’s nachts te zorgen dat iemand bij de deur staat, zodat de koerier niet hoeft aan te bellen en de tank snel binnen is."],
  ["Mag ik lachgas gebruiken in het Slotpark of op de Markt in Oosterhout?", "Wij bezorgen alleen op privéadressen en adviseren gebruik in de openbare ruimte te vermijden; gemeenten mogen dit via de APV verbieden en handhaven. Raadpleeg de APV van de gemeente Oosterhout of lees eerst ons artikel over <a href=\"/informatie/is-lachgas-legaal-in-nederland/\">de wet in Nederland</a>."]],
 "nearby": ["breda", "raamsdonksveer", "made"], "lat": 51.645, "lon": 4.860},

{"slug": "etten-leur", "name": "Etten-Leur", "kind": "stad", "region": "west-brabant", "gemeente": "Etten-Leur",
 "title": "Lachgas bestellen Etten-Leur | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Etten-Leur? Verzegelde lachgastanks bezorgd in De Keen, Grauwe Polder, Hooghuis en het centrum, meestal binnen 30 tot 45 minuten. 18+.",
 "h1": "Lachgas bezorgen in Etten-Leur",
 "lead": "Lachgastanks 2KG, 4KG en 10KG bezorgd in Etten-Leur, van de Markt tot Schoenmakershoek. WhatsApp ons je adres, wij bevestigen prijs en tijdvak.",
 "intro": [
  "Etten-Leur is uit twee dorpen gegroeid: Etten rond de Markt met het Van Gogh Kerkje en Leur rond de oude haven. Daartussen en daaromheen liggen de wijken De Keen, De Grient, Hooghuis, Banakkers, Sander-Banken, Grauwe Polder, De Streek en het nieuwere Schoenmakershoek. In al deze buurten bezorgen we lachgastanks aan de deur, ook in de appartementen boven het Winkelhart. Bestellen doe je via WhatsApp: adres en gewenste maat doorgeven, en wij sturen de prijs plus een tijdvak terug waar jij ja of nee op zegt.",
  "De A58 loopt langs de noordrand van Etten-Leur en verbindt de plaats in tien minuten met Breda; ook binnendoor via de Liesboslaan en het Liesbos kom je er snel. Daarom valt Etten-Leur net als Breda in de snelste band: meestal binnen 30 tot 45 minuten. Station Etten-Leur ligt aan de lijn Breda–Roosendaal, maar voor een lachgastank hoef je niet naar het perron: de koerier komt naar je voordeur, ook in Leur aan de kant van de haven.",
  "Voor een avond met een paar vrienden in Hooghuis kies je anders dan voor een groter feest in een tuin in De Streek. Vergelijk de maten op onze pagina met <a href=\"/lachgas-tanks/\">lachgastanks</a>, we helpen je via WhatsApp als je het niet zeker weet. Afrekenen gebeurt pas aan de deur, contant of via Tikkie, en de koerier vraagt om een ID; onder de 18 gaat de tank terug mee. Bij vragen over tintelingen of vermoeidheid helpt ons artikel over <a href=\"/informatie/lachgas-en-vitamine-b12/\">lachgas en vitamine B12</a>."],
 "wijken": "Centrum, Leur, De Keen, De Grient, Hooghuis, Banakkers, Sander-Banken, Grauwe Polder, De Streek, Schoenmakershoek",
 "levertijd": "meestal binnen 30 tot 45 minuten",
 "faq": [
  ["Hoe snel zijn jullie in Schoenmakershoek of De Keen?", "Beide wijken liggen aan de noordkant van Etten-Leur, dicht bij de A58, waardoor de koerier daar vaak als eerste is. De indicatie blijft dezelfde als voor de rest van de plaats: meestal 30 tot 45 minuten, met een bevestigd tijdvak vooraf."],
  ["Leveren jullie bij het station of in het Winkelhart van Etten-Leur?", "Nee, alleen op een woonadres of ander privéadres. Het Winkelhart, het stationsplein en de Markt zijn openbare ruimte en daar bezorgen we niet. Woon je boven een winkel in het centrum, geef dan duidelijk de ingang en het huisnummer door."],
  ["Kan ik een grotere tank bestellen voor een feest in Etten-Leur?", "Ja, naast 2KG en 4KG bezorgen we ook de 10KG voor grotere gezelschappen. Alle tanks komen verzegeld en de prijs hoor je vooraf via WhatsApp. Kijk op de pagina van de <a href=\"/lachgas-tanks/10kg/\">lachgastank 10KG</a> wat die maat inhoudt."]],
 "nearby": ["breda", "roosendaal", "sint-willebrord"], "lat": 51.571, "lon": 4.636},

{"slug": "zevenbergen", "name": "Zevenbergen", "kind": "dorp", "region": "west-brabant", "gemeente": "Moerdijk",
 "title": "Lachgas bestellen Zevenbergen | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Zevenbergen? Lachgastanks 2KG, 4KG en 10KG bezorgd in Zevenbergen, Klundert en Fijnaart, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Zevenbergen",
 "lead": "Lachgastanks thuisbezorgd in Zevenbergen en de andere kernen van de gemeente Moerdijk. Stuur je adres via WhatsApp en hoor meteen wat het kost en wanneer we er zijn.",
 "intro": [
  "Zevenbergen is de hoofdkern van de gemeente Moerdijk, een oud stadje waar de Roode Vaart weer door het centrum stroomt. Rond de Markt liggen de oudere straten; daaromheen de woonwijken Molengors, Lindonk, Serena en Bosselaar met de nieuwbouw in Bosselaar-Zuid. Wij bezorgen lachgastanks in heel Zevenbergen en in de andere kernen van Moerdijk: Klundert, Fijnaart, Willemstad, Standdaarbuiten, Zevenbergschen Hoek, Langeweg en het dorp Moerdijk. Appen met adres en maat volstaat; daarna hoor je van ons de prijs en het tijdvak en beslis jij.",
  "Vanuit Breda rijdt de koerier via de A16 naar knooppunt Klaverpolder en dan over de A17 naar de afslag Zevenbergen, of binnendoor via Terheijden, Wagenberg en de N285. Dat is zo’n twintig kilometer door open polderland; samen met de spreiding van de kernen over de gemeente maakt dat band B logisch: meestal binnen 45 tot 60 minuten. Station Zevenbergen ligt aan de stoptreinlijn Dordrecht–Roosendaal, maar de dorpen en het buitengebied zijn met de auto beter te bereiken dan met het spoor.",
  "Een verjaardag in een nieuwbouwhuis in Bosselaar-Zuid of een avond bij vrienden binnen de vesting van Willemstad: per gezelschap verschilt welke maat handig is. Op de pagina met <a href=\"/lachgas-tanks/\">onze lachgastanks</a> staat per maat een korte uitleg. De verzegeling zit er nog op als de koerier aanbelt; je rekent af met contant geld of een Tikkie en laat je ID zien, want jonger dan 18 krijgt bij ons niets. In de open polders rond Moerdijk kan het ’s winters stevig vriezen, lees daarom ook <a href=\"/informatie/lachgas-bij-kou-en-warmte/\">lachgas bij kou en warmte</a>."],
 "wijken": "Centrum, Markt, Molengors, Lindonk, Serena, Bosselaar, Bosselaar-Zuid, Klundert, Fijnaart, Willemstad",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie ook in Fijnaart, Klundert en Willemstad?", "Ja, alle kernen van de gemeente Moerdijk doen mee. Willemstad en Fijnaart liggen het verst van de A17, dus daar komt de koerier eerder aan het einde van het tijdvak van meestal 45 tot 60 minuten aan. Geef de kern altijd apart door in je WhatsApp-bericht."],
  ["Kunnen jullie leveren op het industrieterrein Moerdijk?", "Alleen op een adres waar je als privépersoon verblijft, bijvoorbeeld een woning in het dorp Moerdijk. Op bedrijfsterreinen, bij de haven of op parkeerplaatsen langs de A16 en A17 bezorgen we niet. Zo blijft de levering overzichtelijk en controleerbaar voor beide kanten."],
  ["Wat moet ik weten over de regels voor lachgas in Moerdijk?", "Lachgas valt sinds 1 januari 2023 onder lijst II van de Opiumwet; bezit en verkoop voor recreatief gebruik zijn verboden, met uitzonderingen voor medisch, technisch en voedingsgebruik. Daarnaast kan de gemeente via de APV regels stellen voor de openbare ruimte. Raadpleeg <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a> voor de actuele stand."]],
 "nearby": ["etten-leur", "oudenbosch", "breda"], "lat": 51.653, "lon": 4.603},

{"slug": "oudenbosch", "name": "Oudenbosch", "kind": "dorp", "region": "west-brabant", "gemeente": "Halderberge",
 "title": "Lachgas bestellen Oudenbosch | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Oudenbosch? Lachgastanks verzegeld bezorgd in Oudenbosch, Hoeven, Bosschenhoofd en Oud Gastel, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Oudenbosch",
 "lead": "Lachgastanks 2KG, 4KG en 10KG bezorgd in Oudenbosch en de rest van Halderberge. Je ontvangt vooraf de prijs en een tijdvak via WhatsApp.",
 "intro": [
  "Oudenbosch herken je van verre aan de koepel van de Basiliek, een verkleinde kopie van de Sint-Pieter in Rome, met daarnaast het voormalige internaat Saint Louis en het Arboretum. Het dorp is de grootste kern van de gemeente Halderberge, naast Hoeven, Bosschenhoofd, Oud Gastel en Stampersgat. Wij bezorgen lachgastanks in het centrum rond de Markt en de Fenkelstraat, in de wijken Albano, Velletri en Pagnevaart en in alle andere kernen. Via WhatsApp geef je adres en maat door; wij noemen de prijs en het tijdvak, en jij bepaalt of we komen.",
  "De koerier komt vanaf Breda over de A58 tot Hoeven en dan via de N640 het dorp in, of over de A17 bij Standdaarbuiten en Oud Gastel. Die ruim twintig kilometer en de laatste stukken over provinciale wegen maken dat Oudenbosch in band B valt: meestal binnen 45 tot 60 minuten. Station Oudenbosch aan de lijn Roosendaal–Dordrecht is handig voor bezoekers, maar een bestelling leveren we bij je op het adres, niet op het perron of het stationsplein.",
  "Een avond met z’n drieën in een appartement bij de Pagnevaart is iets anders dan een groot feest in een schuur bij Oud Gastel. Vergelijk daarom eerst de maten in ons <a href=\"/lachgas-tanks/\">tankoverzicht</a>. De prijs staat vast zodra wij die via WhatsApp hebben bevestigd; betalen gebeurt contant of via Tikkie bij de deur. De koerier controleert een geldig identiteitsbewijs, want 18+ geldt zonder uitzondering. Hoe je iemand helpt die onwel wordt, lees je bij <a href=\"/informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>."],
 "wijken": "Centrum, Markt, Fenkelstraat, Albano, Velletri, Pagnevaart, Hoeven, Bosschenhoofd, Oud Gastel, Stampersgat",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Leveren jullie in Hoeven en Bosschenhoofd ook binnen hetzelfde tijdvak?", "Ja, Hoeven en Bosschenhoofd liggen tussen Oudenbosch en de A58 en zijn voor onze koerier zelfs iets sneller te bereiken. Oud Gastel en Stampersgat liggen aan de westkant; ook daar is meestal 45 tot 60 minuten realistisch; het concrete tijdvak hoor je vooraf."],
  ["Kan ik lachgas laten bezorgen bij een vakantiehuisje bij Hoeven?", "Ja, een vakantieadres telt als privéadres zolang jij daar verblijft en zelf de deur opent. Geef het huisnummer of de naam van het park duidelijk door via WhatsApp en zorg dat je een geldig ID bij de hand hebt voor de leeftijdscontrole."],
  ["Wat als de koerier later is dan het tijdvak?", "Dat komt soms voor bij een ongeval op de A58 of een gesloten overweg in Oudenbosch zelf. We laten het dan via WhatsApp weten en noemen een nieuw tijdvak. Je betaalt pas bij levering, dus je zit nergens aan vast. Lees meer over hoe we tijdvakken bepalen bij <a href=\"/service/bezorgtijden-per-regio/\">bezorgtijden per regio</a>."]],
 "nearby": ["roosendaal", "etten-leur", "zevenbergen"], "lat": 51.588, "lon": 4.527},

{"slug": "steenbergen", "name": "Steenbergen", "kind": "stad", "region": "west-brabant", "gemeente": "Steenbergen",
 "title": "Lachgas bestellen Steenbergen | Bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Steenbergen? Verzegelde lachgastanks bezorgd in Steenbergen, Dinteloord en Kruisland, meestal binnen 60 tot 90 minuten. 18+.",
 "h1": "Lachgas bezorgen in Steenbergen",
 "lead": "Lachgastanks aan huis in Steenbergen en de omliggende dorpen in de polder. Via WhatsApp bevestigen we de prijs en een tijdvak voor we gaan rijden.",
 "intro": [
  "Steenbergen ligt in de uiterste noordwesthoek van Brabant, tussen de Steenbergse Vliet en de polders richting Zeeland. Het centrum rond de Markt en de Kaaistraat, de Gummaruskerk en de nieuwbouw in Buiten de Veste vormen de stad; verder horen Dinteloord, Kruisland, Nieuw-Vossemeer, De Heen en Welberg bij de gemeente. Lachgastanks 2KG, 4KG en 10KG brengen we tot in de kleinste van die kernen. Bestellen gaat via WhatsApp: je stuurt adres en maat, wij sturen prijs en tijdvak, en pas na jouw akkoord vertrekt de koerier.",
  "Sinds de A4 tussen Dinteloord en Bergen op Zoom open is, ligt Steenbergen aan de snelweg, maar vanuit Breda blijft het ruim veertig kilometer over de A58 en de A4. Dat is de reden dat Steenbergen in band C valt: meestal binnen 60 tot 90 minuten. Vanuit Bergen op Zoom gaat het sneller, via de A4 of de oude N259 door Halsteren. Een station is er niet; de bus rijdt naar Bergen op Zoom en Roosendaal, maar voor een tank wacht je gewoon thuis.",
  "Een avondje in een appartement aan de haven of een tuinfeest in Kruisland: de maat van de tank hangt af van het gezelschap. Kijk in ons <a href=\"/lachgas-tanks/\">assortiment lachgastanks</a> welke past. Elke tank komt verzegeld aan; afrekenen kan contant of via Tikkie, maar alleen nadat de koerier je identiteitsbewijs heeft gezien en je 18 of ouder blijkt. Wie voor het eerst bestelt, leest het best eerst de <a href=\"/veelgestelde-vragen/veiligheid/\">vragen over veiligheid</a>."],
 "wijken": "Centrum, Markt, Kaaistraat, Buiten de Veste, Dinteloord, Kruisland, Nieuw-Vossemeer, De Heen, Welberg",
 "levertijd": "meestal binnen 60 tot 90 minuten",
 "faq": [
  ["Waarom duurt bezorgen in Steenbergen langer dan in Bergen op Zoom?", "Steenbergen ligt verder van Breda en de kernen Dinteloord en Nieuw-Vossemeer liggen nog eens kilometers uit elkaar in de polder. Daarom rekenen we met band C: meestal 60 tot 90 minuten. Vanuit Bergen op Zoom is het via de A4 een kwartier, en als een koerier al in die buurt is, kan het sneller gaan."],
  ["Bezorgen jullie in Dinteloord en bij Nieuw Prinsenland?", "In Dinteloord zelf wel, op een woonadres. Op het agro- en foodcluster Nieuw Prinsenland en andere bedrijventerreinen langs de A4 leveren we niet. Vermeld in je WhatsApp-bericht dat het om Dinteloord gaat, dan houden we daar rekening mee in het tijdvak."],
  ["Kan ik lachgas bestellen voor een feest in een loods of schuur buiten Steenbergen?", "Dat kan als het een privéadres is waar jij als 18-plusser aanwezig bent en de tank aanneemt. Voor een afgelegen locatie bij De Heen of Welberg vragen we een duidelijke routebeschrijving. Lees vooraf ook ons artikel over <a href=\"/informatie/lachgastank-bewaren-en-vervoeren/\">het bewaren en vervoeren van een tank</a>."]],
 "nearby": ["halsteren", "bergen-op-zoom", "roosendaal"], "lat": 51.584, "lon": 4.316},

{"slug": "zundert", "name": "Zundert", "kind": "dorp", "region": "west-brabant", "gemeente": "Zundert",
 "title": "Lachgas bestellen Zundert | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Zundert? Lachgastanks 2KG, 4KG en 10KG bezorgd in Zundert, Rijsbergen, Wernhout en Achtmaal, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Zundert",
 "lead": "Lachgastanks thuisbezorgd in Zundert en de kerkdorpen tot aan de Belgische grens. WhatsApp ons je adres; prijs en tijdvak volgen voordat de koerier de N263 oprijdt.",
 "intro": [
  "Zundert is het dorp van het bloemencorso en de geboorteplaats van Vincent van Gogh, pal tegen de Belgische grens. De gemeente bestaat uit Zundert zelf, met de Markt en de Molenstraat als middelpunt, en de kerkdorpen Rijsbergen, Klein-Zundert, Wernhout en Achtmaal. Tussen de boomkwekerijen en aardbeienvelden staan veel vrijstaande huizen met ruimte voor een feest. We bezorgen lachgastanks op elk privéadres in de gemeente. Een bericht via WhatsApp met je adres en de gewenste maat is genoeg; de prijs en een tijdvak volgen daarna.",
  "De koerier komt vanaf Breda over de N263 door Rijsbergen of over de A16 met de afslagen bij Rijsbergen en Hazeldonk. Dat is zo’n zeventien kilometer naar het centrum, maar Achtmaal en Wernhout liggen weer een stuk verder en de buitenwegen zijn smal en donker. Daarom hanteren we voor de gemeente Zundert band B: meestal binnen 45 tot 60 minuten. Openbaar vervoer is beperkt tot de bus vanuit Breda, dus thuisbezorging is hier extra praktisch.",
  "Of het nu een verjaardag in Klein-Zundert is of een avond met vrienden na de kermis in Rijsbergen: kies de tank die bij je groep past via ons <a href=\"/lachgas-tanks/\">overzicht van lachgastanks</a>. Verzegeld geleverd, afrekenen bij de deur met contant geld of een Tikkie, en altijd een ID-controle omdat we onder de 18 niet leveren. Woon je vlak bij de grens: lachgas meenemen naar België kan andere regels raken, lees daarom ons artikel over <a href=\"/informatie/is-lachgas-legaal-in-nederland/\">de wet in Nederland</a>."],
 "wijken": "Centrum, Markt, Molenstraat, Klein-Zundert, Rijsbergen, Wernhout, Achtmaal, Wernhoutsburg",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie tijdens het corso in Zundert?", "Ja, maar op corsozondag en de dagen ervoor zijn delen van het centrum en de route afgesloten. Kies een adres buiten de afzettingen en bestel ruim op tijd; wij bezorgen nooit langs de route of op een feestterrein. Zie ook onze pagina over <a href=\"/service/feestdagen-en-evenementen/\">feestdagen en evenementen</a>."],
  ["Hoe lang duurt het naar Achtmaal of Wernhout?", "Beide dorpen liggen aan de buitenkant van de gemeente, dus de koerier komt daar eerder richting het einde van de indicatie van meestal 45 tot 60 minuten. Via WhatsApp hoor je vooraf een concreet tijdvak voor jouw adres."],
  ["Mag een vriend uit België bij mij in Zundert de tank aannemen?", "Dat mag, zolang die persoon 18 jaar of ouder is en een geldig identiteitsbewijs laat zien; een Belgische identiteitskaart is prima. De bestelling wordt altijd bezorgd op het Nederlandse adres dat je via WhatsApp hebt doorgegeven."]],
 "nearby": ["breda", "etten-leur", "sint-willebrord"], "lat": 51.472, "lon": 4.656},

{"slug": "sint-willebrord", "name": "Sint Willebrord", "kind": "dorp", "region": "west-brabant", "gemeente": "Rucphen",
 "title": "Lachgas bestellen Sint Willebrord | Bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Sint Willebrord? Lachgastanks bezorgd in Sint Willebrord, Rucphen, Sprundel, Zegge en Schijf, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Sint Willebrord",
 "lead": "Lachgastanks 2KG, 4KG en 10KG aan huis in Sint Willebrord en de andere dorpen van Rucphen. Je appt je adres, wij melden prijs en tijdvak voordat we rijden.",
 "intro": [
  "Sint Willebrord is het grootste dorp van de gemeente Rucphen, bekend als bedevaartplaats met de Lourdesgrot in het Processiepark en als wielerdorp. Het dorp ligt langs de Dorpsstraat en de Poppestraat, direct onder de A58, met Rucphen, Sprundel, Zegge en Schijf als buurdorpen rond de Rucphense Bossen. Alle vijf de kernen van Rucphen liggen binnen ons bezorggebied. Je stuurt via WhatsApp je adres en de gewenste maat; wij komen terug met de prijs en een tijdvak, en pas na jouw akkoord stapt de koerier in.",
  "Vanaf Breda is het zo’n achttien kilometer over de A58 tot de afslag Sint Willebrord, die bijna in het dorp uitkomt. Toch rekenen we met band B, meestal binnen 45 tot 60 minuten, omdat de koerier vaak ook Sprundel, Schijf of Zegge in dezelfde ronde meeneemt en de wegen door de bossen geen snelweg zijn. Een treinstation heeft Rucphen niet; de bus rijdt naar Roosendaal en Etten-Leur. Voor een tank hoef je dus niet de deur uit.",
  "Een barbecue in een tuin aan de rand van de Rucphense Bossen of een verjaardag in een rijtjeshuis aan de Dorpsstraat: per situatie past een andere maat. Bekijk de verschillen in ons <a href=\"/lachgas-tanks/\">assortiment lachgastanks</a>. Contant of Tikkie, dat kies je zelf aan de deur; wat vaststaat is de verzegeling op de tank en de ID-controle, want 18+ is verplicht. Heb je zorgen over je eigen gebruik of dat van iemand in je omgeving, lees dan <a href=\"/informatie/problematisch-lachgasgebruik-hulp/\">waar je in Brabant hulp vindt</a>."],
 "wijken": "Dorpsstraat, Poppestraat, Processiepark, Rucphen, Sprundel, Zegge, Schijf, Rucphense Bossen",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie ook in Rucphen, Sprundel, Zegge en Schijf?", "Ja, voor alle dorpen van Rucphen hanteren we meestal 45 tot 60 minuten. Zegge ligt het dichtst bij Roosendaal, Schijf het meest zuidelijk richting de grens; vermeld daarom altijd het dorp bij je adres in het WhatsApp-bericht."],
  ["Kan ik lachgas bestellen bij een vakantiehuisje bij de Rucphense Bossen?", "Ja, een huisje in de bossen is een privéadres zolang jij er verblijft. Noem de naam van het park en het huisnummer, en houd er rekening mee dat de koerier bij een slagboom of receptie niet kan leveren; jij neemt de tank zelf bij je huisje aan."],
  ["Hoe discreet is de bezorging in een klein dorp als Sint Willebrord?", "De koerier komt met een onopvallende auto en belt één keer aan. Je kunt in het WhatsApp-gesprek vragen om een berichtje zodra hij voor de deur staat, zodat je zelf naar buiten kunt komen. Lees meer bij <a href=\"/service/bestellen-via-whatsapp/\">bestellen via WhatsApp</a>."]],
 "nearby": ["roosendaal", "etten-leur", "oudenbosch"], "lat": 51.549, "lon": 4.588},

{"slug": "hoogerheide", "name": "Hoogerheide", "kind": "dorp", "region": "west-brabant", "gemeente": "Woensdrecht",
 "title": "Lachgas bestellen Hoogerheide | Bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Hoogerheide? Lachgastanks 2KG, 4KG en 10KG bezorgd in Hoogerheide, Ossendrecht en Putte, meestal binnen 60 tot 90 minuten. 18+.",
 "h1": "Lachgas bezorgen in Hoogerheide",
 "lead": "Lachgastanks thuisbezorgd in Hoogerheide en de rest van de gemeente Woensdrecht, op de Brabantse Wal. Via WhatsApp bevestigen we eerst prijs en tijdvak.",
 "intro": [
  "Hoogerheide is de grootste kern van de gemeente Woensdrecht en ligt hoog op de Brabantse Wal, met uitzicht over de polders richting de Schelde. Het dorp strekt zich uit langs de Raadhuisstraat en de Antwerpsestraatweg, met de vliegbasis Woensdrecht en het bedrijvenpark Aviolanda aan de noordkant. Tot de gemeente horen ook Woensdrecht, Ossendrecht, Huijbergen en Putte tegen de grens. Overal in de gemeente komen we aan de deur met lachgastanks 2KG, 4KG en 10KG. Via WhatsApp stuur je adres en maat, waarna wij de prijs en een tijdvak terugsturen en jij akkoord geeft.",
  "De rit vanaf Breda loopt over de A58 tot knooppunt Markiezaat bij Bergen op Zoom en dan over de A4 richting Antwerpen tot de afslag Hoogerheide, in totaal zo’n vijftig kilometer. Dat maakt Hoogerheide een van de verste bestemmingen in West-Brabant, vandaar band C: meestal binnen 60 tot 90 minuten. Vanuit Bergen op Zoom is het via de N289 nog geen kwartier. Een station is er niet; de bus rijdt naar Bergen op Zoom en Putte.",
  "Een avond in een vrijstaand huis in Huijbergen of een verjaardag in een appartement aan de Raadhuisstraat: welke maat daarbij hoort, lees je op onze <a href=\"/lachgas-tanks/\">pagina over de drie tankmaten</a>. Bij de overdracht is de tank nog verzegeld, betaal je contant of via Tikkie en kijkt de koerier naar je identiteitsbewijs; ben je geen 18, dan gaat hij onverrichter zake terug. Vlak bij de Kalmthoutse Heide en de grens is het verleidelijk de tank mee naar buiten te nemen; lees eerst <a href=\"/veelgestelde-vragen/regels/\">onze vragen over regels</a>."],
 "wijken": "Raadhuisstraat, Antwerpsestraatweg, Aviolanda, Woensdrecht, Ossendrecht, Huijbergen, Putte, Brabantse Wal",
 "levertijd": "meestal binnen 60 tot 90 minuten",
 "faq": [
  ["Bezorgen jullie tot aan de grens in Putte?", "Ja, Putte ligt in de gemeente Woensdrecht en we rijden er met dezelfde indicatie heen als naar Hoogerheide: meestal 60 tot 90 minuten. We leveren alleen aan het Nederlandse deel van het dorp; voor adressen over de grens in België kunnen we niet komen."],
  ["Hoe kom ik aan een snellere levering in Hoogerheide?", "Bestel vroeg op de avond, voordat het rond Bergen op Zoom druk wordt, en geef meteen je volledige adres door. Rijdt een koerier al rond Bergen op Zoom of Halsteren, dan kan het sneller gaan dan de indicatie; we noemen altijd het realistische tijdvak in de bevestiging. Lees meer bij <a href=\"/service/spoedbezorging/\">spoedbezorging</a>."],
  ["Hoe zit het met lachgas en de regels van de gemeente Woensdrecht?", "Landelijk staat lachgas sinds 2023 op lijst II van de Opiumwet; daarnaast kan de gemeente via de APV gebruik op straat of bij evenementen verbieden. Wij leveren alleen aan 18-plussers op een privéadres. Controleer de actuele regels bij de gemeente of op <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a>."]],
 "nearby": ["bergen-op-zoom", "halsteren", "roosendaal"], "lat": 51.423, "lon": 4.325},

{"slug": "raamsdonksveer", "name": "Raamsdonksveer", "kind": "dorp", "region": "west-brabant", "gemeente": "Geertruidenberg",
 "title": "Lachgas bestellen Raamsdonksveer | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Raamsdonksveer? Lachgastanks verzegeld bezorgd in Raamsdonksveer, Geertruidenberg en Raamsdonk, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Raamsdonksveer",
 "lead": "Lachgastanks 2KG, 4KG en 10KG aan huis in Raamsdonksveer, Geertruidenberg en Raamsdonk. Stuur je adres via WhatsApp; de koerier vertrekt pas als jij prijs en tijdvak hebt goedgekeurd.",
 "intro": [
  "Raamsdonksveer ligt aan de Donge en de Bergsche Maas, vlak bij knooppunt Hooipolder waar de A27 en de A59 elkaar kruisen. Het is de grootste kern van de gemeente Geertruidenberg, met de Keizersdijk en het Heereplein als winkelhart en woonbuurten als Boterpolder, Sandoel en het nieuwere Dongeburgh langs het water. Ook in de vestingstad Geertruidenberg en in Raamsdonk bezorgen we lachgastanks. Zodra je adres en maat via WhatsApp binnen zijn, noemen wij de prijs en stellen we een tijdvak voor.",
  "Vanuit Breda rijdt de koerier over de A27 richting Gorinchem en neemt na Oosterhout de afslag Raamsdonksveer, een rit van nog geen twintig kilometer. Toch kiezen we hier voor band B, meestal binnen 45 tot 60 minuten, omdat bij Hooipolder al jaren aan de A27 wordt gewerkt en de drie kernen uit elkaar liggen. Een station heeft de gemeente niet; bussen rijden naar Breda en Oosterhout. Een lachgastank laat je dus gewoon komen in plaats van hem te gaan halen.",
  "Een verjaardag in een nieuw appartement in Dongeburgh of een feest in een oud pand binnen de vesting van Geertruidenberg: op de pagina met <a href=\"/lachgas-tanks/\">lachgastanks 2KG, 4KG en 10KG</a> zie je snel welke maat daarbij hoort. Je ontvangt een verzegelde tank, betaalt ter plekke contant of via Tikkie en laat je identiteitsbewijs zien; onder de 18 gaat de deur voor ons dicht. Drink je die avond ook, lees dan eerst waarom <a href=\"/informatie/lachgas-en-alcohol/\">lachgas en alcohol</a> geen goede combinatie zijn."],
 "wijken": "Centrum, Keizersdijk, Heereplein, Boterpolder, Sandoel, Dongeburgh, Dombosch, Geertruidenberg, Raamsdonk",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie ook in Geertruidenberg en Raamsdonk?", "Ja, Geertruidenberg en Raamsdonk bezorgen we in hetzelfde tijdvak als Raamsdonksveer, meestal 45 tot 60 minuten na bevestiging. In de smalle straten van de vesting Geertruidenberg parkeert de koerier kort op of bij de Markt; sta dan klaar bij de deur zodat de overdracht snel gaat."],
  ["Wat als er file staat bij knooppunt Hooipolder?", "Dan rijden we binnendoor via Oosterhout en Oosteind. Bij ernstige vertraging melden we een nieuw tijdvak via WhatsApp, en je betaalt pas als de tank er is. Meer uitleg over hoe we tijdvakken inschatten vind je bij <a href=\"/service/bezorgtijden-per-regio/\">bezorgtijden per regio</a>."],
  ["Kan ik lachgas laten bezorgen op een boot in de haven van Raamsdonksveer?", "Nee, we leveren alleen op een vast privéadres met huisnummer. Een boot, de jachthaven of de oevers van de Donge gelden als openbare ruimte en daar bezorgen we niet; de tank hoort ook niet op een warm, schommelend dek. Lees onze tips over <a href=\"/informatie/lachgastank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."]],
 "nearby": ["oosterhout", "made", "waalwijk"], "lat": 51.697, "lon": 4.880},

{"slug": "made", "name": "Made", "kind": "dorp", "region": "west-brabant", "gemeente": "Drimmelen",
 "title": "Lachgas bestellen Made | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Made? Lachgastanks 2KG, 4KG en 10KG bezorgd in Made, Terheijden, Wagenberg en Lage Zwaluwe, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Made",
 "lead": "Lachgastanks thuisbezorgd in Made en alle dorpen van de gemeente Drimmelen tot aan de Biesbosch. Met één WhatsApp-bericht regel je prijs, tijdvak en levering.",
 "intro": [
  "Made is het grootste dorp van de gemeente Drimmelen, tussen de A59 en de Amer, met de Marktstraat als winkelstraat en het gemeentehuis aan het Park. Rondom liggen Terheijden en Wagenberg aan de zuidkant van de snelweg, Hooge en Lage Zwaluwe richting het Hollandsch Diep en het havendorp Drimmelen als poort naar de Biesbosch. Elk van deze dorpen zit in ons bezorggebied. Bestellen doe je via WhatsApp: adres en gewenste maat doorgeven, prijs en tijdvak ontvangen, bevestigen en de koerier gaat rijden.",
  "Vanaf Breda is Made vijftien kilometer: over de A16 naar Zonzeel en dan de A59 tot de afslag Made, of binnendoor door Terheijden en Wagenberg. Omdat de dorpen van Drimmelen over een groot gebied verspreid liggen en Lage Zwaluwe en Drimmelen aan het eind van doodlopende polderwegen liggen, hanteren we band B: meestal binnen 45 tot 60 minuten. Station Lage Zwaluwe ligt buiten het dorp aan de lijn Dordrecht–Breda; voor een tank hoef je er niet heen, die komt naar je toe.",
  "Een zomeravond in een tuin bij de haven van Drimmelen of een verjaardag in Wagenberg: de maat van de tank hangt af van je gezelschap, de drie maten op onze <a href=\"/lachgas-tanks/\">tankpagina</a> maken de keuze makkelijk. Afrekenen doe je bij de koerier, contant of met een Tikkie; hij levert de tank verzegeld en controleert eerst je ID, omdat we alleen aan 18-plussers leveren. Een tank hoort niet in de zon op een boot of in een warme auto; lees waarom bij <a href=\"/informatie/lachgas-bij-kou-en-warmte/\">lachgas bij kou en warmte</a>."],
 "wijken": "Marktstraat, Park, Terheijden, Wagenberg, Hooge Zwaluwe, Lage Zwaluwe, Drimmelen, Helkant",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Bezorgen jullie ook in Terheijden en Lage Zwaluwe?", "Ja, voor heel Drimmelen geldt één indicatie: meestal 45 tot 60 minuten. Terheijden ligt het dichtst bij Breda en is vaak sneller; Lage Zwaluwe en Drimmelen liggen aan het einde van de polder en zitten eerder aan de bovenkant van het tijdvak."],
  ["Kan ik lachgas laten bezorgen bij de jachthaven van Drimmelen?", "Alleen op een woonadres of vakantiehuis met huisnummer, niet op de steiger, in de haven of in het Biesboschgebied zelf. Dat is deels beschermde natuur en openbare ruimte; wij leveren daar niet en raden gebruik buiten af. Zie onze <a href=\"/veelgestelde-vragen/bezorgen/\">vragen over bezorgen</a>."],
  ["Hoe werkt betalen bij levering in Made?", "Je betaalt pas als de koerier de verzegelde tank overhandigt, contant of via een Tikkie die we ter plekke sturen. Het bedrag is hetzelfde als wat we vooraf via WhatsApp hebben bevestigd; vooruitbetalen vragen we nooit. Meer details op <a href=\"/service/betalen-bij-levering/\">betalen bij levering</a>."]],
 "nearby": ["oosterhout", "raamsdonksveer", "breda"], "lat": 51.676, "lon": 4.794},

{"slug": "baarle-nassau", "name": "Baarle-Nassau", "kind": "dorp", "region": "west-brabant", "gemeente": "Baarle-Nassau",
 "title": "Lachgas bestellen Baarle-Nassau | Bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Baarle-Nassau? Lachgastanks bezorgd op Nederlandse adressen in Baarle-Nassau, Ulicoten en Castelré.",
 "h1": "Lachgas bezorgen in Baarle-Nassau",
 "lead": "Lachgastanks aan huis in Baarle-Nassau, Ulicoten en Castelré. Door de enclaves vragen we altijd je volledige adres; daarna volgen prijs en tijdvak via WhatsApp.",
 "intro": [
  "Baarle-Nassau deelt zijn dorpskern met het Belgische Baarle-Hertog: ruim twintig Belgische enclaves liggen verspreid door het dorp, en de grens loopt met tegels gemarkeerd over de Nieuwstraat en dwars door winkels. Het centrum rond de Singel en het Sint-Annaplein, de buurtschap Loveren en de dorpen Ulicoten en Castelré horen bij de Nederlandse gemeente. Daar bezorgen we lachgastanks 2KG, 4KG en 10KG, uitsluitend op adressen met een Nederlands huisnummer. Bestellen gaat via WhatsApp; zodra we je adres en maat hebben, melden we prijs en tijdvak en wacht de koerier op jouw akkoord.",
  "De koerier komt vanaf Breda via Ulvenhout en Chaam over de N639, of vanuit Tilburg over de N260 door Alphen, en volgt bij het dorp de randweg. Het is bijna dertig kilometer landelijk gebied zonder snelweg, en dat merk je in de levertijd: band C, meestal binnen 60 tot 90 minuten. Openbaar vervoer beperkt zich tot de bus vanuit Tilburg en Breda. Door de grillige grens controleren we het adres vooraf extra zorgvuldig, zodat de koerier niet aan een Belgische deur staat.",
  "Een feest in een boerderij bij Ulicoten of een avond in een appartement aan de Singel: vergelijk 2KG, 4KG en 10KG op onze <a href=\"/lachgas-tanks/\">pagina met lachgastanks</a> voordat je bestelt. Ook hier geldt: verzegelde tank, betalen aan de deur met contant geld of Tikkie, en een geldig identiteitsbewijs waaruit blijkt dat je 18 of ouder bent. Omdat Nederlandse en Belgische regels in dit dorp letterlijk naast elkaar liggen, raden we aan vooraf ons artikel over <a href=\"/informatie/is-lachgas-legaal-in-nederland/\">lachgas en de Nederlandse wet</a> te lezen."],
 "wijken": "Singel, Sint-Annaplein, Nieuwstraat, Pastoor de Katerstraat, Loveren, Ulicoten, Castelré, Randweg",
 "levertijd": "meestal binnen 60 tot 90 minuten",
 "faq": [
  ["Bezorgen jullie ook op Belgische adressen in Baarle-Hertog?", "Nee, we leveren alleen op adressen die bij de Nederlandse gemeente Baarle-Nassau horen. In het centrum wisselen Nederlandse en Belgische huisnummers elkaar soms per deur af; kijk naar het vlaggetje op je huisnummerbordje of stuur ons via WhatsApp een foto als je twijfelt."],
  ["Hoe lang duurt bezorgen in Ulicoten en Castelré?", "Beide dorpen liggen nog eens enkele kilometers van het centrum, Castelré zelfs vrijwel omsloten door België. Reken op de bovenkant van de indicatie van meestal 60 tot 90 minuten; het exacte tijdvak voor jouw adres bevestigen we vooraf via WhatsApp."],
  ["Kan ik een lachgastank meenemen over de grens vanuit Baarle-Nassau?", "Dat raden we af. In Nederland valt lachgas onder de Opiumwet en in België gelden eigen regels voor verkoop en bezit; vervoer over de grens kan dus problemen opleveren. Houd de tank op het Nederlandse adres waar hij geleverd is en raadpleeg bij twijfel <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a>."]],
 "nearby": ["goirle", "breda", "hilvarenbeek"], "lat": 51.447, "lon": 4.930},

{"slug": "werkendam", "name": "Werkendam", "kind": "dorp", "region": "west-brabant", "gemeente": "Altena",
 "title": "Lachgas bestellen Werkendam | Bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Werkendam? Lachgastanks 2KG, 4KG en 10KG bezorgd in Werkendam, Sleeuwijk, Nieuwendijk en Hank, meestal binnen 60 tot 90 minuten. 18+.",
 "h1": "Lachgas bezorgen in Werkendam",
 "lead": "Lachgastanks thuisbezorgd in Werkendam en de westelijke dorpen van Altena, aan de rand van de Biesbosch. Na je bericht op WhatsApp hoor je direct de prijs en het tijdvak.",
 "intro": [
  "Werkendam ligt in het Land van Heusden en Altena, boven de Bergsche Maas en direct tegen de Biesbosch, met het Biesbosch MuseumEiland en de Biesboschhaven als bekendste plekken. De Hoogstraat vormt het centrum; daaromheen de woonbuurten en aan het water de Beatrixhaven en bedrijventerrein Bruine Kilhaven. Sinds 2019 hoort het dorp bij de gemeente Altena, samen met Sleeuwijk, Nieuwendijk, Hank, Dussen en Woudrichem. Voor al die kernen geldt deze pagina. Stuur via WhatsApp je adres en maat, dan hoor je de prijs en een tijdvak voordat de koerier vertrekt.",
  "Vanaf Breda rijdt de koerier de A27 op richting Gorinchem, passeert knooppunt Hooipolder en de Bergsche Maas bij Keizersveer en neemt de afslag Werkendam bij Nieuwendijk, waarna de N322 naar het dorp voert. Dat is ruim dertig kilometer, en de A27 kent hier veel werkzaamheden; daarom valt Werkendam in band C en rekenen we op meestal binnen 60 tot 90 minuten. Treinen rijden er niet, de bus gaat naar Gorinchem en Breda. Juist in zo’n uithoek is het prettig dat de tank bij je thuis wordt gebracht.",
  "Een verjaardag in een dijkhuis in Sleeuwijk of een avond met vrienden in een rijtjeshuis aan de Hoogstraat: de juiste maat vind je terug in ons <a href=\"/lachgas-tanks/\">assortiment</a>. Verzegeling intact, betaling contant of via Tikkie op het moment van levering, en een koerier die je identiteitsbewijs wil zien: onder de 18 leveren we niet. Woon je dicht bij het water en de natuur, lees dan ook ons artikel over <a href=\"/informatie/lachgas-en-het-milieu/\">lachgas en het milieu</a>."],
 "wijken": "Centrum, Hoogstraat, Biesboschhaven, Beatrixhaven, Bruine Kilhaven, Sleeuwijk, Nieuwendijk, Hank, Dussen, Woudrichem",
 "levertijd": "meestal binnen 60 tot 90 minuten",
 "faq": [
  ["Bezorgen jullie in heel Altena, ook in Woudrichem en Wijk en Aalburg?", "Werkendam, Sleeuwijk, Nieuwendijk, Hank, Dussen en Woudrichem zitten in onze vaste route. Voor de oostelijke kernen zoals Wijk en Aalburg of Veen vragen we je eerst even via WhatsApp te checken of we die avond kunnen komen; de rit is daar nog een stuk langer."],
  ["Waarom is Werkendam band C terwijl Raamsdonksveer band B is?", "Raamsdonksveer ligt direct aan knooppunt Hooipolder, Werkendam nog eens vijftien kilometer verder over de A27 en de N322, met de Bergsche Maas ertussen. Die extra afstand en de kans op file bij Keizersveer maken meestal 60 tot 90 minuten realistischer dan een kortere indicatie."],
  ["Mag ik lachgas gebruiken in de Biesbosch of op een boot bij Werkendam?", "Wij raden dat af en bezorgen daar niet. De Biesbosch is een nationaal park met eigen regels, en lachgas aan boord of op het water brengt extra risico’s met zich mee. Gebruik alleen binnen op een privéadres en lees vooraf de <a href=\"/veelgestelde-vragen/veiligheid/\">vragen over veiligheid</a>."]],
 "nearby": ["raamsdonksveer", "oosterhout", "waalwijk"], "lat": 51.810, "lon": 4.895},

{"slug": "halsteren", "name": "Halsteren", "kind": "dorp", "region": "west-brabant", "gemeente": "Bergen op Zoom",
 "title": "Lachgas bestellen Halsteren | Snel bezorgd via WhatsApp",
 "description": "Lachgas bestellen in Halsteren? Verzegelde lachgastanks bezorgd in Halsteren en Lepelstraat, boven Bergen op Zoom, meestal binnen 45 tot 60 minuten. 18+.",
 "h1": "Lachgas bezorgen in Halsteren",
 "lead": "Lachgastanks aan huis in Halsteren en Lepelstraat, tussen Bergen op Zoom en Steenbergen. Appen, akkoord geven op prijs en tijdvak, deur openen: meer is het niet.",
 "intro": [
  "Halsteren is het grote dorp direct ten noorden van Bergen op Zoom, op de rand van de Brabantse Wal waar de hoge zandgrond overgaat in de polders richting Tholen. Het dorp heeft de Dorpsstraat met de Sint-Quirinuskerk als centrum, recreatiegebied De Melanen, de nieuwbouw in Rode Schouw en Fort de Roovere met de Mozesbrug aan de oostkant. Lepelstraat en de buurtschap Kladde horen erbij. We bezorgen lachgastanks 2KG, 4KG en 10KG in al deze buurten; bestellen gaat via WhatsApp, waarna wij prijs en tijdvak bevestigen.",
  "De koerier komt vanaf Breda over de A58 en bij Bergen op Zoom via de A4 naar de afslag Halsteren, in totaal zo’n 45 kilometer. Vanuit Bergen op Zoom zelf is het via de Halsterseweg nog geen tien minuten. Door die ligging rekenen we net als voor de stad met band B: meestal binnen 45 tot 60 minuten. Een station is er niet, maar de bus tussen Bergen op Zoom, Steenbergen en Tholen stopt in het dorp; voor een lachgastank hoef je niet in te stappen.",
  "Een barbecue in een tuin aan de rand van De Melanen of een verjaardag in Lepelstraat: het aantal gasten bepaalt de maat, en die drie maten staan uitgelegd bij <a href=\"/lachgas-tanks/\">onze lachgastanks</a>. Verzegelde levering, afrekenen contant of via Tikkie zodra de koerier er staat, en een controle van je identiteitsbewijs omdat 18+ hier net zo hard geldt als elders. Omdat Halsteren veel fietsers en wandelaars trekt richting Tholen en de Waterlinie: gebruik niet buiten, en lees eerst ons artikel over <a href=\"/informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>."],
 "wijken": "Dorpsstraat, Lepelstraat, Kladde, De Melanen, Rode Schouw, Fort de Roovere, Tholenseweg, Steenbergseweg",
 "levertijd": "meestal binnen 45 tot 60 minuten",
 "faq": [
  ["Valt Halsteren onder dezelfde levertijd als Bergen op Zoom?", "Ja. Voor Halsteren rekenen we met hetzelfde tijdvak als voor de stad, meestal 45 tot 60 minuten. Omdat het dorp direct aan de A4 ligt, is de koerier er vaak even snel als in de wijken aan de noordkant van de stad, zoals Noordgeest."],
  ["Bezorgen jullie ook over de Tholensebrug op Tholen?", "Nee, Tholen ligt in Zeeland en valt buiten ons bezorggebied; Halsteren en Lepelstraat zijn de meest westelijke adressen die we aan deze kant bedienen. Woon je op Tholen, dan kun je de tank laten bezorgen bij vrienden in Halsteren en daar zelf aannemen met een geldig ID."],
  ["Kan ik ’s avonds laat nog bestellen in Halsteren?", "Ja, onze WhatsApp is ook ’s nachts bereikbaar. In Halsteren staan veel vrijstaande huizen in rustige straten, dus vragen we je bij een late levering op de uitkijk te staan zodat de koerier niet hoeft aan te bellen. Meer hierover op de pagina <a href=\"/service/nachtbezorging/\">nachtbezorging</a>."]],
 "nearby": ["bergen-op-zoom", "steenbergen", "hoogerheide"], "lat": 51.527, "lon": 4.282},
]
