# -*- coding: utf-8 -*-
# Noordoost-Brabant: de twaalf overige plaatsen (zonder 's-Hertogenbosch, Rosmalen en Oss).
AREAS = [
    {
        "slug": "veghel", "name": "Veghel", "kind": "stad", "region": "noordoost-brabant", "gemeente": "Meierijstad",
        "title": "Lachgas Veghel | Bezorgd aan huis in Meierijstad",
        "description": "Lachgas bestellen in Veghel? Lachgas Brabant bezorgt lachgastanks 2KG, 4KG en 10KG aan huis, van de Noordkade tot De Bunders en Zijtaart. Alleen 18+.",
        "h1": "Lachgas bezorgen in Veghel",
        "lead": "Lachgastanks verzegeld aan huis in Veghel en de kerkdorpen van Meierijstad, besteld via WhatsApp en meestal binnen 45 tot 60 minuten bij je.",
        "intro": [
            "Veghel is sinds 2017 de grootste kern van de fusiegemeente Meierijstad en ook het bestuurlijke hart ervan: het gemeentehuis staat aan het Stadhuisplein. De Zuid-Willemsvaart snijdt dwars door het stadje, met aan de ene oever de Noordkade op het oude fabrieksterrein en aan de andere kant het centrum rond de Markt en de Lambertuskerk. Wij bezorgen in alle woonwijken, van De Bunders, De Leest en 't Ven tot Veghel-Zuid, Hoogeind en de nieuwbouw in De Scheifelaar, en daarnaast in Mariaheide, Eerde, Zijtaart en Erp. Een bestelling plaats je met één WhatsApp-bericht waarin je adres en de gewenste tank staan.",
            "Onze bezorger komt vanuit 's-Hertogenbosch meestal over de N279, die langs de Zuid-Willemsvaart tot aan de rand van Veghel loopt, of via de A50 wanneer het verkeer op de kanaalroute vastzit. Beide routes zijn ongeveer een half uur rijden, en samen met het laden en de laatste kilometers door de wijk komen we uit op meestal binnen 45 tot 60 minuten. Op vrijdag- en zaterdagavond kan het rond de Noordkade en bij de afritten van de A50 druk zijn; we bevestigen daarom altijd eerst een tijdvak voordat we vertrekken. Veghel heeft geen treinstation meer, maar voor een levering tot aan de voordeur maakt dat niets uit.",
            "Voor een avond met een paar vrienden in een appartement aan de Hoogstraat volstaat vaak een <a href=\"/lachgas-tanks/2kg/\">lachgastank 2KG</a>; voor een groter gezelschap in een huis in Veghel-Zuid is de 4KG of 10KG logischer. Alle tanks komen verzegeld aan en je ziet het totaalbedrag vooraf in de WhatsApp-bevestiging, zodat je bij de deur alleen nog contant of via Tikkie afrekent. We leveren uitsluitend aan personen van 18 jaar of ouder en vragen om een legitimatiebewijs als daar twijfel over bestaat. Lees voor je bestelt ook onze pagina over <a href=\"/informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a>.",
        ],
        "wijken": "Centrum, De Bunders, De Leest, 't Ven, Veghel-Zuid, Hoogeind, De Scheifelaar, Noordkade, Mariaheide, Zijtaart",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Erp, Eerde en Zijtaart?", "Ja, de kerkdorpen die vroeger bij de gemeente Veghel hoorden nemen we gewoon mee in de route. Houd er rekening mee dat Erp en Boerdonk aan de buitenkant van ons gebied liggen, waardoor het tijdvak daar iets ruimer kan uitvallen dan in het stadje zelf."],
            ["Hoe snel zijn jullie in Veghel?", "Vanaf 's-Hertogenbosch of Oss zijn we meestal binnen 45 tot 60 minuten bij je, afhankelijk van de drukte op de N279 en de A50. Je krijgt vooraf via WhatsApp een tijdvak, zodat je niet voor niets bij de deur staat te wachten."],
            ["Kan ik bezorgd krijgen bij een feest op de Noordkade?", "Nee, op de Noordkade en andere horeca- of evenemententerreinen bezorgen we niet; daar gelden de regels van de uitbater en van de gemeente Meierijstad. Ga je daarna nog bij iemand thuis verder, dan geef je dat woonadres door en komen we daar."],
        ],
        "nearby": ["schijndel", "uden", "sint-oedenrode"],
        "lat": 51.6167, "lon": 5.5500,
    },
    {
        "slug": "schijndel", "name": "Schijndel", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Meierijstad",
        "title": "Lachgas Schijndel | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Schijndel? Verzegelde lachgastanks aan huis, van de Markt bij de Glazen Boerderij tot Boschweg, Hoevenbraak en Wijbosch. Voor 18+.",
        "h1": "Lachgas bezorgen in Schijndel",
        "lead": "Bestel via WhatsApp en we brengen je lachgastank meestal binnen 45 tot 60 minuten naar je adres in Schijndel of Wijbosch.",
        "intro": [
            "Schijndel ligt midden tussen 's-Hertogenbosch, Veghel en Boxtel en hoort sinds de herindeling van 2017 bij Meierijstad, al voelt het dorp nog altijd als een eigen plek met de Glazen Boerderij als blikvanger op de Markt. De Hoofdstraat en de Markt vormen het centrum; daaromheen liggen woonwijken als Boschweg, Hoevenbraak, Hulzebraak, Beemd en Plein, en aan de oostkant het kerkdorp Wijbosch. In al die buurten komen wij aan huis. Je appt ons je straat en huisnummer, welke tank je wilt hebben en rond welk tijdstip je thuis bent, en wij regelen de rest.",
            "Vanuit 's-Hertogenbosch rijden onze bezorgers via Sint-Michielsgestel over de N617 het dorp binnen, een route van een kleine twintig minuten als het meezit; komt de bezorger uit de richting van Veghel, dan is het via Eerde nog een stuk korter. Omdat Schijndel geen eigen afrit op een snelweg heeft en de bus vanuit de stad maar een paar keer per uur rijdt, kiezen veel klanten voor bezorging in plaats van zelf op pad te gaan. Wij hanteren hier de band meestal binnen 45 tot 60 minuten; op drukke avonden sturen we vooraf een realistisch tijdvak zodat je weet waar je aan toe bent.",
            "Een borrel in een rijtjeshuis aan de Boschweg, een verjaardag in Hoevenbraak of een tuinfeest in het buitengebied richting Wijbosch: de situatie bepaalt welk formaat zinvol is. In ons <a href=\"/lachgas-tanks/\">assortiment</a> vind je de lachgastank 2KG, 4KG en 10KG, allemaal verzegeld en met de prijs vooraf vastgelegd in de chat. Betalen doe je bij levering, contant of via Tikkie, en we leveren alleen aan mensen van 18 jaar en ouder. Bewaar de tank rechtop en uit de zon; hoe dat precies zit lees je bij <a href=\"/informatie/lachgastank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>.",
        ],
        "wijken": "Markt, Hoofdstraat, Boschweg, Hoevenbraak, Hulzebraak, Beemd, Plein, Wijbosch, Duin",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Wat is het verschil met bestellen in Veghel of Den Bosch?", "Niets in de manier van bestellen; alleen de reistijd verschilt. Schijndel valt in dezelfde levertijdband als Veghel, meestal binnen 45 tot 60 minuten, terwijl het in 's-Hertogenbosch zelf doorgaans wat vlotter gaat."],
            ["Bezorgen jullie ook laat in de avond in Schijndel?", "Ja, we zijn ook ’s avonds en ’s nachts bereikbaar via WhatsApp. In een rustige woonwijk als Hulzebraak bellen we zacht aan of appen we dat we voor de deur staan, zodat de buren er niets van merken. Meer hierover bij <a href=\"/service/nachtbezorging/\">nachtbezorging</a>."],
            ["Mag lachgas op straat in Schijndel?", "Gemeenten kunnen in hun APV gebruik op straat of bij evenementen verbieden, en lachgas valt landelijk sinds 2023 onder de Opiumwet. Raadpleeg daarom de regels van Meierijstad en lees onze uitleg over <a href=\"/informatie/lachgas-regels-per-gemeente-brabant/\">regels per gemeente</a>."],
        ],
        "nearby": ["veghel", "sint-michielsgestel", "boxtel"],
        "lat": 51.6200, "lon": 5.4330,
    },
    {
        "slug": "sint-oedenrode", "name": "Sint-Oedenrode", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Meierijstad",
        "title": "Lachgas Sint-Oedenrode | Snel bezorgd in Rooi",
        "description": "Lachgas bestellen in Sint-Oedenrode? Lachgastanks verzegeld aan huis in Rooi, Nijnsel, Boskant en Olland, besteld via WhatsApp. Uitsluitend voor 18+.",
        "h1": "Lachgas bezorgen in Sint-Oedenrode",
        "lead": "Via WhatsApp bestellen, meestal binnen 45 tot 60 minuten aan huis in Sint-Oedenrode en de kerkdorpen langs de Dommel.",
        "intro": [
            "Sint-Oedenrode, voor iedereen uit de buurt gewoon Rooi, is het groenste deel van Meierijstad: de Dommel slingert door het dorp, langs kasteel Henkenshage en het park bij de Markt en de Martinuskerk. De bebouwing ligt grotendeels tussen de rivier en de A50, met woonwijken als Kienehoef, Eerschot, Dommelrode, Cathalijne en Armenhoef, en daarbuiten de kerkdorpen Nijnsel, Boskant en Olland. Al die adressen zitten in ons bezorggebied. Bestellen gaat met een kort WhatsApp-bericht: je adres, de tank die je wilt en of je er direct bent of liever een later tijdvak kiest.",
            "De A50 heeft een eigen afrit voor Sint-Oedenrode, wat de rit vanuit Eindhoven of vanuit het noorden overzichtelijk maakt; vanuit 's-Hertogenbosch rijden we via Schijndel binnendoor. Reken op meestal binnen 45 tot 60 minuten, omdat we de kilometers vanaf onze vertrekpunten en het afleveren bij andere klanten op dezelfde route meetellen. Rooi heeft geen station en de bussen naar Eindhoven en Veghel stoppen ’s avonds laat met rijden, dus thuis laten bezorgen scheelt je een lange omweg. Zodra je bestelt krijg je een tijdvak dat we ook echt verwachten te halen.",
            "Of het nu gaat om een rustige avond in een appartement bij het Kerkplein of een groter feest in een boerderij richting Olland, je kiest het formaat dat past: de <a href=\"/lachgas-tanks/2kg/\">lachgastank 2KG</a> voor een klein gezelschap, de 4KG als middenmaat en de 10KG voor een avond met veel mensen. De prijs staat vooraf in de chat en bij de deur betaal je contant of met een Tikkie. Onze bezorgers leveren alleen aan 18-plussers en vragen bij twijfel naar een ID. Lees vooraf ook onze <a href=\"/veelgestelde-vragen/veiligheid/\">veelgestelde vragen over veiligheid</a>.",
        ],
        "wijken": "Markt, Kerkplein, Kienehoef, Eerschot, Dommelrode, Cathalijne, Armenhoef, Nijnsel, Boskant, Olland",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Komen jullie ook in Nijnsel, Boskant en Olland?", "Ja, de drie kerkdorpen horen bij ons gebied rond Sint-Oedenrode. Nijnsel ligt vlak bij de A50 en is zelfs sneller bereikbaar dan het centrum; voor Olland en Boskant rekenen we een paar minuten extra."],
            ["Hoe werkt het tijdvak dat jullie noemen?", "Na je bericht kijken we welke bezorger het dichtst bij Rooi zit en sturen we een tijdvak terug, bijvoorbeeld binnen 45 tot 60 minuten. Loopt het door drukte op de A50 toch anders, dan hoor je dat direct in dezelfde chat."],
            ["Bezorgen jullie ook in het buitengebied van Rooi?", "Ja, ook op adressen langs de Dommel of in het buitengebied richting Boskant komen we. Geef in dat geval een duidelijk herkenningspunt door, want sommige wegen hebben geen straatverlichting en huisnummers zijn in het donker lastig te vinden."],
        ],
        "nearby": ["veghel", "schijndel", "best"],
        "lat": 51.5660, "lon": 5.4620,
    },
    {
        "slug": "uden", "name": "Uden", "kind": "stad", "region": "noordoost-brabant", "gemeente": "Maashorst",
        "title": "Lachgas Uden | Bezorgd aan huis in Maashorst",
        "description": "Lachgas bestellen in Uden? Lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Markt tot Uden-Zuid, Bitswijk en Volkel. Alleen voor 18 jaar en ouder.",
        "h1": "Lachgas bezorgen in Uden",
        "lead": "Uden en de kernen van Maashorst bedienen we via WhatsApp, met levering meestal binnen 45 tot 60 minuten.",
        "intro": [
            "Uden is sinds 1 januari 2022 de grootste plaats van de nieuwe gemeente Maashorst, die ontstond door de fusie met Landerd en vernoemd is naar het natuurgebied ten noorden van de stad. Het centrum rond de Markt, de Marktstraat en het Mondriaanplein is het winkelhart van de regio; daaromheen liggen Bitswijk, Raam, Moleneind, Melle, Hoeven en de grote uitbreiding Uden-Zuid met Hoenderbos en Velmolen. Ook Volkel en Odiliapeel nemen we mee. Je bestelt bij ons met een WhatsApp-bericht waarin je adres staat en het formaat tank dat je wilt hebben.",
            "Onze bezorger pakt vanuit 's-Hertogenbosch of Oss de A50 en rijdt er bij Uden af, vlak bij ziekenhuis Bernhoven; vanuit Veghel is het over de oude weg door Mariaheide nog korter. De afstand tot onze vertrekpunten is net wat groter dan voor Veghel of Heesch, en daarom valt Uden in de band meestal binnen 45 tot 60 minuten. Een treinstation is er niet en het busstation ligt aan de rand van het centrum, maar voor een levering aan huis maakt dat allemaal niets uit: we komen tot aan de voordeur en bevestigen vooraf een tijdvak zodat je het kunt inplannen.",
            "Voor een avond in een appartement in de Flatwijk is de lachgastank 2KG meestal genoeg; bij een feest in een huis in Uden-Zuid of een schuur in Odiliapeel kom je eerder bij de 4KG of 10KG uit. Vergelijk ze op de pagina <a href=\"/lachgas-tanks/\">lachgastanks</a>. Iedere tank is verzegeld, de prijs is vooraf bevestigd in de chat en je betaalt bij levering contant of via Tikkie. We leveren uitsluitend aan 18-plussers en controleren zo nodig je ID. Wil je weten wat de combinatie met drank doet, lees dan <a href=\"/informatie/lachgas-en-alcohol/\">lachgas en alcohol</a>.",
        ],
        "wijken": "Markt, Marktstraat, Mondriaanplein, Bitswijk, Raam, Moleneind, Melle, Hoeven, Uden-Zuid, Volkel",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie in heel Maashorst, dus ook in Zeeland en Schaijk?", "Ja, sinds de fusie van 2022 rekenen we Zeeland, Schaijk en Reek bij het gebied rond Uden. Voor die kernen kan het tijdvak een kwartier ruimer zijn, omdat ze verder van de A50 af liggen."],
            ["Gelden er in Uden speciale regels voor lachgas?", "Landelijk staat lachgas sinds 2023 op lijst II van de Opiumwet, met uitzonderingen voor onder meer technisch en voedingsgebruik, en gemeenten kunnen via de APV extra beperkingen stellen voor de openbare ruimte. Kijk voor de actuele stand op <a href=\"https://www.rijksoverheid.nl\">rijksoverheid.nl</a> en bij de gemeente Maashorst."],
            ["Kunnen jullie ook ’s nachts in Uden komen?", "Dat kan; we zijn ook na middernacht via WhatsApp bereikbaar. In de nachtelijke uren is het rustig op de A50, maar we plannen altijd een tijdvak zodat je weet wanneer je de deur open moet doen."],
        ],
        "nearby": ["veghel", "oss", "boekel"],
        "lat": 51.6610, "lon": 5.6180,
    },
    {
        "slug": "boxtel", "name": "Boxtel", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Boxtel",
        "title": "Lachgas Boxtel | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Boxtel? Verzegelde lachgastanks aan huis rond het station, in Boxtel-Oost, Selissen, Munsel en Liempde. Bestel via WhatsApp, 18+.",
        "h1": "Lachgas bezorgen in Boxtel",
        "lead": "Boxtel, Liempde, Lennisheuvel en Esch: besteld via WhatsApp en meestal binnen 45 tot 60 minuten aan huis.",
        "intro": [
            "Boxtel ligt precies halverwege 's-Hertogenbosch en Eindhoven, waar het spoor richting Tilburg aftakt en de A2 het dorp aan de oostkant passeert. Het centrum rond de Markt, de Rechterstraat en de Sint-Petrusbasiliek ligt aan de Dommel, met kasteel Stapelen even verderop. Wij bezorgen in alle wijken, van Breukelen en Selissen bij het station tot Boxtel-Oost, Munsel en In Goede Aarde, en in de kerkdorpen Liempde, Lennisheuvel en Esch. Een bestelling begint met een WhatsApp-bericht waarin je je adres en het gewenste formaat tank doorgeeft.",
            "Dankzij de A2 en de ligging tussen twee grote steden is Boxtel voor onze bezorgers goed te bereiken: afrit Boxtel, dan over de Keulsebaan of de Bosscheweg het dorp in. Toch rekenen we meestal binnen 45 tot 60 minuten, omdat de laatste kilometers door het centrum en het oversteken van het spoor bij drukte tijd kosten. Het station is een knooppunt met intercity's naar Den Bosch en Eindhoven en sprinters naar Tilburg, maar als je laat thuis bent is het gemakkelijker om de tank aan huis te laten brengen. We bevestigen altijd eerst een tijdvak in de chat.",
            "Een gezellige avond in een jaren-dertighuis aan de Stationsstraat vraagt om iets anders dan een feest op een boerenerf in Liempde. Daarom hebben we de lachgastank 2KG, 4KG en 10KG in het <a href=\"/lachgas-tanks/\">assortiment</a>; twijfel je, dan denken we via WhatsApp met je mee. Alles komt verzegeld aan, de prijs is vooraf bevestigd en je betaalt bij levering contant of via Tikkie. Onze bezorger levert alleen aan wie 18 jaar of ouder is en kan daarvoor om een ID vragen. Lees voor je begint hoe je de <a href=\"/informatie/lachgas-bij-kou-en-warmte/\">tank bij kou en warmte</a> behandelt, want een bevroren kraan is een veelgemaakte fout.",
        ],
        "wijken": "Centrum, Markt, Stationsstraat, Breukelen, Selissen, Boxtel-Oost, Munsel, In Goede Aarde, Liempde, Lennisheuvel",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Esch en Liempde?", "Ja, Esch hoort sinds 2021 bij de gemeente Boxtel en Liempde al veel langer; beide dorpen zitten gewoon in de route. Liempde ligt dicht bij de A2, Esch ligt tussen Boxtel en Vught en is vanaf de snelweg binnen een paar minuten bereikbaar."],
            ["Kan ik mijn bestelling bij station Boxtel ophalen?", "Nee, we hebben geen afhaalpunt en overhandigen geen tanks op straat of op het stationsplein. We komen naar een woonadres of een ander vast adres waar jij als 18-plusser aanwezig bent."],
            ["Hoe laat kan ik in Boxtel nog bestellen?", "Je kunt dag en nacht een bericht sturen; buiten kantooruren plannen we de bezorgers vanaf hun actuele positie, dus het tijdvak kan ’s nachts anders uitvallen. Bekijk <a href=\"/service/bezorgtijden-per-regio/\">bezorgtijden per regio</a> voor de uitleg van de banden."],
        ],
        "nearby": ["vught", "sint-michielsgestel", "best"],
        "lat": 51.5900, "lon": 5.3290,
    },
    {
        "slug": "vught", "name": "Vught", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Vught",
        "title": "Lachgas Vught | Snel bezorgd vanuit Den Bosch",
        "description": "Lachgas bestellen in Vught? Lachgastanks verzegeld aan huis, van het Marktveld tot Vught-Zuid, De Baarzen, Cromvoirt en Helvoirt. Via WhatsApp, 18+.",
        "h1": "Lachgas bezorgen in Vught",
        "lead": "Direct onder 's-Hertogenbosch, dus vlot bezorgd: meestal binnen 30 tot 45 minuten aan huis in Vught, Cromvoirt en Helvoirt.",
        "intro": [
            "Vught grenst direct aan de zuidkant van 's-Hertogenbosch, waar de A2 en de N65 richting Tilburg bij knooppunt Vught uit elkaar gaan en het spoor naar Eindhoven en Tilburg zich splitst. Het is een groen forensendorp met het Marktveld en de Raadhuisstraat als kern, de IJzeren Man als recreatieplas en kasteel Maurick aan de Dommel. Wij bezorgen in Vught-Noord en Vught-Zuid, De Baarzen, Schoonveld, Bergenshuizen en het nieuwe Stadhouderspark, en ook in Cromvoirt en Helvoirt. Bestellen doe je via WhatsApp met je adres en de gewenste tank.",
            "Omdat 's-Hertogenbosch een van onze vertrekpunten is, zijn we in Vught vaak sneller dan ergens anders in Noordoost-Brabant: via de Vughterweg of de A2 staan we binnen tien minuten in het dorp, waarna de laatste meters door de wijk volgen. Vandaar de band meestal binnen 30 tot 45 minuten. Rond het spoor wordt de komende jaren flink gebouwd, met afsluitingen en omleidingen in het dorp als gevolg; onze bezorgers kennen die, maar bij een afgesloten straat vragen we soms om een alternatief punt vlakbij. Je krijgt het tijdvak vooraf, dus je hoeft niet te gokken.",
            "Een avond in een appartement bij het Marktveld, een tuinfeest in Vught-Noord of een weekend met vrienden in een huisje bij de IJzeren Man: kies de lachgastank 2KG, 4KG of 10KG die bij het aantal mensen past en bekijk de verschillen op <a href=\"/lachgas-tanks/\">onze tankpagina</a>. Elke tank is verzegeld, de prijs is vooraf in de chat bevestigd en afrekenen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan 18-plussers en vragen bij twijfel om een ID. Let op je lichaam: lees onze uitleg over <a href=\"/informatie/lachgas-en-vitamine-b12/\">lachgas en vitamine B12</a>.",
        ],
        "wijken": "Marktveld, Raadhuisstraat, Vught-Noord, Vught-Zuid, De Baarzen, Schoonveld, Bergenshuizen, Stadhouderspark, Cromvoirt, Helvoirt",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Waarom is Vught sneller dan Boxtel of Schijndel?", "Simpel: afstand. Vught ligt tegen 's-Hertogenbosch aan, waar onze bezorgers vaak al rijden, zodat we hier meestal binnen 30 tot 45 minuten zijn in plaats van de 45 tot 60 minuten die we voor dorpen verderop rekenen."],
            ["Bezorgen jullie ook in Helvoirt en Cromvoirt?", "Ja, Helvoirt hoort sinds 2021 bij Vught en Cromvoirt al langer; beide liggen aan onze kant van de Loonse en Drunense Duinen. Voor Helvoirt kan het tijdvak iets ruimer zijn omdat het verder van de A2 ligt."],
            ["Kan ik bij de IJzeren Man of in het bos laten bezorgen?", "Nee, op strandjes, parkeerplaatsen en in natuurgebieden leveren we niet; dat is geen vast adres en op veel van die plekken verbiedt de gemeente het gebruik via de APV. Geef een woonadres of vakantieadres door waar je als 18-plusser aanwezig bent."],
        ],
        "nearby": ["s-hertogenbosch", "boxtel", "sint-michielsgestel"],
        "lat": 51.6530, "lon": 5.2870,
    },
    {
        "slug": "cuijk", "name": "Cuijk", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Land van Cuijk",
        "title": "Lachgas Cuijk | Bezorgd aan huis in Land van Cuijk",
        "description": "Lachgas bestellen in Cuijk? Lachgastanks 2KG, 4KG en 10KG verzegeld thuisbezorgd, van de Maasboulevard tot Padbroek, De Valuwe en Katwijk. Alleen 18+.",
        "h1": "Lachgas bezorgen in Cuijk",
        "lead": "Aan de Maas en de A73 ligt Cuijk aan de rand van ons gebied; via WhatsApp besteld en meestal binnen 60 tot 90 minuten bij je.",
        "intro": [
            "Cuijk is sinds 1 januari 2022 de hoofdplaats van Land van Cuijk, een van de grootste gemeenten van Brabant qua oppervlakte, ontstaan uit Cuijk, Boxmeer, Grave, Mill en Sint Hubert en Sint Anthonis. Het gemeentehuis staat aan het Louis Jansenplein, op een steenworp van de Grotestraat en de Maasboulevard waar je over het water naar Limburg kijkt. Wij bezorgen in het centrum, Padbroek, De Valuwe en Heeswijkse Kampen, en in de kerkdorpen Katwijk, Sint Agatha, Beers, Vianen, Haps en Linden. Je bestelt via WhatsApp door je adres en het gewenste formaat tank te sturen.",
            "Onze bezorgers komen vanuit Oss of 's-Hertogenbosch via de A50 en de A73, of binnendoor over Grave, en nemen de afrit Cuijk. Dat is een flinke rit naar de uiterste oostrand van Noord-Brabant, en daarom hanteren we hier de band meestal binnen 60 tot 90 minuten. Het station aan de Maaslijn verbindt Cuijk met Nijmegen en Venlo, maar wie ’s avonds laat thuis is, heeft meer aan een bezorging tot de voordeur. In het weekend, als het bij de Maasboulevard en in de Grotestraat druk is, sturen we een ruim tijdvak zodat je er niet op hoeft te wachten, en we melden het als het eerder lukt.",
            "Een avond met een paar vrienden in een appartement aan de Maasboulevard, een verjaardag in Padbroek of een feest in een schuur bij Sint Agatha: het aantal gasten bepaalt het formaat. We hebben de <a href=\"/lachgas-tanks/2kg/\">lachgastank 2KG</a>, 4KG en 10KG, allemaal verzegeld en met de prijs vooraf bevestigd in de chat. Betalen doe je bij levering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Wordt iemand onwel, dan wil je weten wat je moet doen: lees <a href=\"/informatie/lachgas-bijwerkingen-en-eerste-hulp/\">bijwerkingen en eerste hulp</a> voordat de avond begint.",
        ],
        "wijken": "Centrum, Louis Jansenplein, Grotestraat, Maasboulevard, Padbroek, De Valuwe, Heeswijkse Kampen, Katwijk, Sint Agatha, Beers",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook over de Maas, in Mook of Middelaar?", "Nee, ons gebied stopt bij de provinciegrens; de overkant van de Maas is Limburg en daar komen we niet. Binnen Land van Cuijk bezorgen we wel in alle kernen rond Cuijk, van Katwijk tot Haps en Linden."],
            ["Waarom duurt het in Cuijk langer dan in Oss?", "Cuijk ligt aan de oostrand van Brabant, ruim een half uur rijden over de A50 en A73 vanaf onze vertrekpunten, terwijl Oss veel dichterbij ligt. Daarom geldt hier meestal binnen 60 tot 90 minuten in plaats van 45 tot 60."],
            ["Kan het in Cuijk ook sneller dan 60 minuten?", "Soms wel, als een bezorger toevallig al in de buurt van Grave of Boxmeer is, maar daar kunnen we niet op bouwen. Wil je het zeker weten, vraag dan via WhatsApp naar het actuele tijdvak; bij <a href=\"/service/spoedbezorging/\">spoedbezorging</a> lees je wat wij wel en niet beloven."],
        ],
        "nearby": ["grave", "boxmeer", "uden"],
        "lat": 51.7300, "lon": 5.8780,
    },
    {
        "slug": "boxmeer", "name": "Boxmeer", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Land van Cuijk",
        "title": "Lachgas Boxmeer | Thuisbezorgd via WhatsApp",
        "description": "Lachgas bestellen in Boxmeer? Verzegelde lachgastanks aan huis, van de Steenstraat tot Boxmeer-Noord, Beugen, Sambeek en Overloon. Via WhatsApp, 18+.",
        "h1": "Lachgas bezorgen in Boxmeer",
        "lead": "Het zuidelijke deel van Land van Cuijk bedienen we vanuit Boxmeer: bestellen via WhatsApp, levering meestal binnen 60 tot 90 minuten.",
        "intro": [
            "Boxmeer is de zuidelijkste grote kern van Land van Cuijk, de gemeente die begin 2022 ontstond uit vijf gemeenten in de Maasvallei. De Steenstraat is de winkelstraat van het dorp, met het Weijerpark en het kasteel aan de ene kant en de Sint-Petrusbasiliek aan de andere. Woonwijken als Boxmeer-Noord en het centrum nemen we mee, net als de dorpen langs de Maas en in het achterland: Beugen, Sambeek, Oeffelt, Rijkevoort, Vortum-Mullem, Vierlingsbeek en Overloon. Bestellen gaat via WhatsApp: adres, gewenste tank en het tijdstip waarop je thuis bent.",
            "De A73 loopt pal langs Boxmeer en de afrit ligt vlak bij het Maasziekenhuis in Beugen, zodat we vanuit het noorden snel het dorp in rijden. Het probleem zit niet in de laatste kilometers maar in de eerste: Boxmeer is vanaf onze vertrekpunten in 's-Hertogenbosch en Oss het verste punt dat we bedienen, bijna aan de grens met Limburg. Daarom geldt hier meestal binnen 60 tot 90 minuten. Het station aan de Maaslijn verbindt het dorp met Nijmegen en Venlo, maar voor een tank aan huis maakt dat niet uit. Je ontvangt vooraf een tijdvak en we laten het weten als het verschuift.",
            "Of je nu een rustige avond in een appartement aan de Steenstraat plant of een groot feest in een loods bij Rijkevoort, kies de tank die daarbij past: de lachgastank 2KG voor een klein gezelschap, de <a href=\"/lachgas-tanks/4kg/\">4KG</a> als allrounder of de 10KG voor een groter gezelschap. Elke tank wordt verzegeld geleverd, de prijs is vooraf in de chat bevestigd en je betaalt bij de deur contant of via Tikkie. We leveren uitsluitend aan 18-plussers. Lees vooraf ook de pagina over <a href=\"/informatie/lachgas-in-het-verkeer/\">lachgas in het verkeer</a>, want wie na een feest in Boxmeer naar huis rijdt, mag niets gebruikt hebben.",
        ],
        "wijken": "Steenstraat, Centrum, Weijerpark, Boxmeer-Noord, Beugen, Sambeek, Oeffelt, Rijkevoort, Vierlingsbeek, Overloon",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook in Overloon en Vierlingsbeek?", "Ja, de dorpen ten zuiden van Boxmeer tot aan de Limburgse grens horen erbij. Omdat ze nog verder van onze vertrekpunten liggen, kan het tijdvak daar aan de ruime kant van de 60 tot 90 minuten zitten."],
            ["Kunnen jullie tijdens de Boxmeerse Vaart of carnaval bezorgen?", "We bezorgen ook op die dagen, maar alleen op een woonadres en niet in de feesttent of op straat. Bestel bij voorkeur eerder op de dag, want tijdens evenementen zijn delen van het centrum afgesloten en lopen de tijdvakken uit. Zie <a href=\"/service/feestdagen-en-evenementen/\">feestdagen en evenementen</a>."],
            ["Wat doe ik met de lege tank in Boxmeer?", "Een lege tank hoort niet bij het restafval maar kan naar de milieustraat van Land van Cuijk; vraag ons via WhatsApp wat op dat moment de handigste optie is. Meer uitleg vind je bij <a href=\"/informatie/lege-lachgastank-inleveren-brabant/\">lege tanks inleveren</a>."],
        ],
        "nearby": ["cuijk", "grave", "uden"],
        "lat": 51.6460, "lon": 5.9470,
    },
    {
        "slug": "heesch", "name": "Heesch", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Bernheze",
        "title": "Lachgas Heesch | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Heesch? Lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van 't Dorp en De Misse tot De Hoef en Nistelrode. Alleen voor 18+.",
        "h1": "Lachgas bezorgen in Heesch",
        "lead": "Heesch en de kernen van Bernheze, besteld via WhatsApp en meestal binnen 45 tot 60 minuten aan huis geleverd.",
        "intro": [
            "Heesch is de grootste kern van de gemeente Bernheze en huisvest het gemeentehuis aan De Misse, vlak bij 't Dorp, de lange winkelstraat die het dorp van west naar oost doorsnijdt. Het ligt ingeklemd tussen de A59 aan de noordkant en de bossen van de Maashorst in het zuiden, met Oss als directe buur. Wij bezorgen in heel Heesch, inclusief De Hoef en de nieuwere uitbreidingen aan de zuidkant, en in de andere kernen van Bernheze: Nistelrode, Heeswijk-Dinther, Vorstenbosch en Loosbroek. Bestellen doe je door via WhatsApp je adres en het gewenste formaat tank te sturen.",
            "Vanuit 's-Hertogenbosch is Heesch een rechte lijn over de A59, die bij knooppunt Paalgraven overgaat in de A50; onze bezorger neemt de afslag bij het dorp en is dan binnen een paar minuten in je straat. Vanuit Oss is het nog korter, over de Osseweg. Toch rekenen we meestal binnen 45 tot 60 minuten, omdat de rit vanaf het vertrekpunt en eventuele andere leveringen op dezelfde route meetellen. Een station is er niet; de bus over 't Dorp rijdt tussen Oss en Den Bosch, maar wie laat thuiskomt heeft weinig aan die dienstregeling. Je krijgt vooraf via WhatsApp een tijdvak.",
            "Een borrel met vrienden in een rijtjeshuis aan de Schoonstraat vraagt om een ander formaat dan een groot feest in een schuur bij Loosbroek. In ons <a href=\"/lachgas-tanks/\">overzicht van lachgastanks</a> zie je de verschillen tussen 2KG, 4KG en 10KG; weet je het niet, dan adviseren we je in de chat. De tank komt verzegeld aan, de prijs is vooraf bevestigd en je betaalt bij levering contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar of ouder en controleren zo nodig je ID. Lees ook hoe je een tank <a href=\"/informatie/lachgastank-bewaren-en-vervoeren/\">bewaart en vervoert</a>: rechtop, koel en niet in een warme auto.",
        ],
        "wijken": "'t Dorp, De Misse, Schoonstraat, De Hoef, Cereslaan, Osseweg, Nistelrode, Heeswijk-Dinther, Vorstenbosch, Loosbroek",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Horen Heeswijk-Dinther en Nistelrode ook bij jullie gebied?", "Ja, alle kernen van Bernheze zitten in het gebied rond Heesch. Nistelrode ligt direct aan de A50 en is snel bereikbaar; voor Heeswijk-Dinther, Vorstenbosch en Loosbroek kan het tijdvak een kwartier ruimer zijn."],
            ["Is Heesch even snel als Oss?", "Vrijwel wel; Heesch grenst aan Oss en valt in dezelfde band, meestal binnen 45 tot 60 minuten. Rijdt een bezorger toevallig al in Oss, dan ben je vaak eerder aan de beurt, maar daar kunnen we vooraf geen zekerheid over geven."],
            ["Hoe betaal ik bij levering in Heesch?", "Contant of via een Tikkie die we ter plekke sturen; het bedrag staat al in de bevestiging die je bij het bestellen ontving. Vooruitbetalen hoeft nooit. Lees meer bij <a href=\"/service/betalen-bij-levering/\">betalen bij levering</a>."],
        ],
        "nearby": ["oss", "uden", "rosmalen"],
        "lat": 51.7340, "lon": 5.5290,
    },
    {
        "slug": "sint-michielsgestel", "name": "Sint-Michielsgestel", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Sint-Michielsgestel",
        "title": "Lachgas Sint-Michielsgestel | Bezorgd aan huis",
        "description": "Lachgas bestellen in Sint-Michielsgestel? Lachgastanks verzegeld aan huis in Gestel, Berlicum, Den Dungen en Gemonde, besteld via WhatsApp. Alleen 18+.",
        "h1": "Lachgas bezorgen in Sint-Michielsgestel",
        "lead": "Gestel, Berlicum, Den Dungen, Middelrode en Gemonde: bestel via WhatsApp en we zijn er meestal binnen 45 tot 60 minuten.",
        "intro": [
            "Sint-Michielsgestel, in de volksmond Gestel, is een Dommeldorp ten zuidoosten van 's-Hertogenbosch met het Petrus Dondersplein als middelpunt en de Theerestraat als doorgaande winkelstraat. Aan de rand liggen landgoed Zegenwerp, kasteel Nieuw-Herlaer en het oude instituutsterrein van Kentalis, en daaromheen de andere kernen van de gemeente: Berlicum, Middelrode, Den Dungen en Gemonde, met het door een filmreeks bekend geworden Maaskantje. Wij bezorgen in al die dorpen. Je stuurt ons via WhatsApp je adres en het formaat tank dat je wilt, en we bevestigen een tijdvak.",
            "De N617 verbindt Gestel rechtstreeks met 's-Hertogenbosch en loopt door naar Schijndel, wat voor onze bezorgers een vlotte route is zonder snelweg; vanuit Rosmalen rijden we via Berlicum binnendoor. Hoewel de afstand tot de stad klein is, delen we het dorp in bij meestal binnen 45 tot 60 minuten, omdat de dorpen van de gemeente verspreid liggen en we vaak meerdere adressen in één rit combineren. Een treinstation is er niet en de bus naar de stad stopt ’s avonds vroeg, dus thuisbezorging is voor de meeste klanten de praktische keuze. Het tijdvak dat we sturen is wat we echt verwachten te halen.",
            "Voor een avond met een handvol vrienden in een appartement bij het Petrus Dondersplein past de lachgastank 2KG; bij een tuinfeest in Den Dungen of een verjaardag in een boerderij bij Gemonde zijn de <a href=\"/lachgas-tanks/4kg/\">4KG</a> of 10KG geschikter. Alles wordt verzegeld geleverd, met de prijs vooraf bevestigd in de chat, en je rekent bij levering af, contant of via Tikkie. We leveren uitsluitend aan 18-plussers en vragen bij twijfel naar een ID. Wie meer wil weten over wat lachgas met het lichaam doet, leest eerst <a href=\"/informatie/wat-is-lachgas/\">wat lachgas is</a>.",
        ],
        "wijken": "Petrus Dondersplein, Theerestraat, Zegenwerp, Haanwijk, Ruwenberg, Berlicum, Middelrode, Den Dungen, Gemonde, Maaskantje",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Berlicum en Den Dungen?", "Ja, beide dorpen horen bij de gemeente en bij ons gebied. Den Dungen ligt tegen Rosmalen aan en is vanuit de stad zelfs sneller te bereiken dan Gestel zelf; Berlicum en Middelrode nemen we vanaf de kant van Rosmalen mee."],
            ["Hoe snel zijn jullie in Sint-Michielsgestel?", "Meestal binnen 45 tot 60 minuten na bevestiging, afhankelijk van waar onze bezorger op dat moment rijdt en of de N617 vrij is. In het weekend geven we een iets ruimer tijdvak om geen loze beloftes te doen."],
            ["Kan ik ook bestellen als ik maar één avond in Gestel logeer?", "Ja, een vakantieadres of het huis van vrienden is prima, zolang jij er bent als 18-plusser en de bewoner akkoord is. Geef bij voorkeur de naam op de bel door, dan vindt de bezorger de juiste deur. Zie ook <a href=\"/service/bestellen-via-whatsapp/\">bestellen via WhatsApp</a>."],
        ],
        "nearby": ["s-hertogenbosch", "vught", "schijndel"],
        "lat": 51.6410, "lon": 5.3500,
    },
    {
        "slug": "grave", "name": "Grave", "kind": "stad", "region": "noordoost-brabant", "gemeente": "Land van Cuijk",
        "title": "Lachgas Grave | Bezorgd in de vestingstad aan de Maas",
        "description": "Lachgas bestellen in Grave? Lachgastanks 2KG, 4KG en 10KG verzegeld aan huis, van de Hampoort tot Estersveld, De Stoof, Escharen en Velp. Alleen 18+.",
        "h1": "Lachgas bezorgen in Grave",
        "lead": "Vestingstad aan de Maas en sinds 2022 onderdeel van Land van Cuijk: bestellen via WhatsApp, meestal binnen 60 tot 90 minuten geleverd.",
        "intro": [
            "Grave is een kleine vestingstad aan de Maas, met de Hampoort, de Sint-Elisabethkerk en het Arsenaal binnen de oude wallen en de stuw en sluis net buiten de stad. Sinds 1 januari 2022 maakt het deel uit van Land van Cuijk, de fusiegemeente waarin ook Cuijk, Boxmeer, Mill en Sint Anthonis opgingen. Wij bezorgen in de binnenstad rond de Hoofdwagt en de Maaskade, in de woonwijken Estersveld en De Stoof, en in de dorpen Escharen, Gassel en Velp, waar het Emmausklooster staat. Bestellen gaat via WhatsApp: stuur je adres en het formaat tank dat je wilt.",
            "De bezorger rijdt vanuit Oss over de N324 rechtstreeks naar Grave; die weg steekt bij de Maasbrug over naar Gelderland, maar daar stopt ons gebied. Vanuit 's-Hertogenbosch gaat het via de A59 en de A50 of binnendoor over Heesch en Schaijk. Grave ligt in de noordoosthoek van Brabant, en die afstand vertaalt zich in meestal binnen 60 tot 90 minuten. Een station is er niet; het dichtstbijzijnde ligt in Cuijk of Wijchen. Op warme zomeravonden, als de Maaskade en het centrum volstromen, sturen we bewust een ruimer tijdvak, en we laten het direct weten als het eerder lukt.",
            "Een avond in een historisch pand aan de Hoofdwagt vraagt om een ander formaat dan een feest in een loods bij Gassel. We leveren de lachgastank 2KG, 4KG en 10KG; op <a href=\"/lachgas-tanks/\">de tankpagina</a> staan de verschillen. Alles wordt verzegeld afgeleverd, de prijs is vooraf in de chat bevestigd en je betaalt bij levering contant of via Tikkie. We leveren uitsluitend aan personen van 18 jaar of ouder en vragen bij twijfel naar een ID. Lees ook waarom wij alleen tanks bezorgen en geen patronen, bij <a href=\"/informatie/tank-versus-patronen/\">tank versus patronen</a>.",
        ],
        "wijken": "Binnenstad, Hampoort, Hoofdwagt, Maaskade, Estersveld, De Stoof, Escharen, Gassel, Velp",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook aan de overkant van de Maasbrug, in Nederasselt of Wijchen?", "Nee, de John S. Thompsonbrug over de Maas is voor ons de grens: Nederasselt en Wijchen liggen in Gelderland en vallen buiten het gebied. Aan de Brabantse kant komen we overal in en rond Grave."],
            ["Waarom is de levertijd in Grave langer dan in Oss?", "Vanaf onze vertrekpunten is Grave een stuk verder weg dan Oss, over de N324 of via de A50. Daarom geldt hier meestal binnen 60 tot 90 minuten; we bevestigen het tijdvak vooraf zodat je het kunt inplannen."],
            ["Gelden er in Grave regels voor lachgas op straat?", "Landelijk valt lachgas sinds 2023 onder de Opiumwet en gemeenten kunnen in hun APV extra verboden opnemen voor de openbare ruimte, zoals de wallen of het centrum. Raadpleeg de APV van Land van Cuijk en onze <a href=\"/veelgestelde-vragen/regels/\">vragen over regels</a>."],
        ],
        "nearby": ["cuijk", "oss", "boxmeer"],
        "lat": 51.7580, "lon": 5.7380,
    },
    {
        "slug": "boekel", "name": "Boekel", "kind": "dorp", "region": "noordoost-brabant", "gemeente": "Boekel",
        "title": "Lachgas Boekel | Bezorgd aan huis via WhatsApp",
        "description": "Lachgas bestellen in Boekel? Verzegelde lachgastanks aan huis, van het Sint Agathaplein tot De Burgt, De Vlonder en Venhorst. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas bezorgen in Boekel",
        "lead": "Boekel en Venhorst, aan de rand van de Peel: besteld via WhatsApp en meestal binnen 60 tot 90 minuten aan huis.",
        "intro": [
            "Boekel is een van de kleinste zelfstandige gemeenten van Brabant, gelegen op de Peelrand tussen Uden, Gemert en Veghel, met Venhorst als tweede kern en Huize Padua als bekend zorgterrein aan de rand van het dorp. Het Sint Agathaplein en de Kerkstraat vormen het centrum, met daaromheen woonbuurten als De Donk en de nieuwbouw van De Burgt, en bedrijventerrein De Vlonder aan de zuidkant. Wij bezorgen in heel Boekel, in Venhorst en in het buitengebied. Een bestelling plaats je met een WhatsApp-bericht met je adres en het gewenste formaat tank.",
            "Onze bezorgers bereiken Boekel via Uden of Veghel, over de provinciale weg die vanuit Volkel richting Gemert loopt, of vanuit Zuidoost-Brabant via Gemert. Er is geen snelweg in de buurt en geen station, en juist daardoor valt Boekel in de band meestal binnen 60 tot 90 minuten: de kilometers over binnenwegen tellen zwaarder dan de afstand hemelsbreed. We combineren leveringen in Boekel waar mogelijk met Uden of Gemert, en het tijdvak dat je vooraf krijgt houdt daar rekening mee. Verandert er onderweg iets, dan hoor je het in dezelfde chat.",
            "Een avond met een klein gezelschap in een huis aan de Kerkstraat, een verjaardag in De Burgt of een feest in een schuur richting Venhorst: kies de lachgastank 2KG, 4KG of 10KG die bij de groep past. Op <a href=\"/lachgas-tanks/\">de pagina met lachgastanks</a> staan de verschillen op een rij. Elke tank is verzegeld, de prijs is vooraf bevestigd in de chat en je betaalt bij levering contant of via Tikkie. We leveren uitsluitend aan 18-plussers en controleren bij twijfel een ID. Merk je dat iemand in je omgeving moeilijk kan stoppen, lees dan <a href=\"/informatie/problematisch-lachgasgebruik-hulp/\">waar je hulp vindt</a>.",
        ],
        "wijken": "Sint Agathaplein, Kerkstraat, De Donk, De Burgt, De Vlonder, Huize Padua, Venhorst",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook in Venhorst?", "Ja, Venhorst hoort bij de gemeente Boekel en bij ons gebied. Het ligt een paar kilometer verder de Peel in, dus het tijdvak kan iets ruimer zijn dan voor het dorp zelf."],
            ["Waarom is Boekel 60 tot 90 minuten terwijl Uden korter is?", "Uden ligt aan de A50 en is vanaf onze vertrekpunten direct bereikbaar, terwijl Boekel nog een stuk over binnenwegen verder ligt. Die extra kilometers maken het verschil; vanuit Uden of Gemert zelf is het maar een kwartier."],
            ["Hoe vindt de bezorger mijn adres in het buitengebied van Boekel?", "Stuur je volledige adres en, als je afgelegen woont, een herkenningspunt of je locatie via WhatsApp. Zet de buitenverlichting aan als het donker is; dat scheelt zoeken op lange wegen zonder lantaarnpalen."],
        ],
        "nearby": ["uden", "gemert", "veghel"],
        "lat": 51.6020, "lon": 5.6760,
    },
]
