# -*- coding: utf-8 -*-
"""Content voor lachgasbrabant.nl: Zuidoost-Brabant deel A.
Eindhoven met vijf stadsdelen, Helmond, Veldhoven, Best, Geldrop, Mierlo, Valkenswaard, Nuenen en Son en Breugel.
Toegestane HTML in tekstvelden: strong en a (interne paden of rijksoverheid.nl / drugsinfo.nl / trimbos.nl / novadic-kentron.nl)."""

AREAS = [
    {
        "slug": "eindhoven", "name": "Eindhoven", "kind": "stad", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Eindhoven | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Eindhoven? Lachgastanks discreet bezorgd via WhatsApp in Centrum, Strijp-S, Woensel, Tongelre, Stratum en Gestel. Alleen 18+.",
        "h1": "Lachgas Eindhoven",
        "lead": "Lachgastanks verzegeld bezorgd in heel Eindhoven, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Eindhoven is de grootste stad van Noord-Brabant en het hart van de Brainportregio. De stad is opgebouwd uit zeven stadsdelen: Centrum, Woensel-Noord, Woensel-Zuid, Tongelre, Stratum, Gestel en Strijp, met daarbinnen bekende plekken als Strijp-S, de TU/e-campus, het Philips Stadion en de nieuwbouw van Meerhoven aan de westkant. Lachgas Brabant bezorgt lachgastanks in al die stadsdelen, van een studentenhuis bij de Kruisstraat tot een gezinswoning in Blixembosch. Je stuurt een WhatsApp-bericht met je adres en de gewenste maat, waarna we de prijs en een tijdvak bevestigen voordat de bezorger vertrekt.""",
            """Onze bezorgers kennen de Randweg goed: de A2 en N2 lopen langs de westkant van de stad, de A67 sluit aan bij knooppunt Leenderheide en de A58 en A50 komen bij Ekkersweijer en Batadorp samen. Binnen de stad rijden we over de Ring, de Boschdijk, de Kennedylaan en de Aalsterweg, en rond station Eindhoven Centraal en het Stationsplein weten we waar je kunt stoppen. Door die ligging valt Eindhoven in onze snelste band: meestal binnen 30 tot 45 minuten, al kan het op een drukke zaterdagavond rond het centrum iets langer duren. Dat zeggen we dan vooraf.""",
            """Een huisfeest in een appartement op Strijp-S, een verjaardag in Woensel of een avond met huisgenoten in Stratum: kies uit onze <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG het formaat dat bij de grootte van je gezelschap past. Elke tank komt verzegeld bij je aan, je betaalt contant of via Tikkie bij levering en we controleren altijd of iedereen die ontvangt 18 jaar of ouder is. Lees voor je bestelt onze informatie over <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp</a>, en houd rekening met het gebruiksverbod dat in de Eindhovense openbare ruimte geldt.""",
        ],
        "wijken": "Centrum, Strijp-S, Woensel-Noord, Woensel-Zuid, Tongelre, Stratum, Gestel, Meerhoven, TU/e-campus, Stationsplein",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie in alle stadsdelen van Eindhoven?", """Ja, van Acht en Blixembosch in het noorden tot Gestel en Stratum in het zuiden, inclusief Meerhoven, Strijp-S en het centrum rond de Markt. Voor elk stadsdeel hebben we een eigen pagina, bijvoorbeeld <a href="/lachgas-bezorgen/woensel/">lachgas Woensel</a>, waar je de details voor dat deel van de stad vindt."""],
            ["Hoe lang moet ik in Eindhoven op een bestelling wachten?", "In Eindhoven leveren we meestal binnen 30 tot 45 minuten nadat je bestelling via WhatsApp is bevestigd. Op vrijdag- en zaterdagavond, en tijdens evenementen zoals carnaval of Koningsdag in de binnenstad, geven we vooraf een ruimer tijdvak door zodat je weet waar je aan toe bent."],
            ["Kan ik ook een tank laten bezorgen bij een studentenhuis of op de TU/e-campus?", """Bij een woonadres in de stad kan dat, ook bij studentenhuizen rond de Kruisstraat of in Woensel. Op de campus zelf en in studentencomplexen gelden huisregels van de beheerder, en daar leveren we alleen aan de persoon die bestelt en een geldig ID laat zien. Meer over onze controle lees je bij <a href="/service/leeftijdscontrole-18-plus/">leeftijdscontrole 18+</a>."""],
        ],
        "nearby": ["veldhoven", "nuenen", "geldrop"],
        "lat": 51.441, "lon": 5.470,
    },
    {
        "slug": "woensel", "name": "Woensel", "kind": "wijk", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Woensel | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Woensel? Lachgastanks discreet bezorgd via WhatsApp in Woensel-Noord en Woensel-Zuid, van Blixembosch tot Woenselse Markt. 18+.",
        "h1": "Lachgas Woensel",
        "lead": "Lachgastanks verzegeld bezorgd in Woensel-Noord en Woensel-Zuid, besteld via WhatsApp. Alleen voor 18+.",
        "intro": [
            """Woensel is het grootste deel van <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a>: alles ten noorden van het spoor, bestuurlijk verdeeld in de stadsdelen Woensel-Noord en Woensel-Zuid. Hier wonen meer mensen dan in menige Brabantse gemeente, in buurten als Blixembosch, Achtse Barrier, Vaartbroek, Eckart, Prinsejagt, Kronehoef en Hemelrijken, met winkelcentrum Woensel en de Woenselse Markt als drukke middelpunten. Lachgas Brabant bezorgt lachgastanks in al deze buurten en ook in het dorpse Acht. Een WhatsApp-bericht met adres en gewenste maat is genoeg; wij bevestigen de prijs en het tijdvak.""",
            """Vanaf de Randweg rijden we Woensel in via de A58 bij Ekkersweijer of via de Kennedylaan, die dwars door het stadsdeel naar het centrum loopt. De Boschdijk, de Castiliëlaan en de Europalaan zijn onze vaste routes naar de buurten aan weerszijden, en het Catharina Ziekenhuis is een herkenningspunt dat elke bezorger kent. Omdat Woensel direct aan de snelwegen ligt en binnen de stad goed ontsloten is, hanteren we hier dezelfde levertijd als voor de rest van Eindhoven: meestal binnen 30 tot 45 minuten na bevestiging van je bestelling.""",
            """In Woensel bezorgen we vaak aan gezinswoningen in Blixembosch en Achtse Barrier, aan flats langs de Kennedylaan en aan oudere arbeiderswoningen rond de Woenselse Markt. Voor een klein gezelschap is een <a href="/lachgas-tanks/2kg/">2KG lachgastank</a> doorgaans voldoende, bij een grotere groep kies je voor 4KG of 10KG; alle tanks worden verzegeld afgeleverd. Betalen gaat bij de deur, contant of via Tikkie, en we vragen altijd naar een ID van iemand die 18 jaar of ouder is. Op <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">deze pagina</a> lees je wat je moet weten over de risico's.""",
        ],
        "wijken": "Blixembosch, Achtse Barrier, Vaartbroek, Eckart, Prinsejagt, Kronehoef, Hemelrijken, Woenselse Markt, Winkelcentrum Woensel, Acht",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Hoort Acht ook bij jullie bezorggebied Woensel?", "Ja, Acht ligt binnen de gemeentegrens van Eindhoven in Woensel-Noord en we bezorgen er net zo goed als in Blixembosch of Vaartbroek. Omdat het dorp aan de rand ligt, rekenen we op het latere deel van de 30 tot 45 minuten."],
            ["Zijn jullie 's nachts ook in Woensel-Noord te vinden?", """We zijn dag en nacht bereikbaar via WhatsApp, ook voor adressen in Woensel-Noord. 's Nachts vragen we om bij een appartementencomplex zelf naar beneden te komen, zodat de buren rustig doorslapen. Hoe dat precies werkt lees je bij <a href="/service/nachtbezorging/">nachtbezorging</a>."""],
            ["Welke tankmaat past bij een verjaardag thuis in Woensel?", """Dat hangt af van het aantal gasten en hoe lang de avond duurt. Een 2KG tank is handig voor een klein gezelschap, een 4KG tank voor een gemiddelde verjaardag en een 10KG tank voor een groot feest. Twijfel je, stuur dan even een berichtje; op <a href="/lachgas-tanks/">de overzichtspagina</a> staan de verschillen op een rij."""],
        ],
        "nearby": ["eindhoven", "son-en-breugel", "best"],
        "lat": 51.472, "lon": 5.478,
    },
    {
        "slug": "strijp", "name": "Strijp", "kind": "wijk", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Strijp | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Strijp? Lachgastanks discreet bezorgd via WhatsApp op Strijp-S, in Philipsdorp, Drents Dorp en Meerhoven. Dag en nacht, alleen 18+.",
        "h1": "Lachgas Strijp",
        "lead": "Lachgastanks verzegeld bezorgd in Strijp en Meerhoven, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Strijp is het westelijke stadsdeel van <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a> en strekt zich uit van het Philips Stadion tot aan Eindhoven Airport. Het stadsdeel omvat het herontwikkelde fabrieksterrein Strijp-S met zijn lofts en horeca, de buurten Strijp-R en Strijp-T, de oude Philipswijken Philipsdorp en Drents Dorp, en de nieuwbouwwijk Meerhoven met Grasrijk, Zandrijk, Waterrijk en Bosrijk. Lachgas Brabant levert lachgastanks aan huis in heel Strijp. Je appt je adres, de maat die je wilt en het moment waarop het je past, en wij komen terug met een bevestiging.""",
            """Strijp ligt pal aan de Randweg: via de N2 en de A2 zijn Meerhoven en de Zeelsterstraat binnen een paar minuten bereikbaar, en richting Strijp-S rijden we via de Beukenlaan of de Tilburgseweg. Station Eindhoven Strijp-S ligt midden in het gebied en station Eindhoven Centraal is een korte rit verderop. Omdat we vanaf de snelweg nergens de hele stad hoeven te doorkruisen, halen we in Strijp meestal binnen 30 tot 45 minuten je deur. Bij thuiswedstrijden van PSV is het rond het stadion en de Frederiklaan druk, en dan plannen we daar iets ruimer voor.""",
            """Een borrel in een loft aan de Torenallee, een avondje in een rijtjeshuis in Grasrijk of een huisfeest in Philipsdorp: met een <a href="/lachgas-tanks/4kg/">4KG lachgastank</a> zit een gemiddeld gezelschap goed, en voor kleinere of grotere groepen zijn er de 2KG en 10KG. We leveren uitsluitend verzegelde tanks, je rekent af bij levering met contant geld of Tikkie en de ontvanger laat een ID zien waaruit blijkt dat hij of zij 18 jaar of ouder is. Over de regels in de openbare ruimte lees je meer bij <a href="/informatie/lachgas-regels-per-gemeente-brabant/">regels per gemeente</a>.""",
        ],
        "wijken": "Strijp-S, Strijp-R, Strijp-T, Philipsdorp, Drents Dorp, Meerhoven, Grasrijk, Zandrijk, Waterrijk, Philips Stadion",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Komen jullie ook in Meerhoven, dat zo ver aan de westkant ligt?", "Zeker, Meerhoven hoort bij het stadsdeel Strijp en ligt direct aan de N2, waardoor het voor ons juist snel bereikbaar is. Grasrijk, Zandrijk, Waterrijk en Bosrijk vallen allemaal binnen de levertijd van meestal 30 tot 45 minuten."],
            ["Kunnen jullie bezorgen bij een appartement op Strijp-S?", "Ja, we bezorgen regelmatig in de woongebouwen op Strijp-S. Stuur in je bericht het gebouw, de verdieping en de naam op de bel mee, dan hoeft de bezorger niet te zoeken. Vaak vragen we je om even naar de ingang te komen."],
            ["Wat gebeurt er met de tank als die leeg is?", """Een lege tank hoort niet bij het restafval, maar bij het metaal op de milieustraat van de gemeente. Op <a href="/informatie/lege-lachgastank-inleveren-brabant/">lege lachgastank inleveren</a> leggen we uit hoe je dat in Eindhoven regelt en waar je op moet letten."""],
        ],
        "nearby": ["eindhoven", "veldhoven", "gestel"],
        "lat": 51.446, "lon": 5.448,
    },
    {
        "slug": "tongelre", "name": "Tongelre", "kind": "wijk", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Tongelre | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Tongelre? Lachgastanks discreet bezorgd via WhatsApp in Oud-Tongelre, Doornakkers, Lakerlopen, 't Hofke en het Villapark. Alleen 18+.",
        "h1": "Lachgas Tongelre",
        "lead": "Lachgastanks verzegeld bezorgd in het Eindhovense stadsdeel Tongelre, besteld via WhatsApp. Alleen 18+.",
        "intro": [
            """Tongelre is het oostelijke stadsdeel van <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a>, ingeklemd tussen het spoor naar Helmond, het Eindhovensch Kanaal en de gemeentegrens met Nuenen en Geldrop. Het vroegere dorp Tongelre is nog herkenbaar rond de Sint-Martinuskerk in Oud-Tongelre, met daaromheen buurten als Doornakkers, Lakerlopen, 't Hofke, Karpen, Urkhoven, Koudenhoven en het statige Villapark bij de Parklaan. Lachgas Brabant bezorgt lachgastanks in heel Tongelre. Stuur ons via WhatsApp je adres en de gewenste maat, dan bevestigen we de prijs en het tijdvak voordat we gaan rijden.""",
            """Vanuit het centrum is Tongelre dichtbij: via de Tongelresestraat of de Insulindelaan op de Ring sta je zo in Lakerlopen of Doornakkers, en de Eisenhowerlaan brengt ons naar 't Hofke en Karpen. Vanaf de A270 uit Helmond rijden we via de Helmondweg en de Kanaaldijk het stadsdeel in. Station Eindhoven Centraal ligt direct tegen de westrand van Tongelre aan, zodat de adressen rond het Villapark en de Fuutlaan ook vanaf die kant snel te bereiken zijn. Daardoor geldt hier de levertijd van meestal 30 tot 45 minuten, zoals overal in de stad.""",
            """Of je nu een avond met vrienden plant in een jaren-dertigwoning in 't Hofke of een feestje geeft in een appartement bij de Picuskade: kies uit de <a href="/lachgas-tanks/">tanks van 2KG, 4KG en 10KG</a> het formaat dat aansluit bij je gezelschap. We leveren alleen verzegelde tanks, je betaalt bij de deur contant of via Tikkie en we controleren het ID van de ontvanger op de leeftijd van 18 jaar. Wil je weten waar je op moet letten bij bewaren en vervoeren, lees dan <a href="/informatie/lachgastank-bewaren-en-vervoeren/">dit artikel</a> voordat de tank arriveert.""",
        ],
        "wijken": "Oud-Tongelre, Doornakkers, Lakerlopen, 't Hofke, Karpen, Urkhoven, Koudenhoven, Villapark, Picuskade",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Ik woon in Urkhoven aan de rand van Tongelre, komen jullie daar ook?", "Ja, Urkhoven en Koudenhoven liggen weliswaar tegen de grens met Geldrop en Nuenen, maar vallen gewoon onder Eindhoven en onder onze levertijd van meestal 30 tot 45 minuten. Geef bij een adres aan een buitenweg even een herkenningspunt door."],
            ["Kan ik een tank bestellen voor een feest op een boot in het Eindhovensch Kanaal?", "We bezorgen alleen op een woonadres of een ander vast adres waar iemand van 18 jaar of ouder de tank in ontvangst neemt en betaalt. Een ligplaats aan de kade is geen bezorgadres; laat de tank thuis afleveren en neem hem zelf rechtop en afgedekt mee."],
            ["Wat doe ik als iemand tijdens het feest onwel wordt?", """Zet de persoon rustig neer, zorg voor frisse lucht en blijf erbij. Verbetert het niet snel of raakt iemand buiten bewustzijn, bel dan 112. Op <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp</a> staat stap voor stap wat je kunt doen."""],
        ],
        "nearby": ["eindhoven", "nuenen", "geldrop"],
        "lat": 51.443, "lon": 5.512,
    },
    {
        "slug": "stratum", "name": "Stratum", "kind": "wijk", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Stratum | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Stratum? Lachgastanks discreet bezorgd via WhatsApp in Oud-Stratum, de Rochusbuurt, Kortonjo, Tivoli en Gijzenrooi. Alleen 18+.",
        "h1": "Lachgas Stratum",
        "lead": "Lachgastanks verzegeld bezorgd in het Eindhovense stadsdeel Stratum, besteld via WhatsApp. Alleen 18+.",
        "intro": [
            """Stratum ligt direct ten zuiden van het centrum van <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a> en loopt vanaf de Stratumsedijk door tot aan de Randweg en de grens met Geldrop en Waalre. Het stadsdeel kent een grote variatie: de populaire Rochusbuurt en Irisbuurt in Oud-Stratum, de ruime villa's van De Elzent bij het Stadswandelpark, Kortonjo en Burghplan, het volkse Tivoli en de nieuwere buurten Gijzenrooi en Schuttersbosch. Wij bezorgen lachgastanks overal in Stratum. Via WhatsApp geef je je adres en de gewenste maat door, en wij bevestigen direct of het tijdvak haalbaar is.""",
            """Vanuit de binnenstad is Stratum een kwestie van minuten: de Stratumsedijk gaat over in de Aalsterweg, die als een ruggengraat door het stadsdeel naar knooppunt Leenderheide en de A67 loopt. De Leostraat en de Geldropseweg leiden ons naar Tivoli en Kortonjo, de Roostenlaan naar de buurten rond de Genneper Parken. Omdat de A2 en de A67 aan de zuidkant van Stratum samenkomen, komen we vanuit alle richtingen snel het stadsdeel binnen. Daarom geldt hier de levertijd die we voor de hele stad hanteren: meestal binnen 30 tot 45 minuten.""",
            """Een verjaardag in een studentenhuis in de Rochusbuurt, een avond in een gezinswoning in Gijzenrooi of een feest in een appartement aan de Aalsterweg: een <a href="/lachgas-tanks/2kg/">2KG tank</a> volstaat voor een klein groepje, terwijl een 4KG of 10KG tank beter past bij een groter gezelschap. Alle tanks worden verzegeld geleverd en je betaalt bij ontvangst contant of via Tikkie. We bezorgen uitsluitend aan personen van 18 jaar en ouder en vragen daarom altijd een ID. Hoe de bestelling precies verloopt, lees je bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>.""",
        ],
        "wijken": "Oud-Stratum, Rochusbuurt, Irisbuurt, De Elzent, Kortonjo, Burghplan, Tivoli, Gijzenrooi, Schuttersbosch, Genneper Parken",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie ook rond de Aalsterweg en in de buurten bij de Genneper Parken?", "Ja, de hele strook langs de Aalsterweg tot aan Leenderheide hoort bij ons gebied, net als Gennep, Schuttersbosch en Gijzenrooi. Woon je vlak bij het sportpark, geef dan het dichtstbijzijnde kruispunt door zodat de bezorger de juiste ingang kiest."],
            ["Mag ik lachgas gebruiken op straat of op een terras in Stratum?", """Nee, in de gemeente Eindhoven geldt een verbod op het gebruik van lachgas in de openbare ruimte, en sinds 2023 is lachgas voor recreatief gebruik landelijk verboden. Houd het dus binnen op een privéadres. Op <a href="https://www.rijksoverheid.nl">rijksoverheid.nl</a> vind je de actuele landelijke regels."""],
            ["Kan ik overdag op een werkdag bestellen in Stratum?", "Ja, we bezorgen zeven dagen per week, ook door de week overdag. Op werkdagen is de Aalsterweg in de spits druk, maar dat heeft op onze levertijd van meestal 30 tot 45 minuten zelden grote invloed. Je ontvangt hoe dan ook vooraf een tijdvak."],
        ],
        "nearby": ["eindhoven", "geldrop", "waalre"],
        "lat": 51.424, "lon": 5.490,
    },
    {
        "slug": "gestel", "name": "Gestel", "kind": "wijk", "region": "zuidoost-brabant", "gemeente": "Eindhoven",
        "title": "Lachgas Gestel | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Gestel? Lachgastanks discreet bezorgd via WhatsApp in Oud-Gestel, Blaarthem, Bennekel, Genderdal en Hanevoet. Alleen 18+.",
        "h1": "Lachgas Gestel",
        "lead": "Lachgastanks verzegeld bezorgd in het Eindhovense stadsdeel Gestel, besteld via WhatsApp. Alleen 18+.",
        "intro": [
            """Gestel is het zuidwestelijke stadsdeel van <a href="/lachgas-bezorgen/eindhoven/">Eindhoven</a>, tussen de Dommel, de Gender en de Randweg, met Veldhoven en Waalre als buren. Het oude dorpshart ligt rond de Hoogstraat in Oud-Gestel, en daaromheen groeiden Blaarthem, Rapenland, de Bennekel, Genderdal, Hanevoet, Ooievaarsnest en de Gestelse Ontginning, met het Kastelenplein als winkelhart en de High Tech Campus aan de zuidrand. Lachgas Brabant bezorgt lachgastanks in al deze buurten. Een WhatsApp-bericht met je adres en de gewenste maat volstaat; je krijgt van ons de prijs en een tijdvak terug.""",
            """Vanuit het centrum rijden we via de Hoogstraat of de Karel de Grotelaan Gestel in, en vanaf de A2 en N2 nemen we de afslagen bij Veldhoven of de Hanevoet om direct in de buitenste buurten te staan. De Ring, hier de Karel de Grotelaan en de Boutenslaan, verbindt het stadsdeel met Strijp en Stratum. Door die dubbele ontsluiting, vanaf de snelweg en vanuit de stad, is Gestel voor ons een overzichtelijk gebied en halen we de levertijd van meestal 30 tot 45 minuten vrijwel altijd, ook op drukke avonden.""",
            """Een huisfeest in een rijtjeshuis in Hanevoet, een verjaardag in een flat in de Bennekel of een avond met collega's die bij de High Tech Campus werken en in Genderdal wonen: kies op de pagina <a href="/lachgas-tanks/">lachgastanks</a> tussen 2KG, 4KG en 10KG en noem je keuze in je bericht. De tank wordt verzegeld afgeleverd en afgerekend bij de deur, contant of via Tikkie, aan iemand die met een ID aantoont 18 jaar of ouder te zijn. Over het combineren met alcohol, iets wat op een feest snel gebeurt, lees je meer bij <a href="/informatie/lachgas-en-alcohol/">lachgas en alcohol</a>.""",
        ],
        "wijken": "Oud-Gestel, Hoogstraat, Blaarthem, Rapenland, Bennekel, Genderdal, Hanevoet, Ooievaarsnest, Kastelenplein, Gestelse Ontginning",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Ik woon op de grens van Gestel en Veldhoven, welke pagina geldt voor mij?", """Dat maakt voor de levertijd niets uit: zowel Gestel als Veldhoven zit in onze snelste band van meestal 30 tot 45 minuten. Ligt je adres officieel in Veldhoven, kijk dan op <a href="/lachgas-bezorgen/veldhoven/">lachgas Veldhoven</a>; voor Eindhovense adressen is deze pagina de juiste."""],
            ["Bezorgen jullie ook aan flats langs de Karel de Grotelaan?", "Ja, de hoogbouw in de Bennekel en Genderdal kennen onze bezorgers goed. Zet in je bericht de verdieping en de naam op de bel, en kom bij voorkeur zelf naar de centrale ingang zodat de overdracht en de ID-controle snel verlopen."],
            ["Hoe weet ik of de tank onderweg niet is geopend?", """Elke tank verlaat ons depot met een verzegeling die je bij levering zelf controleert voordat je betaalt. Is de verzegeling beschadigd, dan neem je de tank niet aan en zorgen wij voor een andere. Meer over wat je bij levering mag verwachten staat bij <a href="/service/betalen-bij-levering/">betalen bij levering</a>."""],
        ],
        "nearby": ["eindhoven", "veldhoven", "waalre"],
        "lat": 51.425, "lon": 5.457,
    },
    {
        "slug": "helmond", "name": "Helmond", "kind": "stad", "region": "zuidoost-brabant", "gemeente": "Helmond",
        "title": "Lachgas Helmond | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Helmond? Lachgastanks discreet bezorgd via WhatsApp in Centrum, Brandevoort, Mierlo-Hout, Dierdonk en Rijpelberg. Alleen 18+.",
        "h1": "Lachgas Helmond",
        "lead": "Lachgastanks verzegeld bezorgd in heel Helmond, van Brandevoort tot Rijpelberg. Bestellen via WhatsApp, alleen 18+.",
        "intro": [
            """Helmond is na Eindhoven de grootste stad van Zuidoost-Brabant en ligt aan de Zuid-Willemsvaart, met het kasteel en het winkelgebied rond de Markt als middelpunt. De stad bestaat uit duidelijk herkenbare delen: het nieuwe Brandevoort in het westen, de dorpse kernen Mierlo-Hout en Stiphout, Dierdonk in het noorden, Rijpelberg en Brouwhuis aan de oostkant en de wijken Helmond-Noord, -Oost en -West rond het centrum. Lachgas Brabant bezorgt lachgastanks in alle Helmondse wijken. Stuur een WhatsApp met je adres en de tankmaat die je wilt, dan bevestigen we prijs en tijdvak.""",
            """Vanuit Eindhoven rijden we over de A270, die bij Brandevoort de stad binnenkomt en als Europaweg verder loopt richting het centrum en de N270 naar Deurne. De N279 langs het kanaal brengt ons naar Dierdonk in het noorden en Brouwhuis in het zuidoosten. Helmond heeft vier stations, waarvan Helmond Centraal en Helmond Brandevoort voor ons de bekendste oriëntatiepunten zijn. Omdat de stad compact is en direct aan de snelweg ligt, geldt dezelfde levertijd als in Eindhoven: meestal binnen 30 tot 45 minuten. Bij carnaval en tijdens de kermis in het centrum zeggen we er eerlijk bij als het langer duurt.""",
            """Een feestje in een nieuwbouwwoning in Brandevoort, een verjaardag in Dierdonk of een avond met vrienden in een bovenwoning in de binnenstad: op de pagina <a href="/lachgas-tanks/">lachgastanks</a> zie je het verschil tussen 2KG, 4KG en 10KG en kies je wat bij je groep past. Alle tanks komen verzegeld aan en je rekent af bij levering, contant of via Tikkie. We leveren alleen aan mensen van 18 jaar en ouder en vragen daarom een ID. Hoe je iemand helpt die het gebruik niet meer onder controle heeft, lees je bij <a href="/informatie/problematisch-lachgasgebruik-hulp/">hulp bij problematisch gebruik</a>.""",
        ],
        "wijken": "Centrum, Brandevoort, Mierlo-Hout, Stiphout, Dierdonk, Rijpelberg, Brouwhuis, Helmond-Noord, Helmond-Oost, Suytkade",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie ook in Brandevoort en Stiphout aan de westkant van Helmond?", "Ja, Brandevoort en Stiphout liggen voor ons juist gunstig, omdat we vanuit Eindhoven via de A270 als eerste daar aankomen. Beide wijken vallen onder de levertijd van meestal 30 tot 45 minuten die voor heel Helmond geldt."],
            ["Kan ik in Helmond ook op zondag een lachgastank laten bezorgen?", """Zeker, we bezorgen zeven dagen per week, zondag inbegrepen. Op zondag is het in Helmond rustig op de weg, dus de bezorging verloopt dan vaak vlot. Lees meer over onze planning in het weekend bij <a href="/service/weekendbezorging/">weekendbezorging</a>."""],
            ["Hoe gaat de betaling bij een bestelling in Rijpelberg of Brouwhuis?", "Overal in Helmond betaal je pas als de tank voor je staat, contant of via een Tikkie-link die de bezorger ter plekke stuurt. Het bedrag is vooraf via WhatsApp bevestigd, zodat er bij de deur geen verrassingen zijn."],
        ],
        "nearby": ["mierlo", "nuenen", "deurne"],
        "lat": 51.481, "lon": 5.657,
    },
    {
        "slug": "veldhoven", "name": "Veldhoven", "kind": "stad", "region": "zuidoost-brabant", "gemeente": "Veldhoven",
        "title": "Lachgas Veldhoven | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Veldhoven? Lachgastanks discreet bezorgd via WhatsApp in Zeelst, Meerveldhoven, Oerle, Heikant, Zonderwijk en rond De Run. Alleen 18+.",
        "h1": "Lachgas Veldhoven",
        "lead": "Lachgastanks verzegeld bezorgd in heel Veldhoven, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Veldhoven ligt tegen de zuidwestkant van Eindhoven en is uitgegroeid van vier kerkdorpen, Veldhoven-Dorp, Zeelst, Meerveldhoven en Oerle, tot een stad met ruim veertigduizend inwoners. Daartussen liggen wijken als Heikant, Zonderwijk, 't Look, Cobbeek en De Kelen, met het Citycentrum als winkelhart en de nieuwbouw van Zilverackers aan de westrand. Aan de oostkant ligt bedrijventerrein De Run, waar ASML en het Máxima Medisch Centrum veel mensen uit de regio naartoe trekken. Lachgas Brabant bezorgt lachgastanks op elk woonadres in Veldhoven; een WhatsApp-bericht met adres en gewenste maat is het begin.""",
            """Veldhoven is direct op de Randweg aangesloten: vanaf de A2 en N2 rijden we via de Kempenbaan of de afslag bij De Run binnen een paar minuten de stad in, en de A67 ligt aan de zuidkant. De grens met de Eindhovense wijk Meerhoven loopt langs de Heerbaan, zodat Zeelst en Meerhoven voor onze bezorgers vrijwel één gebied vormen. Daarom valt Veldhoven in dezelfde snelle band als Eindhoven: meestal binnen 30 tot 45 minuten. In de avondspits kan het rond De Run en de Kempenbaan even vastlopen; dan houden we daar in het tijdvak rekening mee.""",
            """Een borrel met collega's die bij ASML werken en in Zonderwijk wonen, een verjaardag in een jaren-zeventigwoning in Heikant of een feest in een nieuwe woning in Zilverackers: kies tussen een <a href="/lachgas-tanks/2kg/">2KG tank</a>, een 4KG of een 10KG en geef je keuze door. Elke tank is verzegeld, je betaalt bij levering contant of via Tikkie en de ontvanger toont een ID als bewijs van 18 jaar of ouder. Wil je de tank een paar dagen bewaren voordat het feest begint, lees dan eerst <a href="/informatie/lachgastank-bewaren-en-vervoeren/">bewaren en vervoeren</a>.""",
        ],
        "wijken": "Veldhoven-Dorp, Zeelst, Meerveldhoven, Oerle, Heikant, Zonderwijk, 't Look, Cobbeek, Zilverackers, De Run, Citycentrum",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie ook in Oerle en Zilverackers aan de westkant?", "Ja, ook de kleinere kern Oerle en de nieuwbouw van Zilverackers horen bij ons bezorggebied Veldhoven. Omdat ze verder van de Randweg liggen, komt de bezorger daar eerder tegen het einde van de 30 tot 45 minuten aan dan in Zeelst of Meerveldhoven."],
            ["Kunnen jullie leveren op een bedrijfsadres op De Run?", "Nee, we bezorgen alleen op woonadressen of op een privéadres waar iemand van 18 jaar of ouder de tank aanneemt. Een kantoor, bedrijfshal of parkeerterrein op De Run is geen bezorgadres, ook niet na werktijd."],
            ["Wat als ik mijn bestelling in Veldhoven wil wijzigen nadat ik heb besteld?", """Stuur zo snel mogelijk een berichtje in dezelfde WhatsApp-chat met wat je anders wilt, bijvoorbeeld een andere maat of een later tijdvak. Zolang de bezorger nog niet onderweg is, passen we het kosteloos aan. Hoe dat werkt staat bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>."""],
        ],
        "nearby": ["eindhoven", "waalre", "eersel"],
        "lat": 51.419, "lon": 5.404,
    },
    {
        "slug": "best", "name": "Best", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Best",
        "title": "Lachgas Best | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Best? Lachgastanks discreet bezorgd via WhatsApp in het centrum, Batadorp, Heuveleind, Wilhelminadorp en Salderes. Alleen 18+.",
        "h1": "Lachgas Best",
        "lead": "Lachgastanks verzegeld bezorgd in Best, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Best ligt ten noordwesten van Eindhoven, aan de A2 en aan het spoor naar 's-Hertogenbosch, en groeide uit tot een gemeente met bijna dertigduizend inwoners. Het dorp heeft een compact centrum rond de Hoofdstraat en de Sint-Odulphuskerk, de karakteristieke fabriekswijk Batadorp uit de jaren dertig, en woonwijken als Heuveleind, Wilhelminadorp, Salderes, Speelheide, Heivelden en de Leeuwerik. Aan de noordkant wordt gebouwd in Dijkstraten en Aarle. Lachgas Brabant bezorgt lachgastanks in heel Best. Stuur een WhatsApp met je adres en de gewenste maat; wij antwoorden met de prijs en een tijdvak.""",
            """Vanuit Eindhoven rijden we via de A2 naar afslag Best, of via de Boschdijk en de Eindhovenseweg binnendoor door Acht. Station Best ligt midden in het dorp en vanaf daar zijn Heuveleind en Wilhelminadorp in een paar minuten te bereiken. Omdat de afstand tot Eindhoven klein is en de A2 bijna tot in het dorp loopt, zit Best in onze snelste band: meestal binnen 30 tot 45 minuten na bevestiging. Alleen als de A2 bij Batadorp vaststaat, wat in de avondspits voorkomt, melden we vooraf dat het tijdvak iets ruimer wordt.""",
            """Een tuinfeest in Salderes, een verjaardag in een hoekwoning in Heivelden of een avond met vrienden in een appartement bij het station: een <a href="/lachgas-tanks/4kg/">4KG tank</a> is voor een gemiddeld gezelschap de gebruikelijke keuze, en 2KG en 10KG zijn er voor kleinere en grotere groepen. Tanks worden verzegeld geleverd, je betaalt bij de deur contant of via Tikkie en iedereen die aanneemt laat een ID zien waaruit de leeftijd van 18 jaar of ouder blijkt. Kijk voor de gemeentelijke regels in Best bij <a href="/informatie/lachgas-regels-per-gemeente-brabant/">regels per gemeente</a>.""",
        ],
        "wijken": "Centrum, Batadorp, Heuveleind, Wilhelminadorp, Salderes, Speelheide, Heivelden, De Leeuwerik, Dijkstraten, Aarle",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Komen jullie ook in Aarle en het buitengebied van Best?", "Ja, Aarle en de buitenwegen richting Oirschot en Son horen bij de gemeente Best en dus bij ons bezorggebied. Bij een adres zonder duidelijke straatverlichting helpt het als je een lichtje aan de voordeur doet of een herkenningspunt noemt."],
            ["Bezorgen jullie ook 's avonds laat in Best?", """We zijn dag en nacht via WhatsApp bereikbaar en bezorgen ook laat in de avond en 's nachts. In een rustig dorp als Best vragen we je om zelf naar de deur te komen, zodat de bezorger niet hoeft aan te bellen. Meer daarover bij <a href="/service/nachtbezorging/">nachtbezorging</a>."""],
            ["Waarom bezorgen jullie alleen tanks en geen patronen?", """Tanks zijn hervulbaar, worden verzegeld geleverd en leveren veel minder metaalafval op dan losse patronen met een cracker. Het verschil leggen we uit in <a href="/informatie/tank-versus-patronen/">tank versus patronen</a>."""],
        ],
        "nearby": ["eindhoven", "son-en-breugel", "oirschot"],
        "lat": 51.507, "lon": 5.390,
    },
    {
        "slug": "geldrop", "name": "Geldrop", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Geldrop-Mierlo",
        "title": "Lachgas Geldrop | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Geldrop? Lachgastanks discreet bezorgd via WhatsApp in het centrum, Braakhuizen, Coevering, Skandia en Zesgehuchten. Alleen 18+.",
        "h1": "Lachgas Geldrop",
        "lead": "Lachgastanks verzegeld bezorgd in Geldrop, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Geldrop ligt direct ten oosten van Eindhoven, aan de Kleine Dommel en aan de rand van de Strabrechtse Heide, en vormt samen met Mierlo de gemeente Geldrop-Mierlo. Het centrum rond de Heuvel, de Korte Kerkstraat en het kasteel is compact, met daaromheen de wijken Braakhuizen-Noord en -Zuid, Coevering, Skandia, Hulst, Akert en Genoenhuis, en het oude kerkdorp Zesgehuchten tegen de Eindhovense grens. Lachgas Brabant bezorgt lachgastanks in alle Geldropse wijken. Stuur ons een WhatsApp met je adres en de maat die je wilt, dan bevestigen we prijs en tijdvak.""",
            """Vanuit Eindhoven is Geldrop een korte rit: via de Geldropseweg door Stratum, via de A67 naar afslag Geldrop of via de Eindhovenseweg langs Zesgehuchten. Station Geldrop aan de lijn Eindhoven–Weert ligt aan de westkant van het centrum, en het St. Anna Ziekenhuis is een bekend punt in het zuiden van het dorp. Door de ligging pal naast de stad en de aansluiting op de A67 bij Leenderheide valt Geldrop in onze snelste band: meestal binnen 30 tot 45 minuten. Op zomerse weekenden kan de weg naar de heide druk zijn, maar dat raakt onze routes nauwelijks.""",
            """Een verjaardag in Coevering, een feestje in een rijtjeshuis in Braakhuizen-Zuid of een avond met vrienden in een appartement bij de Heuvel: vergelijk op <a href="/lachgas-tanks/">lachgastanks</a> de maten 2KG, 4KG en 10KG en noem in je bericht welke je wilt. We leveren verzegeld, je betaalt bij levering contant of via Tikkie en we controleren het ID van de ontvanger op 18 jaar of ouder. Een lachgastank kan in de kou anders reageren dan je verwacht; lees daarover meer bij <a href="/informatie/lachgas-bij-kou-en-warmte/">lachgas bij kou en warmte</a>.""",
        ],
        "wijken": "Centrum, Heuvel, Braakhuizen-Noord, Braakhuizen-Zuid, Coevering, Skandia, Hulst, Akert, Genoenhuis, Zesgehuchten",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Hoort Zesgehuchten bij Geldrop of bij Eindhoven voor jullie bezorging?", "Zesgehuchten valt onder de gemeente Geldrop-Mierlo en dus onder deze pagina, maar in de praktijk maakt het geen verschil: beide kanten van de grens bezorgen we meestal binnen 30 tot 45 minuten. De bezorger komt meestal via de Eindhovenseweg aan."],
            ["Bezorgen jullie ook in Mierlo, het andere dorp van de gemeente?", """Ja, maar Mierlo ligt verder van de snelweg en heeft daarom een eigen pagina met een iets ruimere levertijd. Kijk op <a href="/lachgas-bezorgen/mierlo/">lachgas Mierlo</a> voor de details voor dat deel van de gemeente."""],
            ["Kan ik een tank ophalen in plaats van laten bezorgen?", "Nee, we werken uitsluitend met bezorging aan huis. Zo controleren we ter plekke de leeftijd van de ontvanger en zorgen we dat de tank rechtop en verzegeld op de plek van bestemming aankomt."],
        ],
        "nearby": ["eindhoven", "mierlo", "heeze"],
        "lat": 51.421, "lon": 5.560,
    },
    {
        "slug": "mierlo", "name": "Mierlo", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Geldrop-Mierlo",
        "title": "Lachgas Mierlo | 45-60 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Mierlo? Lachgastanks discreet bezorgd via WhatsApp in het dorp, Loeswijk, Luchen, Kerkakkers en rond de Molenheide. Alleen 18+.",
        "h1": "Lachgas Mierlo",
        "lead": "Lachgastanks verzegeld bezorgd in Mierlo, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Mierlo ligt tussen Geldrop en Helmond, aan de noordkant van de Strabrechtse Heide, en hoort bij de gemeente Geldrop-Mierlo. Het dorp heeft een gezellige kern rond de Dorpsstraat en de Heilige Luciakerk, met daaromheen buurten als Loeswijk en Kerkakkers, de nieuwbouwwijk Luchen aan de Helmondse kant en het bosrijke recreatiegebied Molenheide in het zuiden. Richting Nuenen ligt landgoed Gulbergen met de Gulbergenheuvel. Lachgas Brabant bezorgt lachgastanks op elk woonadres in Mierlo; stuur een WhatsApp met je straat, huisnummer en de gewenste maat, en we bevestigen prijs en tijdvak.""",
            """Vanuit Eindhoven rijden we via de A270 tot Brandevoort en dan via de Brandevoortse Dreef en de Geldropseweg het dorp in, of via Geldrop over de Mierloseweg. Het dichtstbijzijnde station is Helmond Brandevoort, op een paar minuten rijden van Luchen. Mierlo ligt net iets verder van de snelwegen dan Geldrop en Helmond en we rijden er altijd via een omliggende kern naartoe. Daarom hanteren we hier de middelste band: meestal binnen 45 tot 60 minuten na bevestiging. Rijden we toevallig al in Helmond, dan zijn we er vaak sneller.""",
            """Een verjaardag in een vrijstaand huis aan de rand van Molenheide, een feest in een nieuwbouwwoning in Luchen of een avond met vrienden in Loeswijk: een <a href="/lachgas-tanks/2kg/">2KG tank</a> past bij een klein gezelschap, een 4KG of 10KG bij een groter feest. Tanks worden verzegeld geleverd en afgerekend bij de deur, contant of via Tikkie, aan iemand die met een ID laat zien 18 jaar of ouder te zijn. Rijd na een feest niet zelf; wat de regels zijn en hoe je thuiskomt, lees je bij <a href="/informatie/lachgas-in-het-verkeer/">lachgas in het verkeer</a>.""",
        ],
        "wijken": "Dorpsstraat, Loeswijk, Kerkakkers, Luchen, Molenheide, Gulbergen, Mierlo-Oost, Brandevoortse Dreef",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Waarom is de levertijd in Mierlo langer dan in Geldrop?", "Geldrop ligt direct aan de A67 en tegen Eindhoven aan, terwijl we voor Mierlo altijd eerst door Geldrop of Helmond rijden. Die extra kilometers maken het verschil tussen meestal 30 tot 45 minuten en meestal 45 tot 60 minuten; vaak zijn we eerder, maar dat beloven we niet."],
            ["Bezorgen jullie ook op het vakantiepark bij Molenheide?", "We leveren alleen op een vast woonadres waar iemand van 18 jaar of ouder de tank aanneemt en betaalt. Op vakantieparken en campings gelden de regels van de beheerder en daar bezorgen we niet; laat de tank op je huisadres leveren."],
            ["Kan ik voor een feest in het weekend in Mierlo vooraf reserveren?", """Ja, en voor een dorp met een ruimere levertijd is dat zelfs verstandig. Stuur een paar dagen vooraf je adres, de maat en het gewenste tijdvak, dan plannen we de bezorger in. Lees meer bij <a href="/service/weekendbezorging/">weekendbezorging</a>."""],
        ],
        "nearby": ["geldrop", "helmond", "nuenen"],
        "lat": 51.440, "lon": 5.620,
    },
    {
        "slug": "valkenswaard", "name": "Valkenswaard", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Valkenswaard",
        "title": "Lachgas Valkenswaard | 45-60 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Valkenswaard? Lachgastanks discreet bezorgd via WhatsApp rond de Markt, in Dommelen, Geenhoven, Hoge Akkers en Lage Heide. Alleen 18+.",
        "h1": "Lachgas Valkenswaard",
        "lead": "Lachgastanks verzegeld bezorgd in Valkenswaard en Dommelen, besteld via WhatsApp. Alleen voor 18+.",
        "intro": [
            """Valkenswaard ligt ten zuiden van Eindhoven en Waalre, aan de Dommel en tegen de Belgische grens, en is bekend om de horeca rond de Markt en het natuurgebied De Malpie. De gemeente omvat naast het hoofddorp ook Dommelen aan de westkant van de Dommel en het kleine Borkel en Schaft in het zuiden. Woonbuurten als Geenhoven, Hoge Akkers, 't Gegraaf, Kerkakkers, Turfberg en Schepelweijen liggen rond het centrum, en aan de zuidrand groeit de nieuwe wijk Lage Heide. Lachgas Brabant bezorgt lachgastanks in heel Valkenswaard. Stuur een WhatsApp met adres en gewenste maat, en wij bevestigen prijs en tijdvak.""",
            """Vanuit Eindhoven rijden we via de Aalsterweg en de N69 door Waalre naar Valkenswaard, of via de A67 en de nieuwe Westparallel langs Dommelen. De Europalaan en de Eindhovenseweg brengen ons vervolgens naar de buurten rond de Markt en verder naar Borkel en Schaft. Valkenswaard heeft geen station, dus alles gaat over de weg, en de rit vanaf de Randweg duurt wat langer dan naar de directe buurgemeenten van Eindhoven. Daarom geldt hier onze middelste band: meestal binnen 45 tot 60 minuten. Op vrijdag- en zaterdagavond is het rond de Markt druk; dan plannen we iets ruimer.""",
            """Een verjaardag in een gezinswoning in Dommelen, een avond met vrienden in Geenhoven of een huisfeest in een nieuwe woning in Lage Heide: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG en kies het formaat dat bij je groep past. De tank komt verzegeld aan, je betaalt bij levering contant of via Tikkie en de ontvanger laat een ID zien als bewijs van 18 jaar of ouder. Bezorgen op straat, op een terras of in een café doen we niet; waarom dat zo is lees je bij <a href="/veelgestelde-vragen/regels/">vragen over regels</a>.""",
        ],
        "wijken": "Markt, Dommelen, Geenhoven, Hoge Akkers, 't Gegraaf, Kerkakkers, Turfberg, Schepelweijen, Lage Heide, Borkel en Schaft",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Borkel en Schaft, helemaal in het zuiden?", "Ja, Borkel en Schaft hoort bij de gemeente Valkenswaard en we komen er, maar reken op het einde van de band van meestal 45 tot 60 minuten of iets daarboven. We geven vooraf via WhatsApp een eerlijke indicatie voor zo'n buitengelegen adres."],
            ["Kan ik lachgas laten bezorgen bij een café of op een terras aan de Markt?", "Nee, we bezorgen alleen op privéadressen aan iemand van 18 jaar of ouder. Horeca en openbare ruimte vallen buiten ons bezorggebied, ook omdat gebruik daar in strijd is met de landelijke regels en de gemeentelijke APV."],
            ["Ik woon in Dommelen, aan de andere kant van de Dommel. Maakt dat uit?", "Nee, Dommelen ligt voor ons zelfs gunstig omdat we vanaf de A67 via de Westparallel als eerste daar aankomen. De levertijd is dezelfde als in de rest van Valkenswaard, meestal binnen 45 tot 60 minuten."],
        ],
        "nearby": ["waalre", "eindhoven", "bergeijk"],
        "lat": 51.351, "lon": 5.460,
    },
    {
        "slug": "nuenen", "name": "Nuenen", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Nuenen, Gerwen en Nederwetten",
        "title": "Lachgas Nuenen | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Nuenen? Lachgastanks discreet bezorgd via WhatsApp in het centrum, Nuenen-Zuid, Nuenen-West, Eeneind en Gerwen. Alleen 18+.",
        "h1": "Lachgas Nuenen",
        "lead": "Lachgastanks verzegeld bezorgd in Nuenen, Gerwen en Nederwetten, besteld via WhatsApp. Alleen voor 18+.",
        "intro": [
            """Nuenen ligt direct ten oosten van Eindhoven en is vooral bekend als het dorp waar Vincent van Gogh twee jaar woonde en werkte. Het centrum rond het Park, de Berg en het Vincentre is klein en groen, met daaromheen de woonwijken Nuenen-Zuid, Nuenen-Oost en het nieuwe Nuenen-West richting Eindhoven, en het bedrijventerrein en de woonbuurt Eeneind aan de zuidkant. De kerkdorpen Gerwen en Nederwetten in het noorden horen bij dezelfde gemeente. Lachgas Brabant bezorgt lachgastanks in al deze kernen. Stuur een WhatsApp met adres en gewenste maat; wij bevestigen prijs en tijdvak.""",
            """Vanuit Eindhoven rijden we via de A270 en de Helmondweg, die bij Nuenen-West het dorp bereikt, of binnendoor via de Collse Hoefdijk langs de Collse Watermolen en via de Opwettenseweg. Vanaf station Eindhoven Centraal is het hemelsbreed maar een paar kilometer naar het Park. Nuenen grenst direct aan het stadsdeel Tongelre en ligt aan de snelweg naar Helmond, en daarom hanteren we dezelfde levertijd als in de stad: meestal binnen 30 tot 45 minuten. Gerwen en Nederwetten liggen iets verder, dus daar komen we eerder tegen het einde van dat tijdvak aan.""",
            """Een verjaardag in een jaren-zestigwoning in Nuenen-Zuid, een feest in een nieuwbouwhuis in Nuenen-West of een avond met vrienden in een boerderij bij Gerwen: op <a href="/lachgas-tanks/">lachgastanks</a> staan de maten 2KG, 4KG en 10KG naast elkaar, zodat je snel kiest. We leveren uitsluitend verzegeld, je rekent af bij de deur met contant geld of Tikkie en we controleren of de ontvanger 18 jaar of ouder is. Lachgas is sinds 2023 voor recreatief gebruik verboden; wat dat voor jou betekent lees je bij <a href="/informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a>.""",
        ],
        "wijken": "Centrum, Park, Berg, Nuenen-Zuid, Nuenen-Oost, Nuenen-West, Eeneind, Gerwen, Nederwetten, Opwetten",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie ook in Gerwen en Nederwetten?", "Ja, beide kerkdorpen horen bij de gemeente Nuenen en bij ons bezorggebied. Ze liggen een paar kilometer ten noorden van het centrum, dus de bezorger is daar meestal aan het einde van de 30 tot 45 minuten; een drukke avond kan het iets langer maken."],
            ["Ik woon in Nuenen-West, vlak bij de Eindhovense grens. Welke pagina gebruik ik?", """Deze pagina, want Nuenen-West ligt binnen de gemeente Nuenen. Voor adressen net over de grens in Eindhoven kijk je op <a href="/lachgas-bezorgen/tongelre/">lachgas Tongelre</a>, maar de levertijd is aan beide kanten gelijk."""],
            ["Kan ik voor een groot tuinfeest in Nuenen meerdere tanks bestellen?", "Dat kan, geef in je bericht het aantal en de maten door, dan bevestigen we vooraf de totaalprijs en een tijdvak. Voor een groot gezelschap is één 10KG tank vaak overzichtelijker dan meerdere kleine, en alles wordt verzegeld geleverd."],
        ],
        "nearby": ["eindhoven", "son-en-breugel", "helmond"],
        "lat": 51.470, "lon": 5.553,
    },
    {
        "slug": "son-en-breugel", "name": "Son en Breugel", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Son en Breugel",
        "title": "Lachgas Son en Breugel | 30-45 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Son en Breugel? Lachgastanks discreet bezorgd via WhatsApp in Son, Breugel, Sonniuspark, De Gentiaan en 't Zand. Alleen 18+.",
        "h1": "Lachgas Son en Breugel",
        "lead": "Lachgastanks verzegeld bezorgd in Son en Breugel, besteld via WhatsApp. Alleen voor 18 jaar en ouder.",
        "intro": [
            """Son en Breugel ligt ten noorden van Eindhoven, waar de Dommel het Wilhelminakanaal kruist, en bestaat uit de twee oude dorpen Son en Breugel met daartussen de rivier. Son heeft het winkelcentrum rond de Nieuwstraat en het Kerkplein, Breugel het dorpse hart rond de Sint-Genovevakerk; daaromheen liggen buurten als De Gentiaan, 't Zand, 't Harde Ven, Breeakker en de nieuwbouw van Sonniuspark. Aan de zuidkant ligt het grote bedrijventerrein Ekkersrijt. Lachgas Brabant bezorgt lachgastanks op woonadressen in beide dorpen. Een WhatsApp met je adres en de gewenste maat volstaat; je krijgt de prijs en een tijdvak terug.""",
            """Vanuit Eindhoven rijden we via de A50 naar afslag Son en Breugel of via de Boschdijk en Ekkersrijt het dorp binnen, en de A58 bij knooppunt Ekkersweijer is nooit ver weg. Voor Breugel nemen we de Van den Elsenstraat over de Dommel of komen we via Nederwetten vanuit Nuenen aan. Een station is er niet, maar de Eindhovense wijk Blixembosch grenst bijna aan Son, dus de afstand vanaf de stad is minimaal. Daarom valt Son en Breugel in onze snelste band: meestal binnen 30 tot 45 minuten na bevestiging van je bestelling.""",
            """Een barbecue in een vrijstaand huis in Sonniuspark, een verjaardag in een rijtjeshuis in De Gentiaan of een avond met vrienden in Breugel: een <a href="/lachgas-tanks/4kg/">4KG tank</a> is de meest gekozen maat voor een gemiddeld gezelschap, met 2KG en 10KG als alternatief. Elke tank is verzegeld, betalen doe je bij levering contant of via Tikkie, en we vragen een ID van de ontvanger om de leeftijd van 18 jaar te controleren. Over onze eigen rol in de uitstoot van N2O en wat je zelf kunt doen, lees je bij <a href="/informatie/lachgas-en-het-milieu/">lachgas en het milieu</a>.""",
        ],
        "wijken": "Son, Breugel, Sonniuspark, De Gentiaan, 't Zand, 't Harde Ven, Breeakker, Kerkplein, Nieuwstraat, Ekkersrijt",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie ook op bedrijventerrein Ekkersrijt?", "Nee, Ekkersrijt is een bedrijventerrein en daar bezorgen we niet, ook niet bij een bedrijfsfeest. We leveren uitsluitend op woonadressen in Son en Breugel aan iemand van 18 jaar of ouder die de tank aanneemt en betaalt."],
            ["Zijn jullie net zo snel in Breugel als in Son?", "Ja, het verschil is een brug over de Dommel en een paar minuten rijden. Beide dorpen vallen onder de levertijd van meestal 30 tot 45 minuten; alleen bij adressen aan de buitenwegen richting Nederwetten of Sint-Oedenrode kan het iets langer duren."],
            ["Hoe weet ik zeker dat de bezorger echt van jullie is?", """Je ontvangt vooraf via WhatsApp een bevestiging met het tijdvak, en de bezorger kent jouw naam en bestelling. Je betaalt pas als de verzegelde tank voor je staat, nooit vooraf. Meer over hoe wij omgaan met je gegevens lees je in ons <a href="/privacy/">privacybeleid</a>."""],
        ],
        "nearby": ["eindhoven", "best", "nuenen"],
        "lat": 51.515, "lon": 5.493,
    },
]
