# -*- coding: utf-8 -*-
# Plaatspagina's Midden-Brabant (12) + 's-Hertogenbosch, Rosmalen en Oss uit Noordoost-Brabant. Alleen data.
AREAS = [
 {'slug': 'tilburg', 'name': 'Tilburg', 'kind': 'stad', 'region': 'midden-brabant', 'gemeente': 'Tilburg',
  'title': 'Lachgas bestellen Tilburg | 24/7 bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Tilburg? Lachgastanks 2KG, 4KG en 10KG verzegeld bezorgd in Reeshof, Noord, Centrum en Zuid, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Tilburg',
  'lead': 'Lachgastank nodig in Tilburg? Stuur een WhatsApp-bericht en we brengen een verzegelde tank naar je adres, van de Reeshof tot de Spoorzone.',
  'intro': [
   'Tilburg is de grootste stad van Midden-Brabant en strekt zich uit van de Reeshof in het westen tot Berkel-Enschot en Udenhout aan de oostkant. Wij bezorgen lachgastanks in alle stadsdelen: Tilburg-Noord en Oud-Noord rond het Wilhelminapark, het Centrum met de Spoorzone en de Piushaven, Oud-Zuid, Zuid langs de Stappegoorweg en West bij de universiteit. Bestellen doe je via WhatsApp: je stuurt je adres, de gewenste tankmaat en een tijdvak, wij bevestigen de prijs en de verwachte aankomsttijd. Daarna hoef je alleen nog thuis te zijn als de koerier aanbelt.',
   'Onze koeriers rijden vanuit het stedelijk gebied en gebruiken de ringbanen om snel van wijk naar wijk te komen. Vanaf de A58 en de A65 pakken ze de Ringbaan-Zuid of Ringbaan-Oost, en voor de Reeshof is de N261 via de Burgemeester Letschertweg de kortste route. Omdat Tilburg compact is en de meeste adressen binnen een kwartier rijden van elkaar liggen, valt de stad in onze snelste levertijdband: meestal binnen 30 tot 45 minuten. Woon je vlak bij station Tilburg of Tilburg Universiteit, noem dan een duidelijk herkenningspunt bij je adres, zodat de koerier niet hoeft te zoeken in de drukke binnenstad.',
   'Een studentenhuis in Oud-Noord vraagt om iets anders dan een feest in een loods aan de Piushaven. Voor een kleine groep is de 2KG-tank doorgaans voldoende, voor een avond met meer gasten kies je de 4KG of 10KG; op <a href="/lachgas-tanks/">de assortimentspagina</a> staat per maat wat je mag verwachten. Je betaalt contant of via Tikkie bij levering, de prijs is vooraf via WhatsApp bevestigd. We leveren uitsluitend aan personen van 18 jaar of ouder en controleren je legitimatie aan de deur. Bekijk voordat je bestelt ook onze uitleg over <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp bij lachgas</a>.',
  ],
  'wijken': 'Reeshof, Tilburg-Noord, Oud-Noord, Centrum, Spoorzone, Piushaven, Oud-Zuid, Zuid, West, Stappegoor',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Bezorgen jullie ook in de Reeshof en in Tilburg-Noord?', 'Ja, de Reeshof, Tilburg-Noord en alle andere stadsdelen vallen binnen hetzelfde bezorggebied en dezelfde levertijdband. De Reeshof ligt iets verder van het centrum, maar via de N261 en de Burgemeester Letschertweg is de koerier er doorgaans net zo snel.'],
   ['Kan ik een tank laten bezorgen bij station Tilburg of in de Spoorzone?', 'Dat kan, zolang er een adres of een duidelijk afleverpunt is waar we je persoonlijk treffen. We leveren niet aan onbeheerde plekken; in de Spoorzone spreken we meestal een ingang of een straatnaam af, zodat de overdracht en de leeftijdscontrole rustig kunnen gebeuren.'],
   ['Mag ik lachgas gebruiken op straat of in een park in Tilburg?', 'Nee. Lachgas valt sinds 2023 onder de Opiumwet en veel Brabantse gemeenten hebben daarnaast in hun APV regels over gebruik in de openbare ruimte. Raadpleeg de actuele regels op <a href="https://www.rijksoverheid.nl">rijksoverheid.nl</a> en bij de gemeente, en gebruik alleen op een privéadres.'],
  ],
  'nearby': ['goirle', 'berkel-enschot', 'udenhout'],
  'lat': 51.5555, 'lon': 5.0913},

 {'slug': 'waalwijk', 'name': 'Waalwijk', 'kind': 'stad', 'region': 'midden-brabant', 'gemeente': 'Waalwijk',
  'title': 'Lachgas bestellen Waalwijk | Snel bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Waalwijk? Verzegelde lachgastanks bezorgd in Waalwijk, Sprang-Capelle en Waspik, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Waalwijk',
  'lead': 'Van Baardwijk tot Landgoed Driessen: een WhatsApp-bericht is genoeg om een verzegelde lachgastank in Waalwijk aan huis te krijgen.',
  'intro': [
   'Waalwijk ligt aan de noordrand van Midden-Brabant, tussen de Loonse en Drunense Duinen en de Bergsche Maas. De gemeente bestaat uit de stad zelf met wijken als Baardwijk, Besoyen, Laageinde, De Hoef en Zanddonk, de nieuwbouw op Landgoed Driessen en de kernen Sprang-Capelle en Waspik langs de A59. Op al die adressen komen we aan de deur. Je bestelt door ons via WhatsApp je straat, huisnummer en de gewenste tankmaat te sturen; wij reageren met een bevestiging van de prijs en een verwacht tijdvak, zodat je weet waar je aan toe bent.',
   'De koerier komt meestal via de A59 of de N261 vanuit de richting Tilburg en rijdt daarna via de Taxandriaweg of de Groenewoudlaan de wijken in. Waalwijk ligt een stuk buiten de grote steden, en Waspik en Sprang-Capelle liggen weer een paar kilometer westelijker, waardoor de rit per bestelling varieert. Daarom plannen we hier in de middelgrote band: meestal binnen 45 tot 60 minuten. Met het openbaar vervoer is Waalwijk alleen per bus bereikbaar, dus we vragen een adres waar de koerier met de auto voor de deur kan staan en jij de tank direct kunt aannemen.',
   'Een rustige vrijdagavond met vrienden in Besoyen of een verjaardag met een grotere groep in Sprang-Capelle: de tankmaat bepaalt hoe lang je vooruit kunt. Op <a href="/lachgas-tanks/">het overzicht van onze tanks</a> vind je de 2KG, 4KG en 10KG met uitleg over het verschil. Elke tank wordt verzegeld geleverd en je betaalt pas bij ontvangst, contant of met een Tikkie. Onze koerier vraagt altijd naar een geldig legitimatiebewijs, want we leveren uitsluitend aan 18-plussers. Bekijk vooraf ook de <a href="/veelgestelde-vragen/veiligheid/">veelgestelde vragen over veiligheid</a>, zeker als je voor het eerst bestelt.',
  ],
  'wijken': 'Centrum, Baardwijk, Besoyen, Laageinde, De Hoef, Zanddonk, Landgoed Driessen, Sprang-Capelle, Waspik',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Komen jullie ook in Waspik en Sprang-Capelle?', 'Ja, beide kernen horen bij de gemeente Waalwijk en bezorgen we net als de stad zelf. Omdat ze westelijker langs de A59 liggen kan de koerier een paar minuten langer onderweg zijn; het tijdvak dat we vooraf doorgeven houdt daar rekening mee.'],
   ['Kan ik overdag bestellen voor levering in de avond in Waalwijk?', 'Zeker, en voor Waalwijk raden we dat zelfs aan. Stuur je bestelling via WhatsApp met het gewenste tijdvak, dan zetten we de rit alvast in de planning en bevestigen we de prijs. Je betaalt gewoon bij levering.'],
   ['Wat doe ik met een lege tank na een feest in Waalwijk?', 'Een lege tank hoort niet bij het restafval. Je kunt hem inleveren bij de milieustraat van je eigen gemeente; informeer vooraf naar de voorwaarden. Meer daarover lees je in <a href="/informatie/lege-lachgastank-inleveren-brabant/">ons artikel over lege tanks inleveren</a>.'],
  ],
  'nearby': ['drunen', 'kaatsheuvel', 'tilburg'],
  'lat': 51.6830, 'lon': 5.0680},

 {'slug': 'dongen', 'name': 'Dongen', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Dongen',
  'title': 'Lachgas bestellen Dongen | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Dongen? Lachgastanks 2KG, 4KG en 10KG verzegeld bezorgd in Dongen, Beljaart en ’s Gravenmoer, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Dongen',
  'lead': 'Woon je in Dongen, de Beljaart of ’s Gravenmoer? Stuur een WhatsApp-bericht en een verzegelde lachgastank komt naar je toe.',
  'intro': [
   'Dongen ligt tussen Tilburg en Oosterhout, met het Wilhelminakanaal als zuidgrens en de Beljaart als jongste woonwijk aan de noordkant. De gemeente telt naast het dorp zelf de kernen ’s Gravenmoer, Dongen-Vaart en Klein-Dongen, en ook daar komen onze koeriers. Of je nu in de Biezen woont, in West 1 of West 2 of aan de rand van het centrum bij de Hoge Ham: je bestelt met één WhatsApp-bericht waarin je adres, tankmaat en het liefst ook een tijdvak staan. Wij sturen een bevestiging terug met de prijs en de verwachte aankomst.',
   'Vanuit Tilburg rijdt de koerier via de N632 richting Dongen, vanuit Oosterhout via de N629. Beide routes zijn kort, maar Dongen ligt net buiten het stedelijk gebied en de kernen ’s Gravenmoer en Dongen-Vaart liggen weer een stuk noordelijker aan het kanaal. Daarom rekenen we hier met de middelgrote band: meestal binnen 45 tot 60 minuten. Een treinstation heeft Dongen niet, en de bus rijdt beperkt in de avond, dus we komen altijd met de auto tot aan je voordeur. Geef bij een appartement of hofje even aan hoe de ingang te vinden is, dan verliest de koerier geen tijd.',
   'Een barbecue in de tuin in de Beljaart, een kleine borrel in een rijtjeshuis in de Biezen of een groter feest in een schuur bij ’s Gravenmoer: elke situatie vraagt een andere hoeveelheid. Kies tussen de 2KG, 4KG en 10KG op <a href="/lachgas-tanks/">onze tankpagina</a>; twijfel je, dan denken we via WhatsApp mee. Betalen gaat contant of met Tikkie zodra de koerier de verzegelde tank overhandigt. Leeftijd controleren we altijd, zonder uitzondering, en we leveren niet aan minderjarigen. Hoe je een tank thuis bewaart lees je in <a href="/informatie/lachgastank-bewaren-en-vervoeren/">dit artikel over bewaren en vervoeren</a>.',
  ],
  'wijken': 'Centrum, Hoge Ham, Biezen, West 1, West 2, Beljaart, ’s Gravenmoer, Dongen-Vaart, Klein-Dongen',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in ’s Gravenmoer en Dongen-Vaart?', 'Ja, alle kernen van de gemeente Dongen horen bij ons bezorggebied. Voor ’s Gravenmoer en Dongen-Vaart rekent de koerier een paar minuten extra rijtijd vanaf het dorp, wat binnen het opgegeven tijdvak past.'],
   ['Hoe snel is een lachgastank in Dongen bij me?', 'Voor Dongen geven we als indicatie meestal binnen 45 tot 60 minuten. Op drukke avonden of bij werkzaamheden aan de N629 kan het iets uitlopen; het tijdvak dat we via WhatsApp bevestigen is dan leidend.'],
   ['Kan ik in Dongen ook ’s nachts bestellen?', 'Ja, we zijn via WhatsApp dag en nacht bereikbaar en bezorgen ook in de late uren. Houd er rekening mee dat we in woonwijken rustig aanbellen en niet claxonneren; lees meer op <a href="/service/nachtbezorging/">de pagina over nachtbezorging</a>.'],
  ],
  'nearby': ['rijen', 'tilburg', 'oosterhout'],
  'lat': 51.6267, 'lon': 4.9400},

 {'slug': 'rijen', 'name': 'Rijen', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Gilze en Rijen',
  'title': 'Lachgas bestellen Rijen | 24/7 bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Rijen? Lachgastanks 2KG, 4KG en 10KG verzegeld bezorgd in Rijen, Gilze, Hulten en Molenschot, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Rijen',
  'lead': 'Rijen ligt op een steenworp van Tilburg en Breda, dus een lachgastank is er snel: één WhatsApp-bericht en de koerier komt eraan.',
  'intro': [
   'Rijen is de grootste kern van de gemeente Gilze en Rijen en ligt precies tussen Tilburg en Breda, met de spoorlijn en de A58 als vaste begrenzing. We bezorgen in heel het dorp, van de oudere buurten rond de Hoofdstraat en de Julianastraat tot de Vliegende Vennen en Wolfsweide aan de zuidkant, en ook in Gilze, Hulten en Molenschot. Bestellen gaat via WhatsApp: je noemt je adres, de tankmaat en wanneer je de tank wilt ontvangen. Wij antwoorden met de prijs en een tijdvak, en de koerier laat weten wanneer hij vertrekt.',
   'Doordat Rijen vlak langs de A58 ligt en via de N282 direct met Tilburg en Breda verbonden is, zit de koerier er vanuit beide steden binnen een kwartier. Daarom hoort het dorp bij onze snelste band: meestal binnen 30 tot 45 minuten. Station Gilze-Rijen ligt midden in het dorp, maar wij komen uiteraard met de auto naar je woonadres. Bij de buurten aan de noordkant van het spoor, zoals Rijen-Noord, kan een gesloten overweg een minuut kosten; dat is al ingecalculeerd in het tijdvak dat we vooraf doorgeven. Gilze en Molenschot liggen iets verder, maar vallen onder dezelfde indicatie.',
   'Of het nu een avond met huisgenoten is of een tuinfeest in Gilze met een flinke groep, de keuze tussen 2KG, 4KG en 10KG bepaalt hoe de avond loopt. Op <a href="/lachgas-tanks/4kg/">de pagina van de 4KG-tank</a> lees je waarom dat voor veel middelgrote groepen de meest gekozen maat is. De tank komt verzegeld aan en je betaalt bij de deur, contant of via Tikkie, nooit vooraf. Legitimatie is verplicht: de koerier controleert of iedereen die de tank aanneemt 18 jaar of ouder is. Lees ook <a href="/informatie/lachgas-en-alcohol/">waarom lachgas en alcohol een slechte combinatie zijn</a> voordat je bestelt.',
  ],
  'wijken': 'Centrum, Rijen-Noord, Rijen-Zuid, Vliegende Vennen, Wolfsweide, Gilze, Hulten, Molenschot',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Bezorgen jullie ook in Gilze, Hulten en Molenschot?', 'Ja, de hele gemeente Gilze en Rijen valt binnen ons gebied. Gilze ligt aan de andere kant van de A58 en Molenschot richting Tilburg, maar beide zijn vanuit Rijen in enkele minuten bereikbaar, zodat dezelfde levertijd geldt.'],
   ['Ik woon in Rijen maar werk in Breda, kan ik de tank daar laten bezorgen?', 'Dat kan, zolang het afleveradres een plek is waar je de tank persoonlijk kunt aannemen en we je legitimatie kunnen controleren. Kijk op <a href="/lachgas-bezorgen/breda/">onze pagina voor Breda</a> voor de levertijd die daar geldt en geef in je bericht duidelijk aan welk adres het wordt.'],
   ['Hoe weet ik dat de tank in Rijen onaangebroken is?', 'Elke tank gaat met een intacte verzegeling op pad en de koerier overhandigt hem zo aan jou. Controleer de zegel bij ontvangst voordat je betaalt; is er iets niet in orde, dan neem je de tank niet aan en lossen we het via WhatsApp op.'],
  ],
  'nearby': ['tilburg', 'dongen', 'breda'],
  'lat': 51.5906, 'lon': 4.9231},

 {'slug': 'goirle', 'name': 'Goirle', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Goirle',
  'title': 'Lachgas bestellen Goirle | 24/7 bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Goirle? Verzegelde lachgastanks 2KG, 4KG en 10KG aan huis in Goirle en Riel, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Goirle',
  'lead': 'Goirle grenst direct aan Tilburg-Zuid, dus een lachgastank is er snel bezorgd. Bestel via WhatsApp en betaal pas aan de deur.',
  'intro': [
   'Goirle ligt tegen de zuidrand van Tilburg aan, gescheiden door de A58 en verder omringd door de Regte Heide en de bossen richting de Belgische grens. Onze koeriers bezorgen in alle buurten: het centrum rond de Tilburgseweg en het Kloosterplein, De Hellen, Grobbendonck, Abcoven en de nieuwere wijk Boschkens aan de kant van de snelweg, plus het kerkdorp Riel. Een bestelling plaatsen doe je door via WhatsApp je adres en de gewenste tankmaat door te geven. We bevestigen de prijs en melden hoe laat je ons ongeveer kunt verwachten.',
   'Vanuit Tilburg is Goirle via de afrit op de A58 of rechtstreeks via de Goirleseweg binnen een paar minuten bereikbaar, en ook vanaf de A58 richting Breda is het maar één afslag. Omdat de koerier bijna geen tijd kwijt is aan de aanrijroute, delen we Goirle in bij onze snelste band: meestal binnen 30 tot 45 minuten. Riel ligt een paar kilometer westelijker over de Rielseweg en hoort bij dezelfde indicatie. Goirle heeft geen station; de bus uit Tilburg stopt wel in het dorp, maar voor een levering is dat niet relevant omdat we toch tot aan je voordeur rijden.',
   'Een gezellige avond in een twee-onder-een-kapwoning in Boschkens vraagt om minder dan een feest op een boerderij bij Riel. Vergelijk daarom eerst de 2KG, 4KG en 10KG op <a href="/lachgas-tanks/">de overzichtspagina van onze tanks</a> en kies wat bij je gezelschap past. De koerier levert de tank verzegeld af en je betaalt ter plekke contant of met Tikkie. Iedereen die bij ons bestelt moet 18 jaar of ouder zijn en dat met een ID kunnen aantonen. In onze <a href="/veelgestelde-vragen/veiligheid/">vragen over veiligheid</a> lees je waar je op moet letten als je lachgas in huis hebt.',
  ],
  'wijken': 'Centrum, Kloosterplein, De Hellen, Grobbendonck, Abcoven, Boschkens, De Grootte Akkers, Riel',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Horen Riel en de Regte Heide ook bij het bezorggebied van Goirle?', 'Riel wel: het kerkdorp hoort bij de gemeente Goirle en we bezorgen er met dezelfde levertijd. De Regte Heide is natuurgebied, daar bezorgen we niet; we leveren alleen op woon- of verblijfsadressen waar we je persoonlijk kunnen treffen.'],
   ['Is de levertijd in Goirle dezelfde als in Tilburg?', 'Ja, Goirle ligt zo dicht tegen Tilburg aan dat we dezelfde indicatie hanteren, meestal binnen 30 tot 45 minuten. Alleen tijdens piekmomenten op vrijdag- en zaterdagavond kan het tijdvak dat we bevestigen iets ruimer zijn.'],
   ['Kan ik een tank meenemen naar een feest buiten Goirle?', 'Vervoer van lachgas voor recreatief gebruik valt onder de Opiumwet, en de regels daarover zijn streng. Lees eerst ons artikel over <a href="/informatie/is-lachgas-legaal-in-nederland/">de wet rond lachgas in Nederland</a> en laat de tank liever bezorgen op het adres waar je hem gaat gebruiken.'],
  ],
  'nearby': ['tilburg', 'hilvarenbeek', 'rijen'],
  'lat': 51.5206, 'lon': 5.0656},

 {'slug': 'oisterwijk', 'name': 'Oisterwijk', 'kind': 'stad', 'region': 'midden-brabant', 'gemeente': 'Oisterwijk',
  'title': 'Lachgas bestellen Oisterwijk | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Oisterwijk? Verzegelde lachgastanks bezorgd in Oisterwijk, Moergestel en Haaren, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Oisterwijk',
  'lead': 'Een lachgastank in Oisterwijk, Moergestel of Haaren? Eén WhatsApp-bericht met je adres is genoeg; we bevestigen prijs en tijdvak meteen.',
  'intro': [
   'Oisterwijk staat bekend om De Lind en de vennen, maar het is ook een gemeente met flinke woonwijken: Pannenschuur en Westend aan de westkant, de Waterhoef en de Bunders richting het spoor, en sinds 2021 ook de kernen Haaren en Moergestel. In al die buurten en dorpen bezorgen we lachgastanks. Je stuurt ons via WhatsApp je adres, de maat die je wilt en het tijdvak dat je voor ogen hebt. Daarna ontvang je een bevestiging met de prijs, zodat er aan de deur geen verrassingen zijn.',
   'De koerier bereikt Oisterwijk via de A58 (afrit Oisterwijk) of via de N65 wanneer hij vanuit de kant van ’s-Hertogenbosch komt; Haaren ligt direct aan die N65 en Moergestel aan de A58. Oisterwijk ligt een stuk oostelijker dan Tilburg en de drie kernen liggen onderling ook weer uit elkaar, waardoor we hier met een ruimere indicatie werken: meestal binnen 45 tot 60 minuten. Station Oisterwijk ligt aan de lijn Tilburg–Eindhoven, maar onze bezorging gaat altijd per auto naar je huisadres, ook in de rustige lanen rond de Gemullehoekenweg.',
   'Een borrel met buren in de Waterhoef of een feestweekend in een vakantiehuis bij Moergestel: de gewenste hoeveelheid verschilt, en daarom hebben we drie maten. Kijk op <a href="/lachgas-tanks/">onze assortimentspagina</a> welke van de 2KG, 4KG of 10KG past bij jouw avond. Betalen gebeurt pas als de verzegelde tank bij je is, contant of via Tikkie. We bezorgen alleen aan 18-plussers en controleren dat met een legitimatiebewijs, ook bij herhaalbestellingen. Lees ook <a href="/informatie/lachgas-bij-kou-en-warmte/">wat temperatuur doet met een lachgastank</a>, handig als je buiten zit.',
  ],
  'wijken': 'Centrum, De Lind, Pannenschuur, Westend, Waterhoef, Bunders, Moergestel, Haaren, Heukelom',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in Moergestel en Haaren?', 'Ja, sinds de herindeling horen Haaren en Moergestel bij de gemeente Oisterwijk en we bezorgen er met dezelfde indicatie als in Oisterwijk zelf. Vermeld in je bericht wel duidelijk de kern, omdat sommige straatnamen in de regio dubbel voorkomen.'],
   ['Kan ik lachgas laten bezorgen bij een vakantiepark rond Oisterwijk?', 'Dat kan alleen als het park dat toestaat en we je bij de receptie of op het huisjesnummer persoonlijk kunnen treffen. Vraag het vooraf na bij het park en geef ons het exacte nummer door; op veel parken gelden eigen huisregels over lachgas.'],
   ['Hoe lang duurt bezorgen in Oisterwijk op een zaterdagavond?', 'We gaan uit van meestal binnen 45 tot 60 minuten, maar zaterdagavond is in heel Midden-Brabant de drukste periode. Bestel daarom liever vroeg op de dag en kies een tijdvak; meer tips vind je op <a href="/service/weekendbezorging/">de pagina over weekendbezorging</a>.'],
  ],
  'nearby': ['tilburg', 'berkel-enschot', 'udenhout'],
  'lat': 51.5789, 'lon': 5.1897},

 {'slug': 'kaatsheuvel', 'name': 'Kaatsheuvel', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Loon op Zand',
  'title': 'Lachgas bestellen Kaatsheuvel | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Kaatsheuvel? Verzegelde lachgastanks bezorgd in Kaatsheuvel, Loon op Zand en De Moer, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Kaatsheuvel',
  'lead': 'Kaatsheuvel, Loon op Zand of De Moer: stuur ons een WhatsApp-bericht en een verzegelde lachgastank wordt bij je thuisgebracht.',
  'intro': [
   'Kaatsheuvel is de grootste kern van de gemeente Loon op Zand en ligt aan de noordkant van de Loonse en Drunense Duinen, met de Efteling als bekende buur. Wij bezorgen in het hele dorp, van de Pannenhoef en De Hoogt tot het winkelgebied rond de Gasthuisstraat en het Anton Pieckplein, en daarnaast in Loon op Zand en De Moer. Een bestelling begint met een WhatsApp-bericht waarin je adres, de gewenste maat en een voorkeurstijd staan. Je krijgt van ons een bevestiging van de prijs en van het tijdvak waarin de koerier aankomt.',
   'De snelste route naar Kaatsheuvel loopt over de N261 tussen Tilburg en Waalwijk, met de afrit bij de Efteling; vanuit Waalwijk is het via de Europalaan maar een paar minuten. Toch ligt het dorp buiten het stedelijk gebied en vormen de Loonse en Drunense Duinen een barrière zonder doorgaande wegen, waardoor de koerier altijd via de N261 moet. Vandaar de middelgrote indicatie: meestal binnen 45 tot 60 minuten. Openbaar vervoer beperkt zich tot de bus richting Tilburg en Waalwijk, dus wij komen met de auto tot aan je deur, ook in Loon op Zand en in het buurtschap De Moer.',
   'Een verjaardag in een rijtjeshuis in de Pannenhoef, een vrijgezellenavond in een vakantiehuisje bij de duinen of een groter feest in Loon op Zand: voor elke groep is er een passende tank. Op <a href="/lachgas-tanks/2kg/">de pagina over de 2KG-tank</a> lees je waarom die voor een klein gezelschap vaak genoeg is; voor meer mensen kies je 4KG of 10KG. Je betaalt bij levering, contant of via Tikkie, en pas nadat je de verzegeling hebt gecontroleerd. We leveren uitsluitend aan volwassenen en vragen altijd om een ID. Kijk ook naar <a href="/informatie/lachgas-regels-per-gemeente-brabant/">de regels per gemeente in Brabant</a>.',
  ],
  'wijken': 'Centrum, Anton Pieckplein, Gasthuisstraat, Pannenhoef, De Hoogt, Efteling, Loon op Zand, De Moer',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in Loon op Zand en De Moer?', 'Ja, beide kernen horen bij dezelfde gemeente als Kaatsheuvel en vallen binnen onze indicatie van meestal 45 tot 60 minuten. Loon op Zand ligt richting Tilburg aan de N261 en is voor de koerier zelfs iets sneller te bereiken dan Kaatsheuvel zelf.'],
   ['Kan ik lachgas laten bezorgen bij een vakantiepark in Kaatsheuvel?', 'Alleen als het park dat toelaat en we je persoonlijk kunnen treffen op het huisje of bij de receptie. Veel parken rond de Efteling hebben eigen huisregels over lachgas; informeer daar eerst en stuur ons daarna het exacte huisjesnummer.'],
   ['Wat als de tank in Kaatsheuvel niet binnen het afgesproken tijdvak komt?', 'Loopt een rit uit door drukte op de N261 of door een eerdere levering, dan laten we dat via WhatsApp weten voordat het tijdvak voorbij is. De indicatie is geen vaste toezegging; wijzigen of annuleren kan zolang de koerier nog niet vertrokken is, zie <a href="/service/bestellen-via-whatsapp/">de stappen op onze bestelpagina</a>.'],
  ],
  'nearby': ['waalwijk', 'drunen', 'tilburg'],
  'lat': 51.6572, 'lon': 5.0383},

 {'slug': 'vlijmen', 'name': 'Vlijmen', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Heusden',
  'title': 'Lachgas bestellen Vlijmen | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Vlijmen? Verzegelde lachgastanks aan huis in Vlijmen, Nieuwkuijk en Haarsteeg, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Vlijmen',
  'lead': 'Vlijmen ligt vlak onder ’s-Hertogenbosch aan de A59. Bestel je lachgastank via WhatsApp en betaal pas als de koerier voor je staat.',
  'intro': [
   'Vlijmen is de grootste kern van de gemeente Heusden en ligt direct ten westen van ’s-Hertogenbosch, met de A59 als noordgrens en de Moerputten als groene buffer richting de stad. We bezorgen in het hele dorp, van het centrum rond het Plein en de Vliedberg tot de Vijfhoeven en de nieuwbouw in De Grassen, en ook in Nieuwkuijk, Haarsteeg en Hedikhuizen. Bestellen doe je door via WhatsApp je adres, de tankmaat en een gewenst tijdvak te sturen; wij bevestigen daarna de prijs en de verwachte aankomsttijd van de koerier.',
   'Komt de koerier vanuit ’s-Hertogenbosch, dan is Vlijmen via de A59 of de Vlijmenseweg in enkele minuten bereikbaar; vanuit Waalwijk of Drunen loopt de route over dezelfde A59 in oostelijke richting. Dat Vlijmen toch in de middelgrote band zit, komt doordat onze ritten in dit deel van Brabant vaak uit de richting Tilburg of ’s-Hertogenbosch worden gecombineerd en de kernen Haarsteeg en Hedikhuizen noordelijk van het dorp liggen. Reken daarom op meestal binnen 45 tot 60 minuten. Een station is er niet; de bus uit Den Bosch stopt wel op de Wolput, maar wij komen met de auto aan huis.',
   'Een avond met vrienden in de Vijfhoeven vraagt iets anders dan een feest in een schuur bij Haarsteeg. Daarom bieden we drie maten aan; op <a href="/lachgas-tanks/">het tankoverzicht</a> zie je het verschil tussen 2KG, 4KG en 10KG en kies je wat bij je gezelschap past. Betalen doe je bij levering, contant of via Tikkie, nooit vooraf. De koerier levert alleen aan 18-plussers en controleert dat met een geldig legitimatiebewijs. Wil je weten hoe je een tank bewaart tot de avond begint, lees dan <a href="/informatie/lachgastank-bewaren-en-vervoeren/">onze uitleg over bewaren en vervoeren</a>.',
  ],
  'wijken': 'Centrum, Vliedberg, Vijfhoeven, De Grassen, Wolput, Nieuwkuijk, Haarsteeg, Hedikhuizen',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in Nieuwkuijk, Haarsteeg en Hedikhuizen?', 'Ja, alle kernen van de gemeente Heusden rond Vlijmen vallen binnen ons bezorggebied. Haarsteeg en Hedikhuizen liggen noordelijker richting de Maas, waardoor de koerier daar een paar minuten langer rijdt dan naar het dorp zelf.'],
   ['Is de levertijd in Vlijmen dezelfde als in ’s-Hertogenbosch?', 'Niet helemaal. Voor ’s-Hertogenbosch hanteren we een snellere indicatie, voor Vlijmen meestal binnen 45 tot 60 minuten, omdat we ritten hier vaak combineren met Drunen en Waalwijk. Het tijdvak dat we via WhatsApp bevestigen is altijd leidend.'],
   ['Kan ik in Vlijmen een tank bestellen voor een feest op een later moment?', 'Ja, je kunt via WhatsApp een dag of enkele dagen vooruit bestellen en een tijdvak afspreken. Dat raden we rond feestdagen aan; lees hoe dat werkt op <a href="/service/feestdagen-en-evenementen/">onze pagina over feestdagen en evenementen</a>.'],
  ],
  'nearby': ['drunen', 's-hertogenbosch', 'waalwijk'],
  'lat': 51.6967, 'lon': 5.2217},

 {'slug': 'drunen', 'name': 'Drunen', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Heusden',
  'title': 'Lachgas bestellen Drunen | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Drunen? Verzegelde lachgastanks bezorgd in Drunen, Elshout en de vesting Heusden, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Drunen',
  'lead': 'Van de Venne tot aan de Drunense Duinen: een WhatsApp-bericht met je adres volstaat om een verzegelde lachgastank in Drunen te laten bezorgen.',
  'intro': [
   'Drunen ligt tussen Waalwijk en Vlijmen, pal ten noorden van de Loonse en Drunense Duinen en met de A59 aan de bovenkant van het dorp. Onze koeriers bezorgen in alle buurten: de Venne-Oost en Venne-West, Braken-Oost en Braken-West, het centrum rond het Raadhuisplein en de buurten richting de duinen, en daarnaast in Elshout, Oudheusden en de vesting Heusden aan de Maas. Een bestelling plaats je via WhatsApp met je adres en de tankmaat; wij laten de prijs en het tijdvak weten voordat de koerier vertrekt.',
   'De A59 brengt de koerier vanuit ’s-Hertogenbosch of vanuit de kant van Waalwijk tot de afrit Drunen, waarna het via de Spoorlaan of de Stationsstraat nog maar een paar minuten is. Drunen ligt echter op afstand van de grote steden en de vesting Heusden en Oudheusden liggen nog weer noordelijker, bijna aan de Maas. Daarom hanteren we hier meestal binnen 45 tot 60 minuten. Een spoorverbinding heeft Drunen al lang niet meer, ondanks de straatnamen die eraan herinneren, dus we komen uitsluitend met de auto en bellen aan op het adres dat je hebt doorgegeven.',
   'Een rustige avond in Braken-West, een feest in een schuur in Elshout of een weekend met vrienden in een huisje bij de duinen: de omvang van je groep bepaalt de tank. Bekijk <a href="/lachgas-tanks/10kg/">de pagina van de 10KG-tank</a> als je een grotere groep verwacht, of kies anders de 2KG of 4KG. Betalen kan contant of via Tikkie op het moment van levering, en de prijs is al via WhatsApp vastgelegd. Zonder geldig ID van iemand van 18 jaar of ouder laten we geen tank achter. Lees vooraf ook <a href="/informatie/lachgas-en-vitamine-b12/">waarom lachgas de vitamine B12-huishouding beïnvloedt</a>.',
  ],
  'wijken': 'Centrum, Raadhuisplein, Venne-Oost, Venne-West, Braken-Oost, Braken-West, Elshout, Oudheusden, Heusden-vesting',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in de vesting Heusden en in Elshout?', 'Ja, Heusden-vesting, Oudheusden en Elshout horen bij ons gebied rond Drunen. In de vesting zijn de straten smal en is parkeren beperkt, dus noem in je bericht een plek waar de koerier kort kan stoppen en je de tank kunt aannemen.'],
   ['Mag ik met een lachgastank de Drunense Duinen in?', 'Nee. De Loonse en Drunense Duinen zijn een nationaal park, en bezit van lachgas voor recreatief gebruik is sinds 2023 overal in Nederland verboden onder de Opiumwet. Gebruik alleen op een privéadres en kijk voor de regels op <a href="https://www.rijksoverheid.nl">rijksoverheid.nl</a>.'],
   ['Hoe lang duurt bezorgen in Drunen op een doordeweekse avond?', 'Op een rustige avond halen we de indicatie van meestal binnen 45 tot 60 minuten doorgaans ruim, maar we noemen bewust een tijdvak in plaats van een exact tijdstip. Je ontvangt via WhatsApp een bericht zodra de koerier richting Drunen vertrekt.'],
  ],
  'nearby': ['vlijmen', 'waalwijk', 'kaatsheuvel'],
  'lat': 51.6850, 'lon': 5.1350},

 {'slug': 'hilvarenbeek', 'name': 'Hilvarenbeek', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Hilvarenbeek',
  'title': 'Lachgas bestellen Hilvarenbeek | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Hilvarenbeek? Verzegelde lachgastanks bezorgd in Hilvarenbeek, Diessen en Esbeek, meestal binnen 60 tot 90 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Hilvarenbeek',
  'lead': 'Hilvarenbeek ligt ten zuiden van Tilburg richting de grens. Bestel je lachgastank via WhatsApp; we bevestigen vooraf prijs en tijdvak.',
  'intro': [
   'Hilvarenbeek is een landelijke gemeente onder Tilburg en Goirle, met het Vrijthof als historisch hart en de Beekse Bergen als bekendste trekpleister. Naast het dorp zelf bezorgen we in de kerkdorpen Diessen, Esbeek, Haghorst, Biest-Houtakker en Baarschot, die verspreid liggen tussen de N269 en het Wilhelminakanaal. Bestellen werkt hier net als overal: je stuurt via WhatsApp je adres, de tankmaat en een tijdvak dat je uitkomt, en wij antwoorden met de prijs en de verwachte aankomsttijd. Vermeld bij een buitengebiedadres graag een herkenningspunt, want navigatie is daar niet altijd precies.',
   'De koerier rijdt vanuit Tilburg over de N269 in zuidelijke richting, of komt via de A58, afrit Moergestel en de N395 het dorp binnen. Hilvarenbeek ligt op een kwartier tot twintig minuten van de stad, en de kerkdorpen liggen daar nog eens enkele kilometers vandaan over smalle wegen. Omdat ritten naar deze hoek zelden met andere adressen te combineren zijn, geven we een ruimere indicatie: meestal binnen 60 tot 90 minuten. Een station is er niet en de bus rijdt in de avond beperkt, dus elke levering gaat met de auto rechtstreeks naar het adres dat je hebt opgegeven.',
   'Een familiefeest in een boerderij bij Esbeek, een vriendenweekend in een huisje bij de Beekse Bergen of gewoon een avond thuis aan het Vrijthof: de grootte van je gezelschap bepaalt welke maat verstandig is. Op <a href="/lachgas-tanks/">het overzicht van de 2KG, 4KG en 10KG</a> staan de verschillen op een rij. Je betaalt bij levering, contant of via Tikkie, na controle van de verzegeling. We leveren uitsluitend aan personen van 18 jaar of ouder en vragen daarvoor naar een ID. Op <a href="/service/bezorgtijden-per-regio/">de pagina over bezorgtijden per regio</a> lees je waarom Hilvarenbeek in de ruimere band valt.',
  ],
  'wijken': 'Centrum, Vrijthof, Beekse Bergen, Diessen, Esbeek, Haghorst, Biest-Houtakker, Baarschot',
  'levertijd': 'meestal binnen 60 tot 90 minuten',
  'faq': [
   ['Bezorgen jullie ook in Diessen, Esbeek en Haghorst?', 'Ja, alle kerkdorpen van de gemeente Hilvarenbeek horen bij ons bezorggebied en vallen onder dezelfde indicatie van meestal 60 tot 90 minuten. Voor adressen in het buitengebied helpt het als je een herkenbaar punt of de kleur van het huis doorgeeft.'],
   ['Kan ik lachgas laten bezorgen op de camping of in een huisje bij de Beekse Bergen?', 'Alleen als het park dat toestaat en je ons persoonlijk kunt ontvangen op het nummer van je plek of huisje. Recreatieparken hebben vaak eigen regels over lachgas, dus vraag dat eerst na voordat je bij ons bestelt.'],
   ['Waarom is de levertijd in Hilvarenbeek langer dan in Goirle?', 'Goirle grenst direct aan Tilburg, terwijl Hilvarenbeek en de kerkdorpen een stuk zuidelijker liggen en de koerier er over provinciale en landelijke wegen naartoe rijdt. Daarom rekenen we hier meestal 60 tot 90 minuten; op <a href="/lachgas-bezorgen/goirle/">de pagina voor Goirle</a> zie je het verschil.'],
  ],
  'nearby': ['goirle', 'tilburg', 'oisterwijk'],
  'lat': 51.4867, 'lon': 5.1378},

 {'slug': 'udenhout', 'name': 'Udenhout', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Tilburg',
  'title': 'Lachgas bestellen Udenhout | Bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Udenhout? Verzegelde lachgastanks 2KG, 4KG en 10KG aan huis in Udenhout en Biezenmortel, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Udenhout',
  'lead': 'Udenhout hoort bij Tilburg maar heeft een eigen dorps karakter. Bestel je lachgastank via WhatsApp en ontvang hem verzegeld aan de deur.',
  'intro': [
   'Udenhout ligt ten noordoosten van Tilburg, tussen de Loonse en Drunense Duinen en de N65, en maakt sinds 1997 deel uit van de gemeente Tilburg. Het dorp heeft een compact centrum rond de Slimstraat en de Kreitenmolenstraat, nieuwere buurten als Den Bogerd en Achthoeven, en sinds 2021 ook het kerkdorp Biezenmortel binnen de grenzen. In al die delen bezorgen we lachgastanks. Stuur ons via WhatsApp je adres, de maat die je wilt en een tijdvak, dan bevestigen we de prijs en laten we weten wanneer de koerier er ongeveer is.',
   'Vanuit Tilburg rijdt de koerier via de Bosscheweg en de N65 of binnendoor via Berkel-Enschot naar Udenhout; vanaf de N65 is het bij de afslag Udenhout nog een paar minuten tot het centrum. Het dorp ligt verder van de stad dan Berkel-Enschot en de wegen door het buitengebied richting Biezenmortel zijn smal, waardoor de rit per adres langer kan duren. Daarom hoort Udenhout bij de middelgrote band: meestal binnen 45 tot 60 minuten. Udenhout heeft geen station meer; de bus naar Tilburg rijdt wel, maar wij komen uiteraard met de auto tot aan je voordeur.',
   'Een borrel in een nieuwbouwwoning in Den Bogerd of een feest op een boerderij richting Biezenmortel: kies de tank die bij de groep past. Op <a href="/lachgas-tanks/4kg/">de pagina over de 4KG-tank</a> lees je waarom die maat voor een gemiddeld gezelschap het meest praktisch is; voor kleine of grote groepen zijn er de 2KG en 10KG. De koerier overhandigt de tank verzegeld en je betaalt direct, contant of via Tikkie. Ben je of is de ontvanger jonger dan 18, dan leveren we niet, ook niet met toestemming van ouders. Lees ook <a href="/informatie/lachgas-in-het-verkeer/">waarom je na lachgas niet mag rijden</a>.',
  ],
  'wijken': 'Centrum, Slimstraat, Kreitenmolenstraat, Den Bogerd, Achthoeven, Biezenmortel, Zandkant, Groenstraat',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Horen Biezenmortel en het buitengebied ook bij Udenhout?', 'Ja, Biezenmortel hoort sinds 2021 bij de gemeente Tilburg en bezorgen we samen met Udenhout. In het buitengebied is het handig om een duidelijk herkenningspunt te noemen, zodat de koerier niet hoeft te zoeken tussen de boerderijen.'],
   ['Waarom is de levertijd in Udenhout anders dan in Tilburg zelf?', 'Udenhout ligt buiten de ringbanen en de koerier rijdt via de N65 of door Berkel-Enschot, wat meer tijd kost dan een rit binnen de stad. Daarom geven we meestal 45 tot 60 minuten aan in plaats van de stedelijke indicatie; het tijdvak dat we bevestigen is leidend.'],
   ['Kan ik in Udenhout ook laat in de avond bestellen?', 'Ja, we bezorgen ook ’s avonds laat en ’s nachts. In een dorp als Udenhout zijn we extra discreet: de koerier parkeert netjes, belt één keer aan en wacht rustig. Hoe we dat doen lees je op <a href="/service/nachtbezorging/">de pagina over nachtbezorging</a>.'],
  ],
  'nearby': ['berkel-enschot', 'oisterwijk', 'tilburg'],
  'lat': 51.6100, 'lon': 5.1433},

 {'slug': 'berkel-enschot', 'name': 'Berkel-Enschot', 'kind': 'dorp', 'region': 'midden-brabant', 'gemeente': 'Tilburg',
  'title': 'Lachgas bestellen Berkel-Enschot | 24/7 via WhatsApp',
  'description': 'Lachgas bestellen in Berkel-Enschot? Verzegelde lachgastanks bezorgd in Berkel, Enschot en Koningsoord, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Berkel-Enschot',
  'lead': 'Berkel-Enschot ligt direct tegen Tilburg-Oost aan. Een WhatsApp-bericht met je adres is genoeg; de koerier brengt een verzegelde tank.',
  'intro': [
   'Berkel-Enschot is een tweelingdorp aan de oostkant van Tilburg, ontstaan uit de kernen Berkel en Enschot en sinds 1997 onderdeel van de gemeente Tilburg. Het nieuwe centrum Koningsoord, gebouwd rond de voormalige abdij, verbindt de twee delen; daaromheen liggen buurten als de Rauwbraken, winkelcentrum Eikenbosch en de nieuwbouw aan de Enschotsebaan, en richting de A65 het buurtschap Heukelom. We bezorgen in het hele dorp. Een bestelling plaats je via WhatsApp door je adres en de gewenste tankmaat te sturen; wij reageren met de prijs en het tijdvak waarin je ons kunt verwachten.',
   'Vanuit Tilburg is Berkel-Enschot via de Burgemeester Bechtweg of de Bosscheweg in een paar minuten te bereiken, en vanaf de A65 ligt het dorp direct naast de afslag. Daardoor hoort het bij dezelfde snelle band als de stad: meestal binnen 30 tot 45 minuten. Het dorp heeft geen eigen treinstation, maar dat speelt geen rol omdat de koerier toch met de auto tot aan je voordeur komt, of dat nu in het oude Berkel is of in de nieuwbouw aan de Enschotsebaan. Vermeld in je bericht wel of je in Berkel, Enschot of Koningsoord woont, want de straatnamen lopen daar voor buitenstaanders door elkaar.',
   'Een huisfeest in de Rauwbraken, een verjaardag in een appartement in Koningsoord of een tuinfeest in Heukelom: de maat van de tank kies je op basis van je gezelschap. Vergelijk de 2KG, 4KG en 10KG op <a href="/lachgas-tanks/">onze tankpagina</a> en vraag via WhatsApp gerust om advies. De tank wordt verzegeld afgeleverd en je betaalt pas bij ontvangst, contant of met een Tikkie. Zonder geldig legitimatiebewijs van een 18-plusser laten we geen tank achter, ook niet bij een vaste klant. Lees ook <a href="/informatie/tank-versus-patronen/">waarom wij alleen tanks bezorgen en geen patronen</a>.',
  ],
  'wijken': 'Berkel, Enschot, Koningsoord, Rauwbraken, Eikenbosch, Enschotsebaan, De Hoge Hoek, Heukelom',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Geldt voor Berkel-Enschot dezelfde levertijd als voor Tilburg?', 'Ja, het dorp ligt zo dicht tegen Tilburg-Oost aan dat we dezelfde indicatie gebruiken: meestal binnen 30 tot 45 minuten. Heukelom en de randen van het buitengebied kunnen een paar minuten extra kosten, maar vallen binnen hetzelfde tijdvak.'],
   ['Bezorgen jullie ook in Koningsoord en de nieuwbouw aan de Enschotsebaan?', 'Zeker, ook in de nieuwe woonbuurten. Omdat straten daar soms nog niet in alle navigatiesystemen staan, vragen we je bij een nieuwbouwadres het huisnummer en eventueel een herkenbaar punt in de buurt te noemen.'],
   ['Kan ik een tank laten bezorgen op mijn werk in Berkel-Enschot?', 'Dat kan, mits je de tank persoonlijk aanneemt, je legitimatie kunt tonen en de locatie dat toestaat. We laten een tank nooit achter bij een receptie of collega; zie <a href="/veelgestelde-vragen/bezorgen/">onze vragen over bezorgen</a> voor de voorwaarden.'],
  ],
  'nearby': ['tilburg', 'udenhout', 'oisterwijk'],
  'lat': 51.5800, 'lon': 5.1400},

 {'slug': 's-hertogenbosch', 'name': "'s-Hertogenbosch", 'kind': 'stad', 'region': 'noordoost-brabant', 'gemeente': "'s-Hertogenbosch",
  'title': 'Lachgas bestellen ’s-Hertogenbosch | 24/7 via WhatsApp',
  'description': 'Lachgas bestellen in ’s-Hertogenbosch? Verzegelde lachgastanks bezorgd in Binnenstad, Maaspoort en Rosmalen, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in ’s-Hertogenbosch',
  'lead': 'Van de Binnenstad tot Maaspoort en De Groote Wielen: stuur een WhatsApp-bericht en we bezorgen een verzegelde lachgastank op je adres in ’s-Hertogenbosch.',
  'intro': [
   '’s-Hertogenbosch is de provinciehoofdstad en het knooppunt van Noordoost-Brabant, gebouwd rond de Sint-Jan, de Markt en de Binnendieze. Wij bezorgen in alle stadsdelen: de Binnenstad en het Paleiskwartier achter het station, de Muntel en de Vliert, Graafsepoort en Zuid, de wijken Noord en Maaspoort boven de A59, West met Boschveld en de Kruiskamp, en de dorpen Engelen, Empel, Nuland en Vinkel. Voor <a href="/lachgas-bezorgen/rosmalen/">Rosmalen en De Groote Wielen</a> hebben we een aparte pagina. Bestellen gaat via WhatsApp: je stuurt je adres, de gewenste tankmaat en een tijdvak, wij bevestigen de prijs en de verwachte aankomst van de koerier.',
   'De stad ligt op het kruispunt van de A2 en de A59, met de knooppunten Empel en Hintham aan de oostkant; vanuit Tilburg komt de N65 via Vught de stad in. Onze koerier kiest per adres de Randweg, de Vughterweg of de Orthenseweg naar Noord; Engelen ligt ten noordwesten van de stad langs de Dieze. Omdat de stad compact is en veel ritten in deze hoek van Brabant hier samenkomen, hanteren we de snelste band: meestal binnen 30 tot 45 minuten. Woon je in de drukke binnenstad rond de Parade of de Uilenburg, geef dan een straat op waar de koerier kort kan stoppen; het station is geen afleverpunt.',
   'Een studentenhuis in de Muntel, een verjaardag in een appartement in het Paleiskwartier of een tuinfeest in Empel: de grootte van het gezelschap bepaalt de maat. Op <a href="/lachgas-tanks/">de overzichtspagina van onze lachgastanks</a> staan de 2KG, 4KG en 10KG naast elkaar, zodat je gericht kunt kiezen; twijfel je, dan denken we via WhatsApp mee. De koerier levert de tank verzegeld af, je controleert de zegel en betaalt daarna contant of via Tikkie. Leveren doen we uitsluitend aan 18-plussers, en de koerier vraagt daarvoor om een geldig legitimatiebewijs. Lees voor je bestelt ook <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">wat je doet als iemand onwel wordt</a>.',
  ],
  'wijken': 'Binnenstad, Paleiskwartier, Muntel-Vliert, Graafsepoort, Zuid, Noord, Maaspoort, West, Engelen, Empel',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Bezorgen jullie ook in Engelen, Empel, Nuland en Vinkel?', 'Ja, alle kernen van de gemeente ’s-Hertogenbosch horen bij ons gebied. Nuland en Vinkel liggen oostelijk richting Oss en kunnen een paar minuten extra rijtijd kosten; het tijdvak dat we vooraf bevestigen houdt daar rekening mee.'],
   ['Kan ik een tank laten bezorgen in de binnenstad van ’s-Hertogenbosch?', 'Ja, maar veel straten rond de Markt en de Parade zijn beperkt toegankelijk voor auto’s. Noem daarom een adres of een hoek waar de koerier even kan stoppen en jij de tank persoonlijk kunt aannemen; op straat of op een terras leveren we niet.'],
   ['Hoe snel zijn jullie op een vrijdagavond in Den Bosch?', 'Onze indicatie blijft meestal binnen 30 tot 45 minuten, maar vrijdag- en zaterdagavond is het rond de binnenstad en op de uitvalswegen druk. Bestel bij voorkeur eerder op de dag; op <a href="/service/spoedbezorging/">de pagina over spoedbezorging</a> lees je wat wel en niet kan als het snel moet.'],
  ],
  'nearby': ['rosmalen', 'vught', 'vlijmen'],
  'lat': 51.6978, 'lon': 5.3037},

 {'slug': 'rosmalen', 'name': 'Rosmalen', 'kind': 'dorp', 'region': 'noordoost-brabant', 'gemeente': "'s-Hertogenbosch",
  'title': 'Lachgas bestellen Rosmalen | 24/7 bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Rosmalen? Verzegelde lachgastanks bezorgd in Rosmalen, De Groote Wielen, Maliskamp en Hintham, meestal binnen 30 tot 45 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Rosmalen',
  'lead': 'Rosmalen ligt direct achter de A2 tegen ’s-Hertogenbosch aan. Eén WhatsApp-bericht met je adres en de koerier brengt een verzegelde lachgastank.',
  'intro': [
   'Rosmalen was tot 1996 een zelfstandige gemeente en is sindsdien het grootste dorp binnen ’s-Hertogenbosch, met de Dorpsstraat en winkelcentrum De Driesprong als middelpunt. Daaromheen liggen de buurten Molenhoek, Sparrenburg, ’t Ven en Hondsberg, in het zuiden Maliskamp tegen de bossen, aan de kant van de stad Hintham, en ten noorden van de A59 de nieuwe wijk De Groote Wielen met Kruisstraat als oude kern. Wij bezorgen in al die buurten. Bestellen doe je via WhatsApp met je adres, de tankmaat en het tijdvak dat je wilt; wij bevestigen de prijs en de verwachte aankomsttijd voordat de koerier vertrekt.',
   'Vanuit de stad is Rosmalen via de Graafsebaan of de A59, afrit Rosmalen, in een paar minuten te bereiken, en komt de koerier van de A2, dan zit hij bij knooppunt Hintham al bijna in het dorp. Daarom rekenen we hier met dezelfde snelle indicatie als in ’s-Hertogenbosch: meestal binnen 30 tot 45 minuten. Station Rosmalen ligt aan de spoorlijn naar Oss en Nijmegen, al speelt dat voor een levering geen rol: de koerier rijdt door tot je voordeur, ook in de nieuwbouwstraten van De Groote Wielen. Woon je daar, noem dan naast het huisnummer ook de buurtnaam, omdat navigatiesystemen in nieuwe buurten nog wel eens achterlopen.',
   'Een avond met vrienden in een rijtjeshuis in Molenhoek, een familiefeest in Maliskamp of een housewarming in De Groote Wielen: kies de tank die bij het aantal gasten past. Vergelijk de 2KG, 4KG en 10KG op <a href="/lachgas-tanks/">onze assortimentspagina</a>; de prijs die we via WhatsApp bevestigen is wat je bij de deur betaalt, contant of met Tikkie. Elke tank komt verzegeld aan en we leveren alleen aan 18-plussers, dus houd een legitimatiebewijs bij de hand. Lees ook ons artikel over <a href="/informatie/lachgas-en-alcohol/">lachgas in combinatie met alcohol</a>, zodat je weet waarom die combinatie riskant is.',
  ],
  'wijken': 'Centrum, De Driesprong, Molenhoek, Sparrenburg, ’t Ven, Hondsberg, Maliskamp, Hintham, De Groote Wielen, Kruisstraat',
  'levertijd': 'meestal binnen 30 tot 45 minuten',
  'faq': [
   ['Hoort De Groote Wielen bij Rosmalen of bij ’s-Hertogenbosch?', 'Officieel is De Groote Wielen een wijk van Rosmalen, al ligt zij aan de andere kant van de A59. Voor de bezorging maakt het niets uit: dezelfde koerier en dezelfde indicatie van meestal 30 tot 45 minuten gelden voor het hele dorp.'],
   ['Bezorgen jullie ook in Hintham en Maliskamp?', 'Ja. Hintham ligt tussen de A2 en de stad en Maliskamp aan de zuidkant tegen de bossen; beide nemen we mee in dezelfde route als het centrum van Rosmalen. Vermeld de buurt in je bericht, dan kiest de koerier direct de juiste afslag.'],
   ['Kan ik in Rosmalen ook op zondag bestellen?', 'Ja, we bezorgen zeven dagen per week, ook op zondag. Zondagavond is doorgaans rustiger dan de vrijdag en zaterdag, waardoor het tijdvak vaak krapper uitvalt. Bekijk <a href="/service/weekendbezorging/">onze pagina over weekendbezorging</a> voor de praktische kant.'],
  ],
  'nearby': ['s-hertogenbosch', 'oss', 'heesch'],
  'lat': 51.7167, 'lon': 5.3650},

 {'slug': 'oss', 'name': 'Oss', 'kind': 'stad', 'region': 'noordoost-brabant', 'gemeente': 'Oss',
  'title': 'Lachgas bestellen Oss | Verzegeld bezorgd via WhatsApp',
  'description': 'Lachgas bestellen in Oss? Verzegelde lachgastanks 2KG, 4KG en 10KG bezorgd in Ruwaard, Ussen en Schadewijk, meestal binnen 45 tot 60 minuten. 18+.',
  'h1': 'Lachgas bezorgen in Oss',
  'lead': 'Oss ligt aan de A50 en de A59 in het noordoosten van Brabant. Bestel je lachgastank via WhatsApp; we bevestigen vooraf de prijs en een tijdvak.',
  'intro': [
   'Oss is de grootste stad van het Maasland, tussen ’s-Hertogenbosch en Nijmegen, met een centrum rond de Heuvel, de Eikenboomgaard en het Walplein. Daaromheen liggen de Ruwaard en het uitgestrekte Ussen aan de westkant, de Horzak in het noorden, de Schadewijk, Krinkelhoek en Mettegeupel aan de oostkant richting Berghem, en Oss-Zuid tussen het centrum en de A59. Ook in Berghem, Geffen, Lith, Megen en Ravenstein komen we aan de deur. Bestellen gaat via WhatsApp: stuur je adres, de maat die je wilt en een tijdvak, en wij antwoorden met de prijs en de verwachte aankomsttijd.',
   'Vanuit ’s-Hertogenbosch rijdt de koerier via de A59 langs Rosmalen en Nuland naar Oss, een rit van ongeveer twintig minuten; komt hij uit de richting Uden of Eindhoven, dan via de A50 tot knooppunt Paalgraven en vandaar de stad in. Oss ligt daarmee een flink stuk van de steden vandaan waar onze ritten beginnen, en de dorpen aan de Maas zoals Lith en Megen liggen nog weer verder. Daarom geldt hier de middelgrote band: meestal binnen 45 tot 60 minuten. De stad heeft twee stations, Oss en Oss West, aan de lijn ’s-Hertogenbosch–Nijmegen, maar de koerier komt altijd met de auto naar het adres dat je hebt opgegeven.',
   'Een borrel in een appartement bij de Eikenboomgaard, een verjaardag in een hoekwoning in Ussen of een feest op een boerderij bij Lith: de maat van de tank hangt af van het gezelschap. Op <a href="/lachgas-tanks/">ons assortiment lachgastanks</a> zie je het verschil tussen 2KG, 4KG en 10KG en kies je de maat die past. De koerier overhandigt de tank met intacte verzegeling en pas daarna betaal je, contant of via Tikkie, het bedrag dat vooraf in WhatsApp is bevestigd. Leeftijdscontrole hoort er altijd bij: zonder geldig ID van een 18-plusser nemen we de tank weer mee. In onze <a href="/veelgestelde-vragen/veiligheid/">vragen over veiligheid</a> lees je hoe je verantwoord met een tank omgaat.',
  ],
  'wijken': 'Centrum, Ruwaard, Ussen, Horzak, Schadewijk, Krinkelhoek, Mettegeupel, Oss-Zuid, Berghem, Geffen',
  'levertijd': 'meestal binnen 45 tot 60 minuten',
  'faq': [
   ['Bezorgen jullie ook in Berghem, Geffen en de Maasdorpen?', 'Ja, de hele gemeente Oss hoort bij ons gebied, inclusief Berghem, Geffen, Lith, Megen en Ravenstein. Voor de dorpen aan de Maas rekent de koerier extra rijtijd vanaf de stad, dus daar kan het tijdvak ruimer uitvallen dan de indicatie voor Oss zelf.'],
   ['Waarom duurt bezorgen in Oss langer dan in ’s-Hertogenbosch?', 'Oss ligt ruim twintig kilometer oostelijker en onze ritten in dit deel van Brabant starten meestal vanuit de omgeving van ’s-Hertogenbosch. De reistijd over de A59 is daarom al een deel van het tijdvak; vandaar meestal 45 tot 60 minuten in plaats van de stedelijke band. Op <a href="/service/bezorgtijden-per-regio/">de uitleg over bezorgtijden per regio</a> staat hoe we dat indelen.'],
   ['Kan ik lachgas laten bezorgen in een appartement in het centrum van Oss?', 'Ja, zolang je zelf de deur opent, de tank aanneemt en je legitimatie laat zien. Bij appartementencomplexen rond de Raadhuislaan of het station vragen we je even naar beneden te komen; we laten een tank nooit in een portiek of bij een buur achter.'],
  ],
  'nearby': ['rosmalen', 'heesch', 'uden'],
  'lat': 51.7650, 'lon': 5.5183},
]
