# -*- coding: utf-8 -*-
"""Gebiedspagina's lachgasbrabant.nl, Zuidoost-Brabant deel B: Waalre, Deurne, Gemert, Someren, Asten,
Bladel, Eersel, Bergeijk, Budel, Heeze, Oirschot, Beek en Donk, Reusel.

Toegestane HTML in tekstvelden: strong en a (interne paden uit de site-brief of de toegestane externe bronnen).
"""

AREAS = [
    {
        "slug": "waalre", "name": "Waalre", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Waalre",
        "title": "Lachgas bezorgen Waalre en Aalst | Lachgas Brabant",
        "description": "Lachgas bestellen in Waalre? Lachgastanks aan huis in Aalst, Waalre-dorp en Ekenrooi, meestal binnen 30 tot 45 minuten. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas bezorgen in Waalre",
        "lead": "Lachgastanks bezorgd in Waalre en Aalst, direct onder Eindhoven. Je regelt alles via WhatsApp en wij staan er meestal binnen 30 tot 45 minuten.",
        "intro": [
            """Waalre ligt direct onder Eindhoven en bestaat uit twee kernen: Aalst, dat langs de Eindhovenseweg bijna naadloos overgaat in de stad, en het dorp Waalre iets westelijker aan de Dommel. We bezorgen lachgastanks in beide kernen: rond de Markt en de oude Willibrorduskerk in Waalre-dorp, in Ekenrooi en Voldijn, bij winkelcentrum Den Hof in Aalst en in de nieuwere straten van Hoogh Waalre. Bestellen doe je door via WhatsApp je adres, de gewenste maat en een voorkeurstijd door te geven; wij reageren met een tijdvak en een bevestigde prijs.""",
            """Omdat de Randweg Eindhoven met de knooppunten De Hogt en Leenderheide pal langs de noordkant van de gemeente loopt, zijn we vanuit Eindhoven en Veldhoven in een paar minuten bij de afslag Waalre. De in 2021 geopende Westparallel van de N69 houdt het doorgaande verkeer naar Valkenswaard inmiddels uit Aalst, wat de ritten door het dorp rustiger maakt. Een treinstation heeft Waalre niet; de bussen tussen Eindhoven en Valkenswaard rijden door Aalst. Door die korte afstand hoort Waalre bij onze snelste band en zijn we er meestal binnen 30 tot 45 minuten.""",
            """Of je nu een borrel in een vrijstaand huis in Waalre-dorp houdt of met een groep in een appartement bij Den Hof zit: kies in ons <a href="/lachgas-tanks/">assortiment lachgastanks</a> de maat die bij de avond past, van 2KG tot 10KG. De prijs leggen we vooraf vast in WhatsApp en je betaalt pas bij de deur, contant of via Tikkie. Jonger dan 18? Dan gaat de bestelling niet door, en een geldig legitimatiebewijs kan aan de deur gevraagd worden. Neem voor de levering ook even onze uitleg over <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp</a> door, zodat je weet waar je op moet letten.""",
        ],
        "wijken": "Aalst, Waalre-dorp, Ekenrooi, Voldijn, Hoogh Waalre, Den Hof, Markt, Eindhovenseweg",
        "levertijd": "meestal binnen 30 tot 45 minuten",
        "faq": [
            ["Bezorgen jullie zowel in Aalst als in Waalre-dorp?", "Ja, beide kernen van de gemeente Waalre horen bij ons gebied en kennen dezelfde indicatieve levertijd. Noem in je bericht wel even de straat, want Aalst en Waalre-dorp liggen een paar kilometer uit elkaar en dat helpt bij het plannen."],
            ["Hoe snel zijn jullie in Waalre vanuit Eindhoven?", "De gemeente grenst aan de Randweg Eindhoven, dus de rit vanaf onze kant van de stad is kort. We houden rekening met meestal 30 tot 45 minuten en bevestigen vooraf een tijdvak via WhatsApp."],
            ["Kan ik ook laat op de avond bestellen in Waalre?", """Dat kan: we zijn dag en nacht via WhatsApp bereikbaar en bezorgen ook 's nachts in Aalst en Waalre-dorp. Hoe een nachtlevering verloopt lees je bij <a href="/service/nachtbezorging/">nachtbezorging</a>."""],
        ],
        "nearby": ["eindhoven", "veldhoven", "valkenswaard"],
        "lat": 51.389, "lon": 5.452,
    },
    {
        "slug": "deurne", "name": "Deurne", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Deurne",
        "title": "Lachgas bezorgen in Deurne | Lachgas Brabant",
        "description": "Lachgas bestellen in Deurne? Lachgastanks bezorgd in het centrum, Koolhof, Heiakker, Liessel en Vlierden, meestal binnen 45 tot 60 minuten. Alleen 18+.",
        "h1": "Lachgas bezorgen in Deurne",
        "lead": "Lachgastanks bezorgd in Deurne en de Peeldorpen, geregeld via WhatsApp. Meestal binnen 45 tot 60 minuten aan de deur.",
        "intro": [
            """Deurne is een van de grotere plaatsen van de Peel, een eind voorbij Helmond en op een steenworp van de Limburgse grens. De gemeente is uitgestrekt: naast het centrum rond de Markt, de Stationsstraat en het Groot Kasteel bezorgen we in de woonwijken Koolhof, Heiakker, Houtenhoek en Sint Jozefparochie, in Zeilberg en Walsberg en in de dorpen Liessel, Vlierden, Neerkant en Helenaveen midden in het veen. Een bestelling plaats je via WhatsApp met je adres, de maat van de tank en het moment waarop je ons verwacht; je krijgt dan een tijdvak terug.""",
            """Vanuit Helmond rijden we over de N270 recht op Deurne aan, een rit van ruim een kwartier. Komen we vanaf Eindhoven, dan is de A67 richting Venlo tot de afslag Liessel vaak sneller, waarna we door Liessel noordwaarts het dorp binnenkomen. Station Deurne ligt aan de spoorlijn Eindhoven–Venlo en de stationsbuurt is dus goed te vinden. De afstand tot Eindhoven is ruim dertig kilometer en de Peeldorpen liggen nog verder uit elkaar, daarom rekenen we voor Deurne meestal op 45 tot 60 minuten.""",
            """Voor een feestje in een rijtjeshuis in Heiakker of een avond op een boerenerf bij Helenaveen kies je uit <a href="/lachgas-tanks/">onze lachgastanks</a>; de 2KG is handig voor een klein gezelschap, de 4KG en 10KG voor een grotere groep of een langere avond. Je weet vooraf precies wat je betaalt, want we bevestigen het bedrag in WhatsApp, en je rekent af bij levering met contant geld of een Tikkie. Levering gebeurt alleen aan 18+. Hoe je een tank rechtop en koel bewaart staat in ons artikel over <a href="/informatie/lachgastank-bewaren-en-vervoeren/">bewaren en vervoeren</a>.""",
        ],
        "wijken": "Centrum, Koolhof, Heiakker, Houtenhoek, Sint Jozefparochie, Zeilberg, Walsberg, Liessel, Vlierden, Neerkant, Helenaveen",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Komen jullie ook in Liessel, Neerkant en Helenaveen?", "Ja, alle kernen van de gemeente Deurne vallen binnen ons bezorggebied. Voor de buitendorpen in de Peel kan de rit wat langer duren dan voor het centrum; het tijdvak dat we vooraf bevestigen houdt daar rekening mee."],
            ["Waarom is de levertijd in Deurne langer dan in Helmond?", "Deurne ligt ruim dertig kilometer van Eindhoven en een stuk voorbij Helmond, en de gemeente strekt zich uit tot aan de Limburgse grens. Daardoor zit Deurne in de middelste band: meestal binnen 45 tot 60 minuten."],
            ["Hoe weet ik dat de lachgastank nieuw en verzegeld is?", """Elke tank die we in Deurne afleveren is verzegeld en ongeopend; je controleert de verzegeling samen met onze bezorger bij de deur. Meer over het verschil met losse patronen lees je bij <a href="/informatie/tank-versus-patronen/">tank versus patronen</a>."""],
        ],
        "nearby": ["helmond", "asten", "gemert"],
        "lat": 51.464, "lon": 5.795,
    },
    {
        "slug": "gemert", "name": "Gemert", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Gemert-Bakel",
        "title": "Lachgas bezorgen Gemert | Lachgas Brabant",
        "description": "Lachgas bestellen in Gemert? Lachgastanks aan huis rond het Ridderplein, in Molenbroek, Doonheide, Bakel en Handel, meestal binnen 45 tot 60 minuten. 18+.",
        "h1": "Lachgas bezorgen in Gemert",
        "lead": "Lachgastanks bezorgd in Gemert en de kernen van Gemert-Bakel. Bestel via WhatsApp; we zijn er meestal binnen 45 tot 60 minuten.",
        "intro": [
            """Gemert is het kasteeldorp van de Peelrand, ten noordoosten van Helmond, met het Kasteel van de Duitse Orde en het Ridderplein als onmiskenbaar middelpunt. We bezorgen lachgastanks in het centrum en in de woonwijken Molenbroek, Berglaren, Paashoef en Molenakker, in de nieuwbouw van Doonheide aan de noordkant en in de andere kernen van de gemeente Gemert-Bakel: Bakel, De Mortel, Handel, Elsendorp, Milheeze en De Rips. Je stuurt ons via WhatsApp je adres, de gewenste maat en een tijdstip, en wij laten weten in welk tijdvak we voor de deur staan.""",
            """Een spoorlijn kent Gemert niet, dus alles gaat over de weg. Vanuit Helmond rijden we via Bakel het dorp binnen, en vanuit de richting Eindhoven of Nuenen nemen we de N615 over Beek en Donk, die bij Gemert aansluit op de N272 naar Boxmeer en de N605 richting Boekel. De streekbussen tussen Helmond, Uden en Eindhoven stoppen in het centrum. Omdat Gemert zo'n 25 kilometer van Eindhoven ligt en de dorpen van de gemeente ver de Peel in reiken, hanteren we hier de middelste band: meestal binnen 45 tot 60 minuten.""",
            """Een verjaardag in Paashoef, een avond met vrienden in een boerderij bij Handel of een feest in een zaal aan de rand van Bakel: in <a href="/lachgas-tanks/">ons assortiment</a> vind je lachgastanks van 2KG, 4KG en 10KG en we denken graag mee over wat voor jouw groep logisch is. Het bedrag spreken we af voordat onze bezorger vertrekt, en pas bij de overdracht betaal je, contant of met een Tikkie. We bezorgen uitsluitend aan volwassenen van 18 jaar en ouder en controleren daar zo nodig op; lees waarom bij <a href="/service/leeftijdscontrole-18-plus/">leeftijdscontrole</a>.""",
        ],
        "wijken": "Centrum, Ridderplein, Molenbroek, Berglaren, Paashoef, Molenakker, Doonheide, Bakel, De Mortel, Handel, Elsendorp, Milheeze, De Rips",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Bakel, Handel en De Rips?", "Ja, de hele gemeente Gemert-Bakel hoort bij ons gebied, van Elsendorp tot Milheeze. Voor de kleinere kernen verder de Peel in kan het tijdvak iets ruimer uitvallen dan voor het centrum van Gemert; dat zeggen we er vooraf eerlijk bij."],
            ["Hoe rijden jullie naar Gemert en hoe lang duurt dat?", "Meestal via Helmond en Bakel, of over de N615 via Beek en Donk, afhankelijk van waar onze bezorger op dat moment is. Reken op meestal 45 tot 60 minuten; het precieze tijdvak krijg je vooraf in WhatsApp."],
            ["Wat doe ik met een lege lachgastank in Gemert?", """Zet de lege tank niet bij het restafval. Bij een volgende bestelling nemen we hem graag mee terug, en anders kun je terecht bij de milieustraat van je gemeente; lees meer bij <a href="/informatie/lege-lachgastank-inleveren-brabant/">lege tank inleveren</a>."""],
        ],
        "nearby": ["helmond", "beek-en-donk", "deurne"],
        "lat": 51.555, "lon": 5.690,
    },
    {
        "slug": "someren", "name": "Someren", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Someren",
        "title": "Lachgas bezorgen in Someren | Lachgas Brabant",
        "description": "Lachgas bestellen in Someren? Lachgastanks bezorgd rond het Wilhelminaplein, in Waterdael, Someren-Eind en Lierop, meestal binnen 45 tot 60 minuten. 18+.",
        "h1": "Lachgas bezorgen in Someren",
        "lead": "Lachgastanks aan huis in Someren, Someren-Eind, Someren-Heide en Lierop. Via WhatsApp geregeld, meestal binnen 45 tot 60 minuten bezorgd.",
        "intro": [
            """Someren ligt aan de zuidkant van de Peel, tussen de Zuid-Willemsvaart en de Strabrechtse Heide, met Asten aan de overkant van het kanaal als naaste buur. Ons bezorggebied omvat het centrum rond het Wilhelminaplein, de nieuwbouwbuurten Waterdael en Groote Hoeven en de kerkdorpen Someren-Eind, Someren-Heide en Lierop aan de rand van de heide. Een bestelling begint met een WhatsApp-bericht met je adres, het gewenste formaat en wanneer je ons verwacht; wij antwoorden met een tijdvak en bevestigen de afspraak, inclusief de prijs.""",
            """De A67 richting Venlo heeft een eigen afslag Someren, waardoor we vanuit Eindhoven en Geldrop zonder omwegen het dorp in rijden; vanuit Helmond komen we via Asten of over de N266, de provinciale weg die Someren met Nederweert verbindt. Een station is er niet, de dichtstbijzijnde zijn Heeze en Helmond, en de streekbus verbindt Someren met Eindhoven en Helmond. De afstand tot het centrum van Eindhoven is ongeveer 25 kilometer, met daar bovenop de spreiding van de kerkdorpen, en daarom staat Someren in de band van meestal 45 tot 60 minuten.""",
            """Zit je met een paar mensen in een rijwoning in Waterdael of vier je iets groters op een erf bij Someren-Heide, dan bepaalt vooral de groepsgrootte welke <a href="/lachgas-tanks/">lachgastank</a> logisch is: 2KG, 4KG of 10KG. Vooraf weet je het bedrag, omdat we dat in WhatsApp vastleggen, en je betaalt bij de levering contant of via Tikkie. Een tank gaat alleen mee naar binnen bij iemand van 18 jaar of ouder; een ID-check hoort daar soms bij. Wie weinig ervaring heeft, leest het beste eerst ons artikel over <a href="/informatie/lachgas-en-alcohol/">lachgas en alcohol</a>.""",
        ],
        "wijken": "Centrum, Wilhelminaplein, Waterdael, Groote Hoeven, Someren-Eind, Someren-Heide, Lierop",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Komen jullie ook naar Lierop en Someren-Heide?", "Ja, ook de kerkdorpen rijden we aan; de gemeente Someren bedienen we van kanaal tot heide. Lierop ligt dicht bij de A67 en is snel bereikbaar; voor Someren-Heide en Someren-Eind rekenen we iets meer rijtijd, wat je terugziet in het tijdvak dat we bevestigen."],
            ["Kan ik voor een feest in Someren vooraf reserveren?", """Zeker, dat heeft onze voorkeur bij grotere feesten of op vrijdag- en zaterdagavond. Stuur ons een paar dagen vooraf een bericht met datum en tijd; hoe dat werkt staat bij <a href="/service/weekendbezorging/">weekendbezorging</a>."""],
            ["Hoe betaal ik bij een levering in Someren?", "Bij de deur, nooit vooraf: contant of via een Tikkie die onze bezorger ter plekke stuurt. Het bedrag is al in WhatsApp bevestigd, dus er komen bij de levering geen verrassingen bij."],
        ],
        "nearby": ["asten", "helmond", "heeze"],
        "lat": 51.385, "lon": 5.711,
    },
    {
        "slug": "asten", "name": "Asten", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Asten",
        "title": "Lachgas bezorgen Asten | Lachgas Brabant",
        "description": "Lachgas bestellen in Asten? Lachgastanks bezorgd in het centrum, Loverbosch, Heusden en Ommel, meestal binnen 45 tot 60 minuten. Via WhatsApp, alleen 18+.",
        "h1": "Lachgas bezorgen in Asten",
        "lead": "Lachgastanks bezorgd in Asten, Heusden en Ommel aan de rand van de Groote Peel. Bestellen via WhatsApp, meestal binnen 45 tot 60 minuten.",
        "intro": [
            """Asten is het Peeldorp waar de A67 en de N279 elkaar ontmoeten, bekend van zijn klokkenmuseum en van de Groote Peel die achter Heusden en Ommel begint. We brengen lachgastanks naar het centrum rond het Koningsplein en de Markt, naar Bluijssens Broek en de nieuwbouw van Loverbosch aan de oostkant, en naar de kerkdorpen Heusden en Ommel. Je bestelt met een WhatsApp-bericht waarin je adres, de gewenste maat en een voorkeurstijd staan; wij bevestigen dan een tijdvak en de prijs, zodat je niets hoeft te gokken.""",
            """Vanuit Eindhoven en Geldrop volgen we de A67 richting Venlo tot de afslag Asten, een rit van zo'n 25 kilometer; vanuit Helmond is de N279 langs de Zuid-Willemsvaart de kortste weg en komen we via Ommel binnen. Treinen stoppen hier niet, het dichtstbijzijnde station is Deurne, en de streekbus verbindt Asten met Helmond en Someren. Door die afstand tot de stad en de ligging van Heusden en Ommel richting het natuurgebied geldt voor Asten de middelste band: meestal binnen 45 tot 60 minuten.""",
            """Voor een huisfeest in Loverbosch, een verjaardag aan het Koningsplein of een avond bij vrienden in Heusden kies je in ons <a href="/lachgas-tanks/">overzicht van lachgastanks</a> tussen 2KG, 4KG en 10KG; twijfel je, dan geven we in WhatsApp een nuchter advies. Het bedrag uit de WhatsApp-bevestiging reken je bij de overdracht af, contant of met een Tikkie; vooraf storten doe je nooit. Levering is uitsluitend voor 18+, met legitimatiecontrole als daar aanleiding voor is. Ga je daarna nog de weg op, lees dan eerst <a href="/informatie/lachgas-in-het-verkeer/">lachgas in het verkeer</a>.""",
        ],
        "wijken": "Centrum, Koningsplein, Markt, Bluijssens Broek, Loverbosch, Heusden, Ommel",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Heusden en Ommel bij Asten?", "Ja, beide kerkdorpen van de gemeente Asten horen bij ons gebied, net als de buitenwegen richting de Groote Peel. Geef je adres compleet door, want een plaats met de naam Heusden bestaat ook elders in Brabant en we willen niet verkeerd rijden."],
            ["Hoe lang duurt bezorgen in Asten vanaf Eindhoven?", "Via de A67 is het ongeveer 25 kilometer tot de afslag Asten, en vanaf daar ben je zo in het dorp. Daardoor zijn we er meestal binnen 45 tot 60 minuten; bij drukte in het weekend geven we een realistischer tijdvak."],
            ["Komen jullie ook 's nachts naar Asten?", """Ja, we zijn 24/7 bereikbaar via WhatsApp en rijden ook laat in de nacht de Peel in. Onze bezorger belt rustig aan en houdt rekening met de buren; meer daarover bij <a href="/service/nachtbezorging/">nachtbezorging</a>."""],
        ],
        "nearby": ["someren", "helmond", "deurne"],
        "lat": 51.404, "lon": 5.750,
    },
    {
        "slug": "bladel", "name": "Bladel", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Bladel",
        "title": "Lachgas bezorgen in Bladel | Lachgas Brabant",
        "description": "Lachgas bestellen in Bladel? Lachgastanks bezorgd in de Kempen: Bladel, Hapert, Hoogeloon, Casteren en Netersel, meestal binnen 60 tot 90 minuten. 18+.",
        "h1": "Lachgas bezorgen in Bladel",
        "lead": "Lachgastanks bezorgd in Bladel en de Kempendorpen langs de N284. Bestellen via WhatsApp, meestal binnen 60 tot 90 minuten aan huis.",
        "intro": [
            """Bladel is het winkelhart van de Kempen, halverwege de N284 tussen Hapert en Reusel, met de Markt en de Sniederslaan als drukste plekken. We bezorgen lachgastanks in het centrum, in de nieuwere wijk Egyptische Poort en in de overige kernen van de gemeente: Hapert aan de A67, Hoogeloon, Casteren en het kleine Netersel. Stuur ons via WhatsApp je adres, de maat die je wilt en het tijdstip waarop het je uitkomt; je ontvangt dan een bevestiging met een tijdvak en de afgesproken prijs.""",
            """Vanuit Eindhoven en Veldhoven volgen we de A67 richting Antwerpen tot de afslag Hapert, waar het Kempisch Bedrijvenpark ligt, en rijden we via de N284 het dorp in. Bladel heeft geen treinstation; de bussen richting Eindhoven stoppen in het centrum. Het is bijna 30 kilometer rijden vanaf het centrum van Eindhoven en de dorpen Casteren en Netersel liggen nog een stuk noordelijker tussen de akkers, daarom rekenen we voor de gemeente Bladel op de ruimste band: meestal binnen 60 tot 90 minuten.""",
            """Een avond met vrienden in een tussenwoning in Egyptische Poort of een feest op een boerderij bij Hoogeloon vraagt om een ander formaat; bekijk de <a href="/lachgas-tanks/">lachgastanks van 2KG, 4KG en 10KG</a> en kies wat past. We bevestigen het bedrag vooraf in WhatsApp en je rekent pas af als de tank voor je staat, contant of via Tikkie. Zonder bewijs dat je 18 of ouder bent, gaat de tank niet mee naar binnen. Omdat het in de Kempen 's winters stevig kan vriezen, is ons artikel over <a href="/informatie/lachgas-bij-kou-en-warmte/">lachgas bij kou en warmte</a> hier extra nuttig.""",
        ],
        "wijken": "Centrum, Markt, Sniederslaan, Egyptische Poort, Hapert, Hoogeloon, Casteren, Netersel",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Waarom duurt bezorgen in Bladel langer dan in Veldhoven?", "Bladel ligt bijna 30 kilometer van Eindhoven en de kernen van de gemeente liggen verspreid tussen de A67 en de Kempische bossen. Daarom hoort Bladel bij onze ruimste band, meestal binnen 60 tot 90 minuten, en bevestigen we altijd eerst een tijdvak."],
            ["Komen jullie ook in Hapert, Hoogeloon en Netersel?", "Ja, we bezorgen in alle vijf de kernen van de gemeente Bladel. Hapert ligt direct aan de A67 en is vaak het snelst; voor Netersel en Casteren rekenen we wat extra rijtijd mee."],
            ["Kan ik in Bladel met spoed bestellen?", """Spoed is in de Kempen lastiger dan in de stad, maar laat het ons weten; als er een bezorger in de buurt is, zeggen we dat direct. Wat spoed van jou en van ons vraagt, lees je bij <a href="/service/spoedbezorging/">spoedbezorging</a>."""],
        ],
        "nearby": ["eersel", "reusel", "veldhoven"],
        "lat": 51.370, "lon": 5.218,
    },
    {
        "slug": "eersel", "name": "Eersel", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Eersel",
        "title": "Lachgas bezorgen Eersel | Lachgas Brabant",
        "description": "Lachgas bestellen in Eersel? Lachgastanks bezorgd rond de Markt en de Hint, in Kerkebogten, Duizel en Vessem, meestal binnen 45 tot 60 minuten. 18+.",
        "h1": "Lachgas bezorgen in Eersel",
        "lead": "Lachgastanks bezorgd in Eersel en de zes Kempendorpen van de gemeente. Via WhatsApp besteld, meestal binnen 45 tot 60 minuten gebracht.",
        "intro": [
            """Eersel is het eerste Kempendorp voorbij Veldhoven, met de Markt vol lindebomen en terrassen en de Hint als lang, groen hart. We bezorgen lachgastanks in het centrum, in de nieuwbouw van Kerkebogten en in de andere kernen van de gemeente: Duizel en Steensel vlak langs de A67, Knegsel, Vessem en Wintelre richting het noorden. Bestellen gaat via WhatsApp: je geeft je adres, de gewenste maat en een tijdstip door, en wij komen terug met een tijdvak en een vaste prijs waar je op kunt rekenen.""",
            """De A67 heeft een eigen afslag Eersel, waardoor we vanuit Eindhoven in een rechte lijn langs Veldhoven naar het dorp rijden; het is ongeveer 17 kilometer vanaf het stadscentrum. Vanuit Eersel vertakt de N397 naar Bergeijk en Valkenswaard, en de bussen naar Eindhoven en Reusel halteren in het centrum. Een trein is er niet, Eindhoven Centraal is het dichtstbijzijnde station. Eersel zelf ligt gunstig, maar Vessem en Wintelre liggen een stuk verder van de snelweg, en daarom geldt voor de gemeente meestal 45 tot 60 minuten.""",
            """Voor een borrel na een terrasavond aan de Markt, een feest in Kerkebogten of een avond bij de recreatieplas E3-strand kies je een <a href="/lachgas-tanks/">lachgastank</a> die past bij het aantal mensen: 2KG, 4KG of 10KG. Het bedrag staat van tevoren vast in WhatsApp en je betaalt bij levering, contant of via een Tikkie. De leeftijdsgrens van 18 jaar geldt zonder uitzondering; twijfelt onze bezorger, dan vraagt die naar je ID. Een tank die rechtop staat en niet in de zon ligt, blijft in orde; de praktische tips staan bij <a href="/informatie/lachgastank-bewaren-en-vervoeren/">tank bewaren en vervoeren</a>.""",
        ],
        "wijken": "Centrum, Markt, de Hint, Kerkebogten, Duizel, Steensel, Knegsel, Vessem, Wintelre",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Vessem, Wintelre en Knegsel?", "Ja, de zes dorpen van de gemeente Eersel bedienen we allemaal, het kleine Knegsel inbegrepen. Duizel en Steensel liggen bij de A67 en zijn snel bereikbaar; voor Vessem en Wintelre houden we iets meer rijtijd aan binnen het tijdvak dat we bevestigen."],
            ["Hoe snel kunnen jullie in Eersel zijn?", "Via de afslag Eersel op de A67 is het dorp vanuit Eindhoven goed te bereiken, dus meestal binnen 45 tot 60 minuten. Op vrijdag- en zaterdagavond is het drukker en kan het tijdvak wat ruimer zijn; dat zeggen we vooraf."],
            ["Welke lachgastank past bij een klein gezelschap in Eersel?", """Voor een kleine groep thuis is de 2KG meestal voldoende; voor een groter feest kies je de 4KG of 10KG. Vergelijk ze rustig op <a href="/lachgas-tanks/2kg/">de pagina over de 2KG-tank</a> en de andere maten."""],
        ],
        "nearby": ["veldhoven", "bladel", "bergeijk"],
        "lat": 51.357, "lon": 5.318,
    },
    {
        "slug": "bergeijk", "name": "Bergeijk", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Bergeijk",
        "title": "Lachgas bezorgen in Bergeijk | Lachgas Brabant",
        "description": "Lachgas bestellen in Bergeijk? Lachgastanks bezorgd in 't Hof en 't Loo, Luyksgestel, Westerhoven en Riethoven, meestal binnen 60 tot 90 minuten. 18+.",
        "h1": "Lachgas bezorgen in Bergeijk",
        "lead": "Lachgastanks bezorgd in Bergeijk en de kernen tot aan de Belgische grens. Bestellen via WhatsApp, meestal binnen 60 tot 90 minuten.",
        "intro": [
            """Bergeijk ligt in de zuidelijke Kempen, tussen Eersel en de Belgische grens bij Lommel, en is een dorp met twee oude kernen: 't Hof met de Hofkerk en 't Loo. Daar omheen bezorgen we lachgastanks in Westerhoven, waar ook het vakantiepark De Kempervennen ligt, in Riethoven, in Luyksgestel vlak bij de grens en in het kleine Weebosch. Via WhatsApp geef je je adres, het gewenste formaat en een moment door, waarna wij een tijdvak voorstellen en de prijs bevestigen, zodat alles vooraf duidelijk is.""",
            """Er lopen twee logische routes naar Bergeijk: vanuit Eindhoven over de A67 tot Eersel en dan de N397 zuidwaarts, of via Valkenswaard en diezelfde N397 vanuit het oosten. Openbaar vervoer beperkt zich tot de bus naar Eindhoven en Valkenswaard; een spoorlijn is er in deze hoek van de Kempen niet. De afstand tot het centrum van Eindhoven is ruim 20 kilometer en vooral Luyksgestel en Weebosch liggen diep in het buitengebied, dus voor Bergeijk hanteren we meestal 60 tot 90 minuten.""",
            """Een bijeenkomst in een huis bij weverij De Ploeg, een feest in een vakantiehuisje op De Kempervennen of een avond in Luyksgestel: kies in <a href="/lachgas-tanks/">ons tankoverzicht</a> het formaat dat bij je groep past, van 2KG tot 10KG. Over de prijs bestaat vooraf geen onduidelijkheid, die staat in WhatsApp, en afrekenen doe je bij de deur met contant geld of een Tikkie. Levering is uitsluitend aan personen van 18 jaar en ouder, ook op vakantieparken. Wat de wet in Nederland zegt over bezit en verkoop lees je in <a href="/informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a>.""",
        ],
        "wijken": "'t Hof, 't Loo, Centrum, Westerhoven, Riethoven, Luyksgestel, Weebosch, De Kempervennen",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie op De Kempervennen in Westerhoven?", "Ja, het vakantiepark ligt binnen de gemeente Bergeijk en dus in ons gebied. Geef naast je huisjesnummer ook de ingang door, en houd er rekening mee dat parkregels over bezoek en geluid gewoon blijven gelden."],
            ["Rijden jullie ook over de grens naar Lommel of Pelt?", "Nee, we bezorgen alleen op Nederlands grondgebied. Luyksgestel en Weebosch vlak bij de grens vallen er wel onder, de Belgische kant niet, ook niet voor een adres dat maar een paar honderd meter verder ligt."],
            ["Waarom is de levertijd voor Bergeijk ruimer dan voor Eersel?", "Bergeijk ligt een stuk verder van de A67 en de kernen van de gemeente liggen verspreid tot aan de grens. Daardoor valt Bergeijk in onze ruimste band, meestal binnen 60 tot 90 minuten; het exacte tijdvak bevestigen we vooraf via WhatsApp."],
        ],
        "nearby": ["eersel", "valkenswaard", "bladel"],
        "lat": 51.319, "lon": 5.360,
    },
    {
        "slug": "budel", "name": "Budel", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Cranendonck",
        "title": "Lachgas bezorgen Budel | Lachgas Brabant",
        "description": "Lachgas bestellen in Budel? Lachgastanks bezorgd in Budel, Budel-Schoot, Budel-Dorplein, Maarheeze en Soerendonk, meestal binnen 60 tot 90 minuten. 18+.",
        "h1": "Lachgas bezorgen in Budel",
        "lead": "Lachgastanks bezorgd in Budel en de rest van Cranendonck, tot vlak aan de Belgische grens. Via WhatsApp besteld, meestal binnen 60 tot 90 minuten.",
        "intro": [
            """Budel is de hoofdkern van de gemeente Cranendonck, in de uiterste zuidoosthoek van Brabant waar Limburg en België elkaar bijna raken. Het dorp heeft een compact centrum rond het Capucijnerplein en de Markt, en daar omheen bezorgen we ook in Budel-Schoot, in Budel-Dorplein bij de zinkfabriek, in Maarheeze aan het spoor en in Soerendonk en Gastel. Een bestelling plaats je via WhatsApp met je adres, de maat van de tank en wanneer je ons wilt zien; wij reageren met een tijdvak en een bevestigde prijs.""",
            """Vanuit Eindhoven nemen we de A2 richting Weert en verlaten we de snelweg bij Maarheeze, waarna het via Soerendonk nog een paar kilometer naar Budel is. Wie met de trein komt, stapt uit in Maarheeze aan de lijn Eindhoven–Weert; Budel zelf heeft geen station en is per bus verbonden met Weert en Eindhoven. Met ongeveer 35 kilometer is dit een van de verste bestemmingen in ons Zuidoost-Brabantse gebied, en daarom rekenen we voor Cranendonck op meestal 60 tot 90 minuten.""",
            """Voor een avond in een woning aan het Capucijnerplein, een feest in Budel-Schoot of een verjaardag in Maarheeze kies je uit <a href="/lachgas-tanks/">lachgastanks van 2KG, 4KG en 10KG</a>; we helpen je in WhatsApp met een realistische inschatting. Vooruitbetalen hoeft nooit; wat we in WhatsApp hebben afgesproken, betaal je aan de deur, contant of via een Tikkie. Levering uitsluitend aan 18+, met controle van je legitimatie als dat nodig is. Wat je doet als iemand onwel wordt, staat beschreven bij <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp</a>; neem dat vooraf even door.""",
        ],
        "wijken": "Centrum, Capucijnerplein, Markt, Budel-Schoot, Budel-Dorplein, Maarheeze, Soerendonk, Gastel",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook in Hamont-Achel, net over de grens?", "Nee, ons bezorggebied stopt bij de landsgrens. Budel, Budel-Schoot en Budel-Dorplein horen er wel bij, maar voor een adres in Hamont, Achel of Weert kunnen we helaas niets betekenen."],
            ["Hoe lang moet ik in Budel op een bestelling wachten?", "Budel is een van onze verste adressen in Zuidoost-Brabant, zo'n 35 kilometer van Eindhoven via de A2. Reken daarom op meestal 60 tot 90 minuten; we noemen vooraf een tijdvak zodat je weet waar je aan toe bent."],
            ["Kan ik in Maarheeze bij het station laten bezorgen?", "We bezorgen alleen op een woon- of verblijfadres, niet op straat of bij een station. Geef een adres in Maarheeze door waar je zelf aanwezig bent, dan komen we daar naartoe."],
        ],
        "nearby": ["valkenswaard", "heeze", "someren"],
        "lat": 51.272, "lon": 5.573,
    },
    {
        "slug": "heeze", "name": "Heeze", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Heeze-Leende",
        "title": "Lachgas bezorgen in Heeze | Lachgas Brabant",
        "description": "Lachgas bestellen in Heeze? Lachgastanks bezorgd rond de Kapelstraat, in De Bulders, Leende en Sterksel, meestal binnen 45 tot 60 minuten. Alleen 18+.",
        "h1": "Lachgas bezorgen in Heeze",
        "lead": "Lachgastanks bezorgd in Heeze, Leende en Sterksel, aan de rand van de Strabrechtse Heide. Bestellen via WhatsApp, meestal binnen 45 tot 60 minuten.",
        "intro": [
            """Heeze is het kasteeldorp ten zuidoosten van Eindhoven, met Kasteel Heeze aan de rand van het dorp en de Kapelstraat en Jan Deckersstraat als winkelstraten, bekend van de jaarlijkse optocht van de Brabantsedag. We bezorgen lachgastanks in het centrum, in de buurt rond het station, in het bosrijke Heezerenbosch, in de nieuwbouw van De Bulders en in de andere kernen van Heeze-Leende: Leende, Sterksel en Leenderstrijp. Je bestelt via WhatsApp door adres, maat en tijdstip te sturen; wij bevestigen een tijdvak en de prijs.""",
            """Heeze heeft als een van de weinige dorpen in deze hoek een eigen station aan de lijn Eindhoven–Weert, dus de stationsbuurt is voor ons vertrouwd terrein. Met de auto komen we vanuit Eindhoven via Geldrop over de Heezerweg, of via de A2 en de afslag Leende als we uit het zuiden komen; de randweg langs De Bulders houdt het doorgaande verkeer uit het centrum. De afstand is zo'n 15 kilometer, maar Sterksel en Leenderstrijp liggen verspreid tussen bos en heide, en daarom geldt hier meestal 45 tot 60 minuten.""",
            """Een feestavond in een vrijstaand huis in Heezerenbosch, een borrel in De Bulders of een weekend in Leende: in ons <a href="/lachgas-tanks/">assortiment</a> staan tanks van 2KG, 4KG en 10KG, verzegeld geleverd. Wat je betaalt is vooraf in WhatsApp bevestigd en je rekent bij de deur af, contant of via Tikkie. Ben je jonger dan 18, dan leveren we niet; houd dus een ID bij de hand. Lees ook waarom lachgas en alcohol geen goede combinatie zijn in <a href="/informatie/lachgas-en-alcohol/">dit artikel</a>.""",
        ],
        "wijken": "Centrum, Kapelstraat, Jan Deckersstraat, Stationsbuurt, Heezerenbosch, De Bulders, Leende, Sterksel, Leenderstrijp",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Leende en Sterksel?", "Ja, de hele gemeente Heeze-Leende hoort bij ons gebied, inclusief Leenderstrijp. Leende ligt dicht bij de A2 en is vlot bereikbaar; voor Sterksel rekenen we wat meer rijtijd en dat verwerken we in het tijdvak."],
            ["Kunnen jullie tijdens de Brabantsedag in Heeze bezorgen?", """Op de dag van de optocht zijn delen van het centrum afgesloten, dus bezorgen we dan buiten de afzettingen of op een later moment. Reserveer vooraf; lees meer bij <a href="/service/feestdagen-en-evenementen/">feestdagen en evenementen</a>."""],
            ["Hoe snel zijn jullie in Heeze?", "Via Geldrop of de A2 is Heeze zo'n 15 kilometer van Eindhoven, en we zijn er meestal binnen 45 tot 60 minuten. Het tijdvak dat we in WhatsApp noemen is leidend, zeker in het weekend."],
        ],
        "nearby": ["geldrop", "mierlo", "valkenswaard"],
        "lat": 51.383, "lon": 5.571,
    },
    {
        "slug": "oirschot", "name": "Oirschot", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Oirschot",
        "title": "Lachgas bezorgen Oirschot | Lachgas Brabant",
        "description": "Lachgas bestellen in Oirschot? Lachgastanks bezorgd rond de Markt, in Moorland, Spoordonk en de Beerzen, meestal binnen 45 tot 60 minuten. Alleen 18+.",
        "h1": "Lachgas bezorgen in Oirschot",
        "lead": "Lachgastanks bezorgd in Oirschot, Spoordonk en de Beerzen, direct aan de A58. Bestellen via WhatsApp, meestal binnen 45 tot 60 minuten.",
        "intro": [
            """Oirschot ligt aan de A58 tussen Eindhoven en Tilburg en heeft een van de mooiste marktpleinen van Brabant, met de Sint-Petrusbasiliek, het Boterkerkje en de Rijkesluisstraat als winkelstraat. We bezorgen lachgastanks in het centrum, in de nieuwbouwwijk Moorland, langs het Wilhelminakanaal en in de andere kernen van de gemeente: Spoordonk, Oostelbeers, Middelbeers en Westelbeers. Een appje met straat, huisnummer, de maat die je wilt en het uur waarop het je past is genoeg; wij antwoorden met een tijdvak en noemen daarbij de prijs.""",
            """Vanuit Eindhoven rijden we via Best over de A58 en nemen we de afslag Oirschot, een route van ruim 15 kilometer; vanuit Tilburg is het dezelfde snelweg in omgekeerde richting. De grote kazerne aan de oostkant van het dorp kennen we van de route, maar daar bezorgen we niet. Oirschot heeft geen treinstation, het dichtstbijzijnde is Best, en de bussen naar Eindhoven en Tilburg stoppen bij de Markt. Omdat de Beerzen een flink stuk ten zuiden van de snelweg liggen, hanteren we voor de gemeente meestal 45 tot 60 minuten.""",
            """Voor een avond in een herenhuis aan de Markt, een feest in Moorland of een verjaardag in Middelbeers vind je in ons <a href="/lachgas-tanks/">assortiment lachgastanks</a> het juiste formaat: 2KG, 4KG of 10KG. Je kent het bedrag al uit WhatsApp voordat we vertrekken, en afrekenen gebeurt bij levering met contant geld of een Tikkie. Leeftijd telt: zonder aantoonbare 18 jaar blijft de tank in de bus. Een lege tank hoort niet bij het huisvuil; lees wat je ermee doet bij <a href="/informatie/lege-lachgastank-inleveren-brabant/">lege tank inleveren</a>.""",
        ],
        "wijken": "Centrum, Markt, Rijkesluisstraat, Moorland, De Stad, Spoordonk, Oostelbeers, Middelbeers, Westelbeers",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Komen jullie ook in Oostelbeers, Middelbeers en Westelbeers?", "Ja, de drie Beerzen vallen onder de gemeente Oirschot en rijden we net zo goed aan als het centrum. Ze liggen een stuk zuidelijker dan het centrum, dus het tijdvak kan iets later uitvallen; we zeggen dat er vooraf bij."],
            ["Bezorgen jullie op de kazerne in Oirschot?", "Nee, op militair terrein bezorgen we niet. Woon je in Oirschot of verblijf je er op een gewoon adres, dan kom je uiteraard wel in aanmerking, mits je 18 jaar of ouder bent en dat kunt aantonen."],
            ["Wat is de levertijd in Oirschot op een zaterdagavond?", """Ook dan houden we meestal 45 tot 60 minuten aan, maar zaterdag is onze drukste avond. Bestel liever vroeg of reserveer vooraf via WhatsApp; tips staan bij <a href="/service/weekendbezorging/">weekendbezorging</a>."""],
        ],
        "nearby": ["best", "eindhoven", "boxtel"],
        "lat": 51.505, "lon": 5.311,
    },
    {
        "slug": "beek-en-donk", "name": "Beek en Donk", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Laarbeek",
        "title": "Lachgas bezorgen Beek en Donk | Lachgas Brabant",
        "description": "Lachgas bestellen in Beek en Donk? Lachgastanks bezorgd in Beek, Donk, Aarle-Rixtel, Lieshout en Mariahout, meestal binnen 45 tot 60 minuten. Alleen 18+.",
        "h1": "Lachgas bezorgen in Beek en Donk",
        "lead": "Lachgastanks bezorgd in Beek en Donk en de andere Laarbeek-dorpen, net boven Helmond. Via WhatsApp besteld, meestal binnen 45 tot 60 minuten.",
        "intro": [
            """Beek en Donk is de grootste kern van de gemeente Laarbeek en ligt op de plek waar het Wilhelminakanaal uitkomt op de Zuid-Willemsvaart, pal ten noorden van Helmond. Het dorp bestaat uit het oude Beek rond het Heuvelplein en Donk rond het Piet van Thielplein, verbonden door de Beekse Brug. We bezorgen lachgastanks in beide helften, in de nieuwbouw van de Beekse Akkers, rond bedrijventerrein Bemmer en in Aarle-Rixtel, Lieshout en Mariahout. Een berichtje met adres, maat en tijdstip volstaat; het tijdvak dat we terugsturen is waar je op kunt rekenen.""",
            """De N279 langs de Zuid-Willemsvaart brengt ons vanuit Helmond in een paar minuten bij Beek en Donk, en vanuit Eindhoven en Nuenen is de N615 via Gerwen de kortste weg; die weg loopt door tot Gemert. Treinen rijden hier niet, de stations van Helmond zijn het dichtstbij, en de bus verbindt Laarbeek met Helmond en Eindhoven. De afstand tot Helmond is klein, maar vanaf Eindhoven is het ruim 15 kilometer en Mariahout ligt aan de verre kant van de gemeente, waardoor we meestal uitkomen op 45 tot 60 minuten.""",
            """Een feest aan het Heuvelplein, een avond met vrienden in de Beekse Akkers of een verjaardag in Lieshout: kies uit onze <a href="/lachgas-tanks/">lachgastanks</a> het formaat dat bij je groep past, 2KG, 4KG of 10KG, allemaal verzegeld geleverd. Wat het kost staat zwart op wit in WhatsApp voordat we rijden; afrekenen kan contant of met een Tikkie zodra de tank binnen staat. Minderjarigen leveren we niet aan; onze bezorger mag naar een ID vragen. Hoe bestellen stap voor stap gaat, lees je bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>.""",
        ],
        "wijken": "Beek, Donk, Heuvelplein, Piet van Thielplein, Beekse Akkers, Bemmer, Aarle-Rixtel, Lieshout, Mariahout",
        "levertijd": "meestal binnen 45 tot 60 minuten",
        "faq": [
            ["Bezorgen jullie ook in Aarle-Rixtel, Lieshout en Mariahout?", "Ja, alle kernen van Laarbeek horen bij ons gebied. Aarle-Rixtel ligt tegen Helmond aan en is snel bereikbaar; Lieshout en Mariahout liggen verder westelijk en krijgen soms een iets ruimer tijdvak."],
            ["Hoe snel kunnen jullie in Beek en Donk zijn?", "Vanuit Helmond is het over de N279 een korte rit, vanuit Eindhoven ruim 15 kilometer via de N615. In de praktijk komt dat neer op meestal 45 tot 60 minuten; het tijdvak dat we vooraf noemen is leidend."],
            ["Mag ik lachgas gebruiken op straat in Beek en Donk?", """Lachgas staat sinds 1 januari 2023 op lijst II van de Opiumwet en veel Brabantse gemeenten hebben in hun APV aanvullende regels over gebruik in de openbare ruimte. Raadpleeg de APV van Laarbeek en lees meer bij <a href="/informatie/lachgas-regels-per-gemeente-brabant/">regels per gemeente</a>."""],
        ],
        "nearby": ["helmond", "gemert", "nuenen"],
        "lat": 51.531, "lon": 5.627,
    },
    {
        "slug": "reusel", "name": "Reusel", "kind": "dorp", "region": "zuidoost-brabant", "gemeente": "Reusel-De Mierden",
        "title": "Lachgas bezorgen in Reusel | Lachgas Brabant",
        "description": "Lachgas bestellen in Reusel? Lachgastanks bezorgd in Reusel, Hooge Mierde, Lage Mierde en Hulsel in de Kempen, meestal binnen 60 tot 90 minuten. 18+.",
        "h1": "Lachgas bezorgen in Reusel",
        "lead": "Lachgastanks bezorgd in Reusel en De Mierden, het westelijkste puntje van de Brabantse Kempen. Bestellen via WhatsApp, meestal binnen 60 tot 90 minuten.",
        "intro": [
            """Reusel is het laatste dorp aan de N284 voordat je bij Arendonk België binnenrijdt, met de Markt en de Wilhelminalaan als centrum en het bos van Postel aan de overkant van de grens. De gemeente Reusel-De Mierden omvat ook Hooge Mierde, Lage Mierde en Hulsel, en we bezorgen in alle vier de kernen, van de nieuwbouw in Molen Akkers tot Lensheuvel en bedrijventerrein Kleine Hoeven. Via WhatsApp geef je adres, maat en gewenst tijdstip door en wij laten weten in welk tijdvak we komen en wat het kost.""",
            """De route vanuit Eindhoven loopt over de A67 tot Hapert en vervolgens over de N284 door Bladel naar Reusel, een rit van ongeveer 35 kilometer. Een alternatief vanuit Tilburg gaat over de N269 via Hilvarenbeek en Lage Mierde door het buitengebied. Een station is er niet; de bus naar Eindhoven rijdt via Bladel en Eersel. Omdat Reusel het verste puntje van de Kempen is en De Mierden nog weer noordelijker tussen de bossen liggen, hoort de gemeente bij onze ruimste band: meestal binnen 60 tot 90 minuten.""",
            """Voor een avond in Molen Akkers, een feestje op een boerderij bij Hulsel of een weekend in een vakantiehuis bij Lage Mierde kies je in ons <a href="/lachgas-tanks/">overzicht van lachgastanks</a> tussen 2KG, 4KG en 10KG. Het bedrag is vooraf bevestigd in WhatsApp en betalen doe je bij levering, contant of via Tikkie. Onder de 18 bezorgen we niet, en bij twijfel over je leeftijd willen we een legitimatie zien. Wordt lachgas voor jou of iemand in je buurt meer dan iets incidenteels, dan staat bij <a href="/informatie/problematisch-lachgasgebruik-hulp/">problematisch gebruik en hulp</a> waar je terechtkunt.""",
        ],
        "wijken": "Centrum, Markt, Wilhelminalaan, Molen Akkers, Lensheuvel, Kleine Hoeven, Hooge Mierde, Lage Mierde, Hulsel",
        "levertijd": "meestal binnen 60 tot 90 minuten",
        "faq": [
            ["Bezorgen jullie ook in Arendonk of Postel, net over de grens?", "Nee, we rijden niet over de landsgrens. Reusel en De Mierden aan de Nederlandse kant bedienen we wel; adressen in Arendonk, Postel of Mol vallen buiten ons gebied."],
            ["Hoeveel tijd moet ik rekenen voor een levering in Reusel?", "Reusel ligt zo'n 35 kilometer van Eindhoven, aan het einde van de N284, dus we komen meestal binnen 60 tot 90 minuten. Je krijgt vooraf een tijdvak via WhatsApp, zodat je niet hoeft te gokken."],
            ["Komen jullie ook in Hooge Mierde, Lage Mierde en Hulsel?", "Ja, alle kernen van de gemeente Reusel-De Mierden horen erbij. Ze liggen noordelijker dan Reusel zelf, richting Hilvarenbeek, en dat kan een paar minuten extra rijtijd betekenen die we in het tijdvak meenemen."],
        ],
        "nearby": ["bladel", "eersel", "hilvarenbeek"],
        "lat": 51.363, "lon": 5.165,
    },
]
