# -*- coding: utf-8 -*-
# Lachgas Brabant — FAQ-thema's, FAQ-hub, contactpagina en over ons. Alleen data.

FAQ_TOPICS = [
    {
        'slug': 'bestellen',
        'title': 'Vragen over bestellen | Lachgas Brabant',
        'description': 'Hoe je bij Lachgas Brabant bestelt via WhatsApp: welke gegevens we nodig hebben, hoe de bevestiging werkt en hoe je een bestelling wijzigt of annuleert.',
        'h1': 'Vragen over bestellen',
        'lead': 'Alles over het plaatsen van een bestelling via WhatsApp: van je eerste bericht tot de bevestiging van je tijdvak.',
        'intro': [
            'Bestellen gaat bij ons via één kanaal: WhatsApp. Dat houdt het overzichtelijk voor jou en voor de bezorger, omdat alles wat is afgesproken in dezelfde chat terug te lezen is. Hieronder beantwoorden we de vragen die we het vaakst krijgen over het plaatsen van een bestelling, van de gegevens die we nodig hebben tot het aanpassen van een tijdvak. Staat jouw vraag er niet bij, dan stel je hem natuurlijk gewoon in de chat.',
        ],
        'items': [
            ['Hoe plaats ik een bestelling?',
             'Je stuurt ons een WhatsApp-bericht met het gewenste formaat, je adres en het moment waarop je de tank wilt ontvangen. Wij reageren met de prijs en een tijdvak, en zodra jij akkoord geeft, staat de bestelling vast. Een uitgebreide uitleg vind je op de pagina <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a>.'],
            ['Welke gegevens hebben jullie van mij nodig?',
             'Een volledig adres met huisnummer en eventuele toevoeging, het formaat tank (2KG, 4KG of 10KG) en het gewenste tijdstip. Een naam waarnaar de bezorger kan vragen is handig, net als een korte aanwijzing als de ingang moeilijk te vinden is. Meer vragen we niet.'],
            ['Kan ik ook bestellen zonder WhatsApp?',
             'WhatsApp is het kanaal waarop we het snelst en het hele etmaal reageren, dus voor een bestelling die vandaag nog bezorgd moet worden is het de beste keuze. Voor vragen die niet dringend zijn kun je ons mailen; de gegevens staan op de <a href="/contact/">contactpagina</a>. Een bestelling per e-mail duurt doorgaans langer, omdat we die mailbox niet continu uitlezen.'],
            ['Krijg ik een bevestiging van mijn bestelling?',
             'Ja. Nadat je akkoord hebt gegeven op de prijs en het tijdvak, sturen we één bericht waarin alles kort staat samengevat: formaat, adres, tijdvak en betaalwijze. Controleer dat bericht even, want dat is wat de bezorger meekrijgt. Klopt er iets niet, dan pas je het direct aan in dezelfde chat.'],
            ['Kan ik mijn bestelling nog wijzigen of annuleren?',
             'Zolang de bezorger nog niet onderweg is, pas je formaat, adres of tijdvak gewoon aan in de chat. Is de koerier al vertrokken, laat het dan zo snel mogelijk weten, dan kijken we wat er nog mogelijk is. Annuleren kan altijd; we vragen alleen om het tijdig te melden, zodat we niet voor een dichte deur staan.'],
            ['Kan ik vooruit bestellen voor een later moment?',
             'Zeker, en voor een feest of een druk weekend raden we dat zelfs aan. Je geeft de datum en het gewenste tijdvak door en wij bevestigen of dat past in de planning. Een dag of twee van tevoren is in de regel voldoende; rond feestdagen graag iets eerder, zie ook <a href="/service/feestdagen-en-evenementen/">feestdagen en evenementen</a>.'],
            ['Kan ik meerdere tanks in één bestelling opnemen?',
             'Dat kan; geef in je bericht aan hoeveel tanks en welke formaten je wilt. We bevestigen vooraf of alles in één rit mee kan of dat we een tweede moment inplannen. We adviseren je graag over wat passend is, maar we zullen je nooit aansporen om meer te nemen dan je zelf voor ogen had.'],
            ['Kan ik bestellen voor iemand anders of op een ander adres?',
             'Ja, zolang de persoon die de tank aanneemt zelf 18 jaar of ouder is en dat aan de deur kan aantonen. Zet in je bericht de naam van de ontvanger en het afleveradres, en laat die persoon weten in welk tijdvak de bezorger komt. Zo voorkomen we dat de koerier voor een verraste huisgenoot staat.'],
            ['Kan ik een vaste bestelling of herhaalbestelling instellen?',
             'Nee, we werken niet met abonnementen of automatische herhaalbestellingen. Elke levering is een losse afspraak die je zelf start, zodat je steeds bewust kiest of en wat je bestelt. Eerdere bestellingen kunnen we wel terugzoeken in de chat als je dezelfde gegevens opnieuw wilt gebruiken.'],
            ['Wat doen jullie met mijn gegevens na de bestelling?',
             'We bewaren alleen wat nodig is om de levering uit te voeren en eventuele vragen achteraf te beantwoorden. Je chatgeschiedenis staat in WhatsApp en kun je zelf verwijderen; wij delen je naam en adres met niemand buiten de bezorger. De details staan in onze <a href="/privacy/">privacyverklaring</a>.'],
        ],
        'related': ['bezorgen', 'betalen'],
    },
    {
        'slug': 'bezorgen',
        'title': 'Vragen over bezorgen | Lachgas Brabant',
        'description': 'Vragen over de bezorging van lachgastanks in Noord-Brabant: werkgebied, indicatieve levertijden, wat je geleverd krijgt en wat er aan de deur gebeurt.',
        'h1': 'Vragen over bezorgen',
        'lead': 'Hoe de bezorging in Noord-Brabant werkt: werkgebied, tijdvakken, wat je geleverd krijgt en wat er aan de deur van je wordt verwacht.',
        'intro': [
            'Over de bezorging komen de meeste vragen binnen, en dat is logisch: je wilt weten of we bij jou komen, hoe lang het duurt en wat er aan de deur van je wordt verwacht. We bezorgen in heel Noord-Brabant, verdeeld over vier regio’s met elk een indicatieve levertijd. Op deze pagina leggen we uit hoe dat in de praktijk gaat, zonder beloftes die we niet kunnen nakomen.',
        ],
        'items': [
            ['Waar bezorgen jullie precies?',
             'In heel Noord-Brabant, van Bergen op Zoom tot Boxmeer en van Werkendam tot Budel. We hebben het gebied verdeeld in vier regio’s met elk een eigen overzicht van plaatsen en levertijden. Op de pagina <a href="/bezorggebied/">bezorggebied</a> zie je of jouw plaats erbij staat; staat die er niet, vraag het ons dan gewoon.'],
            ['Hoe lang duurt het voordat de tank er is?',
             'Dat hangt af van waar je woont en van de drukte op dat moment. In de grote steden en hun buurgemeenten is het meestal binnen 30 tot 45 minuten, in middelgrote kernen meestal binnen 45 tot 60 minuten en in kleinere of verder gelegen plaatsen meestal binnen 60 tot 90 minuten. Dit zijn indicaties; het tijdvak dat we in de chat bevestigen is wat telt, zie <a href="/service/bezorgtijden-per-regio/">bezorgtijden per regio</a>.'],
            ['Hoe wordt het tijdvak bepaald?',
             'Zodra je bestelling binnenkomt, kijken we waar de dichtstbijzijnde bezorger is en hoeveel adressen er al gepland staan. Op basis daarvan noemen we een tijdvak in plaats van een exact tijdstip, omdat verkeer en weer altijd meespelen. Loopt het toch anders, dan laten we het je in dezelfde chat weten.'],
            ['Wie moet er thuis zijn om de tank aan te nemen?',
             'Iemand van 18 jaar of ouder die zich kan legitimeren en de betaling kan afronden. De bezorger geeft de tank niet af aan een minderjarige en zet hem ook niet onbeheerd bij de deur of in een portiek. Is de ontvanger een ander dan de besteller, meld dat dan vooraf.'],
            ['Wat krijg ik precies geleverd?',
             'Een verzegelde lachgastank in het formaat dat je hebt besteld: 2KG, 4KG of 10KG netto-inhoud. De verzegeling is intact bij de overdracht, zodat je zeker weet dat niemand de tank eerder heeft geopend. Wij leveren geen patronen, crackers of andere accessoires.'],
            ['Bezorgen jullie ook op een feestlocatie, hotel of vakantiepark?',
             'Ja, zolang het een adres is waar een volwassene de tank persoonlijk aanneemt en de locatie dat toestaat. Geef bij een hotel of park het kamer- of huisnummer door en zorg dat je bereikbaar bent als de bezorger bij de receptie of slagboom staat. Op een openbare plek, zoals een park of parkeerterrein, leveren we niet.'],
            ['Wat gebeurt er als er niemand opendoet?',
             'De bezorger stuurt je eerst een bericht via WhatsApp en wacht een paar minuten. Krijgen we geen reactie, dan rijdt hij door naar het volgende adres en nemen we contact op om een nieuw moment af te spreken. Een tweede rit plannen we graag, maar we vragen je om dan echt bereikbaar te zijn.'],
            ['Hoe discreet is de bezorging?',
             'De bezorger komt in een gewone auto zonder opdruk en met de tank neutraal verpakt. Hij houdt het kort aan de deur en belt ’s nachts niet aan als je in de chat aangeeft dat je op je telefoon let. Over je bestelling praten we met niemand anders dan met jou.'],
            ['Kan ik zien hoe laat de bezorger er is?',
             'Live volgen is niet mogelijk, maar je krijgt een bericht als de bezorger vertrekt en meestal nog een als hij vlakbij is. Wil je tussendoor weten hoe het staat, vraag het dan in de chat; we antwoorden eerlijk, ook als het later wordt dan gehoopt.'],
            ['Bezorgen jullie ook buiten Noord-Brabant?',
             'Nee, ons werkgebied stopt bij de provinciegrens. Woon je net over de grens in Gelderland, Limburg, Zeeland of Zuid-Holland, dan kunnen we helaas niet bij je langskomen. Voor adressen in Noord-Brabant die niet op onze plaatsenlijst staan, kijken we per geval of het haalbaar is.'],
            ['Wat als het slecht weer is of druk op de weg?',
             'Dan kan een tijdvak ruimer uitvallen; dat melden we vooraf als we het zien aankomen. Bij sneeuw, storm of een afgesloten weg zoeken we een andere route, maar de veiligheid van de bezorger gaat voor snelheid. Je hoort het van ons voordat het tijdvak verstrijkt, niet erna.'],
        ],
        'related': ['bestellen', 'regels'],
    },
    {
        'slug': 'betalen',
        'title': 'Vragen over betalen | Lachgas Brabant',
        'description': 'Vragen over betalen bij Lachgas Brabant: contant of via Tikkie bij levering, een prijs die vooraf vaststaat en wat je doet als er iets niet klopt.',
        'h1': 'Vragen over betalen',
        'lead': 'Alles over afrekenen bij levering: contant of via Tikkie, de prijs die vooraf vaststaat en wat je doet als er iets niet klopt.',
        'intro': [
            'Afrekenen doe je bij ons pas op het moment dat de tank voor je staat, contant of via Tikkie. Vooraf weet je precies welk bedrag dat wordt, omdat we de prijs in de chat bevestigen voordat de bezorger vertrekt. Hieronder lees je hoe dat in de praktijk werkt, wat je doet als een betaalmethode niet lukt en hoe we omgaan met een levering waar iets aan schort.',
        ],
        'items': [
            ['Hoe kan ik betalen?',
             'Je betaalt bij levering, contant of via Tikkie. Beide opties zijn aan de deur beschikbaar; laat in de chat even weten welke je kiest, dan weet de bezorger of hij wisselgeld moet meenemen. Meer uitleg staat op de pagina <a href="/service/betalen-bij-levering/">betalen bij levering</a>.'],
            ['Moet ik vooruitbetalen of een aanbetaling doen?',
             'Nee. We vragen nooit om een overboeking of een betaalverzoek voordat de tank bij je staat. Ontvang je toch zo’n verzoek uit onze naam, dan komt dat niet van ons; betaal niet en meld het ons in de chat waarin je hebt besteld.'],
            ['Waar vind ik de prijs?',
             'De prijs noemen we vooraf in de chat, zodra je het formaat en je adres hebt doorgegeven. Wat daar staat, is wat je aan de deur betaalt; er komen geen kosten bij die niet vooraf zijn genoemd. Op de website zelf publiceren we geen prijzen, omdat die per situatie kunnen verschillen.'],
            ['Hoe werkt betalen via Tikkie aan de deur?',
             'De bezorger stuurt je in de chat een betaalverzoek voor het afgesproken bedrag en jij rondt het af met je eigen bankapp. Zodra de betaling zichtbaar is, krijg je de tank overhandigd. Zorg dat je telefoon opgeladen is en je bankapp werkt; op sommige plekken is het mobiele bereik matig.'],
            ['Wat als Tikkie niet lukt of ik geen bereik heb?',
             'Dan is contant betalen de uitwijkmogelijkheid, dus het is verstandig om voor de zekerheid het bedrag ook contant in huis te hebben. Werken beide niet, dan nemen we de tank weer mee en spreken we een nieuw moment af. Op rekening of achteraf betalen is niet mogelijk.'],
            ['Krijg ik een bon of factuur?',
             'Op verzoek sturen we na de levering een bevestiging van de betaling in de chat. Heb je een factuur nodig, geef dat dan vooraf aan; we laten eerlijk weten wat we kunnen aanleveren en welke gegevens we daarvoor nodig hebben. Zonder verzoek ontvang je geen papieren bon aan de deur.'],
            ['Kan iemand anders voor mij betalen?',
             'Ja, degene die de tank aanneemt kan afrekenen, contant of met een Tikkie op zijn eigen telefoon. Wil je als besteller zelf betalen terwijl iemand anders ontvangt, geef dat dan vooraf door; de bezorger stuurt het betaalverzoek dan naar jou. We geven de tank pas af als de betaling rond is.'],
            ['Wat doe ik als ik denk dat er iets niet klopt met de levering of het bedrag?',
             'Zeg het direct aan de deur, voordat de tank van eigenaar wisselt; dan kan de bezorger het ter plekke nakijken. Merk je iets pas later, stuur dan een bericht in dezelfde chat met wat er niet klopt. We zoeken samen een redelijke oplossing; de spelregels staan in onze <a href="/algemene-voorwaarden/">algemene voorwaarden</a>.'],
            ['Kunnen we met een groep de betaling delen?',
             'Aan de deur rekenen we met één persoon af; het onderling verdelen regelen jullie daarna zelf, bijvoorbeeld met een eigen betaalverzoek. Dat houdt de overdracht kort en voorkomt verwarring over wie wat heeft betaald.'],
            ['Is er korting als ik vaker of meer bestel?',
             'Nee, we werken niet met staffels, acties of beloningen voor grotere afnames. We vinden het belangrijk dat je bestelt wat je nodig hebt en niet meer, en prijsprikkels passen daar niet bij. De prijs die je in de chat krijgt, is de prijs.'],
        ],
        'related': ['bestellen', 'bezorgen'],
    },
    {
        'slug': 'veiligheid',
        'title': 'Vragen over veiligheid | Lachgas Brabant',
        'description': 'Eerlijke antwoorden over de risico’s van lachgas: gezondheid, bevriezing, alcohol, wat je doet als iemand onwel wordt en hoe je een tank bewaart.',
        'h1': 'Vragen over veiligheid',
        'lead': 'Eerlijke antwoorden over de risico’s van lachgas, bevriezing, alcohol, wat je doet als iemand onwel wordt en hoe je een tank bewaart.',
        'intro': [
            'Lachgas is niet zonder risico, en we vinden dat je dat ook van ons mag horen, niet alleen van de overheid. Op deze pagina beantwoorden we de vragen over gezondheid en veiligheid die ons het vaakst worden gesteld: wat de risico’s zijn, waarom kou en alcohol de zaak erger maken, wat je doet als iemand onwel wordt en hoe je een tank thuis bewaart. Het zijn geen gebruiksaanwijzingen, maar informatie waarmee je verstandiger kunt kiezen.',
        ],
        'items': [
            ['Welke gezondheidsrisico’s heeft lachgas?',
             'Op korte termijn kun je duizelig worden, hoofdpijn of misselijkheid krijgen of kort het bewustzijn verliezen, met valpartijen als gevolg. Bij regelmatig gebruik kan een tekort aan vitamine B12 ontstaan, wat tot tintelingen, krachtverlies en in ernstige gevallen blijvende zenuwschade leidt. Een uitgebreid overzicht staat in ons artikel over <a href="/informatie/lachgas-bijwerkingen-en-eerste-hulp/">bijwerkingen en eerste hulp</a>.'],
            ['Wat is het risico op bevriezing?',
             'Lachgas verlaat de tank extreem koud en het metaal van de kraan koelt daarbij sterk af. Huid die daarmee in aanraking komt, kan binnen seconden bevriezen; direct uit de tank inhaleren is om die reden ronduit gevaarlijk voor lippen, mond en luchtwegen. Een bevriezingswond behandel je als een brandwond: koelen met lauw water en bij blaren of witte plekken naar de huisartsenpost.'],
            ['Waarom is lachgas in combinatie met alcohol riskant?',
             'Beide verdoven, en samen versterken ze elkaar: je wordt sneller duizelig, valt eerder en merkt minder goed dat het misgaat. Alcohol vergroot ook de kans op braken terwijl je minder helder bent, en dat kan levensgevaarlijk zijn. Waarom we deze combinatie afraden, lees je in <a href="/informatie/lachgas-en-alcohol/">lachgas en alcohol</a>.'],
            ['Wat doe ik als iemand onwel wordt?',
             'Haal de persoon weg bij de tank, zorg voor frisse lucht en leg hem of haar op de zij als de reactie traag of afwezig is. Blijf erbij, praat rustig en laat niemand alleen in slaap vallen die kort daarvoor is weggevallen. Reageert iemand niet, ademt hij vreemd of houdt het niet op, bel dan 112; hulpdiensten komen om te helpen, niet om te oordelen.'],
            ['Wie kan beter helemaal geen lachgas gebruiken?',
             'Mensen die zwanger zijn, een hart- of longaandoening hebben, medicijnen gebruiken die op het zenuwstelsel werken of psychisch kwetsbaar zijn, lopen extra risico. Ook wie al eens tintelingen of gevoelloosheid heeft gehad na gebruik, moet stoppen en met de huisarts praten. Onafhankelijke informatie vind je bij <a href="https://www.drugsinfo.nl">drugsinfo.nl</a>.'],
            ['Hoe bewaar ik een tank thuis?',
             'Rechtop, op een koele en droge plek, uit de zon en weg van verwarming, kachels en open vuur. Zet de tank buiten bereik van kinderen en huisdieren en leg hem niet in een kleine afgesloten ruimte zonder ventilatie. Meer tips lees je in <a href="/informatie/lachgastank-bewaren-en-vervoeren/">lachgastank bewaren en vervoeren</a>.'],
            ['Mag de tank in de auto blijven staan?',
             'Liever niet, en in de zon al helemaal niet. Een auto warmt snel op en bij hogere temperaturen loopt de druk in de tank op; dat is precies wat je bij een drukvat wilt vermijden. Moet de tank toch mee, zet hem dan rechtop, vastgezet en uit het directe zonlicht, en haal hem bij aankomst meteen uit de auto.'],
            ['Kan een tank ontploffen of lekken?',
             'Een onbeschadigde tank bij normale temperaturen is stabiel. Risico ontstaat door hitte, een val van hoogte of door aan de kraan te sleutelen. Hoor je sissen of ruik je iets vreemds, zet de tank dan buiten in de open lucht, blijf er niet naast staan en stuur ons direct een bericht.'],
            ['Wat merk ik van een vitamine B12-tekort?',
             'Tintelingen of een doof gevoel in handen en voeten, onzeker lopen, vermoeidheid en concentratieproblemen zijn de bekendste signalen. Ze ontstaan sluipend en worden vaak laat herkend als gevolg van lachgas. Herken je dit, stop dan en ga naar de huisarts; vroeg behandelen voorkomt blijvende schade. Lees meer in <a href="/informatie/lachgas-en-vitamine-b12/">lachgas en vitamine B12</a>.'],
            ['Waar vind ik hulp als het gebruik uit de hand loopt?',
             'Je huisarts is een laagdrempelige eerste stap en kan doorverwijzen. In Brabant is Novadic-Kentron de instelling voor verslavingszorg waar je terechtkunt voor advies en behandeling. Twijfel je of het bij jou of iemand in je omgeving zo ver is, lees dan ons artikel over <a href="/informatie/problematisch-lachgasgebruik-hulp/">problematisch lachgasgebruik</a>.'],
            ['Is lachgas in een kleine ruimte gevaarlijk voor de omgeving?',
             'In een slecht geventileerde ruimte verdringt vrijkomend gas de zuurstof, en dat merk je niet aan geur of kleur. Houd een tank daarom uit kleine afgesloten ruimtes zoals een auto, tent of badkamer en zorg altijd voor frisse lucht. Een lekkende tank hoort buiten te staan, niet in de gang.'],
        ],
        'related': ['regels', 'bezorgen'],
    },
    {
        'slug': 'regels',
        'title': 'Vragen over de regels | Lachgas Brabant',
        'description': 'Wat de Opiumwet, gemeentelijke verordeningen en het verkeer betekenen voor lachgas, waarom wij strikt 18+ werken en hoe het zit bij de Belgische grens.',
        'h1': 'Vragen over de regels',
        'lead': 'Wat de Opiumwet, gemeentelijke verordeningen en het verkeersrecht betekenen voor lachgas, en waarom wij strikt 18+ werken.',
        'intro': [
            'De regels rond lachgas zijn de afgelopen jaren flink veranderd en verschillen bovendien per gemeente. Wij zijn geen juristen en geven geen juridisch advies, maar we leggen graag uit wat we zelf weten en waar je de officiële bronnen vindt. Hieronder gaan we in op de Opiumwet, gemeentelijke verordeningen, het verkeer en onze eigen leeftijdsgrens. Bij twijfel geldt altijd: raadpleeg de Rijksoverheid of je gemeente, niet een bezorgservice.',
        ],
        'items': [
            ['Wat staat er in de Opiumwet over lachgas?',
             'Lachgas valt sinds 1 januari 2023 onder lijst II van de Opiumwet. Daarmee zijn verkoop en bezit voor recreatief gebruik verboden; voor medische, technische en voedingstoepassingen gelden uitzonderingen. De officiële uitleg en de actuele stand van zaken vind je bij de <a href="https://www.rijksoverheid.nl">Rijksoverheid</a>.'],
            ['Wat betekent die wet voor mij als ik een tank in huis heb?',
             'Wij geven geen juridisch advies, en de wet maakt onderscheid naar het doel waarvoor je lachgas hebt. Bezit voor recreatief gebruik valt onder het verbod; de uitzonderingen gelden voor professionele toepassingen en voedingsgebruik. Lees ons artikel <a href="/informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a> en raadpleeg bij twijfel een jurist of de officiële bronnen.'],
            ['Wat is een APV en wat heeft die met lachgas te maken?',
             'De Algemene Plaatselijke Verordening is de lokale regelgeving van je gemeente. Veel Brabantse gemeenten hebben daarin bepalingen over lachgas opgenomen, bijvoorbeeld een verbod op gebruik op straat, in parken of rond evenementen. Welke regels precies gelden, verschilt per gemeente; kijk op de website van je eigen gemeente of lees <a href="/informatie/lachgas-regels-per-gemeente-brabant/">regels per gemeente</a>.'],
            ['Mag ik een tank meenemen naar een festival of evenement?',
             'Meestal niet. Organisatoren verbieden lachgas doorgaans in hun huisregels en gemeenten nemen het vaak op in de evenementenvergunning of de APV. Beveiliging kan je de tank afnemen of de toegang weigeren, dus controleer de huisregels vooraf.'],
            ['Mag ik rijden nadat ik lachgas heb gebruikt?',
             'Nee. Rijden onder invloed van een stof die je rijvaardigheid beïnvloedt is verboden, en lachgas valt daar nadrukkelijk onder. De effecten voelen kort, maar je reactievermogen en zicht zijn langer verstoord dan je zelf merkt, ook als passagiers vinden dat je er prima uitziet.'],
            ['Wat zijn de gevolgen als de politie je betrapt achter het stuur?',
             'De politie controleert op opvallend rijgedrag en op tanks in de auto en kan je aanhouden voor een onderzoek. Dat kan leiden tot een boete, invordering van je rijbewijs of strafvervolging, afhankelijk van de situatie. Regel dus vooraf hoe je thuiskomt; wat de politie precies doet, lees je in <a href="/informatie/lachgas-in-het-verkeer/">lachgas in het verkeer</a>.'],
            ['Waarom leveren jullie alleen aan 18+?',
             'Omdat de hersenen van jongeren nog in ontwikkeling zijn en lachgas voor hen extra risico’s heeft, en omdat we er simpelweg niet aan willen meewerken dat minderjarigen eraan komen. De leeftijdsgrens geldt voor iedereen die de tank aanneemt, niet alleen voor de besteller. Hoe de controle aan de deur gaat, staat op <a href="/service/leeftijdscontrole-18-plus/">leeftijdscontrole 18+</a>.'],
            ['Welk legitimatiebewijs is geldig aan de deur?',
             'Een geldig paspoort, een identiteitskaart, een rijbewijs of een verblijfsdocument waarop je geboortedatum staat. Een foto van je legitimatie op je telefoon of een studentenpas is niet voldoende. Zonder geldig document gaat de tank mee terug.'],
            ['Wat gebeurt er als blijkt dat de ontvanger jonger is dan 18?',
             'Dan wordt er niet geleverd en nemen we de tank terug, ongeacht wie er heeft besteld. Bestel je bewust voor een minderjarige, dan weigeren we ook toekomstige bestellingen van jou. We zien dit niet als een formaliteit, maar als een kernregel.'],
            ['Gelden in Baarle-Nassau dezelfde regels als in de rest van Brabant?',
             'Baarle-Nassau is Nederlands grondgebied en valt dus onder de Nederlandse Opiumwet en de APV van de gemeente. Het dorp is echter verweven met het Belgische Baarle-Hertog, waar Belgische wetgeving geldt en de regels rond lachgas anders zijn. Wij bezorgen uitsluitend op Nederlandse adressen; in de Belgische enclaves leveren we niet.'],
            ['Waar blijf ik op de hoogte van veranderingen in de regels?',
             'De Rijksoverheid publiceert wijzigingen in de Opiumwet en de bijbehorende besluiten; dat is de bron die wij zelf ook volgen. Voor lokale regels is de website van je gemeente leidend. Onafhankelijke, niet-commerciële uitleg over lachgas en wetgeving vind je ook bij het <a href="https://www.trimbos.nl">Trimbos-instituut</a>.'],
        ],
        'related': ['veiligheid', 'bestellen'],
    },
]

FAQ_INDEX = {
    'title': 'Veelgestelde vragen over lachgas | Lachgas Brabant',
    'description': 'Antwoorden op de meest gestelde vragen over bestellen, bezorgen, betalen, veiligheid en regels rond lachgas in Noord-Brabant, gebundeld per thema.',
    'h1': 'Veelgestelde vragen',
    'lead': 'Vijf thema’s, één plek. Vind snel het antwoord op je vraag of stel hem direct via WhatsApp.',
    'intro': [
        'Op deze pagina bundelen we de vragen die ons dagelijks via WhatsApp bereiken, verdeeld over vijf thema’s. Onder bestellen lees je hoe je een aanvraag plaatst en aanpast, onder bezorgen vind je alles over werkgebied, tijdvakken en de overdracht aan de deur, en onder betalen leggen we uit hoe contant of Tikkie bij levering werkt. Het thema veiligheid gaat over gezondheidsrisico’s, kou, alcohol en bewaren; het thema regels over de Opiumwet, gemeentelijke verordeningen, het verkeer en onze leeftijdsgrens. Onder elk thema staan acht tot twaalf vragen met een kort, eerlijk antwoord.',
    ],
    'top_h2': 'De vijf meest gestelde vragen',
    'top': [
        ['Hoe snel kunnen jullie ergens in Brabant zijn?',
         'Dat verschilt per plaats: in en rond de grote steden meestal binnen 30 tot 45 minuten, in middelgrote kernen meestal binnen 45 tot 60 minuten en in de kleinere of verder weg gelegen dorpen meestal binnen 60 tot 90 minuten. Het zijn indicaties; wat we in de chat bevestigen, is het tijdvak waar we naar werken. Een toelichting per regio staat op <a href="/service/bezorgtijden-per-regio/">bezorgtijden per regio</a>.'],
        ['Welke tank past bij mijn situatie?',
         'We bezorgen drie formaten: 2KG, 4KG en 10KG, elk verzegeld en met de netto-inhoud in kilo N2O als enige verschil. Een klein gezelschap komt doorgaans uit met de 2KG; de grotere formaten zijn bedoeld voor meer mensen of een langere gelegenheid. Op <a href="/lachgas-tanks/">de tankpagina</a> staan de formaten naast elkaar, en in de chat denken we eerlijk mee.'],
        ['Hoe werkt afrekenen aan de deur?',
         'Je betaalt pas als de tank bij je staat, contant of via een Tikkie die de bezorger ter plekke stuurt. Het bedrag is het bedrag dat we vooraf in de chat hebben genoemd; daar komt niets bij. Alle details, ook over wat je doet bij een probleem, vind je bij <a href="/veelgestelde-vragen/betalen/">vragen over betalen</a>.'],
        ['Kan ik ook midden in de nacht of op zondag bestellen?',
         'Ja, onze WhatsApp is dag en nacht bemand, ook in het weekend en op feestdagen. ’s Nachts vragen we je om je telefoon bij de hand te houden, zodat de bezorger niet hoeft aan te bellen. Hoe dat in de praktijk gaat, lees je bij <a href="/service/nachtbezorging/">nachtbezorging</a>.'],
        ['Wat doen jullie zelf om verantwoord te leveren?',
         'We leveren uitsluitend aan volwassenen die zich legitimeren, altijd verzegelde tanks, en we geven eerlijke informatie over risico’s in plaats van die te verzwijgen. We hebben geen kortingsacties en we sturen je niet aan op meer bestellen dan je van plan was. Meer over onze uitgangspunten lees je op <a href="/over-ons/">over ons</a>.'],
    ],
}

CONTACT = {
    'title': 'Contact | Lachgas Brabant',
    'description': 'Neem contact op met Lachgas Brabant: via WhatsApp voor bestellingen en dringende vragen, dag en nacht, of per e-mail voor alles wat kan wachten.',
    'h1': 'Contact',
    'lead': 'Een vraag, een bestelling of iets dat niet goed ging? Je bereikt ons het snelst via WhatsApp; voor de rest is er e-mail.',
    'intro': [
        'WhatsApp is ons hoofdkanaal, en dat is een bewuste keuze. Alles wat je met ons afspreekt staat in één chat, van je eerste bericht tot de bevestiging van het tijdvak en de afronding aan de deur. Via WhatsApp zijn we dag en nacht bereikbaar, zeven dagen per week, ook op feestdagen. Wil je bestellen, een lopende levering aanpassen of heb je een dringende vraag, dan is dit de weg; de knop op deze pagina opent de chat direct.',
        'Voor vragen die niet vandaag beantwoord hoeven te worden is e-mail een prima alternatief. Denk aan een vraag over onze voorwaarden, een opmerking over de website, een verzoek om een eerder gestuurde betaalbevestiging of een zakelijke aanvraag. E-mail lezen we overdag en niet continu; stuur dus geen bestelling of wijziging van een levering per mail, want die komt mogelijk te laat bij ons aan. Het e-mailadres staat in het contactblok op deze pagina.',
        'Zet in je eerste bericht meteen waar het over gaat: een bestelling, een vraag of een klacht. Bij een bestelling helpt het als je het formaat, je adres en het gewenste moment direct meestuurt, dan hoeven we niet heen en weer te vragen. Over de reactietijd zijn we eerlijk: via WhatsApp antwoorden we vrijwel altijd snel, maar op piekmomenten, zoals een vrijdag- of zaterdagavond, kan het iets langer duren. Je krijgt in alle gevallen een reactie van een mens, niet van een automatisch systeem.',
    ],
    'faq': [
        ['Wat is de snelste manier om een probleem met een lopende levering te melden?',
         'Stuur een bericht in dezelfde WhatsApp-chat waarin je hebt besteld, zodat wij en de bezorger direct zien om welke levering het gaat. Noem kort wat er aan de hand is en of je op het afleveradres bereikbaar blijft. Mailen is in dit geval niet handig, omdat we de mailbox niet snel genoeg lezen.'],
        ['Kan ik ook langskomen om een tank op te halen?',
         'Nee, we hebben geen winkel of afhaalpunt; alles gaat via bezorging aan de deur. Afspraken over een bestelling leggen we altijd vast in WhatsApp, zodat beide kanten kunnen teruglezen wat is afgesproken. Zo weet jij wat je kunt verwachten en weet de bezorger wat hij moet meenemen.'],
        ['Hoe snel krijg ik antwoord op een e-mail?',
         'Dat hangt af van het moment en de drukte; we lezen de mailbox overdag en beantwoorden berichten op volgorde van binnenkomst. Een exacte termijn noemen we liever niet, omdat we die niet altijd kunnen waarmaken. Is je vraag dringend, kies dan WhatsApp.'],
    ],
}

ABOUT = {
    'title': 'Over Lachgas Brabant | Bezorgservice in Noord-Brabant',
    'description': 'Lees wie Lachgas Brabant is, hoe de bezorging van verzegelde lachgastanks in heel Noord-Brabant werkt en waar wij voor staan: 18+, eerlijk en zonder druk.',
    'h1': 'Over Lachgas Brabant',
    'lead': 'Een bezorgservice voor verzegelde lachgastanks in heel Noord-Brabant, die liever eerlijk is dan groot.',
    'sections': [
        {
            'h2': 'Wie wij zijn',
            'paragraphs': [
                'Lachgas Brabant is een bezorgservice voor verzegelde lachgastanks in de provincie Noord-Brabant. We zijn geen webshop met een magazijn vol accessoires en geen groothandel; we bezorgen drie formaten tank aan de deur en verder niets. Je leest hier geen verhaal over hoe het allemaal begon of hoeveel mensen we al hebben geholpen, omdat dat voor jou weinig uitmaakt. Wat wel uitmaakt: dat je weet wat je krijgt, van wie, en onder welke voorwaarden. Daarom staat op deze site veel informatie, ook over de kanten van lachgas die minder prettig zijn. We werken met vaste bezorgers en houden de organisatie bewust overzichtelijk, zodat afspraken nakomen eenvoudiger is dan ze breken.',
            ],
        },
        {
            'h2': 'Hoe wij werken',
            'paragraphs': [
                'Alles begint met een bericht via WhatsApp. Je geeft door welk formaat je wilt, waar het heen moet en wanneer; wij antwoorden met de prijs en een tijdvak. Pas als jij akkoord geeft, gaat een bezorger op weg. Betalen doe je bij levering, contant of via Tikkie, en nooit vooraf. De levertijd hangt af van je plaats: in en rond de grote steden is het meestal binnen 30 tot 45 minuten, in middelgrote kernen meestal binnen 45 tot 60 minuten en in de verder gelegen dorpen meestal binnen 60 tot 90 minuten. Aan de deur controleert de bezorger of de ontvanger 18 jaar of ouder is, overhandigt de tank met intacte verzegeling en rondt de betaling af. Meer uitleg vind je bij <a href="/service/bestellen-via-whatsapp/">bestellen via WhatsApp</a> en <a href="/service/bezorgtijden-per-regio/">bezorgtijden per regio</a>.',
            ],
        },
        {
            'h2': 'Ons werkgebied: vier regio’s',
            'paragraphs': [
                'We bezorgen in heel Noord-Brabant en hebben de provincie verdeeld in vier regio’s, elk met een eigen overzicht van plaatsen en indicatieve levertijden. <a href="/bezorggebied/west-brabant/">West-Brabant</a> loopt van Breda, Oosterhout en Etten-Leur tot Bergen op Zoom, Roosendaal en de dorpen richting de Zeeuwse grens. <a href="/bezorggebied/midden-brabant/">Midden-Brabant</a> draait om Tilburg, met daaromheen Waalwijk, Oisterwijk, Goirle en de kernen van de Langstraat.',
                '<a href="/bezorggebied/noordoost-brabant/">Noordoost-Brabant</a> omvat ’s-Hertogenbosch, Oss, Uden, Veghel en het Land van Cuijk. <a href="/bezorggebied/zuidoost-brabant/">Zuidoost-Brabant</a> bestaat uit Eindhoven met zijn stadsdelen, Helmond, Veldhoven en de dorpen van de Kempen en de Peel. Hoe verder een adres van onze vaste routes ligt, hoe ruimer het tijdvak dat we noemen; dat zeggen we liever vooraf dan dat we je laten wachten zonder bericht.',
            ],
        },
        {
            'h2': 'Waar wij voor staan',
            'paragraphs': [
                'Vier uitgangspunten bepalen hoe we werken, en we houden ons eraan, ook als dat een bestelling kost.',
            ],
            'bullets': [
                '<strong>Uitsluitend 18+.</strong> We leveren alleen aan volwassenen die zich aan de deur kunnen legitimeren. Geen document, geen tank, ook niet als de besteller zelf wel volwassen is.',
                '<strong>Altijd verzegeld.</strong> Elke tank wordt met intacte verzegeling overhandigd, zodat je zeker weet dat de inhoud is wat erop staat en dat niemand er eerder aan heeft gezeten.',
                '<strong>Eerlijke informatie.</strong> We schrijven open over gezondheidsrisico’s, de Opiumwet en lokale regels, en verwijzen naar onafhankelijke bronnen in plaats van het mooier te maken dan het is.',
                '<strong>Geen druk om meer te bestellen.</strong> We kennen geen voordeel bij grotere afname en zullen je in de chat nooit een groter formaat aanpraten dan je zelf voor ogen had.',
            ],
        },
        {
            'h2': 'Contact met ons',
            'paragraphs': [
                'Heb je een vraag over een bestelling, over onze werkwijze of over iets wat niet goed ging, dan horen we het graag. WhatsApp is het snelste kanaal en staat dag en nacht open; voor zaken die kunnen wachten is e-mail prima. Op de <a href="/contact/">contactpagina</a> lees je wat je in je eerste bericht zet en wat je van onze reactietijd mag verwachten. Antwoorden op veel vragen vind je ook al in onze <a href="/veelgestelde-vragen/">veelgestelde vragen</a>, verdeeld over bestellen, bezorgen, betalen, veiligheid en regels.',
            ],
        },
    ],
    'note': 'Lachgas Brabant levert uitsluitend aan personen van 18 jaar en ouder. Lees voor je bestelt ook onze informatie over de risico’s en de geldende regels.',
}
