# -*- coding: utf-8 -*-
# Nieuwe wijken van de stad Groningen (fase 3) en de regio-hub Noord-Nederland. Alleen data.

AREAS = [
    {
        "slug": "zernike", "name": "Zernike", "kind": "wijk",
        "title": "Lachgas Zernike | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen op Zernike in Groningen: campus en studentenhuisvesting, meestal binnen 20 tot 30 minuten. Via WhatsApp, uitsluitend 18+ met ID-controle.",
        "h1": "Lachgas Zernike",
        "lead": "Bezorging op de Zernike Campus en in de studentenhuisvesting eromheen, besteld via WhatsApp en uitsluitend voor 18+.",
        "intro": [
            "Zernike ligt aan de noordrand van de stad Groningen, direct boven de Noordelijke Ringweg en op zo’n vier kilometer van de Grote Markt. Het gebied bestaat uit de campus van de Rijksuniversiteit en de Hanzehogeschool, de bedrijven aan de Zernikelaan en de wooncomplexen voor studenten aan de rand van het terrein. Wij bezorgen op het hele campusterrein en in de woongebouwen eromheen. Je stuurt via WhatsApp het gebouw, het huisnummer en eventueel de ingang door; wij bevestigen je bestelling en noemen vooraf de prijs.",
            "Vanuit het centrum rijden we via de Zonnelaan of de Eikenlaan naar de campus, een rit van ruim tien minuten buiten de spits. Met het openbaar vervoer is Zernike rechtstreeks verbonden met het Hoofdstation, maar onze bezorgers komen met de auto en hoeven dus niet op een bus te wachten. Omdat de campus aan de ringweg ligt en wij hier dagelijks rijden, staan we meestal binnen 20 tot 30 minuten voor de deur. Aan het begin van de avond, als veel bewoners tegelijk thuiskomen, kan het iets drukker zijn.",
            "Zernike is een studentenomgeving en daar zijn we duidelijk over: wij leveren uitsluitend aan personen van 18 jaar en ouder en de bezorger vraagt bij twijfel naar een geldig identiteitsbewijs. Zonder legitimatie gaat de tank weer mee terug. Voor een kleine groep in een studio is de 2KG het gangbare formaat; voor een gedeelde keuken met meer mensen past de 4KG beter. Bekijk de verschillen in ons <a href=\"/assortiment/\">assortiment</a>. Je betaalt bij levering contant of via Tikkie. Lees vooraf ook de informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Zernikelaan, Zernikeplein, Nijenborgh, Blauwborgje, Nettelbosje, Landleven, Zonnelaan, Kapteynborg, Bernoulliborg, Willem-Alexander Sportcentrum",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de studentenflats aan de rand van de campus?",
             "Ja, de woongebouwen rond de campus horen gewoon bij ons gebied. Vermeld in je bericht het volledige adres en of de hoofdingang gesloten is, dan spreekt de bezorger af waar hij je treft."],
            ["Moet ik een ID laten zien als ik op Zernike bestel?",
             "Als de bezorger niet zeker is dat je 18 jaar of ouder bent, vraagt hij naar een geldig identiteitsbewijs. Kun je dat niet tonen, dan leveren we niet. Meer hierover lees je op <a href=\"/leeftijdscontrole-18-plus/\">leeftijdscontrole 18+</a>."],
            ["Leveren jullie ook bij universiteitsgebouwen of bij de sportvelden?",
             "Nee, we bezorgen alleen op woonadressen en bij privéfeesten op een duidelijk afgesproken plek. Onderwijsgebouwen, sportaccommodaties en openbare plekken op de campus slaan we over."],
        ],
        "nearby": ["paddepoel", "selwerd", "reitdiep"],
        "lat": 53.241, "lon": 6.533,
    },
    {
        "slug": "schildersbuurt", "name": "Schildersbuurt", "kind": "wijk",
        "title": "Lachgas Schildersbuurt | 20-30 min via WhatsApp",
        "description": "Lachgas bezorgen in de Schildersbuurt in Groningen, tussen Noorderplantsoen en Westerhaven. Meestal binnen 20 tot 30 minuten, via WhatsApp, alleen 18+.",
        "h1": "Lachgas Schildersbuurt",
        "lead": "Lachgastanks, crackers en slagroompatronen bezorgd in de Schildersbuurt, aan de westkant van het centrum van Groningen.",
        "intro": [
            "De Schildersbuurt ligt pal ten westen van de Groningse binnenstad, tussen het Noorderplantsoen aan de noordkant en de Westerhaven en het Hoendiep aan de zuidkant. De Kraneweg loopt er als drukke as doorheen; daaromheen liggen de Jozef Israëlsstraat, de H.W. Mesdagstraat en de rustigere straten richting de Westersingel. Wij bezorgen in de hele buurt, van de Westerhaven tot de Melkweg. Bestellen doe je door je adres en de gewenste tank via WhatsApp te sturen, waarna je een bevestiging met de prijs ontvangt.",
            "Vanaf de Grote Markt is het nog geen kilometer naar de Kraneweg, dus deze buurt ligt op onze kortste route. We rijden via de Westersingel of de Aweg en hoeven de ringweg niet op. Bussen naar het Hoofdstation stoppen op de Westersingel en aan het Hoendiep, maar als bezorger komen we vanzelfsprekend met de auto. Door de korte afstand staan we meestal binnen 20 tot 30 minuten bij je; op vrijdag- en zaterdagavond, wanneer de parkeerdruk in de smalle straten hoog is, kan het aan de bovenkant van die indicatie uitkomen.",
            "In de Schildersbuurt wonen veel studenten in gedeelde huizen. Wij gaan daar zakelijk mee om: de bezorger controleert de leeftijd bij twijfel en levert nooit aan iemand onder de 18. Bij een kleine borrel is de <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> meestal voldoende, bij een vol huis kies je eerder voor 4KG; op de assortimentpagina zie je alle formaten naast elkaar. Betalen gebeurt bij de deur, contant of via Tikkie. We raden iedereen aan om eerst onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">verantwoord omgaan met lachgas</a> te lezen.",
        ],
        "wijken": "Kraneweg, Jozef Israëlsstraat, Jozef Israëlsplein, H.W. Mesdagstraat, Taco Mesdagstraat, Westersingel, Melkweg, Hofstede de Grootkade, Westerhaven, Noorderplantsoen",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Kunnen jullie wel parkeren in de Schildersbuurt?",
             "Onze bezorger zoekt een plek in de buurt of stopt kort voor de deur om af te leveren. Zorg dat je bereikbaar bent op WhatsApp, zodat hij je kan laten weten dat hij er is."],
            ["Ik woon aan de Kraneweg boven een winkel; hoe vinden jullie de ingang?",
             "Geef in je bericht aan waar de voordeur zit, bijvoorbeeld in een zijstraat of achter een poort. De bezorger stuurt een berichtje zodra hij voor de juiste deur staat."],
            ["Bezorgen jullie ook in het Noorderplantsoen zelf?",
             "Nee, we leveren alleen op woonadressen en niet in parken of op straat. Op een adres aan de rand van het plantsoen komen we natuurlijk wel; lees ook de pagina over <a href=\"/lachgas-informatie/lachgas-regels-groningen/\">regels in Groningen</a>."],
        ],
        "nearby": ["binnenstad", "hortusbuurt", "kostverloren"],
        "lat": 53.2195, "lon": 6.553,
    },
    {
        "slug": "hortusbuurt", "name": "Hortusbuurt", "kind": "wijk",
        "title": "Lachgas Hortusbuurt | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in de Hortusbuurt en het Ebbingekwartier, net boven de binnenstad van Groningen. Meestal binnen 20 tot 30 minuten, uitsluitend 18+.",
        "h1": "Lachgas Hortusbuurt",
        "lead": "Snelle bezorging in de Hortusbuurt en het Ebbingekwartier, op loopafstand van de Grote Markt en uitsluitend voor 18+.",
        "intro": [
            "De Hortusbuurt vormt het noordelijke deel van de oude stad van Groningen, binnen de Diepenring: tussen de Noorderhaven en de Spilsluizen aan de zuidkant, het Boterdiep aan de oostkant en het Noorderplantsoen aan de westkant. De buurt dankt haar naam aan de voormalige Hortus Botanicus aan de Grote Rozenstraat. Wij bezorgen in de hele buurt, inclusief het Ebbingekwartier langs de Bloemsingel. Je bestelt door via WhatsApp je adres door te geven; wij reageren met een bevestiging en de prijs.",
            "De Grote Markt ligt op vijf minuten lopen, dus voor onze bezorgers is dit een van de dichtstbijzijnde buurten. We komen via de Nieuwe Ebbingestraat of de Boteringebrug de buurt in en zijn zelden lang onderweg. Omdat de straten smal zijn en eenrichtingsverkeer hebben, stopt de bezorger kort voor je deur. Meestal zijn we binnen 20 tot 30 minuten bij je; de afstand is kort, maar het klaarzetten van de bestelling en het verkeer rond de Diepenring bepalen de rest van de tijd.",
            "Tussen de universiteitsgebouwen en de oude herenhuizen wonen in de Hortusbuurt veel studenten en starters. Ook hier geldt zonder uitzondering: uitsluitend 18+, en de bezorger kan om een identiteitsbewijs vragen. Welke tank je kiest, hangt af van het gezelschap; in ons <a href=\"/assortiment/\">assortiment</a> staan de 2KG, 4KG en 10KG met hun kenmerken naast elkaar, net als de crackers en slagroompatronen. Afrekenen doe je bij de deur, contant of via Tikkie. Op de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> lees je waar je op moet letten.",
        ],
        "wijken": "Nieuwe Ebbingestraat, Nieuwe Boteringestraat, Nieuwe Kijk in 't Jatstraat, Grote Rozenstraat, Grote Kruisstraat, Bloemsingel, Boterdiep, Noorderhaven, Spilsluizen, Ebbingekwartier",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Mijn huis in de Hortusbuurt heeft geen parkeerplek voor de deur; is dat een probleem?",
             "Nee, de bezorger stopt kort of parkeert om de hoek en loopt het laatste stuk. Houd je telefoon bij de hand, dan weet je precies wanneer hij er is."],
            ["Bezorgen jullie ook in het Ebbingekwartier en de nieuwbouw aan de Bloemsingel?",
             "Ja, dat deel hoort bij de Hortusbuurt en zit in ons gebied. Vermeld bij een appartementencomplex de verdieping en het belnummer, dan verloopt de aflevering vlot."],
            ["Wat als ik in de Hortusbuurt woon maar ’s nachts wil bestellen?",
             "Ook ’s avonds laat en ’s nachts zijn we bereikbaar; de tijd kan dan iets afwijken van de indicatie overdag. Kijk op <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a> voor hoe dat werkt."],
        ],
        "nearby": ["binnenstad", "korrewegwijk", "schildersbuurt"],
        "lat": 53.2235, "lon": 6.5635,
    },
    {
        "slug": "de-wijert", "name": "De Wijert", "kind": "wijk",
        "title": "Lachgas De Wijert | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in De Wijert in Groningen-Zuid, tussen de Hereweg en de A28. Meestal binnen 20 tot 30 minuten aan de deur, via WhatsApp, alleen 18+.",
        "h1": "Lachgas De Wijert",
        "lead": "Bezorging in De Wijert-Noord en De Wijert-Zuid, de woonwijk direct onder de Zuidelijke Ringweg van Groningen.",
        "intro": [
            "De Wijert ligt in het zuiden van de stad Groningen, direct onder de Zuidelijke Ringweg, met de Hereweg en Helpman aan de oostkant en de A28 aan de westkant. De wijk bestaat uit De Wijert-Noord, met de flats en portiekwoningen rond de Vondellaan en de Van Iddekingeweg, en het ruimer opgezette De Wijert-Zuid ten zuiden van de Van Ketwich Verschuurlaan. Wij bezorgen in beide delen. Bestellen gaat via WhatsApp: je stuurt je straat en huisnummer, wij bevestigen en noemen de prijs vooraf.",
            "Vanuit het centrum rijden we over de Hereweg of via de ringweg en het Julianaplein de wijk in; dat is een rit van ongeveer tien minuten. De wijk ligt op fietsafstand van het Hoofdstation en wordt door stadsbussen ontsloten, maar voor de bezorging rijden wij zelf. Door de goede aansluiting op de ringweg hoort De Wijert bij de wijken waar we meestal binnen 20 tot 30 minuten staan. Alleen bij files op de ring aan het einde van de middag kan het aan de ruime kant uitvallen.",
            "In De Wijert wonen gezinnen, ouderen en studenten door elkaar, en de aanleidingen voor een bestelling zijn even divers: een verjaardag, een avond met vrienden of een tuinfeest in De Wijert-Zuid. Voor een klein gezelschap volstaat de 2KG, voor een groter feest is de <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> het logische formaat; alle maten staan op de assortimentpagina. Wij leveren alleen aan 18+ en vragen bij twijfel naar je ID. Betalen kan contant of via Tikkie. Lees voor je bestelt onze tips over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Vondellaan, Van Iddekingeweg, Van Ketwich Verschuurlaan, Van Lenneplaan, P.C. Hooftlaan, De Wijert-Noord, De Wijert-Zuid, Hereweg, Zuidelijke Ringweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de flats aan de Vondellaan?",
             "Ja. Geef in je bericht de verdieping en het belnummer door, dan belt de bezorger aan of appt hij zodra hij beneden staat."],
            ["Hoe lang duurt het naar De Wijert-Zuid, helemaal achterin de wijk?",
             "Ook het zuidelijke deel ligt binnen een paar minuten van de ringweg, dus de indicatie van 20 tot 30 minuten geldt voor de hele wijk. Bij vertraging laten we dat via WhatsApp weten."],
            ["Kan ik een 10KG tank laten bezorgen voor een groot feest in De Wijert?",
             "Ja, de 10KG bezorgen we net zo goed aan de deur. Bekijk vooraf de pagina over de <a href=\"/product/lachgas-tank-10kg/\">lachgastank 10KG</a>, zodat je weet hoe groot en zwaar die is."],
        ],
        "nearby": ["helpman", "rivierenbuurt", "hoornse-meer"],
        "lat": 53.196, "lon": 6.573,
    },
    {
        "slug": "hoornse-meer", "name": "Hoornse Meer", "kind": "wijk",
        "title": "Lachgas Hoornse Meer | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Hoornse Meer en Hoornse Park in Groningen-Zuidwest, aan het Paterswoldsemeer. Meestal binnen 20 tot 30 minuten, uitsluitend 18+.",
        "h1": "Lachgas Hoornse Meer",
        "lead": "Bezorging in Hoornse Meer, Hoornse Park en Piccardthof, de waterrijke wijken aan de zuidwestkant van Groningen.",
        "intro": [
            "Hoornse Meer ligt in het zuidwesten van de stad Groningen, tussen de A28 en het water van het Hoornsemeer en het Paterswoldsemeer. Ten noorden ligt Corpus den Hoorn met het Martini Ziekenhuis, ten westen het buurtje Piccardthof en aan de oostkant, aan de overkant van de snelweg, De Wijert. Wij bezorgen in Hoornse Meer, Hoornse Park en Piccardthof. Je bestelt met een WhatsApp-bericht waarin je adres en de gewenste tank staan; wij bevestigen met de prijs en de verwachte aankomsttijd.",
            "Vanuit het centrum is de wijk het snelst te bereiken via de Zuidelijke Ringweg en de A28, afslag Groningen-Zuid, of via de Paterswoldseweg langs het Stadspark. Dat is een rit van een kwartier. Bussen rijden over de Laan Corpus den Hoorn, maar voor de bezorging doet dat er niet toe: wij komen met de auto. De aansluiting op de snelweg maakt dat we hier meestal binnen 20 tot 30 minuten staan, ook al ligt de wijk aan de rand van de stad.",
            "De woningen aan het water en de ruime huizen in Hoornse Park lenen zich voor een tuinfeest of een avond op het terras. Bij warm weer houd je de tank uit de zon en in de schaduw; de bezorger geeft die tip ook aan de deur. Welke maat past, zie je in het <a href=\"/assortiment/\">assortiment</a>: 2KG voor een klein gezelschap, 4KG of 10KG als er meer mensen komen. Wij leveren uitsluitend aan 18+ en controleren bij twijfel je ID. Afrekenen gebeurt bij aflevering, contant of met een Tikkie. Neem vooraf de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door.",
        ],
        "wijken": "Hoornsemeer, Hoornse Plas, Paterswoldsemeer, Hoornsedijk, Hoornse Park, Piccardthof, Kaap Hoorn, Laan Corpus den Hoorn, Martini Ziekenhuis",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook bij het strand van de Hoornse Plas of bij Kaap Hoorn?",
             "Nee, op het strand, in het recreatiegebied en op parkeerplaatsen leveren we niet. Wel op woonadressen in de wijk, dus geef een huisadres op."],
            ["Ik woon aan de Hoornsedijk, buiten de bebouwing. Komen jullie daar?",
             "Ja, de Hoornsedijk hoort bij ons gebied. Stuur het huisnummer en eventueel een herkenningspunt mee, want de nummering langs de dijk is niet overal even logisch."],
            ["Is Hoornse Meer trager dan het centrum omdat het aan de rand ligt?",
             "Nauwelijks: via de A28 is de wijk snel bereikbaar en de indicatie van 20 tot 30 minuten geldt hier ook. Bekijk alle zones op <a href=\"/bezorgtijden-groningen/\">bezorgtijden in Groningen</a>."],
        ],
        "nearby": ["de-wijert", "eelde-paterswolde", "haren"],
        "lat": 53.187, "lon": 6.556,
    },
    {
        "slug": "europapark", "name": "Europapark", "kind": "wijk",
        "title": "Lachgas Europapark | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Europapark in Groningen, rond de Euroborg en station Europapark. Meestal binnen 20 tot 30 minuten aan de deur, uitsluitend 18+.",
        "h1": "Lachgas Europapark",
        "lead": "Bezorging in de nieuwe stadswijk Europapark, tussen de Oosterpoort, Helpman en het Winschoterdiep.",
        "intro": [
            "Europapark is de jonge wijk aan de zuidoostkant van de stad Groningen, gebouwd rond de Euroborg en het gelijknamige treinstation. De wijk ligt tussen de Zuidelijke Ringweg en de Oosterpoort aan de noordkant, de spoorlijn naar Helpman aan de westkant en het Winschoterdiep aan de oostkant. Appartementen langs de Boumaboulevard, kantoren aan het Helperpark en het rijkskantoor aan de Kempkensberg bepalen het beeld. Wij bezorgen op alle woonadressen in Europapark; een WhatsApp-bericht met je adres is genoeg om te bestellen.",
            "Het Hoofdstation ligt op een paar minuten rijden; via de Hereweg en de Helperzoom of via de Europaweg zijn we snel in de wijk. Station Europapark heeft treinen in de richting van Assen en Winschoten, en de Euroborg is op wedstrijddagen druk, maar daarbuiten is het hier rustig rijden. Daarom staan we meestal binnen 20 tot 30 minuten bij je. Rond een thuiswedstrijd van FC Groningen zijn wegen afgezet en parkeerplaatsen vol, en dan kan het langer duren; dat melden we vooraf.",
            "In de appartementencomplexen van Europapark gaat het meestal om een borrel of een verjaardag met een handvol gasten; de <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> is dan het meest gekozen formaat en past makkelijk in een lift. Voor een groter gezelschap kijk je op de assortimentpagina naar de 4KG. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen bij twijfel naar een identiteitsbewijs. Betalen doe je bij de deur, contant of via Tikkie. Op de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> staan de belangrijkste aandachtspunten.",
        ],
        "wijken": "Euroborg, Station Groningen Europapark, Boumaboulevard, Helperpark, Kempkensberg, Mediacentrale, Europaweg, Winschoterdiep, Zuidelijke Ringweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie op een wedstrijddag van FC Groningen in Europapark?",
             "Ja, maar dan zijn er afzettingen rond de Euroborg en is parkeren lastig. Reken op een ruimere tijd en vermeld in je bericht hoe de bezorger je gebouw het beste kan bereiken."],
            ["Hoe gaat de aflevering in een appartementengebouw aan de Boumaboulevard?",
             "De bezorger belt of appt bij de centrale ingang en je komt naar beneden of laat hem binnen. Vermeld de verdieping en het belnummer, dat scheelt zoeken."],
            ["Welke tank is handig in een appartement met een lift?",
             "De 2KG en 4KG zijn compact genoeg voor elke lift en trap. Twijfel je, lees dan de keuzehulp <a href=\"/lachgas-informatie/welke-lachgastank-heb-ik-nodig/\">welke lachgastank heb ik nodig</a>."],
        ],
        "nearby": ["oosterpoort", "helpman", "binnenstad"],
        "lat": 53.2045, "lon": 6.586,
    },
    {
        "slug": "reitdiep", "name": "Reitdiep", "kind": "wijk",
        "title": "Lachgas Reitdiep | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in de wijk Reitdiep in Groningen-Noordwest, rond de Reitdiephaven en Dorkwerd. Meestal binnen 20 tot 30 minuten, uitsluitend voor 18+.",
        "h1": "Lachgas Reitdiep",
        "lead": "Bezorging in de woonwijk Reitdiep, aan het water in het noordwesten van Groningen, besteld via WhatsApp.",
        "intro": [
            "De wijk Reitdiep ligt in het noordwesten van de stad Groningen, tussen de rivier het Reitdiep, Vinkhuizen aan de zuidkant en de Zernike Campus aan de oostkant. Het is een van de jongste woonwijken van de stad, met de Reitdiephaven en zijn gekleurde gevels als middelpunt en het oude dorp Dorkwerd aan de noordrand. Wij bezorgen in de hele wijk, van de haven tot aan Dorkwerd. Bestellen doe je via WhatsApp: adres en gewenste tank doorgeven, bevestiging met de prijs terug.",
            "Vanuit het centrum rijden we via de Friesestraatweg en de Noordelijke Ringweg naar de wijk, een rit van ruim tien minuten. Ook via Vinkhuizen is Reitdiep goed te bereiken. Het openbaar vervoer verbindt de wijk met de binnenstad en Zernike, maar wij komen uiteraard zelf. Door de rechtstreekse aansluiting op de ringweg hoort Reitdiep bij de gebieden waar we meestal binnen 20 tot 30 minuten staan. In de avondspits op de westelijke ring kan het iets langer duren.",
            "Reitdiep is een wijk van gezinnen en tweeverdieners, en bestellingen gaan hier vaak om een tuinfeest, een verjaardag of een avond aan het water. De 2KG volstaat voor een klein gezelschap; voor meer gasten staan de 4KG en 10KG in ons <a href=\"/assortiment/\">assortiment</a> beschreven. Wij leveren uitsluitend aan 18+ en de bezorger kan om een identiteitsbewijs vragen. Je rekent af als de tank er is, contant of via Tikkie. Lees vooraf de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> en zet de tank na gebruik koel en rechtop weg.",
        ],
        "wijken": "Reitdiephaven, Reitdiep, Dorkwerd, Dorkwerdersluis, Van Starkenborghkanaal, Friesestraatweg, Noordelijke Ringweg, Zernike Campus",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in Dorkwerd?",
             "Ja, Dorkwerd hoort bij de wijk Reitdiep en dus bij ons gebied. Geef je huisnummer duidelijk door; het dorp is klein, dus de bezorger vindt het snel."],
            ["Kan ik laten bezorgen bij een boot in de Reitdiephaven?",
             "Nee, we leveren niet op boten of steigers, alleen op een woonadres. Woon je aan de haven, dan geef je gewoon je huisadres door."],
            ["Hoe laat kan ik in Reitdiep nog bestellen?",
             "Ook ’s avonds laat zijn we bereikbaar en ’s nachts in overleg; de indicatie kan dan iets ruimer zijn. Zie <a href=\"/lachgas-nachtbezorging/\">nachtbezorging</a> voor de details."],
        ],
        "nearby": ["vinkhuizen", "zernike", "paddepoel"],
        "lat": 53.238, "lon": 6.518,
    },
    {
        "slug": "meerstad", "name": "Meerstad", "kind": "wijk",
        "title": "Lachgas Meerstad | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Meerstad aan het Woldmeer, ten oosten van Groningen: Meeroevers, Tersluis en Groenewei. Meestal binnen 20 tot 30 minuten, 18+.",
        "h1": "Lachgas Meerstad",
        "lead": "Bezorging in Meerstad, de nieuwe woonwijk aan het Woldmeer aan de oostkant van Groningen, besteld via WhatsApp.",
        "intro": [
            "Meerstad is de nieuwbouwwijk aan de oostkant van de stad Groningen, rond het aangelegde Woldmeer en voorbij de dorpen Engelbert en Middelbert. Het gebied hoort bij de gemeente Groningen en grenst aan Harkstede. De buurten Meeroevers, Tersluis en Groenewei zijn bewoond, De Zeilen is in aanbouw. Wij bezorgen in alle woonbuurten van Meerstad. Omdat niet elke nieuwe straat al in navigatiesystemen staat, vragen we je bij het bestellen via WhatsApp om straat, huisnummer en de buurtnaam door te geven.",
            "Vanuit het centrum rijden we via de Oostelijke Ringweg en de weg door Engelbert naar Meerstad. Reken op een kwartier rijden buiten de spits. Er rijdt een bus tussen Meerstad en de stad, maar voor de bezorging maakt dat niet uit: wij komen met de auto. Ondanks de afstand tot de Grote Markt rekenen we Meerstad tot de stad en staan we meestal binnen 20 tot 30 minuten voor de deur, omdat de route grotendeels over doorgaande wegen loopt en we er geregeld komen.",
            "Meerstad is een gezinswijk met ruime kavels en tuinen aan het water, dus bestellingen zijn hier vaak voor een tuinfeest of een verjaardag met volwassen gasten. De <a href=\"/product/lachgas-tank-4kg/\">lachgastank 4KG</a> is voor zo’n gelegenheid een gangbare keuze; op de assortimentpagina staan ook de 2KG en 10KG. Wij leveren uitsluitend aan 18+ en controleren dat bij twijfel aan de hand van een identiteitsbewijs. Afrekenen kan contant of via Tikkie op het moment van levering. Lees voor het feest onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Meeroevers, Tersluis, Groenewei, De Zeilen, Woldmeer, Vossenburglaan, Harkstede, Engelbert, Middelbert",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Mijn straat in Meerstad staat nog niet op de kaart; vinden jullie het dan wel?",
             "Meestal wel, als je de buurtnaam en een herkenningspunt meestuurt. De bezorger appt je zodra hij de wijk inrijdt, zodat je kunt bijsturen."],
            ["Bezorgen jullie ook in Harkstede, net over de grens met Midden-Groningen?",
             "Harkstede ligt direct tegen Meerstad aan en we komen er in de praktijk ook; de levertijd kan daar iets ruimer zijn. Stuur je adres via WhatsApp en we bevestigen of en hoe snel we kunnen komen."],
            ["Mag een lachgastank aan het Woldmeer in de zon staan?",
             "Liever niet: zet de tank in de schaduw of binnen, rechtop en uit de buurt van warmtebronnen. Meer tips lees je in het artikel over <a href=\"/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/\">bewaren en vervoeren</a>."],
        ],
        "nearby": ["engelbert", "lewenborg", "europapark"],
        "lat": 53.218, "lon": 6.665,
    },
    {
        "slug": "hoogkerk", "name": "Hoogkerk", "kind": "wijk",
        "title": "Lachgas Hoogkerk | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Hoogkerk, Gravenburg en Buitenhof aan de westkant van Groningen bij de A7. Meestal binnen 20 tot 30 minuten aan de deur, 18+.",
        "h1": "Lachgas Hoogkerk",
        "lead": "Bezorging in Hoogkerk, het voormalige dorp aan de A7 dat tegenwoordig het westelijkste stadsdeel van Groningen is.",
        "intro": [
            "Hoogkerk ligt aan de westkant van de stad Groningen, buiten de Westelijke Ringweg en direct aan de A7, op ongeveer zes kilometer van de Grote Markt. Het was lang een zelfstandig dorp en voelt nog steeds zo, met de oude kern rond het Hoendiep, de suikerfabriek als blikvanger en nieuwere buurten als Gravenburg, Buitenhof en Hoogkerk-Zuid eromheen. Wij bezorgen in heel Hoogkerk, inclusief Leegkerk en Ruskenveen. Via WhatsApp geef je je adres door en krijg je direct een bevestiging met de prijs.",
            "Vanuit het centrum rijden we via de Westelijke Ringweg en de A7, afslag Hoogkerk, of binnendoor via de Peizerweg en het Hoendiep. Het is een rit van ongeveer een kwartier, want het grootste deel gaat over doorgaande wegen. Stadsbussen rijden tussen Hoogkerk en het Hoofdstation, maar onze bezorgers komen met de auto. Door de snelwegaansluiting staan we hier meestal binnen 20 tot 30 minuten, ook al is Hoogkerk het verste punt aan de westkant van de stad. Rond de spits op de A7 kan het iets uitlopen.",
            "In Hoogkerk gaat het vaak om een verjaardag in een gezinswoning, een avond met de buren of een feest in een schuur bij een van de boerderijen rond Leegkerk. Voor een klein gezelschap is de 2KG genoeg; voor meer gasten vind je de 4KG en 10KG in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan personen van 18 jaar en ouder en vragen bij twijfel om een ID. Betaling volgt bij levering, contant of via Tikkie. Op de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> lees je hoe je verantwoord met de tank omgaat.",
        ],
        "wijken": "Hoendiep, Zuiderweg, Gravenburg, Buitenhof, Hoogkerk-Zuid, Ruskenveen, Leegkerk, Suikerfabriek, Peizerweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Horen Gravenburg en Buitenhof bij jullie gebied Hoogkerk?",
             "Ja, beide nieuwbouwbuurten tussen Hoogkerk en Vinkhuizen horen erbij en hebben dezelfde indicatie van 20 tot 30 minuten. Stuur gewoon je adres via WhatsApp."],
            ["Komen jullie ook op de boerderijen rond Leegkerk?",
             "Ja, mits het een woonadres is. Geef het huisnummer en de weg goed door en zet buitenverlichting aan als het donker is, dan vindt de bezorger de oprit sneller."],
            ["Waar kan ik in Hoogkerk een lege tank kwijt?",
             "Een lege tank hoort niet bij het restafval; lever hem in bij een afvalbrengstation van de gemeente. Hoe dat gaat, lees je in ons artikel over <a href=\"/lachgas-informatie/lege-lachgastank-inleveren-groningen/\">lege lachgastanks inleveren</a>."],
        ],
        "nearby": ["vinkhuizen", "leek", "zuidhorn"],
        "lat": 53.215, "lon": 6.498,
    },
    {
        "slug": "oosterparkwijk", "name": "Oosterparkwijk", "kind": "wijk",
        "title": "Lachgas Oosterparkwijk | 20-30 min via WhatsApp",
        "description": "Lachgas bezorgen in de Oosterparkwijk in Groningen, naast het UMCG en het Oosterpark. Meestal binnen 20 tot 30 minuten, via WhatsApp, alleen 18+.",
        "h1": "Lachgas Oosterparkwijk",
        "lead": "Bezorging in de Oosterparkwijk, de volksbuurt direct ten oosten van het UMCG en de Groningse binnenstad.",
        "intro": [
            "De Oosterparkwijk ligt direct ten oosten van de binnenstad van Groningen, aan de andere kant van het UMCG. De wijk wordt begrensd door de Petrus Campersingel in het westen, het Oosterhamrikkanaal in het noorden en het Damsterdiep in het zuiden; in het midden ligt het Oosterpark. De Gorechtbuurt, de Bloemenbuurt met haar straten met bloemennamen en de nieuwbouw op de plek van het oude stadion vormen samen de wijk. Wij bezorgen overal in de Oosterparkwijk; via WhatsApp stuur je je adres en ontvang je de prijs en een bevestiging.",
            "Vanaf de Grote Markt is het nog geen tien minuten rijden via het Damsterdiep of de Petrus Campersingel. Ook vanaf de Oostelijke Ringweg is de wijk via de Oosterhamriklaan snel binnen. Het UMCG en de Oosterhamrikzone trekken veel verkeer, maar de woonstraten zelf zijn rustig. Daardoor zijn we meestal binnen 20 tot 30 minuten bij je. In de smalle straten van de Bloemenbuurt parkeert de bezorger kort en loopt hij naar je deur, zodat niemand lang in de weg staat.",
            "De Oosterparkwijk is een mix van oude arbeiderswoningen, studentenkamers en nieuwe appartementen. Een verjaardag in een bovenwoning, een borrel na het werk of een huisfeest: voor een paar mensen is de 2KG voldoende, voor een grotere groep kies je de 4KG uit ons <a href=\"/assortiment/\">assortiment</a>. Verkoop is uitsluitend aan 18+ en de bezorger controleert dat bij twijfel met een identiteitsbewijs. Betalen doe je aan de deur, contant of via Tikkie. Lees ook onze pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> voordat je bestelt.",
        ],
        "wijken": "Oosterpark, Zaagmuldersweg, Gorechtkade, Oliemuldersweg, Oosterhamrikkade, Klaprooslaan, Irislaan, Linnaeusplein, Pioenpark, Bloemenbuurt",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook bij het UMCG of in het Oosterpark?",
             "Nee, wij leveren niet bij het ziekenhuis, in parken of op straat. Op een woonadres in de wijk, ook direct naast het park, komen we wel."],
            ["Ik woon in een bovenwoning aan de Zaagmuldersweg zonder bel. Hoe gaat dat?",
             "Stuur dat vooraf even door, dan appt de bezorger zodra hij voor de deur staat en kom je naar beneden. Zo blijft de aflevering kort en onopvallend."],
            ["Zijn jullie in de Oosterparkwijk ook in het weekend beschikbaar?",
             "Ja, in het weekend bezorgen we net als op werkdagen, al kan het op zaterdagavond iets drukker zijn. Hoe dat werkt, lees je op <a href=\"/lachgas-weekendbezorging/\">weekendbezorging</a>."],
        ],
        "nearby": ["binnenstad", "korrewegwijk", "oosterpoort"],
        "lat": 53.2235, "lon": 6.583,
    },
    {
        "slug": "rivierenbuurt", "name": "Rivierenbuurt", "kind": "wijk",
        "title": "Lachgas Rivierenbuurt | 20-30 min via WhatsApp",
        "description": "Lachgas bezorgen in de Rivierenbuurt in Groningen, direct achter het Hoofdstation. Meestal binnen 20 tot 30 minuten aan de deur, via WhatsApp, alleen 18+.",
        "h1": "Lachgas Rivierenbuurt",
        "lead": "Bezorging in de Rivierenbuurt, het Zuiderpark en de Grunobuurt, de woonstraten ten zuiden van het Hoofdstation van Groningen.",
        "intro": [
            "De Rivierenbuurt ligt direct ten zuiden van het Hoofdstation van Groningen, ingeklemd tussen de Hereweg aan de oostkant, de Paterswoldseweg aan de westkant en de Zuidelijke Ringweg aan de zuidkant. De straten dragen namen van rivieren: Merwedestraat, Maasstraat, Rijnstraat, IJsselstraat. Aan de noordkant, tegen het station aan, liggen het Zuiderpark en even verder de Grunobuurt; aan de zuidrand ligt het openluchtbad De Papiermolen. Wij bezorgen in de hele buurt. Via WhatsApp stuur je je adres en gewenste tank; wij bevestigen met de prijs.",
            "Vanuit het centrum is dit een van de kortste ritten: over de Hereweg of de Paterswoldseweg ben je in een paar minuten in de buurt, en ook de afslag van de Zuidelijke Ringweg bij de Hereweg ligt vlakbij. Het Hoofdstation met al zijn bussen en treinen is om de hoek, maar onze bezorger komt met de auto tot voor je deur. De ligging tussen station en ringweg maakt dat we meestal binnen 20 tot 30 minuten bij je staan; bij drukte op de Hereweg kan het een paar minuten langer duren.",
            "In de Rivierenbuurt wonen starters, gezinnen en studenten naast elkaar in portiekwoningen en herenhuizen. Voor een borrel in een bovenwoning is de 2KG het handzaamste formaat; voor een feest met meer mensen bekijk je de 4KG en 10KG in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan 18+ en vragen bij twijfel om een geldig identiteitsbewijs. Betalen kan contant of via Tikkie zodra de bezorger voor je staat. Neem vooraf de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> door, zodat je weet waar je op moet letten.",
        ],
        "wijken": "Merwedestraat, Maasstraat, Rijnstraat, IJsselstraat, Hereweg, Paterswoldseweg, Zuiderpark, Grunobuurt, De Papiermolen, Hoofdstation",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Ik stap uit de trein op het Hoofdstation; kan ik dan laten bezorgen op mijn adres in de Rivierenbuurt?",
             "Ja, stuur je bestelling alvast onderweg, dan is de tank er vaak kort na jou. Geef je adres en een tijdstip waarop je thuis bent door, want we leveren alleen aan de deur."],
            ["Horen het Zuiderpark en de Grunobuurt ook bij dit gebied?",
             "Ja, beide liggen direct naast de Rivierenbuurt en krijgen dezelfde indicatie van 20 tot 30 minuten. Geef gewoon je straat en huisnummer door."],
            ["Hoe vraag ik vooraf de prijs op?",
             "Stuur via WhatsApp welk formaat je wilt en je adres; je krijgt dan de prijs en de verwachte tijd terug voordat we rijden. Meer over afrekenen lees je bij <a href=\"/betaalmethoden/\">betaalmethoden</a>."],
        ],
        "nearby": ["oosterpoort", "de-wijert", "binnenstad"],
        "lat": 53.2055, "lon": 6.566,
    },
    {
        "slug": "lewenborg", "name": "Lewenborg", "kind": "wijk",
        "title": "Lachgas Lewenborg | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Lewenborg in Groningen-Oost, bij Kardinge en de Oostelijke Ringweg. Meestal binnen 20 tot 30 minuten, via WhatsApp, alleen 18+.",
        "h1": "Lachgas Lewenborg",
        "lead": "Bezorging in Lewenborg en omliggende buurten als Oosterhoogebrug, Ruischerbrug en Noorddijk in het oosten van Groningen.",
        "intro": [
            "Lewenborg ligt in het noordoosten van de stad Groningen, aan de buitenkant van de Oostelijke Ringweg en naast het recreatiegebied Kardinge. Het is een wijk uit de jaren zeventig met woonerven, veel groen en het winkelcentrum aan de Kajuit als middelpunt. Aan de noordwestkant ligt Kardinge en daarachter Beijum; aan de zuidkant liggen Oosterhoogebrug en Ruischerbrug langs het Van Starkenborghkanaal. Wij bezorgen in Lewenborg en deze aangrenzende buurten. Je bestelt met een WhatsApp-bericht met je adres; wij bevestigen en noemen de prijs.",
            "Vanuit het centrum rijden we via de Oosterhamriklaan en de Oostelijke Ringweg naar de afslag richting Kardinge en Lewenborg, of binnendoor over de Pop Dijkemaweg. Dat is een rit van ruim tien minuten. De wijk heeft een rechtstreekse busverbinding met het Hoofdstation, maar onze bezorging gaat met de auto. Door de aansluiting op de ringweg staan we in Lewenborg meestal binnen 20 tot 30 minuten voor de deur. Op de woonerven kan het zoeken zijn naar het juiste huisnummer, dus een korte aanwijzing in je bericht helpt.",
            "Lewenborg is een gezinswijk waar een bestelling meestal hoort bij een verjaardag, een tuinfeest of een avond met vrienden. Voor een klein groepje is de 2KG het meest praktische formaat, voor meer gasten kijk je naar de 4KG of 10KG in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren alleen aan 18+ en vragen bij twijfel een identiteitsbewijs. Je betaalt pas bij levering, contant of via een Tikkie. Lees vooraf onze informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a> en houd de tank buiten bereik van kinderen.",
        ],
        "wijken": "Kajuit, Kardinge, Kardingerplas, Zilvermeer, Ulgersmaweg, Noorddijk, Ruischerbrug, Oosterhoogebrug, Van Starkenborghkanaal, Oostelijke Ringweg",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook bij Kardinge, bijvoorbeeld bij het sportcentrum of aan de plas?",
             "Nee, in het recreatiegebied en bij het sportcentrum leveren we niet. We komen alleen op woonadressen in Lewenborg en de buurten eromheen."],
            ["Horen Oosterhoogebrug en Ruischerbrug bij Lewenborg?",
             "Voor onze bezorging wel: ze liggen direct naast Lewenborg en hebben dezelfde indicatie van 20 tot 30 minuten. Vermeld je straat en huisnummer en we komen eraan."],
            ["Hoe vindt de bezorger mijn huis op een woonerf?",
             "Geef in je bericht een herkenningspunt door, zoals een parkeerhof of een speeltuin, en houd je telefoon bij de hand. Bij twijfel appt de bezorger even voor hij de auto parkeert."],
        ],
        "nearby": ["beijum", "oosterparkwijk", "ten-boer"],
        "lat": 53.238, "lon": 6.613,
    },
    {
        "slug": "indische-buurt", "name": "Indische Buurt", "kind": "wijk",
        "title": "Lachgas Indische Buurt | 20-30 min via WhatsApp",
        "description": "Lachgas bezorgen in de Indische Buurt in Groningen, tussen de Korreweg en het Oosterhamrikkanaal. Meestal binnen 20 tot 30 minuten, alleen 18+.",
        "h1": "Lachgas Indische Buurt",
        "lead": "Bezorging in de Indische Buurt, het hart van de Korrewegwijk met straten als het Floresplein en de Sumatralaan.",
        "intro": [
            "De Indische Buurt is het deel van de Korrewegwijk in Groningen dat tussen de Korreweg, de Bedumerweg en het Oosterhamrikkanaal ligt, op loopafstand van het UMCG en station Groningen Noord. De straten zijn genoemd naar eilanden van de Indonesische archipel: Floresstraat, Javastraat, Sumatralaan, Molukkenstraat. Het Floresplein en het Molukkenplantsoen zijn de centrale open plekken. Wij bezorgen in de hele buurt. Je bestelt door via WhatsApp je adres en het gewenste formaat door te geven; wij sturen een bevestiging met de prijs terug.",
            "Vanaf de Grote Markt is het via de Nieuwe Ebbingestraat en de Korreweg een rit van hooguit tien minuten; vanaf de Noordelijke Ringweg komen we via de Bedumerweg de buurt in. Station Groningen Noord ligt aan de bovenkant van de buurt en bussen rijden over de Korreweg en de Bedumerweg. Omdat de afstand kort is en de buurt vanuit twee kanten bereikbaar is, staan we hier meestal binnen 20 tot 30 minuten. In de smalle straten stopt de bezorger kort voor je deur en rijdt daarna meteen weer door.",
            "De Indische Buurt is een echte studentenbuurt met veel gedeelde huizen. Wij benaderen dat nuchter: er wordt uitsluitend geleverd aan personen van 18 jaar en ouder en de bezorger vraagt bij twijfel naar een identiteitsbewijs. Voor een huis met een paar bewoners is de <a href=\"/product/lachgas-tank-2kg/\">lachgastank 2KG</a> gangbaar, bij een groter huisfeest kies je op de assortimentpagina voor de 4KG. Betalen doe je op het moment van levering, contant of via Tikkie. Lees vooraf de pagina over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>, zeker als er veel mensen bij elkaar zijn.",
        ],
        "wijken": "Floresplein, Floresstraat, Javastraat, Sumatralaan, Molukkenstraat, Molukkenplantsoen, Bankastraat, Korreweg, Bedumerweg, Station Groningen Noord",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Wat is het verschil tussen jullie pagina’s Korrewegwijk en Indische Buurt?",
             "De Indische Buurt is een deel van de grotere Korrewegwijk. Voor de bezorging maakt het niet uit: beide hebben dezelfde indicatie en je bestelt op dezelfde manier via WhatsApp. Zie ook <a href=\"/bezorggebied/korrewegwijk/\">Lachgas Korrewegwijk</a>."],
            ["Ik deel een huis met zes anderen; wie moet er legitimatie laten zien?",
             "Degene die de tank aanneemt en betaalt moet 18 jaar of ouder zijn en dat bij twijfel kunnen aantonen. Zorg dus dat die persoon bij de deur staat als de bezorger er is."],
            ["Bezorgen jullie ook bij station Groningen Noord, als ik daar net aankom?",
             "Nee, we leveren niet op het station of op straat, alleen op een woonadres. Stuur je bestelling alvast vanuit de trein, dan zijn we er vaak kort nadat je thuis bent."],
        ],
        "nearby": ["korrewegwijk", "oosterparkwijk", "hortusbuurt"],
        "lat": 53.229, "lon": 6.570,
    },
    {
        "slug": "kostverloren", "name": "Kostverloren", "kind": "wijk",
        "title": "Lachgas Kostverloren | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bezorgen in Kostverloren in Groningen-West, tussen Schildersbuurt, Hoendiep en Reitdiep. Meestal binnen 20 tot 30 minuten aan de deur, alleen 18+.",
        "h1": "Lachgas Kostverloren",
        "lead": "Bezorging in Kostverloren, de kleine woonbuurt ten westen van de Schildersbuurt en de Westerhaven in Groningen.",
        "intro": [
            "Kostverloren is een kleine, compacte buurt aan de westkant van de stad Groningen. De buurt ligt tussen de Schildersbuurt aan de oostkant, het Hoendiep en de Aweg aan de zuidkant en de Friesestraatweg langs het Reitdiep aan de westkant. De vooroorlogse straten, zoals de Herman Colleniusstraat, liggen op een paar minuten lopen van de Westerhaven en op een kwartier van de Grote Markt. Wij bezorgen in heel Kostverloren. Bestellen kan door je adres en de gewenste tank via WhatsApp te sturen; je ontvangt dan de prijs en een bevestiging.",
            "Vanuit het centrum rijden we via de Aweg of de Kraneweg de buurt in, een rit van een paar minuten. Komen we van de westelijke ring, dan is de Friesestraatweg de kortste route. Bussen van en naar het Hoofdstation stoppen aan het Hoendiep en op de Westersingel, maar wij komen met de auto tot voor je deur. De korte afstand maakt dat we meestal binnen 20 tot 30 minuten bij je zijn. In de avonduren staan de straten vol geparkeerd, dus de bezorger stopt kort en loopt het laatste stuk.",
            "In Kostverloren wonen gezinnen en studenten gemengd in rijtjeshuizen en bovenwoningen. Een bestelling is hier vaak voor een verjaardag of een rustige avond met vrienden; de 2KG is dan het meest gekozen formaat, en voor een grotere groep vind je de 4KG en 10KG in ons <a href=\"/assortiment/\">assortiment</a>. Wij leveren uitsluitend aan 18+ en vragen bij twijfel om een geldig identiteitsbewijs. De betaling regel je aan de deur, contant of via Tikkie. Lees voor je bestelt de informatie over <a href=\"/lachgas-informatie/veilig-gebruik/\">veilig gebruik</a>.",
        ],
        "wijken": "Herman Colleniusstraat, Aweg, Westerhaven, Hoendiep, Friesestraatweg, Reitdiep, Kraneweg, Noorderplantsoen, Schildersbuurt",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Is Kostverloren niet gewoon de Schildersbuurt?",
             "Het zijn twee aparte buurten die direct aan elkaar grenzen; voor de bezorging maakt het geen verschil. Woon je net over de grens, dan kun je ook kijken op <a href=\"/bezorggebied/schildersbuurt/\">Lachgas Schildersbuurt</a>."],
            ["Kan ik in Kostverloren ook crackers en slagroompatronen laten bezorgen?",
             "Ja, naast de tanks bezorgen we ook crackers en slagroompatronen, los of samen met een tank. Zet in je bericht wat je wilt hebben, dan nemen we het in één rit mee."],
            ["Wat als niemand thuis is als de bezorger aankomt?",
             "Dan belt of appt de bezorger en wacht hij kort. Lukt het niet om te leveren, dan gaat de tank mee terug; we zetten nooit iets voor de deur, omdat we de leeftijd aan de deur controleren."],
        ],
        "nearby": ["schildersbuurt", "vinkhuizen", "binnenstad"],
        "lat": 53.2195, "lon": 6.544,
    },
]

HUBS = [
    {
        "slug": "noord-nederland", "name": "Groningen en Noord-Nederland",
        "title": "Lachgas bezorgen in Groningen en Noord-Nederland",
        "description": "Overzicht van ons bezorggebied: de stad Groningen, de dorpen eromheen, de provincie en Noord-Drenthe tot Friesland. Levertijden per zone, 18+.",
        "h1": "Lachgas bezorgen in Groningen en Noord-Nederland",
        "lead": "Vanuit de stad Groningen bezorgen we lachgastanks in de hele regio: van de binnenstad tot Delfzijl, Emmen en Drachten, met een levertijd die met de afstand meegroeit.",
        "intro": [
            "Ons bezorggebied begint in de stad Groningen. Alle wijken binnen en direct rond de ringweg horen erbij, van de Binnenstad en de Hortusbuurt tot Beijum, Lewenborg, Hoogkerk en de nieuwbouw in Meerstad en Reitdiep. Omdat onze bezorgers hier dagelijks rijden en elke wijk via de ring of een doorgaande weg bereikbaar is, staan we in de stad meestal binnen 20 tot 30 minuten voor de deur. Voor iedere wijk hebben we een eigen pagina met de buurten, de route en antwoorden op lokale vragen; je vindt ze hieronder onder Stad Groningen.",
            "Direct buiten de stad liggen de dorpen van het ommeland: Haren en Glimmen in het zuiden, Ten Boer, Bedum en Winsum in het noorden, Zuidhorn, Leek en Marum in het Westerkwartier en vlak over de provinciegrens de Noord-Drentse kernen Eelde-Paterswolde, Peize, Roden, Vries en Zuidlaren. De rit gaat hier deels over provinciale wegen en door dorpskernen, en soms wacht de bezorger voor een brug of een spoorwegovergang. Daarom rekenen we voor deze plaatsen op een levertijd van meestal 25 tot 40 minuten. Bij het bestellen hoor je direct welke indicatie op dat moment realistisch is.",
            "Verder weg in de provincie, in Hoogezand, Veendam, Stadskanaal, Winschoten, Oude Pekela, Appingedam, Delfzijl en Uithuizen, en in Drenthe en Friesland bij Assen, Beilen, Hoogeveen, Emmen en Drachten, gaat het om een langere rit over de A7, A28 of N33. Daar staan we meestal binnen 40 tot 60 minuten, en bij drukte zeggen we dat vooraf eerlijk. Bestellen werkt overal hetzelfde: je stuurt je adres en het gewenste formaat via WhatsApp, krijgt de prijs bevestigd en betaalt bij levering contant of via Tikkie. Hoe dat precies gaat, lees je bij onze <a href=\"/werkwijze/\">werkwijze</a>; de formaten staan in het <a href=\"/assortiment/\">assortiment</a>.",
        ],
        "groups": [
            {"h2": "Stad Groningen",
             "text": "Alle wijken binnen en direct rond de ringweg, plus Engelbert en Meerstad aan de oostkant: meestal binnen 20 tot 30 minuten.",
             "slugs": ["binnenstad", "hortusbuurt", "schildersbuurt", "kostverloren", "korrewegwijk", "indische-buurt", "oosterparkwijk", "oosterpoort", "rivierenbuurt", "helpman", "de-wijert", "hoornse-meer", "europapark", "paddepoel", "selwerd", "zernike", "vinkhuizen", "reitdiep", "hoogkerk", "beijum", "lewenborg", "meerstad", "engelbert", "corpus-den-hoorn", "de-hoogte", "oosterhoogebrug"]},
            {"h2": "Dorpen rond de stad",
             "text": "Het ommeland en de Noord-Drentse dorpen vlak over de provinciegrens, meestal binnen 25 tot 40 minuten.",
             "slugs": ["haren", "glimmen", "ten-boer", "bedum", "winsum", "zuidhorn", "leek", "marum", "eelde-paterswolde", "peize", "roden", "vries", "zuidlaren", "aduard", "tynaarlo"]},
            {"h2": "Provincie Groningen",
             "text": "De grotere plaatsen in het oosten en noorden van de provincie, meestal binnen 40 tot 60 minuten.",
             "slugs": ["hoogezand", "veendam", "stadskanaal", "oude-pekela", "winschoten", "appingedam", "delfzijl", "uithuizen", "loppersum"]},
            {"h2": "Drenthe en Friesland",
             "text": "Assen, Beilen, Hoogeveen, Emmen en Drachten: een langere rit vanuit de stad, meestal binnen 40 tot 60 minuten.",
             "slugs": ["assen", "beilen", "hoogeveen", "emmen", "drachten", "gieten"]},
        ],
        "faq": [
            ["Hoe hangt de levertijd samen met de afstand tot Groningen?",
             "Elke bestelling vertrekt vanuit de stad, dus hoe verder je woont, hoe langer de rit. In de stad is dat meestal 20 tot 30 minuten, in de dorpen eromheen 25 tot 40 en in de rest van de provincie en in Drenthe en Friesland 40 tot 60 minuten; de exacte zones staan op <a href=\"/bezorgtijden-groningen/\">bezorgtijden Groningen</a>."],
            ["Betaal ik extra voor bezorging buiten de stad?",
             "Voor plaatsen verder weg kunnen we een bijdrage in de rijkosten vragen; dat hangt af van de afstand en het formaat. Je hoort het vooraf in de WhatsApp-bevestiging, zodat er bij de deur geen verrassingen zijn."],
            ["Bezorgen jullie ’s nachts ook buiten Groningen?",
             "Ja, in de dorpen rond de stad vaak wel; voor de verder gelegen plaatsen bekijken we per bestelling of het die nacht haalbaar is. Hoe nachtbezorging werkt, lees je op <a href=\"/lachgas-nachtbezorging/\">lachgas nachtbezorging</a>."],
            ["Mijn woonplaats staat niet in de lijst. Komen jullie dan toch?",
             "Ligt je dorp tussen of vlak bij de genoemde plaatsen, dan meestal wel. Stuur je adres via WhatsApp en we laten weten of we kunnen komen en hoe lang het ongeveer duurt."],
            ["Is bezorgen in Drenthe of Friesland net zo snel als in Groningen?",
             "Nee, dat is het eerlijke antwoord: Assen, Emmen, Hoogeveen, Beilen en Drachten liggen een flink stuk rijden van de stad en we komen er meestal binnen 40 tot 60 minuten. We plannen die ritten goed en melden het vooraf als het die avond langer duurt."],
        ],
    },
]
