# -*- coding: utf-8 -*-
# Nieuwe plaatsen verder van Groningen, deel B (fase 3): Appingedam, Delfzijl, Emmen, Hoogeveen, Drachten, Beilen, Uithuizen, Oude Pekela.

AREAS = [
    {
        'slug': 'appingedam', 'name': 'Appingedam', 'kind': 'stad',
        'title': 'Lachgas Appingedam | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Appingedam? Lachgastanks, crackers en slagroompatronen bezorgd in Appingedam en Opwierde, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Appingedam',
        'lead': 'Lachgastanks aan de deur in Appingedam en de omliggende dorpen van Eemsdelta, besteld via WhatsApp en meestal binnen 40 tot 60 minuten geleverd.',
        'intro': [
            'Appingedam is een van de oudste stadjes van de provincie en vormt samen met Delfzijl en Loppersum de gemeente Eemsdelta. De binnenstad langs het Damsterdiep, met de bekende hangende keukens en de Nicolaïkerk, ligt op een kleine dertig kilometer ten oosten van Groningen. Wij bezorgen in de hele stad: in het centrum, in Opwierde ten zuiden van het spoor, in Olingermeeden en Oling, in Tjamsweer en Solwerd, en bij de bedrijven op Fivelpoort. Een bestelling plaats je via WhatsApp met je adres en de gewenste producten; wij antwoorden met de prijs en een realistische aankomsttijd.',
            'De kortste route vanuit de stad is de N360 via Ten Boer, een provinciale weg met rotondes en dorpskernen die niet overal snel rijdt. Als alternatief nemen onze bezorgers de A7 tot Zuidbroek en vervolgens de N33 noordwaarts, wat vooral buiten de spits tijd scheelt. Reken voor Appingedam op meestal 40 tot 60 minuten; de rit zelf duurt al ruim een half uur en daar komt het laden bovenop. Het station aan de lijn Groningen–Delfzijl ligt midden in de stad, maar wij leveren op je adres en niet op een perron. Bij werkzaamheden aan de N360 hoor je vooraf wat dat voor jouw bestelling betekent.',
            'Een verjaardag in Opwierde, een avond met vrienden aan het Damsterdiep of een feest in een loods buiten de stad: het formaat van de tank hangt af van het gezelschap en de duur. In het <a href="/assortiment/">assortiment</a> staan de tanks van 2KG, 4KG en 10KG beschreven, met daarnaast crackers en slagroompatronen die in dezelfde bestelling meegaan. Via WhatsApp bevestigen we de prijs vooraf; bij de deur betaal je contant of via Tikkie. Levering is uitsluitend aan volwassenen van 18 jaar of ouder en de bezorger kan naar je identiteitsbewijs vragen. Onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> is het lezen waard voordat je bestelt.',
        ],
        'wijken': 'Centrum, Damsterdiep, Opwierde, Olingermeeden, Oling, Tjamsweer, Solwerd, Fivelpoort, Marsum, Station Appingedam',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Tjamsweer, Solwerd en bij Fivelpoort?', 'Ja, alle buurten en buurtschappen van Appingedam vallen onder dezelfde zone, net als het bedrijvenpark Fivelpoort tussen Appingedam en Delfzijl. Vermeld bij een bedrijfsadres ook de naam van het bedrijf of de loods, dan vindt de bezorger de juiste ingang.'],
            ['Kan de bezorging in Appingedam gecombineerd worden met Delfzijl?', 'Dat gebeurt regelmatig: Delfzijl ligt nog geen tien minuten verder over de N360, dus een bezorger neemt vaak beide plaatsen in één rit mee. Voor jou verandert er niets aan de afspraak, hoogstens zit je aan het begin of het einde van die rit.'],
            ['Hoe weet ik hoe laat jullie in Appingedam aankomen?', 'Je krijgt bij de bevestiging een tijdsindicatie die rekening houdt met de rit vanuit Groningen en de bestellingen die al onderweg zijn. Loopt het uit door verkeer op de N360 of de N33, dan sturen we een bericht. Zie ook onze uitleg over <a href="/bezorgtijden-groningen/">bezorgtijden per zone</a>.'],
        ],
        'nearby': ['delfzijl', 'ten-boer', 'uithuizen'],
        'lat': 53.321, 'lon': 6.858,
    },
    {
        'slug': 'delfzijl', 'name': 'Delfzijl', 'kind': 'stad',
        'title': 'Lachgas Delfzijl | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Delfzijl? Lachgastanks, crackers en slagroompatronen bezorgd in Delfzijl, Farmsum en Tuikwerd, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Delfzijl',
        'lead': 'Lachgastanks thuisbezorgd in de havenstad Delfzijl en de dorpen langs de Eems: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten aan de deur.',
        'intro': [
            'Delfzijl is de havenstad van de gemeente Eemsdelta, aan de monding van de Eems en met zicht op de Duitse oever. De stad heeft een compact centrum met de wijk Over de Gracht, daaromheen Delfzijl-Noord en Delfzijl-West, de wijk Tuikwerd en het oude dorp Farmsum bij de zeesluizen. Ons bezorggebied omvat al die wijken en ook Uitwierde, Biessum, Meedhuizen en Wagenborgen. Je bestelt met een WhatsApp-bericht waarin je adres, de producten en eventueel een gewenst tijdstip staan; wij bevestigen alles in één reactie, inclusief de prijs.',
            'Delfzijl is voor ons een van de verste bestemmingen in de provincie: zo’n dertig kilometer over de N360 door Ten Boer en Appingedam, of via de A7 en de N33 die bij Farmsum de stad binnenkomt. Daarom geldt hier meestal 40 tot 60 minuten, en bij veel bestellingen tegelijk kan het richting de bovenkant van die marge gaan. De treinen uit Groningen eindigen op station Delfzijl, met een tussenstop op Delfzijl West; de bezorger komt echter tot aan je voordeur, ook bij de Marina en op de boulevard. We geven bij de bevestiging altijd aan hoe druk het op dat moment is.',
            'Een avond met collega’s uit de haven, een verjaardag in Tuikwerd of een feest in een dorpshuis in Wagenborgen vraagt elk om een ander formaat. Vergelijk in het <a href="/assortiment/">assortiment</a> de tank van 2KG met de 4KG en de 10KG; crackers en slagroompatronen leveren we in dezelfde rit mee. De prijs staat vast zodra we die in WhatsApp hebben bevestigd, en afrekenen doe je contant of via Tikkie bij de deur. We bezorgen niet aan minderjarigen en controleren bij twijfel de leeftijd. Lees voor je bestelt ook de informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Centrum, Over de Gracht, Delfzijl-Noord, Delfzijl-West, Tuikwerd, Farmsum, Uitwierde, Biessum, Meedhuizen, Wagenborgen',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Komen jullie ook in Farmsum, Wagenborgen en Termunten?', 'Farmsum en Meedhuizen liggen direct tegen de stad en vallen onder dezelfde levertijd. Wagenborgen, Woldendorp en Termunten liggen verder naar het zuidoosten; we bezorgen daar wel, maar de rit kan dan iets langer duren dan de indicatie voor Delfzijl zelf.'],
            ['Bezorgen jullie in Delfzijl ook laat in de avond en ’s nachts?', 'Ja, de rit naar Delfzijl rijden we op elk moment van de dag, al kan de bezorger ’s nachts eerst een adres in Appingedam of Hoogezand afwerken. Op de pagina over <a href="/lachgas-nachtbezorging/">nachtbezorging</a> staat hoe dat in de praktijk gaat.'],
            ['Wat als ik op een boot in de Marina of op een bedrijventerrein ben?', 'Dat kan, zolang de locatie met de auto bereikbaar is en jij er zelf bent om aan te nemen. Stuur de naam van de jachthaven of het bedrijf plus een omschrijving van de ingang; op afgesloten industrieterreinen zoals Oosterhorn spreken we een punt bij de toegang af.'],
        ],
        'nearby': ['appingedam', 'uithuizen', 'veendam'],
        'lat': 53.330, 'lon': 6.922,
    },
    {
        'slug': 'emmen', 'name': 'Emmen', 'kind': 'stad',
        'title': 'Lachgas Emmen | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Emmen? Lachgastanks, crackers en slagroompatronen bezorgd in Emmen, Angelslo en Bargeres, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Emmen',
        'lead': 'Lachgastanks bezorgd in Emmen, de grootste plaats van Zuidoost-Drenthe: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten vanuit Groningen geleverd.',
        'intro': [
            'Emmen is met ruim vijftigduizend inwoners de grootste plaats van Zuidoost-Drenthe, gelegen op het zuidelijke eind van de Hondsrug. Het centrum rond de Hoofdstraat en het Raadhuisplein grenst aan het Rensenpark, waar vroeger de dierentuin zat, en aan Wildlands aan de westkant. Wij bezorgen in alle wijken: Emmermeer en Emmerschans in het noorden, Angelslo en Emmerhout in het oosten, Bargeres en Rietlanden in het zuidwesten, Delftlanden en Parc Sandur daarbuiten. Stuur je adres en de producten via WhatsApp en je ontvangt direct een bevestiging met prijs en tijdsindicatie.',
            'Emmen ligt zo’n zestig kilometer van Groningen en is daarmee de zuidelijkste plaats in ons werkgebied. De bezorger rijdt de A28 tot De Punt of Assen en dan de N34 over de Hondsrug via Gieten, Borger en Odoorn de stad in; de rit alleen kost al dicht bij een uur. Wij hanteren daarom meestal 40 tot 60 minuten als indicatie, en we zeggen eerlijk dat die bij drukte of winterweer wordt overschreden. Emmen heeft twee stations, Emmen en Emmen Zuid, aan de lijn uit Zwolle; met Groningen is er geen directe trein. Je hoort bij de bevestiging of de bezorger al richting Drenthe rijdt.',
            'Een huisfeest bij het station, een verjaardag in Rietlanden of een weekend op een vakantiepark bij Parc Sandur: het gezelschap bepaalt het formaat. In het <a href="/assortiment/">assortiment</a> staan de 2KG, 4KG en 10KG naast elkaar, met crackers en slagroompatronen als aanvulling. Omdat de rit lang is, loont het om vooraf met je gezelschap af te stemmen wat er besteld wordt, zodat we niet twee keer hoeven te rijden. Betalen gaat contant of via Tikkie aan de deur, tegen de vooraf bevestigde prijs. Wij leveren uitsluitend aan 18-plussers en vragen zo nodig een legitimatie. Bekijk ook onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Centrum, Emmermeer, Emmerschans, Angelslo, Emmerhout, Bargeres, Rietlanden, Delftlanden, Parc Sandur, Noordbarge',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Klazienaveen, Nieuw-Amsterdam en Erica?', 'Die dorpen horen bij de gemeente Emmen en liggen op tien tot vijftien minuten rijden van het centrum. We komen er wel, maar omdat de rit vanuit Groningen al lang is, kan de levertijd daar boven de indicatie voor Emmen uitkomen. Vraag het vooraf in WhatsApp.'],
            ['Waarom is Emmen een van de langste ritten vanuit Groningen?', 'Er is geen snelweg die Groningen en Emmen rechtstreeks verbindt; de bezorger rijdt de A28 en daarna de N34, een provinciale weg zonder snelwegtempo. Dat is zo’n zestig kilometer enkele reis, waardoor Emmen aan de rand van ons gebied zit. In het overzicht van <a href="/bezorggebied/noord-nederland/">Groningen en Noord-Nederland</a> zie je hoe de zones lopen.'],
            ['Kan ik in Emmen ook in het weekend of op een feestdag bestellen?', 'Ja, we rijden ook in het weekend naar Drenthe, al zijn vrijdag- en zaterdagavond de drukste momenten en kan de rit dan langer duren. Geef in je bericht aan of een bepaald tijdstip belangrijk is, dan plannen we daarop.'],
        ],
        'nearby': ['beilen', 'hoogeveen', 'stadskanaal'],
        'lat': 52.785, 'lon': 6.897,
    },
    {
        'slug': 'hoogeveen', 'name': 'Hoogeveen', 'kind': 'stad',
        'title': 'Lachgas Hoogeveen | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Hoogeveen? Lachgastanks, crackers en slagroompatronen bezorgd in Hoogeveen en Krakeel, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Hoogeveen',
        'lead': 'Lachgastanks aan de deur in Hoogeveen, langs de A28 in Zuid-Drenthe: besteld via WhatsApp en meestal binnen 40 tot 60 minuten vanuit Groningen bezorgd.',
        'intro': [
            'Hoogeveen ligt in het zuiden van Drenthe, waar de A37 op de A28 aansluit, en is uitgegroeid van veenkolonie tot een stad met een lange Hoofdstraat als winkelas en theater De Tamboer als middelpunt. Wij bezorgen in het centrum en in de woonwijken Krakeel, Wolfsbos, De Weide, Erflanden, Kinholt, Trasselt en Schutlanden, en ook in de omliggende dorpen Hollandscheveld, Pesse, Fluitenberg en Noordscheschut. Bestellen doe je door een WhatsApp-bericht te sturen met je adres en wat je wilt ontvangen; je krijgt de prijs en de verwachte aankomsttijd terug.',
            'Vanuit Groningen is Hoogeveen bijna helemaal snelweg: de A28 zuidwaarts langs Assen en Beilen tot de afslagen bij Hoogeveen, een rit van ruim zestig kilometer. Dankzij de snelweg rijdt dat vlot, maar het blijft een van de langste trajecten die wij rijden, en daarom geldt hier meestal 40 tot 60 minuten. In de avondspits rond Assen en bij werkzaamheden op de A28 kan het langer duren; dat zeggen we er dan bij. Station Hoogeveen ligt aan de spoorlijn Zwolle–Groningen, maar wij bezorgen aan de deur en komen ook in de buitendorpen langs de Hoogeveense Vaart.',
            'Een huisfeest in Erflanden, een verjaardag in Wolfsbos of een weekend met vrienden op een camping bij Pesse: kies het formaat dat bij het gezelschap past. Het <a href="/assortiment/">assortiment</a> toont de verschillen tussen de tank van 2KG, 4KG en 10KG, en je kunt crackers en slagroompatronen aan dezelfde bestelling toevoegen. Je rekent af bij levering, contant of via Tikkie, tegen de prijs die vooraf in WhatsApp is afgesproken. Levering is er alleen voor wie 18 jaar of ouder is; houd je identiteitsbewijs bij de hand. Lees vooraf ook onze toelichting over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Centrum, Hoofdstraat, Krakeel, Wolfsbos, De Weide, Erflanden, Kinholt, Trasselt, Schutlanden, Hollandscheveld',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Hollandscheveld, Pesse en Nieuwlande?', 'Ja, de dorpen van de gemeente Hoogeveen nemen we mee, al liggen Nieuwlande en Elim een stuk zuidelijker dan de stad. Vermeld je dorp duidelijk in het bericht, dan houden we daar in de tijdsindicatie rekening mee.'],
            ['Hoe lang is de rit van Groningen naar Hoogeveen echt?', 'Over de A28 is het ruim zestig kilometer, ongeveer drie kwartier rijden zonder oponthoud. Omdat de bezorger ook moet laden en soms eerst een adres in Assen of Beilen heeft, komen we uit op meestal 40 tot 60 minuten. Een overzicht van alle zones staat bij <a href="/bezorgtijden-groningen/">bezorgtijden</a>.'],
            ['Kan ik met spoed bestellen in Hoogeveen?', 'Spoed is in Hoogeveen beperkt mogelijk: de afstand bepaalt de ondergrens van de levertijd. Geef in je bericht aan dat het haast heeft, dan laten we direct weten of een bezorger al in Drenthe rijdt en wat de snelste realistische tijd is.'],
        ],
        'nearby': ['beilen', 'emmen', 'assen'],
        'lat': 52.722, 'lon': 6.476,
    },
    {
        'slug': 'drachten', 'name': 'Drachten', 'kind': 'stad',
        'title': 'Lachgas Drachten | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Drachten? Lachgastanks, crackers en slagroompatronen bezorgd in Drachten en De Wiken, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Drachten',
        'lead': 'Lachgastanks thuisbezorgd in Drachten en de dorpen van Smallingerland: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten over de A7 vanuit Groningen.',
        'intro': [
            'Drachten is de grootste plaats van de Friese gemeente Smallingerland en de eerste Friese bestemming die wij vanuit Groningen bedienen. De stad groeide na de komst van Philips snel en kent een centrum met De Lawei, Museum Dr8888 en de heropende Drachtstervaart. Wij bezorgen in alle wijken, van De Wiken, De Venen en De Singels tot De Drait, De Trisken, Himsterhout, Fennepark en De Folgeren, en ook in Opeinde, Rottevalle, Boornbergum en Oudega. Een bestelling begint met een WhatsApp-bericht; daarin zet je het adres en de producten, en wij antwoorden met prijs en tijd.',
            'De route is eenvoudig: de A7 westwaarts via Hoogkerk, langs Leek en Marum, over de provinciegrens bij Frieschepalen en dan de afslag Drachten. Dat is ongeveer veertig kilometer snelweg, waardoor Drachten ondanks de afstand goed te doen is; wij houden meestal 40 tot 60 minuten aan. Drachten staat bekend als de grootste plaats van Nederland zonder treinstation, en de Qliner-bussen vanaf het Groninger Hoofdstation stoppen op het Van Knobelsdorffplein. Voor onze bezorging maakt dat niet uit: we komen tot aan je deur. Bij een file op de A7 rond Hoogkerk melden we vooraf dat het later wordt.',
            'Een feest in een rijtjeshuis in De Wiken, een verjaardag in Himsterhout of een avond aan het water bij De Veenhoop: per gelegenheid past een ander formaat. Het <a href="/assortiment/">assortiment</a> beschrijft de lachgastank van 2KG, 4KG en 10KG en de bijpassende crackers en slagroompatronen. De prijs bevestigen we vooraf in WhatsApp, zodat er bij de deur geen verrassingen zijn; betalen kan contant of via Tikkie. We leveren niet aan personen onder de 18 en controleren dat waar nodig. Neem voor je bestelt de pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> door.',
        ],
        'wijken': 'Centrum, De Wiken, De Venen, De Singels, De Drait, De Trisken, Himsterhout, Fennepark, De Folgeren, Opeinde',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Ureterp, Beetsterzwaag en Burgum?', 'Ureterp ligt vlak naast Drachten aan de A7 en nemen we mee. Beetsterzwaag en Burgum liggen verder van onze route af; vraag het vooraf via WhatsApp, dan kijken we of het die dag past en wat de tijd wordt.'],
            ['Is Drachten niet te ver voor bezorging vanuit Groningen?', 'Het is een van onze verste bestemmingen, maar de A7 maakt de rit voorspelbaar: ongeveer veertig kilometer zonder dorpskernen onderweg. Daarom valt Drachten in dezelfde zone als Emmen en Hoogeveen, met meestal 40 tot 60 minuten. Meer over de opbouw van de zones lees je bij <a href="/bezorgtijden-groningen/">bezorgtijden</a>.'],
            ['Kan ik in Drachten contant betalen of alleen via Tikkie?', 'Beide kan. De bezorger neemt een Tikkie-link mee voor wie liever digitaal betaalt, en contant geld is net zo goed welkom. De prijs is in alle gevallen vooraf in WhatsApp vastgelegd, zodat je precies weet wat je bij de deur afrekent.'],
        ],
        'nearby': ['marum', 'leek', 'zuidhorn'],
        'lat': 53.112, 'lon': 6.099,
    },
    {
        'slug': 'beilen', 'name': 'Beilen', 'kind': 'dorp',
        'title': 'Lachgas Beilen | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Beilen? Lachgastanks, crackers en slagroompatronen bezorgd in Beilen en Nagtegael, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Beilen',
        'lead': 'Lachgastanks aan de deur in Beilen, het hart van Midden-Drenthe aan de A28: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten geleverd.',
        'intro': [
            'Beilen is de hoofdplaats van de gemeente Midden-Drenthe en ligt halverwege Assen en Hoogeveen, pal naast de A28. Het dorp heeft een compact centrum rond de Brinkstraat, de nieuwbouwwijk Nagtegael aan de westkant en de zuivelfabriek als grote werkgever. Wij bezorgen in het hele dorp en in de buurtschappen Lieving, Holthe, Brunsting, Klatering en Ter Horst, en verder in Hijken, Wijster, Spier en Hooghalen. Bestellen gaat via WhatsApp: stuur je adres en de gewenste producten, dan ontvang je de prijs en een inschatting van de aankomsttijd.',
            'De bezorger rijdt vanuit Groningen de A28 richting Zwolle, passeert Assen en neemt de afslag Beilen; dat is ongeveer vijfenveertig kilometer en in rustige uren ruim een half uur rijden. Met laden en de kans dat er eerst in Assen wordt bezorgd, komen we voor Beilen uit op meestal 40 tot 60 minuten. Het station aan de lijn Groningen–Zwolle ligt aan de oostkant van het dorp, maar de levering gaat naar je adres en niet naar de perrons. Bij winterweer op de A28 of drukte rond Assen hoor je vooraf een aangepaste tijd.',
            'Een verjaardag in Nagtegael, een avond met vrienden in een boerderij bij Lieving of een feest in een dorpshuis in Hijken: het gezelschap bepaalt het formaat. In het <a href="/assortiment/">assortiment</a> zie je de tank van 2KG, 4KG en 10KG met uitleg, en ook crackers en slagroompatronen kun je toevoegen. De prijs wordt vooraf in WhatsApp bevestigd en je betaalt bij de deur, contant of via Tikkie. Wij leveren alleen aan meerderjarigen en kunnen om een geldig identiteitsbewijs vragen. Op de pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> staat waar je rekening mee houdt.',
        ],
        'wijken': 'Centrum, Brinkstraat, Nagtegael, Lieving, Holthe, Brunsting, Klatering, Ter Horst, Hijken, Wijster',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Westerbork, Hooghalen en Spier?', 'Ja, die dorpen horen bij Midden-Drenthe en liggen op korte afstand van Beilen. Westerbork is zo’n tien minuten verder naar het oosten, Spier ligt aan de A28 ten zuiden van het dorp; de indicatie kan daar iets afwijken van die voor Beilen zelf.'],
            ['Waarom valt Beilen in de zone van 40 tot 60 minuten en Assen niet?', 'Beilen ligt een kwartier voorbij Assen op de A28, en elke extra kilometer telt mee in de rit vanuit Groningen. Daarom zit Beilen in dezelfde zone als Hoogeveen en Emmen. De pagina over <a href="/bezorggebied/assen/">Assen</a> laat zien hoe de tijd daar korter uitvalt.'],
            ['Kunnen jullie op een vakantiepark of camping bij Beilen leveren?', 'Dat kan, zolang je ons het adres of de naam van het park en het nummer van de plek doorgeeft. De bezorger komt tot aan de slagboom of de receptie als het terrein niet vrij toegankelijk is; spreek dat in WhatsApp af.'],
        ],
        'nearby': ['assen', 'hoogeveen', 'emmen'],
        'lat': 52.861, 'lon': 6.517,
    },
    {
        'slug': 'uithuizen', 'name': 'Uithuizen', 'kind': 'dorp',
        'title': 'Lachgas Uithuizen | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Uithuizen? Lachgastanks, crackers en slagroompatronen bezorgd in Uithuizen en Roodeschool, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Uithuizen',
        'lead': 'Lachgastanks bezorgd in Uithuizen en de dorpen op het Hogeland bij de Eemshaven: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten aan de deur.',
        'intro': [
            'Uithuizen is een van de grotere dorpen in het noorden van de gemeente Het Hogeland, bekend van de Menkemaborg met zijn tuinen en van de treinhalte aan de lijn naar Roodeschool. Het dorp ligt op een kleine vijfentwintig kilometer van Groningen, met de Eemshaven en de Waddenkust vlak ten noorden. Wij bezorgen in het centrum rond de Hoofdstraat, in de woonbuurten daaromheen en in de omliggende dorpen Uithuizermeeden, Roodeschool, Usquert, Kantens, Zandeweer en Oosternieland. Je bestelt via WhatsApp door je adres en de producten te sturen; de bevestiging bevat de prijs en de verwachte tijd.',
            'Twee routes leiden vanuit de stad naar Uithuizen: de N46 (Eemshavenweg) via Bedum en Middelstum met daarna de N363, of de N361 door Winsum en Warffum naar Usquert. Beide zijn provinciale wegen met rotondes en dorpen onderweg, en samen met het laden en de terugrit komen we daarom op meestal 40 tot 60 minuten. Wie met de trein uit Groningen komt, stapt uit op station Uithuizen; wij bezorgen op het adres dat je opgeeft, ook op de buitenwegen richting Oudeschip en de Eemshaven. Als de bezorger eerst een adres in Bedum of Winsum heeft, zeggen we dat bij de bevestiging.',
            'Een feest in een schuur buiten het dorp, een verjaardag in Uithuizermeeden of een avond met collega’s die bij de Eemshaven werken: de keuze van het formaat hangt af van het aantal mensen en de duur. Kijk in het <a href="/assortiment/">assortiment</a> naar de 2KG, 4KG en 10KG tanks en de bijbehorende crackers en slagroompatronen. We bevestigen de prijs vooraf in WhatsApp; afrekenen doe je bij de deur, contant of via Tikkie. Levering uitsluitend aan 18 jaar en ouder, met een leeftijdscontrole als de bezorger twijfelt. Onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> lees je het best voordat je bestelt.',
        ],
        'wijken': 'Centrum, Hoofdstraat, Menkemaborg, Station Uithuizen, Uithuizermeeden, Roodeschool, Usquert, Kantens, Zandeweer, Oosternieland',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Komen jullie ook in Roodeschool, Oudeschip en bij de Eemshaven?', 'Ja, de dorpen ten noorden en oosten van Uithuizen nemen we mee in dezelfde rit. Voor de Eemshaven geldt dat we alleen op adressen leveren die met de auto bereikbaar zijn; geef de naam van het bedrijf of de kade door, dan plannen we een afspreekpunt.'],
            ['Waarom is Uithuizen 40 tot 60 minuten en Winsum korter?', 'Winsum ligt op ongeveer de helft van de route en heeft een directere weg vanuit de stad. Naar Uithuizen rijdt de bezorger verder door over de N46 of de N361 en de N363, met meer dorpen en rotondes onderweg. Vergelijk het gerust met de pagina over <a href="/bezorggebied/winsum/">Winsum</a>.'],
            ['Kan ik ook ’s avonds laat in Uithuizen bestellen?', 'Ja, we rijden ook in de avond en nacht naar het Hogeland. Houd er rekening mee dat de wegen dan rustig zijn maar de bezorger soms vanaf een ander adres in de provincie komt; de tijdsindicatie bij je bevestiging is daarop aangepast.'],
        ],
        'nearby': ['winsum', 'bedum', 'appingedam'],
        'lat': 53.410, 'lon': 6.673,
    },
    {
        'slug': 'oude-pekela', 'name': 'Oude Pekela', 'kind': 'dorp',
        'title': 'Lachgas Oude Pekela | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Oude Pekela? Lachgastanks, crackers en slagroompatronen bezorgd in Oude en Nieuwe Pekela, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Oude Pekela',
        'lead': 'Lachgastanks aan de deur in Oude Pekela en de rest van de gemeente Pekela: bestellen via WhatsApp, meestal binnen 40 tot 60 minuten vanuit Groningen geleverd.',
        'intro': [
            'Oude Pekela is een langgerekt veenkoloniaal dorp langs de Pekel Aa, in het oosten van de provincie tussen Winschoten en Stadskanaal. Samen met Nieuwe Pekela vormt het de gemeente Pekela, waarvan het gemeentehuis aan de Raadhuislaan staat. Het dorp is gebouwd rond de Feiko Clockstraat en de Hendrik Westerstraat, met de voormalige strokartonfabrieken als herinnering aan de industrie van vroeger. Wij bezorgen in heel Oude Pekela, in Boven Pekela, in Nieuwe Pekela en in Blijham. Bestellen doe je via WhatsApp met je adres en de gewenste producten; je krijgt de prijs en een tijdsindicatie terug.',
            'De bezorger rijdt vanuit Groningen de A7 naar het oosten tot de afslag Winschoten en vervolgt over de N367 naar Oude Pekela, een rit van ongeveer vijfenveertig kilometer. Een alternatief is de N33 via Veendam en de N366 door Nieuwe Pekela, handig als er al een adres in Veendam op de route staat. Door de afstand en het laatste stuk over provinciale wegen hanteren we hier meestal 40 tot 60 minuten. Pekela heeft geen eigen station; de trein uit Groningen stopt in Winschoten en rijdt door naar Bad Nieuweschans. Onze bezorger komt in elk geval tot aan de deur.',
            'Een verjaardag aan het Pekelder Hoofddiep, een avond met vrienden in een rijtjeshuis of een feest in een schuur richting Blijham: per situatie past een andere tank. Vergelijk in het <a href="/assortiment/">assortiment</a> de 2KG, 4KG en 10KG en voeg eventueel crackers en slagroompatronen toe. De prijs staat vooraf vast in het WhatsApp-gesprek en je betaalt bij levering, contant of via Tikkie. Wij bezorgen uitsluitend aan volwassenen van 18 jaar of ouder en controleren dat met een identiteitsbewijs als dat nodig is. Lees ook onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Feiko Clockstraat, Hendrik Westerstraat, Raadhuislaan, Pekelder Hoofddiep, Boven Pekela, Nieuwe Pekela, Heeresmeer, Blijham',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Nieuwe Pekela en Blijham?', 'Ja, Nieuwe Pekela ligt in het verlengde van Oude Pekela langs hetzelfde diep en Blijham ligt een paar kilometer naar het oosten. Beide dorpen vallen onder dezelfde indicatie; zet de plaatsnaam er duidelijk bij, omdat straatnamen in beide Pekela’s op elkaar lijken.'],
            ['Waarom duurt het in Oude Pekela langer dan in Winschoten?', 'Winschoten ligt direct aan de A7; voor Oude Pekela rijdt de bezorger daarna nog een kwartier door over de N367. Dat extra stuk, plus het laden in Groningen, maakt dat we hier meestal 40 tot 60 minuten aanhouden. De pagina over <a href="/bezorggebied/winschoten/">Winschoten</a> laat het verschil zien.'],
            ['Kan ik een bestelling voor een feest in Oude Pekela vooraf vastleggen?', 'Ja, stuur ons een paar uur van tevoren of een dag eerder een bericht met het adres, de producten en het gewenste tijdstip. We plannen de rit dan in en bevestigen de afspraak; bij wijzigingen laat je het via hetzelfde gesprek weten.'],
        ],
        'nearby': ['winschoten', 'veendam', 'stadskanaal'],
        'lat': 53.105, 'lon': 7.010,
    },
]
