# -*- coding: utf-8 -*-
# Herschreven bezorggebieden lachgasgroningen.nl (fase 3): bestaande slugs, volledig nieuwe tekst.

AREAS = [
    {
        "slug": "binnenstad",
        "name": "Binnenstad",
        "kind": "wijk",
        "title": """Lachgas Binnenstad | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Binnenstad? Bezorgd via WhatsApp rond de Grote Markt, de Vismarkt en het Hoofdstation, meestal binnen 20 tot 30 minuten. Alleen 18+.""",
        "h1": """Lachgas Binnenstad""",
        "lead": """Bezorging binnen de Diepenring en rond het Hoofdstation, van de Grote Markt tot het Zuiderdiep, besteld via WhatsApp.""",
        "intro": [
            """De binnenstad van Groningen is het gebied binnen de Diepenring: van de Grote Markt met de Martinitoren en het Forum tot de Vismarkt, de A-kerk en het Gedempte Zuiderdiep. Wij bezorgen in alle straten daartussen, van de Oosterstraat en de Poelestraat tot de Oude Kijk in ’t Jatstraat, de Folkingestraat en de kades langs de Noorderhaven. Bestellen gaat via WhatsApp: je stuurt je adres, de etage en welke bel we moeten gebruiken, en je krijgt direct een bevestiging terug. Voor woningen boven winkels en cafés is die laatste informatie onmisbaar.""",
            """Omdat een groot deel van de binnenstad autoluw is, rijden onze bezorgers over de Diepenring of het Gedempte Zuiderdiep en leggen ze het laatste stuk te voet af, of ze komen op de fiets. Vanaf het Hoofdstation sta je via de Herestraat in een paar minuten op de Grote Markt, en zo kort zijn onze afstanden hier ook. Daardoor zijn we in de binnenstad meestal binnen 20 tot 30 minuten bij je. Op uitgaansavonden rond de Poelestraat en de Peperstraat en tijdens de KEI-week is het vol in de straten; dat kan de levertijd iets oprekken en dat hoor je vooraf via WhatsApp.""",
            """Een huisfeest in een studentenhuis aan de Nieuwe Ebbingestraat, een verjaardag op een bovenverdieping aan de Vismarkt of een avond met vrienden voordat jullie de stad in gaan: bekijk het <a href="/assortiment/">assortiment</a> en kies een tank die past bij de grootte van je gezelschap en de ruimte die je hebt. In een krappe bovenwoning is een compacte tank praktischer dan een grote. Je betaalt contant of via Tikkie bij levering; de prijs bevestigen we vooraf via WhatsApp. We leveren uitsluitend aan 18+ en kunnen om een geldig ID vragen. Lees voor je begint onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": """Grote Markt, Vismarkt, Gedempte Zuiderdiep, Poelestraat, Oosterstraat, Folkingestraat, Oude Kijk in ’t Jatstraat, Noorderhaven, Hoofdstation""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Bezorgen jullie ook op een bovenwoning in de binnenstad zonder eigen bel?""", """Ja. Veel woningen boven winkels en cafés delen één voordeur. Zet in je bericht op welke verdieping je woont en welke bel of naam we moeten hebben, of kom even naar beneden zodra we melden dat we er zijn. Zo blijft de overdracht kort en onopvallend."""],
            ["""Kunnen jullie met de auto tot aan mijn deur komen in het voetgangersgebied?""", """Niet overal, want een groot deel van de binnenstad is autoluw. Onze bezorgers parkeren aan de Diepenring of het Gedempte Zuiderdiep en lopen het laatste stuk, dus een adres in de Herestraat of op de Vismarkt is geen probleem."""],
            ["""Mag ik met een lachgastank over straat richting de Grote Markt?""", """In Groningen gelden lokale regels voor lachgas in de openbare ruimte en daar kan op gehandhaafd worden. Houd het gebruik daarom binnen, op je eigen adres, en bekijk de actuele regels op <a href="https://gemeente.groningen.nl">gemeente.groningen.nl</a>."""],
        ],
        "nearby": ["hortusbuurt", "schildersbuurt", "oosterpoort"],
        "lat": 53.219,
        "lon": 6.568,
    },
    {
        "slug": "korrewegwijk",
        "name": "Korrewegwijk",
        "kind": "wijk",
        "title": """Lachgas Korrewegwijk | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Korrewegwijk? Via WhatsApp bezorgd rond de Korreweg, het Floresplein en De Hoogte, meestal binnen 20 tot 30 minuten. Alleen voor 18+.""",
        "h1": """Lachgas Korrewegwijk""",
        "lead": """Van het Floresplein tot De Hoogte: in de Korrewegwijk bezorgen we snel, discreet en na een berichtje via WhatsApp.""",
        "intro": [
            """De Korrewegwijk ligt direct ten noorden van de Diepenring, tussen het Boterdiep, de Bedumerweg en het Oosterhamrikkanaal. De wijk dankt zijn naam aan de Korreweg, de lange straat die vanaf de Ebbingebrug naar de Gerrit Krolbrug over het Van Starkenborghkanaal loopt. Wij bezorgen in de hele wijk: rond het Floresplein en het Bernoulliplein, in de straten van de Indische buurt, in De Hoogte en langs de Oosterhamrikkade. Je bestelt door ons een WhatsApp-bericht te sturen met je straat, huisnummer en eventueel de etage; wij bevestigen en gaan op weg.""",
            """Onze bezorgers rijden vanuit het centrum via de Korreweg of de Oosterhamrikkade de wijk in, en vanaf de noordelijke ringweg via de Bedumerweg. Die korte lijnen maken de Korrewegwijk een van de snelste delen van ons bezorggebied, meestal binnen 20 tot 30 minuten. Het UMCG ligt aan de overkant van het Oosterhamrikkanaal en station Groningen Noord aan de rand van De Hoogte, dus de wijk is ook met het openbaar vervoer goed ontsloten. Dat merken wij vooral op doordeweekse avonden, wanneer de straten rond het Floresplein rustig zijn en we vlot kunnen doorrijden.""",
            """De Korrewegwijk is een echte studentenwijk met veel gedeelde woningen en etages boven elkaar. Voor een avond met huisgenoten past een kleinere tank uit ons <a href="/assortiment/">assortiment</a> meestal het beste; voor een groter huisfeest ligt de 4KG meer voor de hand. Je betaalt contant of via Tikkie bij levering, na een prijsbevestiging vooraf via WhatsApp. We leveren alleen aan 18+ en vragen bij twijfel naar een geldig identiteitsbewijs. Denk aan je buren in de smalle straten en lees onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> voordat de tank opengaat.""",
        ],
        "wijken": """Korreweg, Floresplein, Bernoulliplein, Indische buurt, De Hoogte, Oosterhamrikkade, Molukkenstraat, Station Groningen Noord, Gerrit Krolbrug""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""We wonen met zes huisgenoten aan de Korreweg; wie moet er aan de deur komen?""", """De persoon die de bestelling aanneemt moet 18 jaar of ouder zijn en kan om een ID gevraagd worden, dus laat de besteller zelf opendoen. Hoe we dat aanpakken staat op onze pagina over <a href="/leeftijdscontrole-18-plus/">leeftijdscontrole</a>."""],
            ["""Bezorgen jullie ook in De Hoogte, aan de andere kant van de Bedumerweg?""", """Ja. De Hoogte hoort bij de Korrewegwijk en ligt voor onze bezorgers op dezelfde route, dus daar geldt dezelfde indicatie van 20 tot 30 minuten. Zet je volledige adres in je bericht en we komen langs."""],
            ["""Hoe laat kan ik in de Korrewegwijk nog bestellen?""", """We zijn ook in de late uren bereikbaar via WhatsApp. Stuur je bericht, dan hoor je meteen of we kunnen komen en hoe lang het ongeveer duurt. De details staan op onze pagina over <a href="/lachgas-nachtbezorging/">nachtbezorging</a>."""],
        ],
        "nearby": ["indische-buurt", "binnenstad", "selwerd"],
        "lat": 53.230,
        "lon": 6.578,
    },
    {
        "slug": "oosterpoort",
        "name": "Oosterpoort",
        "kind": "wijk",
        "title": """Lachgas Oosterpoort | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Oosterpoort? Bezorgd via WhatsApp rond de Meeuwerderweg, De Oosterpoort en het Europapark, meestal binnen 20 tot 30 minuten. 18+.""",
        "h1": """Lachgas Oosterpoort""",
        "lead": """Achter het Hoofdstation, tussen het spoor en het Winschoterdiep: in de Oosterpoort bezorgen we snel na een bericht via WhatsApp.""",
        "intro": [
            """De Oosterpoort ligt direct achter het Hoofdstation, ingeklemd tussen het spoor, het Winschoterdiep en de Europaweg. Het is een compacte wijk met vooroorlogse straten rond de Meeuwerderweg, het cultuurcentrum De Oosterpoort aan de Trompsingel en aan de zuidkant het Europapark met de Euroborg en station Europapark. Wij bezorgen in de hele wijk, van de Griffeweg en de Lodewijkstraat tot de Winschoterkade en de Palmslag. Bestellen doe je via WhatsApp: stuur je adres en, als je boven woont, de verdieping, dan krijg je direct een bevestiging en een indicatie van de tijd.""",
            """Vanuit het centrum rijden onze bezorgers via de Herebrug en het Herewegviaduct de wijk in, of ze komen via de Europaweg vanaf de zuidelijke ringweg. Door de ligging pal naast het Hoofdstation en station Europapark zijn we in de Oosterpoort meestal binnen 20 tot 30 minuten, vaak aan de korte kant van die marge. Bij een thuiswedstrijd van FC Groningen in de Euroborg of een uitverkocht concert in De Oosterpoort staan de straten rond de Meeuwerderweg wel voller en is parkeren krapper. We plannen daar omheen en melden het vooraf als het een paar minuten langer wordt.""",
            """Een borrel met vrienden na een concert, een verjaardag in een bovenwoning aan de Meeuwerderweg of een rustige avond thuis: in ons <a href="/assortiment/">assortiment</a> vind je tanks van 2KG tot 10KG, zodat je niet meer in huis haalt dan je nodig hebt. Betalen kan contant of via Tikkie op het moment van levering; de prijs hoor je vooraf via WhatsApp. We leveren uitsluitend aan personen van 18 jaar en ouder en controleren dat waar nodig. Neem ook even onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> door.""",
        ],
        "wijken": """Meeuwerderweg, De Oosterpoort, Trompsingel, Griffeweg, Lodewijkstraat, Winschoterkade, Palmslag, Europaweg, Euroborg""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Horen de Euroborg en station Europapark ook bij jullie bezorggebied?""", """Ja. Het Europapark grenst direct aan de Oosterpoort en heeft een eigen pagina met dezelfde levertijd; kijk op <a href="/bezorggebied/europapark/">lachgas bezorgen in het Europapark</a>. Woon je aan de Europaweg of de Boumaboulevard, dan bestel je gewoon zoals in de rest van de wijk."""],
            ["""Kunnen jullie bezorgen als er een wedstrijd of concert is?""", """Zeker, al zijn de straten rond de Meeuwerderweg en de Europaweg dan voller en wordt er strenger op parkeren gelet. Onze bezorgers kennen de alternatieve routes via de Griffeweg en de Winschoterkade; soms kost het een paar minuten extra en dat laten we je vooraf weten."""],
            ["""Wat doe ik in de Oosterpoort met een lege lachgastank?""", """Een lege tank hoort niet bij het huisvuil of in de ondergrondse container. Je levert hem in bij een afvalbrengstation van de gemeente; hoe dat werkt lees je in ons artikel over <a href="/lachgas-informatie/lege-lachgastank-inleveren-groningen/">lege lachgastanks inleveren</a>."""],
        ],
        "nearby": ["europapark", "binnenstad", "helpman"],
        "lat": 53.210,
        "lon": 6.575,
    },
    {
        "slug": "helpman",
        "name": "Helpman",
        "kind": "wijk",
        "title": """Lachgas Helpman | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Helpman? Via WhatsApp bezorgd rond het Helperplein, de Verlengde Hereweg en Coendersborg, meestal binnen 20 tot 30 minuten. 18+.""",
        "h1": """Lachgas Helpman""",
        "lead": """In Helpman, tussen de zuidelijke ringweg en Haren, bezorgen we aan huis na een bericht via WhatsApp.""",
        "intro": [
            """Helpman ligt aan de zuidkant van Groningen, aan weerszijden van de Verlengde Hereweg, tussen de zuidelijke ringweg bij het Julianaplein en de grens met Haren. Het is een groene woonwijk met het Helperplein als winkelhart, de Helperzoom langs het spoor naar Assen en Coendersborg aan de zuidrand. Wij bezorgen in heel Helpman, van de Helperbrink en de Haydnlaan tot de straten rond het Sterrebos en de Savornin Lohmanlaan. Bestellen is eenvoudig: stuur via WhatsApp je adres en wat je wilt hebben, dan bevestigen we en komen we eraan.""",
            """Vanuit het centrum is Helpman een rechte lijn: over de Hereweg, onder de ringweg door en de Verlengde Hereweg op. Vanaf de A28 nemen onze bezorgers de afslag bij het Julianaplein. Daardoor staan we hier meestal binnen 20 tot 30 minuten voor de deur, net als in de rest van de stad. Treinen richting Assen rijden langs de Helperzoom zonder te stoppen en de bussen naar Haren rijden over de Verlengde Hereweg. Bij werkzaamheden op de zuidelijke ringweg kiezen we een omweg via de Hereweg of de Van Ketwich Verschuurlaan; als dat tijd kost, hoor je het vooraf.""",
            """Helpman is een wijk van gezinnen, ouderen en jonge professionals, met veel woningen met een tuin of een ruime etage. Voor een verjaardag in de tuin of een avond met vrienden kijk je in het <a href="/assortiment/">assortiment</a> welk formaat tank bij jullie past; voor een klein gezelschap is 2KG vaak al genoeg. Afrekenen doe je bij de deur, contant of via Tikkie, nadat we de prijs via WhatsApp hebben bevestigd. Verkoop alleen aan 18+; onze bezorger kan naar je ID vragen. Lees ook onze aanwijzingen voor <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>, zodat iedereen in huis weet waar hij op moet letten.""",
        ],
        "wijken": """Helperplein, Verlengde Hereweg, Helperzoom, Coendersborg, Helperbrink, Haydnlaan, Savornin Lohmanlaan, Sterrebos, Julianaplein""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Bezorgen jullie ook in Coendersborg en aan de Helperzoom?""", """Ja, Coendersborg en de straten langs de Helperzoom horen bij Helpman en vallen onder dezelfde indicatie van 20 tot 30 minuten. Woon je net over de grens in Haren, kijk dan op onze pagina voor <a href="/bezorggebied/haren/">lachgas in Haren</a>."""],
            ["""Heeft het verkeer rond het Julianaplein invloed op de levertijd?""", """Soms. De zuidelijke ringweg is de snelste aanrijroute vanaf de A28, maar bij files of werkzaamheden rijden we via de Hereweg. Dat scheelt meestal maar een paar minuten; de actuele inschatting krijg je altijd via WhatsApp zodra je bestelt."""],
            ["""Kan ik een tank in mijn schuur in Helpman bewaren tot het feest?""", """Dat kan, zolang de tank rechtop, droog en uit de zon staat en buiten bereik van kinderen blijft. In ons artikel over <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">bewaren en vervoeren</a> lees je waar je verder op moet letten."""],
        ],
        "nearby": ["de-wijert", "oosterpoort", "haren"],
        "lat": 53.198,
        "lon": 6.578,
    },
    {
        "slug": "paddepoel",
        "name": "Paddepoel",
        "kind": "wijk",
        "title": """Lachgas Paddepoel | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Paddepoel? Via WhatsApp bezorgd rond winkelcentrum Paddepoel, de Zonnelaan en Zernike, meestal binnen 20 tot 30 minuten. Alleen 18+.""",
        "h1": """Lachgas Paddepoel""",
        "lead": """Van de Zonnelaan tot de rand van Zernike: lachgas aan huis in Paddepoel, besteld via WhatsApp.""",
        "intro": [
            """Paddepoel is de jarenzestigwijk in het noordwesten van Groningen, herkenbaar aan straatnamen uit het heelal: Zonnelaan, Dierenriemstraat, Pleiadenlaan, Planetenlaan en Grote Beerstraat. De wijk ligt tussen het Reitdiep, de noordelijke ringweg, Selwerd en de Zernike Campus, met winkelcentrum Paddepoel als middelpunt. Wij bezorgen in de hele wijk, van de laagbouw rond de Venuslaan tot de flats aan de Pleiadenlaan en de nieuwbouw richting Zernikelaan. Bestellen gaat via WhatsApp: adres, eventueel het nummer van je flat en de verdieping, en je krijgt direct antwoord.""",
            """Onze bezorgers komen vanaf de noordelijke ringweg via de Zonnelaan of de Eikenlaan Paddepoel in, een route van een paar minuten vanaf het centrum. Daardoor zijn we hier meestal binnen 20 tot 30 minuten. De bussen tussen het Hoofdstation en Zernike rijden door de wijk en station Groningen Noord ligt op fietsafstand, maar voor de levering maakt dat weinig uit: wij komen tot aan je voordeur. Op donderdag- en vrijdagavond, als veel studenten thuis zijn, hebben we vaak meerdere adressen in Paddepoel en Selwerd tegelijk op de route; dat plannen we strak in.""",
            """In Paddepoel wonen veel studenten en starters, vaak met huisgenoten in een flat of een gedeelde woning. Kies in ons <a href="/assortiment/">assortiment</a> een formaat dat past bij het aantal mensen en bij de ruimte: op een kleine kamer is een 2KG een stuk handiger dan een 10KG. Je betaalt contant of via Tikkie wanneer we aan de deur staan, met een prijs die vooraf via WhatsApp is bevestigd. Jonger dan 18? Dan leveren we niet, en bij twijfel vragen we een ID. Voor een avond zonder gedoe is onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> de moeite van het lezen waard.""",
        ],
        "wijken": """Winkelcentrum Paddepoel, Zonnelaan, Dierenriemstraat, Pleiadenlaan, Planetenlaan, Grote Beerstraat, Venuslaan, Zernikelaan, Reitdiep""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Bezorgen jullie ook op de Zernike Campus en in de studentenhuisvesting daar?""", """Ja, de campus ligt direct ten noorden van Paddepoel en heeft een eigen pagina: <a href="/bezorggebied/zernike/">lachgas bezorgen op Zernike</a>. Geef het gebouw en de ingang door, want de campus is groot en niet alle adressen zijn even vindbaar."""],
            ["""Hoe werkt de levering bij een flat met een centrale ingang?""", """Zet in je bericht het huisnummer, de verdieping en de naam op de bel. Zodra we beneden staan, sturen we een appje; je kunt dan opendrukken of even naar beneden komen. Zo blijft de bezorging snel en onopvallend voor de rest van het gebouw."""],
            ["""Kan ik in Paddepoel ook slagroompatronen en een cracker meebestellen?""", """Ja, <a href="/product/slagroompatronen/">slagroompatronen</a> en crackers nemen we in dezelfde rit mee. Zet erbij wat je nodig hebt, dan bevestigen we het hele pakket in één bericht."""],
        ],
        "nearby": ["zernike", "selwerd", "vinkhuizen"],
        "lat": 53.236,
        "lon": 6.545,
    },
    {
        "slug": "vinkhuizen",
        "name": "Vinkhuizen",
        "kind": "wijk",
        "title": """Lachgas Vinkhuizen | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Vinkhuizen? Via WhatsApp bezorgd rond de Siersteenlaan, de Diamantlaan en het Westpark, meestal binnen 20 tot 30 minuten. Alleen 18+.""",
        "h1": """Lachgas Vinkhuizen""",
        "lead": """Lachgas in Vinkhuizen, van de Siersteenlaan tot de Goudlaan, bezorgd aan huis na een bericht via WhatsApp.""",
        "intro": [
            """Vinkhuizen ligt in het westen van Groningen, tussen de westelijke ringweg, de Friesestraatweg en het Westpark. De wijk is gebouwd in de jaren zestig en zeventig en heeft straatnamen van edelstenen en metalen: Siersteenlaan, Diamantlaan, Edelsteenlaan, Goudlaan, Zilverlaan en Platinalaan. Het winkelcentrum aan de Siersteenlaan vormt het middelpunt. Wij bezorgen in de hele wijk, van de hoogbouw langs de Diamantlaan tot de eengezinswoningen bij de Metaallaan en de rand van het Westpark. Bestellen doe je via WhatsApp met je adres en, bij een flat, de verdieping en het portiek.""",
            """Vanuit het centrum rijden onze bezorgers over de Friesestraatweg of nemen ze de westelijke ringweg tot de afslag Vinkhuizen, waar de Siersteenlaan de wijk in loopt. Beide routes zijn kort en meestal vrij van oponthoud, dus in Vinkhuizen leveren we meestal binnen 20 tot 30 minuten. Stadsbussen rijden via de Siersteenlaan en de Diamantlaan door de wijk, en Hoogkerk en de Reitdiephaven liggen om de hoek. Aan het einde van de middag kan de ringweg bij de Friesestraatweg stroperig zijn; dan kiezen we de binnendoorroute langs het Hoendiep.""",
            """Vinkhuizen is een echte woonwijk met gezinnen, ouderen en steeds meer jonge huishoudens in de vernieuwde delen. Of het nu om een verjaardag in de tuin of een avond met vrienden op de bank gaat: kijk in ons <a href="/assortiment/">assortiment</a> welk formaat bij jullie past en bestel niet meer dan je verwacht te gebruiken. Betalen doe je aan de deur, contant of via Tikkie, tegen de prijs die we vooraf via WhatsApp hebben doorgegeven. Levering is alleen mogelijk aan 18+; bij twijfel vraagt de bezorger een legitimatie. Onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> geeft in een paar minuten de belangrijkste aandachtspunten.""",
        ],
        "wijken": """Winkelcentrum Vinkhuizen, Siersteenlaan, Diamantlaan, Edelsteenlaan, Goudlaan, Zilverlaan, Platinalaan, Metaallaan, Westpark""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Bezorgen jullie ook aan de andere kant van het Westpark, in Hoogkerk?""", """Ja, Hoogkerk ligt direct ten zuidwesten van Vinkhuizen en hoort bij ons gebied; de details staan op <a href="/bezorggebied/hoogkerk/">lachgas bezorgen in Hoogkerk</a>. Ook de Reitdiephaven aan de noordkant nemen we mee."""],
            ["""Komen jullie in Vinkhuizen ook op zondag?""", """Ja, we bezorgen zeven dagen per week, dus ook in het weekend. Zondag is in Vinkhuizen vaak een rustige dag op de weg, waardoor we dicht bij de 20 minuten uitkomen. Meer over onze weekenddienst lees je op <a href="/lachgas-weekendbezorging/">weekendbezorging</a>."""],
            ["""Hoe herkennen jullie het juiste portiek in de hoogbouw aan de Diamantlaan?""", """Geef het huisnummer, de verdieping en de naam op de bel door. Onze bezorgers kennen de flats in Vinkhuizen en sturen een appje zodra ze beneden staan, zodat je kunt opendrukken of naar beneden kunt komen."""],
        ],
        "nearby": ["paddepoel", "hoogkerk", "reitdiep"],
        "lat": 53.226,
        "lon": 6.527,
    },
    {
        "slug": "beijum",
        "name": "Beijum",
        "kind": "wijk",
        "title": """Lachgas Beijum | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Beijum? Via WhatsApp bezorgd rond de Claremaheerd, Kardinge en de Beijumerweg, meestal binnen 20 tot 30 minuten. Alleen voor 18+.""",
        "h1": """Lachgas Beijum""",
        "lead": """Van de Claremaheerd tot de rand van Kardinge: in Beijum bezorgen we aan huis, besteld via WhatsApp.""",
        "intro": [
            """Beijum ligt in het noordoosten van Groningen, tussen de oostelijke ringweg, het recreatiegebied Kardinge en de buurwijk Lewenborg. De wijk uit de jaren zeventig en tachtig bestaat uit woonerven die allemaal eindigen op -heerd: Claremaheerd, Wibenaheerd, Isebrandtsheerd, Ypemaheerd, Fossemaheerd en nog tientallen andere. Het winkelcentrum aan de Claremaheerd is het centrale punt, de Beijumerweg de oude verbindingsweg door de wijk. Wij bezorgen in alle heerden. Je bestelt via WhatsApp door je volledige adres te sturen; omdat de namen op elkaar lijken, is de exacte spelling van je heerd belangrijk.""",
            """Onze bezorgers komen via de oostelijke ringweg en nemen de afslag Beijum-Noord of Beijum-Zuid, of ze rijden vanuit de Korrewegwijk via de Kardingerweg. Beijum ligt aan de rand van de stad, maar door de ringweg zijn we hier meestal binnen 20 tot 30 minuten. Vanaf het Hoofdstation rijden stadsbussen rechtstreeks naar de wijk en bij Kardinge ligt een P+R, al heb je dat voor de levering niet nodig: wij komen tot je voordeur. Binnen de wijk zijn de heerden vaak doodlopend of eenrichting; onze mensen kennen de doorsteekjes, waardoor het zoeken naar het juiste erf weinig tijd kost.""",
            """Beijum is een gezinswijk met veel eengezinswoningen, tuinen en een gemengde bevolking. Voor een verjaardag, een tuinfeest of een avond met de buren bekijk je ons <a href="/assortiment/">assortiment</a> en kies je een formaat dat bij de groep past. Afrekenen doe je bij levering, contant of via Tikkie, tegen de vooraf via WhatsApp bevestigde prijs. We leveren alleen aan 18+ en controleren leeftijd als daar aanleiding voor is. Houd het gezellig en verantwoord en lees onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> voordat je begint.""",
        ],
        "wijken": """Claremaheerd, Wibenaheerd, Isebrandtsheerd, Ypemaheerd, Fossemaheerd, Beijumerweg, Kardingerweg, Kardinge, Winkelcentrum Beijum""",
        "levertijd": """meestal binnen 20 tot 30 minuten""",
        "faq": [
            ["""Hoe vinden jullie het juiste adres tussen al die heerden?""", """Met je volledige adres en de juiste spelling van de heerd komen we er met de navigatie prima uit. Ligt je woning aan een binnenpad of achter een parkeerhof, zet dan een korte aanwijzing in je bericht, bijvoorbeeld de kleur van de deur of het dichtstbijzijnde parkeervak."""],
            ["""Bezorgen jullie ook in Lewenborg en bij sportcentrum Kardinge?""", """Ja. Lewenborg ligt direct naast Beijum en heeft een eigen pagina: <a href="/bezorggebied/lewenborg/">lachgas bezorgen in Lewenborg</a>. Rond Kardinge leveren we alleen op woonadressen, niet op parkeerplaatsen of in het recreatiegebied."""],
            ["""Kan ik in Beijum ook een cracker bij de tank bestellen?""", """Ja, een <a href="/product/lachgas-cracker/">lachgas cracker</a> en slagroompatronen bestel je gewoon mee in hetzelfde bericht. Alles komt in één rit, zodat je niet twee keer hoeft te wachten."""],
        ],
        "nearby": ["lewenborg", "korrewegwijk", "ten-boer"],
        "lat": 53.243,
        "lon": 6.597,
    },
    {
        "slug": "haren",
        "name": "Haren",
        "kind": "dorp",
        "title": """Lachgas Haren | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Haren? Via WhatsApp bezorgd rond de Rijksstraatweg, het Raadhuisplein en Oosterhaar, meestal binnen 25 tot 40 minuten. Alleen 18+.""",
        "h1": """Lachgas Haren""",
        "lead": """Lachgas in Haren, Onnen en Noordlaren: aan huis bezorgd vanuit Groningen, besteld via WhatsApp.""",
        "intro": [
            """Haren ligt direct ten zuiden van Groningen en hoort sinds 2019 bij de gemeente Groningen, maar het heeft nog altijd het karakter van een zelfstandig dorp. De Rijksstraatweg is de lange hoofdas, met het Raadhuisplein en de winkels van het centrum, en aan de oostkant van het spoor ligt de wijk Oosterhaar. Wij bezorgen in heel Haren: rond station Haren, bij de Hortus aan de Kerklaan, in Tuindorp, in Dilgt en in de buitendorpen Onnen en Noordlaren. Bestellen gaat via WhatsApp: stuur je adres en je bestelling, wij bevestigen en geven aan hoe laat we er ongeveer zijn.""",
            """Vanuit de stad rijden onze bezorgers via de Verlengde Hereweg, die in Haren overgaat in de Rijksstraatweg, of via de A28 met de afslag Haren. Dat is tien tot vijftien minuten rijden, iets langer dan binnen de stadsgrenzen, en daarom rekenen we voor Haren meestal 25 tot 40 minuten. De trein tussen Groningen en Assen stopt op station Haren en bussen rijden over de Rijksstraatweg, maar wij komen tot aan je deur, ook in de buitengebieden richting Sassenhein en Appelbergen. Op zomerse weekenden rond het Paterswoldsemeer kan de Meerweg vol staan; dan plannen we daar omheen.""",
            """Haren staat bekend om zijn ruime woningen, tuinen en een rustig, welvarend dorpsleven. Een familieverjaardag, een tuinfeest in de zomer of een avond met vrienden: in ons <a href="/assortiment/">assortiment</a> staan tanks van 2KG, 4KG en 10KG, en bij een klein gezelschap is het kleinste formaat doorgaans ruim genoeg. Je betaalt bij levering, contant of via Tikkie, na een prijsbevestiging via WhatsApp. We leveren uitsluitend aan 18+ en kunnen daar een ID voor vragen. Lees voor de zekerheid ook onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>, zodat iedereen weet waar hij aan toe is.""",
        ],
        "wijken": """Rijksstraatweg, Raadhuisplein, Station Haren, Oosterhaar, Hortus Haren, Tuindorp, Dilgt, Onnen, Noordlaren""",
        "levertijd": """meestal binnen 25 tot 40 minuten""",
        "faq": [
            ["""Bezorgen jullie ook in Onnen, Noordlaren en Glimmen?""", """Ja. Onnen en Noordlaren vallen onder Haren en nemen we mee met dezelfde indicatie; voor Glimmen, iets zuidelijker langs de A28, hebben we een eigen pagina over <a href="/bezorggebied/glimmen/">lachgas bezorgen in Glimmen</a>."""],
            ["""Waarom duurt bezorgen in Haren langer dan in Helpman?""", """Helpman ligt binnen de ringweg en Haren er een stuk voorbij, dus de rit over de Verlengde Hereweg of de A28 kost onze bezorgers extra minuten. Daarom rekenen we hier op meestal 25 tot 40 minuten in plaats van 20 tot 30."""],
            ["""Kan ik in Haren met Tikkie betalen of alleen contant?""", """Allebei kan. Je rekent af op het moment dat we aan de deur staan, contant of met een Tikkie-verzoek dat we direct sturen. Meer over de mogelijkheden lees je op onze pagina <a href="/betaalmethoden/">betaalmethoden</a>."""],
        ],
        "nearby": ["helpman", "glimmen", "eelde-paterswolde"],
        "lat": 53.171,
        "lon": 6.606,
    },
    {
        "slug": "hoogezand",
        "name": "Hoogezand",
        "kind": "dorp",
        "title": """Lachgas Hoogezand | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Hoogezand? Via WhatsApp bezorgd in Hoogezand, Sappemeer en Martenshoek, meestal binnen 25 tot 40 minuten vanuit Groningen. Alleen 18+.""",
        "h1": """Lachgas Hoogezand""",
        "lead": """Lachgas in Hoogezand-Sappemeer, van De Hooge Meeren tot Kropswolde, bezorgd vanuit Groningen via WhatsApp.""",
        "intro": [
            """Hoogezand ligt zo’n vijftien kilometer ten oosten van Groningen langs het Winschoterdiep en vormt samen met Sappemeer de grootste kern van de gemeente Midden-Groningen. De bebouwing strekt zich als een lint uit langs de Hoofdstraat en de Kerkstraat, met winkelcentrum De Hooge Meeren en het Kielzog als centrum. Wij bezorgen in heel Hoogezand-Sappemeer: in Gorecht-West en Woldwijck, in Martenshoek en Foxhol, in Kropswolde en Meerwijck aan het Zuidlaardermeer en in Westerbroek. Bestellen gaat via WhatsApp; stuur je adres en je bestelling en je ontvangt een bevestiging met een tijdsindicatie.""",
            """Vanuit Groningen rijden onze bezorgers over de A7 en nemen ze de afslag Hoogezand, of ze volgen de oude weg langs het Winschoterdiep via Engelbert en Westerbroek. Dat is een rit van ongeveer twintig minuten, en daarom rekenen we in Hoogezand meestal 25 tot 40 minuten. De treinen op de lijn Groningen–Winschoten stoppen op de stations Kropswolde, Martenshoek, Hoogezand-Sappemeer en Sappemeer Oost, een handig ijkpunt als je ons je adres doorgeeft. Op vrijdagmiddag kan de A7 bij Westerbroek vast staan; onze bezorgers wijken dan uit via de oude weg en melden het als het later wordt.""",
            """Hoogezand heeft een lange geschiedenis van scheepsbouw en industrie en is tegenwoordig vooral een woonplaats met veel eengezinswoningen en jonge gezinnen in de nieuwe buurten. Voor een feestje thuis, een verjaardag of een avond aan het Zuidlaardermeer vind je in ons <a href="/assortiment/">assortiment</a> het passende formaat tank; neem geen grotere dan je nodig hebt. Betalen doe je bij de deur, contant of via Tikkie, na bevestiging van de prijs via WhatsApp. Alleen voor 18+; een ID kan bij de deur gevraagd worden. Neem onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> door voordat je begint.""",
        ],
        "wijken": """Kerkstraat, De Hooge Meeren, Het Kielzog, Gorecht-West, Woldwijck, Sappemeer, Martenshoek, Foxhol, Kropswolde, Westerbroek""",
        "levertijd": """meestal binnen 25 tot 40 minuten""",
        "faq": [
            ["""Bezorgen jullie in Sappemeer en Martenshoek net zo snel als in Hoogezand?""", """Ja. Sappemeer, Martenshoek, Foxhol en Kropswolde liggen allemaal aan dezelfde lijn langs het Winschoterdiep, dus de indicatie van 25 tot 40 minuten geldt voor het hele gebied. Zet je volledige adres met plaatsnaam in je bericht."""],
            ["""Komen jullie ook naar Meerwijck aan het Zuidlaardermeer?""", """Ja, Meerwijck in Kropswolde hoort bij ons bezorggebied. Omdat het aan het einde van een lange weg ligt, helpt het als je het huisnummer en eventueel de naam van het pad doorgeeft. In de zomer rijden we daar regelmatig."""],
            ["""Hoe lang van tevoren moet ik in Hoogezand bestellen voor een feest?""", """Je kunt op de avond zelf bestellen, maar voor een grotere bijeenkomst is een bericht eerder op de dag prettig; dan reserveren we het formaat dat je wilt. Lees ook onze pagina over <a href="/lachgas-feest-evenement/">lachgas voor een feest of evenement</a>."""],
        ],
        "nearby": ["engelbert", "veendam", "meerstad"],
        "lat": 53.159,
        "lon": 6.760,
    },
    {
        "slug": "leek",
        "name": "Leek",
        "kind": "dorp",
        "title": """Lachgas Leek | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Leek? Via WhatsApp bezorgd rond de Tolberterstraat, Nienoord en Tolbert, meestal binnen 25 tot 40 minuten vanuit Groningen. 18+.""",
        "h1": """Lachgas Leek""",
        "lead": """Lachgas in Leek, Tolbert en Nietap: aan huis bezorgd vanuit Groningen na een bericht via WhatsApp.""",
        "intro": [
            """Leek ligt in het Westerkwartier, ongeveer zeventien kilometer ten zuidwesten van Groningen, direct aan de A7 en vlak bij de grens met Drenthe. Het dorp is vergroeid met Tolbert en met het Drentse Nietap, en staat bekend om landgoed Nienoord met de borg, het Rijtuigmuseum en het familiepark. Wij bezorgen in heel Leek: in het centrum rond de Tolberterstraat en de Diepswal, in de woonwijk Rodenburg, bij het Leekstermeer en in de omliggende dorpen Tolbert, Midwolde, Zevenhuizen en Nietap. Bestellen gaat via WhatsApp: stuur je adres met plaatsnaam en je bestelling, dan bevestigen we direct.""",
            """Onze bezorgers rijden vanuit Groningen over de A7 richting Drachten en nemen de afslag Leek, een rit van ruim een kwartier zonder stoplichten. Daarom rekenen we in Leek meestal 25 tot 40 minuten. Een station heeft Leek niet; de snelbus over de A7 verbindt het dorp met het Hoofdstation, maar voor de levering komen wij gewoon tot je voordeur. Aan het einde van de werkdag kan het bij Hoogkerk en de oprit van de A7 even stroperig zijn, en in de zomer is het druk rond Nienoord; dan hoor je vooraf via WhatsApp als het aan de lange kant van de indicatie wordt.""",
            """Leek is een dorp van gezinnen en forenzen, met veel vrijstaande woningen, tuinen en in het buitengebied boerderijen met ruimte voor een feest. Kijk in ons <a href="/assortiment/">assortiment</a> welk formaat tank bij jullie gezelschap past; voor een tuinfeest met een grotere groep is de 4KG een logische middenweg. Betalen gebeurt bij levering, contant of via Tikkie, tegen de prijs die we vooraf via WhatsApp bevestigen. Zoals overal leveren we ook in Leek uitsluitend aan 18+, met een ID-check waar nodig. Lees onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>, zeker als er veel mensen bij elkaar zijn.""",
        ],
        "wijken": """Tolberterstraat, Diepswal, Nienoord, Rodenburg, Leeksterveld, Tolbert, Midwolde, Zevenhuizen, Nietap, Leekstermeer""",
        "levertijd": """meestal binnen 25 tot 40 minuten""",
        "faq": [
            ["""Bezorgen jullie ook in Tolbert, Nietap en Zevenhuizen?""", """Ja. Tolbert en Nietap grenzen direct aan Leek en Zevenhuizen ligt er een paar kilometer onder; alle drie vallen onder dezelfde indicatie van 25 tot 40 minuten. Dat Nietap officieel in Drenthe ligt, maakt voor ons geen verschil."""],
            ["""Hoe ver is het voor jullie van Groningen naar Leek?""", """Ongeveer zeventien kilometer, vrijwel volledig over de A7. Bij normale omstandigheden is dat ruim een kwartier rijden, en met het inladen en de route door het dorp komen we op meestal 25 tot 40 minuten. Kijk voor alle zones op <a href="/bezorgtijden-groningen/">bezorgtijden</a>."""],
            ["""Kan ik bestellen voor een feest op een adres in het buitengebied rond Leek?""", """Ja, ook buiten de bebouwde kom komen we langs, bijvoorbeeld bij een boerderij of een schuur bij Midwolde of Zevenhuizen. Stuur het precieze adres en een aanwijzing voor de oprit, dan vinden onze bezorgers het ook in het donker."""],
        ],
        "nearby": ["zuidhorn", "roden", "marum"],
        "lat": 53.164,
        "lon": 6.378,
    },
    {
        "slug": "assen",
        "name": "Assen",
        "kind": "stad",
        "title": """Lachgas Assen | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Assen? Via WhatsApp bezorgd rond het Koopmansplein, Kloosterveen en Marsdijk, meestal binnen 40 tot 60 minuten vanuit Groningen. 18+.""",
        "h1": """Lachgas Assen""",
        "lead": """Lachgas in Assen, van het Koopmansplein tot Kloosterveen en Marsdijk, bezorgd vanuit Groningen na een bericht via WhatsApp.""",
        "intro": [
            """Assen is de hoofdstad van Drenthe en ligt ruim vijfentwintig kilometer ten zuiden van Groningen, aan de A28 en bij het beginpunt van de N33. Het centrum draait om het Koopmansplein, de Brink met het Drents Museum en de Gouverneurstuin, met de Vaart als groene as naar het westen. Daaromheen liggen grote woonwijken: Kloosterveen in het westen, Marsdijk in het noordoosten, Peelo, Pittelo, Baggelhuizen, Lariks en Assen-Oost. Wij bezorgen in de hele stad, dus ook in de buitenwijken en rond het TT Circuit. Bestellen gaat via WhatsApp: stuur je adres in Assen en wat je nodig hebt, dan bevestigen we en plannen we de rit.""",
            """Vanuit Groningen rijden onze bezorgers over de A28 langs Haren, Glimmen en Vries naar Assen, met de afslag Assen-Noord voor Marsdijk en Peelo en de afslagen bij de Europaweg en Assen-Zuid voor het centrum en Kloosterveen. Dat is zo’n dertig minuten rijden, en daarom is Assen bij ons een zone met meestal 40 tot 60 minuten. Treinen tussen Groningen en Assen rijden een paar keer per uur en stoppen bij station Assen naast het centrum, maar wij komen met de auto tot je voordeur. In het TT-weekend eind juni en bij evenementen op het circuit zijn wegen afgesloten; dat vraagt extra tijd en melden we vooraf.""",
            """Assen is een stad van gezinnen, ambtenaren en studenten die in Groningen studeren maar hier wonen. Voor een verjaardag in Kloosterveen, een avond met vrienden in een appartement bij het station of een feestje in Marsdijk kijk je in ons <a href="/assortiment/">assortiment</a> welk formaat past; omdat we van verder komen, loont het om in één keer het juiste formaat te kiezen. Betalen doe je bij levering, contant of via Tikkie, na bevestiging van de prijs via WhatsApp. We leveren uitsluitend aan 18+ en vragen zo nodig een ID. Lees ook onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> voordat de avond begint.""",
        ],
        "wijken": """Koopmansplein, Brink, Drents Museum, Station Assen, Kloosterveen, Marsdijk, Peelo, Pittelo, Baggelhuizen, Lariks""",
        "levertijd": """meestal binnen 40 tot 60 minuten""",
        "faq": [
            ["""Bezorgen jullie in heel Assen, ook in Kloosterveen en Marsdijk?""", """Ja, van het centrum tot de buitenwijken. Kloosterveen ligt aan de westkant en Marsdijk aan de noordoostkant, en voor beide geldt dezelfde indicatie van 40 tot 60 minuten vanuit Groningen. Zet je adres met postcode in je bericht, dan plannen we de kortste route."""],
            ["""Zijn jullie ook bereikbaar tijdens het TT-weekend?""", """Ja, maar houd rekening met afgesloten wegen rond het circuit en drukte in de binnenstad en op de A28. We laten vooraf weten of we je adres kunnen bereiken en hoe lang het duurt; soms is dat langer dan de gebruikelijke indicatie."""],
            ["""Waarom is de levertijd in Assen langer dan in de stad Groningen?""", """De rit over de A28 duurt alleen al zo’n dertig minuten, en daar komen het inladen en de route door Assen bij. Daarom valt Assen in onze buitenste zone van 40 tot 60 minuten; een overzicht van alle zones staat op <a href="/bezorgtijden-groningen/">bezorgtijden</a>."""],
        ],
        "nearby": ["vries", "beilen", "eelde-paterswolde"],
        "lat": 52.993,
        "lon": 6.564,
    },
    {
        "slug": "winschoten",
        "name": "Winschoten",
        "kind": "stad",
        "title": """Lachgas Winschoten | Snel bezorgd via WhatsApp""",
        "description": """Lachgas bestellen in Winschoten? Bezorgd via WhatsApp rond Marktplein, Langestraat en Blauwestad, meestal binnen 40 tot 60 minuten vanuit Groningen. 18+.""",
        "h1": """Lachgas Winschoten""",
        "lead": """Lachgas in Winschoten en het Oldambt, van het Marktplein tot Blauwestad, bezorgd vanuit Groningen na een bericht via WhatsApp.""",
        "intro": [
            """Winschoten is de grootste plaats van Oost-Groningen en het hart van de gemeente Oldambt, ongeveer vijfendertig kilometer ten oosten van Groningen aan de A7 richting Duitsland. De stad staat bekend als Molenstad vanwege de molens Berg, Dijkstra en Edens, en als Rozenstad vanwege het Rosarium. Het centrum ligt rond het Marktplein, de Torenstraat en de winkelstraat Langestraat. Wij bezorgen in heel Winschoten, van Sint Vitusholt en Bovenburen tot de buurten rond het station en de Blijhamsterweg, en ook in Blauwestad aan het Oldambtmeer. Bestellen gaat via WhatsApp: stuur je adres met plaatsnaam en je bestelling, dan bevestigen we met een tijdsindicatie.""",
            """Onze bezorgers rijden vanuit Groningen over de A7 via Hoogezand en Scheemda naar Winschoten, een rit van ruim een half uur. Winschoten is daarmee het verste punt van ons gebied aan de oostkant, en daarom geldt hier meestal 40 tot 60 minuten. De trein van Groningen naar Bad Nieuweschans stopt op station Winschoten en is ongeveer even lang onderweg, maar voor de levering komen wij met de auto tot aan je deur. Bij werkzaamheden op de A7 of drukte bij de aansluiting met de N33 kan het aan de lange kant van de indicatie worden; dat laten we vooraf weten, zodat je weet waar je aan toe bent.""",
            """Winschoten en het Oldambt zijn een regio van ruime huizen en dorpse rust, met Blauwestad als nieuwe woonwijk aan het water. Voor een verjaardag, een avond met vrienden of een feest in de tuin bekijk je ons <a href="/assortiment/">assortiment</a> en kies je het formaat dat bij jullie past; omdat we van ver komen, is het handig om in één bestelling alles mee te nemen. Betalen doe je bij levering, contant of via Tikkie, tegen de prijs die we vooraf via WhatsApp hebben bevestigd. Ook in Winschoten geldt: alleen 18+, en de bezorger mag om een legitimatie vragen. Onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> hoort bij elke bestelling, dus neem die vooraf door.""",
        ],
        "wijken": """Marktplein, Torenstraat, Langestraat, Station Winschoten, Blijhamsterweg, Rosarium, Sint Vitusholt, Bovenburen, Blauwestad""",
        "levertijd": """meestal binnen 40 tot 60 minuten""",
        "faq": [
            ["""Bezorgen jullie ook in Blauwestad en Scheemda?""", """Ja. Blauwestad ligt direct ten noorden van Winschoten aan het Oldambtmeer en Scheemda ligt aan de A7 op onze aanrijroute; beide nemen we mee met dezelfde indicatie van 40 tot 60 minuten. Vermeld de plaatsnaam bij je adres."""],
            ["""Hoe lang duurt het vanuit Groningen naar Winschoten?""", """De rit over de A7 is ruim een half uur bij normaal verkeer. Met inladen en de laatste kilometers door de stad komen we op meestal 40 tot 60 minuten. Alle zones en tijden staan op onze pagina <a href="/bezorgtijden-groningen/">bezorgtijden Groningen</a>."""],
            ["""Hebben jullie spoedbezorging in Winschoten?""", """We vertrekken na je bevestiging direct, maar de afstand blijft; sneller dan de A7 toelaat kunnen we niet. Wat spoed op deze afstand realistisch betekent, lees je op <a href="/lachgas-spoedbezorging/">spoedbezorging</a>."""],
        ],
        "nearby": ["oude-pekela", "veendam", "hoogezand"],
        "lat": 53.143,
        "lon": 7.034,
    },
]
