# -*- coding: utf-8 -*-
# Nieuwe plaatsen rond Groningen, deel A (fase 3): Zuidlaren, Winsum, Peize, Vries, Glimmen, Engelbert, Marum, Veendam, Stadskanaal.

AREAS = [
    {
        'slug': 'zuidlaren', 'name': 'Zuidlaren', 'kind': 'dorp',
        'title': 'Lachgas Zuidlaren | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Zuidlaren? Lachgastanks en patronen bezorgd in Zuidlaren, Westlaren en Midlaren, meestal binnen 25 tot 40 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Zuidlaren',
        'lead': 'Lachgastanks aan de deur in Zuidlaren en rond het Zuidlaardermeer, besteld via WhatsApp en meestal binnen 25 tot 40 minuten geleverd.',
        'intro': [
            'Zuidlaren ligt op de Hondsrug in de Drentse gemeente Tynaarlo, een kwartier ten zuiden van Groningen. Het dorp staat bekend om zijn brinken, de Zuidlaardermarkt in oktober en het Zuidlaardermeer aan de oostkant. Wij bezorgen in heel Zuidlaren: rond de Brink en de Stationsweg, in Westlaren, op het terrein van Dennenoord en in de buurdorpen Midlaren, Zuidlaarderveen en De Groeve. Bestellen gaat via WhatsApp: je stuurt wat je wilt hebben en je adres, wij bevestigen de prijs en de verwachte aankomsttijd in hetzelfde gesprek.',
            'Onze bezorgers rijden vanuit de stad over de A28 naar De Punt en pakken daar de N34 richting Zuidlaren, of nemen de oude route over de Hondsrug via Haren en Noordlaren. Beide routes kosten zo’n twintig minuten, en daarom rekenen we voor Zuidlaren op meestal 25 tot 40 minuten in plaats van de stadstijd. Met het openbaar vervoer ben je afhankelijk van de streekbus vanaf het Hoofdstation; wij komen tot aan de deur, ook op de buitenwegen richting Schipborg en Annen. Bij slecht weer of drukte op de N34 hoor je dat vooraf.',
            'Een avond met vrienden aan het meer, een feestje in Westlaren of een gezelschap dat na de Zuidlaardermarkt doorgaat: per situatie past een ander formaat. In ons <a href="/assortiment/">assortiment</a> vind je de lachgastank 2KG, 4KG en 10KG, plus crackers en slagroompatronen. Twijfel je over het formaat, dan denken we via WhatsApp mee. Betalen doe je contant of via Tikkie bij levering, nadat de prijs vooraf is bevestigd. We leveren uitsluitend aan 18+ en kunnen om een legitimatie vragen. Lees voor je bestelt onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Brink, Stationsweg, Westlaren, Dennenoord, Midlaren, Zuidlaarderveen, De Groeve, Zuidlaardermeer, Schipborg',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie ook bij het Zuidlaardermeer en in Midlaren?', 'Ja. Midlaren, De Groeve en de recreatieplekken aan de westoever van het Zuidlaardermeer vallen binnen de rit naar Zuidlaren. Zet het volledige adres of de naam van het park in je bericht, dan plannen we de route daarop.'],
            ['Waarom duurt het in Zuidlaren langer dan in Groningen?', 'Zuidlaren ligt buiten de stad, via de A28 en de N34 of over de Hondsrug. Die rit kost ongeveer twintig minuten, dus de indicatie is meestal 25 tot 40 minuten. Op de pagina over <a href="/bezorgtijden-groningen/">bezorgtijden</a> zie je hoe de zones zijn opgebouwd.'],
            ['Is Zuidlaren ook tijdens de Zuidlaardermarkt bereikbaar?', 'Tijdens de markt in oktober is het centrum deels afgesloten en staat er veel verkeer op de toegangswegen. We bezorgen dan wel, maar spreken via WhatsApp een punt af dat met de auto bereikbaar is, en de levertijd kan oplopen.'],
        ],
        'nearby': ['haren', 'glimmen', 'vries'],
        'lat': 53.094, 'lon': 6.683,
    },
    {
        'slug': 'winsum', 'name': 'Winsum', 'kind': 'dorp',
        'title': 'Lachgas Winsum | Snel bezorgd via WhatsApp',
        'description': 'Lachgas bestellen in Winsum? Wij bezorgen lachgastanks en patronen in Winsum, Obergum en Sauwerd, meestal binnen 25 tot 40 minuten. Alleen 18+.',
        'h1': 'Lachgas bezorgen in Winsum',
        'lead': 'Lachgastanks thuisbezorgd in Winsum en de dorpen langs het Reitdiep: bestellen via WhatsApp, meestal binnen 25 tot 40 minuten aan de deur.',
        'intro': [
            'Winsum ligt een kleine vijftien kilometer ten noordwesten van Groningen en hoort sinds 2019 bij de gemeente Het Hogeland. Het dorp bestaat uit twee oude kernen, Winsum en Obergum, aan weerszijden van het Winsumerdiep, met de molens De Ster en De Vriendschap als herkenningspunten. Wij bezorgen in het hele dorp, van de Hoofdstraat en de wijken Ripperda en Potmaar tot de nieuwbouw richting het station, en ook in Sauwerd, Adorp, Baflo en Garnwerd. Je bestelt met een WhatsApp-bericht waarin je adres en gewenste producten staan; wij reageren met prijs en tijd.',
            'De rit vanuit de stad gaat over de N361 langs Adorp en Sauwerd, parallel aan de spoorlijn van Groningen naar Roodeschool waarop Winsum een eigen station heeft. Het is een vlakke, overzichtelijke weg van ongeveer een kwartier, maar met het laden en de terugweg erbij komen we in Winsum uit op meestal 25 tot 40 minuten. ’s Avonds en in het weekend rijden we gewoon door; wel kan het zijn dat de bezorger eerst een adres in Bedum of Zuidhorn afwerkt. Je krijgt bij bevestiging altijd een realistische inschatting.',
            'Of het nu gaat om een borrel in de tuin, een feestavond met huisgenoten of een groter feest in een schuur buiten het dorp, de keuze van het formaat bepaalt het gemak. Bekijk in het <a href="/assortiment/">assortiment</a> de verschillen tussen de tank van 2KG, 4KG en 10KG; crackers en slagroompatronen nemen we in dezelfde rit mee. Je betaalt contant of via Tikkie zodra de bezorger voor je staat, tegen de prijs die vooraf in WhatsApp is bevestigd. We leveren alleen aan personen van 18 jaar en ouder. Op onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> staat waar je op moet letten.',
        ],
        'wijken': 'Hoofdstraat, Obergum, Ripperda, Potmaar, Station Winsum, Winsumerdiep, Sauwerd, Adorp, Baflo, Garnwerd',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Komen jullie ook in Baflo, Garnwerd en Sauwerd?', 'Ja, die dorpen liggen op of vlak bij de route naar Winsum en horen bij dezelfde zone. Voor Baflo en verder richting Warffum kan de tijd iets oplopen; dat melden we vooraf in het gesprek.'],
            ['Kan ik bestellen als ik met de trein in Winsum aankom?', 'Dat kan, maar we leveren op een adres en niet op het perron. Stuur een bericht zodra je weet waar je bent, bijvoorbeeld bij vrienden in Obergum, dan plannen we de bezorging op dat adres.'],
            ['Hoe werkt betalen in Winsum?', 'Je betaalt bij levering, contant of via een Tikkie dat de bezorger ter plekke stuurt. De prijs staat vooraf vast in het WhatsApp-gesprek; op de pagina <a href="/betaalmethoden/">betaalmethoden</a> lees je alle details.'],
        ],
        'nearby': ['bedum', 'zuidhorn', 'uithuizen'],
        'lat': 53.330, 'lon': 6.518,
    },
    {
        'slug': 'peize', 'name': 'Peize', 'kind': 'dorp',
        'title': 'Lachgas Peize | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Peize? Lachgastanks en patronen bezorgd in Peize, Peizermade en Roderwolde, meestal binnen 25 tot 40 minuten. Alleen 18+.',
        'h1': 'Lachgas bezorgen in Peize',
        'lead': 'Lachgastanks bezorgd in Peize, aan de rand van De Onlanden, besteld via WhatsApp en meestal binnen 25 tot 40 minuten geleverd.',
        'intro': [
            'Peize is een esdorp in de Drentse gemeente Noordenveld, net over de provinciegrens ten zuidwesten van Groningen. Tussen het dorp en de stad ligt het natuurgebied De Onlanden, met de Peizermaden en het Peizerdiep. Ons bezorggebied omvat het hele dorp, van de Hoofdstraat en de Kerkstraat tot de Groningerweg, en daarnaast Peizerwold, Altena en Roderwolde. Bestellen doe je door via WhatsApp te sturen welk product je wilt en op welk adres; je ontvangt dan een bevestiging met prijs en een indicatie van de aankomsttijd.',
            'Vanuit Groningen rijden we via Hoogkerk over de Peizerweg door De Onlanden, of via de A7 en de N372 richting Roden, met Peize als eerste afslag. De afstand is bescheiden, maar de wegen door het natuurgebied zijn smal en in de spits druk, zodat we voor Peize meestal 25 tot 40 minuten aanhouden. Een treinstation heeft het dorp niet; de bus vanuit de stad rijdt door naar Roden en Norg. Onze bezorger komt tot aan de voordeur, ook op de buitenwegen richting Roderwolde en Peizermade.',
            'Een tuinfeest achter een boerderij, een verjaardag in de nieuwbouw of een avond met vrienden die uit Roden en Groningen komen: in het <a href="/assortiment/">assortiment</a> staan de 2KG, 4KG en 10KG tanks naast elkaar, zodat je snel ziet welk formaat bij de groep past. Crackers en slagroompatronen kunnen in dezelfde bestelling. Afrekenen gebeurt bij de deur, contant of via Tikkie, tegen de vooraf bevestigde prijs. We leveren uitsluitend aan 18+ en vragen bij twijfel om een geldig ID. Lees ook onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Hoofdstraat, Kerkstraat, Groningerweg, Peizermade, Peizerwold, Altena, Roderwolde, De Onlanden, Peizerdiep',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie ook in Roderwolde en Peizerwold?', 'Ja, beide buurtschappen liggen binnen een paar minuten van Peize en horen bij dezelfde zone. Geef het volledige adres door, want huisnummers langs de buitenwegen zijn in het donker lastig te vinden.'],
            ['Is Peize sneller dan Roden?', 'Peize ligt een paar kilometer dichter bij de stad, dus doorgaans wel. Toch houden we voor beide dorpen 25 tot 40 minuten aan, omdat de weg door De Onlanden weinig ruimte biedt om tijd in te halen. Voor <a href="/bezorggebied/roden/">Roden</a> geldt dus dezelfde zone.'],
            ['Hoe bewaar ik de tank als het feest in de tuin is?', 'Zet de tank rechtop, in de schaduw en uit de buurt van de barbecue of een vuurkorf, omdat de druk in de cilinder oploopt bij warmte. Meer tips vind je bij <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">bewaren en vervoeren</a>.'],
        ],
        'nearby': ['roden', 'eelde-paterswolde', 'vries'],
        'lat': 53.146, 'lon': 6.496,
    },
    {
        'slug': 'vries', 'name': 'Vries', 'kind': 'dorp',
        'title': 'Lachgas Vries | Bezorgd via WhatsApp, dag en nacht',
        'description': 'Lachgas bestellen in Vries? Lachgastanks en patronen bezorgd in Vries, Tynaarlo en Zeijen, meestal binnen 25 tot 40 minuten. Alleen voor 18+.',
        'h1': 'Lachgas bezorgen in Vries',
        'lead': 'Lachgastanks aan huis in Vries en de dorpen tussen Groningen en Assen, besteld via WhatsApp en meestal binnen 25 tot 40 minuten bezorgd.',
        'intro': [
            'Vries is het bestuurlijke hart van de gemeente Tynaarlo: het gemeentehuis staat aan de rand van het dorp en de oude Bonifatiuskerk op de Brink markeert het centrum. Het dorp ligt halverwege Groningen en Assen, pal aan de A28, met Norg aan de westkant en Zuidlaren aan de oostkant. Wij bezorgen in Vries zelf en in de omliggende dorpen Tynaarlo, Taarlo, Donderen, Zeijen, Yde en De Punt. Stuur via WhatsApp je adres en wat je nodig hebt; we laten direct weten wat het kost en wanneer we er ongeveer zijn.',
            'De bezorger rijdt vanuit Groningen de A28 op en neemt de afslag Vries, een rit van ruim een kwartier zonder stoplichten. Daarna volgt vaak nog een stuk binnenweg naar Zeijen, Donderen of Taarlo, en dat verklaart waarom we hier meestal 25 tot 40 minuten aanhouden. Vries heeft geen station; de bus tussen Groningen en Assen stopt wel langs de Asserstraat. Omdat Assen vlakbij ligt, combineren we ritten soms met adressen daar, maar je hoort bij bevestiging precies wat dat voor jouw tijd betekent.',
            'Voor een avond op de Brink met een paar vrienden is een kleine tank genoeg, voor een feest in een schuur bij Zeijen of een grote groep in Tynaarlo kijk je eerder naar de 4KG of 10KG. In het <a href="/assortiment/">assortiment</a> staan alle formaten met uitleg; crackers en slagroompatronen leveren we erbij. De prijs wordt vooraf bevestigd via WhatsApp en je betaalt contant of via Tikkie bij levering. Verkoop alleen aan 18+, legitimatie kan gevraagd worden. Bekijk vooraf ook onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Brink, Asserstraat, Oude Asserstraat, Tynaarlo, Taarlo, Donderen, Zeijen, Yde, De Punt',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie ook in Zeijen, Donderen en Taarlo?', 'Ja. Deze dorpen horen bij de gemeente Tynaarlo en liggen op korte afstand van Vries; ze vallen onder dezelfde zone van 25 tot 40 minuten. Vermeld het dorp in je bericht, dan plannen we de binnenweg erbij.'],
            ['Wat is sneller: bestellen vanuit Vries of vanuit Assen?', 'Vries ligt dichter bij Groningen en kent daarom een kortere indicatie. Voor <a href="/bezorggebied/assen/">Assen</a> rekenen we meestal 40 tot 60 minuten. Woon je tussen beide plaatsen, zet dan je exacte adres in het bericht.'],
            ['Leveren jullie ook laat in de avond in Vries?', 'Ja, we bezorgen ook in de late uren. Meer over de werkwijze in de nacht lees je op <a href="/lachgas-nachtbezorging/">nachtbezorging</a>; het is verstandig om na middernacht iets meer tijd in te calculeren.'],
        ],
        'nearby': ['assen', 'eelde-paterswolde', 'zuidlaren'],
        'lat': 53.078, 'lon': 6.580,
    },
    {
        'slug': 'glimmen', 'name': 'Glimmen', 'kind': 'dorp',
        'title': 'Lachgas Glimmen | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Glimmen? Lachgastanks en patronen bezorgd in Glimmen, Noordlaren en Onnen, meestal binnen 25 tot 40 minuten. Alleen 18+.',
        'h1': 'Lachgas bezorgen in Glimmen',
        'lead': 'Lachgastanks bezorgd in Glimmen, Noordlaren en Onnen aan de zuidrand van de gemeente Groningen, meestal binnen 25 tot 40 minuten na je WhatsApp-bericht.',
        'intro': [
            'Glimmen ligt aan de Rijksstraatweg ten zuiden van Haren, waar de gemeente Groningen bij De Punt overgaat in Drenthe. Het is een bosrijk dorp met het Quintusbos, landgoed Huis te Glimmen en het natuurgebied Appelbergen vlakbij. Wij bezorgen in Glimmen en in de buurdorpen Noordlaren en Onnen, die samen met Glimmen tot 2019 bij de gemeente Haren hoorden. Een bestelling plaats je via WhatsApp met je adres en de gewenste producten; je krijgt een bevestiging met prijs en verwachte tijd terug.',
            'Vanuit het centrum van Groningen rijdt de bezorger over de A28 tot voorbij Haren, of via de Rijksstraatweg door Haren zelf. Dat kost ongeveer een kwartier, en voor de adressen langs de Drentsche Aa of op de Hondsrug bij Noordlaren komt daar een stuk binnenweg bij. Daarom geldt voor Glimmen meestal 25 tot 40 minuten, net buiten de stadszone. Het dichtstbijzijnde station is Haren; de bus naar Zuidlaren en Assen stopt langs de Rijksstraatweg. Wij rijden door tot aan je oprit.',
            'Glimmen heeft veel vrijstaande huizen met grote tuinen, en veel bestellingen komen dan ook van tuinfeesten en verjaardagen in de zomer. In het <a href="/assortiment/">assortiment</a> vergelijk je de lachgastank 2KG, 4KG en 10KG, en zie je ook de crackers en slagroompatronen. Betaal bij levering, contant of via Tikkie, tegen de prijs die in het WhatsApp-gesprek is afgesproken. We leveren uitsluitend aan 18+. Lees voordat je bestelt de pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>, zeker als er gasten bij zijn die het niet kennen.',
        ],
        'wijken': 'Rijksstraatweg, Quintusbos, Huis te Glimmen, Appelbergen, Meentweg, Zuidlaarderweg, Noordlaren, Onnen, De Punt',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie in Noordlaren en Onnen tegen dezelfde tijd?', 'Ja. Noordlaren ligt via de Zuidlaarderweg op een paar minuten en Onnen ligt tussen Haren en Glimmen in. Beide dorpen vallen onder dezelfde indicatie van 25 tot 40 minuten.'],
            ['Waarom valt Glimmen niet in de zone van Haren?', 'Haren grenst direct aan de stad en hoort bij de stadszone. Glimmen ligt verder langs de A28 en de huizen liggen verspreid, waardoor de laatste kilometers meer tijd kosten. De indeling staat op <a href="/bezorggebied/">het bezorggebied</a>.'],
            ['Kan ik in Glimmen ook betalen via Tikkie?', 'Ja, de bezorger stuurt bij aankomst een Tikkie dat je direct kunt voldoen, of je betaalt contant. De prijs is al vooraf via WhatsApp bevestigd, zodat er aan de deur niets te bespreken valt.'],
        ],
        'nearby': ['haren', 'zuidlaren', 'eelde-paterswolde'],
        'lat': 53.137, 'lon': 6.628,
    },
    {
        'slug': 'engelbert', 'name': 'Engelbert', 'kind': 'dorp',
        'title': 'Lachgas Engelbert | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Engelbert? Lachgastanks en patronen bezorgd in Engelbert, Middelbert en Roodehaan, meestal binnen 20 tot 30 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Engelbert',
        'lead': 'Lachgastanks aan de deur in Engelbert en Middelbert, aan de oostkant van Groningen: bestellen via WhatsApp, meestal binnen 20 tot 30 minuten geleverd.',
        'intro': [
            'Engelbert is een lintdorp aan de oostrand van Groningen, ingeklemd tussen de A7, het Eemskanaal en de nieuwe wijk Meerstad. Het dorp hoort bij de gemeente Groningen en bestaat uit de Engelberterweg met de omliggende boerderijen en nieuwbouw, met Middelbert als noorderbuur en Roodehaan aan het Winschoterdiep. Ook de bedrijventerreinen Driebond en Eemspoort en de huizen richting Harkstede nemen we mee. Je bestelt via WhatsApp door je adres en de gewenste producten te sturen; we bevestigen prijs en tijd voordat de bezorger vertrekt.',
            'Engelbert zit vanuit het centrum op nog geen tien minuten rijden: via de Europaweg en de Sint-Petersburgweg langs het Europapark, of vanaf de A7 bij de afslag Westerbroek. Daardoor hanteren we hier dezelfde indicatie als in de stad, meestal 20 tot 30 minuten. De buslijn naar Harkstede rijdt door het dorp, maar voor een bezorging hoef je niets te regelen: de bezorger komt tot aan de voordeur, ook op de erven langs de Woldjerspoorweg. Bij werkzaamheden op de A7 kiezen we de route binnendoor.',
            'Ruimte is in Engelbert geen probleem, dus feesten zijn hier vaak in een schuur, loods of grote tuin. Voor een klein gezelschap is de 2KG handig, voor een feest met veel gasten kijk je naar de 4KG of de 10KG; alle formaten staan in het <a href="/assortiment/">assortiment</a>, net als crackers en slagroompatronen. Je betaalt bij levering, contant of via Tikkie, nadat de prijs in WhatsApp is vastgelegd. Verkoop is uitsluitend aan 18+ en de bezorger mag om een ID vragen. Onze tips over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> lees je het best vooraf.',
        ],
        'wijken': 'Engelberterweg, Woldjerspoorweg, Middelbert, Roodehaan, Driebond, Eemspoort, Harkstede, Woldmeer',
        'levertijd': 'meestal binnen 20 tot 30 minuten',
        'faq': [
            ['Hoort Engelbert bij de stadszone of bij de dorpen?', 'Bij de stad. Engelbert ligt binnen de gemeente Groningen en op een paar minuten van het Europapark, dus we rekenen hier meestal 20 tot 30 minuten. Dat geldt ook voor Middelbert.'],
            ['Bezorgen jullie ook op een bedrijventerrein zoals Driebond?', 'Ja, mits er iemand van 18 jaar of ouder aanwezig is om de bestelling aan te nemen. Geef het adres en een naam door, dan weet de bezorger bij welke ingang hij moet zijn.'],
            ['Kan ik een bestelling voor een feest in Harkstede ook in Engelbert laten bezorgen?', 'Dat kan, maar we bezorgen ook gewoon in Harkstede zelf; de tijd kan daar iets oplopen omdat het buiten de gemeente Groningen ligt. Voor grotere feesten lees je meer op <a href="/lachgas-feest-evenement/">feest en evenement</a>.'],
        ],
        'nearby': ['meerstad', 'hoogezand', 'europapark'],
        'lat': 53.206, 'lon': 6.655,
    },
    {
        'slug': 'marum', 'name': 'Marum', 'kind': 'dorp',
        'title': 'Lachgas Marum | Bezorgd via WhatsApp, dag en nacht',
        'description': 'Lachgas bestellen in Marum? Lachgastanks en patronen bezorgd in Marum, Nuis, Niebert en De Wilp, meestal binnen 25 tot 40 minuten. Alleen 18+.',
        'h1': 'Lachgas bezorgen in Marum',
        'lead': 'Lachgastanks bezorgd in Marum en de dorpen van het zuidelijk Westerkwartier, langs de A7 richting Friesland, meestal binnen 25 tot 40 minuten na je bericht.',
        'intro': [
            'Marum ligt aan de A7 in het zuidwesten van de gemeente Westerkwartier, vlak voor de grens met Friesland. De Wendtsteinweg is de winkelstraat van het dorp, en rondom liggen de kernen Nuis en Niebert met de Coendersborg, De Wilp aan de zuidkant en Boerakker richting Leek. Wij bezorgen in Marum en al deze dorpen, tot aan Jonkersvaart en Noordwijk. Een bestelling stuur je via WhatsApp: adres, gewenste producten en eventueel een voorkeurstijd. Je ontvangt de prijs en een indicatie van de aankomst voordat we vertrekken.',
            'Vanuit Groningen is het één rechte lijn: de A7 richting Drachten, voorbij de afslagen Hoogkerk en Leek, tot de afrit Marum. Zonder file duurt dat zo’n twintig minuten, en vandaar is het nog een paar minuten naar Nuis, Niebert of De Wilp. Marum valt daarom in de zone van meestal 25 tot 40 minuten, aan de ruime kant van die marge. De snelbus tussen Groningen en Drachten stopt bij de A7; wij komen tot aan het huis. Bij werkzaamheden op de A7 wijken we uit via Leek en de binnenwegen, wat extra tijd kost.',
            'Feesten in het Westerkwartier zijn vaak groot en in een schuur of tent, maar ook voor een avond met een paar vrienden in de nieuwbouw is er een passend formaat. Vergelijk in het <a href="/assortiment/">assortiment</a> de lachgastank 2KG, 4KG en 10KG en voeg naar wens crackers of slagroompatronen toe. Betalen doe je bij de deur, contant of via Tikkie, tegen de prijs die vooraf is bevestigd. We leveren uitsluitend aan 18+ en controleren bij twijfel een ID. Lees onze informatie over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> voordat de avond begint.',
        ],
        'wijken': 'Wendtsteinweg, Nuis, Niebert, De Wilp, Boerakker, Jonkersvaart, Noordwijk, Lucaswolde, Trimunt',
        'levertijd': 'meestal binnen 25 tot 40 minuten',
        'faq': [
            ['Bezorgen jullie ook over de Friese grens, bijvoorbeeld in Frieschepalen?', 'Ja. <a href="/bezorggebied/drachten/">Drachten</a> en de dorpen daartussen vallen onder de zone van 40 tot 60 minuten. Voor adressen net over de grens, zoals Frieschepalen of Siegerswoude, bespreken we de tijd per bestelling via WhatsApp.'],
            ['Hoe laat kan ik in Marum nog bestellen?', 'We bezorgen ook ’s avonds en in het weekend; zie <a href="/lachgas-weekendbezorging/">weekendbezorging</a>. In de late uren is de A7 rustig, maar de rit blijft even lang, dus houd rekening met de bovenkant van de indicatie.'],
            ['Kan ik in Marum ook alleen crackers of slagroompatronen bestellen?', 'Ja, dat kan. Zo’n kleine bestelling combineren we waar mogelijk met andere ritten richting het Westerkwartier; we laten via WhatsApp weten of dat direct kan of dat het iets later wordt. Bekijk de <a href="/product/lachgas-cracker/">lachgas cracker</a> voor de details.'],
        ],
        'nearby': ['leek', 'zuidhorn', 'drachten'],
        'lat': 53.145, 'lon': 6.265,
    },
    {
        'slug': 'veendam', 'name': 'Veendam', 'kind': 'stad',
        'title': 'Lachgas Veendam | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Veendam? Lachgastanks en patronen bezorgd in Veendam, Wildervank en Sorghvliet, meestal binnen 40 tot 60 minuten. 18+.',
        'h1': 'Lachgas bezorgen in Veendam',
        'lead': 'Lachgastanks bezorgd in Parkstad Veendam en Wildervank, besteld via WhatsApp en meestal binnen 40 tot 60 minuten aan de deur.',
        'intro': [
            'Veendam, ook wel Parkstad genoemd vanwege het Borgerspark, het Julianapark en het groen rond Veenlust, is de grootste plaats van de Veenkoloniën. Wij bezorgen in de hele stad: in het centrum rond de Promenade en de Kerkstraat, in Sorghvliet, Buitenwoel en Langebosch, in Veendam-Noord en in Wildervank, dat aan de zuidkant naadloos aan Veendam vastzit. Ook Ommelanderwijk, Zuidwending en Borgercompagnie liggen binnen het gebied. Bestellen gaat via WhatsApp met je adres en producten; je ontvangt een prijs en een eerlijke inschatting van de aankomsttijd.',
            'Vanuit Groningen rijden we over de A7 tot Zuidbroek en vervolgens de N33 naar het zuiden tot de afslag Veendam, een rit van ongeveer een halfuur. Dat is beduidend verder dan de dorpen rond de stad, en daarom geldt voor Veendam meestal 40 tot 60 minuten. Er is een treinverbinding via Zuidbroek, maar bezorgen doen we met de auto tot aan de deur, ook in de lange lintbebouwing van Wildervank en Ommelanderwijk. Combineren we de rit met Hoogezand of Winschoten, dan zeggen we dat vooraf.',
            'Een studentenfeest in het centrum, een verjaardag in Buitenwoel of een groot feest in een loods aan de rand van Wildervank: elke situatie vraagt een ander formaat. In ons <a href="/assortiment/">assortiment</a> staan de lachgastank 2KG, 4KG en 10KG met uitleg, en ook crackers en slagroompatronen. Omdat de rit naar Veendam langer is, loont het om meteen het juiste formaat te kiezen in plaats van later bij te bestellen. Afrekenen doe je bij levering, contant of via Tikkie, tegen de vooraf bevestigde prijs. Alleen voor 18+; lees vooraf over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a>.',
        ],
        'wijken': 'Promenade, Kerkstraat, Sorghvliet, Buitenwoel, Langebosch, Veendam-Noord, Wildervank, Ommelanderwijk, Zuidwending, Borgercompagnie',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Wildervank en Ommelanderwijk?', 'Ja. Wildervank ligt direct aan Veendam vast en Ommelanderwijk hoort bij dezelfde gemeente; beide vallen onder de indicatie van 40 tot 60 minuten. Vermeld de plaatsnaam, omdat straatnamen zoals Kerkstraat in de regio vaker voorkomen.'],
            ['Waarom duurt het in Veendam langer dan in Hoogezand?', 'Hoogezand ligt direct aan de A7 op een kwartier van de stad; voor Veendam komt daar de N33 en het stuk naar het centrum bij. De zones staan toegelicht op <a href="/bezorgtijden-groningen/">bezorgtijden Groningen</a>.'],
            ['Kan ik in Veendam een grote bestelling voor een feest laten bezorgen?', 'Ja. Voor een groot gezelschap raden we de 10KG aan, zodat je niet tijdens de avond hoeft bij te bestellen. Zie <a href="/product/lachgas-tank-10kg/">de lachgastank 10KG</a> voor de details; de prijs bevestigen we vooraf via WhatsApp.'],
        ],
        'nearby': ['hoogezand', 'winschoten', 'stadskanaal'],
        'lat': 53.106, 'lon': 6.878,
    },
    {
        'slug': 'stadskanaal', 'name': 'Stadskanaal', 'kind': 'stad',
        'title': 'Lachgas Stadskanaal | Bezorgd via WhatsApp, 24/7',
        'description': 'Lachgas bestellen in Stadskanaal? Lachgastanks en patronen bezorgd in Stadskanaal, Musselkanaal en Onstwedde, meestal binnen 40 tot 60 minuten.',
        'h1': 'Lachgas bezorgen in Stadskanaal',
        'lead': 'Lachgastanks bezorgd langs het kanaal in Stadskanaal en Musselkanaal, besteld via WhatsApp en meestal binnen 40 tot 60 minuten geleverd.',
        'intro': [
            'Stadskanaal is een langgerekte veenkoloniale plaats in het zuidoosten van de provincie Groningen, gebouwd langs het kanaal waaraan het zijn naam dankt. De Hoofdstraat volgt het water kilometers lang, met het Pagecentrum en theater Geert Teis als middelpunt en de wijken Maarsstee, Maarswold, Parkwijk en Ceresdorp eromheen. Wij bezorgen in heel Stadskanaal en ook in Musselkanaal, Onstwedde, Alteveer en Mussel. Een bestelling stuur je via WhatsApp met je adres en wat je nodig hebt; wij antwoorden met de prijs en een realistische aankomsttijd.',
            'Dit is een van de verste plaatsen in ons gebied. Vanuit Groningen gaat de rit over de A7 en de N33 tot Veendam en vervolgens over de N366 naar Stadskanaal, ruim veertig kilometer in totaal; een alternatief loopt via de N34 en Gieten. Daarom rekenen we hier meestal 40 tot 60 minuten, en voor Musselkanaal eerder het laatste deel van die marge. Een reguliere treinverbinding is er niet; de museumspoorlijn naar Veendam rijdt alleen op geplande dagen. De bus vanuit Groningen stopt langs de Hoofdstraat, wij komen tot aan de voordeur.',
            'In Stadskanaal en de omliggende dorpen zijn feesten vaak thuis of in een schuur, met voldoende ruimte. Kies in het <a href="/assortiment/">assortiment</a> het formaat dat bij het gezelschap past: de 2KG voor een kleine groep, de 4KG of 10KG voor een volle avond, en eventueel crackers en slagroompatronen erbij. Omdat de rit lang is, bevestigen we de prijs vooraf in WhatsApp en reken je bij levering af, contant of via Tikkie. Uitsluitend 18+, met ID-controle wanneer daar aanleiding voor is. Onze pagina over <a href="/lachgas-informatie/veilig-gebruik/">veilig gebruik</a> is het startpunt.',
        ],
        'wijken': 'Hoofdstraat, Pagecentrum, Maarsstee, Maarswold, Parkwijk, Ceresdorp, Stadskanaal-Noord, Musselkanaal, Onstwedde, Alteveer',
        'levertijd': 'meestal binnen 40 tot 60 minuten',
        'faq': [
            ['Bezorgen jullie ook in Musselkanaal en Onstwedde?', 'Ja, de hele gemeente Stadskanaal hoort bij ons gebied. Musselkanaal ligt nog zo’n acht kilometer verder langs het kanaal en Onstwedde ligt aan de oostkant; reken daar op de bovenkant van de 40 tot 60 minuten.'],
            ['Kan ik in Stadskanaal ook ’s nachts bestellen?', 'Ja, maar houd rekening met de afstand: ook ’s nachts blijft de rit via Veendam ruim een halfuur. Hoe dat werkt lees je op <a href="/lachgas-nachtbezorging/">nachtbezorging</a>.'],
            ['Zijn jullie sneller als ik via Emmen bestel?', 'Nee, wij rijden vanuit Groningen en niet vanuit Drenthe. Voor <a href="/bezorggebied/emmen/">Emmen</a> geldt dezelfde zone van 40 tot 60 minuten; Stadskanaal ligt voor ons zelfs iets gunstiger via de N33 en de N366.'],
        ],
        'nearby': ['veendam', 'oude-pekela', 'emmen'],
        'lat': 52.990, 'lon': 6.950,
    },
]
