# -*- coding: utf-8 -*-
"""Content voor lachgasrotterdam.nl, fase 2 (deel C): zeven Rotterdamse wijken,
de regiopagina Zuid-Holland en extra homepage-content.

Toegestane HTML in tekstvelden: strong en a (interne paden of drugsinfo.nl / rijksoverheid.nl / trimbos.nl).
"""

AREAS = [
    {
        "slug": "nesselande", "name": "Nesselande", "kind": "wijk",
        "title": "Lachgas Nesselande | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Nesselande? Snel en discreet bezorgd via WhatsApp aan de Boulevard, in de Waterwijk en rond metrostation Nesselande. 24/7, alleen 18+.",
        "h1": "Lachgas Nesselande",
        "lead": "Snel en discreet bezorgd in Nesselande, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Nesselande is de jongste wijk van Rotterdam en ligt helemaal in het noordoosten van de stad, aan de Zevenhuizerplas en tegen Nieuwerkerk aan den IJssel. De wijk valt onder het stadsgebied <a href="/lachgas-bestellen/prins-alexander/">Prins Alexander</a>, net als Zevenkamp en Ommoord. Wij bezorgen lachgastanks in heel Nesselande: op de Boulevard langs het water, in de Waterwijk met zijn grachten, in de Tuinenwijk en de Rietveldenwijk en rond het winkelcentrum aan de Siciliëboulevard. Je appt je adres, de gewenste maat en het tijdstip, en wij bevestigen wanneer we voor de deur staan.""",
            """Vanuit het centrum rijden we via de A20 tot afslag Nieuwerkerk aan den IJssel en dan over de Hoofdweg de wijk in, of binnendoor via de Capelseweg en de Hoofdweg langs Zevenkamp. Metrostation Nesselande is het eindpunt van lijn B, en de adressen rond de Laan van Avant-Garde en de Siciliëboulevard kennen onze bezorgers goed. Nesselande ligt aan de rand van Rotterdam, dus we rekenen op het hogere deel van de 20 tot 30 minuten; 's avonds en 's nachts is de A20 rustig en gaat het vaak sneller dan overdag.""",
            """Een verjaardag in een gezinswoning in de Waterwijk, een housewarming in een appartement aan de Boulevard of een avond met vrienden in de Rietveldenwijk: kies de <a href="/lachgas-tanks/">lachgastank</a> die past bij je groep, 2KG, 4KG of 10KG, altijd verzegeld geleverd. Afrekenen doe je bij levering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees vooraf de basisregels op <a href="/veilig-gebruik/">veilig gebruik</a> en houd er rekening mee dat lachgas in de openbare ruimte in Rotterdam niet is toegestaan.""",
        ],
        "wijken": "Boulevard, Waterwijk, Tuinenwijk, Rietveldenwijk, Siciliëboulevard, Laan van Avant-Garde, Zevenhuizerplas, metrostation Nesselande",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Nesselande, zo aan de rand van de stad?", "Meestal binnen 20 tot 30 minuten. Nesselande ligt verder van het centrum dan Kralingen of Prins Alexander, maar via de A20 en de Hoofdweg is de wijk goed bereikbaar. Je krijgt vooraf via WhatsApp een eerlijke indicatie."],
            ["Bezorgen jullie ook aan de Boulevard en bij de Zevenhuizerplas?", "Ja, in heel Nesselande, inclusief de Boulevard, de Waterwijk en de straten rond de Siciliëboulevard. Bij een appartementencomplex helpt het als je de verdieping en de naam op de bel meestuurt."],
            ["Kan ik lachgas bestellen voor een adres net over de grens in Nieuwerkerk?", """Zeker, Nieuwerkerk aan den IJssel hoort ook bij ons bezorggebied en ligt direct naast Nesselande. Kijk op <a href="/lachgas-bestellen/nieuwerkerk-aan-den-ijssel/">lachgas Nieuwerkerk aan den IJssel</a> voor de levertijd daar."""],
        ],
        "nearby": ["prins-alexander", "zevenkamp", "nieuwerkerk-aan-den-ijssel"],
        "lat": 51.966, "lon": 4.584,
    },
    {
        "slug": "ommoord", "name": "Ommoord", "kind": "wijk",
        "title": "Lachgas Ommoord | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Ommoord? Discreet bezorgd via WhatsApp bij Binnenhof, Hesseplaats, Romeynshof en de President Rooseveltweg. 24/7, alleen 18+.",
        "h1": "Lachgas Ommoord",
        "lead": "Snel en discreet bezorgd in Ommoord, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Ommoord ligt in het noordoosten van Rotterdam, tussen de Rotte en het Ommoordse Veld, en hoort bij het stadsgebied <a href="/lachgas-bestellen/prins-alexander/">Prins Alexander</a>. De wijk is in de jaren zestig en zeventig gebouwd en valt op door de hoge flats langs de President Rooseveltweg, met laagbouw en groene hofjes daaromheen. Lachgas Rotterdam bezorgt lachgastanks in heel Ommoord: rond winkelcentrum Binnenhof en de Hesseplaats, bij de Romeynshof, aan de John Mottweg en in de rustige straten richting de Rotte. Stuur een WhatsApp-bericht met je adres en de gewenste maat, dan hoor je direct wanneer we komen.""",
            """Vanuit het centrum rijden onze bezorgers via de A20 tot het Terbregseplein en dan over de President Rooseveltweg de wijk in, of via de Bosdreef en de Terbregseweg langs de Rotte. Metrolijn A heeft zijn eindpunt bij Binnenhof en stopt ook bij Romeynshof, en de adressen rond beide stations kennen we goed. De afstand tot het centrum is ruim tien kilometer, maar de route is overzichtelijk, zodat we Ommoord meestal binnen 20 tot 30 minuten halen. Op vrijdag- en zaterdagavond kan het rond het Terbregseplein druk zijn; je krijgt dan vooraf een realistische indicatie.""",
            """Of je nu een verjaardag viert op de twaalfde verdieping van een flat aan de Niels Bohrplaats of een avond met vrienden hebt in een eengezinswoning bij het Ommoordse Veld: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG en kies het formaat dat bij je gezelschap past. Elke tank wordt verzegeld geleverd, je betaalt bij levering contant of via Tikkie, en we leveren alleen aan volwassenen van 18 jaar en ouder. Op <a href="/veilig-gebruik/">veilig gebruik</a> lees je waar je op moet letten voordat je bestelt.""",
        ],
        "wijken": "Binnenhof, Hesseplaats, Romeynshof, President Rooseveltweg, John Mottweg, Niels Bohrplaats, Ommoordse Veld, Rotte-oever",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie ook in de hoge flats van Ommoord?", "Ja, we komen dagelijks in de flats langs de President Rooseveltweg en rond de Hesseplaats. Zet je verdieping en de naam bij de intercom in je bericht, dan staat de bezorger zonder zoeken bij de juiste deur."],
            ["Wat is de levertijd in Ommoord?", "Ook Ommoord halen we meestal binnen 20 tot 30 minuten. Via de A20 en het Terbregseplein zijn we snel aan de President Rooseveltweg; alleen op drukke weekendavonden kan het iets langer duren en dat melden we vooraf via WhatsApp."],
            ["Kan ik in Ommoord 's nachts bestellen?", """Ja, ook in Ommoord zijn we 24/7 bereikbaar via WhatsApp. 's Nachts is de weg vanuit het centrum rustig, dus de bezorgtijd is dan meestal eerder korter dan langer. Meer op <a href="/lachgas-nachtbezorging/">lachgas nachtbezorging</a>."""],
        ],
        "nearby": ["prins-alexander", "zevenkamp", "hillegersberg-schiebroek"],
        "lat": 51.955, "lon": 4.552,
    },
    {
        "slug": "zevenkamp", "name": "Zevenkamp", "kind": "wijk",
        "title": "Lachgas Zevenkamp | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Zevenkamp? Snel bezorgd via WhatsApp rond het Ambachtsplein, de Zevenkampse Ring en metrostation De Tochten. 24/7, alleen 18+.",
        "h1": "Lachgas Zevenkamp",
        "lead": "Snel en discreet bezorgd in Zevenkamp, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Zevenkamp ligt in Rotterdam-Oost, tussen Ommoord, Nesselande en de gemeentegrens met Capelle aan den IJssel, en hoort bij het stadsgebied <a href="/lachgas-bestellen/prins-alexander/">Prins Alexander</a>. De wijk is in de jaren tachtig gebouwd rond de Zevenkampse Ring, met het winkelcentrum aan het Ambachtsplein als middelpunt. Wij bezorgen lachgastanks in heel Zevenkamp: rond het Ambachtsplein, bij de metrostations De Tochten en Ambachtsland, langs de Zevenkampse Ring en in de woonerven daarbinnen. Je appt je adres en de gewenste maat, wij bevestigen het levermoment en het totaalbedrag.""",
            """Vanuit het centrum rijden we via de A20 tot afslag Prins Alexander en dan over de Capelseweg en de Hoofdweg de wijk in; vanaf Zuid gaat het via de Van Brienenoordbrug, de A16 en de A20. Metrolijn B stopt bij De Tochten en Ambachtsland, en de adressen rond die stations en langs de Zevenkampse Ring kennen onze bezorgers goed. Zevenkamp ligt een stuk verder van het centrum dan Kralingen, maar door de directe aansluiting op de A20 zitten we meestal gewoon binnen de 20 tot 30 minuten. In het weekend kan het op het Terbregseplein druk zijn; we laten je vooraf weten wat realistisch is.""",
            """Een verjaardag in een eengezinswoning aan de Zevenkampse Ring, een verhuisfeest in een appartement bij De Tochten of een rustige avond met vrienden: kies een <a href="/lachgas-tanks/">lachgastank</a> van 2KG, 4KG of 10KG, afhankelijk van hoe groot je groep is. We leveren de tank verzegeld aan de deur, je betaalt contant of via Tikkie bij aflevering en we vragen bij twijfel om een ID, want we leveren uitsluitend aan 18+. Lees voor je bestelt onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Ambachtsplein, Zevenkampse Ring, De Tochten, Ambachtsland, Hoofdweg, Capelseweg, Ommoordse Veld, Schollevaar (Capelle)",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie in alle woonerven van Zevenkamp?", "Ja, ook in de autoluwe woonerven binnen de Zevenkampse Ring. Omdat de nummering daar soms verspringt, helpt het als je een herkenningspunt of de dichtstbijzijnde zijstraat meestuurt in je WhatsApp-bericht."],
            ["Hoe lang moet ik in Zevenkamp wachten?", "Meestal 20 tot 30 minuten. Vanaf de A20 zijn we via de Capelseweg en de Hoofdweg snel in de wijk; bij drukte op het Terbregseplein hoor je vooraf een realistische tijd."],
            ["Ik woon in Zevenkamp maar het feest is in Capelle, kan dat?", """Natuurlijk. Capelle aan den IJssel grenst direct aan Zevenkamp en hoort bij ons vaste bezorggebied. Kijk op <a href="/lachgas-bestellen/capelle-aan-den-ijssel/">lachgas Capelle aan den IJssel</a> en geef in je bericht het adres door waar we moeten zijn."""],
        ],
        "nearby": ["prins-alexander", "nesselande", "ommoord"],
        "lat": 51.958, "lon": 4.572,
    },
    {
        "slug": "kop-van-zuid", "name": "Kop van Zuid", "kind": "wijk",
        "title": "Lachgas Kop van Zuid | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen op de Kop van Zuid? Discreet bezorgd via WhatsApp op de Wilhelminapier, bij de Entrepothaven en de Laan op Zuid. 24/7, alleen 18+.",
        "h1": "Lachgas Kop van Zuid",
        "lead": "Snel en discreet bezorgd op de Kop van Zuid, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """De Kop van Zuid is het nieuwe stadshart aan de zuidkant van de Nieuwe Maas, direct over de Erasmusbrug, en valt onder het stadsgebied <a href="/lachgas-bestellen/feijenoord/">Feijenoord</a>. Hoogbouw als De Rotterdam en Montevideo op de Wilhelminapier, de appartementen rond de Entrepothaven en de Landtong, de nieuwere blokken aan de Laan op Zuid en de Posthumalaan: Lachgas Rotterdam bezorgt lachgastanks op al deze adressen. Stuur een bericht via WhatsApp met je adres, de gewenste maat en het tijdstip, dan bevestigen we direct het levermoment. Vergeet bij een appartementencomplex niet je verdieping en de intercomnaam mee te sturen.""",
            """Vanuit het centrum is het voor onze bezorgers een kwestie van de Erasmusbrug of de Maastunnel oversteken; vanaf de A16 nemen we de Van Brienenoordbrug en de Laan op Zuid. Metrostations Wilhelminaplein en Rijnhaven liggen midden in de wijk op de lijnen D en E, en de watertaxi legt aan bij Hotel New York. Omdat de Kop van Zuid pal tegen het centrum ligt, horen de adressen hier bij de snelste van ons hele bezorggebied: meestal ruim binnen de 20 tot 30 minuten. Alleen bij grote evenementen op de Wilhelminapier kan het parkeren wat extra tijd kosten.""",
            """Een housewarming in een appartement aan de Wilhelminakade, een verjaardag in een loft in het Entrepotgebouw of een avond met vrienden rond het Deliplein in buurwijk Katendrecht: kies de <a href="/lachgas-tanks/">lachgastank</a> die past bij je gezelschap, 2KG, 4KG of 10KG. We leveren verzegeld en onopvallend aan de deur, je betaalt bij aflevering contant of via Tikkie, en we controleren bij twijfel op leeftijd: alleen 18+. Lees vooraf onze uitleg over <a href="/veilig-gebruik/">veilig gebruik</a>, zeker als je in een hoog gebouw woont en de tank met de lift mee moet.""",
        ],
        "wijken": "Wilhelminapier, Wilhelminakade, Entrepothaven, Landtong, Laan op Zuid, Posthumalaan, Rijnhaven, Katendrecht, Stieltjesstraat",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Bezorgen jullie in de torens op de Wilhelminapier?", "Ja, in De Rotterdam, Montevideo, New Orleans en de andere woontorens op de pier komen we regelmatig. Geef je verdieping en de naam bij de intercom door, dan meldt de bezorger zich beneden en komt hij naar boven of wacht hij bij de ingang, wat jij wilt."],
            ["Hoe snel zijn jullie op de Kop van Zuid?", "De Kop van Zuid ligt direct over de Erasmusbrug, dus meestal aan de snelle kant van de 20 tot 30 minuten. Bij evenementen op de Wilhelminapier of een afgesloten brug kan het iets langer duren; je hoort het vooraf via WhatsApp."],
            ["Kan ik ook laten bezorgen in Katendrecht of de Afrikaanderwijk?", """Zeker, beide wijken grenzen aan de Kop van Zuid en horen bij hetzelfde stadsgebied. Kijk op <a href="/lachgas-bestellen/feijenoord/">lachgas Feijenoord</a> of stuur gewoon het adres via WhatsApp, dan regelen we het."""],
        ],
        "nearby": ["feijenoord", "centrum", "charlois"],
        "lat": 51.905, "lon": 4.491,
    },
    {
        "slug": "blijdorp", "name": "Blijdorp", "kind": "wijk",
        "title": "Lachgas Blijdorp | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Blijdorp? Snel en discreet bezorgd via WhatsApp aan de Statenweg, rond het Vroesenpark en in Bergpolder. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Blijdorp",
        "lead": "Snel en discreet bezorgd in Blijdorp, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Blijdorp ligt direct ten noorden van Rotterdam Centraal, tussen de Statenweg, de Gordelweg en de spoorlijn naar Den Haag, en hoort bij het stadsgebied <a href="/lachgas-bestellen/noord/">Rotterdam Noord</a>. De wijk is vooral bekend van Diergaarde Blijdorp, maar bestaat verder uit statige jaren-dertig-bouw rond de Statenweg, de Stadhoudersweg en het Vroesenpark. Lachgas Rotterdam bezorgt lachgastanks in heel Blijdorp: aan de Statensingel en de Statenweg, in de straten rond de Bentincklaan, bij het Roel Langerakpark en in het aangrenzende Bergpolder en Liskwartier. Appen met je adres en de gewenste maat is genoeg; wij bevestigen het levermoment.""",
            """Vanuit het centrum is Blijdorp een paar minuten rijden via de Schiekade of de Statenweg; vanaf de A20 nemen we afslag Rotterdam-Centrum en komen we via de Stadhoudersweg de wijk binnen. Metrostation Blijdorp op lijn E ligt aan de kop van de Statenweg, op loopafstand van Centraal Station. Omdat onze bezorgers vaak al in en rond het centrum rijden, hoort Blijdorp bij de snelst bereikbare wijken van de stad, meestal aan de onderkant van de 20 tot 30 minuten. Parkeren in de smalle zijstraten kost soms even tijd, maar je ziet via WhatsApp precies wanneer we er zijn.""",
            """Een verjaardag in een bovenwoning aan de Stadhoudersweg, een housewarming in Bergpolder of een avond met vrienden in een appartement bij het Vroesenpark: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG en geef in je bericht aan welke je wilt. Elke tank is verzegeld, betalen kan bij levering contant of via Tikkie en we leveren alleen aan 18+. Lachgas gebruiken in het Vroesenpark of op straat is in Rotterdam verboden; houd het dus binnen en lees vooraf onze <a href="/veilig-gebruik/">tips voor veilig gebruik</a>.""",
        ],
        "wijken": "Statenweg, Statensingel, Stadhoudersweg, Vroesenpark, Bentincklaan, Roel Langerakpark, Gordelweg, Bergpolder, Liskwartier, metrostation Blijdorp",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe snel kunnen jullie in Blijdorp zijn?", "Blijdorp ligt direct naast Rotterdam Centraal, dus meestal aan de snelle kant van de 20 tot 30 minuten. Het enige dat soms tijd kost is parkeren in de smalle straten rond de Statenweg; we appen je zodra we voor de deur staan."],
            ["Bezorgen jullie ook in Bergpolder en het Liskwartier?", "Ja, die buurten liggen direct naast Blijdorp en vallen onder hetzelfde stadsgebied Noord. Stuur je straat en huisnummer mee, dan bevestigen we meteen."],
            ["Mag ik lachgas meenemen naar het Vroesenpark?", """Nee. Rotterdam heeft een verbod op lachgasgebruik in de openbare ruimte en lachgas staat sinds 2023 op lijst II van de Opiumwet. Wij bezorgen alleen op een woonadres. Lees meer op <a href="/lachgas-informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a>."""],
        ],
        "nearby": ["noord", "centrum", "overschie"],
        "lat": 51.930, "lon": 4.455,
    },
    {
        "slug": "pernis", "name": "Pernis", "kind": "wijk",
        "title": "Lachgas Pernis | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Pernis? Discreet bezorgd via WhatsApp in het hele dorp, van de Ring en de Pastoriedijk tot metrostation Pernis. 24/7, alleen 18+.",
        "h1": "Lachgas Pernis",
        "lead": "Snel en discreet bezorgd in Pernis, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Pernis is een dorp binnen de gemeente Rotterdam, op de zuidoever van de Nieuwe Maas tussen de Waalhaven, de Beneluxtunnel en de raffinaderijen van de Botlek. Het is een eigen gebied van Rotterdam, met <a href="/lachgas-bestellen/hoogvliet/">Hoogvliet</a> en <a href="/lachgas-bestellen/charlois/">Charlois</a> als buren. Lachgas Rotterdam bezorgt lachgastanks in heel Pernis: in het oude dorp rond de Ring en de Pastoriedijk, in de straten rond de Burgemeester van Esstraat en de Ozingastraat, aan de G.A. Soetemanweg en langs de Uiterdijk. Het dorp is compact en onze bezorgers kennen er de weg; stuur je adres en de gewenste maat via WhatsApp en wij bevestigen het levermoment.""",
            """Vanuit Rotterdam-centrum rijden we via de Maastunnel en de A15, of via de A4, tot afslag Pernis en dan de Vondelingenweg op; vanaf Hoogvliet komen we via de Groene Kruisweg. Metrostation Pernis ligt op lijn C aan de rand van het dorp, met de Beneluxtunnel vlak ernaast. Pernis ligt ingeklemd tussen snelwegen en havens, dus de aanrijroute is snel en overzichtelijk, ook 's nachts als het industriegebied stil is. Daardoor halen we ook hier meestal 20 tot 30 minuten, al kan het bij werkzaamheden in de Beneluxtunnel of op de A15 een stuk langer duren; dat melden we dan vooraf.""",
            """Een verjaardag in een rijtjeshuis aan de Ring, een avond met vrienden in een bovenwoning bij de Pastoriedijk of een groter feest in een vrijstaand huis aan de Uiterdijk: kies een <a href="/lachgas-tanks/">lachgastank</a> van 2KG, 4KG of 10KG en geef dat in je bericht aan. Je ontvangt de tank verzegeld en onopvallend aan de deur, betaalt contant of via Tikkie bij aflevering en laat bij twijfel je ID zien, want we leveren alleen aan 18+. Lees vooraf onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a>, ook over het bewaren van de tank.""",
        ],
        "wijken": "Ring, Pastoriedijk, Burgemeester van Esstraat, Ozingastraat, G.A. Soetemanweg, Uiterdijk, Vondelingenweg, metrostation Pernis",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Komen jullie wel helemaal naar Pernis?", "Ja, Pernis hoort gewoon bij Rotterdam en bij ons vaste bezorggebied. Via de A15 of de A4 zijn we er snel; meestal binnen 20 tot 30 minuten, tenzij er werkzaamheden zijn in de Beneluxtunnel."],
            ["Bezorgen jullie ook op de bedrijventerreinen rond Pernis?", "Nee, we bezorgen uitsluitend op woonadressen in het dorp zelf, niet op industrieterreinen of in de haven. Lachgastanks zijn bij ons alleen voor particulier gebruik door volwassenen."],
            ["Kan ik vanuit Pernis ook voor een adres in Hoogvliet bestellen?", """Ja, Hoogvliet ligt een paar minuten verderop en hoort bij ons bezorggebied. Kijk op <a href="/lachgas-bestellen/hoogvliet/">lachgas Hoogvliet</a> of stuur het adres direct via WhatsApp."""],
        ],
        "nearby": ["hoogvliet", "charlois", "rozenburg"],
        "lat": 51.888, "lon": 4.389,
    },
    {
        "slug": "lombardijen", "name": "Lombardijen", "kind": "wijk",
        "title": "Lachgas Lombardijen | 20-30 min bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Lombardijen? Snel bezorgd via WhatsApp rond station Lombardijen, de Spinozaweg, Molièreweg en Pascalweg. 24/7, alleen 18+.",
        "h1": "Lachgas Lombardijen",
        "lead": "Snel en discreet bezorgd in Lombardijen, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Lombardijen ligt in Rotterdam-Zuid, tussen de Vaanweg, de spoorlijn naar Dordrecht en de Smeetslandseweg, en hoort bij het stadsgebied <a href="/lachgas-bestellen/ijsselmonde/">IJsselmonde</a>. De wijk is in de jaren vijftig en zestig gebouwd en de straten dragen namen van schrijvers en filosofen: Spinozaweg, Molièreweg, Pascalweg, Homerusstraat en Dantestraat. Lachgas Rotterdam bezorgt lachgastanks in heel Lombardijen, van de flats rond station Lombardijen tot de portiekwoningen rond het Spinozapark en de eengezinswoningen richting Groot-IJsselmonde. Je stuurt een WhatsApp-bericht met je adres en de gewenste maat, wij bevestigen tijdstip en totaalbedrag.""",
            """Vanuit het centrum rijden we via de Maastunnel of de Erasmusbrug en dan over de Pleinweg en de Vaanweg de wijk in, of via de A16 en het Vaanplein als we vanaf de ring komen. Station Rotterdam Lombardijen heeft sprinters richting Dordrecht en Den Haag, en tram 25 rijdt over de Spinozaweg dwars door de wijk. Lombardijen ligt dicht bij het Vaanplein, waar de A15 en de A16 elkaar kruisen, dus ook vanuit Barendrecht of Ridderkerk zijn we er snel. Meestal halen we 20 tot 30 minuten; in de avondspits rond het Vaanplein kan het iets langer duren en dat melden we vooraf.""",
            """Een verjaardag in een portiekflat aan de Molièreweg, een avond met vrienden in een eengezinswoning bij het Spinozapark of een feest in een bovenwoning aan de Pascalweg: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG en zet je keuze in je bericht. Verzegeld geleverd, afrekenen aan de deur contant of via Tikkie, en uitsluitend voor volwassenen vanaf 18 jaar; bij twijfel vragen we om een legitimatie. Op <a href="/veilig-gebruik/">veilig gebruik</a> staan de basisregels die je wilt kennen voordat we aanbellen.""",
        ],
        "wijken": "Spinozaweg, Spinozapark, Molièreweg, Pascalweg, Homerusstraat, Dantestraat, Smeetslandseweg, Vaanweg, station Lombardijen",
        "levertijd": "meestal binnen 20 tot 30 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Lombardijen?", "In Lombardijen is dat meestal 20 tot 30 minuten. Via de Vaanweg of de A16 en het Vaanplein zijn we snel in de wijk; alleen in de avondspits kan het rond het Vaanplein wat drukker zijn en dan geven we vooraf een eerlijke tijd door."],
            ["Bezorgen jullie ook bij station Lombardijen en in de flats daar?", "Ja, de flats rond het station en langs de Spinozaweg kennen we goed. Stuur je verdieping en de naam op de bel mee, dan hoeft de bezorger niet te zoeken."],
            ["Ik woon net over de grens in Barendrecht, bezorgen jullie daar ook?", """Zeker, Barendrecht ligt direct ten zuiden van Lombardijen en hoort bij ons bezorggebied; reken daar op iets meer tijd. Kijk op <a href="/lachgas-bestellen/barendrecht/">lachgas Barendrecht</a> voor de details."""],
        ],
        "nearby": ["ijsselmonde", "barendrecht", "ridderkerk"],
        "lat": 51.883, "lon": 4.530,
    },
]

REGIO = {
    "title": "Lachgas Zuid-Holland | Regio Rotterdam 24/7 bezorgd",
    "description": "Lachgas bezorgen in Zuid-Holland: heel Rotterdam en ruim 25 plaatsen van Westland tot Dordrecht, Delft, Zoetermeer en Gouda. 24/7 via WhatsApp, alleen 18+.",
    "h1": "Lachgas bezorgen in Zuid-Holland",
    "lead": "Vanuit Rotterdam bezorgen we lachgastanks in een groot deel van Zuid-Holland, 24/7 via WhatsApp. Kies hieronder je plaats of wijk.",
    "intro": [
        """Lachgas Rotterdam is begonnen als bezorgservice voor de stad zelf, maar rijdt inmiddels een flink stuk van Zuid-Holland. Het bezorggebied omvat heel Rotterdam, van Hoek van Holland tot Nesselande en van Overschie tot Hoogvliet, plus de regio daaromheen: het Westland met Naaldwijk, de steden langs de Nieuwe Maas zoals Schiedam, Vlaardingen en Maassluis, Lansingerland, Delft, Zoetermeer en Gouda in het noorden, en in het zuiden de Drechtsteden met Dordrecht en Zwijndrecht, de Hoeksche Waard rond Oud-Beijerland en Voorne-Putten met Spijkenisse, Hellevoetsluis en Brielle. Op deze pagina vind je elke plaats en wijk met een eigen pagina.""",
        """De levertijd hangt samen met de afstand tot Rotterdam. In de stad zelf, inclusief wijken als Blijdorp, Kop van Zuid of Ommoord, is dat meestal binnen 20 tot 30 minuten. In de buurgemeenten, zoals Schiedam, Capelle aan den IJssel, Barendrecht of Berkel en Rodenrijs, rekenen we meestal op 25 tot 40 minuten. Voor plaatsen verder weg, denk aan Dordrecht, Gouda, Zoetermeer, Hellevoetsluis of Naaldwijk, is het meestal 35 tot 50 minuten. We zijn 24/7 bereikbaar via WhatsApp, ook 's nachts en in het weekend, en je hoort vooraf de prijs inclusief bezorging, zodat je weet waar je aan toe bent voordat we vertrekken.""",
        """Bestellen werkt in de hele regio hetzelfde: je stuurt een WhatsApp-bericht met je adres, de gewenste tankmaat en het tijdstip, wij bevestigen de prijs en de verwachte levertijd en komen naar je deur. Hoe dat precies gaat lees je op <a href="/werkwijze/">onze werkwijze</a>. Je kiest uit <a href="/lachgas-tanks/">lachgastanks</a> van 2KG, 4KG en 10KG, die altijd verzegeld worden geleverd. Betalen doe je bij levering, contant of via Tikkie. We leveren uitsluitend aan volwassenen van 18 jaar en ouder en vragen bij twijfel om een geldig ID, ongeacht in welke plaats je woont.""",
    ],
    "groups": [
        {"h2": "Rotterdam en directe omgeving", "text": "Alle stadsgebieden en wijken van Rotterdam, van Hoek van Holland tot Nesselande, meestal binnen 20 tot 30 minuten bezorgd.", "slugs": ["centrum", "noord", "kralingen-crooswijk", "delfshaven", "feijenoord", "ijsselmonde", "charlois", "prins-alexander", "hillegersberg-schiebroek", "overschie", "hoogvliet", "hoek-van-holland", "nesselande", "ommoord", "zevenkamp", "kop-van-zuid", "blijdorp", "pernis", "lombardijen", "rozenburg"]},
        {"h2": "Rijnmond en Lansingerland", "text": "De buurgemeenten langs de Nieuwe Maas, de Hollandsche IJssel en in Lansingerland, meestal binnen 25 tot 40 minuten.", "slugs": ["schiedam", "vlaardingen", "maassluis", "capelle-aan-den-ijssel", "krimpen-aan-den-ijssel", "nieuwerkerk-aan-den-ijssel", "berkel-en-rodenrijs", "bergschenhoek", "bleiswijk", "pijnacker"]},
        {"h2": "Zuid en Drechtsteden", "text": "Ten zuiden van Rotterdam, van Barendrecht en Rhoon tot de Drechtsteden en de Hoeksche Waard, met oplopende levertijd naarmate je verder van de stad woont.", "slugs": ["barendrecht", "ridderkerk", "rhoon", "hendrik-ido-ambacht", "zwijndrecht", "dordrecht", "oud-beijerland"]},
        {"h2": "Voorne-Putten en Westland", "text": "Spijkenisse ligt dicht bij de stad; voor Hellevoetsluis, Brielle en het Westland rekenen we op meer reistijd.", "slugs": ["spijkenisse", "hellevoetsluis", "brielle", "naaldwijk"]},
        {"h2": "Delft, Zoetermeer en Gouda", "text": "De grotere steden ten noorden en oosten van Rotterdam, meestal binnen 35 tot 50 minuten via de A13, de A12 en de A20.", "slugs": ["delft", "zoetermeer", "gouda"]},
    ],
    "faq": [
        ["Bezorgen jullie ook buiten Rotterdam?", "Ja. Naast heel Rotterdam bezorgen we in ruim 25 plaatsen in Zuid-Holland, van het Westland en Delft tot Zoetermeer, Gouda, Dordrecht, de Hoeksche Waard en Voorne-Putten. Elke plaats heeft een eigen pagina met de levertijd die daar meestal geldt."],
        ["Wat kost bezorgen in de regio?", "Je hoort het totaalbedrag vooraf in je WhatsApp-gesprek, inclusief bezorging, voordat we vertrekken. Zo zijn er geen verrassingen aan de deur, ook niet als je verder van Rotterdam woont."],
        ["Tot hoe laat kan ik 's nachts bestellen in de regio?", """We zijn 24/7 bereikbaar via WhatsApp, dus ook midden in de nacht en in het weekend, in de hele regio. 's Nachts zijn de snelwegen rustig, waardoor de levertijd buiten de stad vaak gunstiger uitvalt dan overdag. Lees meer op <a href="/lachgas-nachtbezorging/">lachgas nachtbezorging</a>."""],
        ["Mijn plaats staat er niet bij, kunnen jullie toch komen?", "Stuur je postcode via WhatsApp. Ligt je adres binnen een redelijke afstand van ons bezorggebied, dan laten we direct weten of het lukt en wat de verwachte levertijd is. Zo niet, dan zeggen we dat eerlijk."],
        ["Is er een minimumbestelling voor bezorging buiten Rotterdam?", "Er is geen vaste eis. Voor adressen verder weg bevestigen we vooraf of het haalbaar is op dat moment, bijvoorbeeld afhankelijk van de drukte en de afstand, en je hoort meteen de prijs en de levertijd."],
    ],
}

HOME = {
    "regio_badge": "Ook in de regio",
    "regio_h2": "Lachgas bezorgd in heel Zuid-Holland",
    "regio_text": "Niet alleen in Rotterdam: we bezorgen van het Westland tot Dordrecht en van Delft via Zoetermeer tot Gouda. In de buurgemeenten meestal binnen 25 tot 40 minuten, verder weg meestal binnen 35 tot 50 minuten.",
    "compare_badge": "Eerlijk vergelijken",
    "compare_h2": "Waar let je op bij een lachgas bezorgservice in Rotterdam?",
    "compare_text": "Niet elke bezorgservice werkt hetzelfde. Dit zijn de punten die volgens ons het verschil maken, en hoe wij ze invullen.",
    "compare_rows": [
        ["Bereikbaarheid", "24/7 via WhatsApp, ook 's nachts en in het weekend", "Alleen avond of weekend"],
        ["Levertijd in de stad", "Meestal 20 tot 30 minuten, vooraf aangegeven", "Onduidelijk of 'zo snel mogelijk'"],
        ["Prijs", "Vooraf bevestigd in je WhatsApp-gesprek, geen verrassingen", "Pas bekend aan de deur"],
        ["Tanks", "Verzegeld geleverd, 2KG, 4KG en 10KG", "Niet altijd verzegeld"],
        ["Bezorggebied", "Heel Rotterdam en ruim 25 plaatsen in Zuid-Holland", "Alleen de stad"],
        ["Discretie", "Onopvallende bezorging aan de deur, geen opdruk", "Wisselend"],
        ["Leeftijdscontrole", "Altijd 18+, we vragen om een ID bij twijfel", "Niet altijd"],
        ["Informatie", "Eerlijke uitleg over risico's, bewaren en regels", "Alleen verkoop"],
    ],
    "faq_extra": [
        ["Bezorgen jullie ook buiten Rotterdam?", """Ja, we bezorgen in ruim 25 plaatsen in Zuid-Holland: van Schiedam, Vlaardingen en Capelle tot Delft, Zoetermeer, Gouda, Dordrecht en Voorne-Putten. Reken buiten de stad op iets meer tijd. Bekijk alle plaatsen op <a href="/bezorggebieden/">bezorggebieden</a>."""],
        ["Hoe weet ik dat de tank vol en verzegeld is?", """Elke tank wordt met een intacte verzegeling geleverd en je controleert die samen met de bezorger aan de deur. Is de zegel beschadigd, dan neem je de tank niet aan en wisselen we hem om. Meer over de maten lees je op <a href="/lachgas-tanks/">lachgastanks</a>."""],
        ["Kan ik voor een feest of evenement vooraf reserveren?", """Ja, stuur ons via WhatsApp de datum, het adres en het aantal tanks dat je verwacht nodig te hebben, dan plannen we de levering in en bevestigen we de prijs vooraf. Lees meer op <a href="/lachgas-feest-evenement/">lachgas voor een feest of evenement</a>."""],
        ["Wat doe ik met een lege tank?", """Gooi een lege tank nooit bij het restafval of in de glasbak; het is een drukhouder. Bewaar hem rechtop op een koele plek en lever hem in bij de milieustraat van je gemeente, of vraag ons via WhatsApp wat de mogelijkheden zijn. Meer op <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">tank bewaren en vervoeren</a>."""],
        ["Is lachgas legaal in Nederland?", """Lachgas staat sinds 1 januari 2023 op lijst II van de Opiumwet. Verkoop en bezit voor recreatief gebruik zijn verboden; er gelden uitzonderingen voor medisch, technisch en voedingsgebruik. Wij leveren uitsluitend aan volwassenen en informeren je eerlijk over de regels. Lees onze uitleg op <a href="/lachgas-informatie/is-lachgas-legaal-in-nederland/">is lachgas legaal in Nederland</a> en kijk voor de actuele regels op <a href="https://www.rijksoverheid.nl">rijksoverheid.nl</a>."""],
        ["Waarom bestellen via WhatsApp en niet via een webshop?", """Omdat we je dan direct kunnen helpen: je krijgt binnen een paar minuten een bevestiging van de prijs en de levertijd, je kunt vragen stellen over de maat en we checken meteen of je adres binnen ons bezorggebied ligt. Geen account, geen wachtwoord, geen bestelling die in een wachtrij verdwijnt. Hoe het werkt lees je op <a href="/werkwijze/">onze werkwijze</a>."""],
    ],
}
