# -*- coding: utf-8 -*-
"""Gebieden fase 2 (deel B) voor lachgasrotterdam.nl: Drechtsteden, Gouda, Lansingerland, Pijnacker-Nootdorp, Westland en Hoeksche Waard."""

AREAS = [
    {
        "slug": "dordrecht", "name": "Dordrecht", "kind": "stad",
        "title": "Lachgas Dordrecht | 24/7 bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Dordrecht? Discreet bezorgd via WhatsApp in de Binnenstad, Krispijn, Sterrenburg en Stadspolders. 24/7 bereikbaar, alleen voor 18+.",
        "h1": "Lachgas Dordrecht",
        "lead": "Snel en discreet bezorgd in Dordrecht, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Dordrecht is de oudste stad van Holland en ligt op het Eiland van Dordrecht, waar de Oude Maas, de Noord, de Beneden-Merwede en de Dordtsche Kil samenkomen. Wij bezorgen lachgastanks in de hele stad: in de historische binnenstad rond de Voorstraat, de Grote Kerk en het Scheffersplein, in Oud- en Nieuw-Krispijn, Wielwijk en Crabbehof, in Sterrenburg en Dubbeldam, in Stadspolders en Reeland en op De Staart. Stuur via WhatsApp je adres, de gewenste maat en het tijdstip; wij bevestigen het levermoment en de prijs en rijden naar je toe.""",
            """Vanuit Rotterdam rijden we via de A16 over de Van Brienenoordbrug, langs Ridderkerk en Zwijndrecht en door de Drechttunnel het Eiland van Dordrecht op; voor Stadspolders en Dubbeldam pakken we de N3. Treinen vanuit Rotterdam Centraal en Blaak stoppen op Dordrecht Centraal, Dordrecht Zuid en Dordrecht Stadspolders, en de Waterbus vaart van de Erasmusbrug naar de Merwekade. Dordrecht ligt een flink stuk verder dan onze stadswijken, dus de rit duurt meestal 35 tot 50 minuten; het precieze tijdstip hoor je vooraf.""",
            """Een huisfeest in een pand aan de Wijnhaven, een verjaardag in een gezinswoning in Sterrenburg of een avond met vrienden in Stadspolders: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> in 2KG, 4KG en 10KG en kies het formaat dat bij je gezelschap past. Voor een 10KG tank stemmen we de levering vooraf af. Je betaalt bij aflevering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees vooraf onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Binnenstad, Voorstraat, Krispijn, Wielwijk, Crabbehof, Sterrenburg, Dubbeldam, Stadspolders, Reeland, De Staart",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Dordrecht?", "Meestal binnen 35 tot 50 minuten. We komen vanuit Rotterdam via de A16 en de Drechttunnel, dus reken op meer reistijd dan in de Drechtsteden aan de noordkant van de Oude Maas. Je krijgt vooraf via WhatsApp een eerlijke indicatie."],
            ["Bezorgen jullie in heel Dordrecht, ook in Sterrenburg en Dubbeldam?", "Ja, we bezorgen op het hele Eiland van Dordrecht: van de binnenstad en Krispijn tot Sterrenburg, Dubbeldam, Stadspolders en De Staart. Stuur je postcode mee, dan bevestigen we direct of en hoe laat we kunnen komen."],
            ["Kan ik in Dordrecht ook 's nachts of in het weekend bestellen?", """Ja, we zijn 24/7 bereikbaar via WhatsApp. Houd 's nachts rekening met de rijtijd vanuit Rotterdam. Lees meer op <a href="/lachgas-nachtbezorging/">lachgas 's nachts</a>."""],
        ],
        "nearby": ["zwijndrecht", "hendrik-ido-ambacht", "ridderkerk"],
        "lat": 51.813, "lon": 4.690,
    },
    {
        "slug": "zwijndrecht", "name": "Zwijndrecht", "kind": "stad",
        "title": "Lachgas Zwijndrecht | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Zwijndrecht? Snel en discreet bezorgd via WhatsApp in Centrum, Walburg, Kort Ambacht en Heerjansdam. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Zwijndrecht",
        "lead": "Snel en discreet bezorgd in Zwijndrecht, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Zwijndrecht ligt aan de noordoever van de Oude Maas, recht tegenover de Dordtse binnenstad, en is de eerste Drechtstad die je vanaf Rotterdam bereikt. We bezorgen lachgastanks in het centrum rond het Veerplein en de Maasboulevard, in Walburg bij het gelijknamige winkelcentrum, in Kort Ambacht, Nederhoven en Zwijndrecht-Noord, in Heer Oudelands Ambacht en in het dorp Heerjansdam aan de westkant van de gemeente. Je appt je adres, de gewenste maat en het tijdstip, wij bevestigen en komen naar je deur.""",
            """Vanuit Rotterdam volgen we de A16 over de Van Brienenoordbrug en nemen we vlak voor de Drechttunnel de afslag Zwijndrecht; voor Heerjansdam rijden we via Barendrecht en de Lindtsedijk. Station Zwijndrecht ligt aan de spoorlijn Rotterdam–Dordrecht en de adressen rond de Koninginneweg en de Burgemeester de Bruïnelaan kennen onze bezorgers goed. Omdat we de tunnel niet door hoeven, ben je in Zwijndrecht meestal eerder aan de beurt dan in Dordrecht.""",
            """Een verjaardag in een flat in Walburg, een avond met vrienden in Kort Ambacht of een tuinfeest in Heerjansdam: kies een <a href="/lachgas-tanks/">lachgastank</a> van 2KG, 4KG of 10KG, afhankelijk van de grootte van je groep. De tank komt verzegeld aan, je rekent af bij de deur, contant of via Tikkie, en we leveren alleen aan 18+. Bekijk ook onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Zwijndrecht Centrum, Veerplein, Maasboulevard, Walburg, Kort Ambacht, Nederhoven, Zwijndrecht-Noord, Heer Oudelands Ambacht, Heerjansdam",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Zwijndrecht?", "Meestal binnen 25 tot 40 minuten. Zwijndrecht ligt direct langs de A16, nog voor de Drechttunnel, dus we zijn er sneller dan in Dordrecht. Op drukke avonden hoor je vooraf via WhatsApp hoe laat we er zijn."],
            ["Bezorgen jullie ook in Heerjansdam?", "Ja, Heerjansdam hoort bij de gemeente Zwijndrecht en dus bij ons bezorggebied. Stuur je postcode mee in je bericht, dan bevestigen we direct het levermoment."],
            ["Hoe weet ik wat ik in Zwijndrecht betaal?", """Je krijgt het totaalbedrag inclusief bezorging vooraf via WhatsApp, voordat we vertrekken. Betalen doe je bij levering, contant of via Tikkie. Alle stappen staan op onze pagina <a href="/werkwijze/">werkwijze</a>."""],
        ],
        "nearby": ["dordrecht", "hendrik-ido-ambacht", "barendrecht"],
        "lat": 51.817, "lon": 4.633,
    },
    {
        "slug": "gouda", "name": "Gouda", "kind": "stad",
        "title": "Lachgas Gouda | 24/7 bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Gouda? Discreet bezorgd via WhatsApp in de Binnenstad, Korte Akkeren, Bloemendaal en Goverwelle. 24/7 bereikbaar, alleen voor 18+.",
        "h1": "Lachgas Gouda",
        "lead": "Snel en discreet bezorgd in Gouda, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Gouda ligt aan de Hollandsche IJssel en de Gouwe, aan de oostrand van ons bezorggebied. We bezorgen lachgastanks in de binnenstad rond de Markt, het stadhuis en de Sint-Janskerk, in Korte Akkeren en het Nieuwe Park, in Bloemendaal en Plaswijck aan de noordkant, in Kort Haarlem, Oosterwei en Goverwelle aan de oostkant en in de nieuwe wijk Westergouwe richting Moordrecht. Een WhatsApp-bericht met je adres, de gewenste maat en het tijdstip is genoeg; wij bevestigen en komen langs.""",
            """Vanuit Rotterdam rijden we de A20 helemaal af, voorbij Nieuwerkerk aan den IJssel en Moordrecht, en nemen we de afslag Gouda bij de Goudse Poort of rijden we bij knooppunt Gouwe een kort stuk A12 richting Utrecht. De sprinter en intercity vanuit Rotterdam stoppen op Gouda en Gouda Goverwelle, dus de buurten rond het station en de Burgemeester Jamessingel vinden we blind. Gouda ligt op ruim 25 kilometer van Rotterdam-centrum; daarom rekenen we hier op 35 tot 50 minuten.""",
            """Een verjaardag in een grachtenhuis aan de Turfmarkt, een avond met vrienden in Goverwelle of een feest in een nieuwbouwwoning in Westergouwe: op de pagina <a href="/lachgas-tanks/">lachgastanks</a> zie je het verschil tussen 2KG, 4KG en 10KG. Betalen kan bij aflevering, contant of via Tikkie, en we leveren uitsluitend aan volwassenen van 18 jaar en ouder. Lees voor je bestelt onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Binnenstad, Markt, Korte Akkeren, Nieuwe Park, Bloemendaal, Plaswijck, Kort Haarlem, Oosterwei, Goverwelle, Westergouwe",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Gouda?", "Meestal binnen 35 tot 50 minuten. Gouda ligt aan het einde van de A20, voorbij Nieuwerkerk en Moordrecht, dus we zijn langer onderweg dan in de buurgemeenten van Rotterdam. Je krijgt vooraf via WhatsApp een eerlijke indicatie."],
            ["Bezorgen jullie ook in Goverwelle en Westergouwe?", "Ja, in alle wijken van Gouda, van Goverwelle in het oosten tot de nieuwbouw in Westergouwe in het westen. Stuur je postcode via WhatsApp en we bevestigen direct of en hoe laat we kunnen komen."],
            ["Is een grote tank in Gouda ook mogelijk?", """Ja, ook de 4KG en 10KG tank bezorgen we in Gouda. Voor een 10KG tank plannen we de levering vooraf in via WhatsApp. Lees meer op <a href="/lachgas-feest-evenement/">feest en evenement</a>."""],
        ],
        "nearby": ["nieuwerkerk-aan-den-ijssel", "capelle-aan-den-ijssel", "zoetermeer"],
        "lat": 52.011, "lon": 4.711,
    },
    {
        "slug": "pijnacker", "name": "Pijnacker-Nootdorp", "kind": "gemeente",
        "title": "Lachgas Pijnacker-Nootdorp | 24/7 via WhatsApp",
        "description": "Lachgas bestellen in Pijnacker-Nootdorp? Discreet bezorgd via WhatsApp in Pijnacker, Nootdorp en Delfgauw, van Klapwijk tot Keijzershof. 24/7, alleen 18+.",
        "h1": "Lachgas Pijnacker-Nootdorp",
        "lead": "Snel en discreet bezorgd in Pijnacker, Nootdorp en Delfgauw, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """De gemeente Pijnacker-Nootdorp ligt tussen Rotterdam, Delft, Den Haag en Zoetermeer en bestaat uit drie kernen die we alle drie bedienen. In Pijnacker bezorgen we lachgastanks in het centrum rond het Raadhuisplein, in Klapwijk, Koningshof, Tolhek, Keijzershof en Ackerswoude; in Nootdorp in het centrum, Craeyenburch, 's-Gravenhout en Vrouwtjeslant; in Delfgauw in het dorp en de wijk Emerald. Je stuurt een WhatsApp-bericht met je adres, de gewenste maat en het tijdstip, en wij bevestigen wanneer we er zijn.""",
            """Vanuit Rotterdam rijden we via de A13 en de N470 bij Delft de gemeente in, of vanaf Berkel en Rodenrijs via de N470 rechtstreeks naar Pijnacker; Nootdorp ligt vlak bij de A12 en het Prins Clausplein. Metrolijn E (RandstadRail) rijdt vanuit Rotterdam Centraal via Pijnacker Zuid en Pijnacker Centrum naar Nootdorp, dus de buurten rond die haltes kennen we goed. Omdat we net buiten Lansingerland de polders in moeten, duurt het iets langer dan in Berkel.""",
            """Een verjaardag in een nieuwbouwwoning in Keijzershof, een avond met vrienden in Craeyenburch of een tuinfeest in Delfgauw: kies via <a href="/lachgas-tanks/">lachgastanks</a> het formaat dat past, 2KG, 4KG of 10KG. Voor een 10KG tank overleggen we vooraf even over het tijdstip. De tank wordt verzegeld afgeleverd, je betaalt bij de deur, contant of via Tikkie, en we leveren alleen aan personen van 18 jaar en ouder. Neem vooraf de basisregels door op <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Pijnacker Centrum, Klapwijk, Koningshof, Tolhek, Keijzershof, Ackerswoude, Nootdorp Centrum, Craeyenburch, Delfgauw, Emerald",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie in alle drie de kernen van Pijnacker-Nootdorp?", "Ja, in Pijnacker, Nootdorp en Delfgauw, inclusief de nieuwbouw in Keijzershof, Tolhek en Emerald. Stuur je postcode mee in je WhatsApp-bericht, dan bevestigen we direct het levermoment."],
            ["Hoe snel zijn jullie in Pijnacker of Nootdorp?", "Meestal binnen 25 tot 40 minuten. Pijnacker ligt via de N470 dicht bij Berkel en Rodenrijs; Nootdorp aan de kant van Den Haag duurt soms een paar minuten langer. Je hoort vooraf via WhatsApp hoe laat we er zijn."],
            ["Kan ik ook laat op de avond bestellen in Pijnacker-Nootdorp?", """Ja, we zijn 24/7 bereikbaar via WhatsApp, ook na middernacht en in het weekend. Lees meer over <a href="/lachgas-nachtbezorging/">lachgas 's nachts</a>."""],
        ],
        "nearby": ["berkel-en-rodenrijs", "delft", "zoetermeer"],
        "lat": 52.019, "lon": 4.430,
    },
    {
        "slug": "bergschenhoek", "name": "Bergschenhoek", "kind": "dorp",
        "title": "Lachgas Bergschenhoek | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Bergschenhoek? Discreet bezorgd via WhatsApp in het Centrum, Boterdorp, Parkzoom en Wilderszijde. 24/7 bereikbaar, alleen voor 18+.",
        "h1": "Lachgas Bergschenhoek",
        "lead": "Snel en discreet bezorgd in Bergschenhoek, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Bergschenhoek is een van de drie kernen van Lansingerland en ligt direct boven Rotterdam Hillegersberg-Schiebroek, tegen de Rotte en het Hoge Bergse Bos aan. We bezorgen lachgastanks in het oude dorp rond de Dorpsstraat en de Bergweg, in Boterdorp, in Parkzoom aan de kant van Berkel en in de nieuwe wijk Wilderszijde op de grens met Rotterdam. Ook de lintbebouwing langs de Rottekade en de Hoeksekade nemen we mee. Je appt je adres, de maat en het tijdstip en wij bevestigen.""",
            """Vanuit Rotterdam-Noord rijden we via de Molenlaan en de Ankie Verbeek-Ohrlaan rechtstreeks Bergschenhoek binnen, of we komen via de N209 vanaf het Terbregseplein (A16 en A20). Bergschenhoek heeft geen eigen metro- of treinstation: de dichtstbijzijnde haltes van metro E liggen in Berkel en Rodenrijs, en station Rotterdam Alexander ligt een paar kilometer zuidelijker. Door de korte afstand tot Hillegersberg zijn we er meestal vlot, zeker buiten de spits.""",
            """Een verjaardag in een gezinswoning in Parkzoom, een avond met vrienden in Boterdorp of een tuinfeest aan de rand van de Rottemeren: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> in 2KG, 4KG en 10KG en kies wat bij je gezelschap past. Verzegeld bezorgd, afrekenen bij levering, contant of via Tikkie, en alleen voor personen van 18 jaar en ouder. Lees ook onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Bergschenhoek Centrum, Dorpsstraat, Boterdorp, Parkzoom, Wilderszijde, Rottekade, Hoeksekade, Hoge Bergse Bos",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe snel bezorgen jullie in Bergschenhoek?", "Meestal binnen 25 tot 40 minuten. Bergschenhoek grenst direct aan Hillegersberg, dus vanuit Rotterdam-Noord zijn we er vlot; in de spits op de N209 kan het iets langer duren. Je krijgt vooraf een eerlijke indicatie via WhatsApp."],
            ["Bezorgen jullie ook in Wilderszijde en Parkzoom?", "Ja, alle buurten van Bergschenhoek horen erbij, inclusief de nieuwbouw in Wilderszijde en Parkzoom en de lintbebouwing langs de Rotte. Stuur je postcode mee, dan bevestigen we direct."],
            ["Kan ik een tank bestellen voor een feest bij de Rottemeren?", """Ja, we bezorgen op elk woonadres in Bergschenhoek. Voor een groter feest is de 4KG of 10KG tank geschikt; lees eerst onze pagina <a href="/lachgas-feest-evenement/">feest en evenement</a> en houd rekening met de regels op openbare plekken."""],
        ],
        "nearby": ["hillegersberg-schiebroek", "berkel-en-rodenrijs", "bleiswijk"],
        "lat": 51.990, "lon": 4.500,
    },
    {
        "slug": "bleiswijk", "name": "Bleiswijk", "kind": "dorp",
        "title": "Lachgas Bleiswijk | 24/7 bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Bleiswijk? Snel en discreet bezorgd via WhatsApp in het dorp, langs de Hoefweg en bij de Rottemeren. 24/7 bereikbaar, alleen voor 18+.",
        "h1": "Lachgas Bleiswijk",
        "lead": "Snel en discreet bezorgd in Bleiswijk, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Bleiswijk is de noordelijkste kern van Lansingerland en ligt tussen de Rottemeren en de A12, midden in het glastuinbouwgebied richting Zoetermeer. We bezorgen lachgastanks in het dorp rond de Dorpsstraat en de Kerkstraat, in de woonbuurten aan de zuid- en westkant, langs de Hoefweg en de Hoeksekade en bij de recreatiegebieden Bleiswijkse Zoom en Rottemeren. Stuur een WhatsApp-bericht met je adres, de gewenste maat en het tijdstip; wij bevestigen en komen naar je toe.""",
            """Vanuit Rotterdam rijden we via de N209 door Bergschenhoek naar Bleiswijk, of via de A20 en de N219 bij Zevenhuizen; vanaf de A12 is er een eigen afslag Bleiswijk. Het dorp heeft geen station: de dichtstbijzijnde treinen stoppen in Zoetermeer en op Rotterdam Alexander, en metro E eindigt in Berkel en Rodenrijs. Omdat we vanaf Hillegersberg eerst door Bergschenhoek moeten, reken je in Bleiswijk op een paar minuten meer dan daar.""",
            """Een verjaardag in een rijtjeshuis aan de rand van het dorp, een avond met vrienden aan de Hoefweg of een feest in een woning bij de Rotte: op <a href="/lachgas-tanks/">lachgastanks</a> kies je tussen 2KG, 4KG en 10KG. We leveren verzegeld, je betaalt bij aflevering, contant of via Tikkie, en we bezorgen uitsluitend aan 18+. Bekijk vooraf ook onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Bleiswijk Centrum, Dorpsstraat, Kerkstraat, Hoefweg, Hoeksekade, Bleiswijkse Zoom, Rottemeren, Klappolder",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Bleiswijk?", "Meestal binnen 25 tot 40 minuten. Bleiswijk ligt aan de noordkant van Lansingerland, dus net iets verder dan Bergschenhoek en Berkel. Je hoort vooraf via WhatsApp hoe laat we er zijn."],
            ["Bezorgen jullie ook in het buitengebied van Bleiswijk?", "Ja, ook op adressen langs de Hoefweg, de Hoeksekade en bij de Rottemeren. Geef je volledige adres met postcode door, dan laten we direct weten hoe laat we er kunnen zijn."],
            ["Wat heb ik nodig om in Bleiswijk te bestellen?", """Je adres met postcode en huisnummer, de gewenste maat en het tijdstip, en een telefoon die bereikbaar is op WhatsApp als de bezorger eraan komt. De stappen staan op <a href="/werkwijze/">werkwijze</a>."""],
        ],
        "nearby": ["bergschenhoek", "berkel-en-rodenrijs", "zoetermeer"],
        "lat": 52.013, "lon": 4.531,
    },
    {
        "slug": "hendrik-ido-ambacht", "name": "Hendrik-Ido-Ambacht", "kind": "gemeente",
        "title": "Lachgas Hendrik-Ido-Ambacht | 24/7 via WhatsApp",
        "description": "Lachgas bestellen in Hendrik-Ido-Ambacht? Discreet bezorgd via WhatsApp in Centrum, De Volgerlanden, Kruiswiel en Sandeling. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Hendrik-Ido-Ambacht",
        "lead": "Snel en discreet bezorgd in Hendrik-Ido-Ambacht, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Hendrik-Ido-Ambacht ligt aan de rivier de Noord, tussen Ridderkerk en Zwijndrecht, en is de eerste van de Drechtsteden die je vanaf Rotterdam-Zuid tegenkomt. We bezorgen lachgastanks in het centrum rond winkelcentrum De Schoof en de Dorpsstraat, in Kruiswiel en Krommeweg, in Sandeling en de oude kern aan de Veersedijk en in de grote nieuwbouwwijk De Volgerlanden op de grens met Zwijndrecht. Je appt je adres, de maat en het gewenste tijdstip, wij bevestigen en komen langs.""",
            """Vanuit Rotterdam rijden we via de A16 over de Van Brienenoordbrug en voorbij knooppunt Ridderkerk de afslag Hendrik-Ido-Ambacht af, of vanaf IJsselmonde via de Rotterdamseweg en de Pruimendijk langs het Waalbos. Een treinstation is er niet; de Waterbus legt aan bij de halte Hendrik-Ido-Ambacht aan de Noord en station Zwijndrecht ligt net over de gemeentegrens. Door de ligging direct langs de A16 verschilt de bezorgtijd weinig van die in Ridderkerk.""",
            """Een verjaardag in een gezinswoning in De Volgerlanden, een avond met vrienden in Kruiswiel of een feest aan de dijk met uitzicht op de Noord: bekijk de <a href="/lachgas-tanks/">lachgastanks</a> in 2KG, 4KG en 10KG en kies het formaat dat bij je groep past. Afrekenen doe je bij aflevering, contant of via Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees voor je bestelt onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Centrum, De Schoof, Dorpsstraat, De Volgerlanden, Kruiswiel, Krommeweg, Sandeling, Veersedijk, Antoniapolder",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe snel bezorgen jullie in Hendrik-Ido-Ambacht?", "Meestal binnen 25 tot 40 minuten. De gemeente ligt direct langs de A16, vlak achter Ridderkerk, dus vanuit Rotterdam-Zuid zijn we er vlot. Je krijgt vooraf via WhatsApp een eerlijke indicatie van het tijdstip."],
            ["Bezorgen jullie ook in De Volgerlanden?", "Ja, De Volgerlanden hoort volledig bij ons bezorggebied, net als Kruiswiel, Sandeling en het centrum rond De Schoof. Stuur je postcode mee in je bericht en we bevestigen direct."],
            ["Hoe zit het met de leeftijdscontrole in Hendrik-Ido-Ambacht?", "We leveren overal, dus ook in Hendrik-Ido-Ambacht, uitsluitend aan personen van 18 jaar en ouder. Bij twijfel vraagt de bezorger aan de deur om een geldig identiteitsbewijs."],
        ],
        "nearby": ["zwijndrecht", "ridderkerk", "dordrecht"],
        "lat": 51.845, "lon": 4.640,
    },
    {
        "slug": "naaldwijk", "name": "Naaldwijk en Westland", "kind": "gemeente",
        "title": "Lachgas Naaldwijk en Westland | 24/7 via WhatsApp",
        "description": "Lachgas bestellen in Naaldwijk en Westland? Discreet bezorgd via WhatsApp in Naaldwijk, 's-Gravenzande, Monster, De Lier en Wateringen. 24/7, alleen 18+.",
        "h1": "Lachgas Naaldwijk en Westland",
        "lead": "Snel en discreet bezorgd in Naaldwijk en de andere kernen van Westland, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Naaldwijk is de grootste kern van de gemeente Westland, het kassengebied tussen Rotterdam, Delft, Den Haag en de kust. We bezorgen lachgastanks in Naaldwijk rond het Wilhelminaplein en de Herenstraat, in Hoogeland, Pijletuinen en Opstal, en in de andere Westlandse dorpen: 's-Gravenzande, Monster en Ter Heijde aan de kust, De Lier, Maasdijk, Honselersdijk, Kwintsheul, Poeldijk en Wateringen. Je stuurt via WhatsApp je adres, de gewenste maat en het tijdstip, en wij laten weten wanneer we er zijn.""",
            """Vanuit Rotterdam rijden we de A20 richting Hoek van Holland en gaan bij knooppunt Westerlee de N213 (Burgemeester Elsenweg) op naar Naaldwijk; Wateringen en Kwintsheul bereiken we sneller via de A4 en de N211. Westland heeft geen eigen treinstation en geen metro, dus alles gaat over de weg. De afstand tot Rotterdam-centrum is groter dan bij Maassluis of Vlaardingen, en daarom rekenen we in Westland op 35 tot 50 minuten.""",
            """Een verjaardag in een nieuwbouwwoning in Hoogeland, een avond met vrienden in 's-Gravenzande of een feest op een tuindersbedrijf bij De Lier: op <a href="/lachgas-tanks/">lachgastanks</a> zie je welk formaat past, 2KG, 4KG of 10KG. De tank komt verzegeld, je betaalt bij aflevering, contant of via Tikkie, en we leveren alleen aan volwassenen van 18 jaar en ouder. Lees vooraf ook de basisregels op <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Naaldwijk Centrum, Hoogeland, Pijletuinen, 's-Gravenzande, Monster, De Lier, Wateringen, Honselersdijk, Kwintsheul, Poeldijk",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie in heel Westland of alleen in Naaldwijk?", "In alle kernen van Westland: Naaldwijk, 's-Gravenzande, Monster, De Lier, Wateringen, Honselersdijk, Kwintsheul, Poeldijk en Maasdijk. Zet je postcode in je eerste bericht, dan weet je meteen hoe laat we er zijn."],
            ["Hoe lang duurt bezorgen in Naaldwijk?", "Meestal binnen 35 tot 50 minuten. We komen via de A20 en knooppunt Westerlee, en kernen aan de kust zoals Monster liggen nog iets verder. Je hoort vooraf via WhatsApp hoe laat we er zijn."],
            ["Kan ik in Westland ook 's nachts bestellen?", """Ja, we zijn 24/7 bereikbaar via WhatsApp, ook 's nachts en in het weekend. Houd wel rekening met de rijtijd vanuit Rotterdam. Lees meer op <a href="/lachgas-nachtbezorging/">lachgas 's nachts</a>."""],
        ],
        "nearby": ["maassluis", "hoek-van-holland", "delft"],
        "lat": 51.994, "lon": 4.209,
    },
    {
        "slug": "oud-beijerland", "name": "Oud-Beijerland", "kind": "stad",
        "title": "Lachgas Oud-Beijerland | Snel bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Oud-Beijerland? Discreet bezorgd via WhatsApp in Centrum, Zoomwijck, Croonenburgh en Poortwijk, Hoeksche Waard. 24/7 bereikbaar, 18+.",
        "h1": "Lachgas Oud-Beijerland",
        "lead": "Snel en discreet bezorgd in Oud-Beijerland, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Oud-Beijerland is de grootste plaats van de Hoeksche Waard en ligt aan het Spui, ten zuiden van Rotterdam en de Oude Maas. We bezorgen lachgastanks in het historische centrum rond de Molendijk, de Oostdijk en het Vierwiekenplein, in Zoomwijck en Croonenburgh, in de nieuwere wijk Poortwijk aan de zuidkant en bij de Spuioever langs het water. Een WhatsApp-bericht met je adres, de gewenste maat en het tijdstip is voldoende; wij bevestigen het levermoment en komen langs.""",
            """Vanuit Rotterdam-Zuid rijden we via het Vaanplein de A29 op, door de Heinenoordtunnel onder de Oude Maas en bij de afslag Oud-Beijerland via de N217 het stadje in. Een trein of metro is er niet; de bussen vanaf het busstation rijden naar Rotterdam Zuidplein en Spijkenisse. Door de tunnel en de afstand tot de stad zijn we in de Hoeksche Waard langer onderweg dan in Barendrecht of Rhoon; daarom rekenen we hier op 35 tot 50 minuten.""",
            """Een verjaardag in een dijkwoning aan de Oostdijk, een avond met vrienden in Zoomwijck of een feest in een nieuwbouwhuis in Poortwijk: kies via <a href="/lachgas-tanks/">lachgastanks</a> tussen 2KG, 4KG en 10KG. Alles wordt verzegeld geleverd, je rekent af bij de deur, contant of via Tikkie, en we bezorgen uitsluitend aan personen van 18 jaar en ouder. Lees vooraf onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Oud-Beijerland Centrum, Molendijk, Oostdijk, Vierwiekenplein, Zoomwijck, Croonenburgh, Poortwijk, Spuioever",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Oud-Beijerland?", "Meestal binnen 35 tot 50 minuten. We rijden vanuit Rotterdam via de A29 en de Heinenoordtunnel de Hoeksche Waard in, dus de rit is langer dan naar Barendrecht. Je krijgt vooraf via WhatsApp een eerlijke indicatie."],
            ["Bezorgen jullie ook in andere dorpen in de Hoeksche Waard?", "Oud-Beijerland is ons vaste gebied in de Hoeksche Waard. Woon je in Heinenoord, Puttershoek, Mijnsheerenland of Nieuw-Beijerland? Stuur je postcode via WhatsApp, dan laten we direct weten of bezorging mogelijk is."],
            ["Mag ik een lachgastank zelf meenemen in de auto vanuit Oud-Beijerland?", """Wij bezorgen aan huis, zodat je niet met een tank hoeft te rijden. Wil je een tank toch vervoeren, lees dan eerst <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">lachgas tank bewaren en vervoeren</a>; rijden onder invloed van lachgas is altijd verboden."""],
        ],
        "nearby": ["barendrecht", "rhoon", "hoogvliet"],
        "lat": 51.824, "lon": 4.411,
    },
]
