# -*- coding: utf-8 -*-
"""Gebiedspagina's lachgasrotterdam.nl, fase 2 (deel A): Maassluis, Delft, Zoetermeer,
Krimpen aan den IJssel, Nieuwerkerk aan den IJssel, Rhoon en Poortugaal, Hellevoetsluis, Brielle, Rozenburg.

Toegestane HTML in tekstvelden: strong en a (interne paden of drugsinfo.nl / rijksoverheid.nl / trimbos.nl).
"""

AREAS = [
    {
        "slug": "maassluis", "name": "Maassluis", "kind": "stad",
        "title": "Lachgas Maassluis | 24/7 bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Maassluis? Discreet bezorgd via WhatsApp, van de Binnenstad tot Steendijkpolder en Het Balkon. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Maassluis",
        "lead": "Lachgastanks aan huis bezorgd in Maassluis, geregeld via WhatsApp. Dag en nacht bereikbaar.",
        "intro": [
            """Maassluis is de laatste stad aan de noordoever van de Nieuwe Waterweg voordat het Westland begint, en het westelijkste punt van ons bezorggebied langs de A20. We brengen lachgastanks naar de Binnenstad rond de Grote Kerk en de Monsterse Sluis, naar Het Hoofd aan het water, Sluispolder-Oost en -West, Kapelpolder, de Burgemeesterswijk, Steendijkpolder en de nieuwere woonbuurten Het Balkon en Dijkpolder. Bestellen gaat via WhatsApp: je noemt je adres, de gewenste maat en wanneer het je past, en wij komen langs.""",
            """Vanuit Rotterdam volgen we de A20 richting Hoek van Holland, langs Schiedam en Vlaardingen, tot de afslag Maassluis. Komen we vanaf Rotterdam-Zuid, dan rijden we via de A15 en door de Maasdeltatunnel van de Blankenburgverbinding, die bij Vlaardingen op de A20 uitkomt. De Hoekse Lijn (metro B) stopt bij Maassluis, Maassluis Steendijkpolder en Maassluis West, dus ook die stationsbuurten kennen we. Door de ruim twintig kilometer vanaf het centrum van Rotterdam rekenen we meestal op 25 tot 40 minuten.""",
            """Voor een avond met vrienden in een appartement in Koningshoek, een huisfeest in Steendijkpolder of een verjaardag aan de Noorddijk bekijk je de <a href="/lachgas-tanks/">lachgastanks</a> in 2KG, 4KG en 10KG en kies je het formaat dat bij je gezelschap past. Het bedrag staat vooraf vast via WhatsApp en je rekent af bij de deur, contant of via Tikkie. We leveren alleen aan 18+ en raden je aan vooraf onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a> door te nemen.""",
        ],
        "wijken": "Binnenstad, Het Hoofd, Sluispolder-Oost, Sluispolder-West, Kapelpolder, Koningshoek, Burgemeesterswijk, Steendijkpolder, Het Balkon, Dijkpolder",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook in Het Balkon en Dijkpolder?", "Ja, ook de nieuwere buurten Het Balkon aan de Waterweg en Dijkpolder aan de noordkant van Maassluis horen bij ons bezorggebied. Vermeld je postcode in je bericht, dan bevestigen we meteen het tijdstip."],
            ["Hoe lang rijden jullie naar Maassluis?", "Vanuit Rotterdam is het via de A20 of de Blankenburgverbinding ruim twintig kilometer, dus meestal binnen 25 tot 40 minuten. Bij files rond Vlaardingen of drukte in het weekend geven we vooraf een eerlijke inschatting."],
            ["Kan ik vanuit Maassluis ook 's avonds laat bestellen?", """Zeker, WhatsApp is 24/7 bereikbaar en we bezorgen ook 's nachts in Maassluis. Hoe dat werkt lees je op <a href="/lachgas-nachtbezorging/">lachgas nachtbezorging</a>."""],
        ],
        "nearby": ["vlaardingen", "rozenburg", "hoek-van-holland"],
        "lat": 51.923, "lon": 4.250,
    },
    {
        "slug": "delft", "name": "Delft", "kind": "stad",
        "title": "Lachgas Delft | Snel en discreet bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Delft? Snel bezorgd via WhatsApp in de Binnenstad, Voorhof, Buitenhof, Tanthof en de TU-wijk. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Delft",
        "lead": "Lachgastanks bezorgd in heel Delft, van de grachten tot Tanthof. Bestellen via WhatsApp, 24/7.",
        "intro": [
            """Delft ligt een kwartier ten noorden van Rotterdam en is met de TU, de grachten en de vele studentenhuizen een stad waar we vaak komen. We bezorgen lachgastanks in de Binnenstad rond de Markt, de Beestenmarkt en de Oude Delft, in Vrijenban en Hof van Delft, in de hoogbouw van Voorhof en Buitenhof, in Tanthof aan de zuidkant, in de Wippolder en de TU-wijk en in de nieuwbouw van de Harnaschpolder. Via WhatsApp geef je je adres, het formaat en het gewenste tijdstip door en wij plannen de rit in.""",
            """Vanuit Rotterdam pakken we bij het Kleinpolderplein de A13 en nemen we de afslag Delft-Zuid, Delft of Delft-Noord, afhankelijk van de wijk; vanaf Schiedam en Zuid rijden we over de in 2015 doorgetrokken A4 en komen we bij Den Hoorn de stad in. Treinstation Delft ligt sinds de spoortunnel onder de Phoenixstraat, Delft Campus bedient de zuidkant, en tram 1 en 19 verbinden de stad met Den Haag. De rijtijd vanuit Rotterdam-centrum is kort, maar met het laden en de drukte op de A13 komt het meestal uit op 25 tot 40 minuten.""",
            """Een huisfeest in een studentenhuis aan de Oude Delft, een afstudeerborrel in de Wippolder of een verjaardag in een flat in Voorhof: op de pagina <a href="/lachgas-tanks/">lachgastanks</a> zie je wat de 2KG, 4KG en 10KG van elkaar verschillen. Elke tank komt verzegeld aan, de prijs krijg je vooraf bevestigd in WhatsApp en afrekenen doe je bij aflevering, contant of met Tikkie. We bezorgen uitsluitend aan volwassenen van 18 jaar en ouder; lees vooraf onze adviezen over <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Binnenstad, Vrijenban, Hof van Delft, Voordijkshoorn, Voorhof, Buitenhof, Tanthof, Wippolder, TU-wijk, Harnaschpolder",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie ook bij studentenhuizen op de TU-campus?", "Ja, we bezorgen in de Wippolder en de TU-wijk net zo goed als in de rest van Delft. Geef in WhatsApp wel een huisnummer en eventueel een toevoeging door, zodat we niet bij de verkeerde voordeur staan."],
            ["Welke route rijden jullie naar Delft en wat betekent dat voor de levertijd?", "Meestal via de A13 vanaf het Kleinpolderplein, soms via de A4 en Den Hoorn. Daardoor zijn we meestal binnen 25 tot 40 minuten bij je; bij spitsdrukte op de A13 geven we vooraf een eerlijke indicatie."],
            ["Kan ik voor een groot studentenfeest in Delft een 10KG tank bestellen?", """Dat kan. Voor een 10KG stemmen we het levermoment vooraf af en leveren we bij voorkeur op een vast adres waar iemand van 18+ aanwezig is. Meer lees je op <a href="/lachgas-feest-evenement/">lachgas voor feest en evenement</a>."""],
        ],
        "nearby": ["schiedam", "overschie", "pijnacker"],
        "lat": 52.012, "lon": 4.357,
    },
    {
        "slug": "zoetermeer", "name": "Zoetermeer", "kind": "stad",
        "title": "Lachgas Zoetermeer | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Zoetermeer? Discreet bezorgd via WhatsApp in Stadshart, Rokkeveen, Oosterheem en Meerzicht. 24/7 bereikbaar, uitsluitend 18+.",
        "h1": "Lachgas Zoetermeer",
        "lead": "Lachgastanks bezorgd in alle wijken van Zoetermeer, van Stadshart tot Oosterheem. Via WhatsApp, 24/7.",
        "intro": [
            """Zoetermeer is met zijn ruim 125.000 inwoners de grootste groeikern tussen Rotterdam en Den Haag en hoort bij de buitenring van ons bezorggebied. We leveren lachgastanks in het Stadshart en het oude Dorp langs de Dorpsstraat, in Palenstein en Driemanspolder, in Meerzicht, Buytenwegh en De Leyens, in Seghwaert en Noordhove, in Rokkeveen aan de zuidkant van de A12 en in het jonge Oosterheem. Een bericht op WhatsApp met je adres, het formaat en het tijdstip is genoeg om de bestelling te starten.""",
            """Vanuit Rotterdam rijden we over de N209 door Bergschenhoek en Bleiswijk naar de A12 bij Zoetermeer-Oost, of via de A13 en de N470 langs Pijnacker richting Rokkeveen. Zoetermeer heeft drie treinstations aan de lijn Den Haag-Gouda, Zoetermeer, Zoetermeer Oost en Lansingerland-Zoetermeer, en de RandstadRail-lijnen 3 en 4 maken een ring door de stad met haltes als Centrum-West, Stadhuis, Seghwaert en Javalaan. Omdat het vanaf Rotterdam-centrum zo'n 25 kilometer is, houden we meestal 35 tot 50 minuten aan.""",
            """Denk aan een housewarming in een nieuwbouwwoning in Oosterheem, een verjaardag in een flat in Meerzicht of een avond met vrienden in Rokkeveen: welke <a href="/lachgas-tanks/">lachgastank</a> je nodig hebt, 2KG, 4KG of 10KG, hangt af van de grootte van je groep. We leveren verzegeld, bevestigen het totaalbedrag vooraf via WhatsApp en je betaalt bij de deur, contant of met Tikkie. Bezorging is uitsluitend voor 18+; de belangrijkste punten over <a href="/veilig-gebruik/">veilig gebruik</a> lees je vooraf op onze site.""",
        ],
        "wijken": "Stadshart, Dorp, Palenstein, Meerzicht, Buytenwegh, De Leyens, Seghwaert, Noordhove, Rokkeveen, Oosterheem",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Waarom duurt bezorgen in Zoetermeer langer dan in Rotterdam?", "Zoetermeer ligt zo'n 25 kilometer van Rotterdam-centrum, via de N209 of de A13 en N470. Daarom rekenen we meestal op 35 tot 50 minuten; in de spits op de A12 of N209 kan het iets uitlopen en dat melden we vooraf."],
            ["Bezorgen jullie in heel Zoetermeer, ook in Oosterheem en Rokkeveen?", "Ja, in alle wijken, van Buytenwegh en De Leyens in het westen tot Oosterheem in het oosten en Rokkeveen ten zuiden van de A12. Stuur je postcode mee en we bevestigen direct."],
            ["Is lachgas bestellen in Zoetermeer toegestaan?", """Lachgas staat sinds 1 januari 2023 op lijst II van de Opiumwet; bezit en verkoop voor recreatief gebruik zijn verboden, met uitzonderingen voor onder meer technisch en voedingsgebruik. Lees de actuele regels op <a href="https://www.rijksoverheid.nl">rijksoverheid.nl</a> en op onze pagina over <a href="/lachgas-informatie/is-lachgas-legaal-in-nederland/">de wet</a>."""],
        ],
        "nearby": ["pijnacker", "bleiswijk", "berkel-en-rodenrijs"],
        "lat": 52.057, "lon": 4.493,
    },
    {
        "slug": "krimpen-aan-den-ijssel", "name": "Krimpen aan den IJssel", "kind": "gemeente",
        "title": "Lachgas Krimpen aan den IJssel | 24/7 via WhatsApp",
        "description": "Lachgas bestellen in Krimpen aan den IJssel? Discreet bezorgd via WhatsApp in Kortland, Langeland en Lansingh-Zuid. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Krimpen aan den IJssel",
        "lead": "Lachgastanks bezorgd in Krimpen aan den IJssel, aan de overkant van de Algerabrug. Bestellen via WhatsApp.",
        "intro": [
            """Krimpen aan den IJssel ligt op de punt van de Krimpenerwaard, waar de Hollandsche IJssel in de Nieuwe Maas stroomt, en is via de Algerabrug direct met Capelle verbonden. We bezorgen lachgastanks in het centrum rond winkelcentrum Crimpenhof, in Kortland, Langeland en Lansingh-Zuid, in Boveneind en Oud-Krimpen en op adressen richting de Stormpolder. Je appt ons je straat en huisnummer, de maat die je wilt en het tijdstip; wij laten weten wanneer we de brug over komen.""",
            """Vanuit Rotterdam-centrum rijden we via de Abram van Rijckevorselweg langs Capelsebrug naar de Algerabrug (N210), die naast de Hollandsche IJsselkering uit 1958 over de rivier gaat; vanaf Zuid komen we over de Van Brienenoordbrug en de A16. Krimpen heeft geen eigen metrostation: de bussen rijden naar Capelsebrug, waar metro A, B en C stoppen. De Algeracorridor is in de spits berucht om zijn files, en juist daarom houden we voor Krimpen meestal 25 tot 40 minuten aan.""",
            """Een verjaardag in een hoekwoning in Langeland, een avondje met vrienden in Lansingh-Zuid of een groter feest in Kortland: vergelijk de <a href="/lachgas-tanks/">lachgastanks</a> in 2KG, 4KG en 10KG en geef je keuze door. Het totaalbedrag krijg je vooraf in WhatsApp bevestigd, afrekenen gebeurt bij de voordeur, contant of met Tikkie, en we leveren uitsluitend aan personen van 18 jaar en ouder. Lees voor je bestelt ook onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Centrum, Crimpenhof, Kortland, Langeland, Lansingh-Zuid, Boveneind, Oud-Krimpen, Stormpolder",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Komen jullie wel over de Algerabrug als het druk is?", "Ja, we bezorgen in Krimpen aan den IJssel op elk moment van de dag. Omdat de Algeracorridor in de spits vaak vaststaat, geven we je vooraf via WhatsApp een eerlijke verwachting van de aankomsttijd."],
            ["Bezorgen jullie in alle wijken van Krimpen aan den IJssel?", "In de hele gemeente, van Oud-Krimpen en Boveneind langs de IJsseldijk tot Kortland, Langeland en Lansingh-Zuid. Vermeld je postcode in je bericht, dan bevestigen we direct het levermoment."],
            ["Hoe betaal ik mijn bestelling in Krimpen?", """Bij aflevering, contant of via Tikkie. Het bedrag staat van tevoren vast in WhatsApp, zodat er aan de deur geen discussie is. De volledige gang van zaken staat op onze pagina <a href="/werkwijze/">werkwijze</a>."""],
        ],
        "nearby": ["capelle-aan-den-ijssel", "prins-alexander", "ridderkerk"],
        "lat": 51.914, "lon": 4.602,
    },
    {
        "slug": "nieuwerkerk-aan-den-ijssel", "name": "Nieuwerkerk aan den IJssel", "kind": "dorp",
        "title": "Lachgas Nieuwerkerk aan den IJssel | Via WhatsApp",
        "description": "Lachgas bestellen in Nieuwerkerk aan den IJssel? Snel bezorgd via WhatsApp in Dorrestein, Zuidplas, Esse en Kortenoord. 24/7, alleen 18+.",
        "h1": "Lachgas Nieuwerkerk aan den IJssel",
        "lead": "Lachgastanks bezorgd in Nieuwerkerk aan den IJssel, vlak langs de A20. Bestellen via WhatsApp, ook 's nachts.",
        "intro": [
            """Nieuwerkerk aan den IJssel is de grootste kern van de gemeente Zuidplas en ligt tussen Rotterdam Nesselande en Gouda, pal aan de A20. Rond de Dorpsstraat en de 's-Gravenweg staat het oude dorp, daaromheen liggen Dorrestein, de wijk Zuidplas, Esse Hoog en Esse Laag, het nieuwere Esse-Zoom en Kortenoord bij het station, met winkelcentrum Reigerbos als middelpunt. Op al die adressen bezorgen we lachgastanks; je stuurt via WhatsApp je adres, het formaat en de gewenste tijd en wij bevestigen de rit.""",
            """Vanuit Rotterdam is het een rechte lijn: via de A20 richting Gouda nemen we de afslag Nieuwerkerk aan den IJssel en staan we binnen enkele minuten in het dorp. Vanuit Prins Alexander kunnen we ook door Zevenkamp en Nesselande langs de Zevenhuizerplas komen. Treinstation Nieuwerkerk a/d IJssel ligt aan de spoorlijn Rotterdam-Gouda en de eindhalte van metro B in Nesselande ligt op fietsafstand. De korte afstand tot Rotterdam-Oost maakt dat we meestal binnen 25 tot 40 minuten voor de deur staan.""",
            """Voor een feestje in een rijtjeshuis in Esse-Zoom, een verjaardag in Dorrestein of een tuinfeest aan de rand van recreatiegebied Hitland kies je op de pagina <a href="/lachgas-tanks/">lachgastanks</a> tussen 2KG, 4KG en 10KG. De tank komt verzegeld aan, de prijs is vooraf via WhatsApp bevestigd en je rekent af bij levering, contant of via Tikkie. We leveren alleen aan 18+ en vragen je om vooraf onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a> te lezen.""",
        ],
        "wijken": "Dorp, Dorrestein, Zuidplas, Esse Hoog, Esse Laag, Esse-Zoom, Kortenoord, Reigerbos",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe snel zijn jullie in Nieuwerkerk aan den IJssel?", "Meestal binnen 25 tot 40 minuten. Het dorp ligt direct aan de A20 en grenst aan Nesselande, dus de rijtijd vanuit Rotterdam-Oost is kort. Bij drukte op de A20 richting Gouda hoor je vooraf hoe laat we er zijn."],
            ["Bezorgen jullie ook in Esse-Zoom en bij het station in Kortenoord?", "Ja, in alle buurten van Nieuwerkerk, van het oude dorp langs de 's-Gravenweg tot de nieuwbouw in Esse-Zoom en Kortenoord. Een postcode in je WhatsApp-bericht is voldoende om het te bevestigen."],
            ["Hoe bewaar ik een tank als ik hem eerder laat bezorgen?", """Zet de verzegelde tank rechtop op een koele, droge plek buiten de zon en buiten bereik van kinderen. Onze pagina over <a href="/lachgas-informatie/lachgas-tank-bewaren-en-vervoeren/">bewaren en vervoeren</a> zet alles op een rij."""],
        ],
        "nearby": ["nesselande", "capelle-aan-den-ijssel", "gouda"],
        "lat": 51.967, "lon": 4.613,
    },
    {
        "slug": "rhoon", "name": "Rhoon en Poortugaal", "kind": "dorp",
        "title": "Lachgas Rhoon en Poortugaal | 24/7 via WhatsApp",
        "description": "Lachgas bestellen in Rhoon en Poortugaal? Discreet bezorgd via WhatsApp in Portland, Essendael, Ghijseland en Valckesteyn. 24/7, alleen 18+.",
        "h1": "Lachgas Rhoon en Poortugaal",
        "lead": "Lachgastanks bezorgd in Rhoon en Poortugaal, de dorpen van Albrandswaard. Via WhatsApp, dag en nacht.",
        "intro": [
            """Rhoon en Poortugaal vormen samen de gemeente Albrandswaard, ingeklemd tussen Rotterdam-Zuid, Hoogvliet, Barendrecht en de Oude Maas. We bezorgen lachgastanks in het oude Rhoon rond de Dorpsdijk en het kasteel, in Ghijseland bij het metrostation, in de nieuwbouw van Essendael en in Portland tegen Barendrecht aan, en in Poortugaal in het dorpscentrum en Valckesteyn. Stuur een WhatsApp-bericht met je adres, de maat van de tank en het tijdstip dat je het beste past; wij reageren met een bevestiging.""",
            """Vanaf Rotterdam-Zuid rijden we via de Groene Kruisweg vanuit Charlois rechtstreeks Rhoon en Poortugaal binnen, of we nemen de A15 en de afslag Rhoon. Beide dorpen hebben een eigen halte aan metrolijn D, tussen Slinge en Tussenwater, dus de buurten rond station Rhoon en station Poortugaal kennen we goed. Omdat het vanaf Zuidplein maar een paar kilometer is, blijft de levertijd beperkt tot meestal 25 tot 40 minuten, inclusief de tijd die we nodig hebben om de rit in te plannen.""",
            """Een verjaardag in een nieuwbouwwoning in Portland, een avond met vrienden in Essendael of een feest in een jarendertighuis aan de Albrandswaardsedijk: welke <a href="/lachgas-tanks/">lachgastank</a> past, 2KG, 4KG of 10KG, hangt af van je gezelschap. Levering gebeurt verzegeld, de prijs is vooraf via WhatsApp afgesproken en je betaalt bij aflevering, contant of met Tikkie. Alleen voor 18+; neem vooraf onze informatie over <a href="/veilig-gebruik/">veilig gebruik</a> door.""",
        ],
        "wijken": "Rhoon Dorp, Ghijseland, Essendael, Portland, Oud-Rhoon, Poortugaal Centrum, Valckesteyn, Albrandswaardsedijk",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Bezorgen jullie in zowel Rhoon als Poortugaal?", "Ja, in de hele gemeente Albrandswaard: Rhoon met Ghijseland, Essendael en Portland, en Poortugaal met het dorpscentrum en Valckesteyn. Stuur je postcode mee in WhatsApp en we bevestigen direct het levermoment."],
            ["Hoe snel zijn jullie in Rhoon of Poortugaal?", "Doorgaans binnen 25 tot 40 minuten. We komen via de Groene Kruisweg of de A15 vanaf Rotterdam-Zuid, een korte rit. In het weekend kan het iets drukker zijn; je krijgt vooraf een eerlijke indicatie."],
            ["Kan ik een tank meenemen naar een feest buiten Rhoon?", """Dat raden we af; laat de tank bij voorkeur bezorgen op het adres waar hij gebruikt wordt. Over vervoer en de regels onderweg lees je meer op <a href="/lachgas-informatie/lachgas-in-het-verkeer/">lachgas in het verkeer</a>."""],
        ],
        "nearby": ["hoogvliet", "barendrecht", "charlois"],
        "lat": 51.857, "lon": 4.422,
    },
    {
        "slug": "hellevoetsluis", "name": "Hellevoetsluis", "kind": "stad",
        "title": "Lachgas Hellevoetsluis | Bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Hellevoetsluis? Discreet bezorgd via WhatsApp in de Vesting, Den Bonsen Hoek, Nieuwenhoorn en Kooistee. 24/7 bereikbaar, 18+.",
        "h1": "Lachgas Hellevoetsluis",
        "lead": "Lachgastanks bezorgd in Hellevoetsluis aan het Haringvliet, geregeld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Hellevoetsluis ligt aan de zuidkant van Voorne-Putten, aan het Haringvliet, en is sinds 2023 onderdeel van de gemeente Voorne aan Zee. Het is een van de verste punten in ons bezorggebied, maar we komen er dagelijks. We bezorgen lachgastanks in de oude Vesting met het Droogdok Jan Blanken, in Den Bonsen Hoek, Nieuw-Helvoet, Nieuwenhoorn, Kooistee en Ravense Hoek, in De Struyten rond het winkelcentrum en in het dorp Oudenhoorn. Via WhatsApp deel je je adres, het formaat en het tijdstip, en wij bevestigen de rit.""",
            """Vanuit Rotterdam gaan we over de A15 door de Botlektunnel naar het Hartelkruis en vervolgens over de N57 langs Brielle naar Hellevoetsluis; een alternatief loopt via Spijkenisse en de Hartelbrug. Een eigen trein- of metrostation heeft de stad niet: de dichtstbijzijnde metro (lijn C en D) is Spijkenisse Centrum, waar de bussen naar Hellevoetsluis vertrekken. Door de ruim dertig kilometer vanaf Rotterdam-centrum en het havengebied onderweg rekenen we meestal op 35 tot 50 minuten.""",
            """Of je nu een feest geeft in een woning in Nieuwenhoorn, een verjaardag viert in De Struyten of een avond op een boot in de jachthaven plant: kies op de pagina <a href="/lachgas-tanks/">lachgastanks</a> tussen 2KG, 4KG en 10KG. Alles wordt verzegeld geleverd, met een vooraf in WhatsApp bevestigd bedrag dat je bij aflevering betaalt, contant of via Tikkie. We leveren alleen aan 18+ en raden je aan de pagina <a href="/veilig-gebruik/">veilig gebruik</a> vooraf te lezen.""",
        ],
        "wijken": "Vesting, Den Bonsen Hoek, Nieuw-Helvoet, Nieuwenhoorn, Kooistee, Ravense Hoek, De Struyten, Kickersbloem, Oudenhoorn",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Hoe lang duurt bezorgen in Hellevoetsluis?", "Meestal binnen 35 tot 50 minuten. De rit loopt via de A15, de Botlektunnel en de N57, en bij files in het Botlekgebied kan het uitlopen. We laten je vooraf via WhatsApp weten hoe laat we er ongeveer zijn."],
            ["Bezorgen jullie ook in Oudenhoorn en Nieuwenhoorn?", "Ja, we bezorgen in heel Hellevoetsluis, inclusief de dorpen Nieuwenhoorn en Oudenhoorn en de wijken rond de Vesting. Zet je postcode in je bericht, dan bevestigen we meteen."],
            ["Wat is het verschil tussen een 2KG en een 4KG tank voor een feest in Hellevoetsluis?", """De 4KG bevat twee keer zoveel lachgas als de 2KG en is bedoeld voor grotere gezelschappen; voor een klein groepje volstaat meestal de 2KG. Bekijk de <a href="/voordelen/">voordelen</a> van bestellen bij ons en vraag ons gerust om advies."""],
        ],
        "nearby": ["brielle", "spijkenisse", "hoogvliet"],
        "lat": 51.833, "lon": 4.133,
    },
    {
        "slug": "brielle", "name": "Brielle", "kind": "stad",
        "title": "Lachgas Brielle | Discreet bezorgd via WhatsApp",
        "description": "Lachgas bestellen in Brielle? Snel en discreet bezorgd via WhatsApp in de Vesting, Rugge, Meeuwenoord en Zuurland. 24/7 bereikbaar, alleen 18+.",
        "h1": "Lachgas Brielle",
        "lead": "Lachgastanks bezorgd in vestingstad Brielle en omliggende dorpen, besteld via WhatsApp. 24/7 bereikbaar.",
        "intro": [
            """Brielle, de vestingstad van 1 april 1572, ligt aan het Brielse Meer op het westelijke deel van Voorne-Putten en maakt sinds 2023 deel uit van de gemeente Voorne aan Zee. We bezorgen lachgastanks binnen de wallen rond de Sint-Catharijnekerk en de Markt, en in de woonwijken buiten de vesting: Rugge, Meeuwenoord, Nieuwland en Zuurland. Ook de dorpen Vierpolders en Zwartewaal nemen we mee. Je appt je adres, de gewenste maat en het tijdstip en krijgt van ons een bevestiging terug.""",
            """De rit vanuit Rotterdam loopt via de A15 door de Botlektunnel naar het Hartelkruis, waar we de N57 nemen en bij Brielle afslaan; vanaf Spijkenisse kunnen we ook over de N218 langs het Hartelkanaal komen. Brielle heeft geen station, de bussen naar Spijkenisse Centrum (metro C en D) zijn de OV-verbinding met de stad. Het is ruim 25 kilometer vanaf Rotterdam-centrum met het havengebied onderweg, daarom rekenen we voor Brielle meestal op 35 tot 50 minuten.""",
            """Een verjaardag in een grachtenpand aan het Maarland, een huisfeest in Rugge of een avond met vrienden bij het Brielse Meer: welke <a href="/lachgas-tanks/">lachgastank</a> je kiest, 2KG, 4KG of 10KG, bepaal je op basis van het aantal mensen. We leveren verzegeld, bevestigen het bedrag vooraf in WhatsApp en je rekent af bij de deur, contant of met Tikkie. Levering is uitsluitend voor 18+; onze pagina over <a href="/veilig-gebruik/">veilig gebruik</a> lees je het liefst vooraf.""",
        ],
        "wijken": "Vesting, Rugge, Meeuwenoord, Nieuwland, Zuurland, Vierpolders, Zwartewaal, Brielse Meer",
        "levertijd": "meestal binnen 35 tot 50 minuten",
        "faq": [
            ["Bezorgen jullie ook in Vierpolders en Zwartewaal?", "Ja, naast Brielle zelf bezorgen we ook in Vierpolders en Zwartewaal. Omdat die dorpen net buiten de stad liggen, kan de levertijd iets afwijken; stuur je postcode mee en we geven direct een inschatting."],
            ["Hoe lang moet ik wachten op een bestelling in Brielle?", "Reken op meestal 35 tot 50 minuten. We rijden via de A15, de Botlektunnel en de N57, en in de spits of bij werkzaamheden in het Botlekgebied kan het wat langer duren. Je hoort het vooraf via WhatsApp."],
            ["Kan ik lachgas bestellen voor een feest in de binnenstad van Brielle?", """Ja, we bezorgen ook binnen de vesting; geef bij smalle straten of een pand zonder parkeerplek even aan waar we het beste kunnen stoppen. Voor grotere groepen lees je meer op <a href="/lachgas-feest-evenement/">feest en evenement</a>."""],
        ],
        "nearby": ["hellevoetsluis", "rozenburg", "spijkenisse"],
        "lat": 51.902, "lon": 4.164,
    },
    {
        "slug": "rozenburg", "name": "Rozenburg", "kind": "dorp",
        "title": "Lachgas Rozenburg | Snel bezorgd via WhatsApp, 24/7",
        "description": "Lachgas bestellen in Rozenburg? Snel en discreet bezorgd via WhatsApp, van het Raadhuisplein tot Blankenburg. 24/7 bereikbaar, uitsluitend 18+.",
        "h1": "Lachgas Rozenburg",
        "lead": "Lachgastanks bezorgd in Rozenburg, tussen Nieuwe Waterweg en Calandkanaal. Besteld via WhatsApp, elk uur van de dag.",
        "intro": [
            """Rozenburg is een dorp op een eiland tussen de Nieuwe Waterweg en het Calandkanaal, omringd door de Botlek en Europoort, en sinds 2010 een gebied van de gemeente Rotterdam. We bezorgen lachgastanks in het centrum rond het Raadhuisplein, langs de Laan van Nieuw Blankenburg en de Molenweg, in de buurten richting de Boulevard aan het water en in Blankenburg aan de oostkant. Stuur ons via WhatsApp je adres, het gewenste formaat en een tijdstip, dan plannen we de rit over het havengebied in.""",
            """Rozenburg was lang alleen via de A15 en de Botlektunnel of Botlekbrug te bereiken, met daarna de afslag Rozenburg. Via de Blankenburgverbinding kunnen we ook vanaf de A20 bij Vlaardingen door de Maasdeltatunnel komen, die vlak bij het dorp op de A15 aansluit. Voor voetgangers en fietsers vaart het veer naar Maassluis, waar de Hoekse Lijn (metro B) stopt. Met het havenverkeer rond de Botlek erbij komen we meestal binnen 25 tot 40 minuten aan.""",
            """Een verjaardag in een rijtjeshuis aan de Laan van Nieuw Blankenburg, een avond met vrienden bij de Boulevard of een feestje na een wandeling over de Landtong: op de pagina <a href="/lachgas-tanks/">lachgastanks</a> vind je de 2KG, 4KG en 10KG naast elkaar. De tank komt verzegeld aan, het bedrag is vooraf via WhatsApp vastgelegd en je betaalt bij levering, contant of via Tikkie. Alleen voor 18+; lees vooraf ook onze tips voor <a href="/veilig-gebruik/">veilig gebruik</a>.""",
        ],
        "wijken": "Rozenburg Centrum, Raadhuisplein, Laan van Nieuw Blankenburg, Molenweg, Blankenburg, Boulevard, Landtong Rozenburg",
        "levertijd": "meestal binnen 25 tot 40 minuten",
        "faq": [
            ["Hoe komen jullie in Rozenburg, via de Botlek of de Maasdeltatunnel?", "Dat hangt af van waar onze bezorger op dat moment is: vanaf Zuid via de A15 en de Botlektunnel, vanaf Rotterdam-West via de A20 en de Maasdeltatunnel van de Blankenburgverbinding. Beide routes komen meestal uit op 25 tot 40 minuten."],
            ["Bezorgen jullie ook bij het veer naar Maassluis?", "Ja, we bezorgen op elk woonadres in Rozenburg, ook in de buurten bij de Boulevard en de veerstoep. Geef in WhatsApp je adres en postcode door, dan bevestigen we het levermoment."],
            ["Kunnen jullie 's nachts in Rozenburg bezorgen?", """Ja, we zijn via WhatsApp 24/7 bereikbaar en bezorgen ook 's nachts in Rozenburg, bijvoorbeeld na een avond uit. Meer hierover lees je op <a href="/lachgas-nachtbezorging/">lachgas nachtbezorging</a>."""],
        ],
        "nearby": ["maassluis", "brielle", "hoogvliet"],
        "lat": 51.904, "lon": 4.249,
    },
]
